#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank: math topics (fresh for batch G)."""


def register(T):
    T["matrix multiplication and what it represents"] = {
        "_cat": "math",
        "what": "a binary operation that takes an m-by-n matrix A and an n-by-p matrix B and produces an m-by-p matrix C whose entries are dot products of rows of A with columns of B, encoding the composition of two linear maps",
        "how": "to compute C = AB, the entry C[i][j] is the sum over k of A[i][k] times B[k][j]. Each row of C is a linear combination of rows of B weighted by the corresponding row of A; equivalently each column of C is a linear combination of columns of A weighted by the column of B. Because matrices represent linear maps, multiplication corresponds to applying B first then A, so order matters and AB usually does not equal BA",
        "why": "matrix multiplication is the workhorse of linear algebra and underlies computer graphics transformations, neural network forward passes, solving linear systems, Markov chain evolution, and quantum-state propagation. Modern hardware (GPUs, TPUs) is shaped around making it as fast as possible",
        "vs": "matrix multiplication differs from elementwise (Hadamard) multiplication, which is commutative and operates entry by entry, and from scalar multiplication, which scales every entry by one number. It differs from the cross product, which is defined only for 3-vectors and has different algebraic properties",
        "ex": "rotating a 2D point by angle theta multiplies the column vector [x, y]^T by the rotation matrix [[cos t, -sin t], [sin t, cos t]]. Composing two rotations corresponds to multiplying their matrices, and the result is itself a rotation matrix for the summed angles",
        "mis": "people assume matrix multiplication is commutative because regular multiplication is. AB and BA are usually different and may not even both be defined. Another myth is that the standard O(n^3) algorithm is optimal; Strassen's 1969 algorithm runs in O(n^2.81) and the current asymptotic record is below O(n^2.372), though such fast algorithms have impractical constants",
    }

    T["the integral as area under a curve"] = {
        "_cat": "math",
        "what": "the definite integral of a function f from a to b is the signed area between the curve y = f(x) and the x-axis, formally defined as the limit of Riemann sums of f sampled over partitions of [a, b] as the partition refines",
        "how": "split [a, b] into n subintervals, choose a sample point in each, multiply f at that point by the subinterval width, and sum. As n grows and widths shrink to zero, the sum converges to the integral for continuous functions. The fundamental theorem of calculus connects this geometric construction to antidifferentiation: if F is an antiderivative of f, then the integral from a to b equals F(b) - F(a)",
        "why": "integrals compute distances from velocity, work from force, total mass from density, expected values in probability, areas, volumes, and arc lengths. They are everywhere a quantity is the accumulated effect of a varying rate, which is essentially every applied science",
        "vs": "integrals differ from derivatives, which give instantaneous rates rather than accumulated totals; the two are inverses by the fundamental theorem. Definite integrals (a number) differ from indefinite integrals (a family of antiderivatives). Lebesgue integrals generalize Riemann's by integrating over more general sets and pathological functions",
        "ex": "a car accelerating from 0 to 30 m/s with velocity v(t) = 3t covers distance equal to the integral of v from 0 to 10, which is (3/2) t^2 from 0 to 10, yielding 150 meters. The triangular area under the velocity-time graph matches the integral exactly",
        "mis": "people think integrals always exist. Many functions are not Riemann-integrable (the indicator of the rationals on [0, 1] is the textbook example, though it is Lebesgue-integrable). Another myth is that integration is just antidifferentiation; the limit-of-sums definition is what gives integrals their geometric and physical meaning, with antidifferentiation as a computational shortcut",
    }

    T["graphs and graph traversal"] = {
        "_cat": "math",
        "what": "a graph is a set of vertices connected by edges, used to model relationships between objects; traversal is the process of visiting vertices in a systematic order, typically by breadth-first or depth-first search",
        "how": "in BFS, you maintain a queue of vertices to visit, dequeue the next vertex, mark it visited, and enqueue its unvisited neighbors. This explores in waves of distance from the start. In DFS, you use a stack (or recursion), going as deep as possible before backtracking. Both run in O(V + E) time given an adjacency-list representation. Variants underlie shortest-path (Dijkstra), connectivity, topological sort, and cycle detection",
        "why": "graphs model road networks, social ties, web links, biological pathways, dependency chains, and circuit layouts. Traversal is the foundation of routing, recommendation, compiler optimization, and almost any algorithm that asks 'what is reachable from here'",
        "vs": "graphs differ from trees, which are connected acyclic graphs and have unique paths between any two vertices. Directed graphs differ from undirected ones in that edges have orientation, and weighted graphs add numerical labels to edges. BFS differs from DFS in giving shortest paths in unweighted graphs, where DFS does not",
        "ex": "Facebook's friend recommendation runs BFS on the social graph to find friends-of-friends. LinkedIn's degree-of-connection display ('1st', '2nd', '3rd') is BFS made visible in the UI. Google's web crawler is essentially a massive BFS over hyperlinks",
        "mis": "people think DFS finds shortest paths. It does not, in general. Another myth is that graphs need explicit edge lists; many problems are solved on implicit graphs (like game-state graphs in chess) where edges are generated on the fly during traversal",
    }

    T["the law of large numbers"] = {
        "_cat": "math",
        "what": "the principle that as the number of independent trials of a random experiment grows, the average of the observed outcomes converges to the expected value, justifying the intuition that averages 'settle down' with more data",
        "how": "if X1, X2, ..., Xn are independent draws from a distribution with finite mean mu, the sample average (X1 + ... + Xn)/n converges to mu. The weak law states convergence in probability; the strong law states convergence with probability one. The argument uses Chebyshev's inequality (variance shrinks as 1/n) for the weak law and the Borel-Cantelli lemma for the strong",
        "why": "the law underwrites Monte Carlo simulation, sampling-based estimation in statistics, the operation of casinos and insurance, and the intuition behind A/B testing. Whenever you average many measurements to estimate a true value, you are leaning on this law",
        "vs": "the law of large numbers differs from the central limit theorem, which describes the shape of fluctuations around the mean rather than just convergence of the mean. It differs from the gambler's fallacy, which mistakenly applies it to short-term outcomes; the law operates only in the limit, not for individual sequences",
        "ex": "flipping a fair coin a million times almost certainly produces a fraction of heads within 0.1 percent of 0.5. After only ten flips, the fraction can easily be 0.3 or 0.7; convergence is real but slow, with deviations shrinking as one over the square root of n",
        "mis": "people think a long streak of one outcome makes the other 'due'. The law is asymptotic and does not correct local imbalances; coins have no memory. Another myth is that the law guarantees the average will hit exactly the mean; it only guarantees convergence in the limit, with arbitrarily small deviations that vanish in the long run",
    }

    T["complex numbers and the unit circle"] = {
        "_cat": "math",
        "what": "complex numbers extend the real numbers by adjoining i, the square root of -1, so every number has the form a + bi for real a and b; the unit circle is the set of complex numbers with absolute value 1, parameterized as e^(i theta) for real theta",
        "how": "addition combines real and imaginary parts separately. Multiplication uses i^2 = -1 and distributes; geometrically, multiplying by re^(i theta) scales by r and rotates by theta. Euler's formula e^(i theta) = cos theta + i sin theta connects the exponential to circular motion. Complex conjugates pair a + bi with a - bi; the modulus squared equals z times its conjugate",
        "why": "complex numbers make polynomial roots easy (every degree-n polynomial has n roots over the complex numbers), unify trigonometric identities, underlie alternating-current analysis, are essential for quantum mechanics, and power Fourier transforms used in signal processing, image compression, and physics",
        "vs": "complex numbers differ from 2D vectors in having a defined multiplication that mixes coordinates, and from quaternions, which extend complex numbers to four dimensions and lose commutativity. The unit circle differs from the real interval [-1, 1], although it projects onto it",
        "ex": "the equation e^(i pi) + 1 = 0, called Euler's identity, uses the unit circle to connect five fundamental constants (0, 1, e, pi, i) in a single relation. It is a special case of Euler's formula at theta = pi, where the exponential lands at -1 on the unit circle",
        "mis": "people think complex numbers are imaginary in the colloquial sense of unreal. They are as real as negative numbers; both are abstractions that emerged because real-world problems demanded them. Another myth is that complex analysis is exotic; it is the foundation of practical engineering disciplines like electrical engineering and control theory",
    }

    T["the pigeonhole principle"] = {
        "_cat": "math",
        "what": "a counting principle that asserts if n + 1 objects are distributed among n boxes, at least one box must contain at least two objects, with generalizations stating that distributing kn + 1 objects forces some box to hold at least k + 1",
        "how": "the proof is by contradiction: if every box held at most one object, the total would be at most n, contradicting the assumption of n + 1 objects. The principle generalizes to fractional and average forms (average box content forces at least one box to hold at least the ceiling of the average) and to infinite settings via the principle that an infinite set distributed into finitely many boxes has at least one infinite box",
        "why": "despite its simplicity, the principle proves nontrivial existence theorems: that any group of 13 people contains two with the same birth month, that some pair in any 6-person group shares a mutual relationship of friend or stranger (Ramsey theory's seed), and that sufficiently long strings must contain repeating patterns. It is a workhorse of combinatorics and computer science",
        "vs": "the pigeonhole principle differs from probabilistic existence arguments, which show typical objects exist but pigeonhole shows guaranteed existence under counting alone. It differs from constructive proofs, which build the object explicitly; pigeonhole arguments often only prove existence without locating the example",
        "ex": "in any group of 367 people at least two share a birthday, by pigeonhole on 366 possible birthdays. The probabilistic birthday paradox sharpens this: in just 23 people there is already a 50 percent chance of a shared birthday, but pigeonhole only guarantees certainty at 367",
        "mis": "people think pigeonhole gives constructive procedures. It usually only proves something exists without telling you which box it is in. Another myth is that the principle is trivial; its non-obvious applications (Ramsey theory, the Chinese remainder theorem, lossless compression bounds) are deep and surprising",
    }

    T["graph coloring and the four color theorem"] = {
        "_cat": "math",
        "what": "a coloring of a graph is an assignment of colors to vertices such that no edge connects two vertices of the same color; the four color theorem states that the regions of any planar map can be colored with at most four colors so adjacent regions get different colors",
        "how": "the chromatic number is the minimum number of colors needed. For planar graphs, Appel and Haken's 1976 proof showed four colors always suffice via a computer-assisted reduction to checking 1936 unavoidable configurations, later simplified by Robertson, Sanders, Seymour, and Thomas to 633 configurations. The proof works by showing every planar graph contains at least one of these configurations, each of which is reducible (a four-coloring of the rest extends to one for the whole)",
        "why": "graph coloring models scheduling (no two conflicting tasks at the same time), register allocation in compilers, frequency assignment in cellular networks, and Sudoku solving. The four color theorem also marks a turning point: the first major mathematical theorem proved with substantial computer assistance, prompting debates about what counts as proof",
        "vs": "graph coloring differs from edge coloring (assigning colors to edges so no two edges sharing a vertex match) and from list coloring (each vertex has a personal allowed list). The four color theorem is special to planar graphs; non-planar graphs can require arbitrarily many colors, like complete graphs K_n requiring n",
        "ex": "the United States map can be colored with four colors so no two states sharing a border have the same color, despite over 100 borders. Try with three colors and you fail (three states can meet at a single point or form an odd cycle), but four always work",
        "mis": "people think the four color theorem applies to any map, including ones with disconnected regions for one country (like Alaska and the continental US). The theorem assumes simply-connected regions; multi-region 'countries' may require more colors. Another myth is that the proof is suspect because it uses computers; the logic has since been verified mechanically by formal proof assistants",
    }

    T["the geometry of conic sections"] = {
        "_cat": "math",
        "what": "the family of curves obtained by intersecting a plane with a double cone, comprising circles, ellipses, parabolas, and hyperbolas, each with characteristic algebraic equations and reflective properties used in optics, orbits, and engineering",
        "how": "a conic is the locus of points whose distances to a focus and a directrix line are in fixed ratio (the eccentricity e). e = 0 gives a circle, 0 < e < 1 an ellipse, e = 1 a parabola, e > 1 a hyperbola. Algebraically, all conics satisfy a degree-2 equation in x and y; the discriminant of the quadratic form classifies them. They share elegant reflective properties: ellipses reflect from one focus to the other; parabolas reflect parallel rays to a single focus; hyperbolas reflect rays as if from one focus to diverge from the other",
        "why": "conic sections describe planetary orbits (Kepler), satellite trajectories, parabolic mirrors and antenna dishes, whispering galleries, and projectile paths in idealized gravity. They are the simplest non-trivial curves and the foundation of analytic geometry, supplying a vocabulary that physics and engineering still use daily",
        "vs": "conic sections differ from higher-degree curves (cubic, quartic) in being fully classified up to projective transformation by a single eccentricity parameter; from spirals and transcendental curves in being algebraic; and from curves on surfaces of negative curvature, which require non-Euclidean geometry. The unified projective description treats all conics as equivalent under the projective group, despite their different metric appearances",
        "ex": "a parabolic satellite dish reflects parallel signals from a distant transmitter to its single focal point, where the LNB sits. The same geometry concentrates sunlight in a parabolic solar cooker. The reflective property follows directly from the calculus of the parabola y = x^2 and underlies billions of dollars of installed antenna and optics infrastructure",
        "mis": "people think conics are exotic. They appear in elementary physics (projectile motion is parabolic in idealized gravity, planetary orbits are elliptical) and basic engineering. Another myth is that the conics are different curves; in projective geometry they are all instances of a single family related by projective transformations",
    }

    T["combinatorial counting (permutations and combinations)"] = {
        "_cat": "math",
        "what": "the branch of discrete mathematics concerned with counting arrangements of objects: permutations count ordered arrangements, combinations count unordered subsets, with formulas P(n,k) = n!/(n-k)! and C(n,k) = n!/(k!(n-k)!)",
        "how": "the multiplication principle says that if a process has independent stages with a, b, c choices, the total count is a*b*c. Permutations of n objects taken k at a time arise when order matters (P(n,k) = n!/(n-k)!). Combinations arise when only the chosen subset matters (C(n,k)). For arrangements with repetition or constraints, more refined methods (inclusion-exclusion, generating functions, recursion) apply. Pascal's triangle organizes binomial coefficients C(n,k) in a familiar grid",
        "why": "counting underwrites probability, statistics, algorithm analysis, and combinatorial design. Anywhere outcomes need to be enumerated (poker hands, lottery odds, scheduling possibilities, dice probabilities, password strength), counting techniques apply. Bad counting produces wrong probabilities and bad decisions",
        "vs": "permutations differ from combinations in caring about order; for the same n and k, P(n,k) = k! * C(n,k). They differ from arrangements with repetition (n^k for ordered selection with replacement). The binomial coefficient differs from the multinomial, which counts distributions of objects into multiple categories. Generating functions differ from direct counting in encoding count sequences as polynomial coefficients for systematic manipulation",
        "ex": "a five-card poker hand has C(52,5) = 2598960 possible deals. The number of full houses is 13 * C(4,3) * 12 * C(4,2) = 3744, giving the probability of a full house as 3744 / 2598960, about 0.144 percent. Every poker probability follows from counting, with no calculus needed",
        "mis": "people confuse permutations and combinations routinely, especially in probability problems. Whether order matters is the operative question. Another myth is that all counting problems have closed-form formulas; many require recursion or generating functions, and some (counting prime knots, for example) are open research problems",
    }

    T["bayesian inference"] = {
        "_cat": "math",
        "what": "a framework for updating probabilities in light of evidence by combining a prior probability for a hypothesis with the likelihood of observed data under that hypothesis, yielding a posterior probability via Bayes' theorem",
        "how": "Bayes' theorem says posterior is proportional to prior times likelihood. Start with a prior distribution over parameters reflecting belief before seeing data. Compute the likelihood of the observed data for each parameter value. Multiply, normalize, and obtain the posterior. As more data arrive, update by treating the previous posterior as the new prior. Modern Bayesian computation uses Markov chain Monte Carlo or variational inference to approximate posteriors that lack closed forms",
        "why": "Bayesian inference handles small data, prior knowledge, and uncertainty quantification gracefully, underlies medical diagnostic test interpretation, spam filtering, search ranking, and scientific updating. It is the dominant framework in modern probabilistic machine learning and a coherent theory of belief revision",
        "vs": "Bayesian inference differs from frequentist inference, which treats parameters as fixed unknowns and reasons about the long-run frequency properties of estimators rather than posterior probabilities. Both can answer similar questions but with different philosophical bases; in practice they often agree on point estimates but disagree on uncertainty interpretation",
        "ex": "consider a disease with 1 percent prevalence and a test 99 percent accurate in both directions. A positive test has only about 50 percent posterior probability of disease, a counterintuitive result that follows immediately from Bayes' theorem and explains why screening healthy populations for rare conditions can produce more false positives than true ones",
        "mis": "people think the posterior depends only on the data, ignoring the prior. Two analysts with different priors can rationally reach different posteriors from the same data; with enough data, priors usually wash out, but for small samples they matter. Another myth is that Bayes is 'subjective' and frequentism 'objective'; both involve modeling choices, and Bayesian analysis can use objective priors derived from invariance arguments",
    }
