#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Part 2: more science entries for gen_knowledge_09_3_A.py."""


def register_part_2(r):
    # ---- hydrogen bonding ----
    r("hydrogen bonding", "mechanism",
      "Hydrogen bonding is an electrostatic attraction between a hydrogen atom covalently bonded to a highly electronegative atom (typically nitrogen, oxygen, or fluorine) and a lone pair of electrons on another electronegative atom. The mechanism rests on the fact that when hydrogen is bonded to N, O, or F, the much greater electronegativity of those atoms pulls the shared bonding electrons strongly away from hydrogen, leaving the hydrogen with a substantial partial positive charge and the heavy atom with a partial negative charge. The exposed proton, with no inner electrons to shield it, can approach a lone pair on a nearby electronegative atom much more closely than other partial charges could, producing a stronger interaction than ordinary dipole-dipole forces. The geometry tends to be linear (donor-H...acceptor angle near 180 degrees) because that orientation maximizes the electrostatic attraction. Hydrogen bonds are typically about 5-30 kJ/mol, weaker than covalent bonds (a few hundred kJ/mol) but strong enough to dominate intermolecular structure in water, alcohols, amines, and biomolecules.")
    r("hydrogen bonding", "comparison",
      "Hydrogen bonds differ from covalent bonds in being roughly an order of magnitude weaker and largely electrostatic in character rather than involving substantial electron sharing. They differ from ordinary dipole-dipole interactions by being directional and stronger, due to the small size of the bare-proton hydrogen and the close approach it permits. They differ from London dispersion forces, which arise from instantaneous fluctuating dipoles in any molecule, in being much stronger and dependent on the specific donor-acceptor chemistry rather than on molecular polarizability. Compared with ionic bonds, which involve full charges, hydrogen bonds involve partial charges and so are much weaker but more directional. Compared with halogen bonds, which involve a halogen atom (rather than hydrogen) and a Lewis base, hydrogen bonds are typically stronger and more common. Among intermolecular forces, hydrogen bonds occupy a special middle ground: weak enough to be reversible at room temperature, strong enough to organize entire molecular structures.")

    # ---- solubility and saturation ----
    r("solubility and saturation", "mechanism",
      "Solubility arises from a competition between the energy required to break solute-solute and solvent-solvent interactions and the energy released when new solute-solvent interactions form, with entropy also favoring mixing in most cases. When sugar dissolves in water, water molecules surround each sugar molecule and form hydrogen bonds with its hydroxyl groups, releasing energy that pays for breaking the sugar-sugar interactions in the crystal. Salt dissolves in water because the high dielectric constant of water and the ion-dipole interactions between water and the sodium and chloride ions pay back most of the lattice energy. Saturation is reached when the chemical potential of the dissolved solute equals that of the undissolved solid, so the rates of dissolving and crystallizing become equal and no net change occurs. Adding more solute beyond this point leaves it sitting at the bottom of the container. Temperature usually shifts the saturation point because solubility is sensitive to the enthalpy of solution.")
    r("solubility and saturation", "comparison",
      "Saturated, unsaturated, and supersaturated solutions differ in how the dissolved amount compares to the equilibrium solubility limit. An unsaturated solution holds less solute than the limit and can dissolve more if added. A saturated solution holds exactly the limit and is in equilibrium with undissolved solid; adding more produces no net dissolution. A supersaturated solution holds more than the limit, a metastable state created by, for example, dissolving a salt in hot water and slowly cooling without disturbance. Supersaturated solutions are unstable and crystallize rapidly when seeded with a tiny solid crystal or disturbed mechanically, releasing the excess solute. These differ from concentrated solutions, a vague term meaning a high mass fraction of solute regardless of saturation. They also differ from suspensions and colloids, which involve particles too large to be truly dissolved and remain dispersed by Brownian motion or stabilizing surfactants.")
    r("solubility and saturation", "example",
      "A vivid example is the supersaturated sodium acetate hand warmer. Sodium acetate trihydrate dissolves readily in hot water; if the hot solution is sealed and slowly cooled to room temperature without disturbance, the solution becomes supersaturated because the equilibrium solubility at room temperature is lower than the dissolved concentration. The metastable solution stays clear until a nucleation event triggers crystallization. In a hand warmer, a small metal disk inside the pouch is clicked, providing the nucleation site. A wave of crystallization sweeps across the pouch within seconds, rapidly converting the dissolved acetate back to solid trihydrate. Because crystallization releases the heat of fusion (the energy that originally went into dissolving the crystal), the pouch warms to about 54 degrees Celsius and stays warm for an hour. Boiling the solidified pouch in water re-dissolves the crystals, resetting the warmer for another use. The example illustrates supersaturation, nucleation, and the connection between phase change and latent heat.")
    r("solubility and saturation", "misconception",
      "A common misconception is that 'like dissolves like' is a strict law rather than a useful heuristic. Polar solvents do tend to dissolve polar solutes and nonpolar solvents tend to dissolve nonpolar solutes, but exceptions abound: gasoline (nonpolar) dissolves substantial amounts of polar compounds like ethanol; water dissolves nonpolar gases like oxygen and CO2 enough to support aquatic life. Another misconception is that hot water always dissolves more of any solute; while this is true for most ionic salts (because dissolving them is endothermic), gases become less soluble at higher temperatures, which is why warm soda goes flat faster and warm rivers carry less dissolved oxygen than cold ones. People also sometimes think that stirring increases solubility; stirring speeds up the rate of dissolution but does not change the saturation limit. Finally, supersaturation is widely thought of as 'extra-dissolved' solute, but it is actually a metastable state in which the solute is precariously held in solution against its thermodynamic preference.")

    # ---- molecular orbital theory ----
    r("molecular orbital theory", "mechanism",
      "Molecular orbital (MO) theory works by combining atomic orbitals from the atoms in a molecule to form a set of molecular orbitals that span the entire molecule. Mathematically, this is a linear combination of atomic orbitals (LCAO): each MO is a sum of atomic orbitals weighted by coefficients determined by solving the Schrodinger equation in the molecular framework. The number of MOs equals the number of atomic orbitals combined; for two atoms each contributing one orbital, you get one bonding MO (lower energy than the parent atomic orbitals, with electron density concentrated between the nuclei) and one antibonding MO (higher energy, with a node between the nuclei). Electrons fill the MOs in order of increasing energy following the same Aufbau, Hund, and Pauli rules as atomic orbitals. The bond order, defined as half the difference between bonding and antibonding electron counts, predicts the strength and existence of the bond. MO theory generalizes to molecules of any size, with each MO potentially extending across many atoms.")
    r("molecular orbital theory", "significance",
      "MO theory matters because it correctly predicts molecular properties that simpler valence-bond pictures cannot, including paramagnetism, bond order in odd-electron species, and electronic spectra. The most famous example is molecular oxygen, O2: simple Lewis structures predict a closed-shell diamagnetic molecule with a double bond, but oxygen is in fact paramagnetic, attracted into magnetic fields, with two unpaired electrons. MO theory predicts this naturally: the two highest-energy electrons in O2 occupy a pair of degenerate antibonding pi* orbitals with parallel spins, in accordance with Hund's rule. MO theory also explains why some molecules absorb light at specific wavelengths (transitions between MOs of different energy), why certain reactions are allowed or forbidden by orbital symmetry, why aromatic molecules like benzene are unusually stable, and how transition metal complexes get their colors. Modern computational chemistry uses MO methods (Hartree-Fock, density functional theory, post-Hartree-Fock methods) to predict molecular structures, energies, and reactivity from first principles.")
    r("molecular orbital theory", "example",
      "The bonding in carbon monoxide (CO) is a clean example. Combining the 2s and 2p atomic orbitals of carbon and oxygen produces eight molecular orbitals: a bonding-antibonding pair from sigma overlap of 2s, a bonding-antibonding pair from sigma overlap of 2p_z (along the bond axis), and two bonding-antibonding pairs from pi overlap of 2p_x and 2p_y. CO has 10 valence electrons (4 from C, 6 from O), which fill the lowest five MOs: the two sigma bonding orbitals and the two pi bonding orbitals. The bond order is (8 - 2)/2 = 3, predicting a triple bond as observed (CO is isoelectronic with N2 and has a similar very short, very strong bond). The HOMO of CO is largely localized on carbon, which is why CO binds to transition metals through its carbon end (forming carbonyl complexes) and why CO is a potent ligand and a deadly poison through its strong binding to the iron in hemoglobin.")
    r("molecular orbital theory", "misconception",
      "A common misconception is that MO theory replaces valence-bond (Lewis structure) theory; the two are complementary descriptions of the same physical reality, with MO theory more rigorous and Lewis structures more intuitive for many qualitative purposes. Another misconception is that bonding electrons in MOs are 'shared between two atoms' in the same way as Lewis bonds; in MO theory, electrons in delocalized orbitals can extend across many atoms, with the bonding character distributed nonlocally. People sometimes also assume that all bonding orbitals lie below all antibonding orbitals; in larger molecules this need not be true, and an antibonding orbital from one set can be lower than a bonding orbital from another. Finally, the picture of MOs as simple sums of atomic orbitals is exact only for the LCAO approximation; in real molecules, orbitals adjust their shape (polarization) and mix with diffuse and core orbitals in ways that the simple LCAO picture omits, requiring more sophisticated computational treatments for accurate predictions.")

    # ---- DNA replication ----
    r("DNA replication", "definition",
      "DNA replication is the biological process by which a cell duplicates its DNA, producing two identical double-stranded copies from one parental molecule. It is semiconservative: each daughter DNA molecule consists of one original strand and one newly synthesized strand. Replication occurs once per cell cycle, in the S phase, before cell division, and is essential for passing genetic information faithfully from one cell generation to the next. The process involves dozens of enzymes and proteins that together unwind the double helix, prime DNA synthesis, polymerize new strands using the original strands as templates, proofread for errors, and join discontinuous fragments. Eukaryotic chromosomes have many origins of replication operating in parallel, while bacterial circular chromosomes typically have a single origin from which replication proceeds bidirectionally. The fidelity of the process is extraordinary: error rates after proofreading and mismatch repair are about one mistake per 10^9 base pairs.")
    r("DNA replication", "mechanism",
      "Replication begins when initiator proteins recognize and bind to specific origin sequences and recruit a helicase, which unwinds the double helix into two single strands by breaking the hydrogen bonds between base pairs. Single-strand binding proteins coat the unwound strands to prevent re-annealing. A primase synthesizes short RNA primers, providing the 3'-OH groups that DNA polymerases require to initiate synthesis. DNA polymerase III (in bacteria) or polymerases delta and epsilon (in eukaryotes) then add deoxyribonucleotides one at a time to the 3' end of the growing strand, using base-pairing rules with the template (A-T, G-C). Because polymerases work only 5' to 3', one daughter strand (the leading strand) is synthesized continuously following the replication fork, while the other (the lagging strand) is built in short pieces called Okazaki fragments, each requiring its own primer. RNA primers are later removed and replaced with DNA, and the fragments are joined by DNA ligase. Topoisomerases relieve the supercoiling stress generated ahead of the fork.")
    r("DNA replication", "comparison",
      "DNA replication differs from transcription in several ways. Replication copies the entire genome and produces double-stranded DNA, while transcription copies short stretches into single-stranded RNA molecules used for protein synthesis or regulation. Replication occurs once per cell cycle while transcription occurs continuously throughout the cell's life as different genes are expressed. Replication uses DNA polymerases that have proofreading exonuclease activity for fidelity, while RNA polymerases lack such proofreading because RNA copies are short-lived and can be remade. Replication is bidirectional from origins, with both strands copied simultaneously, while transcription is unidirectional from promoters and copies only one of the two strands. Compared with reverse transcription, which copies RNA into DNA (used by retroviruses and retrotransposons), normal DNA replication uses DNA as the template. Compared across kingdoms, eukaryotic and bacterial replication share the core principles but differ in details: eukaryotes have multiple origins per chromosome, more complex initiation control, and additional accessory proteins.")
    r("DNA replication", "misconception",
      "A common misconception is that DNA polymerases can start a new strand from scratch; in fact they require an existing 3'-OH group, which is why RNA primers must be laid down first. Another misconception is that the leading and lagging strands have different chemical composition; they are chemically identical DNA, with 'leading' and 'lagging' referring only to the kinetics and continuity of their synthesis at a moving fork. People also sometimes think replication is error-free; while remarkably accurate, it makes about one mistake per 10^7 bases that escapes the proofreading of polymerase, with mismatch repair catching most of the rest before they become permanent mutations. Finally, the popular image of a zipper-like double helix unwinding from one end is misleading; replication initiates at multiple internal origins, and helicases work outward from each origin in two directions, with thousands of forks operating simultaneously in a typical eukaryotic cell.")

    # ---- protein folding ----
    r("protein folding", "definition",
      "Protein folding is the physical process by which a linear chain of amino acids assumes its three-dimensional structure that determines its biological function. After ribosomes synthesize a protein from its mRNA template, the resulting polypeptide is initially an unstructured chain that must fold into a precise compact shape, often within milliseconds to seconds, to become functional. The folded structure has multiple levels of organization: secondary structure (alpha helices and beta sheets), tertiary structure (the overall three-dimensional fold of a single chain), and quaternary structure (the assembly of multiple chains in oligomeric proteins). The folding pathway is encoded in the amino acid sequence (Anfinsen's principle), driven by the burial of hydrophobic residues in the interior, the formation of hydrogen bonds in secondary structure, and the satisfaction of van der Waals contacts in the core. Misfolded proteins are typically degraded or sometimes form pathological aggregates implicated in diseases like Alzheimer's, Parkinson's, and prion disorders.")
    r("protein folding", "mechanism",
      "Folding works through a combination of thermodynamics (the folded state has the lowest accessible free energy under physiological conditions) and kinetics (the protein finds that state along productive pathways much faster than blind search would allow). The hydrophobic effect drives initial collapse: nonpolar side chains tend to cluster together in the interior, expelling structured water and increasing the system's overall entropy. Local secondary structures form rapidly through hydrogen bonding within the backbone. Folding then proceeds by progressive condensation of substructures into the native topology, often through transient intermediates. Many proteins fold spontaneously in vitro, but in cells molecular chaperones (Hsp70, Hsp60/GroEL, Hsp90) assist by binding nascent chains, preventing aggregation, and providing isolated environments in which misfolded proteins can refold. The native state is usually only marginally more stable than the unfolded ensemble, by about 5-15 kcal/mol, which makes folding fragile to mutations, temperature, and chemical disturbances.")
    r("protein folding", "significance",
      "Protein folding matters because the three-dimensional structure of a protein dictates its function, from enzymatic catalysis to molecular recognition to mechanical force generation. Predicting how an amino acid sequence folds has been one of biology's grand challenges for half a century, with implications for understanding biology, designing drugs that bind specific proteins, engineering new enzymes, and treating diseases caused by misfolding. The 2020 success of AlphaFold2 in predicting protein structures from sequence with near-experimental accuracy has transformed the field, putting millions of high-quality structures in public databases and enabling rapid hypothesis generation. Misfolding diseases (Alzheimer's beta-amyloid plaques, Parkinson's alpha-synuclein, prion diseases like mad cow disease) are caused by proteins adopting alternative aggregated structures that resist normal cellular clearance and damage tissue. Understanding folding is essential for protein engineering, where designed sequences must reliably fold into desired structures, and for synthetic biology applications that require tailored protein function.")

    # ---- the citric acid cycle ----
    r("the citric acid cycle", "mechanism",
      "The citric acid cycle (also called the Krebs cycle or TCA cycle) is the central metabolic hub that oxidizes acetyl groups derived from carbohydrates, fats, and proteins into carbon dioxide while harvesting energy in the form of NADH, FADH2, and GTP/ATP. The cycle takes place in the mitochondrial matrix and consists of eight enzyme-catalyzed reactions. Acetyl-CoA enters by combining with the four-carbon oxaloacetate to form the six-carbon citrate. Through a series of decarboxylation, oxidation, and isomerization steps, the cycle releases two molecules of CO2 (accounting for the two carbons brought in by acetyl-CoA), generates three NADH and one FADH2 (which feed into the electron transport chain to drive ATP synthesis), and produces one GTP (or ATP). At the end of one turn, oxaloacetate is regenerated, ready to accept another acetyl-CoA. The cycle's intermediates also serve as biosynthetic precursors for amino acids, heme, and fatty acids, making the cycle a metabolic crossroads rather than a pure energy-extraction loop.")
    r("the citric acid cycle", "comparison",
      "The citric acid cycle differs from glycolysis in location, substrate, and yield. Glycolysis occurs in the cytoplasm, breaks down one glucose into two pyruvates, produces a small net 2 ATP and 2 NADH, and operates with or without oxygen. The citric acid cycle occurs inside mitochondria, processes acetyl-CoA derived from pyruvate (or from fat or amino acid catabolism), produces a much richer harvest per acetyl unit (3 NADH, 1 FADH2, 1 GTP), and requires aerobic conditions because the NADH and FADH2 must be reoxidized by oxygen via the electron transport chain. Compared with the electron transport chain itself, the citric acid cycle is the source of most of the reducing equivalents (NADH and FADH2), while the chain is where those reducing equivalents are oxidized to drive proton pumping and ATP synthesis. Compared with beta-oxidation of fatty acids, the citric acid cycle accepts the acetyl-CoA products of beta-oxidation as inputs and oxidizes them to completion.")
    r("the citric acid cycle", "misconception",
      "A common misconception is that the citric acid cycle 'produces ATP' as its primary function. The cycle directly produces only one GTP (or ATP) per turn; the bulk of ATP comes later from oxidative phosphorylation, which uses the NADH and FADH2 produced by the cycle. Another misconception is that the cycle simply burns fuel for energy; it is also a major biosynthetic pathway, with intermediates withdrawn for synthesis of amino acids (alpha-ketoglutarate to glutamate, oxaloacetate to aspartate), heme (succinyl-CoA), and fatty acids (citrate exported to cytoplasm). The intermediates must be replenished by anaplerotic reactions, most importantly the conversion of pyruvate to oxaloacetate by pyruvate carboxylase. People also sometimes think the cycle runs in only one direction; while the net flow is forward, individual steps are near equilibrium and can be reversed under certain conditions. Finally, the name 'cycle' suggests an isolated loop, but in reality the cycle is heavily integrated with hundreds of other pathways through shared metabolites.")

    # ---- photosynthesis ----
    r("photosynthesis", "definition",
      "Photosynthesis is the process by which plants, algae, and certain bacteria convert light energy into chemical energy stored in sugar molecules, simultaneously releasing oxygen as a byproduct. The overall reaction can be summarized as 6 CO2 + 6 H2O + light energy producing C6H12O6 (glucose) + 6 O2. The process consists of two stages. The light-dependent reactions take place in the thylakoid membranes of chloroplasts, where chlorophyll captures photons, splits water to release oxygen, and produces ATP and NADPH. The light-independent reactions (the Calvin cycle) take place in the chloroplast stroma, where ATP and NADPH are used to fix atmospheric carbon dioxide into three-carbon sugar precursors via the enzyme RuBisCO. Photosynthesis is the primary source of nearly all biomass and oxygen on Earth, supporting almost every food chain and creating the atmospheric conditions required for aerobic life.")
    r("photosynthesis", "mechanism",
      "The mechanism begins when a photon is absorbed by chlorophyll molecules embedded in photosynthetic membranes, exciting an electron to a higher energy state. This electron is passed through a chain of protein complexes (Photosystem II, then the cytochrome b6f complex, then Photosystem I) that pumps protons across the thylakoid membrane, building up a proton gradient. ATP synthase uses this gradient to make ATP from ADP and inorganic phosphate. Meanwhile, photosystem II replaces its lost electron by oxidizing water, splitting H2O molecules to release O2, protons, and electrons. Photosystem I uses light energy to lift the electron's energy further and reduce NADP+ to NADPH. The Calvin cycle then takes ATP, NADPH, and CO2 to drive the carboxylation of ribulose bisphosphate by RuBisCO, producing two molecules of 3-phosphoglycerate that are reduced to glyceraldehyde-3-phosphate. Most of the G3P is recycled to regenerate RuBP, while a fraction exits to build glucose, sucrose, starch, and other organic molecules.")
    r("photosynthesis", "example",
      "A useful concrete example is the cyanobacterium that lives in lakes, ponds, and oceans, performing oxygenic photosynthesis essentially as plants do. A single Synechocystis cell, just a few micrometers across, contains thylakoid membranes packed with chlorophyll and accessory pigments. In sunlight, water molecules at Photosystem II are split into oxygen and protons, electrons travel through the chain to make ATP and NADPH, and these power the Calvin cycle to fix dissolved CO2 into sugars. The oxygen released bubbles into the surrounding water and eventually into the atmosphere; cyanobacteria like these (and their ancestors) were responsible for oxygenating Earth's atmosphere starting about 2.4 billion years ago, the Great Oxygenation Event. Modern marine cyanobacteria such as Prochlorococcus, the most abundant photosynthetic organism on the planet, contribute roughly a fifth of global photosynthetic oxygen production, illustrating that the biosphere's oxygen supply is largely sustained by tiny single-celled organisms invisible without a microscope.")

    # ---- mitosis vs meiosis ----
    r("mitosis vs meiosis", "definition",
      "Mitosis and meiosis are the two principal modes of nuclear division in eukaryotic cells. Mitosis produces two daughter cells genetically identical to the parent, with the same chromosome number and the same alleles. It is the mechanism behind growth, tissue repair, and asexual reproduction; nearly every cell division in your body except the production of gametes is mitotic. Meiosis, by contrast, produces four daughter cells (gametes) with half the chromosome number of the parent and recombined genetic content. It involves two consecutive divisions: meiosis I separates homologous chromosomes (reducing chromosome number from 2n to n), and meiosis II separates sister chromatids (similar to mitosis but on the haploid set). Meiosis is the basis of sexual reproduction, generating genetic diversity through crossing over (recombination during prophase I) and independent assortment of chromosomes, while ensuring that gamete fusion at fertilization restores the diploid chromosome number.")
    r("mitosis vs meiosis", "comparison",
      "Mitosis and meiosis differ in several systematic ways. Mitosis is one division producing two diploid daughter cells; meiosis is two divisions producing four haploid daughter cells. Mitosis maintains chromosome number and genetic identity; meiosis halves chromosome number and reshuffles alleles through crossing over and independent assortment. Mitotic prophase has no pairing of homologous chromosomes; meiotic prophase I features synapsis, where homologs pair up and exchange segments by crossing over. Mitotic metaphase aligns single chromosomes (each with two sister chromatids) at the equator; meiotic metaphase I aligns paired homologs (tetrads). Mitotic anaphase separates sister chromatids; meiotic anaphase I separates homologs while sister chromatids stay attached. Mitosis happens in nearly all somatic cells throughout life; meiosis happens only in germ-line cells producing gametes (sperm and eggs in animals; spores in plants). Mitotic errors are the basis of many cancers; meiotic errors produce aneuploid gametes leading to conditions like Down syndrome.")

    # ---- natural selection ----
    r("natural selection", "definition",
      "Natural selection is the evolutionary mechanism by which organisms with heritable traits that improve their reproductive success leave more offspring than those without such traits, gradually changing the genetic composition of populations over generations. Charles Darwin and Alfred Russel Wallace independently proposed the principle in the mid-19th century. Three conditions are required for natural selection to operate: variation among individuals in some trait, heritability of that trait so offspring resemble their parents, and a correlation between trait values and reproductive success in the prevailing environment. When these conditions are met, the next generation will, on average, contain a higher proportion of the fitter trait values than the present generation. Natural selection is not random; it is the differential outcome of random variation filtered by environmental conditions. Over deep time, natural selection acting on accumulated mutations produces adaptation to environments and ultimately the divergence of new species from ancestral lineages.")
    r("natural selection", "example",
      "The peppered moth in industrial England is a textbook example. Before the Industrial Revolution, the peppered moth Biston betularia was predominantly light-colored, blending with lichen-covered tree bark and avoiding predation by birds. As coal-burning industry blackened tree trunks with soot in the mid-19th century, light moths became conspicuous and were eaten more often, while dark variants (carrying a mutation in a single gene) became cryptic and survived better. Over decades, the dark form rose from less than 2 percent of the population to over 95 percent in heavily polluted areas. After the Clean Air Acts of the 1950s and 1960s reduced soot pollution and lichens regrew, the trend reversed: light moths regained the camouflage advantage and the population shifted back toward the original phenotype. Field experiments releasing marked moths and recapturing the survivors confirmed that bird predation differential drove the shifts. The episode demonstrates natural selection acting visibly within human lifetimes on a heritable trait under shifting environmental pressure.")
    r("natural selection", "misconception",
      "A widespread misconception is that natural selection works 'for the good of the species.' Selection acts on individual organisms (and at finer levels on individual genes); a trait spreads if it benefits its carrier's reproductive success, even if that hurts the species overall. Another misconception is that organisms evolve 'in order to' meet challenges, as though evolution were directed; selection has no foresight, and adaptation arises by retroactive filtering of random mutations that happened to confer advantages in the past. People also commonly confuse natural selection with the entire theory of evolution; selection is one mechanism (alongside genetic drift, gene flow, and mutation) producing evolutionary change. The phrase 'survival of the fittest' is often misread as a circular tautology or as endorsing brute strength; in evolutionary terms, fitness means reproductive success in a particular environment, which can favor cooperators, smaller body sizes, or any other trait depending on context. Finally, evolution does not produce 'higher' or 'more advanced' organisms in any objective sense; modern bacteria are as evolved as humans and superbly adapted to their environments.")

    # ---- genetic mutation types ----
    r("genetic mutation types", "definition",
      "Genetic mutations are heritable changes in the DNA sequence of an organism, ranging from single-letter substitutions to large-scale rearrangements. Point mutations affect a single base pair: substitutions can be silent (no protein change), missense (one amino acid replaced by another), or nonsense (creating a premature stop codon). Insertions and deletions of one or more bases shift the reading frame downstream of the change, often producing a non-functional protein. Copy number variants gain or lose entire stretches of DNA. Inversions flip a segment of a chromosome. Translocations move pieces of one chromosome to another. Aneuploidy involves whole-chromosome additions or losses, like the trisomy 21 that causes Down syndrome. Mutations can occur in germ-line cells (transmitted to offspring) or in somatic cells (carried only by a tissue lineage within an individual; many cancers begin with somatic mutations). The rate of new mutations per base per generation is typically about 10^-8 in humans.")
    r("genetic mutation types", "comparison",
      "Different mutation types differ in scale, frequency, and likely effect. Point mutations are the most common; many are neutral, especially synonymous substitutions in coding regions or substitutions in non-functional non-coding DNA. Frameshift mutations from small insertions or deletions almost always abolish protein function downstream of the change because the codon reading is shifted. Splice-site mutations alter how introns are removed from mRNA, often producing aberrant proteins. Copy number variants and large deletions can affect many genes at once and have larger phenotypic effects per event but are rarer per generation. Compared with chromosomal rearrangements like inversions and translocations, which alter the linear order of genes but typically preserve gene dosage, aneuploidies that change chromosome number alter the dosage of hundreds or thousands of genes simultaneously and are usually severely deleterious or lethal except for a few tolerated chromosomes. Compared with epigenetic changes (modifications to DNA or chromatin that alter gene expression without changing sequence), genetic mutations are heritable through DNA replication while epigenetic changes are often (though not always) erased between generations.")
    r("genetic mutation types", "misconception",
      "A common misconception is that mutations are usually harmful. Many mutations are silent or neutral, especially in noncoding DNA; among those that do affect function, both deleterious and beneficial outcomes occur, with the rate of beneficial mutations being low but nonzero, especially in changing environments. Another misconception is that organisms 'try' to mutate certain genes in response to selection pressure (Lamarckian inheritance); standard mutation generation is largely random with respect to need, though some bacterial systems have evolved adaptive mechanisms that can bias mutation toward useful regions under stress. People also sometimes think a mutation in a single gene always produces a single phenotypic change; pleiotropy means one gene can affect many traits, and many traits are influenced by many genes. Finally, the popular image of mutations as monstrous changes is misleading; most morphological evolution comes from many small accumulated changes rather than rare large ones, and the dramatic 'monster' mutations in lab organisms are typically too disruptive to fix in natural populations.")

    # ---- CRISPR gene editing ----
    r("CRISPR gene editing", "mechanism",
      "CRISPR gene editing repurposes a bacterial immune system that defends against viruses by cutting their DNA at specific sequences. The system has two essential components: a guide RNA whose sequence is complementary to the target DNA, and an enzyme (most commonly Cas9) that uses the guide RNA to find and cut the target. The guide RNA is engineered to match the genomic location to be edited. When the guide RNA-Cas9 complex is introduced into a cell, it scans the genome, base-pairs the guide RNA with the matching DNA sequence, and Cas9 makes a precise double-strand break in the DNA. The cell then repairs the break through one of two pathways: nonhomologous end joining (NHEJ), which often introduces small insertions or deletions that disrupt gene function, or homology-directed repair (HDR), which uses a supplied DNA template to introduce specific edits. By choosing the guide RNA, researchers can target essentially any sequence in the genome; by supplying a repair template, they can write specific edits.")
    r("CRISPR gene editing", "significance",
      "CRISPR matters because it dramatically lowered the technical barrier and cost of editing genomes, transforming basic research, agriculture, and medicine. Before CRISPR, methods like zinc finger nucleases and TALENs could perform similar edits but required custom protein engineering for each target, taking months and large budgets. CRISPR can be redirected to a new target by simply ordering a different guide RNA, often within days for less than a hundred dollars. Researchers have used CRISPR to study gene function in thousands of organisms, develop crop varieties resistant to disease and tolerant of climate stress, and pursue therapies for sickle cell disease, beta-thalassemia, hereditary blindness, and certain cancers. The first CRISPR-based therapy, Casgevy for sickle cell disease, was approved in 2023. CRISPR has also raised significant ethical questions, especially around heritable germ-line edits in human embryos, illustrated by the controversial 2018 case of edited babies in China that was widely condemned by the scientific community.")
    r("CRISPR gene editing", "misconception",
      "A common misconception is that CRISPR is perfectly precise and can edit any genome with no side effects. In practice, off-target cutting at sequences similar to the intended target can occur, requiring careful guide design and validation. Another misconception is that CRISPR rewrites genes 'in place' with surgical precision; it actually breaks DNA and relies on the cell's own repair machinery, which is error-prone (NHEJ produces indels) or dependent on a supplied template (HDR works in only a fraction of cell types and stages). People also conflate CRISPR with germline editing of human embryos; the vast majority of CRISPR research and clinical use targets somatic cells in adults, with effects limited to the treated tissue and not heritable. Finally, the term 'CRISPR' technically refers to a family of bacterial loci, not just to Cas9; many alternative effector proteins (Cas12, Cas13, base editors derived from inactive Cas9 fusions, prime editors) now expand the toolbox for different kinds of edits.")

    # ---- the immune response ----
    r("the immune response", "comparison",
      "The innate and adaptive immune responses differ in speed, specificity, and memory. The innate response is the first line of defense, present from birth, with broadly tuned receptors that recognize molecular patterns common to many pathogens. It activates within minutes to hours and includes physical barriers (skin, mucus), chemical defenses (lysozyme, antimicrobial peptides), phagocytic cells (neutrophils, macrophages), natural killer cells, and the complement cascade. It does not improve with repeated exposure to the same pathogen. The adaptive response (also called acquired immunity) is slower to start (days), more specific (each lymphocyte clone recognizes one particular antigen), and develops immunological memory: after the first exposure, memory B and T cells persist for years and respond much faster and more strongly on subsequent encounters. Adaptive immunity has two arms: humoral (antibody-producing B cells) and cellular (T cells, including helper T cells that coordinate the response and cytotoxic T cells that kill infected cells). Both responses are tightly integrated, with innate signals shaping the adaptive response.")
    r("the immune response", "misconception",
      "A common misconception is that 'boosting your immune system' through supplements or special diets is generally beneficial. The immune system does not have a single 'level' that can be raised; aggressive immune activation can produce autoimmune disease and inflammatory damage as easily as it can fight infection. The well-supported interventions for immune health are basic: adequate sleep, balanced nutrition, regular exercise, stress management, and recommended vaccinations. Another misconception is that vaccines weaken or 'overload' the immune system; the antigens in vaccines are a tiny fraction of the antigens encountered in everyday life, and immunological memory generated by vaccination is the same kind of memory the system makes after natural infection. People also sometimes assume that if you are feverish or feeling sick, the immune response itself is damaging you; while symptoms like fever, fatigue, and inflammation are partly produced by immune activity, they often serve adaptive purposes (fever inhibits some pathogens, fatigue conserves energy for fighting infection). Finally, immunity to a pathogen is not always permanent, especially for fast-mutating viruses like influenza and SARS-CoV-2, which is why repeated vaccination is needed.")

    # ---- neurotransmitters and synapses ----
    r("neurotransmitters and synapses", "definition",
      "Neurotransmitters are chemical messengers released from one neuron and recognized by another, while a synapse is the specialized junction across which this signaling occurs. The presynaptic neuron stores neurotransmitter molecules in vesicles near the synaptic terminal. When an action potential arrives, voltage-gated calcium channels open, calcium flows in, and vesicles fuse with the membrane to release neurotransmitter into the narrow synaptic cleft (about 20-40 nanometers wide). Neurotransmitter molecules diffuse across the cleft and bind specific receptor proteins on the postsynaptic membrane, which open ion channels (ionotropic receptors) or activate intracellular signaling cascades (metabotropic receptors). The result is either depolarization (excitatory) or hyperpolarization (inhibitory) of the postsynaptic neuron, determining whether it fires its own action potential. Neurotransmitters in the cleft are then cleared by enzymatic degradation, reuptake into the presynaptic terminal, or diffusion. The brain uses dozens of distinct neurotransmitters including glutamate, GABA, dopamine, serotonin, acetylcholine, and norepinephrine, each with characteristic distribution and effect.")
    r("neurotransmitters and synapses", "comparison",
      "Chemical synapses (the most common in vertebrate brains) differ from electrical synapses in how signals cross the junction. Chemical synapses use neurotransmitter molecules diffusing across a cleft, introducing a brief delay (about 0.5-2 milliseconds) and allowing complex regulation, plasticity, and signal amplification or inversion. Electrical synapses use gap junctions of connexin proteins that form pores connecting the cytoplasms of adjacent cells, allowing ions and small molecules to flow directly from one cell to another. Electrical synapses are very fast (essentially instantaneous), bidirectional in most cases, and well-suited to synchronizing groups of neurons; they are common in cardiac tissue, smooth muscle, and certain neural circuits requiring tight synchrony. Compared with the diversity of chemical neurotransmitter systems with their fine-grained pharmacology, electrical synapses are simpler and less modulable. Within chemical synapses, ionotropic and metabotropic receptors differ similarly: ionotropic action is fast (millisecond timescale) and brief, while metabotropic action is slower (hundreds of milliseconds) but produces longer-lasting effects through second-messenger signaling.")
    r("neurotransmitters and synapses", "misconception",
      "A widespread misconception is that there are 'good' and 'bad' neurotransmitters or that depression is 'caused by low serotonin.' The actual story is far more complex: most neurotransmitters can be excitatory or inhibitory depending on which receptor subtype they bind, where in the brain they act, and the surrounding circuit context. SSRIs do raise synaptic serotonin levels, but their therapeutic effect emerges over weeks, suggesting downstream changes in receptor expression, gene transcription, and circuit remodeling rather than a simple chemical-deficiency cure. Another misconception is that one neurotransmitter equals one function; dopamine, for example, is involved in reward prediction, motor control, motivation, and many other roles in different circuits. People also sometimes think synaptic communication is unidirectional and stereotyped; in fact, retrograde signaling from postsynaptic to presynaptic neurons is common (endocannabinoids and gases like nitric oxide travel backward), and synaptic strength changes with experience through long-term potentiation and depression, the cellular basis of much learning and memory.")

    # ---- the human microbiome ----
    r("the human microbiome", "definition",
      "The human microbiome is the collective community of microorganisms that live on and in the human body, including bacteria, archaea, fungi, viruses, and protists. The largest and best-studied component is the gut microbiome, with an estimated 10^13 to 10^14 microbial cells in the colon alone, comparable to the number of human cells in the body. Other distinct microbial communities populate the skin, mouth, respiratory tract, urogenital tract, and even the placenta. The microbiome's collective genome (the microbiota encodes roughly a hundred times more genes than the human genome) carries metabolic capabilities the host lacks, including fermentation of dietary fiber, synthesis of certain vitamins, and metabolism of drugs and xenobiotics. Microbiome composition varies among individuals based on genetics, diet, environment, age, geography, antibiotic exposure, and birth mode. The microbiome is dynamic but also surprisingly stable for a given individual over years, with each person carrying a characteristic 'fingerprint' of microbial composition.")
    r("the human microbiome", "mechanism",
      "The microbiome interacts with the host through several mechanisms. In the gut, bacteria ferment dietary fibers that human enzymes cannot digest, producing short-chain fatty acids (acetate, propionate, butyrate) that nourish colonic cells, modulate inflammation, and signal to the immune and metabolic systems. Bacteria also synthesize vitamins (K, B12, biotin, folate), bile acid derivatives that signal through nuclear receptors, and neurotransmitter precursors that influence the gut-brain axis. The microbiome occupies physical and metabolic niches that prevent colonization by pathogens, both by direct competition and by stimulating the host's mucosal immune system to remain alert. Cross-talk with the immune system shapes the development and balance of T helper cell subsets, with implications for allergies, autoimmune disease, and inflammatory bowel disease. Disruption of the microbiome (dysbiosis) by antibiotics, illness, or dietary change can lead to opportunistic infections like Clostridioides difficile colitis or contribute to chronic conditions like obesity and inflammatory bowel disease.")
    r("the human microbiome", "comparison",
      "The human microbiome differs from infectious microbes in being commensal or mutualistic rather than pathogenic, though the line is not absolute and some normally benign organisms can become harmful when displaced from their usual niche or in immunocompromised hosts. Compared with the microbiomes of other animals, the human microbiome is fairly distinctive but shares the gross features of mammalian gut microbiomes, with substantial variation between people that often exceeds variation between species. Compared across body sites, the gut microbiome is dense and dominated by anaerobes (Bacteroidetes and Firmicutes), the skin microbiome is dominated by aerobic actinobacteria and proteobacteria with much lower density, the oral microbiome forms biofilms with characteristic spatial structure, and the vaginal microbiome is unusually low-diversity, dominated by Lactobacillus species in healthy reproductive-age women. Compared with the bacteriocentric view of the early years of microbiome research, modern work increasingly recognizes the importance of fungi, viruses, and archaea, though most species and functions remain incompletely characterized.")
    r("the human microbiome", "example",
      "The use of fecal microbiota transplantation (FMT) for recurrent Clostridioides difficile infection is a striking real-world example of the microbiome's medical importance. C. difficile is a bacterial pathogen that overgrows in the colon when antibiotics have wiped out the normal microbiome, causing severe diarrhea and colitis with recurrence rates as high as 30 percent after antibiotic treatment alone. FMT involves transferring stool from a healthy donor into the recipient's gut, restoring a diverse microbial community that outcompetes C. difficile and prevents its recurrence. Cure rates from FMT exceed 90 percent in many studies, far better than antibiotic-only approaches. The procedure has been performed via colonoscopy, nasogastric tube, enema, or oral capsules of processed donor stool. Beyond C. difficile, FMT and related microbiome interventions are being studied for inflammatory bowel disease, irritable bowel syndrome, hepatic encephalopathy, and even certain metabolic and neuropsychiatric conditions, though efficacy outside C. difficile remains less clear-cut.")
    r("the human microbiome", "significance",
      "The microbiome matters because it influences digestion, immune development, metabolism, drug response, and even mood and behavior, with disruptions implicated in conditions from obesity to autoimmune disease. Understanding the microbiome has reframed many diseases as ecological imbalances rather than purely host pathologies. Practical applications include the development of next-generation probiotics targeted at specific deficits, microbiome-based diagnostics that predict drug response or disease risk, dietary interventions designed to feed beneficial bacteria, and targeted therapies that selectively suppress harmful organisms while sparing useful ones. The microbiome also raises interesting questions about identity and individuality: every person carries millions of microbial genomes that shape their physiology, blurring the line between self and other. From a clinical perspective, awareness of the microbiome is changing antibiotic stewardship, post-antibiotic recovery practices, infant feeding recommendations (favoring vaginal birth and breastfeeding when possible for microbiome seeding), and surgical approaches that consider microbial preservation in addition to host tissue.")

    # ---- viral replication ----
    r("viral replication", "definition",
      "Viral replication is the process by which a virus produces many copies of itself inside an infected host cell. Viruses are not capable of replicating independently; they are obligate intracellular parasites that hijack the host's cellular machinery for protein synthesis, energy production, and often nucleic acid replication. The replication cycle generally proceeds through six stages: attachment, where viral surface proteins bind specific receptors on the host cell; entry, where the virus or its genome crosses the cell membrane; uncoating, where the viral genome is released from its capsid; synthesis, where the genome is replicated and viral proteins are made; assembly, where new virions are constructed from the synthesized components; and release, where progeny virions exit the cell to infect others, either by lysing the cell or by budding off through the membrane. The details vary substantially between viruses with different genome types (DNA, RNA, double- or single-stranded, positive- or negative-sense) and different envelope structures.")
    r("viral replication", "example",
      "The replication cycle of HIV (a retrovirus) is a clinically important and well-studied example. HIV's lipid envelope carries the gp120 protein, which binds the CD4 receptor on certain immune cells (helper T cells, macrophages) and a coreceptor (CCR5 or CXCR4). Binding triggers fusion of viral and cell membranes, releasing the viral core into the cytoplasm. The single-stranded RNA genome is reverse-transcribed by the viral enzyme reverse transcriptase into double-stranded DNA, which is then transported to the nucleus and integrated into the host cell's chromosome by the viral integrase. The integrated provirus can remain latent for years or be transcribed into new viral RNA, which is processed into mRNA for synthesis of viral proteins and packaged as new genomes. Assembled virions bud off through the cell membrane, acquiring their envelope. Antiretroviral therapy targets multiple steps of this cycle, including reverse transcriptase, integrase, and protease, producing the suppression of viral replication that has transformed HIV from a death sentence into a chronic manageable condition.")
    r("viral replication", "misconception",
      "A common misconception is that viruses are alive in the same sense as bacteria. Viruses lack the cellular machinery for metabolism, protein synthesis, and energy production; outside a host cell, a virion is a chemical particle with no activity. Whether to call viruses 'alive' is a matter of definitional preference rather than biology. Another misconception is that all viral infections eventually clear; many establish lifelong latent or chronic infections (herpesviruses, HIV, hepatitis B), with the virus persisting in the host indefinitely and capable of reactivating. People also sometimes think that all viral genomes are DNA; in fact, many medically important viruses (influenza, HIV, SARS-CoV-2, hepatitis C, polio) have RNA genomes, and the great variation in genome type is a major reason viral families differ so much in replication strategy and antiviral susceptibility. Finally, the idea that 'a virus' has a single rigid form misses the constant evolution of viruses through high mutation rates, especially in RNA viruses, which is why annual influenza vaccines must be reformulated and why pandemic preparedness depends on genomic surveillance.")
    r("viral replication", "significance",
      "Viral replication matters because it is the target of every effective antiviral drug and the basis of all viral pathogenesis. Drugs interrupt specific steps: oseltamivir blocks neuraminidase release of influenza virions, acyclovir is preferentially incorporated by viral DNA polymerases of herpesviruses to halt their DNA synthesis, the antiretroviral cocktail in HIV therapy hits multiple steps simultaneously to prevent resistance, and the antivirals against SARS-CoV-2 (paxlovid's protease inhibitor, remdesivir's RNA polymerase inhibitor) interfere with viral protein processing and genome copying. Understanding replication also informs vaccine design: many vaccines present viral surface proteins to elicit antibodies that block attachment or entry; mRNA vaccines hijack the same protein-synthesis machinery viruses use to display viral antigens to the immune system. Finally, viral replication shapes the evolution of viruses themselves, with high mutation rates and short generation times producing rapid adaptation that drives the appearance of new variants and challenges sustained immunity, as illustrated repeatedly through the COVID-19 pandemic.")

    # ---- antibiotic resistance ----
    r("antibiotic resistance", "comparison",
      "Antibiotic resistance differs from intrinsic resistance, which is the natural insusceptibility of certain bacterial species to certain drugs (for example, gram-negative bacteria's outer membrane excludes many antibiotics that work against gram-positives), in being acquired by previously susceptible organisms through mutation or horizontal gene transfer. Compared with antiviral resistance, antibacterial resistance is often more transferable between species through plasmids, transposons, and integrons, allowing resistance traits to spread rapidly across diverse bacteria. Compared with cancer drug resistance, where individual tumor cell lineages evolve resistance independently, bacterial populations can share resistance genes across species in shared environments like hospitals, farms, and human guts, producing resistance gene pools that act as community-level reservoirs. Compared with resistance to disinfectants and antiseptics, antibiotic resistance specifically pertains to systemic anti-bacterial drugs and arises through more diverse mechanisms (efflux pumps, target modification, enzymatic inactivation, target bypass).")
    r("antibiotic resistance", "example",
      "Methicillin-resistant Staphylococcus aureus (MRSA) is a high-profile example. S. aureus is a common skin and nasal commensal that can cause serious infections including bacteremia, pneumonia, and necrotizing fasciitis. In the 1940s, almost all strains were susceptible to penicillin. Within a decade, plasmid-mediated beta-lactamase production made most strains penicillin-resistant. The development of methicillin and related semisynthetic beta-lactams overcame this, but by the 1960s methicillin-resistant strains had emerged, carrying the mecA gene encoding an alternative penicillin-binding protein (PBP2a) with low affinity for all beta-lactam antibiotics. MRSA spread first in hospitals and later in the community, with community-associated strains often carrying additional virulence factors. Treatment options narrowed to vancomycin and a handful of newer agents (linezolid, daptomycin, ceftaroline), and vancomycin-resistant S. aureus has begun appearing as well. The example shows how each new antibiotic class can be defeated within years to decades, with the resistance traits spreading to other species as well.")
    r("antibiotic resistance", "significance",
      "Antibiotic resistance matters because it threatens to undo a century of medical progress, with the WHO listing antimicrobial resistance among the top global health threats. Routine surgeries, chemotherapy for cancer, organ transplantation, and care of premature infants all depend on effective antibiotics to control opportunistic infections; growing resistance is making once-trivial infections deadly again, particularly in low- and middle-income countries with less access to second-line drugs. The pipeline of new antibiotics has thinned dramatically since the 1980s as pharmaceutical companies have moved to more profitable areas, with very few novel mechanism-of-action drugs reaching the market. Estimates of resistance-attributable deaths run into the millions annually worldwide. Combating resistance requires antibiotic stewardship in human and veterinary medicine, infection prevention measures, surveillance systems to track emerging resistance, restrictions on agricultural antibiotic use, investment in new antibiotic discovery, and development of complementary approaches like phage therapy, monoclonal antibodies, and microbiome-based interventions.")
    r("antibiotic resistance", "misconception",
      "A widespread misconception is that 'your body becomes resistant' to antibiotics, as though resistance were a property of the patient. Resistance is a property of the bacteria, not the host; the bacteria in your body (or those subsequently colonizing you) evolve resistance in response to antibiotic pressure. Another misconception is that taking antibiotics for viral infections cannot do harm 'just in case.' Antibiotics have no effect on viruses but disrupt your microbiome and select for resistance in any bacteria present, harming both you and the broader resistance landscape. People also commonly believe that finishing every prescribed course is uniformly required to prevent resistance; recent evidence suggests that for many infections, shorter courses are equally effective and may reduce resistance pressure, and the optimal duration is being actively re-evaluated for many indications. Finally, the term 'superbug' is sometimes taken to imply that resistant bacteria are inherently more virulent; resistant strains often have similar virulence to susceptible ones but become deadly because available treatments fail.")

    # ---- stem cells ----
    r("stem cells", "comparison",
      "Stem cells differ from differentiated cells in their twin capacities for self-renewal (dividing to produce more stem cells) and differentiation (giving rise to specialized cell types). Within the stem cell category, embryonic stem cells (ESCs) derived from the inner cell mass of blastocysts are pluripotent, capable of generating any cell type in the body. Adult (or somatic) stem cells found in various tissues are typically multipotent, restricted to producing the cell types of their resident tissue: hematopoietic stem cells make blood cells, epidermal stem cells make skin layers, intestinal stem cells make gut epithelial lineages. Induced pluripotent stem cells (iPSCs) are adult cells (often skin or blood cells) that have been reprogrammed back to a pluripotent state by introducing a small set of transcription factors (the Yamanaka factors), gaining ESC-like potency without the ethical issues surrounding embryonic sources. Compared with progenitor cells, which are committed to specific lineages and have limited self-renewal, true stem cells maintain their pool indefinitely.")
    r("stem cells", "example",
      "Hematopoietic stem cell transplantation (HSCT) is the most widely practiced clinical use of stem cells. Hematopoietic stem cells, found in bone marrow and umbilical cord blood, give rise to all the cellular components of blood: red blood cells, all types of white blood cells, and platelets. In a typical bone marrow transplant for leukemia or lymphoma, high-dose chemotherapy or radiation eliminates the patient's diseased blood-forming cells (and incidentally most other rapidly dividing cells), then donor stem cells are infused intravenously. The cells home to the bone marrow and engraft, gradually rebuilding the entire blood and immune system from a few thousand stem cells over weeks to months. The procedure has cured many otherwise fatal blood cancers and immune deficiencies, but carries substantial risks including graft-versus-host disease (donor immune cells attacking recipient tissues), infection during the immunocompromised period, and relapse if cancer cells survive the conditioning regimen.")

    # ---- the central dogma of molecular biology ----
    r("the central dogma of molecular biology", "definition",
      "The central dogma of molecular biology, formulated by Francis Crick in 1958, describes the directional flow of sequence information in cells: DNA can be replicated to produce more DNA, transcribed to produce RNA, and the RNA can be translated to produce proteins. The dogma's essential claim is that once information has passed into protein, it cannot flow back to nucleic acids: there is no general process by which a protein's amino acid sequence is reverse-translated into nucleic acid. The forward arrow from DNA through RNA to protein is the basis of how genes encode the proteins that catalyze metabolism, build structures, and regulate cellular processes. The dogma is not a metaphysical principle but an empirical generalization with known exceptions: reverse transcription (RNA to DNA) by retroviruses and retrotransposons, RNA replication (RNA to RNA) by RNA viruses, and prion-based heritable conformational changes in some proteins. The core forbidden step (protein to nucleic acid) remains intact and is what Crick actually emphasized.")

    # ---- cellular respiration ----
    r("cellular respiration", "definition",
      "Cellular respiration is the set of metabolic processes by which cells extract energy from organic molecules (most commonly glucose) and convert it into adenosine triphosphate (ATP), the universal energy currency that powers cellular work. Aerobic cellular respiration uses oxygen as the final electron acceptor and proceeds through three coordinated stages: glycolysis in the cytoplasm, which splits glucose into two pyruvates and makes a small amount of ATP and NADH; the citric acid cycle in the mitochondrial matrix, which oxidizes acetyl groups (derived from pyruvate) to CO2 and produces reducing equivalents NADH and FADH2 plus a small amount of GTP; and the electron transport chain and ATP synthase on the inner mitochondrial membrane, which use NADH and FADH2 to drive proton pumping that powers the synthesis of about 28 ATP per glucose. The full theoretical yield is about 30-32 ATP per glucose. Anaerobic respiration substitutes other electron acceptors (sulfate, nitrate) when oxygen is absent and yields less ATP per substrate.")
    r("cellular respiration", "significance",
      "Cellular respiration matters because it supplies essentially all the energy that animal life depends on, with each adult human turning over roughly their body weight in ATP every day to power muscle contraction, ion pumping, biosynthesis, and active transport. Disruptions to respiration produce serious disease: mitochondrial myopathies, Leigh syndrome, and a host of inherited mitochondrial disorders manifest as muscle weakness, neurological problems, and metabolic imbalances. Cyanide and carbon monoxide kill rapidly by blocking respiration at cytochrome c oxidase or by binding hemoglobin to prevent oxygen delivery. Many drug actions, both therapeutic and toxic, work through effects on mitochondrial function. The same machinery that produces ATP also produces reactive oxygen species as byproducts, contributing to oxidative damage implicated in aging, neurodegeneration, and cancer. Respiration is also evolutionarily ancient: the existence of mitochondria reflects an ancient endosymbiosis of an alpha-proteobacterium with an archaeal host, an event that may have been singular in life's history and a precondition for the evolution of complex multicellular life.")
    r("cellular respiration", "misconception",
      "A common misconception is that 'breathing' and 'cellular respiration' are the same; breathing (ventilation) brings oxygen to the lungs and removes CO2, while cellular respiration is the biochemical process inside cells where the oxygen is consumed and the CO2 is generated. Another misconception is that all energy comes from respiration of carbohydrates; fats are oxidized through beta-oxidation to acetyl-CoA that enters the same citric acid cycle, and amino acids can also be deaminated and fed into the cycle, with each fuel having different ATP yields per mass and different storage characteristics. People sometimes think that cellular respiration is one-step; in fact it is dozens of enzymatic reactions across multiple cellular compartments, and the textbook number of about 30 ATP per glucose is a theoretical maximum that varies in real cells based on proton leak and substrate shuttling. Finally, anaerobic 'respiration' is often confused with fermentation; true anaerobic respiration uses electron transport chains with non-oxygen final acceptors, while fermentation re-oxidizes NADH within the cytoplasm without an electron transport chain.")

    # ---- the cardiovascular system ----
    r("the cardiovascular system", "definition",
      "The cardiovascular system is the circulatory network that moves blood throughout the body to deliver oxygen and nutrients, remove carbon dioxide and metabolic wastes, distribute hormones, and regulate temperature. It consists of the heart (a muscular pump with four chambers), the blood vessels (arteries, arterioles, capillaries, venules, veins), and the blood itself (cells suspended in plasma). The system has two circuits in series: the pulmonary circulation moves blood from the right side of the heart through the lungs and back to the left side, oxygenating it and unloading CO2; the systemic circulation moves blood from the left side of the heart through the rest of the body and back to the right side, delivering oxygen and nutrients to tissues. The heart beats about 100,000 times per day, pumping roughly 7,000 liters of blood through over 100,000 kilometers of vessels. Regulation involves the autonomic nervous system, hormones, local tissue signals, and intrinsic cardiac and vascular properties.")
    r("the cardiovascular system", "mechanism",
      "Mechanically, the heart's two atria fill with returning blood while the two ventricles pump blood out, with one-way valves between chambers and between ventricles and outflow vessels enforcing the direction of flow. An electrical conduction system originating in the sinoatrial node sets the heart's rhythm: electrical impulses spread through the atria, are delayed at the atrioventricular node to allow ventricular filling, then race through the bundle of His and Purkinje fibers to trigger coordinated ventricular contraction. At the tissue level, gas and nutrient exchange happens in capillaries, the smallest vessels, where wall thickness is just one endothelial cell and diffusion distances are tiny. Pressure generated by the left ventricle drives blood through the systemic arteries, with elastic large arteries smoothing the pulsatile flow into more continuous capillary perfusion. Veins return blood to the heart aided by skeletal muscle contraction (the muscle pump) and one-way venous valves. The system is finely regulated by baroreflexes that adjust heart rate and vascular tone to maintain blood pressure across postural changes and other perturbations.")
    r("the cardiovascular system", "example",
      "The cardiovascular response to standing up is a fine example of the system's regulation. When you stand, gravity pools blood in the lower extremities, transiently reducing venous return to the heart and lowering cardiac output and arterial pressure. Stretch receptors in the carotid sinus and aortic arch (baroreceptors) sense the pressure drop and rapidly increase signaling to the brainstem, which reduces parasympathetic and increases sympathetic outflow to the heart and blood vessels. The result, within seconds, is a faster heart rate, stronger cardiac contractions, vasoconstriction in the splanchnic and skin beds, and contraction of leg veins, all of which restore blood pressure and brain perfusion before any symptoms occur. When this reflex fails, as in some elderly patients or people on certain medications, orthostatic hypotension produces dizziness or fainting on standing. The example illustrates how multiple components (heart, vessels, autonomic nervous system) integrate to maintain steady internal conditions despite continuous external challenges.")
    r("the cardiovascular system", "misconception",
      "A common misconception is that the heart's left side is 'arterial' and the right side is 'venous' as a permanent property; in fact, the right side of the heart pumps deoxygenated blood (returning from systemic veins) into the pulmonary arteries, while the left side pumps oxygenated blood (returning from pulmonary veins) into the systemic arteries. Another misconception is that arteries always carry oxygenated blood and veins always carry deoxygenated blood; the pulmonary arteries are the famous exception (carrying deoxygenated blood from heart to lungs), and the pulmonary veins return oxygenated blood to the heart. People also sometimes think the heart is purely under nervous control; in fact, the heart's intrinsic pacemaker keeps it beating even when isolated from all neural input, with the autonomic nervous system modulating but not initiating the rhythm. Finally, the equation of high blood pressure with stress and lifestyle missed the substantial role of genetics, age, kidney function, and salt sensitivity, all of which interact with behavior to determine an individual's pressure trajectory.")

    # ---- the endocrine system ----
    r("the endocrine system", "definition",
      "The endocrine system is the network of glands and tissues that secrete hormones into the bloodstream, where they travel to distant target cells and regulate physiology. Major endocrine glands include the hypothalamus, pituitary, thyroid, parathyroids, adrenals, pancreas (islets), gonads (ovaries and testes), and pineal gland; many other tissues including the heart, kidneys, gastrointestinal tract, adipose tissue, and even bone produce hormones with important systemic effects. Hormones range chemically from peptides and proteins (insulin, growth hormone, oxytocin) to steroids derived from cholesterol (cortisol, estradiol, testosterone) to amine derivatives of amino acids (epinephrine, thyroid hormone). They act by binding specific receptors on or inside target cells, triggering intracellular signaling cascades or directly altering gene transcription. The endocrine system regulates metabolism, growth, reproduction, water balance, stress response, sleep cycles, and many other processes, working in tight coordination with the nervous system through the hypothalamus.")
    r("the endocrine system", "mechanism",
      "The endocrine system works through hormone synthesis, secretion, transport, receptor binding, and feedback regulation. Hormones are typically synthesized and stored in glandular cells, released into capillary blood in response to triggering signals (neural, hormonal, or metabolic), transported through the circulation to all tissues, and recognized only by cells with the matching receptor. Receptor binding triggers a response: G-protein-coupled receptors and tyrosine kinase receptors initiate cytoplasmic signaling cascades that change cellular activity within minutes; intracellular receptors for steroid and thyroid hormones bind hormone-receptor complexes to specific DNA sequences, altering transcription of target genes over hours. Feedback loops keep hormone levels regulated: most hormones inhibit their own production through negative feedback at upstream control centers, so rising cortisol levels suppress further ACTH secretion from the pituitary, and rising thyroid hormone suppresses TSH. Disruption of any element (synthesis defect, receptor mutation, autoimmune destruction, ectopic hormone production by tumors) produces characteristic endocrine disorders.")
    r("the endocrine system", "significance",
      "The endocrine system matters because hormones coordinate processes across the entire body that would be difficult to manage with neural signaling alone, and disorders of endocrine function are among the most common chronic diseases. Diabetes mellitus, with hundreds of millions of people affected globally, results from inadequate insulin secretion (type 1) or insulin resistance combined with relative insulin deficiency (type 2), with downstream consequences for the cardiovascular, renal, and nervous systems. Thyroid disorders, both hypo- and hyperthyroidism, are common and treatable with hormone replacement or anti-thyroid medications. Reproductive endocrinology underpins fertility treatment, contraception, hormone replacement therapy, and gender-affirming care. Stress hormones regulate the response to physical and psychological challenges and are implicated in chronic disease through pathways including allostatic load. Modern medicine increasingly leverages hormones (growth hormone, GLP-1 receptor agonists for obesity and diabetes, leuprolide for hormone-sensitive cancers) as targeted interventions, and ongoing research continues to expand the catalog of endocrine signals and their roles in metabolism, immunity, behavior, and aging.")
