#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank part 3 of 3: technology, everyday life/health/finance, current events (fresh for batch E)."""


def register(T):
    # ===== TECHNOLOGY =====

    T["containerization with Docker"] = {
        "_cat": "technology",
        "what": "an OS-level virtualization approach that packages applications with their dependencies into isolated, portable units called containers, sharing the host kernel but each running with its own filesystem, processes, and network namespace",
        "how": "Docker uses Linux kernel features like namespaces (for isolation of processes, network, mounts) and cgroups (for resource limits) to give each container the appearance of a private OS. Images are built from layered filesystems described by a Dockerfile, stored in registries, and instantiated as containers by the Docker engine. Container orchestrators like Kubernetes manage clusters of containers",
        "why": "containers solve the dependency-hell problem of deploying applications across environments, give consistent dev/staging/prod parity, enable microservices and immutable infrastructure, and underpin modern CI/CD pipelines. They are foundational to current cloud-native architectures",
        "vs": "containers differ from VMs by sharing the host kernel rather than running a full guest OS, making them faster to start (seconds vs minutes) and lighter on resources, at the cost of weaker isolation. They differ from chroot by adding namespaces and cgroups, and from FreeBSD jails or Solaris zones by their tooling and ecosystem",
        "ex": "a typical web app might package its Node.js runtime, application code, and config into a Docker image. The image runs identically on a developer's laptop, in CI, and in production on Kubernetes, removing the 'works on my machine' class of bugs",
        "mis": "people think containers are equivalent to VMs in security. They share the host kernel; a kernel exploit can break out of the container. Another myth is that Docker invented containers; LXC, FreeBSD jails, and Solaris zones predate Docker, which mainly made containers easy to use and share",
    }

    T["the OSI model"] = {
        "_cat": "technology",
        "what": "a conceptual seven-layer reference model from ISO that describes how networking systems should communicate, with each layer (physical, data link, network, transport, session, presentation, application) handling specific responsibilities and providing services to the layer above",
        "how": "data sent by an application is encapsulated layer by layer: application data gets a transport header (TCP/UDP), then a network header (IP), then a data-link header (Ethernet), then converted to electrical or radio signals at the physical layer. The receiver strips headers in reverse. Each layer sees only its peer's information, providing modular abstraction",
        "why": "the OSI model gives engineers a common vocabulary for network problems, separates concerns cleanly, and lets vendors interoperate without coordinating every detail. Even though the actual internet uses a four-layer TCP/IP stack, OSI's seven layers remain the dominant teaching framework",
        "vs": "the OSI model differs from the TCP/IP model, which collapses sessions, presentation, and application into a single application layer. It differs from cleaner unifications like Tanenbaum's five-layer model. In practice, OSI layer 5-7 distinctions are rarely meaningful in production protocols",
        "ex": "an HTTPS request is application data wrapped in TLS (presentation/session functions), then TCP (transport), then IP (network), then Ethernet or Wi-Fi (data link), then radio waves or wires (physical). Each header serves a distinct purpose and is parsed independently by the relevant layer",
        "mis": "people think modern protocols implement the seven OSI layers literally. The actual internet uses TCP/IP's four layers, with OSI layers 5-6 functions usually folded into application protocols. Another myth is that the layer numbers map cleanly to specific products; firewalls, switches, and load balancers operate at multiple layers depending on configuration",
    }

    T["how garbage collection works"] = {
        "_cat": "technology",
        "what": "automatic memory management performed by language runtimes (Java, Go, Python, JavaScript, C#) that identifies objects no longer reachable from program roots and reclaims their memory, freeing programmers from explicit allocation and deallocation",
        "how": "tracing collectors start from root references (stack variables, globals, registers) and traverse the object graph marking reachable objects; unmarked objects are reclaimed. Modern collectors use generational hypotheses (most objects die young, so collect young generations more often), incremental and concurrent algorithms (to limit pause times), and compaction to reduce fragmentation",
        "why": "garbage collection eliminates whole classes of bugs (use-after-free, double-free, memory leaks from forgotten frees), improves programmer productivity, and enables safer abstractions. It is foundational to most modern productivity-oriented languages",
        "vs": "garbage collection differs from manual memory management (C, C++) by not requiring explicit free calls. It differs from reference counting (Python's primary mechanism) by handling cycles correctly. It differs from arena allocation, which frees groups of objects together rather than tracking individual lifetimes",
        "ex": "Go's tricolor mark-and-sweep collector runs concurrently with the application, achieving sub-millisecond pause times even on heaps of tens of gigabytes. Java's G1 and ZGC, JavaScript's V8 collector, and the .NET CLR's collector all use sophisticated generational, incremental designs",
        "mis": "people think GC eliminates all memory bugs; you can still leak memory by holding references to objects you no longer need. Another myth is that GC always pauses the program for long stretches; modern collectors run mostly concurrently, with pauses well under a millisecond on tuned systems",
    }

    T["public-key infrastructure"] = {
        "_cat": "technology",
        "what": "the system of certificate authorities, registration authorities, repositories, and policies that manage digital certificates binding public keys to identities, enabling parties who do not previously know each other to trust each other's keys",
        "how": "a certificate authority (CA) verifies an applicant's identity and signs a certificate (an X.509 document) tying the applicant's public key to its identity. Browsers and operating systems ship with a list of trusted root CAs. Certificates can be revoked via CRLs (certificate revocation lists) or OCSP (online checking). Certificate Transparency logs publicly record issuance to deter fraud",
        "why": "PKI underpins HTTPS (every secure website depends on it), code signing, email signing (S/MIME), and document signing. Without PKI, we could not bootstrap secure communication with strangers on the internet, since exchanging keys directly with every counterparty does not scale",
        "vs": "PKI differs from web-of-trust models like PGP, where users sign one another's keys without a hierarchical CA structure. It differs from symmetric-key infrastructures, where pre-shared keys must be distributed out of band. It also differs from emerging decentralized identity systems (DIDs) that aim to replace CAs with blockchain-based trust",
        "ex": "when you visit a major website over HTTPS, your browser checks that the site's certificate was signed by a trusted CA, that the certificate covers the domain you are visiting, that it has not expired, and that it has not been revoked. All this happens in milliseconds before any application data is exchanged",
        "mis": "people think PKI guarantees a website is safe; it only guarantees that the certificate's key matches the named domain. Another myth is that all CAs are equally trustworthy; CA breaches and mis-issuance have caused real-world attacks, prompting Certificate Transparency and revocation improvements",
    }

    T["B-tree indexes in databases"] = {
        "_cat": "technology",
        "what": "a self-balancing tree data structure used by most relational databases as the default index type, allowing logarithmic-time lookup, insertion, and range scans on sorted keys, optimized for storage on block devices like disks and SSDs",
        "how": "a B-tree (or its B+-tree variant) keeps keys in nodes that pack many keys per node (matching disk page size), keeps leaves at the same depth, and rebalances on insert and delete. Searches traverse from root to leaf, doing one page read per level. With branching factors in the hundreds, billion-row tables typically need only 4 or 5 page reads per lookup",
        "why": "B-trees turn O(N) full-table scans into O(log N) lookups for indexed queries, support range queries efficiently, and remain the workhorse index across PostgreSQL, MySQL, SQL Server, Oracle, and SQLite. Their performance shapes how database schemas are designed and queries optimized",
        "vs": "B-trees differ from hash indexes, which support equality lookups in O(1) average time but no range scans. They differ from LSM trees (used by Cassandra, RocksDB, LevelDB), which optimize writes via sequential log segments at the cost of slower reads. They differ from bitmap indexes used in analytical databases",
        "ex": "querying 'SELECT * FROM users WHERE last_name = ?' on a 100-million-row table takes microseconds with a B-tree index on last_name and full seconds without. Range scans like 'WHERE age BETWEEN 30 AND 40' also benefit because B-trees keep keys sorted",
        "mis": "people think indexes always speed up queries. Indexes slow down writes (every insert must update each index) and can hurt performance for queries that touch large fractions of rows, where a full scan beats random index lookups. Another myth is that indexes are free; they consume substantial storage and memory",
    }

    T["how SSDs work"] = {
        "_cat": "technology",
        "what": "solid-state drives are non-volatile storage devices that use NAND flash memory cells to store data without moving parts, offering much faster random access and lower latency than spinning hard disks at higher cost per byte",
        "how": "each NAND cell traps electrons in a floating gate to represent one or more bits (SLC, MLC, TLC, QLC encode 1, 2, 3, 4 bits per cell). The controller manages flash translation (mapping logical addresses to physical pages), wear leveling (spreading writes across cells), garbage collection (consolidating valid data so erase blocks can be reclaimed), and ECC (correcting bit errors that accumulate with wear)",
        "why": "SSDs transformed personal computing and the data center: laptops boot in seconds, databases handle far more transactions, and entire architectures (caching layers, in-memory databases) shifted as random I/O latency dropped from milliseconds to microseconds",
        "vs": "SSDs differ from HDDs by having no moving parts, much faster random access, lower latency, but historically higher cost per byte and finite write endurance. They differ from RAM by being non-volatile but slower (microseconds vs nanoseconds), and from hybrid drives by using only flash storage",
        "ex": "a modern NVMe SSD reads at over 5 gigabytes per second sequentially and handles hundreds of thousands of random IOPS, compared to a 7,200 RPM HDD's 100-200 IOPS. The difference reshapes how operating systems schedule I/O and how applications structure data layout",
        "mis": "people think SSDs wear out quickly. Modern consumer drives last hundreds of terabytes of writes, far more than typical lifetime usage. Another myth is that defragmentation helps SSDs; on flash, sequential and random access have similar performance, and defragmenting wastes write endurance",
    }

    T["how DNS works"] = {
        "_cat": "technology",
        "what": "the Domain Name System is the hierarchical, distributed naming system that translates human-readable domain names like example.com into numerical IP addresses that computers use to route traffic, along with related records like mail server addresses and text records",
        "how": "a client sends a query to a recursive resolver. The resolver consults the root name servers (which know the top-level domains), then the TLD servers (which know authoritative servers for each domain), then the authoritative server for the target domain. Caching at each level, with TTLs (time-to-live values), reduces load. DNSSEC adds cryptographic signatures to prevent spoofing",
        "why": "DNS is the addressing layer of the internet's user-facing services, allowing humans to use stable names while underlying IP addresses change. Outages and misconfigurations of DNS regularly cause major internet incidents, making DNS literacy critical for any internet engineer",
        "vs": "DNS differs from a flat hosts file by being distributed and globally consistent. It differs from service discovery systems like Consul or Kubernetes' internal DNS, which target dynamic backend services within an organization. DNS also differs from DNS-over-HTTPS or DNS-over-TLS, which add encryption to the queries",
        "ex": "looking up wikipedia.org sends queries through the resolver, root, .org TLD servers, and finally Wikipedia's authoritative servers. The whole process typically completes in milliseconds, with most steps cached at the resolver and at the user's machine",
        "mis": "people think DNS is just a phone book. It is a distributed protocol with caching, hierarchy, and failure modes. Another myth is that DNS is encrypted by default; classic DNS sent queries in plaintext, which is why DNS-over-HTTPS and DNS-over-TLS are now being deployed",
    }

    T["machine learning overfitting"] = {
        "_cat": "technology",
        "what": "the failure mode in supervised learning where a model fits the training data closely, including its noise and idiosyncrasies, and consequently performs poorly on new data drawn from the same distribution",
        "how": "overfitting occurs when model capacity exceeds what the data supports: the model's parameters can memorize training noise rather than learn the underlying signal. Symptoms include training error far below validation error, performance that degrades when training-set perturbations should not matter, and brittle predictions in deployment",
        "why": "controlling overfitting is the central craft of machine learning. Without proper validation, a model that looks excellent on training data may fail catastrophically on real-world inputs, causing financial losses, safety incidents, or scientific errors",
        "vs": "overfitting differs from underfitting, where the model lacks capacity to capture the signal at all. It differs from distribution shift, where the test distribution itself differs from training. It differs from leakage, where training data inadvertently contains information about the test labels",
        "ex": "a polynomial of degree 20 fit to 21 noisy data points passes through every point exactly but oscillates wildly between them. A degree-3 polynomial misses some points but extrapolates much better. The same dynamic plays out in deep networks, where capacity must be balanced against data size and regularization",
        "mis": "people think bigger models always overfit more. Modern overparameterized neural networks often generalize well despite far exceeding training-data interpolation capacity, a phenomenon sometimes called benign overfitting. Another myth is that high training accuracy means a good model; without held-out evaluation, training metrics tell you almost nothing",
    }

    T["the actor model in concurrency"] = {
        "_cat": "technology",
        "what": "a model of concurrent computation in which independent actors communicate solely by passing immutable messages, each actor processes one message at a time, and actors can spawn other actors and supervise them, avoiding shared mutable state and explicit locking",
        "how": "each actor has a private mailbox; sending a message enqueues it, and the actor processes messages one at a time in arrival order. Actors maintain private state, can change behavior between messages, and can create or supervise other actors. Failure is handled via supervision hierarchies (popularized by Erlang's let-it-crash philosophy), where a supervisor decides whether to restart, resume, or stop a failed child",
        "why": "the actor model maps cleanly to distributed systems, fault tolerance, and concurrency without shared memory. It is the foundation of Erlang/OTP, Akka, and Microsoft Orleans, powering systems from telecommunications switches to multiplayer game backends to streaming pipelines",
        "vs": "actors differ from shared-memory threading by exchanging messages instead of mutating shared state, eliminating data races but adding message-handling complexity. They differ from CSP-style channels (Go) by sending to addressable inboxes rather than synchronizing on channels. They differ from microservices by running in-process and being lighter weight",
        "ex": "WhatsApp famously ran on a small number of Erlang servers serving hundreds of millions of users, with each connection represented as a lightweight actor. Telecommunications switches running Erlang/OTP have achieved nine-nines uptime over decades by leveraging supervision and hot code reloading",
        "mis": "people think actors are inherently slow because of message-passing overhead. Erlang's BEAM and Akka achieve millions of messages per second per core. Another myth is that actors eliminate the need for distributed-systems thinking; they manage local concurrency well, but distributed actor systems still face partition, latency, and ordering issues",
    }

    T["functional programming"] = {
        "_cat": "technology",
        "what": "a programming paradigm that treats computation as the evaluation of pure mathematical functions, avoids mutable state and side effects, treats functions as first-class values, and emphasizes composition, immutability, and explicit handling of effects",
        "how": "functional programs build computations by composing functions that take inputs to outputs without modifying anything else. Recursion replaces loops; algebraic data types and pattern matching replace ad-hoc unions; persistent data structures provide efficient immutability; monads or effect systems model effects (I/O, state, errors) explicitly. Type systems (Haskell, OCaml) catch many bugs at compile time",
        "why": "functional code tends to be easier to reason about, parallelize, test, and refactor, since there is no hidden global state. Many ideas (lambdas, generics, immutability, async/await, pattern matching) entered mainstream languages from FP, reshaping how developers think about state and modularity",
        "vs": "functional programming differs from imperative programming (which sequences statements that change state) and from object-oriented programming (which encapsulates state inside objects with methods). Pure FP languages (Haskell) differ from impure functional languages (OCaml, Scala, F#, Clojure) in how strictly they isolate effects",
        "ex": "in Haskell, a function 'sum' that adds the elements of a list is defined recursively without modifying any variables. The same input always produces the same output, the function can be composed with others freely, and the compiler can parallelize and optimize aggressively because there are no hidden dependencies",
        "mis": "people think FP is academic and impractical. Real systems (Jane Street, Standard Chartered, WhatsApp, Discord, Bloomberg) run substantial FP code in production. Another myth is that FP forbids state entirely; it confines state to specific types or monads, making it explicit rather than ubiquitous",
    }

    T["how a CDN works"] = {
        "_cat": "technology",
        "what": "a content delivery network is a globally distributed network of caching servers (edge nodes) deployed close to users that store copies of web content (HTML, images, video, scripts) and serve them to nearby users, reducing latency and offloading traffic from origin servers",
        "how": "when a user requests content, DNS or HTTP routing directs them to the nearest CDN edge node. If the edge has the content cached and fresh, it serves it immediately. If not, it fetches from the origin (or an upstream cache layer), stores the response, and serves it. Cache invalidation, header-based control, geographic load balancing, and TLS termination are part of the CDN's job",
        "why": "CDNs reduce page load times from hundreds of milliseconds to tens, lower bandwidth costs for origins, absorb traffic spikes and DDoS attacks, and enable global services to feel local. Almost every major website uses one or more CDNs",
        "vs": "CDNs differ from origin servers by being geographically distributed and read-optimized. They differ from cloud regions by focusing on edge caching rather than full compute. They differ from peer-to-peer content distribution (BitTorrent) by being centrally managed and SLA-backed",
        "ex": "Netflix's Open Connect places caching appliances directly inside ISP networks worldwide. When a Netflix user starts a movie, the bytes flow from a cache often inside the same building as their broadband router rather than from a distant data center, dramatically improving streaming quality",
        "mis": "people think CDNs are only for large traffic sites. Even small sites benefit from latency reduction, TLS termination, and DDoS protection. Another myth is that CDNs always serve cached content; modern CDNs run dynamic logic at the edge (Cloudflare Workers, Fastly Compute, AWS Lambda@Edge)",
    }

    # ===== EVERYDAY / HEALTH / FINANCE =====

    T["how to read a credit report"] = {
        "_cat": "everyday",
        "what": "a credit report is a record compiled by credit bureaus (Equifax, Experian, TransUnion in the US) summarizing a consumer's borrowing history, including open and closed accounts, payment history, public records, and recent inquiries, used by lenders to assess creditworthiness",
        "how": "to read your report, check personal information for accuracy, review each account for correct balance and payment history, look for accounts you do not recognize (a sign of fraud), inspect public records (bankruptcies, judgments) and collections, count hard inquiries (which lower scores temporarily), and dispute errors directly with the bureau in writing",
        "why": "credit reports drive loan approvals, interest rates on mortgages and auto loans, rental applications, insurance pricing, and sometimes employment screenings. Errors are common (about a quarter of reports have at least one), and unaddressed mistakes can cost thousands in higher rates or denied credit",
        "vs": "credit reports differ from credit scores. The report is the underlying data; the score (FICO, VantageScore) is a number computed from the data. Reports also differ across bureaus, since not all creditors report to all three",
        "ex": "reviewing your free annual report from AnnualCreditReport.com, you might find a closed credit card listed as open or a paid collection still showing a balance. Disputing in writing with documentation and following up with both the bureau and the original creditor typically resolves errors within 30-45 days",
        "mis": "people think checking your own report hurts your score; soft pulls (consumer-initiated) do not affect scoring. Another myth is that closing an unused card always helps; closing reduces total available credit and shortens average account age, often hurting scores",
    }

    T["food allergies vs intolerances"] = {
        "_cat": "everyday",
        "what": "food allergies are immune-system reactions in which the body produces IgE antibodies against specific food proteins, while food intolerances are non-immune adverse reactions, typically due to enzyme deficiencies or chemical sensitivities, with very different mechanisms and severity profiles",
        "how": "in a true food allergy, IgE antibodies on mast cells bind the allergen on second exposure, releasing histamine and other mediators within minutes. Symptoms range from hives to anaphylaxis. Intolerances (lactose, fructose, FODMAPs) involve insufficient digestive enzymes or sensitivities, producing GI symptoms over hours without immune involvement",
        "why": "the distinction matters because allergies can be life-threatening and warrant epinephrine auto-injectors and strict avoidance, while intolerances are uncomfortable but rarely dangerous and often allow small amounts. Misdiagnosing one as the other leads to unnecessary restriction or, worse, dangerous exposure",
        "vs": "allergies differ from intolerances by mechanism (IgE vs enzymatic), speed (minutes vs hours), severity (potentially fatal vs uncomfortable), and tolerable dose (essentially none vs varying). Both differ from food aversions, which are psychological, and from celiac disease, which is autoimmune (T-cell mediated, not IgE)",
        "ex": "a peanut-allergic person can experience anaphylaxis from trace exposure on shared utensils, while a lactose-intolerant person can typically eat hard cheese (which has little lactose) and yogurt (which has bacterial lactase) without trouble. Same word, very different physiology",
        "mis": "people use 'allergy' for any unwanted reaction. Most claimed food allergies are actually intolerances. Another myth is that intolerances will eventually become allergies; they are mechanistically different and do not progress along the same axis",
    }

    T["the flu shot"] = {
        "_cat": "everyday",
        "what": "an annual vaccination against influenza viruses, formulated each year based on World Health Organization predictions of which strains will dominate, typically containing inactivated viruses or recombinant proteins from three or four influenza strains",
        "how": "WHO and national health agencies analyze global influenza surveillance data and select strains for the next season's vaccine. Manufacturers produce billions of doses, primarily by growing virus in chicken eggs (slower) or cell cultures (faster). The shot exposes the immune system to viral antigens, which produces antibodies against the included strains; protection peaks 2-4 weeks after vaccination and lasts the season",
        "why": "influenza causes 290,000-650,000 deaths globally per year. Vaccination reduces hospitalization risk for high-risk groups (elderly, children, pregnant women, immunocompromised) and reduces transmission. Even when strain match is imperfect, partial protection still typically reduces severity",
        "vs": "the flu shot differs from the COVID-19 vaccine in target virus, strain selection process, and platform (most flu vaccines are inactivated; some COVID vaccines are mRNA). It differs from a permanent vaccine like measles because influenza mutates rapidly, requiring annual reformulation. It differs from antiviral drugs (oseltamivir), which treat existing infection",
        "ex": "the 2023-2024 Northern Hemisphere flu vaccines targeted four strains: two influenza A subtypes (H1N1 and H3N2) and two influenza B lineages. CDC end-of-season analysis estimated about 40 percent reduction in symptomatic illness, typical for years of moderate strain match",
        "mis": "people think the flu shot can give you the flu. Inactivated vaccines contain no live virus and cannot. Mild side effects (sore arm, brief malaise) reflect the immune response, not infection. Another myth is that the vaccine is useless when match is imperfect; even partial protection meaningfully reduces severity and complications",
    }

    T["sunscreen and SPF"] = {
        "_cat": "everyday",
        "what": "sunscreen is a topical product that absorbs or reflects ultraviolet radiation to reduce skin damage. SPF (sun protection factor) measures protection against UVB rays specifically; a separate broad-spectrum designation covers UVA",
        "how": "chemical sunscreens (avobenzone, oxybenzone, octinoxate) absorb UV photons via aromatic ring electrons. Mineral sunscreens (zinc oxide, titanium dioxide) primarily reflect and scatter. SPF is measured as the ratio of UV needed to redden sunscreened skin to UV needed to redden bare skin, so SPF 30 lets through 1/30th of burning UVB. Reapplication every two hours and after swimming maintains the rated protection",
        "why": "UV exposure causes sunburn, photoaging, and most skin cancers (basal cell, squamous cell, and melanoma). Daily sunscreen use measurably reduces all three. Sunscreen is among the highest-leverage low-cost preventive habits available, especially for fair-skinned people in sunny climates",
        "vs": "SPF measures UVB protection only; UVA, which causes deeper photoaging and contributes to cancer, is captured by 'broad-spectrum' labels (US) or PA+/PPD ratings (Asia). Sunscreen differs from sunblock (an older term meaning physical barrier) and from UPF clothing, which measures fabric protection rather than chemical product",
        "ex": "applying about a teaspoon to the face and a shot-glass amount to the body is the lab test condition for SPF; most people apply about a quarter to a half of that, getting roughly the square root of labeled SPF in practice. SPF 50 applied at half coverage protects about as well as SPF 7 applied properly",
        "mis": "people think SPF 100 is twice as protective as SPF 50. SPF 50 blocks 98 percent of UVB; SPF 100 blocks 99 percent, only marginally better. Another myth is that dark skin does not need sunscreen; while melanin offers significant protection, melanoma in darker-skinned people is often diagnosed later and has higher mortality",
    }

    T["how blood pressure works"] = {
        "_cat": "everyday",
        "what": "blood pressure is the force exerted by circulating blood on artery walls, expressed as two numbers: systolic (peak pressure during heart contraction) over diastolic (lowest pressure between beats), measured in millimeters of mercury (mmHg)",
        "how": "the heart's left ventricle ejects blood into the aorta, raising pressure (systolic). Between beats, elastic recoil of the arteries maintains residual pressure (diastolic). Pressure is determined by cardiac output (heart rate times stroke volume) and total peripheral resistance (the constriction of small arterioles regulated by the autonomic nervous system, kidneys, and hormones). Normal is below 120/80 mmHg",
        "why": "chronic high blood pressure (hypertension) is the leading modifiable risk factor for stroke, heart disease, kidney failure, and cognitive decline. Modest reductions (5-10 mmHg systolic) substantially lower these risks. Hypertension is often called the silent killer because it usually has no symptoms until organ damage occurs",
        "vs": "high blood pressure differs from anxiety-driven temporary spikes, which do not damage tissues over time. It differs from low blood pressure (hypotension), which can cause dizziness and fainting but is typically less harmful unless severe. Pulse pressure (systolic minus diastolic) is itself a separate prognostic indicator",
        "ex": "lifestyle interventions (DASH diet, sodium reduction, regular aerobic exercise, weight loss, alcohol reduction, smoking cessation) can lower systolic pressure by 5-15 mmHg, often comparable to a single medication. For higher pressures, medication classes include ACE inhibitors, ARBs, calcium channel blockers, thiazide diuretics, and beta-blockers",
        "mis": "people think you only need to worry if your reading is high. Both numbers carry information; isolated systolic hypertension (high systolic, normal diastolic) is common in older adults and dangerous. Another myth is that home readings are unreliable; properly taken home measurements are often more representative than single clinic readings, which suffer white-coat effect",
    }

    T["caffeine effects on the body"] = {
        "_cat": "everyday",
        "what": "caffeine is a methylxanthine stimulant that crosses the blood-brain barrier and exerts effects on the central nervous system, cardiovascular system, kidneys, and skeletal muscle, primarily by blocking adenosine receptors that promote sleepiness",
        "how": "caffeine binds A1 and A2A adenosine receptors as a competitive antagonist, blocking adenosine's normal sleep-promoting and vasodilating effects. This indirectly raises dopamine and norepinephrine activity, increases heart rate and blood pressure modestly, and stimulates the cortex. Half-life is about 5 hours but varies from 2 to 12 hours by individual due to CYP1A2 enzyme variants",
        "why": "caffeine is the most widely used psychoactive substance globally and influences alertness, productivity, athletic performance, headache (both relief and rebound), and sleep quality. Understanding its kinetics helps optimize dosing for performance without disrupting sleep",
        "vs": "caffeine differs from amphetamines, which release dopamine and norepinephrine directly and are far more potent and addictive. It differs from theobromine (in chocolate) and theophylline (medicinal), which share methylxanthine structure but have weaker CNS effects. It differs from L-theanine (in tea), which counterbalances caffeine's anxiogenic effects",
        "ex": "an 8-oz cup of coffee contains about 80-100 mg caffeine. With a 5-hour half-life, drinking coffee at 4 PM still leaves about half the caffeine in your system at 9 PM, which is why afternoon caffeine measurably degrades sleep quality even when you fall asleep without trouble",
        "mis": "people think caffeine dehydrates you. Mild diuresis is real, but the fluid in coffee or tea more than offsets the loss; caffeinated drinks count toward hydration. Another myth is that tolerance fully eliminates effects; tolerance to alertness is partial, while tolerance to cardiovascular effects develops more completely",
    }

    T["mortgage refinancing"] = {
        "_cat": "finance",
        "what": "mortgage refinancing is replacing an existing home loan with a new one, typically to obtain a lower interest rate, change the loan term, switch from adjustable to fixed rate, or extract home equity through a cash-out refinance",
        "how": "the homeowner applies for a new loan that pays off the existing one. The lender appraises the property, verifies income and credit, calculates closing costs (typically 2-5 percent of loan amount), and at closing the new loan replaces the old. Break-even analysis compares closing costs to monthly savings to determine when refinancing pays off",
        "why": "refinancing can save tens of thousands of dollars over a loan's life when rates drop, free up cash flow during financial stress (longer term, lower payment), or accelerate principal repayment (shorter term, higher payment but less interest). It is one of the most consequential financial decisions homeowners make",
        "vs": "rate-and-term refinancing differs from cash-out refinancing, which extracts equity for other uses but raises the loan balance. It differs from a HELOC (home equity line of credit), which adds a second lien rather than replacing the first. It differs from loan modification, where the existing lender adjusts terms during hardship",
        "ex": "a homeowner with a $300,000 mortgage at 7 percent who refinances to 5 percent saves about $400 per month. With $9,000 in closing costs, break-even is about 23 months. Beyond that, every additional month of holding the home is pure savings",
        "mis": "people think a lower rate alone justifies refinancing. Closing costs, remaining term, and how long you plan to stay all matter. Another myth is that you should refinance whenever rates drop; if you are 5 years into a 30-year loan and refinance to a fresh 30-year, you may pay more total interest despite a lower rate",
    }

    T["how 401(k) plans work"] = {
        "_cat": "finance",
        "what": "a 401(k) is an employer-sponsored retirement savings plan in the US that allows employees to contribute pre-tax (or Roth post-tax) earnings into investment accounts, often with employer matching contributions, with significant tax advantages and contribution limits set annually by the IRS",
        "how": "employees elect to defer a percentage of salary into the plan, where it is invested in a menu of mutual funds, target-date funds, or sometimes company stock. Pre-tax contributions reduce taxable income; investment growth is tax-deferred until withdrawal. Employers often match a percentage (commonly 50 percent of contributions up to 6 percent of salary). Withdrawals before age 59 1/2 typically incur a 10 percent penalty plus income tax",
        "why": "401(k) plans are the primary retirement savings vehicle for most Americans. Employer matching is effectively free money; combined tax advantages and compound growth over decades produce nest eggs that defined-benefit pensions used to provide. Decisions about contribution rate, fund choice, and rollover at job change have lifetime financial impact",
        "vs": "401(k) plans differ from traditional IRAs (lower contribution limits but more investment choice, no employer match), from Roth 401(k)s (taxes paid up front, withdrawals tax-free), and from defined-benefit pensions (employer-managed, paying defined retirement income rather than investment-based balance). They differ from taxable brokerage accounts by tax-deferral and contribution limits",
        "ex": "a 30-year-old contributing 10 percent of a $60,000 salary with a 50 percent employer match up to 6 percent saves $9,000 per year ($6,000 own + $1,800 match + tax deferral on contributions). At a 7 percent real return, that grows to about $1.2 million by age 65, more than enough to support modest retirement spending",
        "mis": "people think they cannot afford to contribute. The pre-tax discount and employer match often mean that contributing 6 percent only reduces take-home pay by 4 percent or so. Another myth is that target-date funds are bad; for most savers, low-cost target-date funds are a perfectly good default and beat ad-hoc fund picking",
    }

    T["index investing"] = {
        "_cat": "finance",
        "what": "an investment strategy of buying broad-market index funds (mutual funds or ETFs) that track an index like the S&P 500 or total stock market, holding them long-term, and rebalancing periodically, in preference to selecting individual stocks or active funds",
        "how": "an index fund holds the same securities in the same proportions as the underlying index, automatically tracking its performance minus a small expense ratio. Investors typically allocate across asset classes (stocks, bonds, international) according to risk tolerance, contribute regularly, and rebalance to maintain target weights. Tax-advantaged accounts (401(k), IRA) and tax-loss harvesting in taxable accounts further enhance after-tax returns",
        "why": "decades of evidence (Bogle, Sharpe, Fama, Malkiel, SPIVA reports) show that most active managers underperform their benchmarks after fees, and the few who outperform are not predictable in advance. Index investing captures market returns with minimal fees, often 0.03-0.10 percent annually for total-market funds, vs 0.5-1.5 percent for active funds",
        "vs": "index investing differs from active management (selecting stocks or timing markets to beat the index) by accepting market returns rather than seeking alpha. It differs from individual stock picking by spreading risk across hundreds or thousands of holdings. It differs from factor or thematic ETFs by tracking broad market caps rather than tilting toward style or theme",
        "ex": "a Vanguard Total Stock Market Index Fund charges 0.03 percent and has matched the US market's roughly 10 percent nominal long-term annual return. A 25-year-old investing $500 per month in such a fund through age 65 ends with about $1.4 million at average returns, mostly from compounding rather than contributions",
        "mis": "people think they can pick winning active funds based on past performance. Persistent outperformance is rare and not reliably predictable. Another myth is that indexing produces only average returns; given fee drag and the difficulty of beating the market, average gross returns minus low fees beats most active strategies after costs",
    }

    T["how a budget works"] = {
        "_cat": "everyday",
        "what": "a budget is a plan that allocates expected income across spending categories and savings goals over a defined period (typically a month), helping match spending to income, build savings, and track progress toward financial goals",
        "how": "list all sources of net (after-tax) income. List fixed expenses (rent, utilities, insurance, debt minimums), variable necessities (groceries, gas), discretionary spending (entertainment, dining), and savings goals (emergency fund, retirement, specific targets). Subtract expenses from income; iterate until the result is non-negative. Track actual spending and adjust monthly. Common templates: 50/30/20 (needs/wants/savings) and zero-based",
        "why": "budgeting reduces the gap between intentions and behavior, builds emergency savings (a top determinant of financial resilience), prevents lifestyle inflation, identifies spending leaks, and converts vague goals into concrete weekly decisions. People who budget consistently report lower financial stress and higher savings rates",
        "vs": "budgeting differs from one-time financial planning by being a recurring discipline. It differs from net-worth tracking, which measures position rather than flow. Zero-based budgets differ from envelope budgeting (cash in physical envelopes per category) and from 50/30/20 rules (percentage targets) in their level of precision",
        "ex": "a couple earning $6,000 net per month might budget $1,800 rent, $400 utilities and insurance, $600 groceries, $300 transportation, $400 dining and entertainment, $500 to retirement (in addition to 401(k)), $300 to emergency fund, $400 to debt payoff, $400 sinking funds (vacation, car repairs), $400 buffer. Tracking actual vs planned each month reveals where reality differs",
        "mis": "people think budgeting is restrictive. Done well, it is a tool for consciously spending on what matters by reducing waste on what does not. Another myth is that you need to track every penny; even rough percentage tracking outperforms unmonitored spending for most people",
    }

    T["how sleep affects health"] = {
        "_cat": "everyday",
        "what": "sleep is a regulated brain state with profound effects on metabolic, cardiovascular, immune, cognitive, and mental health, with adults generally needing 7-9 hours per night for optimal function and chronic deficits accumulating measurable harm over time",
        "how": "during sleep, the brain cycles through stages (NREM 1-3 and REM), each performing specific functions: slow-wave sleep clears metabolic waste via the glymphatic system and consolidates declarative memory; REM consolidates procedural memory and processes emotion. Sleep also regulates hormones (cortisol, growth hormone, leptin, ghrelin), supports immune function, and lets the cardiovascular system recover from daily load",
        "why": "chronic short sleep raises risk of obesity, type 2 diabetes, cardiovascular disease, depression, dementia, and accidents. Even one night of 4-5 hours' sleep measurably impairs reaction time and judgment to a degree comparable with alcohol intoxication. Improving sleep is among the highest-leverage health interventions",
        "vs": "sleep differs from rest in that the brain actively processes information during sleep rather than just recovering passively. It differs across stages (slow-wave vs REM) in physiology and function. Sleep duration and continuity matter separately; fragmented sleep is harmful even when total time is adequate",
        "ex": "in randomized studies, restricting sleep to 4 hours per night for a week produced glucose tolerance levels comparable to early type 2 diabetes in healthy young adults. Returning to 8-hour sleep restored normal function. Habitual sleep restriction produces more durable harm",
        "mis": "people think they have adapted to short sleep. Subjective adaptation is real (people stop noticing they feel tired), but objective performance and biomarkers continue to suffer. Another myth is that you can catch up on weekends; while one good weekend partially restores acute deficit, chronic patterns leave residual harm",
    }

    T["estate planning basics"] = {
        "_cat": "finance",
        "what": "estate planning is the process of arranging the management and disposition of one's assets and personal affairs in case of incapacity or death, including wills, trusts, beneficiary designations, powers of attorney, and healthcare directives",
        "how": "core documents include a will (directs asset distribution), a durable power of attorney (delegates financial authority during incapacity), a healthcare proxy and living will (delegate medical decisions and specify wishes), and beneficiary designations on retirement accounts and life insurance (which override the will). Trusts can avoid probate, manage assets for minors, or address taxes. Periodic review (every 3-5 years or after major life events) keeps the plan current",
        "why": "without an estate plan, state intestacy laws determine asset distribution, courts appoint guardians for minor children, and family members face probate delays and disputes. Even modest estates benefit from clear documents, and complex estates need them to avoid unintended outcomes. Healthcare directives in particular spare families from anguished decisions",
        "vs": "wills differ from trusts: wills go through probate (public, slow), while assets in revocable living trusts pass directly to beneficiaries. Estate planning differs from tax planning, which optimizes lifetime tax burden, and from asset protection, which shields assets from creditors. Healthcare directives differ from financial powers of attorney by their scope",
        "ex": "a 35-year-old couple with two young children might have wills naming a guardian for the children, a revocable living trust holding the house and investment accounts, durable powers of attorney for finances, healthcare proxies with HIPAA authorizations, and beneficiary designations naming each other primary and the trust contingent on retirement accounts and life insurance",
        "mis": "people think only the wealthy need estate plans. Even renters with no assets need a healthcare proxy and a guardian designation if they have children. Another myth is that documents drafted decades ago still work; old documents often reference deceased relatives, outdated statutes, and inappropriate trust structures",
    }

    # ===== CURRENT EVENTS =====

    T["the rise of generative AI"] = {
        "_cat": "current_events",
        "what": "the wave of artificial intelligence systems based on large neural networks trained on vast text, image, audio, and code corpora, capable of generating high-quality novel outputs in those modalities, that emerged into broad public awareness with ChatGPT's launch in late 2022 and accelerated through 2023-2026",
        "how": "transformer architectures (Vaswani et al., 2017) scaled with massive compute, large web-scraped data, and reinforcement learning from human feedback (RLHF) produced models that perform broadly across language tasks. Diffusion models did the same for images. Multimodal models combine modalities. Chain-of-thought, tool use, and agentic frameworks extended capabilities. Costs of training frontier models reached the hundreds of millions of dollars",
        "why": "generative AI is reshaping software development, content creation, customer service, scientific research, and creative work, with macroeconomic implications comparable to electricity or the internet. It also raises serious questions about misinformation, copyright, employment displacement, AI safety, alignment, and concentration of power among a handful of frontier labs",
        "vs": "current generative AI differs from earlier symbolic AI by being statistical and learned end-to-end rather than rule-based. It differs from narrow ML systems (image classifiers, recommender systems) by exhibiting broad fluency. It differs from artificial general intelligence in lacking robust agency, persistent memory, and reliable reasoning across novel domains",
        "ex": "ChatGPT reached 100 million users within two months of launch in late 2022, the fastest consumer product adoption in history at the time. By 2024-2025, GPT-4-class and Claude 3 Opus-class models were drafting code, writing marketing copy, summarizing research, and powering autonomous agents in production deployments",
        "mis": "people think these models think or understand. They are statistical predictors trained to continue text plausibly, with emergent capabilities that look like reasoning but lack grounding, persistence, or self-awareness. Another myth is that progress will continue exponentially indefinitely; data, compute, and algorithmic ceilings are real and contested",
    }

    T["climate change adaptation"] = {
        "_cat": "current_events",
        "what": "the set of policies, infrastructure investments, and behavioral changes that reduce vulnerability to ongoing and projected climate impacts (heat waves, floods, droughts, wildfires, sea-level rise), complementary to mitigation (reducing greenhouse gas emissions)",
        "how": "adaptation includes upgrading drainage and seawalls for storm surge, retrofitting buildings for heat tolerance, shifting agricultural varieties and planting dates, restoring wetlands and mangroves for coastal protection, planning managed retreat from highest-risk zones, building cooling centers, redesigning insurance and emergency response, and integrating climate projections into long-term infrastructure decisions",
        "why": "even with rapid mitigation, the climate already locked in by past emissions guarantees decades of further change. Adaptation is essential to limit harm, especially to poorer populations and regions with the least capacity to absorb shocks. Failure to adapt amplifies humanitarian crises, displacement, and economic damage",
        "vs": "adaptation differs from mitigation, which seeks to stop further warming by reducing emissions; adaptation copes with warming already occurring. Soft adaptation (planning, behavior) differs from hard adaptation (infrastructure). Maladaptation refers to interventions that backfire (seawalls that worsen flooding elsewhere, air conditioning that increases emissions)",
        "ex": "the Netherlands' Room for the River program, started in 2007, deliberately widened floodplains, lowered dykes in some places, and relocated farms to give rivers space to rise without flooding cities. The cost ran into billions of euros but provides robust flood protection compatible with rising sea levels and intensifying rainfall",
        "mis": "people think adaptation lets us avoid mitigation. Adaptation has limits; some impacts (ocean acidification, ecosystem collapse, multi-meter sea-level rise) cannot be adapted to at any plausible cost. Another myth is that wealthy countries can adapt without affecting the rest of the world; climate-driven migration and economic shocks are global by nature",
    }

    T["remote work after the pandemic"] = {
        "_cat": "current_events",
        "what": "the persistent shift toward working from home or hybrid arrangements that began as an emergency response to COVID-19 in early 2020 and has substantially outlived the pandemic, especially for knowledge workers in technology, finance, professional services, and government",
        "how": "the pandemic forced a wholesale technology and process upgrade: video conferencing (Zoom, Teams), collaborative documents (Notion, Google Docs), asynchronous communication (Slack), and outcome-based management replaced in-person defaults. Many workers and employers found the new arrangements productive enough that fully returning to office became politically and economically untenable, settling into hybrid (typically 2-3 days in-office) for many roles",
        "why": "remote work reshapes commercial real estate, urban geography, talent markets, family life, and corporate culture. Cities that depend on office workers face fiscal challenges; employees gain time and flexibility but may lose mentorship and professional networks; companies trade overhead savings for management complexity. The long-term equilibrium is still being negotiated",
        "vs": "remote work differs from teleworking arrangements before 2020 (which existed but were marginal), from gig and freelance work (which were always remote), and from purely asynchronous distributed work (which adds time-zone independence on top of location independence). Hybrid models differ from full remote and full onsite by their attempted compromise",
        "ex": "tech companies like GitLab and Automattic pioneered fully remote operation before the pandemic. Post-2020, even traditionally office-bound firms (banks, law, consulting) settled into 2-3 days in-office hybrid for most knowledge roles, while customer-facing and operations roles largely returned onsite",
        "mis": "people think remote work is uniformly more or less productive. The data is mixed and depends on task type, team maturity, management quality, and worker characteristics. Another myth is that this is a temporary aberration; the durable changes to commercial real estate, software tools, and worker expectations make a full reversion unlikely",
    }

    T["streaming services and the music industry"] = {
        "_cat": "current_events",
        "what": "the transformation of the recorded music business by subscription and ad-supported streaming platforms (Spotify, Apple Music, YouTube Music, Amazon Music, Tidal) that replaced album sales and downloads as the primary revenue source for the industry through the 2010s and 2020s",
        "how": "subscribers pay monthly fees or accept ads; platforms pay rights holders pro-rata royalties based on share of total streams. Major labels (Universal, Sony, Warner) negotiate higher per-stream rates and equity stakes than independents. Algorithmic playlists and recommender systems shape listening; viral phenomena (TikTok) feed streams; tour and merchandise revenue rose to compensate for lower per-recording payouts",
        "why": "streaming reversed the post-Napster decline of recorded music revenue and changed how music is created, marketed, and consumed. Artists optimize for short song hooks (since Spotify counts streams over 30 seconds) and frequent releases. Listeners gain near-unlimited access; artists, especially mid-tier ones, often earn less per fan than under album sales",
        "vs": "streaming differs from physical (CD, vinyl) and digital download eras by replacing ownership with rental access. It differs from radio by user-controlled playback and personalized recommendations. It differs from satellite radio (SiriusXM) and curated services by combining catalog access with algorithmic discovery",
        "ex": "Spotify pays roughly $0.003-$0.005 per stream. A song needs about 250-300 streams to generate one dollar of artist revenue (often reduced further by label and distributor cuts). Achieving a sustainable income through streaming requires either massive scale or heavy supplementation through touring, sync licensing, and merchandise",
        "mis": "people think streaming pays artists nothing. Top artists earn millions; mid-tier artists earn enough to live; the long tail of small artists struggles, but they did under prior models too. Another myth is that streaming services keep most revenue; about 60-70 percent flows to rights holders, with the bulk of artist economics dictated by label contracts",
    }

    T["electric grid challenges with renewables"] = {
        "_cat": "current_events",
        "what": "the technical and economic difficulties of integrating large shares of variable renewable generation (wind and solar) into electric grids designed around dispatchable thermal plants, including issues of intermittency, grid stability, transmission, and storage",
        "how": "wind and solar output varies with weather and time of day, creating mismatches with demand. Grid operators must balance supply and demand instantaneously while maintaining frequency and voltage. Solutions include geographic diversity (combining many sites), storage (batteries, pumped hydro), demand response, transmission expansion, dispatchable backup (gas peakers, hydro), and forecasting. Inverter-based resources also raise stability questions for grids long stabilized by spinning thermal generators",
        "why": "decarbonizing electricity is the foundation for decarbonizing transportation and heating. The technical and policy challenges of high-renewable grids are central to climate strategy. Failures cascade (Texas 2021); successes (California, Germany, Denmark) inform global pathways",
        "vs": "renewables differ from fossil generation by being variable, location-dependent, and inverter-based rather than rotational. They differ from nuclear, which is dispatchable and constant but slow to ramp. Behind-the-meter solar differs from utility-scale plants in interconnection, ownership, and price formation",
        "ex": "California's grid in spring 2024 routinely served over 100 percent of midday demand from solar, requiring exports, curtailment, and large battery storage to absorb afternoon production for evening discharge. Texas's February 2021 winter storm exposed gaps in winterization across all generation types and reshaped grid policy debates",
        "mis": "people think renewables cannot support reliable grids. Multiple regions now run substantial renewable shares reliably with appropriate storage and transmission. Another myth is that storage alone solves intermittency; on weekly and seasonal scales, batteries are not yet cost-effective, and dispatchable backup or long-duration storage is also needed",
    }

    T["the global semiconductor supply chain"] = {
        "_cat": "current_events",
        "what": "the geographically distributed network of fabrication, assembly, design, equipment, and materials companies that produces the semiconductor chips powering virtually every modern electronic device, with extreme specialization concentrated in a handful of firms and geographies",
        "how": "design firms (Nvidia, AMD, Apple, ARM) create chip blueprints. Foundries (TSMC, Samsung, Intel) manufacture wafers. Assembly and test happens in lower-cost locations. Specialized equipment comes from a few suppliers (ASML, Applied Materials, Tokyo Electron). Materials (silicon wafers, photoresists, gases) come from another set of specialized suppliers, particularly in Japan. Cutting-edge nodes require ASML's EUV lithography machines, of which only a few dozen are produced annually",
        "why": "semiconductors are critical to economic and military power. Pandemic disruptions and US-China tensions exposed how concentrated and fragile the supply chain is. National policies (US CHIPS Act, EU Chips Act, China's massive investments) are restructuring the industry, with profound implications for trade, security, and innovation",
        "vs": "the modern chip supply chain differs from the integrated-device-manufacturer model of the 1990s, in which firms like Intel did everything from design to manufacturing. Today's fabless-foundry split achieves specialization at the cost of geographic concentration. It differs from commodity manufacturing by extreme capital intensity (a leading-edge fab costs $20+ billion)",
        "ex": "TSMC, in Taiwan, manufactures over 90 percent of the world's most advanced chips (5nm and below). Apple's iPhone processors, Nvidia's AI accelerators, and AMD's CPUs all depend on TSMC. A geopolitical shock affecting Taiwan would be catastrophic for global electronics supply",
        "mis": "people think semiconductor manufacturing can be re-shored quickly. Building a leading-edge fab takes 3-5 years and tens of billions of dollars; training the workforce takes longer. Another myth is that all chips are similar; cutting-edge logic, memory, analog, and power semiconductors involve different processes, suppliers, and economics",
    }

    T["rising healthcare costs"] = {
        "_cat": "current_events",
        "what": "the persistent and outsized growth of healthcare spending in the United States and (to a lesser extent) other high-income countries, where health spending now consumes 17-18 percent of US GDP and continues to grow faster than the overall economy",
        "how": "drivers include aging populations needing more care, expensive new technologies and drugs, fragmented payer-provider negotiation that lacks single-payer leverage, administrative complexity (the US has thousands of insurance plans with separate billing), provider consolidation reducing competition, defensive medicine, and high prices for the same services compared to peer countries",
        "why": "healthcare costs constrain wages (employer premiums substitute for raises), strain government budgets (Medicare, Medicaid, ACA subsidies), drive medical bankruptcy, and shape political debates about insurance, drug pricing, and provider regulation. The US pays roughly twice as much per capita as comparable wealthy countries with similar or worse outcomes",
        "vs": "the US system differs from single-payer systems (Canada, UK, Taiwan) by lacking centralized price negotiation. It differs from regulated multi-payer systems (Germany, Switzerland) by allowing wider variation in coverage and pricing. The US also differs in overall spending, prices for specific services, and administrative costs",
        "ex": "the same MRI that costs $500-$1,000 in Germany, France, or Japan typically costs $1,500-$3,500 in the US, despite using the same equipment and similar labor. Hospital prices for common procedures vary by 5-10x within a single US city, reflecting opaque negotiated rates rather than cost differences",
        "mis": "people think US healthcare is expensive because of higher utilization. Americans actually have fewer doctor visits and hospital stays per capita than peers; the difference is prices. Another myth is that single-payer would automatically reduce costs; while administration would simplify, political support for higher prices to providers would persist absent reform",
    }

    T["the gig economy"] = {
        "_cat": "current_events",
        "what": "the labor market segment in which workers earn income through short-term, on-demand engagements via digital platforms (Uber, DoorDash, Instacart, Upwork, TaskRabbit) rather than through traditional employment relationships with benefits and stable schedules",
        "how": "platforms match workers with consumer demand in real time using GPS, ratings, and dynamic pricing. Workers are typically classified as independent contractors, bearing their own expenses (vehicle, equipment, taxes) and lacking employer-provided benefits. Some jurisdictions (California's AB5, the UK Supreme Court's Uber ruling) have reclassified or expanded protections, while platforms have lobbied for separate regulatory categories",
        "why": "the gig economy has reshaped the labor market for transportation, delivery, freelance services, and increasingly knowledge work. It offers flexibility but shifts risk and benefits cost from firms to workers, raising fundamental questions about employment classification, social insurance, and inequality",
        "vs": "gig work differs from traditional employment by its lack of fixed schedule, benefits, and employer accountability. It differs from earlier freelance work by platform-mediated matching and rating systems. It differs from on-call employment by the absence of a long-term employer relationship",
        "ex": "Uber drivers in major US cities typically earn $15-$25 per hour after expenses, comparable to or below local minimum-wage jobs once vehicle wear, fuel, taxes, and lack of benefits are accounted for. Top earners in dense markets with strong demand can do better, but average net pay has trended down as competition has grown",
        "mis": "people think gig work is mostly side income. While many workers use it that way, a substantial share of platform workers depend on it as primary income. Another myth is that flexibility comes free; in practice, peak earnings require working when the platforms surge demand, often nights and weekends",
    }

    T["how SNAP and food assistance work"] = {
        "_cat": "current_events",
        "what": "the Supplemental Nutrition Assistance Program (SNAP, formerly food stamps) is the largest US federal anti-hunger program, providing monthly benefits to low-income households on EBT cards usable at authorized retailers for most groceries (excluding hot prepared foods, alcohol, and non-food items)",
        "how": "households apply through state agencies, which determine eligibility based on income (typically gross income at or below 130 percent of poverty), assets, and household size. Benefits are calculated to cover the gap between expected food spending and the Thrifty Food Plan budget. Recipients use EBT cards at participating retailers; benefits cannot be exchanged for cash. Work requirements apply to able-bodied adults without dependents in many states",
        "why": "SNAP serves about 41-42 million Americans (roughly 12-13 percent of the population) and is the largest federal anti-hunger program, costing about $100 billion annually. It substantially reduces food insecurity, has measurable long-run benefits for child health and economic mobility, and acts as an automatic stabilizer during recessions",
        "vs": "SNAP differs from WIC (Women, Infants, and Children), which targets specific nutritional needs of pregnant women and young children with prescribed food packages. It differs from school meal programs and from Medicaid (which covers health rather than food). It differs from cash welfare (TANF), which provides cash assistance with stricter time limits",
        "ex": "an average SNAP household receives about $230 per month per person, around $1.40 per meal. Programs like Double Up Food Bucks match SNAP spending at farmers' markets to stretch benefits and improve fresh food access. Pandemic emergency allotments expanded benefits substantially in 2020-2023 before phasing out",
        "mis": "people think SNAP recipients are mostly unemployed. Most SNAP households with working-age adults include at least one worker. Another myth is that SNAP fraud is rampant; payment-error and trafficking rates have fallen to about 1-2 percent, lower than for many private-sector benefits",
    }

    T["the housing affordability crisis"] = {
        "_cat": "current_events",
        "what": "the widespread mismatch between housing costs and household incomes in many cities and regions, marked by rising rents, soaring home prices relative to wages, increased homelessness, and a substantial share of households spending over 30 percent of income on housing",
        "how": "drivers include restrictive land-use regulations (single-family zoning, height limits, parking minimums), permitting delays, NIMBY opposition, decades of underbuilding relative to job and population growth, low interest rates that pushed up asset prices, and concentration of high-paying jobs in a few metros. The result is a chronic supply shortage in productive regions, especially in coastal US cities, the UK, Canada, Australia, and parts of continental Europe",
        "why": "housing affordability shapes inequality, mobility, family formation, fertility, productivity (workers cannot afford to move to high-productivity regions), and political polarization. It also drives homelessness, displaces communities, and constrains the labor force in places that most need workers",
        "vs": "the affordability crisis differs from cyclical housing downturns by being structural and persistent. It differs from luxury housing markets by hitting middle-income workers, not just the poor. It differs from rural housing challenges, where the issue is often dilapidation or lack of jobs rather than price",
        "ex": "in the San Francisco Bay Area, median home prices exceed $1.3 million, requiring over $250,000 household income to qualify for a typical mortgage. A teacher, nurse, or firefighter cannot live near where they work. Tokyo, by contrast, kept prices roughly stable for decades by permitting and building roughly 100,000 new units per year",
        "mis": "people think the crisis is caused mainly by foreign buyers or institutional investors. While they contribute, the dominant driver in most metros is supply restriction. Another myth is that building luxury housing does not help; even high-end construction filters down through chains of moves, expanding effective supply at all price points",
    }

    T["the opioid epidemic"] = {
        "_cat": "current_events",
        "what": "the public health crisis of opioid addiction and overdose deaths in the United States and other countries, driven first by aggressive prescribing of opioid painkillers in the 1990s-2010s, then by heroin and fentanyl-laced street drugs, with over 100,000 US overdose deaths per year recently",
        "how": "the first wave (mid-1990s-2010) followed prescribing changes after Purdue Pharma promoted OxyContin as low-risk for chronic pain. The second wave (around 2010) shifted to heroin as restricted prescribing pushed addicted users to street alternatives. The third wave (around 2013 onward) saw illicit fentanyl, vastly more potent than heroin, contaminate the drug supply, driving overdose deaths to record levels",
        "why": "the opioid crisis has killed over a million Americans, devastated communities, strained child welfare and emergency services, and exposed deep failures of pharmaceutical regulation, pain medicine, and public health response. It has reshaped opioid prescribing, drug policy, and corporate accountability",
        "vs": "the current opioid crisis differs from earlier US drug epidemics (1980s crack, 1970s heroin) by being driven initially by legal prescribing, by reaching deeply into rural and white communities, and by the lethality of fentanyl. It differs from prior pain medicine reforms by the scale of corporate liability ($50+ billion in settlements)",
        "ex": "Naloxone (Narcan), an opioid receptor antagonist, can reverse an overdose if administered in time. Wide distribution of naloxone, including over-the-counter availability since 2023, has saved tens of thousands of lives. Medication-assisted treatment with buprenorphine or methadone substantially improves long-term recovery odds compared to abstinence-only approaches",
        "mis": "people think addiction reflects weak character. Opioid use disorder is a neurological condition shaped by drug pharmacology, genetics, trauma, and environment. Another myth is that pain patients commonly become addicted; the rate among carefully managed patients is much lower than the rate among recreational users",
    }

    T["the metaverse"] = {
        "_cat": "current_events",
        "what": "a hypothesized network of persistent, immersive virtual worlds in which users represented as avatars socialize, work, play, and transact across interconnected platforms, often via VR or AR headsets, popularized by Meta's 2021 rebrand and contested by skeptics ever since",
        "how": "core technologies include VR headsets (Meta Quest, Sony PlayStation VR2, Valve Index), AR systems (Apple Vision Pro, Microsoft HoloLens), 3D engines (Unity, Unreal), networking (low-latency synchronization across thousands of users), and economic layers (some involving blockchain, some not). Companies invested tens of billions of dollars in 2021-2024 in headsets, content, and platforms",
        "why": "the metaverse vision drove substantial investment, reshaped the strategic priorities of Meta (rebranded from Facebook), Apple, and Microsoft, and accelerated VR/AR development. As of 2025-2026, the consumer metaverse remains niche, but spatial computing applications in industry, training, and design have grown",
        "vs": "the metaverse differs from existing online gaming by ambitions of cross-platform persistence and identity. It differs from social media by 3D immersion and embodiment. It differs from web 3 (which focuses on blockchain-based ownership) by focusing on virtual presence rather than decentralized infrastructure, though the two communities overlap",
        "ex": "Apple's Vision Pro, launched in 2024, demonstrated high-end mixed-reality computing but at $3,499 reached limited adoption. Meta's Quest 3 and Quest 3S offered cheaper VR but found their primary market in gaming rather than the broader social metaverse. Industrial uses (training simulations, surgical planning, factory layout) have proven more successful than consumer ones",
        "mis": "people think the metaverse is dead because Meta's broader vision did not materialize on its predicted timeline. Spatial computing and VR/AR continue to develop steadily; the framing has shifted from utopian metaverse to pragmatic mixed-reality applications. Another myth is that the metaverse requires blockchain; most successful platforms (Roblox, Fortnite, VRChat) use traditional infrastructure",
    }

    T["sustainable agriculture"] = {
        "_cat": "current_events",
        "what": "farming approaches that aim to produce food while maintaining environmental health, economic profitability, and social equity over the long term, encompassing practices like crop rotation, cover cropping, reduced tillage, integrated pest management, and improved livestock systems",
        "how": "sustainable practices reduce reliance on synthetic inputs by building soil organic matter, using nitrogen-fixing cover crops, rotating crops to disrupt pest cycles, targeting pesticides only when economic thresholds are crossed, recycling nutrients through livestock-crop integration, and conserving water through drip irrigation and precision agriculture. Certifications (organic, regenerative) and supply-chain commitments scale these practices",
        "why": "agriculture uses about 70 percent of global freshwater, occupies 38 percent of land, and is responsible for 20-25 percent of greenhouse gas emissions. Making farming sustainable is essential to feed 9-10 billion people without further degrading the planet. It also affects food security, rural livelihoods, biodiversity, and water quality",
        "vs": "sustainable agriculture differs from conventional industrial agriculture by reducing external inputs and ecological footprint. It differs from organic farming, which is one specific certification, in being broader and including conventional fertilizers used judiciously. It differs from regenerative agriculture, which emphasizes soil restoration as the core metric",
        "ex": "no-till farming with cover crops on Midwestern US farms can sequester 0.5-1 ton of carbon per hectare annually while reducing fuel use and improving water infiltration. Long-term experiments (Rodale Institute's farming systems trial) show yield-competitive performance after a transition period of 3-5 years",
        "mis": "people think sustainable agriculture cannot feed the world. Yield gaps between sustainable and conventional systems are real but smaller than often claimed and shrink over time. Another myth is that organic equals sustainable; some organic methods (intensive tillage, copper-based fungicides) carry their own ecological costs",
    }

    T["misinformation in elections"] = {
        "_cat": "current_events",
        "what": "the deliberate or accidental spread of false or misleading information about candidates, voting processes, election security, and outcomes, amplified through social media, partisan outlets, and increasingly AI-generated content, threatening informed democratic participation",
        "how": "actors range from foreign state-backed operations to domestic political activists to opportunistic content creators monetizing engagement. Tactics include fabricated stories, manipulated images and videos (including deepfakes), out-of-context clips, conspiracy theories about voting machines, and coordinated inauthentic accounts. Algorithmic amplification rewards emotionally charged content, accelerating spread",
        "why": "misinformation erodes trust in elections, can change voting behavior or turnout in close races, motivates threats against election workers, and corrodes the shared factual basis of democratic deliberation. The 2020 US election and its aftermath, including January 6, 2021, highlighted concrete consequences",
        "vs": "misinformation differs from disinformation, which is intentional, while misinformation can be unintentional sharing of false claims. It differs from biased or partisan reporting, which presents true facts with slant, by being false. It differs from satire, which is recognizable as humor by context",
        "ex": "false claims about Dominion voting machines spread widely during the 2020 US election, contributing to legal action by Dominion against major media outlets. Settlements (including Fox News' nearly $800 million settlement in 2023) demonstrated that some misinformation crossed into actionable defamation",
        "mis": "people think fact-checking eliminates the harm of misinformation. Corrections reach a fraction of the audience exposed to the original false claim and may even strengthen belief through the backfire effect in some cases. Another myth is that misinformation only affects the other side; partisans of all stripes share misinformation that flatters their priors",
    }

    T["the rise of K-pop"] = {
        "_cat": "current_events",
        "what": "the global rise of South Korean popular music since the 2000s, marked by groups like BTS, BLACKPINK, EXO, Twice, and Stray Kids achieving worldwide commercial success, reshaping pop music marketing, fan engagement, and the global cultural footprint of South Korea",
        "how": "Korean entertainment companies (HYBE, SM, JYP, YG) developed an integrated trainee system: years of vocal, dance, language, and media training before debut. They invested heavily in music videos, choreography, and global marketing. Online fandoms organize streaming campaigns, voting drives, and merchandise purchases at industrial scale. Social media (Twitter, YouTube, TikTok, Weverse) connects artists with global fans directly",
        "why": "K-pop has become a major cultural export, contributing meaningfully to South Korea's soft power and economy. BTS's UN speeches, BLACKPINK's Coachella headlining slot, and the genre's broader influence on pop music production, fashion, and choreography mark its arrival as a global force comparable to earlier J-pop or Latin music waves but with greater scale",
        "vs": "K-pop differs from earlier Asian pop exports (J-pop, Cantopop) by its self-consciously global production and marketing. It differs from Western pop in its trainee system, group-centric format, and tighter integration of choreography, fashion, and concept. It differs from US R&B-influenced pop, which it draws from heavily, by its visual and performance density",
        "ex": "BTS's 2018 UN speech and their 2020 Billboard Hot 100 number-one single 'Dynamite' (their first English-language hit) marked turning points. By 2022, the group's tours grossed hundreds of millions of dollars, and BTS-related economic activity contributed an estimated $5 billion annually to the South Korean economy",
        "mis": "people think K-pop is a single genre. K-pop spans hip-hop, EDM, ballad, R&B, and rock influences with distinct group identities. Another myth is that K-pop's success was sudden; the trainee infrastructure and government cultural-export support (Hallyu policy) were built over two decades before the global breakthrough",
    }

    T["the loneliness epidemic"] = {
        "_cat": "current_events",
        "what": "the documented rise in self-reported social isolation, loneliness, and weakened community ties across many high-income countries, with measurable health consequences (increased risk of cardiovascular disease, depression, dementia, and early mortality) declared a public health priority by the US Surgeon General in 2023",
        "how": "drivers include declining participation in civic and religious organizations, longer commutes, more single-person households, shifts from face-to-face socializing to digital interaction, urban design that discourages incidental contact, and the COVID-19 pandemic's lasting effects on social habits. Loneliness is not just being alone; it is the gap between desired and actual social connection, which can occur even amid frequent digital contact",
        "why": "loneliness ranks alongside smoking and obesity as a mortality risk factor. Its rise affects mental health, productivity, civic life, and political polarization. Public health responses include social prescribing (UK), built-environment interventions, age-targeted programs, and broader debates about how technology and urban form shape connection",
        "vs": "loneliness differs from being alone; people can be alone without feeling lonely or surrounded by others while feeling deeply isolated. It differs from depression, though they often co-occur. It differs from introversion, which describes social preference rather than the unmet need that defines loneliness",
        "ex": "Cigna's 2018 US survey found that nearly half of adults reported sometimes or always feeling alone or left out, with Generation Z showing the highest rates. Programs like the UK's Campaign to End Loneliness and Japan's Minister for Loneliness illustrate how seriously governments now take the issue",
        "mis": "people think loneliness is just a feeling. Long-term loneliness changes inflammatory markers, immune function, and stress response measurably. Another myth is that social media causes most of it; evidence is mixed, with social media potentially aggravating loneliness for heavy passive users and alleviating it for those who use it to maintain real relationships",
    }

    T["water scarcity"] = {
        "_cat": "current_events",
        "what": "the chronic or acute mismatch between freshwater demand and accessible supply in a region, affecting roughly 2 billion people who lack safely managed drinking water and many more facing intermittent shortages, agricultural stress, and conflicts over rivers and aquifers",
        "how": "scarcity arises from physical drivers (low precipitation, high evaporation, depleted aquifers, glacier loss) and economic drivers (lack of infrastructure to store, treat, and distribute water). Climate change intensifies droughts and shifts rainfall patterns. Population growth and economic development raise demand. Solutions include efficient irrigation, recycling, desalination, leak reduction, pricing reforms, and watershed protection",
        "why": "water scarcity threatens food production (irrigation uses about 70 percent of freshwater), public health, ecosystems, and political stability. Conflicts over the Nile, the Tigris-Euphrates, the Indus, and the Mekong have geopolitical implications. The Cape Town near-Day-Zero crisis (2018), Chennai's 2019 shortage, and persistent Colorado River basin shortfalls highlight how quickly stress can become crisis",
        "vs": "physical water scarcity (Saudi Arabia, parts of Australia) differs from economic water scarcity (much of sub-Saharan Africa), where rainfall exists but infrastructure does not. It differs from drought, which is temporary, and from water quality problems, where the issue is contamination rather than quantity",
        "ex": "Las Vegas reduced per-capita water use by about 50 percent over two decades through aggressive turf-replacement programs, water recycling, and pricing reforms, even as population grew. Israel reuses about 90 percent of treated wastewater for agriculture and operates large-scale desalination supplying much of municipal demand",
        "mis": "people think desalination solves scarcity broadly. It is energy-intensive (typically 3-4 kWh per cubic meter) and produces brine waste, making it cost-effective only for coastal cities, not interior agriculture. Another myth is that personal use dominates; agriculture and industry vastly outweigh household consumption in most water budgets",
    }

    T["AI in medicine"] = {
        "_cat": "current_events",
        "what": "the application of machine learning and other AI techniques to medical tasks: diagnostic imaging analysis, clinical decision support, drug discovery, clinical documentation, patient triage, and increasingly autonomous diagnostic and therapeutic systems",
        "how": "deep learning models trained on labeled medical images detect conditions (diabetic retinopathy, lung nodules, breast cancer, skin lesions) at performance levels approaching or exceeding specialist physicians on benchmark tasks. Large language models help draft clinical notes, summarize records, and answer questions. Drug discovery tools predict protein structures (AlphaFold) and screen molecules. Regulators (FDA's Software as a Medical Device pathway) have approved hundreds of AI medical devices",
        "why": "AI in medicine promises to reduce errors, expand access (radiology where specialists are scarce), accelerate discovery, and lower costs. Risks include over-reliance, bias against underrepresented populations, opacity of model reasoning, liability ambiguity, and disruption of clinical workflows. The technology is rapidly entering routine practice, raising urgent regulatory and ethical questions",
        "vs": "AI in medicine differs from earlier clinical decision support (rule-based systems) by learning patterns from data rather than encoded expertise. It differs from purely research-stage tools by FDA clearances and reimbursement codes that bring it into clinical practice. It differs from telemedicine, which is care delivery, not algorithmic decision making",
        "ex": "AlphaFold 2 (2020) and AlphaFold 3 (2024) predicted protein structures at near-experimental accuracy across over 200 million proteins, reshaping structural biology. AI-based mammography review tools have been deployed in several European countries' breast cancer screening programs, often as a second reader to catch missed findings",
        "mis": "people think AI will replace doctors imminently. Most successful deployments are augmentation tools that improve specialist throughput rather than autonomous diagnosis. Another myth is that AI is unbiased; training data drawn from specific populations and care patterns can encode disparities, requiring careful validation across demographics",
    }

    T["the rise of plant-based foods"] = {
        "_cat": "current_events",
        "what": "the growth of plant-based meat and dairy alternatives (Impossible Foods, Beyond Meat, Oatly, Just Egg) targeting mainstream consumers rather than only vegetarians, expanding from niche to mass-market shelves and restaurant chains since the late 2010s",
        "how": "food scientists engineer plant proteins (soy, pea, wheat) with binders, fats, and flavor compounds (Impossible's heme via fermented yeast) to mimic meat's texture, taste, and cooking behavior. Production scales through partnerships with traditional food manufacturers and distribution through retail and food service. Marketing emphasizes environmental and health framing rather than vegetarian identity",
        "why": "livestock contributes about 14-15 percent of global greenhouse gas emissions, vast water and land use, and substantial deforestation. Plant-based alternatives could substantially reduce these footprints if they displace meat consumption. Health framing (lower saturated fat, no cholesterol) and animal-welfare framing add additional motivations",
        "vs": "plant-based meat differs from older vegetarian foods (tofu, tempeh, veggie burgers) by targeting omnivore consumers and mimicking meat directly. It differs from cultivated (lab-grown) meat, which uses real animal cells, and from precision-fermentation dairy proteins, which produce molecularly identical proteins via engineered microbes. The category economics differ across these approaches",
        "ex": "Beyond Meat went public in 2019 with the largest first-day stock pop of any major IPO that year, and Impossible Foods rolled into Burger King and other chains. The boom subsided in 2022-2024 as growth slowed and consumers raised concerns about ultra-processed nature, taste, and price relative to conventional meat",
        "mis": "people think plant-based meat is automatically healthier. Many products are highly processed and contain comparable sodium and saturated fat (from coconut or palm oil). Another myth is that they cost more inherently; current price premiums largely reflect scale, not unavoidable cost differences with conventional meat",
    }
