#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank: history topics (fresh for batch G)."""


def register(T):
    T["the Mongol Empire under Genghis Khan"] = {
        "_cat": "history",
        "what": "the largest contiguous land empire in history, forged by Temujin (Genghis Khan) after he unified the Mongol tribes in 1206 and rapidly conquered much of Eurasia, eventually stretching from Korea to Hungary at its height under his successors",
        "how": "Genghis built an army around mounted archers organized in decimal units (arbans, jaguns, mingghans, tumens) with strict meritocratic discipline. Tactics combined feigned retreats, coordinated maneuver across vast distances, intelligence networks, and psychological warfare against besieged cities (surrender to mercy, resist to annihilation). Conquest of the Khwarazmian Empire (1219-1221) and Jin China (1211-1234) demonstrated the playbook; later khans completed Persia, Russia, and Song China",
        "why": "the Mongol conquests killed perhaps 30 to 40 million people and reshaped Eurasia: they ended the Abbasid Caliphate, fragmented Russian principalities, opened the Silk Road for safe travel under the Pax Mongolica, accelerated transmission of gunpowder, paper money, and printing westward, and indirectly catalyzed the Black Death's spread along trade routes",
        "vs": "the Mongol Empire differed from earlier nomadic confederations like the Xiongnu and Gokturks in scale, durability, and administrative reach into sedentary societies. It differs from later land empires like the Russian and Qing in being created in a single lifetime by mounted cavalry rather than over centuries with gunpowder armies",
        "ex": "the sack of Baghdad in 1258 by Hulagu Khan ended the 500-year Abbasid Caliphate, killed an estimated 200,000 to 1,000,000 inhabitants, destroyed the House of Wisdom and its libraries, and ended the city's status as the intellectual capital of the Islamic world. The trauma remains a touchstone in Middle Eastern memory",
        "mis": "people think the Mongols only destroyed. They also built sophisticated administrations, employed talent from conquered peoples (Persian financiers, Chinese engineers, Uighur scribes), promoted religious tolerance, and protected long-distance trade. Another myth is that the empire collapsed quickly; it fragmented into khanates (Yuan, Ilkhanate, Chagatai, Golden Horde) that ruled for over a century",
    }

    T["the Reformation and the printing press"] = {
        "_cat": "history",
        "what": "the sixteenth-century religious and political upheaval in which reformers, beginning with Martin Luther's 1517 Ninety-Five Theses, broke with the Roman Catholic Church over indulgences, papal authority, and access to scripture, producing Lutheran, Reformed, and other Protestant traditions",
        "how": "Luther's theses, originally a scholarly invitation to debate, were translated, printed, and distributed across the Holy Roman Empire within weeks thanks to Gutenberg's movable-type press. His later writings were among the first mass-market bestsellers. The press carried German Bibles to literate laity, broke the clergy's monopoly on scriptural interpretation, and let reformers reach across borders that had previously stopped manuscript circulation. Political rulers (German princes, Henry VIII, Scandinavian kings) seized the moment to assert independence from Rome",
        "why": "the Reformation fractured western Christendom, triggered confessional wars (the Thirty Years' War killed roughly a third of the Holy Roman Empire's population), reshaped European politics around state churches, accelerated literacy, and prepared the ground for the Enlightenment and the modern separation of church and state",
        "vs": "the Reformation differs from earlier reform movements (Wycliffe, Hus, the conciliar movement) in succeeding rather than being suppressed, largely because of the printing press and political timing. It differs from the Counter-Reformation, the Catholic response that reformed internal abuses, codified doctrine at Trent, and launched the Jesuits without conceding to Protestant claims",
        "ex": "Luther's German New Testament, completed in 1522, sold tens of thousands of copies within months at a time when an entire community might own a single book. Priced within reach of artisan households, it standardized the German language, reshaped lay piety, and demonstrated the press's power to bypass institutional gatekeepers",
        "mis": "people think Luther wanted to start a new church. He sought reform within Catholicism and was excommunicated only after years of conflict. Another myth is that the Reformation was purely religious; political, economic, and linguistic forces intertwined, and the choice between Catholic and Protestant often turned on local princely calculation as much as theology",
    }

    T["the Roman Republic to Empire transition"] = {
        "_cat": "history",
        "what": "the prolonged political crisis from roughly 133 BCE to 27 BCE during which the Roman Republic's constitutional norms broke down under the weight of empire, civil wars, and personalized armies, ending when Octavian (Augustus) consolidated power as the first emperor",
        "how": "expansion after the Punic Wars created vast wealth concentrated in elite hands while displacing small farmers. The Gracchi brothers' reforms in the 130s and 120s BCE were defeated violently. Generals like Marius, Sulla, Pompey, and Caesar built personal armies loyal to commanders rather than the Senate. Civil wars culminated in Caesar's assassination in 44 BCE and the second triumvirate's collapse at Actium in 31 BCE. Octavian carefully preserved republican forms while accumulating tribunician, consular, and proconsular powers, becoming Princeps in 27 BCE",
        "why": "Rome's transition shaped Western political theory's understanding of how republics fail (cited by every American Founder), set the template for Mediterranean and European politics for fifteen centuries, and produced the cultural infrastructure (Latin, Roman law, road networks, Christianity's eventual platform) on which medieval and modern Europe were built",
        "vs": "the late Republic differs from the early Republic in the size of the army, the length of commands, the commercialization of politics, and the breakdown of mos maiorum (ancestral custom). The Augustan principate differs from later autocratic regimes by maintaining the fiction of restored republic, where Diocletian's dominate dropped the pretense entirely three centuries later",
        "ex": "Caesar's crossing of the Rubicon in January 49 BCE with the 13th Legion violated the law against entering Italy under arms and triggered civil war. The phrase 'crossing the Rubicon' has entered every Western language as shorthand for an irrevocable decision, exactly because Romans recognized in real time that the Republic could not survive armed generals with personal armies",
        "mis": "people think Augustus made himself king. He pointedly avoided the title rex, holding instead a stack of nominally republican offices (princeps senatus, tribunicia potestas, imperium proconsulare). The legal disguise was as important as the underlying reality. Another myth is that the Republic ended at Caesar's death; it had been malfunctioning for a century and took fifteen more years of war for Augustus to settle the new order",
    }

    T["the Industrial Revolution in Britain"] = {
        "_cat": "history",
        "what": "the sustained transformation of Britain's economy from roughly 1760 to 1840, during which mechanized production, steam power, factory organization, coal extraction, and railways multiplied productivity and population, beginning the long climb out of Malthusian stagnation",
        "how": "convergent factors enabled liftoff: cheap coal in accessible seams, naval-protected colonial markets, financial markets willing to fund infrastructure, agricultural improvements freeing labor for cities, patent and property institutions encouraging invention, and a critical mass of skilled artisans. Watt's improved steam engine (1769) made stationary power flexible. Cotton spinning and weaving mechanized in cascading waves; iron production scaled with coke smelting; canals and then railways collapsed transport costs. Wages, life expectancy, and literacy rose unevenly across decades while inequality and urban squalor exploded",
        "why": "the Industrial Revolution permanently broke the link between population and per-capita income that had constrained every previous society, launched modern economic growth, redrew global power toward Western Europe, and created the working class, factory cities, and labor movements that defined the next two centuries",
        "vs": "the British Industrial Revolution differs from earlier proto-industrial expansions (Song China, late medieval Flanders) in being self-sustaining rather than reverting. It differs from later industrializations (Germany, US, Japan) in being first, slower, and more reliant on tinkering artisans than on state-led science. It differs from the Second Industrial Revolution (chemicals, electricity, internal combustion, around 1870-1914) in its energy and material foundations",
        "ex": "the Stockton and Darlington Railway opened in 1825 as the first public steam railway, hauling coal at unprecedented cost reductions. The 1830 Liverpool and Manchester line proved passenger rail viable; within twenty years Britain had a national network and was exporting locomotives globally, demonstrating how a single transport innovation can compound across an entire economy",
        "mis": "people think industrialization was driven by 'a few great inventors'. The actual story features tens of thousands of small improvements by anonymous mechanics, supported by social institutions that rewarded tinkering. Another myth is that wages collapsed everywhere; data show real wages stagnated for decades early on but rose substantially after 1820, especially with skilled labor, with deep regional and occupational variation",
    }

    T["the Cold War and the nuclear arms race"] = {
        "_cat": "history",
        "what": "the geopolitical confrontation between the United States and the Soviet Union from 1947 to 1991, characterized by ideological rivalry, proxy wars, an unprecedented arms race centered on nuclear weapons, and the threat of mutual destruction that shaped every aspect of international affairs",
        "how": "after WWII, the wartime alliance dissolved over Eastern Europe. The US adopted containment, articulated in Kennan's 1946 'Long Telegram'. NATO and the Warsaw Pact formalized blocs. Both sides built nuclear arsenals from a few warheads to tens of thousands by the 1980s, accompanied by ICBMs, submarines, and bombers in a triad designed to survive a first strike. Crises (Berlin 1948 and 1961, Cuba 1962) repeatedly brought the world close to war. Detente in the 1970s and arms control treaties (SALT, START, INF) capped and then reduced arsenals; the Soviet Union's 1991 collapse ended the rivalry",
        "why": "the Cold War reshaped global politics, drove enormous military and scientific investment (the space race, the internet, nuclear power, satellite navigation), created lasting institutional structures (NATO, the EU's predecessor, Bretton Woods), and left a nuclear arsenal that still defines great-power security. Its end remade Europe and reset post-1991 expectations, which subsequent events (NATO expansion, Russia's 2022 invasion of Ukraine) have unwound to varying degrees",
        "vs": "the Cold War differed from earlier great-power rivalries in being conducted under nuclear deterrence rather than direct combat between principals, in being framed ideologically as well as strategically, and in producing proxy conflicts (Korea, Vietnam, Afghanistan, Angola) rather than continental wars in Europe. It differs from current US-China rivalry in the relative absence of deep economic interdependence",
        "ex": "the Cuban Missile Crisis of October 1962 brought the superpowers within hours of war when US reconnaissance discovered Soviet medium-range missiles in Cuba. Thirteen days of brinkmanship ended with a public Soviet withdrawal in exchange for a public US no-invasion pledge and a secret withdrawal of Jupiter missiles from Turkey. It directly led to the Moscow-Washington hotline and accelerated arms control negotiations",
        "mis": "people think MAD made nuclear war impossible. Multiple near-misses (1983 Petrov incident, Able Archer 83, the Norwegian rocket incident in 1995) show stable deterrence required vigilance and luck. Another myth is that the Cold War was bipolar throughout; the Sino-Soviet split, the Non-Aligned Movement, and shifting Western European positions made the actual landscape more multipolar than the binary framing suggested",
    }

    T["the Meiji Restoration in Japan"] = {
        "_cat": "history",
        "what": "the political revolution of 1868 that ended the Tokugawa shogunate, restored imperial rule under Emperor Meiji, and launched a comprehensive program of modernization that transformed Japan from a feudal polity into an industrialized nation-state within a generation",
        "how": "Commodore Perry's 1853 arrival exposed Japan's military vulnerability and sparked debate. Lower samurai from Choshu and Satsuma overthrew the shogun and proclaimed imperial restoration in 1868. The new government abolished feudal domains (haihan-chiken, 1871), the samurai class and its privileges, and the four-class social hierarchy. They sent the Iwakura Mission abroad to study Western institutions, then imported and adapted constitutional law (1889), conscription, public education, banking, railways, factories, and a modern military, all under the slogan fukoku kyohei (rich country, strong army)",
        "why": "Japan became the first non-Western great power, defeated China (1895) and Russia (1905), built a colonial empire, and demonstrated to the world that industrialization was not a uniquely Western achievement. Meiji-era institutions shaped twentieth-century Japan and inspired modernizing reformers from Turkey to Thailand. The trajectory also led directly to militarism and WWII, raising hard questions about modernization without democratization",
        "vs": "the Meiji Restoration differs from China's parallel modernization attempts (Self-Strengthening Movement, Hundred Days Reform), which were stymied by the Qing court and conservative officials. It differs from European revolutions in being elite-led, top-down, and aimed primarily at preserving sovereignty rather than democratizing. The Iwakura Mission's Bismarckian model contrasts with revolutionary ruptures elsewhere",
        "ex": "in 1872 the new government opened Japan's first railway between Shimbashi (Tokyo) and Yokohama, built with British engineering. Twenty years later domestic engineers were laying track; thirty years later Japanese-built warships defeated the Russian Pacific fleet. The compression of catch-up across one generation has few parallels in modern history",
        "mis": "people think Meiji Japan slavishly copied the West. Reformers were highly selective: French-style civil law, German-style constitution, British-style navy, American-style elementary schools, and Japanese-style household and emperor at the center. Another myth is that the restoration was bloodless; the Boshin War, Satsuma Rebellion, and peasant uprisings produced significant casualties as old elites resisted",
    }

    T["the colonization of the Americas"] = {
        "_cat": "history",
        "what": "the European invasion, settlement, and exploitation of the Americas beginning with Columbus in 1492 and continuing for four centuries, during which Spanish, Portuguese, English, French, and Dutch powers conquered indigenous polities, introduced Old World diseases, imposed extractive economies, and reshaped global demography and ecology",
        "how": "Spanish conquistadors exploited indigenous political fractures, military technology gaps (steel, horses, firearms), and devastating epidemics (smallpox, measles, influenza) that killed an estimated 90 percent of indigenous populations within a century. Encomienda and later hacienda systems extracted labor and tribute. Silver and gold from Potosi and Mexico flowed to Europe. Plantation agriculture in the Caribbean, Brazil, and the southern English colonies relied on enslaved African labor transported via the Atlantic slave trade. Settler colonies pushed indigenous peoples off land they then farmed",
        "why": "the Columbian Exchange transferred maize, potatoes, tomatoes, cassava, and chocolate from the Americas to Europe and wheat, sugarcane, cattle, horses, and pathogens in the other direction, restructuring global food systems and populations. Silver from Potosi catalyzed early modern global trade. The transatlantic slave trade displaced 12.5 million Africans and built plantation economies. The genocide of indigenous peoples, dispossession of land, and imposition of European institutions still shape the social structure of the Americas",
        "vs": "American colonization differs from contemporaneous European trading-post colonialism in Asia, where Europeans rarely held inland power until the eighteenth century. It differs in scale of demographic catastrophe from any other documented contact between civilizations. It differs across regions: Spanish and Portuguese colonization integrated more with indigenous populations and led to mestizo majorities; northern English colonies excluded indigenous peoples more thoroughly",
        "ex": "the conquest of the Aztec Empire by Hernan Cortes in 1519-1521 illustrates the pattern. With perhaps 600 Spaniards, Cortes recruited tens of thousands of indigenous allies (Tlaxcala, Texcoco) who resented Aztec hegemony, exploited smallpox that swept Tenochtitlan during the siege, and toppled an empire of millions. The conquest of the Inca by Pizarro in 1532-1533 followed the same template",
        "mis": "people think Europeans conquered through technological superiority alone. Disease and indigenous allies did most of the actual work; Spanish forces were almost always small. Another myth is that pre-Columbian populations were sparse; estimates of the indigenous population of the Americas in 1492 range from 50 to 100 million, comparable to Europe's, with sophisticated cities and agricultural systems",
    }

    T["the Cuban Revolution"] = {
        "_cat": "history",
        "what": "the armed insurrection led by Fidel Castro's 26th of July Movement that overthrew Fulgencio Batista's US-backed dictatorship on January 1, 1959, and was followed by socialist transformation, alignment with the Soviet Union, and decades of confrontation with the United States",
        "how": "after a failed 1953 attack on the Moncada Barracks, Castro and surviving comrades regrouped in Mexico, returned to Cuba in 1956 aboard the yacht Granma, and waged guerrilla war from the Sierra Maestra. Urban resistance, peasant support, and Batista's brutality eroded the regime's legitimacy. Batista fled on January 1, 1959. The new government nationalized US-owned sugar, oil, and banking assets in 1960; the US imposed an embargo and broke relations. Castro declared Cuba socialist in 1961 and turned to the Soviet Union for economic and military backing, leading to the Bay of Pigs invasion's failure and the 1962 missile crisis",
        "why": "the Cuban Revolution shifted Cold War dynamics into the Western hemisphere, inspired left-wing movements across Latin America, prompted decades of US covert action, and produced one of the longest-running socialist experiments outside Eastern Europe. Cuba's medical and educational expansion, sponsorship of African liberation movements, and persistent poverty and emigration are all parts of the same legacy",
        "vs": "the Cuban Revolution differs from earlier Latin American coups in producing a sustained socialist regime rather than personalist dictatorship. It differs from the Chinese and Russian revolutions in originating from a small guerrilla force rather than mass party organization. The 26th of July Movement's foco theory, articulated later by Che Guevara, inspired but rarely succeeded in other countries",
        "ex": "the 1962 Cuban Missile Crisis was a direct consequence of the revolution: Soviet leader Khrushchev placed nuclear missiles on Cuba to deter another US-sponsored invasion after the failed 1961 Bay of Pigs. The thirteen-day standoff ended with Soviet withdrawal of the missiles, US no-invasion pledge, and quiet US withdrawal of Jupiter missiles from Turkey",
        "mis": "people think Castro was always an open communist. He explicitly denied it in 1959 and presented the revolution as nationalist and reformist, declaring its socialist character only in 1961 after relations with the US collapsed. Another myth is that the revolution was purely homegrown; Soviet aid was decisive in sustaining it after 1960, and Cuba's economy contracted sharply when that aid ended in 1991",
    }

    T["the partition of India"] = {
        "_cat": "history",
        "what": "the August 1947 division of British India into two independent states, India and Pakistan (with East and West wings), accompanied by the largest mass migration in modern history (10 to 18 million people) and communal violence that killed hundreds of thousands to over a million",
        "how": "after WWII, Britain announced rapid withdrawal. The Muslim League under Jinnah demanded a separate state; the Congress under Nehru and Gandhi sought united India. The Mountbatten Plan partitioned the Punjab and Bengal provinces along religious lines, with the Radcliffe Line drawn in five weeks by a barrister who had never visited South Asia. Independence on August 14-15, 1947, triggered cross-border flight as Hindus and Sikhs moved east into India and Muslims moved west into Pakistan. Princely states acceded under pressure; Kashmir's contested accession launched the first Indo-Pakistani war",
        "why": "partition created two nuclear-armed rivals whose enmity has shaped South Asian and global politics, displaced people on a scale unseen since WWII, generated unresolved disputes (Kashmir, Indus waters, refugee compensation), and inscribed religious nationalism into both states' founding identities. Bangladesh's 1971 independence from Pakistan was a delayed consequence of the original two-wing arrangement",
        "vs": "the Indian partition differs from many later national divisions (Korea, Germany, Cyprus) in being defined by religion rather than ideology or ethnicity, in scale of displacement, and in the speed of the process. It differs from Israel-Palestine partition in occurring under outgoing rather than incoming sovereign authority and in producing two recognized successor states immediately",
        "ex": "the Punjab partition between West Punjab (Pakistan) and East Punjab (India) saw perhaps 11 million people cross the new border within months. Sikh, Hindu, and Muslim communities that had lived together for centuries fought brutal massacres along the migration routes; cities like Lahore lost most of their Hindu and Sikh population while Amritsar lost most of its Muslims",
        "mis": "people think partition was the inevitable result of Hindu-Muslim hostility. Many Indian Muslims (and most subcontinental scholars then) opposed it; the demand emerged from elite political bargaining over post-independence representation. Another myth is that violence was random; recent research shows it followed patterns of organized militias, refugee flows, and contested local politics rather than spontaneous communal frenzy",
    }

    T["the rise and fall of the Ottoman Empire"] = {
        "_cat": "history",
        "what": "the Turkish-led empire that began as a small principality in northwest Anatolia around 1299, expanded to dominate the Balkans, Middle East, and North Africa, peaked under Suleiman the Magnificent in the sixteenth century, and was dismantled after WWI in 1922",
        "how": "early Ottomans expanded against weakened Byzantine and Anatolian Beylik neighbors using disciplined cavalry and devshirme-recruited Janissary infantry. The 1453 conquest of Constantinople under Mehmed II symbolically ended the Eastern Roman Empire. Selim I's conquest of Mamluk Egypt in 1517 added the Islamic holy cities and the caliphate. Suleiman's reign extended power into Hungary, the Mediterranean, and North Africa. From the late seventeenth century, defeats by the Habsburgs and Russians, Janissary corruption, fiscal strain, and inability to keep pace with European industrial and military change drove a long decline. WWI defeat and Mustafa Kemal's nationalist revolution ended the empire and replaced it with the Republic of Turkey in 1923",
        "why": "the Ottomans ruled the eastern Mediterranean and much of southeastern Europe for six centuries, shaping the religious, legal, and demographic landscape from the Balkans to Iraq. Their policies (millet system for religious minorities, vakif foundations, devshirme) influenced subsequent state formations. Their dissolution after WWI created the modern Middle East's borders, including unresolved problems (the Kurdish question, the Israeli-Palestinian conflict, Iraqi and Syrian state-building) still active today",
        "vs": "the Ottoman Empire differs from earlier Islamic empires (Umayyad, Abbasid) in being Turkish-led and lasting far longer in its later territories, and in incorporating European Christian populations more deeply. It differs from contemporary European empires in retaining Islamic juristic traditions while adopting bureaucratic structures resembling modern absolutism, and in eventually being a target rather than a beneficiary of nineteenth-century industrialization",
        "ex": "the 1683 Siege of Vienna marked the high-water mark of Ottoman expansion. After the failed siege, the Holy League rolled back Ottoman power in Hungary; the 1699 Treaty of Karlowitz was the first major territorial loss and the symbolic beginning of the long decline that European chancelleries called 'the Eastern Question'",
        "mis": "people think the Ottoman Empire was static and stagnant for centuries. It went through repeated reforms (Tanzimat, 1839-1876; the Young Turk constitutional revolution, 1908) and innovated continuously even as it fell behind European competitors. Another myth is that it suppressed all minorities; Christians and Jews enjoyed legal status under the millet system that European Jewish communities often envied",
    }

    T["the Age of Exploration's consequences"] = {
        "_cat": "history",
        "what": "the period from roughly 1418 (Portuguese voyages along Africa) through the late seventeenth century during which European powers (Portugal, Spain, England, France, Netherlands) explored, charted, and incorporated previously unknown-to-them coasts and continents into European-centered trade networks",
        "how": "Portuguese caravels reached the African coast and India (Vasco da Gama, 1498). Spanish-funded voyages (Columbus, Magellan-Elcano) crossed the Atlantic and circumnavigated the globe. Long-range navigation depended on improved ships, magnetic compasses, lateen sails, astrolabes, the marine chronometer (much later), and accumulated cartographic knowledge. State sponsorship combined with private capital (Casa de Contratacion, Dutch East India Company); religious conversion and commercial extraction were intertwined motives. Asian trade was integrated rather than conquered; American territories were colonized",
        "why": "the Age of Exploration created the first genuinely global trading system, transferred New World silver and crops to the Old World, displaced indigenous American populations through disease and conquest, established the Atlantic slave trade, and shifted Europe's economic center from the Mediterranean to the Atlantic, with consequences that defined the modern world's economic and political map",
        "vs": "European exploration differs from earlier long-distance contacts (Vikings to Vinland, Polynesian Pacific settlement, Zheng He's Ming voyages) in being sustained, capital-backed, and integrated with imperial expansion. Zheng He's expeditions in particular show that technological capacity for distant voyages was not unique to Europe; political will and economic incentive structures were what differed",
        "ex": "the Manila Galleon trade (1565-1815) connected Acapulco to Manila annually, exchanging American silver from Potosi for Chinese silks, porcelain, and spices. The trade tied four continents into a single circuit and made silver the world's first global money for nearly three centuries, illustrating how exploration produced sustained trading institutions, not just discovery",
        "mis": "people think Europeans 'discovered' the Americas. Indigenous peoples had inhabited and developed the continents for over 15000 years; what was new was contact between previously isolated Eurasian and American populations. Another myth is that exploration was driven primarily by curiosity; commercial profit (especially the Asian spice trade) and religious conversion were the dominant motives, with curiosity a distant third",
    }

    T["the Silk Road and pre-modern trade networks"] = {
        "_cat": "history",
        "what": "the network of overland and maritime trade routes that connected China, Central Asia, India, the Middle East, and the Mediterranean from roughly 130 BCE through the fifteenth century, carrying silk, spices, precious metals, and crucially also ideas, religions, and pathogens",
        "how": "the route was rarely a single road; merchants moved goods stepwise through caravan cities (Samarkand, Bukhara, Kashgar, Dunhuang) where different traders handled different legs. Maritime sister routes connected the Indian Ocean rim from the Red Sea to the South China Sea via Indian and later Arab and Chinese vessels. Caravanserais provided shelter and storage. Silver and gold flowed mostly eastward; silk, porcelain, and spices westward. The Pax Mongolica from roughly 1250 to 1350 lowered transit costs and increased volume substantially",
        "why": "the Silk Road carried Buddhism into China, papermaking and gunpowder westward, Islam across Central Asia, and the Black Death westward in the fourteenth century. It supported large urban civilizations far from coasts, transferred crops (cotton, sugar, citrus) across continents, and laid the foundations for Eurasian economic integration that the early modern period accelerated",
        "vs": "the Silk Road differs from later Atlantic trade systems in being polycentric and stage-relayed rather than dominated by a few hub ports, and in being primarily land-based for centuries before maritime alternatives prevailed. It differs from purely regional networks in linking civilizations that rarely had direct contact, mediated by intermediary populations who often grew wealthy on the trade",
        "ex": "the Tang capital Chang'an (modern Xi'an) at its eighth-century peak housed a million people and a substantial foreign merchant community: Sogdians, Persians, Turks, Indians, and Koreans. Buddhist monasteries in the western city accepted donations from caravan operators, and translated Sanskrit texts; this single city captures how the route mixed economies and cultures",
        "mis": "people think Marco Polo invented or opened the Silk Road. It had been operating for over a millennium when he traveled it; his account was popular partly because it described a route that was already legendary. Another myth is that silk was the main trade good; silk was iconic but spices, horses, ceramics, slaves, and bullion all moved in larger volumes at various periods",
    }

    T["the Arab Spring of 2010-2012"] = {
        "_cat": "history",
        "what": "the wave of pro-democracy uprisings, protests, and civil wars that swept the Arab world starting with Tunisia in December 2010, toppling regimes in Tunisia, Egypt, Libya, and Yemen, and triggering long civil wars in Syria and Yemen, with mixed and largely disappointing outcomes",
        "how": "Mohamed Bouazizi's December 2010 self-immolation in Tunisia sparked protests that forced President Ben Ali out within weeks. Tactics spread via satellite TV (Al Jazeera) and social media. Mass demonstrations in Cairo's Tahrir Square forced Mubarak to resign in February 2011. Libyan rebels, backed by NATO airstrikes, killed Gaddafi in October 2011. Yemen's Saleh stepped down in 2012. Syria's Assad responded with violent crackdowns that turned protests into a civil war drawing in Russia, Iran, Turkey, the US, and various jihadist groups, with over 500,000 dead",
        "why": "the Arab Spring briefly raised hopes for democratization across the Middle East but produced only Tunisia as a partial democratic success (and even that backslid by 2021). It accelerated the Syrian and Yemeni humanitarian disasters, expanded ISIS's window for territorial conquest in 2014, drove the largest refugee flows since WWII, and reshaped European politics around migration. It also cooled subsequent protest movements as authoritarian regimes learned defensive tactics",
        "vs": "the Arab Spring differs from the 1989 East European revolutions in lacking a unifying alternative ideology and an external sponsor power that backed transitions; from earlier Arab nationalist movements in originating from below rather than from coup-prone officer corps; and from later movements in Hong Kong and Belarus in actually toppling regimes, even where the aftermath disappointed",
        "ex": "Tahrir Square in February 2011 became the global symbol of the moment: hundreds of thousands of protesters, multi-day occupation, and a televised resignation announcement from Vice President Suleiman ending Mubarak's 30-year rule. The subsequent transition through SCAF, the Muslim Brotherhood's Morsi government, and the 2013 military coup under Sisi shows how fragile the initial gains turned out to be",
        "mis": "people think social media caused the Arab Spring. Long-running grievances over corruption, unemployment, and dignity drove the uprisings; social media accelerated coordination and broadcast events but was not the cause. Another myth is that the protests universally failed; Tunisia's transition produced a sustained democratic period, and ongoing Arab politics still reflects expectations the protests reset",
    }

    T["the Spanish Civil War"] = {
        "_cat": "history",
        "what": "the 1936-1939 conflict between the elected Republican government and Nationalist forces led by Francisco Franco, which ended in Nationalist victory and a 36-year dictatorship, and which served as a proving ground for fascist and democratic powers on the eve of WWII",
        "how": "a partial military coup in July 1936 split Spain's territory and army. The Republic, supported by communists, socialists, anarchists, and Basque and Catalan autonomists, faced Nationalist forces backed by Italian and German troops and aircraft. Republican aid came from the Soviet Union and the International Brigades of foreign volunteers. Battles at Madrid, Jarama, Guadalajara, the Ebro, and the bombing of Guernica defined the war. By 1939, the Republic collapsed under military pressure, internal political fractures, and an Anglo-French non-intervention policy that effectively favored the Nationalists",
        "why": "the war killed roughly 500,000 Spaniards, exiled hundreds of thousands more, and installed a dictatorship that lasted until 1975. It demonstrated to the European democracies the methods (aerial bombing, blitzkrieg-style maneuver, fascist alignment) that would define WWII, and to the Soviet Union the limits of popular-front strategies. Spanish memory of the war and its repression continues to shape contemporary politics, including the 2007 Historical Memory Law",
        "vs": "the Spanish Civil War differs from interwar conflicts in Italy and Germany in having been a sustained military struggle rather than a coup d'etat, and in attracting international participation that prefigured WWII alignments. It differs from later Cold War proxy wars in being defined by domestic ideological splits as much as superpower contest",
        "ex": "the April 1937 bombing of Guernica by German Condor Legion and Italian Aviazione Legionaria aircraft destroyed the Basque town in support of Nationalist ground operations. Picasso's mural, painted for the 1937 Paris International Exposition, made the bombing a global symbol of fascist aggression and a turning point in twentieth-century war imagery",
        "mis": "people think the Republic was a coherent leftist government. It was a fractious coalition where Stalinist communists, anarchists, social democrats, and regional autonomists clashed violently, including the 1937 Barcelona May Days where communists suppressed anarchists and the POUM. Another myth is that the International Brigades were decisive; they were militarily limited and politically divisive, but symbolically powerful in shaping the global memory of the war",
    }
