#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank part 2 of 3: history, arts, literature, philosophy (fresh for batch E)."""


def register(T):
    # ===== HISTORY =====

    T["the Industrial Revolution"] = {
        "_cat": "history",
        "what": "the transformation of agricultural and craft economies into industrial manufacturing economies that began in Britain in the late 18th century, characterized by mechanized factories, steam power, the railway system, urbanization, and unprecedented productivity growth",
        "how": "abundant coal, accessible iron, navigable rivers, secure property rights, and a skilled artisan base let British inventors mechanize textiles (the spinning jenny, the water frame, the power loom), then steam engines (Watt's improvements over Newcomen's), then railways (Stephenson's Rocket, 1829). Investments compounded as factories produced cheaper goods, freeing capital for further mechanization",
        "why": "the Industrial Revolution broke the Malthusian trap, multiplied per-capita output, and reshaped global power. Britain's lead translated into empire and political dominance for a century. The revolution also drove urbanization, public health crises, child labor, and labor movements that produced modern political institutions",
        "vs": "the First Industrial Revolution (steam, textiles, iron, c. 1760-1840) differs from the Second (steel, electricity, chemicals, mass production, c. 1870-1914), the Third (computers, automation, c. 1960-2000), and the Fourth (AI, robotics, biotech, ongoing). Each built on the prior with new general-purpose technologies",
        "ex": "between 1750 and 1850 British cotton output rose more than fiftyfold while the population merely doubled. Manchester grew from 17,000 to 300,000 inhabitants, and the country shifted from over half its population on farms to under a quarter. By 1851 Britain produced about half the world's iron and coal",
        "mis": "people think the Industrial Revolution improved living standards immediately. Real wages stagnated for decades during the early phase; sustained gains for ordinary workers came mostly after 1850. Another myth is that it was uniquely British; the underlying trends spread to Belgium, France, Germany, the United States, and Japan within a few generations",
    }

    T["the Cold War"] = {
        "_cat": "history",
        "what": "the prolonged geopolitical, ideological, and military rivalry between the United States and the Soviet Union (and their respective blocs) from roughly 1947 to 1991, fought through proxy wars, espionage, arms races, and economic and cultural competition rather than direct combat between the principals",
        "how": "the Cold War operated through containment doctrine, NATO and the Warsaw Pact, nuclear deterrence (mutual assured destruction), proxy conflicts in Korea, Vietnam, Afghanistan, and across Africa and Latin America, intelligence agencies (CIA, KGB), economic blocs (Marshall Plan, Comecon), and cultural fronts (Voice of America, Radio Free Europe). Crises like Berlin, Cuba, and Yom Kippur risked direct confrontation",
        "why": "the Cold War shaped the second half of the 20th century: the United Nations, the European Union, decolonization patterns, the space race, the internet (DARPA), and the nuclear order. Its end in 1989-1991 triggered a wave of democratization, market reform, and globalization whose ripples define current politics",
        "vs": "the Cold War differs from hot wars in lacking direct combat between the principals, and from earlier great-power rivalries (Britain-Germany, France-Germany) by being globalized and ideological. It differs from current US-China competition by being more bipolar and more militarized at the strategic-nuclear level",
        "ex": "the Cuban Missile Crisis of October 1962 saw US reconnaissance discover Soviet medium-range missiles in Cuba. Thirteen days of brinkmanship, including a US naval quarantine, ended when Khrushchev agreed to withdraw the missiles in exchange for a US pledge not to invade Cuba and a quiet removal of US Jupiter missiles from Turkey",
        "mis": "people think the Cold War ended cleanly with a Western victory. Many of its conflicts (Korea, Cyprus, Afghanistan, the Israeli-Palestinian dispute) remained unresolved. Another myth is that the United States and the Soviet Union maintained tight control of their blocs; both struggled with allies who pursued independent goals",
    }

    T["the French Revolution"] = {
        "_cat": "history",
        "what": "the political and social upheaval in France from 1789 to 1799 that overthrew the Bourbon monarchy, abolished feudal privilege, declared the rights of man and citizen, executed King Louis XVI, and reshaped European politics, eventually giving rise to Napoleon's empire",
        "how": "fiscal crisis after costly wars and lavish royal spending forced Louis XVI to convene the Estates-General in 1789. The Third Estate broke off as the National Assembly. Storming of the Bastille in July, abolition of feudalism in August, and the Declaration of the Rights of Man and of the Citizen launched the revolution. Successive phases produced a constitutional monarchy, a republic, the Reign of Terror under Robespierre, and finally Napoleon's coup in 1799",
        "why": "the revolution introduced enduring concepts of citizenship, popular sovereignty, secular law, equality before the law, and nationalism. Its codes (the Napoleonic Code) shape civil law systems worldwide. It also inspired and frightened observers across Europe and the Americas, fueling waves of reform and reaction for the next century",
        "vs": "the French Revolution differs from the American Revolution by being a domestic social revolution rather than a colonial independence war, and from the English Civil War by its broader popular base and explicit ideological framework. It differs from the 1848 revolutions in achieving permanent constitutional changes",
        "ex": "the abolition of feudal privileges on the night of August 4, 1789, dismantled centuries-old seigneurial dues, ecclesiastical tithes, and noble exemptions in a single legislative session. By morning, the legal foundation of the old regime had effectively collapsed",
        "mis": "people think the revolution moved smoothly from monarchy to republic. It was chaotic, violent, and reversed multiple times; most of its leaders were executed or exiled by their successors. Another myth is that the revolution was driven by the urban poor; key drivers included middle-class lawyers, provincial elites, and disaffected nobles",
    }

    T["the Meiji Restoration"] = {
        "_cat": "history",
        "what": "the political revolution in Japan in 1868 that ended the Tokugawa shogunate, restored imperial authority under Emperor Meiji, and launched a comprehensive program of modernization, industrialization, and military reform that transformed Japan from a feudal society into a great power within decades",
        "how": "the arrival of Commodore Perry's fleet in 1853 forced Japan open to foreign trade on unequal terms. Lower-ranking samurai from outer domains (Satsuma, Choshu) overthrew the shogunate by 1868 in the emperor's name. The new government abolished the samurai class, established prefectures, built railways, sent missions abroad to study Western institutions, adopted a constitution in 1889, and built a conscript military and modern industries",
        "why": "the Meiji Restoration is the model case of rapid non-Western modernization. Within 40 years Japan defeated China and Russia in major wars and joined the great powers. It demonstrated that industrial development was not culturally Western and inspired modernizers worldwide. It also planted the seeds of Japanese militarism that culminated in World War II",
        "vs": "the Meiji Restoration differs from the Chinese Self-Strengthening Movement (which failed to dismantle the imperial structure) and from the Ottoman Tanzimat (which liberalized but lost ground militarily) by combining institutional revolution with selective Western adoption. It differs from European industrialization by being state-led and explicitly imitative",
        "ex": "the Iwakura Mission (1871-1873) sent over 100 Japanese officials and students on a 22-month tour of the United States and Europe to study constitutions, industries, schools, and militaries. Their detailed reports directly shaped subsequent Japanese reforms in education, banking, postal service, and law",
        "mis": "people think the restoration was a popular movement. It was an elite-led coup using imperial legitimacy. Another myth is that Japan simply copied the West; reformers selected and adapted institutions deliberately, blending them with existing structures (the genro council, traditional emperor worship, kokutai ideology)",
    }

    T["the Treaty of Westphalia"] = {
        "_cat": "history",
        "what": "the pair of peace treaties signed in 1648 in the Westphalian cities of Munster and Osnabruck that ended the Thirty Years' War in the Holy Roman Empire and the Eighty Years' War between Spain and the Dutch Republic, often credited with founding the modern state-based international system",
        "how": "exhausted by three decades of devastating religious-political warfare, European powers negotiated for years until reaching settlements that recognized state sovereignty within fixed borders, allowed each ruler to determine the religion of their territory (cuius regio, eius religio extended), formalized Dutch and Swiss independence, and weakened the Holy Roman Empire in favor of its constituent princes",
        "why": "Westphalia is conventionally treated as the origin of the sovereign state system: territorially bounded states with non-interference in internal affairs as the organizing principle of international order. It marked the end of the era of universalist Catholic-imperial politics and the start of secular diplomacy among formally equal states",
        "vs": "Westphalia differs from later peace settlements (Vienna 1815, Versailles 1919) by codifying sovereignty rather than dynastic legitimacy or collective security. It differs from medieval treaties by treating states as the primary actors rather than monarchs personally. The Westphalian model has been challenged by humanitarian intervention and supranational bodies",
        "ex": "the Dutch Republic gained formal recognition as an independent state from Spain after 80 years of war. Switzerland gained formal independence from the Holy Roman Empire. The Holy Roman Empire's roughly 300 component states each gained the right to conduct independent foreign policy",
        "mis": "people think Westphalia immediately created the modern state system. The transition was gradual; many features (clear borders, professional bureaucracies, mass nationalism) emerged only over the next two centuries. Another myth is that non-interference was strictly observed; great powers continued intervening in weaker states constantly",
    }

    T["the Cultural Revolution"] = {
        "_cat": "history",
        "what": "the sociopolitical movement launched by Mao Zedong in 1966 in China to reassert his authority, purge perceived bourgeois and revisionist elements from the Communist Party, and remold society through mass mobilization of youth (Red Guards) until winding down with Mao's death in 1976",
        "how": "Mao called on students to attack the Four Olds (old customs, culture, habits, ideas), denounce teachers, officials, and intellectuals, and rebel against authority. Red Guard factions formed, then fought one another. The army intervened to restore order from 1968. Tens of millions of urban youth were sent to the countryside; intellectuals were purged or worked to death; the economy and education sustained massive damage",
        "why": "the Cultural Revolution killed hundreds of thousands directly, ruined the lives of tens of millions more, destroyed cultural artifacts, halted higher education for years, and discredited Maoist mass mobilization. It set the stage for Deng Xiaoping's reform-and-opening era from 1978 by making clear the catastrophic costs of ideological politics",
        "vs": "the Cultural Revolution differs from the Great Leap Forward (1958-1962), which was an economic disaster of forced collectivization, in being primarily political and cultural. It differs from Stalin's Great Purge by being mobilizational from below rather than secret-police-driven from above, and far more destructive of cultural patrimony",
        "ex": "the Red Guards' attack on the home of Lao She, one of China's most celebrated 20th-century novelists, in 1966 led to his suicide the next day. Across the country, libraries, temples, and museums were ransacked; about 4,900 of Beijing's 6,843 designated historical sites were damaged or destroyed",
        "mis": "people in the West sometimes romanticized the Cultural Revolution as authentic mass democracy. Inside China, it is officially classified as catastrophic. Another myth is that it was a top-down purge like Stalin's; much of the violence was driven by Red Guards exploiting Mao's authorization to settle local scores",
    }

    T["the partition of India"] = {
        "_cat": "history",
        "what": "the division of British India in 1947 into two independent dominions, India and Pakistan (with East and West wings, the East later becoming Bangladesh in 1971), accompanied by mass violence and one of the largest population displacements in history",
        "how": "facing exhaustion after WWII and unable to reconcile the Indian National Congress and the Muslim League, Britain accelerated its withdrawal. Lord Mountbatten's plan accepted partition along religious-majority lines. The Radcliffe Line was drawn in weeks by a London barrister with no India experience. Independence on August 14-15, 1947 triggered communal violence as Hindus and Sikhs fled westward and Muslims eastward",
        "why": "partition created two states still locked in conflict over Kashmir, four wars between them, and lingering nuclear tension. It killed an estimated one to two million people and displaced about 14 million in months. It also shaped the subcontinent's politics, demographics, and economic trajectories for the rest of the 20th century and beyond",
        "vs": "partition differs from other decolonizations like Indonesia or Malaya by being communal-religious in basis and accompanied by violence on a continental scale. It differs from later separations like Czechoslovakia (1993) by being neither peaceful nor consensual",
        "ex": "the Punjab was split, with Lahore going to Pakistan and Amritsar to India, despite both having sizable minority populations. Trains arriving in either country carried massacre victims. The Sikh community, concentrated in Punjab, suffered particularly devastating displacement and violence",
        "mis": "people think partition was inevitable given Hindu-Muslim differences. Many historians argue specific political failures, including British divide-and-rule policies and the Congress-League negotiation breakdown, made partition contingent rather than necessary. Another myth is that violence was spontaneous; much was organized by paramilitary groups with state and police complicity",
    }

    T["the abolition of the Atlantic slave trade"] = {
        "_cat": "history",
        "what": "the gradual legal and political dismantling of the transatlantic slave trade and slavery itself between the late 18th and late 19th centuries, beginning with British abolition of the trade in 1807 and culminating in emancipation across the Americas, with Brazil ending slavery last in 1888",
        "how": "British evangelicals, freed slaves, and parliamentary reformers (William Wilberforce, Granville Sharp, Thomas Clarkson, Olaudah Equiano) organized petitions, boycotts, and parliamentary campaigns. Britain banned the trade in 1807 and used the Royal Navy's West Africa Squadron to intercept slave ships. Slavery itself was abolished in the British Empire in 1833, France permanently in 1848, the US in 1865 after civil war, and Brazil in 1888",
        "why": "the abolition of the Atlantic slave trade ended a four-centuries-long forced migration of about 12 million Africans, transformed political economies of the Americas, set precedents for later human rights movements, and reshaped Atlantic geopolitics. It also left structural legacies of racism, plantation economies, and underdevelopment that persist",
        "vs": "abolition of the trade differs from abolition of slavery itself, which often lagged by decades. It differs from emancipation movements within other slave systems (Roman, medieval Mediterranean) by being globally coordinated and explicitly framed in universal human rights terms",
        "ex": "the British West Africa Squadron, formed in 1808, intercepted around 1,600 slave ships and freed about 150,000 Africans before the trade was effectively suppressed in the 1860s. Captured ships were tried in admiralty courts; many freed Africans were resettled in Sierra Leone",
        "mis": "people think Britain abolished slavery from purely moral motives. Economic factors (the rise of free-labor industrialism, sugar overproduction, slave revolts in Saint-Domingue) also weighed heavily. Another myth is that abolition ended slavery globally; slavery in various forms continued in parts of Africa and the Middle East until the 20th century",
    }

    T["the Silicon Valley origin"] = {
        "_cat": "history",
        "what": "the cluster of technology companies and research institutions in the southern San Francisco Bay Area whose origins lie in early 20th-century radio and electronics work and accelerated through Stanford University's industrial partnerships, defense funding, and the semiconductor industry founded around the transistor in the 1950s",
        "how": "Stanford engineering dean Frederick Terman encouraged faculty and graduates to start local companies (Hewlett-Packard in 1939) and created Stanford Industrial Park in 1951. William Shockley's 1956 move to Mountain View seeded Fairchild Semiconductor, whose alumni founded Intel, AMD, and dozens of other firms. Defense Department contracts and venture capital institutions matured alongside, with Sand Hill Road as the eventual VC hub",
        "why": "Silicon Valley became the world's dominant technology cluster, producing the integrated circuit, the personal computer, the internet's commercial layer, mobile platforms, and modern AI infrastructure. It set the global template for high-tech innovation clusters, university-industry partnerships, and venture financing",
        "vs": "Silicon Valley differs from earlier industrial clusters (Detroit autos, Pittsburgh steel) by its university anchor, focus on knowledge work, and labor mobility across firms. It differs from later imitators (Boston's Route 128, Shenzhen, Bangalore) by its specific combination of permissive employment law (no enforceable noncompetes), stock-option compensation, and risk-tolerant capital",
        "ex": "the eight engineers who left Shockley Semiconductor in 1957 to found Fairchild (the Traitorous Eight, including Robert Noyce and Gordon Moore) seeded a genealogy of companies later called the Fairchildren, including Intel (1968) and AMD (1969). Many Valley firms can trace their lineage to that founding event",
        "mis": "people think Silicon Valley was a free-market emergence. Decades of defense and federal research funding (DARPA, NASA, Stanford Research Institute) underwrote its early decades. Another myth is that the cluster is replicable purely through tax incentives; the dense knowledge spillovers and labor mobility are decades of accumulated culture",
    }

    T["the rise of Christianity in Rome"] = {
        "_cat": "history",
        "what": "the gradual spread of Christianity from a small Jewish sect in 1st-century Judea to the dominant religion of the Roman Empire by the 4th century, culminating in Constantine's conversion (312) and Theodosius's establishment of Nicene Christianity as the state religion (380)",
        "how": "Christianity spread along Roman trade routes through urban communities, attracting adherents with its social welfare networks, egalitarian rhetoric, charismatic figures (Paul of Tarsus), and afterlife promises. Periodic persecutions (under Nero, Decius, Diocletian) failed to suppress it. Constantine's Edict of Milan (313) ended persecution; Theodosius's later decrees outlawed pagan sacrifice and made Nicene Christianity the official faith",
        "why": "the rise of Christianity reshaped Roman law, art, philosophy, charity, and social structure. Surviving the empire's fall, the Church became the central institution of medieval Europe and indirectly defined Western civilization's intellectual and moral inheritance. Its rise also illustrates how minority religious movements can transform empires",
        "vs": "Christianity's spread differs from earlier mystery religions (Mithraism, the cult of Isis) by exclusive monotheism (no syncretism with other gods), organized leadership, and a written canon. It differs from contemporary Manichaeism by retaining and reinterpreting the Hebrew scriptures rather than rejecting matter as evil",
        "ex": "Pliny the Younger's letter to Trajan (around 112 CE) describes Christianity already spreading widely in Bithynia, with temples nearly empty and meat from sacrifices unsold. He sought guidance on how to handle accused Christians; Trajan replied that they should not be sought out but should be punished if they refused to recant",
        "mis": "people think Constantine's conversion made everyone Christian instantly. The empire remained majority pagan for decades. Another myth is that Christianity grew through martyrdom; while martyrs galvanized communities, sociologist Rodney Stark argues most growth came through ordinary social networks, women's higher conversion rates, and demographic factors",
    }

    T["the Manhattan Project"] = {
        "_cat": "history",
        "what": "the secret American-led research and engineering effort during World War II (1942-1946) that developed the first atomic weapons, employing about 130,000 people across multiple sites and culminating in the Trinity test (July 1945) and the bombings of Hiroshima and Nagasaki",
        "how": "after Einstein's letter warning Roosevelt of German atomic research, the Army Corps of Engineers under General Leslie Groves and physicist Robert Oppenheimer assembled enormous facilities at Oak Ridge (uranium enrichment), Hanford (plutonium production), and Los Alamos (weapon design). Three approaches were pursued in parallel: gaseous diffusion, electromagnetic separation, and reactor production. The implosion design for plutonium and the gun-type design for uranium were perfected by 1945",
        "why": "the Manhattan Project introduced nuclear weapons to the world, ended World War II faster than otherwise, launched the Cold War nuclear arms race, and demonstrated the wartime potential of large-scale state-coordinated science. It set precedents for big science, classified research, and the federal funding of academic physics that shape research to this day",
        "vs": "the Manhattan Project differs from earlier weapons development by its scale (about 0.4 percent of US wartime spending), its theoretical-physics foundation, and its compartmentalized secrecy. It differs from later projects (Apollo, ITER) by being aimed at producing a weapon under wartime urgency rather than peaceful exploration",
        "ex": "the Trinity test on July 16, 1945 in the New Mexico desert detonated a plutonium implosion device with about 21 kilotons of TNT-equivalent yield, vaporizing the steel test tower and producing temperatures hotter than the Sun's surface. Oppenheimer later quoted the Bhagavad Gita: 'Now I am become Death, the destroyer of worlds'",
        "mis": "people think the Manhattan Project was a small secret laboratory effort. It was an industrial undertaking on the scale of the prewar US auto industry. Another myth is that the bombs ended the war single-handedly; Soviet entry into the Pacific war on August 8, 1945 also weighed heavily in Japanese leadership's surrender decision",
    }

    # ===== ARTS / LITERATURE / PHILOSOPHY =====

    T["chiaroscuro in painting"] = {
        "_cat": "arts",
        "what": "the artistic technique of using strong contrasts between light and dark to model three-dimensional form, suggest depth, and create dramatic atmosphere, especially associated with Renaissance and Baroque painters like Leonardo, Caravaggio, and Rembrandt",
        "how": "the painter establishes a single dominant light source, often from outside the picture frame, and renders subjects as illuminated forms emerging from deep shadow. Subtle gradations of half-tone (sfumato in Leonardo's terms) shape volume; sharp transitions (tenebrism in Caravaggio's terms) heighten drama. Underpainting in dark tones (the imprimatura) supports the highlights",
        "why": "chiaroscuro made figures appear sculpturally solid on flat surfaces, gave painters control over psychological mood, and remains the dominant strategy for naturalistic figure painting. Its principles transferred to photography, film noir, and contemporary cinematography",
        "vs": "chiaroscuro differs from sfumato (Leonardo's smoky transitions without hard edges) and from tenebrism (Caravaggio's near-black backgrounds with high-key highlights). It differs from earlier flat-light medieval painting by treating light itself as a compositional element",
        "ex": "Caravaggio's 'The Calling of Saint Matthew' (around 1599) shows a shaft of light slicing across a dim Roman tavern, picking out the saint's astonished face while leaving the room's edges in deep shadow. The light functions both physically and theologically as Christ's calling beam",
        "mis": "people think chiaroscuro just means dark backgrounds. It is specifically about modeling form with light gradients, not about overall key. Another myth is that it was invented in the Baroque; Leonardo's late 15th-century work already explored the principles, with Caravaggio later pushing them to dramatic extremes",
    }

    T["the sonnet form"] = {
        "_cat": "arts",
        "what": "a 14-line lyric poem in iambic pentameter with a fixed rhyme scheme, originating in 13th-century Sicily, reaching artistic peak in Petrarch's Italian model and Shakespeare's English variant, and used for compressed, often argumentative meditations on love, time, and mortality",
        "how": "the Italian (Petrarchan) sonnet has an octave (ABBA ABBA) presenting a problem and a sestet (varying schemes like CDE CDE) responding to it, with a turn (volta) between them. The English (Shakespearean) sonnet uses three quatrains (ABAB CDCD EFEF) and a couplet (GG), often saving the turn for the final pair. The Spenserian variant interlinks rhymes (ABAB BCBC CDCD EE)",
        "why": "the sonnet's compression forces poets to argue, develop, and resolve in a precise structural shape, training generations of writers in concision and rhetorical structure. Its influence runs from Petrarch through Shakespeare, Milton, Wordsworth, and Hopkins to contemporary poets like Terrance Hayes and Don Paterson",
        "vs": "the sonnet differs from the longer Petrarchan canzone, the freer ode, and the haiku's syllabic compression. It differs from blank verse (unrhymed iambic pentameter, used in drama and longer poems) and from the villanelle (also fixed-form but using just two rhymes across 19 lines)",
        "ex": "Shakespeare's Sonnet 18 ('Shall I compare thee to a summer's day?') uses three quatrains to develop the comparison and the couplet ('So long as men can breathe or eyes can see, / So long lives this, and this gives life to thee') to close it. The structure mirrors a logical argument from premise to conclusion",
        "mis": "people think all sonnets are love poems. Sonnets address politics (Milton), religion (Donne, Hopkins), and almost any subject. Another myth is that the form is constraining; experienced poets find that the constraint generates the surprise of their best lines",
    }

    T["the unreliable narrator in fiction"] = {
        "_cat": "arts",
        "what": "a narrative technique in which the storyteller's account of events is, deliberately or unwittingly, untrustworthy, requiring readers to interpret the gaps between what the narrator says, what actually happened, and what the narrator's distortions reveal about character or theme",
        "how": "writers create unreliability through inconsistencies, biased framing, withheld information, mental instability, naive perspective, ulterior motive, or memory failure. Readers detect it through internal contradictions, other characters' reactions, narrator's stake in the outcome, or end-of-novel revelations that recast earlier passages",
        "why": "unreliable narration foregrounds interpretation, dramatizes how perspective shapes truth, and lets writers explore consciousness, deception, and self-deception with intimacy. It is foundational to modernist and postmodern fiction and a workhorse of mystery and psychological thriller",
        "vs": "unreliable narration differs from limited third-person narration, where the narrator's knowledge is bounded but truthful within those bounds. It differs from multiple narrators (Rashomon-style), where readers compare partial accounts. It also differs from outright deceit by the author; the unreliability is structurally legible",
        "ex": "Kazuo Ishiguro's 'The Remains of the Day' (1989) gives us Stevens, an English butler whose narration consistently downplays his emotional life, his political naivete, and his missed romantic chances with the housekeeper. Readers gradually see what Stevens cannot bring himself to say outright",
        "mis": "people think an unreliable narrator must be lying or insane. Naive children, biased adults, and traumatized memoirists are all unreliable in different ways. Another myth is that unreliability undermines meaning; well-handled, it creates richer meaning by inviting interpretation",
    }

    T["postmodernism"] = {
        "_cat": "arts",
        "what": "a broad cultural and intellectual movement of the late 20th century characterized by skepticism toward grand narratives, attention to language and power, mixing of high and low culture, formal experimentation, and ironic self-awareness, prominent in philosophy, literature, architecture, and the arts",
        "how": "postmodern thinkers (Lyotard, Derrida, Foucault, Baudrillard) attacked the totalizing claims of Enlightenment reason, structuralism, and Marxism, emphasizing instead language games, deconstruction, discourse and power, and simulacra. Postmodern artists (Pynchon, Borges, Rauschenberg, Venturi) employed pastiche, intertextuality, fragmentation, and metafiction to undermine modernist autonomy and seriousness",
        "why": "postmodernism reshaped academic humanities, literary fiction, architecture, and design, and prepared the ground for cultural critique focused on identity, representation, and power. Its critiques of objectivity also informed contemporary debates about truth, media, and politics",
        "vs": "postmodernism differs from modernism by treating modernist seriousness with ironic distance and rejecting the modernist hope for a redemptive pure form. It differs from realism by foregrounding artifice. It differs from contemporary metamodernism, which oscillates between earnestness and irony rather than committing to either",
        "ex": "Jorge Luis Borges's story 'Pierre Menard, Author of the Quixote' (1939, prefiguring postmodernism) imagines a 20th-century writer who recreates Cervantes' novel word for word and is praised for his bold modern reinterpretation, satirizing the idea that a text's meaning is independent of its context",
        "mis": "people think postmodernism means anything goes or nothing is true. Most postmodern thinkers argued for situated, perspectival truth, not nihilism. Another myth is that postmodernism is a single coherent doctrine; it spans incompatible thinkers united more by shared targets (Enlightenment universalism) than by shared positive program",
    }

    T["utilitarianism"] = {
        "_cat": "philosophy",
        "what": "an ethical theory holding that the right action is the one that maximizes overall well-being or utility, summing happiness and suffering across all affected sentient beings, with classical formulations by Jeremy Bentham (1789) and John Stuart Mill (1861)",
        "how": "an act-utilitarian evaluates each action by predicting its consequences and choosing the one with the greatest net utility. A rule-utilitarian asks which moral rules, if generally followed, would maximize utility. Hedonistic utilitarians count pleasure and pain; preference utilitarians count satisfied preferences; modern variants use well-being more broadly",
        "why": "utilitarianism remains the dominant framework in cost-benefit analysis, public health prioritization, animal welfare ethics, effective altruism, and policy reasoning more generally. Its insistence on counting everyone's interests equally is also a powerful argument against parochialism",
        "vs": "utilitarianism differs from deontology (which focuses on duties and rules regardless of consequences) and virtue ethics (which focuses on character traits). Within utilitarianism, act vs rule, total vs average, hedonistic vs preference-based, and human-only vs sentience-based variants generate distinct prescriptions",
        "ex": "the trolley problem's standard utilitarian answer is to divert the trolley to kill one person rather than five, since five lives saved outweigh one lost. In policy, utilitarian reasoning supports vaccine campaigns that produce huge aggregate benefits even at the cost of rare individual adverse events",
        "mis": "people think utilitarianism justifies any horror that produces aggregate good. Most utilitarians reject such cases, either by appealing to rule-utilitarian reasoning or by noting that real-world consequences of brutal acts (precedent, fear, abuse of power) almost always make them net negative. Another myth is that it ignores rights; many utilitarians argue rights are themselves utility-maximizing rules",
    }

    T["the categorical imperative"] = {
        "_cat": "philosophy",
        "what": "Immanuel Kant's central moral principle, formulated in the Groundwork of the Metaphysics of Morals (1785), commanding rational agents to act only on maxims they could will to become universal laws, with companion formulations focusing on humanity as an end and on a kingdom of ends",
        "how": "Kant's first formulation (universal law) tests a proposed maxim by asking whether you could rationally will that everyone always act on it. The second formulation (humanity as end) prohibits using rational beings merely as means. The third formulation (kingdom of ends) imagines a community of rational beings legislating laws together. The three formulations are meant to converge on the same set of duties",
        "why": "the categorical imperative grounds modern rights-based and dignity-based ethics, underlies key features of liberal political theory, and remains the major rival to utilitarianism in normative philosophy. Its emphasis on respecting persons as ends underlies modern medical ethics, human-rights law, and Kantian theories of justice",
        "vs": "the categorical imperative differs from hypothetical imperatives, which prescribe means to ends you happen to have. It differs from utilitarianism by ignoring consequences in determining moral worth, and from virtue ethics by focusing on the rationality of action rather than character traits",
        "ex": "Kant's example of lying to a borrower about ability to repay fails the universal law test: if everyone lied about repayment, lending would collapse and the maxim would be self-defeating. The same maxim also violates humanity as end by treating the lender as a mere instrument",
        "mis": "people think the categorical imperative just means 'do unto others as you would have them do unto you'. Kant's formulation is more demanding: it asks about logical universalizability, not personal preferences. Another myth is that Kantian ethics is inflexible; later Kantians have developed sophisticated treatments of conflicting duties",
    }

    T["the philosophy of mind"] = {
        "_cat": "philosophy",
        "what": "the branch of philosophy concerned with the nature of mental phenomena, their relationship to physical phenomena, and the structure of consciousness, intentionality, perception, and personal identity",
        "how": "philosophers of mind develop and test theories: dualism (Descartes), behaviorism (Ryle), identity theory (Place, Smart), functionalism (Putnam, Fodor), eliminative materialism (P. M. Churchland), property dualism (Chalmers), enactivism, and predictive processing accounts. They draw on neuroscience, cognitive science, AI, and linguistics, while subjecting these empirical findings to conceptual analysis",
        "why": "the philosophy of mind shapes how we understand consciousness, free will, mental causation, AI, and the moral status of animals and machines. It influences cognitive science research programs, AI alignment debates, and clinical reasoning about disorders of consciousness",
        "vs": "philosophy of mind differs from cognitive psychology (which is empirical, modeling specific capacities) and from neuroscience (which describes neural mechanisms) by addressing conceptual questions: what makes a state mental, what is consciousness, can a thermostat have beliefs. It differs from philosophy of psychology by focusing on the metaphysics rather than the methodology",
        "ex": "Thomas Nagel's 1974 paper 'What Is It Like to Be a Bat?' argues that the subjective character of experience cannot be captured by any physical description, however complete. The argument frames the hard problem of consciousness and remains a touchstone for debates about whether physicalism can fully explain mind",
        "mis": "people think the philosophy of mind is just neuroscience by another name. Conceptual questions (what counts as a mental state, what consciousness is) are not settled by more brain data. Another myth is that the field is dominated by dualism; most contemporary philosophers of mind are physicalists of various stripes",
    }

    T["jazz harmony"] = {
        "_cat": "arts",
        "what": "the system of chord construction, voicing, and progression characteristic of jazz, featuring extended chords (sevenths, ninths, elevenths, thirteenths), altered tensions, modal interchange, tritone substitution, and ii-V-I progressions used as the harmonic skeleton of standards",
        "how": "jazz musicians extend triadic harmony with sevenths and upper extensions, adapt voicings to keep voice leading smooth, substitute chords sharing common tones (the tritone substitution swaps a dominant for a dominant a tritone away), reharmonize melodies with chromatic approach chords, and improvise lines that imply or alter the underlying harmony",
        "why": "jazz harmony defines the sound of 20th-century American popular music, influencing musical theater, film scoring, R&B, and contemporary songwriting. Mastery of ii-V-I voice leading and chord-scale theory is the core curriculum of jazz education and shapes how millions of musicians think about chords",
        "vs": "jazz harmony differs from classical functional harmony by its extended chords as default, frequent modal interchange, and improvised reharmonization. It differs from rock harmony's preference for simple triads and power chords, and from blues harmony's I-IV-V backbone (though jazz absorbs and elaborates the blues)",
        "ex": "the bridge of 'I Got Rhythm' uses a chain of dominant seventh chords moving by fourths (D7-G7-C7-F7), each prolonged and altered for melodic interest. Bebop reharmonizations of standards added passing ii chords, tritone substitutions, and chromatic approach chords on top of the original changes",
        "mis": "people think jazz chords are random or wildly atonal. Most jazz harmony is functional with extensions; even free-jazz players reference traditional progressions. Another myth is that you must memorize every voicing; experienced players think in terms of chord-scale relationships and voice leading, generating voicings on the fly",
    }

    T["existential nihilism"] = {
        "_cat": "philosophy",
        "what": "the philosophical view that life has no objective meaning, purpose, or intrinsic value, that no transcendent moral order exists, and that any sense of significance is constructed by individuals or cultures rather than discovered in the world",
        "how": "existential nihilism is typically argued from naturalism (the universe contains no purposes), the death of God (in Nietzsche's diagnosis, traditional religious metaphysics has lost its grip), and the apparent indifference of cosmic timescales to human concerns. It is then either embraced (radical nihilists), countered (existentialists who construct meaning anyway), or transcended (Nietzsche's amor fati and Ubermensch)",
        "why": "existential nihilism frames a major modern philosophical problem: if traditional sources of meaning collapse, what grounds remain for morality, motivation, and identity? Existentialism, absurdism, and various humanisms develop in response. The question recurs in psychology of meaning, religious life, and political ideology",
        "vs": "existential nihilism differs from moral nihilism (a narrower claim about values), from metaphysical nihilism (about whether anything exists), and from ethical relativism (which still grants culturally relative norms). It differs from absurdism, which accepts meaninglessness while affirming life nonetheless (Camus)",
        "ex": "Camus's 'The Myth of Sisyphus' (1942) opens by declaring suicide the only serious philosophical question and then argues that, recognizing life's meaninglessness, one should imagine Sisyphus happy as he rolls his boulder. The book exemplifies absurdism's refusal of nihilist despair without denying the nihilist diagnosis",
        "mis": "people think nihilism implies anything goes morally. Many nihilists endorse strong personal commitments to chosen values. Another myth is that nihilism is depressive; some thinkers find liberation in releasing illusory cosmic stakes. The intellectual question is independent of the psychological response",
    }

    T["minimalism in music"] = {
        "_cat": "arts",
        "what": "an American musical movement emerging in the 1960s, characterized by repetition, slow harmonic change, steady pulse, modal or tonal centers, and gradual transformation of small musical cells, with key figures Terry Riley, Steve Reich, Philip Glass, and La Monte Young",
        "how": "minimalist composers limit material to small motivic cells, repeat them with gradual phase shifts, additive lengthening, or process-based transformations, and let large-scale form emerge from these incremental changes. Steve Reich's tape pieces explored phase relationships; Philip Glass's operatic works built large structures from arpeggiated cycles; Terry Riley's 'In C' (1964) is a landmark of indeterminate cellular composition",
        "why": "minimalism reset compositional thinking against postwar serialism and aleatoric music, brought concert music into dialogue with rock, jazz, and non-Western traditions, and shaped subsequent film scoring (Glass), pop production, and ambient music. It remains an influential aesthetic in contemporary classical, electronic, and post-classical music",
        "vs": "minimalism differs from serialism by being tonal or modal and rhythmically pulsed rather than chromatic and rhythmically irregular. It differs from ambient music by its insistent pulse and structural processes, and from earlier repetition in folk or pop by its self-conscious interest in process and phase",
        "ex": "Steve Reich's 'Music for 18 Musicians' (1976) builds an hour-long piece from a cycle of eleven chords, each prolonged through pulsing piano and mallet figures with gradually shifting overtones, breath cycles, and instrumental textures. The structural process is audible to a listener tracking how each section emerges",
        "mis": "people think minimalism means simple or uneventful. The surface may be limited, but the structural processes are intricate, and skilled performance demands precision. Another myth is that minimalism is a single style; mature works of Reich, Glass, Riley, Adams, and Young differ greatly in texture and intent",
    }

    T["the absurd in Camus"] = {
        "_cat": "philosophy",
        "what": "the central concept in Albert Camus's philosophy, naming the confrontation between humans' demand for meaning and a universe that offers none. Camus calls this collision the absurd and treats it as the basic condition of modern thought",
        "how": "Camus argues in 'The Myth of Sisyphus' (1942) that we feel the absurd when our urge to find ultimate purpose meets the universe's silence. He rejects three responses: physical suicide (avoiding the problem), philosophical suicide (illegitimate leap to religion), and willful forgetting. He recommends lucid acceptance: continuing to live and choose values while clear-eyed about meaninglessness",
        "why": "Camus's absurd articulated a postwar mood of collapsed traditional meaning while resisting both nihilist despair and bad-faith leaps. It influenced existential and absurdist literature, modern theater (Beckett, Ionesco), and subsequent secular humanist thinking about meaning, suicide prevention, and ethics without metaphysics",
        "vs": "Camus's absurd differs from Sartre's existentialism by rejecting the program of constructing essence through choice (Camus calls this another flight from the absurd). It differs from religious existentialism (Kierkegaard's leap of faith) by refusing the leap, and from nihilism by demanding life-affirming engagement",
        "ex": "Camus's Sisyphus is condemned to push a boulder up a hill forever, watching it roll back each time. Camus reads the myth not as tragedy but as model: in the moment of returning to the boulder, conscious of his fate, Sisyphus is free, and 'one must imagine Sisyphus happy'",
        "mis": "people think the absurd means meaninglessness pure and simple. For Camus, it specifically names the relation between human demand and cosmic silence. Another myth is that Camus is a nihilist; he wrote 'The Rebel' precisely against nihilist excesses, defending limits and solidarity",
    }
