#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank part 5 of 5: additional fresh topics filling out the 510-seed
target across all 7 categories."""


def register(T):
    # ===== SCIENCE =====

    T["how vision works in the human eye"] = {
        "_cat": "science",
        "what": "the biological process by which the eye converts light into neural signals interpreted as images, involving the cornea, lens, retina, photoreceptors (rods and cones), and the optic nerve to the visual cortex",
        "how": "light enters the cornea (which does most of the focusing), passes through the pupil and adjustable lens, and lands on the retina. Photoreceptors transduce light into electrical signals: rods for low-light, cones for color and detail. Bipolar and ganglion cells process the signal locally; the optic nerve carries it to the lateral geniculate nucleus and then to the primary visual cortex, where edge, motion, and feature detectors construct perception",
        "why": "vision provides about 80 percent of human sensory information, and understanding it underlies treatment of cataracts, glaucoma, macular degeneration, and refractive errors. It also informs camera design, machine vision, and the study of how brains build representations from raw sensor data",
        "vs": "human vision differs from many animals: bees see ultraviolet, mantis shrimp distinguish 12 color channels, and predator birds resolve far finer detail. It differs from cameras in dynamic range (much wider than typical sensors) and in the active, predictive processing the brain layers on top of raw sensory input",
        "ex": "color blindness, affecting about 8 percent of men of European descent, results from missing or altered cone photopigment genes on the X chromosome. The most common form (deuteranomaly) shifts green-cone sensitivity, making certain reds and greens hard to distinguish but leaving overall vision functional",
        "mis": "people think the eye captures images like a camera. The retina samples a small high-resolution central region (fovea) and a much lower-resolution periphery; the brain stitches together a perceived stable scene through saccades and predictive processing. Another myth is that carrots dramatically improve vision; vitamin A is needed to make rhodopsin, but excess does not improve normal sight",
    }

    T["acid-base chemistry in everyday life"] = {
        "_cat": "science",
        "what": "the branch of chemistry concerning compounds that donate protons (acids) or accept them (bases), with pH measuring acidity on a 0-14 logarithmic scale where 7 is neutral, lower is acidic, and higher is basic (alkaline)",
        "how": "in water, acids increase H+ (or H3O+) concentration and bases increase OH- concentration. Strong acids (HCl) dissociate fully; weak acids (acetic acid) partially. Buffers, mixtures of weak acid and conjugate base, resist pH changes by absorbing added H+ or OH-. Reactions between acids and bases produce water and a salt, often releasing heat",
        "why": "acid-base chemistry governs digestion (stomach acid at pH 1-2), blood physiology (tightly buffered at pH 7.35-7.45), soaps and detergents, baking (leavening), water treatment, antacids, and ocean acidification (a major effect of rising CO2). Most household chemistry can be understood through pH",
        "vs": "Bronsted-Lowry acid-base definitions (proton transfer) differ from Lewis (electron-pair acceptor/donor, more general) and Arrhenius (older, water-only). Acidity differs from corrosivity (which depends on the specific anion and material) and from sourness (a related but distinct sensory perception)",
        "ex": "baking soda (sodium bicarbonate, a base) reacts with vinegar (acetic acid) to produce carbon dioxide bubbles, water, and sodium acetate. The same reaction happens at a controlled rate inside cake batter when buttermilk and baking soda combine, leavening the cake without yeast",
        "mis": "people think 'acid' means dangerous. Lemon juice is more acidic than coffee; both are safe to drink. Another myth is that alkaline water has health benefits; the stomach quickly equalizes pH, and there is little evidence of systemic benefit",
    }

    T["how vaccines induce long-lasting immunity"] = {
        "_cat": "science",
        "what": "the immunological process by which a vaccine, presenting weakened or fragmentary pathogen components, primes the adaptive immune system to remember and rapidly respond to future infection by the real pathogen",
        "how": "the vaccine antigens are taken up by dendritic cells, which mature and present them to naive T and B cells in lymph nodes. Activated B cells produce antibodies and differentiate into long-lived plasma and memory B cells. Memory T cells also form. On later infection, memory cells respond within hours to days rather than the weeks naive responses require, often clearing the pathogen before symptoms develop",
        "why": "vaccines are the most cost-effective public-health intervention in history, eradicating smallpox, nearly eradicating polio, and dramatically reducing measles, rubella, and many other diseases. They underlie herd immunity, which protects those who cannot be vaccinated due to age or immune compromise",
        "vs": "vaccine-induced immunity differs from natural-infection immunity (similar mechanism, but vaccines avoid disease risk and often produce more uniform protection) and from passive immunity (transferred antibodies, fast but short-lived). Among vaccine platforms, live-attenuated, inactivated, subunit, mRNA, and viral-vector each trigger different immune responses",
        "ex": "the measles vaccine produces protection lasting decades from a two-dose childhood schedule, with about 97 percent effectiveness. Outbreaks in regions with declining vaccination coverage (such as several US states in recent years) demonstrate both the vaccine's effectiveness and the speed at which measles returns when herd immunity drops below roughly 95 percent",
        "mis": "people think vaccine immunity wanes quickly. Some vaccines do require boosters (tetanus, COVID-19), but many produce decades-long protection. Another myth is that vaccines overload the immune system; even infants encounter thousands of antigens daily from food and environment, far more than any vaccine schedule",
    }

    # ===== MATH =====

    T["set theory basics"] = {
        "_cat": "math",
        "what": "the branch of mathematics dealing with collections of objects called sets, the relations and operations on them (union, intersection, complement, subset), and the logical foundations these provide for the rest of mathematics",
        "how": "sets are defined by their elements, with order and repetition irrelevant. Union and intersection combine sets; complement excludes elements; Cartesian products build pairs. Russell's paradox (the set of all sets that do not contain themselves) led to axiomatic set theory like ZFC (Zermelo-Fraenkel with Choice), which restricts set formation to avoid contradictions",
        "why": "set theory provides the foundational language for mathematics: functions, relations, ordered pairs, numbers, and algebraic structures are all defined in terms of sets in standard treatments. It underlies modern logic, computer science (databases, type theory), probability, and topology",
        "vs": "set theory differs from category theory (which abstracts the relations between mathematical structures rather than building them from elements), from type theory (which assigns objects to types rather than memberships), and from naive collections (which set theory rigorously formalizes to avoid paradox)",
        "ex": "the power set of {a, b} (all subsets) has four elements: {}, {a}, {b}, {a, b}. Cantor's theorem proves that the power set of any set is strictly larger than the set itself, leading to a hierarchy of infinities (aleph-null, aleph-one, ...)",
        "mis": "people think sets are just collections. The empty set is a set, repetition does not matter, and very different formal axioms (ZFC, NBG, Morse-Kelley) handle the same intuitive idea slightly differently. Another myth is that all infinities are equal; Cantor's diagonalization shows that the real numbers are uncountably more numerous than the integers",
    }

    T["the dot product and its uses"] = {
        "_cat": "math",
        "what": "an algebraic operation taking two equal-length vectors and returning a scalar equal to the sum of products of corresponding entries, equivalently the product of their magnitudes times the cosine of the angle between them",
        "how": "for vectors u = (u1, ..., un) and v = (v1, ..., vn), u dot v = u1 v1 + ... + un vn. Geometrically, it equals |u| |v| cos(theta). The dot product is positive when vectors point similarly, zero when perpendicular, negative when opposing. It is bilinear, symmetric, and positive-definite when restricted to v dot v",
        "why": "the dot product is the workhorse of vector geometry: projection (the projection of u onto v has length u dot v / |v|), angle measurement, orthogonality tests, and the squared-distance formula. It appears in physics (work equals force dot displacement), graphics (lighting via surface-normal dot light-direction), and machine learning (cosine similarity for embeddings)",
        "vs": "the dot product differs from the cross product (returns a vector perpendicular to two 3D inputs, used for area and torque), from the outer product (returns a matrix), and from element-wise (Hadamard) products (returns a vector). It generalizes to inner products on abstract vector spaces, including function spaces with integrals",
        "ex": "two text documents represented as bag-of-words vectors have a cosine similarity equal to their dot product divided by the product of their lengths. Search and recommendation systems compute billions of such dot products to retrieve similar items, often using GPU-friendly matrix multiplications",
        "mis": "people confuse the dot product with multiplication. It collapses two vectors to a single number; the result is a scalar, not a vector. Another myth is that the dot product only makes sense in three dimensions; it is defined for any number of dimensions, including the infinite-dimensional inner products of Hilbert spaces",
    }

    T["expected value in probability"] = {
        "_cat": "math",
        "what": "the long-run average outcome of a random variable, computed as the sum (or integral) of each possible value weighted by its probability, often denoted E(X) and central to probability and decision theory",
        "how": "for a discrete random variable X with values x_i and probabilities p_i, E(X) = sum of p_i times x_i. For continuous variables, replace the sum with an integral over the probability density. Expectation is linear: E(X + Y) = E(X) + E(Y) regardless of dependence. The law of large numbers says sample averages converge to the expected value as sample size grows",
        "why": "expected value sets fair prices for bets and insurance, drives optimal decisions under uncertainty, underlies regression (which fits the conditional expectation of Y given X), provides the mean parameter of distributions, and is the basis for risk calculations in finance",
        "vs": "expected value differs from the most likely outcome (the mode), the middle outcome (the median), and from variance (a measure of spread around the mean). It differs from utility, which weights outcomes by subjective preference rather than nominal value, an important distinction in economic decision-making",
        "ex": "in roulette, betting one dollar on a single number pays 35 to 1 if it hits. The probability of hitting is 1/38 (for double-zero American roulette). Expected value of the bet is (35 times 1/38) plus (-1 times 37/38), or about negative 5.3 cents per dollar wagered, the house edge",
        "mis": "people equate expected value with the typical experience. A lottery ticket with positive expected value due to a giant jackpot is still almost certainly a loss. Another myth is that expected value tells you whether to take a bet; for non-repeated bets with large stakes, risk aversion (favoring lower-variance outcomes) can rationally override expected-value maximization",
    }

    T["modular arithmetic and clock math"] = {
        "_cat": "math",
        "what": "arithmetic where numbers wrap around upon reaching a fixed modulus, formalized as integers considered equivalent if they differ by a multiple of the modulus, written a equiv b (mod n)",
        "how": "addition, subtraction, and multiplication work as usual but results are reduced modulo n. Division is replaced by multiplication by a modular inverse, which exists for a (mod n) iff gcd(a, n) equals 1. The set Z/nZ is a ring, and a field when n is prime, providing rich algebraic structure",
        "why": "modular arithmetic underlies cryptography (RSA, Diffie-Hellman, elliptic-curve schemes), error-detection codes (ISBN check digits, IBAN check digits), pseudorandom-number generators, hash functions, and competitive-programming techniques. It is fundamental to number theory and discrete mathematics",
        "vs": "modular arithmetic differs from ordinary integer arithmetic in finiteness and in the existence of multiplicative inverses for some elements. It differs from rational arithmetic, where every nonzero element has an inverse. Composite moduli give rings that are not fields, with zero divisors",
        "ex": "RSA encryption raises a message m to the public exponent e modulo n (the product of two large primes), producing the ciphertext. Decryption raises the ciphertext to the private exponent d modulo n, recovering m. The security relies on factoring being hard while exponentiation modulo n is fast",
        "mis": "people think modular arithmetic is only for clocks. While 12-hour and 24-hour clocks use mod 12 and mod 24, the broader mathematical framework powers most modern cryptography. Another myth is that the modular inverse is the same as 1/a; for instance, 3 inverse mod 7 is 5 because 3 times 5 equals 15 equiv 1 (mod 7)",
    }

    # ===== TECHNOLOGY =====

    T["how database indexes speed up queries"] = {
        "_cat": "technology",
        "what": "auxiliary data structures (most commonly B+ trees, hash tables, or LSM-trees) that databases maintain alongside tables to allow rapid lookup of rows by key without scanning the entire table",
        "how": "a B+ tree index keeps keys in sorted order in a balanced tree, with leaves linked for range scans. Lookup descends the tree in O(log n) page reads. Hash indexes give O(1) point lookups but cannot range-scan. The query planner uses statistics to decide whether to use an index or scan the full table; selectivity, table size, and index cost matter",
        "why": "indexes turn a query that scans gigabytes into one that reads kilobytes. Without indexes, even simple lookups on a million-row table can take seconds; with the right index they take microseconds. Index design is one of the highest-leverage performance levers in database tuning",
        "vs": "B+ tree indexes differ from hash indexes (faster point lookup, no range scans) and from LSM-trees (write-optimized, common in NoSQL). Indexes differ from materialized views (which store query results) and from full-text indexes (which use posting lists for word search). Composite indexes on multiple columns differ from single-column indexes in which queries they accelerate",
        "ex": "adding an index on a 100-million-row users table's email column changes a SELECT WHERE email = ... query from a full-table scan (seconds) to an index lookup (milliseconds). The trade-off is slower writes (each insert/update must also update the index) and additional disk space",
        "mis": "people add indexes on every column and assume queries get faster. Each index slows writes and consumes space; redundant indexes hurt overall performance. Another myth is that the database always uses an index when one exists; if a query touches a large fraction of the table, a full scan can be faster than random index lookups",
    }

    T["how Git's commit graph works"] = {
        "_cat": "technology",
        "what": "the directed acyclic graph of commits that Git uses to represent the history of a repository, where each commit references its parent(s), a tree of files, an author, and a message, identified by a SHA-1 (or SHA-256) hash of its contents",
        "how": "every commit stores a snapshot of the repository (via a tree object pointing to blob objects for files) and the SHA hash of its parent commit (or two parents for merges). Hashes form a Merkle DAG: changing any file changes the tree, which changes the commit, which changes every later commit. Branches are simply named pointers to commits; checkout, merge, and rebase manipulate which commits are reachable from each branch",
        "why": "the commit graph makes Git distributed, integrity-checked, and efficient. Any clone has the full history. Tampering with old history changes hashes, making it detectable. Merge resolution uses common ancestors found by graph traversal. Tools like git log, git bisect, and git rebase all operate on this graph",
        "vs": "Git's commit graph differs from centralized VCS like Subversion (linear revision numbers, central server authority) and from snapshot-only filesystems (no parent tracking). It differs from a simple log file by its DAG structure (multiple branches and merges) and Merkle hashing (tamper-evident)",
        "ex": "a feature branch with three commits, merged back into main with a merge commit, produces a diamond-shaped subgraph: main's tip and the feature tip share an ancestor, and the merge commit has two parents. git log --graph visualizes this; rebase rewrites it into a linear sequence by replaying commits onto the tip",
        "mis": "people think a commit stores a diff. Git stores full snapshots of file contents, deduplicated by hash; diffs are computed on demand. Another myth is that branches are heavy objects; a branch is literally a 40-character file holding a commit hash, making branching practically free",
    }

    T["how containers differ from virtual machines"] = {
        "_cat": "technology",
        "what": "two technologies for isolating workloads on a single physical machine: containers share the host kernel and isolate at the OS level using namespaces and cgroups, while virtual machines run a full guest OS on virtualized hardware via a hypervisor",
        "how": "a container is a process tree running with separated views of mount points, networks, processes, users, and IPC, plus resource limits via cgroups. It uses the host kernel directly, starting in milliseconds with overhead near native. A VM, by contrast, runs a complete OS image atop a hypervisor that emulates or paravirtualizes hardware; boot takes seconds to minutes, with measurable but small CPU overhead and significant memory cost",
        "why": "the choice shapes deployment density, startup latency, security boundaries, and operational complexity. Containers enabled microservices and modern CI/CD by making deployments lightweight and reproducible. VMs remain essential where strong isolation is required (multi-tenant clouds, untrusted workloads) or where running different kernels is needed",
        "vs": "containers differ from VMs in kernel sharing, weight, and isolation guarantees. They differ from process isolation alone (no kernel sharing in VMs; weaker but real isolation in containers). Newer technologies like Firecracker microVMs and gVisor narrow the gap by combining VM isolation with container-like overhead, blurring the line",
        "ex": "AWS Lambda runs each function in a Firecracker microVM that boots in ~125 milliseconds and uses about 5 MiB of overhead, achieving VM-grade isolation with container-like density. Traditional VMs (EC2 instances) take seconds to minutes to boot and consume hundreds of MiB of overhead each",
        "mis": "people think containers are inherently insecure. With user namespaces, seccomp filters, AppArmor or SELinux profiles, and proper image hygiene, containers achieve solid isolation suitable for trusted multi-tenant environments. Another myth is that VMs are obsolete; for security-critical or kernel-level workloads, they remain the standard",
    }

    T["how SAT solvers work"] = {
        "_cat": "technology",
        "what": "programs that decide whether a Boolean formula in conjunctive normal form has a satisfying assignment, using algorithmic techniques (DPLL with conflict-driven clause learning, CDCL) that solve real-world instances with millions of variables despite the NP-hard worst case",
        "how": "modern SAT solvers extend DPLL with: choosing a variable, propagating implied assignments via unit propagation, and backtracking on conflicts. CDCL adds learned clauses derived from analyzing each conflict, restarts to escape stuck regions, and activity-based variable heuristics (VSIDS) that focus search on recently useful variables. These ideas make practical performance vastly outperform worst-case bounds",
        "why": "SAT solvers underpin formal verification of hardware and software, cryptanalysis, planning in AI, dependency resolution in package managers, and combinatorial optimization. Modern microprocessor verification is unthinkable without SAT-based and SMT-based tools; bugs that would have shipped are caught in design phases",
        "vs": "SAT solvers differ from SMT solvers (which extend SAT to handle theories like arithmetic, arrays, bit-vectors), from constraint solvers (which work over richer domains), from brute-force enumeration (impossible at industrial scales), and from heuristic search (which gives no guarantee of completeness)",
        "ex": "Intel and AMD use SAT and SMT solvers extensively in chip verification, encoding correctness properties of arithmetic units and memory systems as Boolean formulas. The 1994 Pentium FDIV bug, which slipped past pre-SAT verification, shipped to millions of CPUs and cost Intel about 475 million USD; modern solvers catch such errors before tape-out",
        "mis": "people assume NP-hardness means SAT is useless in practice. CDCL solvers handle industrial instances with millions of variables in seconds, vastly outperforming theoretical worst-case bounds on structured inputs. Another myth is that all SAT solvers are similar; performance gaps of 1000x or more across solvers on the same instance are common",
    }

    # ===== HISTORY =====

    T["the Aksumite Empire of Ethiopia"] = {
        "_cat": "history",
        "what": "the ancient kingdom centered in modern northern Ethiopia and Eritrea, flourishing from roughly the 1st to 7th century CE, controlling Red Sea trade between Rome, India, and the African interior, and notable as one of the earliest states to officially adopt Christianity",
        "how": "Aksum's wealth came from controlling the port of Adulis on the Red Sea, exporting ivory, gold, and slaves and importing Roman, Persian, and Indian goods. King Ezana converted to Christianity around 330 CE under the influence of Frumentius, making Aksum the first sub-Saharan African Christian state. The empire minted its own coinage (the only sub-Saharan African polity to do so in antiquity), built monumental stelae, and maintained literacy in the Ge'ez script",
        "why": "Aksum was a major late-antique trade power, contemporary to Rome, Sasanian Persia, and Gupta India, and its early Christianity gave rise to the Ethiopian Orthodox Church, which has continuously preserved religious texts and traditions for nearly 1700 years. Aksum thus connects African, Mediterranean, and Indian Ocean histories and refutes any narrative of African isolation in antiquity",
        "vs": "Aksum differs from contemporary Roman provinces (a sovereign African polity, not a colony), from later Ethiopian dynasties (medieval Solomonic, modern Imperial Ethiopia), and from coastal African trading societies that did not develop comparable monumental architecture or coinage. It contrasts with Egypt as a separate African civilizational core",
        "ex": "the Stelae of Aksum, granite obelisks up to 33 meters tall (when standing), mark royal burials. The Obelisk of Aksum was looted by Mussolini's forces in 1937 and erected in Rome; after a long campaign, it was returned to Ethiopia in 2005, reassembled in Aksum in 2008, a notable case of restitution in cultural heritage",
        "mis": "people picture sub-Saharan Africa as lacking literate, urban civilizations before colonialism. Aksum, the Mali Empire, Great Zimbabwe, and others demonstrate the opposite. Another myth is that Aksumite Christianity is a recent missionary import; it predates most European Christianity and has its own scriptures and liturgy in Ge'ez",
    }

    T["the Iranian Constitutional Revolution"] = {
        "_cat": "history",
        "what": "the 1905-1911 movement that established Iran's first parliament (Majles) and constitution, limiting the powers of the Qajar monarchy and inspiring constitutional reform across the broader Middle East, although counter-revolutionary moves and foreign intervention undercut its institutional gains",
        "how": "merchants, clerics, and intellectuals, frustrated by economic concessions to foreign powers and arbitrary royal taxation, mounted strikes and bazaar shutdowns in 1905-1906. The shah signed a constitution and convened a Majles in 1906. After his death, his successor Mohammad Ali Shah bombarded the Majles in 1908; constitutionalist forces from Tabriz and elsewhere reconquered Tehran in 1909, deposed him, and restored the constitution. Russian intervention in 1911 halted constitutional consolidation",
        "why": "the revolution introduced parliamentary politics, written law, and an explicit limitation of royal power into Iran, all influences felt through the 20th century to the 1979 Revolution. It was one of the first major constitutional revolutions in Asia, contemporaneous with the 1905 Russian Revolution and the 1908 Young Turk Revolution, and showed that constitutional ideas were not exclusively Western",
        "vs": "the Iranian Constitutional Revolution differs from later Iranian movements (the 1953 nationalist crisis under Mossadegh, the 1979 Islamic Revolution) by being earlier, more elite-led, and resulting in parliamentary monarchy rather than republic or theocracy. It differs from European constitutional revolutions in occurring under semi-colonial pressure from Britain and Russia",
        "ex": "the Anglo-Russian Convention of 1907 divided Iran into spheres of influence: a Russian sphere in the north, a British in the south, with a neutral zone between. This carve-up, signed without Iranian consent, effectively undermined the constitution and helped the 1911 Russian intervention proceed without British objection",
        "mis": "people think the Middle East had no indigenous constitutional tradition before the Arab Spring. Iran's 1906 constitution and the 1908 Young Turk Revolution show otherwise. Another myth is that the revolution was strictly secular; many leading clerics, especially the Tabriz and Najaf scholars, supported constitutionalism as compatible with Islamic law",
    }

    T["the Haitian Revolution"] = {
        "_cat": "history",
        "what": "the 1791-1804 uprising in the French colony of Saint-Domingue (modern Haiti) by enslaved Africans and free people of color that overthrew slavery and French colonial rule, established the first independent state in Latin America and the only nation born from a successful slave revolt",
        "how": "the revolution began with a coordinated August 1791 uprising on the rich northern plain plantations. Enslaved leaders including Boukman, Toussaint Louverture, and Jean-Jacques Dessalines built disciplined armies, played French, British, and Spanish forces against each other, and eventually defeated a Napoleonic expeditionary force sent in 1802 to restore slavery. Dessalines proclaimed independence on January 1, 1804, and renamed the country Haiti",
        "why": "the revolution destroyed the world's richest sugar colony, helped trigger the Louisiana Purchase (Napoleon abandoned plans for an American empire after losing Saint-Domingue), inspired enslaved people across the Americas, terrified slaveholders into harsher restrictions, and established the moral and political precedent that enslaved people could win freedom by force. It is one of the most significant and most underrepresented revolutions of the modern era",
        "vs": "the Haitian Revolution differs from the American Revolution (which preserved slavery) and the French Revolution (which initially affirmed and then briefly abolished slavery in the colonies before Napoleon reinstated it). It differs from later Latin American independence wars, which were mostly led by creole elites who did not abolish slavery",
        "ex": "the 1791 burning of plantations on the northern plain destroyed roughly 1000 plantations and killed several thousand whites in days. The economic damage to the colony, which had been producing about half the world's coffee and 40 percent of its sugar, was so severe that France's colonial economy never fully recovered",
        "mis": "people think Haiti's later poverty proves the revolution failed. France imposed a crushing indemnity in 1825 (effectively requiring Haiti to pay reparations to former slaveholders for their lost 'property'), debt that took until 1947 to clear and that historians estimate cost Haiti hundreds of billions in lost development. Another myth is that Toussaint achieved independence; he was captured by the French and died in prison in 1803; Dessalines completed the revolution",
    }

    T["the Inca road system"] = {
        "_cat": "history",
        "what": "the Qhapaq Nan, the integrated network of about 40,000 km of roads, bridges, and waystations built and maintained by the Inca Empire across the rugged Andes, connecting the empire from modern Colombia to Argentina at its peak in the 15th century",
        "how": "the system used two main north-south trunk routes (a coastal road and a highland road) connected by transverse links. Where terrain demanded, Inca engineers cut steps into cliffs, built suspension bridges of woven ichu grass over canyons, and laid stone-paved sections through swamps. Tambos (waystations) and qollqas (storehouses) along the route fed runners (chasquis) who carried messages by relay at speeds reaching about 240 km per day",
        "why": "the road system enabled the Inca to administer an empire of 10-12 million people without writing or wheeled vehicles, by moving armies, taxes (in the form of labor and goods), and information rapidly. UNESCO designated the Qhapaq Nan a World Heritage site in 2014 across six countries, recognizing it as one of the great engineering achievements of pre-industrial humanity",
        "vs": "the Inca road system differs from the Roman roads in being built without wheeled transport (the Inca had no draft animals other than llamas), in following terrain rather than imposing straight lines, and in including suspension bridges as routine elements. It differs from later colonial road networks, which often abandoned Inca routes for ports and mines",
        "ex": "the Q'eswachaka rope bridge over the Apurimac River in Peru is rebuilt every year by local communities using traditional ichu-grass weaving techniques, in a four-day collective ritual. It is the last continuously practiced Inca bridge tradition and offers a working example of how the empire spanned canyons impassable by stone arches",
        "mis": "people think pre-Columbian Americas lacked complex infrastructure. The Inca road network is comparable in scale to the Roman empire's road system, built across far more difficult terrain. Another myth is that the Spanish destroyed the system; many segments fell into disuse not from active destruction but because the Spanish economy did not depend on llama caravans and runner relays",
    }

    # ===== ARTS AND HUMANITIES =====

    T["the development of perspective in Western painting"] = {
        "_cat": "arts_and_humanities",
        "what": "the technique, codified in early-15th-century Florence, of representing three-dimensional space on a flat surface using mathematical rules so that parallel lines converge to vanishing points, transforming Western painting's depiction of space",
        "how": "Filippo Brunelleschi performed an experiment around 1413 painting the Florence Baptistery with a mirror and viewing peephole, demonstrating geometric perspective. Leon Battista Alberti's 1435 treatise On Painting formalized the construction: a horizon line, vanishing points, and a grid of orthogonals constructed from a fixed viewpoint. Painters from Masaccio onward used these rules to position figures convincingly in space",
        "why": "perspective changed how Europeans saw images and arguably how they understood space itself. Combined with the printing press, it allowed widespread study of optics, architecture, and engineering. Albrecht Durer, Piero della Francesca, and others produced manuals that fed Renaissance and Baroque art, and the same geometry underlies modern computer graphics and photography",
        "vs": "linear perspective differs from atmospheric perspective (using color and contrast for depth, used by Leonardo and Chinese landscape painters), from isometric/axonometric projection (used in Chinese, Japanese, and modern engineering drawings), and from medieval European depictions, which conveyed importance through scale and position rather than geometric viewpoint",
        "ex": "Masaccio's Trinity fresco (c. 1427) in Santa Maria Novella in Florence is one of the earliest masterworks of single-point perspective. The barrel-vaulted chapel appears to recede into the wall convincingly enough that contemporary viewers reportedly thought a real chapel had been opened in the church",
        "mis": "people think perspective is the only correct way to depict space. It is one cultural and historical convention, not a universal truth; East Asian landscape traditions developed equally sophisticated but different conventions. Another myth is that perspective was unknown before Brunelleschi; Greco-Roman wall paintings show empirical attempts, but the systematic geometric method was a Renaissance achievement",
    }

    T["the modernist novel"] = {
        "_cat": "arts_and_humanities",
        "what": "a literary movement of roughly 1900-1940 that broke with 19th-century realist conventions through experimental form, interior consciousness, fragmented narration, and skepticism about objective truth, exemplified by Joyce, Woolf, Proust, Faulkner, Kafka, and Mann",
        "how": "modernist novels deploy stream-of-consciousness narration (Joyce's Ulysses, Woolf's Mrs Dalloway), unreliable narrators, multiple perspectives (Faulkner's The Sound and the Fury), nonlinear time (Proust's Remembrance of Things Past), fragmented language, and intertextual allusion. The movement responded to Freud, Nietzsche, World War I's shattering of progressivist optimism, and new technologies of cinema, telegraphy, and mass media",
        "why": "modernist techniques permanently changed what novels could do, making interior subjective experience central, expanding the formal range available to writers, and dissolving the assumption that fiction must tell a coherent linear story. They influenced postmodernism, magical realism, and most subsequent serious literary fiction",
        "vs": "the modernist novel differs from Victorian realism (panoramic, omniscient, morally certain), from postmodernism (which often parodies modernist seriousness and embraces playfulness), from genre fiction (which generally maintains realist conventions), and from socialist realism (which rejected modernist forms ideologically)",
        "ex": "the final chapter of Joyce's Ulysses (1922), Molly Bloom's monologue, runs about 24,000 words across just eight unpunctuated sentences, capturing Molly's interior thoughts as she falls asleep. It is the form's most famous demonstration that prose can render consciousness more directly than narrated description",
        "mis": "people think modernist novels are deliberately obscure to be elitist. The difficulty often serves the project of representing how thought actually works, which is rarely linear. Another myth is that modernism is dead; writers from Sebald to Saunders to Solvej Balle continue the modernist project of pushing form to handle new aspects of consciousness",
    }

    # ===== EVERYDAY_LIFE =====

    T["how to read an electricity bill"] = {
        "_cat": "everyday_life",
        "what": "the structured statement from a utility company itemizing energy consumed (in kilowatt-hours), the rate or rates per kilowatt-hour, fixed monthly charges, taxes and surcharges, and the resulting total amount due for a billing period",
        "how": "the bill shows a meter reading at the start and end of the period; the difference (in kWh) is the consumption. Charges combine usage at the applicable rate (flat, tiered, or time-of-use), a fixed customer charge, distribution fees, environmental surcharges, and taxes. Many bills include a year-over-year usage comparison and a graph of monthly use",
        "why": "understanding the bill enables informed energy decisions: identifying inefficient appliances, switching to time-of-use pricing if available, sizing solar arrays, and budgeting for seasonal swings. Bills also surface program eligibility (low-income discounts, weatherization, EV rates) that customers often miss",
        "vs": "an electricity bill differs from a gas bill (priced per therm or cubic foot), a water bill (priced per gallon or cubic meter), and a fixed-rate flat-fee service. It differs from a postpaid mobile bill in that consumption is measured by a regulated meter; metering disputes are governed by utility commission rules",
        "ex": "a household using 800 kWh per month at a tiered rate of 0.12 USD per kWh for the first 500 kWh and 0.18 USD per kWh above, plus a 12 USD customer charge, would owe 0.12 times 500 plus 0.18 times 300 plus 12, equal to 60 plus 54 plus 12, which is 126 USD before taxes and surcharges",
        "mis": "people think the customer charge can be avoided. It is a fixed access fee unrelated to usage; even zero-consumption months still owe it. Another myth is that all kWh cost the same; in tiered or time-of-use plans, the same kWh used at different times or above thresholds can cost very different amounts",
    }

    T["how mortgages work in practice"] = {
        "_cat": "everyday_life",
        "what": "long-term loans (commonly 15 or 30 years in the US) used to buy property, secured by the property itself, with predictable monthly payments split between principal and interest plus often escrowed taxes and insurance",
        "how": "lenders evaluate the borrower's credit, income, debts, and down payment to set the loan amount and rate. Each monthly payment applies to interest first (computed on the remaining balance) and the rest to principal, so early payments are mostly interest. Amortization schedules show this front-loading. Property taxes and insurance are commonly collected monthly and paid yearly from an escrow account",
        "why": "mortgages let people buy homes without saving the full price, channel long-term household wealth into a single asset, and link housing markets tightly to interest rates. Mortgage policy (loan-to-value limits, government guarantees, tax deductions) shapes home affordability and macroeconomic risk, as the 2008 crisis demonstrated",
        "vs": "a 30-year fixed-rate mortgage differs from a 15-year (faster payoff, lower lifetime interest, higher monthly payment), from an adjustable-rate mortgage (ARM, lower initial rate but exposure to future rate increases), and from interest-only loans (no principal reduction during an initial period). Government-backed loans (FHA, VA, USDA) differ from conventional in qualification rules and insurance requirements",
        "ex": "a 400,000 USD 30-year fixed mortgage at 6.5 percent has a principal-and-interest payment of about 2528 USD per month. Over 30 years, the borrower pays about 510,000 USD in interest, a fact that surprises many first-time homebuyers and motivates extra-principal payments or 15-year refinances",
        "mis": "people think paying off the mortgage as fast as possible is always optimal. With low fixed rates and tax deductions on mortgage interest, low-cost debt may be left in place while excess cash invests at higher returns. Another myth is that a 30-year mortgage means you cannot pay it off early; almost all US mortgages allow prepayment without penalty",
    }

    # ===== CURRENT_EVENTS =====

    T["the global decline in birth rates"] = {
        "_cat": "current_events",
        "what": "the sustained drop in the number of children per woman across most of the world since the 1960s, with many high-income countries (and increasingly middle-income ones) below the replacement level of about 2.1, and global fertility projected to fall below replacement around the 2050s",
        "how": "the decline tracks rising female education and labor-force participation, urbanization, falling child mortality, expanding access to contraception, rising costs of child-rearing, and changing gender and family norms. Birth rates have fallen fastest where these factors compound: South Korea has reached about 0.7 children per woman, Italy and Japan about 1.3, China about 1.1; even traditionally high-fertility countries like India have reached or fallen below replacement",
        "why": "low fertility ages populations rapidly, straining pension and healthcare systems built on growing tax bases, shrinking labor forces, raising real wages but lowering aggregate growth, and pushing governments toward immigration and pro-natalist policy. China's working-age population is shrinking by millions per year; Japan has been adapting for decades; the implications for housing, real estate, and geopolitics are far-reaching",
        "vs": "the current decline differs from past demographic transitions in its global reach and its persistence below replacement. Pro-natalist policies tested in Hungary, France, South Korea, and elsewhere have at best delayed declines; cultural and economic patterns appear stickier than cash incentives. The decline differs from the Baby Boom (a one-generation rebound after WWII) in being structural",
        "ex": "South Korea's total fertility rate fell from 6 in 1960 to 0.72 in 2023, the lowest ever recorded for a non-microstate. The country has tried tax credits, parental leave, housing subsidies, and large-scale childcare expansion; none has reversed the trend, suggesting that work culture, housing costs, and gender norms are binding constraints",
        "mis": "people think low birth rates only affect rich countries. Most of the world's population now lives in countries below replacement fertility. Another myth is that low fertility solves climate or resource problems; the population pyramid effects (rapid aging) impose major costs and the per-capita emissions in older, wealthier societies remain high",
    }

    T["the post-2022 surge in interest rates and its consequences"] = {
        "_cat": "current_events",
        "what": "the sharp increase in central bank policy rates by the US Federal Reserve, ECB, Bank of England, and others between 2022 and 2023 to combat post-pandemic inflation, lifting the federal funds rate from near zero to 5.25-5.5 percent in roughly 16 months, the fastest pace in four decades",
        "how": "central banks raise rates by changing the rates they pay or charge in money markets, which propagates to interbank lending, mortgages, business loans, and bond yields. Higher rates make borrowing more expensive, slow demand growth, raise the discount applied to future cash flows in asset pricing, and strengthen the currency. The Fed pairs rate hikes with quantitative tightening, letting bonds run off its balance sheet rather than reinvesting",
        "why": "rate hikes substantially slowed inflation from peaks above 9 percent in 2022 to closer to 3 percent by 2024, but they also stressed bank balance sheets (Silicon Valley Bank's 2023 collapse), depressed commercial real estate values, raised mortgage rates above 7 percent, weakened housing affordability, and shifted capital flows toward dollar assets, complicating emerging-market debt servicing",
        "vs": "the 2022-2023 cycle differs from the slower hikes of 2015-2018 in pace and from 1980s Volcker hikes in inflation backdrop and starting level. Unlike the 2008 crisis response, this was tightening not easing. Different central banks moved at different paces, with the Bank of Japan as the notable holdout, only beginning to lift rates from negative territory in 2024",
        "ex": "the average 30-year US mortgage rate rose from about 3.0 percent in late 2021 to over 7.5 percent by late 2023, lifting monthly payments on a 400,000 USD loan by roughly 1100 USD. New-home sales and existing-home turnover both fell sharply, and homeowners with low fixed rates locked in by 2021 became reluctant to sell, freezing parts of the housing market",
        "mis": "people think rate hikes act immediately. Monetary policy works with lags of 6-18 months; full effects on inflation, unemployment, and asset prices unfold over years. Another myth is that the cuts that follow restore everything; the cumulative damage to households who took variable-rate debt or to banks holding low-coupon bonds is not undone by symmetric rate paths",
    }

    T["the maturation of renewable energy"] = {
        "_cat": "current_events",
        "what": "the transition of solar photovoltaic, onshore wind, and battery storage from premium-priced technologies a decade ago to the cheapest sources of new bulk electricity in most regions, accelerated by manufacturing scale and policy support",
        "how": "learning curves and Chinese manufacturing scale drove solar module costs down by about 90 percent in the 2010s. Wind turbine sizes grew steeply, raising capacity factors and lowering costs. Lithium-ion battery prices fell about 90 percent over the same decade. Auctions and corporate power-purchase agreements priced these technologies into wholesale markets, and global installations surpassed coal additions for the first time in many years",
        "why": "the maturation reframed climate policy from being primarily about higher costs to being about transition speed, grid integration, and supply chains. It also reshaped electricity markets, undermining baseload coal plant economics, changing oil and gas company strategies, and giving China dominant positions in solar manufacturing, wind, and battery cells",
        "vs": "current renewables differ from earlier generations in cost, scale, and reliability. They differ from nuclear (high upfront cost, low fuel cost, dispatchable, slow to build) and from natural gas (dispatchable, fuel-price exposed, lower than coal but nonzero carbon). Hybrid solar-plus-storage projects increasingly compete head-to-head with combined-cycle gas plants on price",
        "ex": "the median levelized cost of utility-scale solar in good locations fell to roughly 30 USD per megawatt-hour by 2024, below the operating cost of many existing coal plants. Several US utilities have proposed early coal retirements with replacement by solar plus storage on pure economic grounds, with regulatory and labor concerns now the binding constraints rather than levelized cost",
        "mis": "people think renewables remain expensive luxury options. They are now the cheapest new generation in most markets, including India and the US Sun Belt. Another myth is that intermittency makes them unsuitable; modern grids handle high renewable shares using storage, demand response, transmission, and remaining gas peaking, and several regions already operate with 50 percent or higher annual renewable electricity",
    }
