#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank: arts_and_humanities + everyday_life topics (fresh for batch G)."""


def register(T):
    # arts_and_humanities
    T["the development of perspective in Renaissance painting (sfumato and chiaroscuro)"] = {
        "_cat": "arts_and_humanities",
        "what": "the suite of techniques developed by Italian Renaissance painters, especially Leonardo da Vinci, where sfumato uses gradual, smoke-like tonal transitions to soften edges and chiaroscuro uses strong contrasts of light and dark to model three-dimensional volume on a flat surface",
        "how": "sfumato builds up many translucent oil glazes, each only slightly different in tone, so contour lines disappear and forms emerge from atmospheric gradients. Chiaroscuro establishes a single dominant light source and tracks its consequences across surfaces, with deeper shadows in occluded areas and bright highlights on raised forms. Together they create three-dimensional illusion without explicit outlines, replacing medieval painting's clean linear contours with tonal modeling that mimics how the eye actually perceives form",
        "why": "these techniques carried Western painting from symbolic representation toward optical realism, made portraits feel psychologically alive, established conventions still used in academic painting, photography, and cinema, and prepared the ground for Caravaggio's tenebrism, Rembrandt's interior light, and the entire baroque sensibility",
        "vs": "sfumato differs from earlier Flemish oil glazing, which emphasized crisp detail and saturated color, and from later impressionist broken color, which built form from optical mixture rather than tonal blending. Chiaroscuro differs from tenebrism (the more extreme version with near-black shadows) and from the high-key lighting of rococo painting, which avoided strong contrasts",
        "ex": "Leonardo's Mona Lisa exemplifies sfumato in the corners of the mouth and eyes, where edges dissolve into gradient zones that produce the famously ambiguous expression. Caravaggio's The Calling of Saint Matthew uses chiaroscuro so dramatic that figures emerge from near-black space under a single dramatic shaft of light",
        "mis": "people think sfumato just means soft edges. The technique is much more specific: imperceptible gradations across hundreds of glazes that physically scatter light differently than blended brushwork. Another myth is that chiaroscuro began with Caravaggio; Renaissance masters had been exploring it for over a century, but Caravaggio's extremity made the term shorthand for his style",
    }

    T["the structure of a sonnet"] = {
        "_cat": "arts_and_humanities",
        "what": "a fourteen-line lyric poem in iambic pentameter following one of two main rhyme schemes: the Petrarchan (Italian) form, divided into an octave (ABBAABBA) and a sestet (variable, often CDECDE), or the Shakespearean (English) form, three quatrains plus a final couplet (ABABCDCDEFEFGG)",
        "how": "the Petrarchan sonnet typically poses a problem in the octave and resolves it after a volta (turn) at line 9. The Shakespearean sonnet often develops three variations on a theme across the quatrains and lands a punchline in the final couplet. Iambic pentameter (five iambic feet, ten syllables per line) sets the rhythmic skeleton; substitutions, enjambment, and caesurae give individual sonnets their voice. The compact form forces compressed argument and intense emotional pressure within a small frame",
        "why": "the sonnet became Western poetry's most enduring fixed form, used by Petrarch, Shakespeare, Donne, Wordsworth, Browning, Hopkins, Frost, and contemporary poets. Its constraints make it a benchmark for craft, its volta a model for argumentative or emotional turns, and its musicality a doorway into iambic English verse",
        "vs": "the sonnet differs from the Spenserian sonnet (a hybrid using ABABBCBCCDCDEE) and from related forms like the villanelle, sestina, and rondeau. It differs from blank verse drama, which uses iambic pentameter without rhyme. It differs from free verse, which abandons fixed metrical and rhyme structures entirely",
        "ex": "Shakespeare's Sonnet 18 ('Shall I compare thee to a summer's day?') exemplifies the English form: three quatrains develop the comparison, the volta at line 9 ('But thy eternal summer shall not fade') turns from nature's mutability to art's preservation, and the closing couplet drives home the boast that the poem itself confers immortality",
        "mis": "people think Shakespeare invented the sonnet. Petrarch made the Italian form famous in the fourteenth century; Wyatt and Surrey introduced it to English in the early sixteenth, and the 'Shakespearean' rhyme scheme was already established when Shakespeare adopted it. Another myth is that all sonnets must rhyme; modern poets like Gerard Manley Hopkins and Tony Lopez wrote sonnets in unconventional meter and rhyme, exploring the form's elasticity",
    }

    T["jazz and improvisation"] = {
        "_cat": "arts_and_humanities",
        "what": "an African American musical tradition that emerged in early twentieth-century New Orleans, fusing blues, ragtime, and band traditions, characterized by syncopated rhythm, blue tonality, swing feel, and individual or collective improvisation over harmonic progressions",
        "how": "jazz musicians improvise melodic lines over a chord progression (the changes), generating new music in real time within shared rules: knowing the harmony, voice-leading principles, scales appropriate to each chord, and the form (often AABA, blues, or rhythm changes). Rhythmic feel comes from swing eighths, syncopation, and interaction with the rhythm section. The tradition developed through New Orleans, Chicago, swing era big bands, bebop's harmonic acceleration, modal jazz, free jazz, fusion, and contemporary post-bop",
        "why": "jazz reshaped twentieth-century music globally, influencing classical composers (Stravinsky, Ravel, Copland), pop and rock, hip-hop sampling, and film scoring. It documented African American cultural expression under segregation, exported American culture worldwide, and established improvisation as a peer to composition in serious art music",
        "vs": "jazz differs from classical music in centering performer creation over composer specification. It differs from blues in adding harmonic complexity and ensemble interplay; from rock and pop in making improvisation central rather than ornamental. Within jazz, bebop differs from swing in tempo, harmonic density, and small-group focus; modal jazz differs from bebop in using static modes rather than rapidly changing chord progressions",
        "ex": "Miles Davis's 1959 album Kind of Blue, recorded with a sextet including John Coltrane and Bill Evans, used minimal modal frameworks (so what minor on D and E flat) instead of dense bebop changes, freeing soloists to develop ideas across longer harmonic stretches. It became the best-selling jazz record of all time and a defining document of modal jazz",
        "mis": "people think jazz improvisation is random or unprepared. Improvisation operates within strict harmonic and rhythmic constraints; great players have practiced thousands of hours and absorbed the language of dozens of predecessors. Another myth is that jazz peaked decades ago; contemporary players (Vijay Iyer, Esperanza Spalding, Kamasi Washington) are extending the tradition in active dialogue with hip-hop, electronics, and global musics",
    }

    T["existentialism in twentieth-century philosophy"] = {
        "_cat": "arts_and_humanities",
        "what": "a philosophical movement centered in mid-twentieth-century France that emphasized individual existence, freedom, choice, and meaning-making in a universe without given essence, associated with Jean-Paul Sartre, Simone de Beauvoir, Albert Camus, and Martin Heidegger",
        "how": "Sartre articulated 'existence precedes essence': humans are not born with a fixed nature but become themselves through choices in concrete situations. This freedom produces anguish (responsibility for one's own being), bad faith (self-deception about one's freedom), and demand for authenticity. De Beauvoir extended the analysis to women's situation in The Second Sex (1949). Camus pursued the absurd: the gap between human demand for meaning and the universe's silence, with revolt as the answer. Heidegger's Being and Time (1927) supplied much of the conceptual vocabulary, especially Dasein, throwness, and being-toward-death",
        "why": "existentialism gave the post-WWII generation a vocabulary for individual moral responsibility in a world that had failed religious and political certainties. It influenced theology, psychotherapy (Frankl, May, Yalom), feminist theory, postcolonial writing, and literary modernism. Even now, debates about authenticity, meaning, and freedom in secular cultures rely on its frameworks",
        "vs": "existentialism differs from analytic philosophy in style and concerns, addressing lived experience and meaning rather than language and logic. It differs from earlier German idealism in rejecting comprehensive metaphysical systems and from logical positivism in taking subjective experience seriously. It differs from later structuralism and post-structuralism, which dissolved the autonomous subject the existentialists made central",
        "ex": "Sartre's 1945 lecture 'Existentialism Is a Humanism' introduced the slogan 'existence precedes essence' to a public audience. He argued that without a creator God to define human nature, we are condemned to be free and entirely responsible for who we become through choices, with no excuses available from inherited identity, social role, or psychological determination",
        "mis": "people think existentialism is pessimism or nihilism. Existentialists argued meaning is real but must be created by individuals rather than received; that is a high-stakes claim, not a denial of meaning. Another myth is that existentialism is irrationalist; Sartre and de Beauvoir wrote dense systematic philosophy, and Camus's absurdism is an argument from premises, not a celebration of unreason",
    }

    T["film noir as a cinematic style"] = {
        "_cat": "arts_and_humanities",
        "what": "a Hollywood cycle of crime films from roughly 1941 to 1958, marked by chiaroscuro lighting, urban settings, morally ambiguous protagonists, fatalistic plots, voice-over narration, and femme fatale figures, retroactively named by French critics for its dark visual and thematic register",
        "how": "noir adapted German Expressionist cinematography brought by emigre directors (Lang, Wilder, Siodmak), pulp fiction by Hammett, Chandler, and Cain, and postwar American anxiety. Visually it relied on low-key lighting, deep shadows, Venetian-blind patterns, wet streets, off-kilter angles, and night exteriors. Narratively it favored amnesia, double-crosses, doomed romance, flashback structures, and protagonists whose hardboiled cynicism barely concealed despair. Studio system constraints encouraged tight budgets and star casting that gave the cycle stylistic coherence",
        "why": "film noir gave Hollywood a vocabulary for postwar disillusion, gender role anxiety, and the limits of redemption that the standard happy-ending formula avoided. Its visual conventions persist in neo-noir, science fiction (Blade Runner), and prestige TV (True Detective). It shaped how American cinema treats the city, crime, and moral compromise",
        "vs": "noir differs from the gangster film, which centered on rise-and-fall narratives of organized crime, and from earlier crime melodrama, which preserved clear moral hierarchies. It differs from neo-noir, the post-1960s revival that quoted noir conventions self-consciously (Chinatown, L.A. Confidential), and from European crime cinema, which evolved its own traditions like the French polar",
        "ex": "Billy Wilder's Double Indemnity (1944), based on James M. Cain's novel and co-written with Raymond Chandler, established many noir conventions: a flashback voice-over confession, a femme fatale (Phyllis Dietrichson), and an insurance investigator protagonist. Its murder plot moves from desire through cover-up to mutual destruction, the typical noir trajectory",
        "mis": "people think film noir is a genre. Critics now generally treat it as a stylistic cycle that crossed multiple genres (detective films, melodramas, social-problem films). Another myth is that all noir films are pessimistic; many have ambivalent or salvaged endings, and the cycle includes wide tonal variation, from the elegiac (The Big Sleep) to the satirical (Sweet Smell of Success)",
    }

    T["the function of myth in human culture"] = {
        "_cat": "arts_and_humanities",
        "what": "myths are traditional narratives, often involving gods, heroes, and cosmic events, that explain origins, sanction social practices, model moral frameworks, and give a community shared symbolic resources for understanding existence",
        "how": "myths are transmitted orally and in written canons, vary across retellings, and bind a community's identity to shared stories. They typically encode etiologies (why this place is sacred, why the seasons turn), charters (why the king rules, why marriage is contracted this way), and exempla (what virtues and vices look like enacted). Comparative mythologists (Frazer, Dumezil, Levi-Strauss, Eliade, Campbell) have proposed structural patterns: hero's journey, threefold Indo-European functions, binary oppositions, and recurrent themes of dying and rising gods",
        "why": "myth grounds religious practice, supplies political legitimacy, fuels literature and art across millennia, and gives individuals frameworks for understanding mortality, identity, and chance. Modern political myths (national origin stories, founder cults, ideologies of progress or decline) work the same machinery. Understanding myth illuminates everything from ancient texts to contemporary advertising and propaganda",
        "vs": "myths differ from folktales in being treated as true within their tradition rather than as entertainment, from legends in being set in mythic time rather than historical time, and from theology in being narrative rather than systematic. Modern usage that treats 'myth' as a synonym for 'falsehood' loses the analytic precision the older sense provides",
        "ex": "the Mesopotamian Epic of Gilgamesh, dating to roughly 2100 BCE, treats kingship, friendship, and mortality through Gilgamesh's quest for immortality after Enkidu's death. Its Flood account predates and parallels the Hebrew Bible's, illustrating how shared mythic motifs can travel between cultures while serving different theological purposes",
        "mis": "people think myth means false belief. In comparative religion and anthropology, myth is a category of narrative defined by function and form, not by truth value. Another myth is that ancient peoples literally believed every detail; ritualists and theologians often treated myths as symbolic, with sophisticated interpretive traditions, much as serious religious thinkers do today",
    }

    T["the novel as a literary form"] = {
        "_cat": "arts_and_humanities",
        "what": "an extended fictional prose narrative, typically over 40000 words, that develops characters and plot across multiple settings and arcs, considered the dominant literary form of the modern period since its eighteenth-century rise in Europe",
        "how": "novels use sustained narrative voice, structured plotting, and psychological interiority to explore characters across time. Conventions emerged through Defoe's pseudo-memoir, Richardson's epistolary form, Fielding's omniscient narration, and Austen's free indirect style. Realism, modernism, and postmodernism each reshaped what novels could do: from the social panoramas of nineteenth-century realism to the fragmented consciousness of Joyce and Woolf and the metafictional play of Borges, Calvino, and Pynchon",
        "why": "novels gave readers immersive access to other minds and other lives at unprecedented depth, shaped modern consciousness around interiority and individual development (the bildungsroman), educated political imagination (Uncle Tom's Cabin, Things Fall Apart), and remain the dominant prose form in literary culture and adaptation pipelines",
        "vs": "novels differ from epics in being prose, secular, and individual-focused; from short stories in scope and structural ambition; from drama in interior access and pacing; and from memoir in being explicitly fictional. The novel's openness to internal variation means subgenres (gothic, science fiction, mystery, romance, literary fiction) each have their own conventions while sharing the basic form",
        "ex": "Cervantes' Don Quixote (1605/1615) is often called the first modern novel: it parodies its predecessors, develops its protagonist psychologically, plays with narrative levels (a found manuscript translated by an Arabic historian), and treats its hero with both irony and sympathy in ways that established what later novelists would build on",
        "mis": "people think the novel was always the dominant form. It is a relatively recent literary genre that displaced epic poetry and verse drama only in the eighteenth and nineteenth centuries, helped by rising literacy and cheap print. Another myth is that novels are inherently realist; modernist and postmodernist novels question realism explicitly, and major traditions outside the West developed different formal possibilities",
    }

    T["abstract expressionism"] = {
        "_cat": "arts_and_humanities",
        "what": "the post-WWII American painting movement centered in New York from roughly 1946 to 1960, characterized by large-scale, gesturally or color-field-organized abstract canvases that emphasized the act of painting itself, associated with Jackson Pollock, Willem de Kooning, Mark Rothko, Barnett Newman, and Helen Frankenthaler",
        "how": "two main tendencies developed. Action painters (Pollock, de Kooning, Kline) emphasized physical gesture: dripped, poured, or slashed paint that recorded the artist's body's motion across the canvas. Color-field painters (Rothko, Newman, Still) used large unmodulated zones of color to elicit immersive emotional response. Both tendencies treated the canvas as an arena of action rather than a window onto a represented world. Critics like Clement Greenberg theorized abstraction as a logical endpoint of modernist self-reflection",
        "why": "abstract expressionism shifted the center of the Western art world from Paris to New York, established American painting as a global force, redirected art-historical attention from representation to medium and process, and shaped how subsequent abstraction, conceptual art, and contemporary painting all positioned themselves against or within its legacy. It was also a Cold War cultural export, championed by US institutions as expressive freedom",
        "vs": "abstract expressionism differs from earlier European abstraction (Kandinsky, Mondrian) in scale, gesture, and lack of geometric program. It differs from surrealism, an immediate predecessor, in dispensing with figural elements while retaining the unconscious as a source. It differs from later movements: pop art rejected its seriousness, minimalism its emotional charge, and conceptual art its commitment to physical painting",
        "ex": "Jackson Pollock's 1950 painting Number 31, created by dripping and pouring enamel paint on a canvas laid on the floor, is among the most reproduced images of twentieth-century art. The energetic web of lines records his motion and decisions; Hans Namuth's films of him working at Springs, Long Island, made the process itself a public artwork",
        "mis": "people think abstract expressionism was random or unskilled. The movement's leaders trained in academic technique and produced their abstractions through deliberate composition; Pollock's drips show controlled distribution and rhythm. Another myth is that the painters intended pure formalism; many wrote and spoke about myth, the unconscious, and emotion as central concerns",
    }

    T["the philosophy of mind and consciousness"] = {
        "_cat": "arts_and_humanities",
        "what": "the branch of philosophy concerned with the nature of mental states, their relation to physical processes, and the question of consciousness: how subjective experience arises from physical substrates and what its character actually is",
        "how": "different positions parse the field. Substance dualism (associated with Descartes) treats mind and matter as different kinds of stuff. Physicalism in various forms (identity theory, functionalism, eliminativism) treats mental states as fully reducible to or constituted by physical states. Property dualism accepts physical substance but argues mental properties are irreducible. The 'hard problem' of consciousness, articulated by David Chalmers, asks why physical processes are accompanied by subjective experience at all. Empirical work in cognitive science, neuroscience, and AI puts these positions under continual pressure",
        "why": "the philosophy of mind sits at the intersection of metaphysics, science, and ethics. How we treat machines, animals, and humans in vegetative states all turns partly on what consciousness is and what bears it. The recent advance of AI has revived debates about machine consciousness, moral status, and whether the questions are well-posed at all",
        "vs": "philosophy of mind differs from philosophy of psychology (which focuses on the methods and findings of psychology as a science), from neuroscience (which studies brains rather than concepts of mind), and from epistemology (which studies knowledge rather than mind). Functionalism differs sharply from biological views by allowing minds to be realized in any substrate that runs the right computations",
        "ex": "the Mary's Room thought experiment imagines a scientist who knows every physical fact about color vision but has lived in black and white, then sees red for the first time. Does she learn something new? If yes, then physical knowledge is not all the knowledge there is, supporting an antiphysicalist conclusion. The argument is debated continuously and remains a touchstone for the field",
        "mis": "people think consciousness is just the brain's electricity. That description is incomplete: the explanatory question is why the electricity is accompanied by experience at all, not whether it is. Another myth is that the field is purely speculative; it constrains and is constrained by empirical work in cognitive science and is increasingly active around AI",
    }

    # everyday_life
    T["the development of Western classical music's common-practice harmony"] = {
        "_cat": "arts_and_humanities",
        "what": "the system of tonal harmony developed in Europe between roughly 1650 and 1900, organized around major and minor keys, functional chord progressions (tonic, subdominant, dominant), modulation, and voice leading, which underlies the bulk of Western art music and shaped popular music throughout the twentieth century",
        "how": "the system codifies how chords function relative to a key center: tonic resolves, dominant pulls toward tonic via the leading tone, subdominant prepares the dominant. Cadences (authentic, plagal, deceptive) punctuate phrases. Modulation moves between keys via pivot chords or chromatic harmonies. Voice leading rules govern smooth movement of individual voices to avoid parallel fifths and octaves and to manage dissonance through preparation and resolution. The approach was systematized by theorists like Rameau (1722) and was the operative grammar of composers from Bach through Brahms",
        "why": "common-practice harmony is the substrate of Western art music's most performed repertoire (Bach's preludes, Mozart's symphonies, Beethoven's quartets, Wagner's operas), of nearly all jazz harmony, of film scores, and of pop music's standard chord progressions. Understanding it unlocks technical analysis, intelligent listening, and competent songwriting in any genre that descends from it",
        "vs": "common-practice harmony differs from earlier modal music (Renaissance polyphony, plainchant), which used different scale collections without the tonic-dominant polarity, and from twentieth-century post-tonal music (Schoenberg, Webern), which abandoned the system. It differs from non-Western traditions (Indian raga, Arabic maqam, Indonesian gamelan), which are organized around different scales, intervals, and ornamentation",
        "ex": "the chord progression I-V-vi-IV (tonic, dominant, submediant, subdominant) underlies hundreds of pop songs from Pachelbel through 'Don't Stop Believin'' to modern hits. Its persistence demonstrates how deeply common-practice tonal logic is embedded in popular music despite stylistic and timbral changes",
        "mis": "people think classical music's rules are arbitrary academic conventions. They emerged empirically over centuries as composers explored what worked sonically; many are descriptive rather than prescriptive. Another myth is that the system is universal; it is one specific tradition, and its elevation as a default reflects historical contingencies more than acoustic necessity",
    }

    T["how to read nutrition facts labels"] = {
        "_cat": "everyday_life",
        "what": "the standardized panel on US packaged food showing serving size, calories, fat (saturated and trans), cholesterol, sodium, total carbohydrates (fiber and added sugars), protein, and selected vitamins and minerals, along with daily value percentages for a 2000-calorie reference diet",
        "how": "start with serving size: everything below scales to that amount, which is often smaller than the package. Calories anchor the energy budget. Saturated fat, sodium, and added sugars are 'limit these' lines; fiber, protein, vitamin D, calcium, iron, and potassium are 'get enough' lines. The percent daily value gives a rough sense: 5 percent or less is low, 20 percent or more is high. Ingredient lists are ordered by weight; allergens are typically called out separately",
        "why": "labels enable informed comparison, help manage chronic disease (hypertension, diabetes, cardiovascular risk), reveal hidden sugars and sodium that drive most dietary problems, and let consumers spot ultra-processed foods masked as healthy. The 2016 FDA update added an 'added sugars' line and modernized serving sizes to reflect realistic consumption",
        "vs": "the US Nutrition Facts label differs from EU nutritional declarations (per 100 g and per portion, with reference intakes called RI), from UK traffic-light front-of-pack labels (color-coded thresholds), and from earlier US labels that did not distinguish added from naturally occurring sugars. Front-of-pack systems give faster signals; back-of-pack give precise data",
        "ex": "a 350 ml soft drink can shows 39 g of sugar, all added, equating to about 78 percent of the recommended daily limit. Two cans push you over the day's added-sugar budget before you have eaten anything else. The serving-size and per-package framing is what reveals just how concentrated the sugar load is",
        "mis": "people think serving sizes are recommendations. They are reference amounts for label purposes, not portion advice; the package itself often contains multiple servings. Another myth is that 'no added sugar' means low sugar; juices and dried fruit can be very high in naturally occurring sugar with comparable metabolic effect",
    }

    T["how a refrigerator's compressor cycle works"] = {
        "_cat": "everyday_life",
        "what": "a closed-loop heat pump that moves heat from the cold interior of the refrigerator to the warmer kitchen by cycling a refrigerant through compression, condensation, expansion, and evaporation",
        "how": "the compressor pressurizes refrigerant gas, raising its temperature above the kitchen air. The hot gas flows through condenser coils on the back or bottom, releasing heat and condensing to liquid. The liquid passes through an expansion valve, where pressure drops sharply, cooling it well below the freezer temperature. The cold liquid flows through evaporator coils inside the cold compartment, absorbing heat from the air and food and boiling back into gas. The gas returns to the compressor and the cycle repeats. A thermostat cycles the compressor to maintain the set temperature",
        "why": "domestic refrigeration extended food storage, transformed diets, reshaped grocery distribution, and eliminated daily food shopping in industrialized countries. The same vapor-compression cycle scales up to commercial refrigeration, supermarket cases, building HVAC, and air conditioning, accounting for around 17 percent of global electricity demand",
        "vs": "vapor-compression refrigeration differs from absorption refrigeration (used in some RVs and propane fridges), which uses heat rather than mechanical work to drive ammonia or lithium bromide cycles, and from thermoelectric (Peltier) coolers, which use no refrigerant but are less efficient and limited to small loads. Modern fridges differ from older ones in using R-600a (isobutane) or R-134a refrigerants instead of ozone-depleting CFCs",
        "ex": "a typical 18 cubic foot refrigerator with a modern inverter compressor uses about 350 to 500 kWh per year, less than a third of an equivalent unit from the 1980s. Energy Star certification and efficient refrigerants together cut household refrigeration consumption substantially over the past three decades",
        "mis": "people think a refrigerator creates cold. It moves heat outward; the kitchen is slightly warmer because of the work the compressor adds. Another myth is that leaving the door open warms the room; in steady state it warms the room, but the inefficiency mostly heats the kitchen rather than cooling it",
    }

    T["how credit card interest is calculated"] = {
        "_cat": "everyday_life",
        "what": "the daily compounding interest charged on credit-card balances that are not paid in full by the due date, computed by applying the daily periodic rate (APR divided by 365) to the average daily balance and accumulating across the billing cycle",
        "how": "if the APR is 24 percent, the daily rate is roughly 0.0658 percent. The card issuer tracks your balance each day of the billing cycle, averages it, and multiplies by the daily rate times days in the cycle. New purchases accrue interest from posting date if a previous balance was carried; otherwise most cards offer a grace period during which purchases incur no interest as long as the prior month's statement balance is paid in full. Cash advances and balance transfers usually have no grace period and may carry higher rates",
        "why": "understanding the math reveals why minimum payments perpetuate debt. On a 5000 dollar balance at 24 percent APR with a 2 percent minimum payment (100 dollars), it takes over twenty years and roughly 7000 dollars in interest to pay off the debt. Recognizing this lets households prioritize aggressive payoff or 0 percent balance-transfer offers and avoid the long-term cost of revolving balances",
        "vs": "credit card interest differs from installment loan interest in compounding daily and floating freely with the prime rate plus margin. It differs from a mortgage's amortizing schedule, where each fixed payment includes principal and interest. It differs from grace-period purchases, which carry no interest if you pay in full",
        "ex": "carrying a 3000 dollar balance for one month at 22.99 percent APR adds roughly 57 dollars in interest. Paying in full would cost zero; paying just the minimum extends the debt and ratchets up the cumulative cost. The grace period is the single most valuable feature of a credit card if used carefully",
        "mis": "people think paying the minimum keeps the account in good standing without consequence. Good standing is preserved, but interest compounds aggressively. Another myth is that the APR is the actual annual cost; daily compounding makes the effective annual rate slightly higher, especially with cash advances and penalty rates",
    }

    T["how to tell if produce is ripe"] = {
        "_cat": "everyday_life",
        "what": "the practical art of judging ripeness in fruits and vegetables using sensory cues like color, firmness, aroma, weight, and stem condition, since stores often display produce at multiple stages and proper ripeness peaks for only a short window",
        "how": "different items have different cues. Avocados yield to gentle pressure and the skin under the stem nub is yellow-green when ready. Pineapples should smell sweet at the base; a leaf pulled from the crown comes out easily when ripe. Tomatoes give slightly to pressure and have full color extending to the shoulders. Stone fruits (peaches, nectarines, plums) emit fragrance and yield slightly. Melons have a dull (not glossy) rind and feel heavy for their size. Bananas brown gradually; brown spots indicate higher sweetness as starch converts to sugar. Climacteric fruits (bananas, avocados, tomatoes, pears, apples) continue ripening after picking; non-climacteric (berries, citrus, grapes) do not",
        "why": "buying produce at the right ripeness reduces food waste, improves flavor and nutrition, and saves money. Ethylene produced by climacteric fruits can speed ripening of others nearby, which is useful for storage planning. Knowing what ripens off the tree versus what does not (cherries, pineapples, watermelons) prevents misplaced expectations",
        "vs": "ripeness assessment differs across categories: leafy greens are evaluated by crispness and color rather than ripeness, root vegetables by firmness and absence of soft spots, and storage fruits by skin condition and weight. Refrigeration slows ripening for some (berries, peaches near peak) but harms others (tomatoes, bananas) by disrupting flavor compounds and texture",
        "ex": "to ripen rock-hard avocados, place them in a paper bag with a banana for two to three days at room temperature. The ethylene from the banana accelerates the ripening enzymes in the avocado. The same trick works for pears and peaches; wrapping in newspaper has the same effect with less concentrated ethylene exposure",
        "mis": "people think all produce ripens off the plant. Watermelon, pineapple, citrus, cherries, and grapes do not ripen meaningfully after harvest, so picking them at the right moment matters. Another myth is that color alone indicates ripeness; many varieties of apple and pear are ripe at green, and color charts vary by cultivar more than most shoppers realize",
    }

    T["what to do when your car battery dies"] = {
        "_cat": "everyday_life",
        "what": "the standard procedure to revive a car with a dead battery using either a portable jump starter or jumper cables connected to a running donor vehicle, restoring enough power to crank the starter and run the alternator",
        "how": "park a running donor car close to the dead vehicle without bumpers touching. Turn off both ignitions. Connect red (positive) clamp to the dead battery's positive terminal, the other red clamp to the donor's positive terminal. Connect black (negative) to the donor's negative terminal, then the other black clamp to a clean unpainted metal ground on the dead car's engine block (not the battery's negative terminal, to avoid sparks near hydrogen gas). Start the donor, wait a minute, then start the dead car. Once running, disconnect in reverse order. Let the revived car run for at least 20 to 30 minutes to recharge the battery",
        "why": "knowing this procedure prevents being stranded, avoids tow charges, and keeps you from damaging electrical components by reverse-polarity connections. Modern jump starter packs are even more convenient because no donor car is needed, though correct polarity still matters",
        "vs": "jump starting differs from charging (which requires a slow charger connected to wall power for hours), from a battery replacement (which addresses an actually dead battery rather than a discharged one), and from push-starting (which only works on manual transmissions and provides no real benefit on modern fuel-injected cars). It differs from a starter motor problem, which jumping will not fix",
        "ex": "a typical scenario: cabin lights left on overnight drained the battery. Five minutes with jumper cables and a donor car restores ignition. A 30-minute drive replenishes the battery enough for the next start. If the battery is more than four to five years old or repeatedly fails to hold charge, replacement (often a $150 to $250 part) is the actual fix",
        "mis": "people think jump starting damages cars. Done correctly with attention to polarity and order, it is benign. Reverse polarity, however, can blow fuses and damage modules. Another myth is that revving the donor car helps; modern voltage regulators provide adequate current at idle, and revving offers little benefit while increasing risk of physical motion at the connection points",
    }
