#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank: arts and humanities topics (fresh for batch H)."""


def register(T):
    T["the Baroque period in Western art"] = {
        "_cat": "arts_and_humanities",
        "what": "the artistic style flourishing in Europe from roughly 1600 to 1750, characterized by dramatic lighting, dynamic composition, emotional intensity, and ornate detail, originating in Counter-Reformation Italy and spreading across Catholic and Protestant courts",
        "how": "Baroque painting (Caravaggio, Rubens, Velazquez, Rembrandt) used tenebrism, foreshortening, and emotional realism to engage viewers. Architecture (Bernini, Borromini) employed curved facades, illusionistic ceilings, and theatrical staging in churches and palaces. Music (Monteverdi, Bach, Handel) developed opera, the basso continuo, and the concerto. The unifying impulse was movement, emotion, and persuasion through sensory immediacy",
        "why": "Baroque art served religious propaganda for the Catholic Church after the Reformation, glorified absolutist monarchies (Versailles, Schonbrunn), and developed many techniques (oil-painting realism, opera, large-scale architectural illusion) that shaped Western art into the nineteenth century. Its emotional rhetoric still influences cinema and design",
        "vs": "Baroque differs from Renaissance art in its dynamism, asymmetry, and emotional drama versus Renaissance balance and idealization. It differs from Rococo, which extended Baroque ornament into lighter, more playful forms in the eighteenth century. It differs from Mannerism, which preceded it with its strained elegance and artifice",
        "ex": "Caravaggio's 'The Calling of Saint Matthew' (about 1600) uses a single shaft of light cutting across a dim tavern to highlight Matthew's startled gesture as Christ summons him. The painting embodies tenebrism, psychological immediacy, and contemporary clothing on biblical subjects, and it became a model for Baroque storytelling",
        "mis": "people think Baroque means 'overdone' or 'fussy'. The term came to be used pejoratively in later eras but is now neutral. Another myth is that it was uniformly Catholic; Dutch Baroque painters worked for Protestant burghers, producing genre scenes and still lifes alongside the religious art of Catholic Europe",
    }

    T["Greek tragedy"] = {
        "_cat": "arts_and_humanities",
        "what": "a dramatic genre developed in fifth-century BCE Athens in which mythological or heroic protagonists confront ethical and existential dilemmas leading to suffering, recognition, and a downfall that probes communal questions of justice, fate, and human limits",
        "how": "tragedies were performed at festivals (especially the City Dionysia) by competing playwrights, with three actors and a chorus. Plays drew on shared myth (Oedipus, the Atreids, the Trojan War) and combined spoken iambic dialogue with sung choral odes. Aeschylus, Sophocles, and Euripides produced the surviving canon, each handling theological, ethical, and psychological themes differently. Aristotle's Poetics later codified concepts like hamartia, catharsis, and the unities",
        "why": "Greek tragedy founded Western drama, supplied recurring myths and dramatic structures, and established conventions of character, conflict, and chorus that shape theater, opera, and cinema. Its handling of moral conflict in irreducible terms still resonates in fiction, philosophy, and political thought (Hegel on Antigone, Nietzsche on Dionysian and Apollonian)",
        "vs": "Greek tragedy differs from Greek comedy by its serious tone and high-status subjects, from Roman tragedy by being civic and ritual rather than rhetorical and Senecan, and from later Renaissance and modern tragedy by its tighter formal conventions and its inseparable religious-civic context",
        "ex": "Sophocles's 'Oedipus Rex' has Oedipus investigate the plague's cause and uncover that he himself is Laius's killer and Jocasta's son, fulfilling prophecy despite efforts to escape it. The play's structure of progressive revelation has been the textbook example of dramatic irony and recognition since Aristotle",
        "mis": "people think tragedy means a sad ending. Aristotelian tragedy involves a fall from prosperity, but the catharsis it provides is closer to clarification than sadness. Another myth is that the chorus is incidental; it carries communal voice and theological reflection that the actors alone could not",
    }

    T["the development of perspective in Renaissance painting"] = {
        "_cat": "arts_and_humanities",
        "what": "the systematic use of geometric techniques in early-fifteenth-century Italy to project three-dimensional space onto a two-dimensional surface, producing the convincing illusion of depth that has dominated Western painting ever since",
        "how": "Brunelleschi demonstrated linear perspective in Florence around 1413 with experiments using mirrors and architectural views. Alberti codified the method in 'On Painting' (1435), defining the picture plane, vanishing point, and orthogonals converging from edges into the depth. Painters added atmospheric perspective (cooler, hazier distance) and foreshortening of figures. The Renaissance treated perspective as a mathematical and metaphysical achievement linking art to natural philosophy",
        "why": "perspective made painting a powerful tool for representing space, narrative, and architecture, supporting Renaissance interests in naturalism, geometry, and the prestige of the painter as intellectual. It influenced architecture, theatre stage design, and later photography. Its conventions still structure most realist representation",
        "vs": "linear perspective differs from medieval hieratic compositions, where figures were sized by importance rather than spatial position, and from non-Western traditions that used isometric, axial, or floating viewpoints. It differs from cubist and modernist rejections of perspective in the early twentieth century",
        "ex": "Masaccio's 'Holy Trinity' (about 1427) in Santa Maria Novella uses linear perspective to make the painted chapel appear to recede into the wall, with a vanishing point at viewer's eye level. The integration of mathematics and theology in a single fresco was revolutionary",
        "mis": "people think perspective is universal or natural. It is a culturally specific construction; cultures with other conventions saw their own pictures as 'natural'. Another myth is that perspective alone makes paintings realistic; texture, lighting, anatomy, and color all matter as much",
    }

    T["jazz as an American art form"] = {
        "_cat": "arts_and_humanities",
        "what": "a musical tradition that emerged in early-twentieth-century African American communities, especially in New Orleans, blending West African rhythmic complexity, European harmony, blues, and ragtime into improvised, swing-based performance that became a defining American contribution to world music",
        "how": "early jazz combined collective improvisation in dance bands, with cornet/trumpet leads, clarinet counter-lines, and trombone underpinning, over a rhythm section. The 1920s saw soloists like Louis Armstrong reshape the music around individual expression. Swing big bands dominated the 1930s-40s; bebop introduced harmonic complexity and small-group virtuosity in the 1940s; cool, hard bop, modal, and free jazz, and fusion followed. Jazz has always evolved through interaction between players, audiences, and adjacent genres",
        "why": "jazz embodies improvisation as a high art, transformed twentieth-century music globally, integrated into popular and concert traditions, and served as a vehicle of African American creativity through eras of legal segregation. It influenced classical composers (Stravinsky, Ravel), pop, hip-hop, and electronic music, and remains a living tradition with contemporary innovators",
        "vs": "jazz differs from classical Western music in centering improvisation and groove, from blues in its harmonic complexity and instrumental focus, and from rock or pop in its emphasis on individual interpretation over song structure. It differs from West African musical traditions by integrating European harmonic frameworks into rhythmic and improvisational practices",
        "ex": "Louis Armstrong's Hot Five recordings (1925-1928), particularly 'West End Blues', established the trumpet as a solo voice and set conventions of phrasing and rhythmic flexibility that shaped subsequent generations. Armstrong's opening cadenza on that record is often cited as the moment jazz became an art of soloists",
        "mis": "people think jazz means free improvisation without structure. Most jazz is highly structured (chord changes, song forms, ensemble roles); free jazz is one branch among many. Another myth is that jazz peaked in the bebop era; the music continues to evolve, with contemporary players spanning hip-hop influences, world music, and conservatory technique",
    }

    T["the philosophy of utilitarianism"] = {
        "_cat": "arts_and_humanities",
        "what": "an ethical theory that judges actions, rules, or institutions by the aggregate welfare they produce, holding that the morally right choice is the one that maximizes overall happiness or utility, originally articulated by Jeremy Bentham and refined by John Stuart Mill",
        "how": "Bentham proposed a 'felicific calculus' summing pleasures and pains across affected persons. Mill distinguished higher (intellectual) and lower (bodily) pleasures and tied utility to long-run human flourishing. Modern variants distinguish act utilitarianism (each action evaluated separately) from rule utilitarianism (general rules chosen by their utility), and total from average utility. Preference utilitarians substitute satisfaction of preferences for hedonic states",
        "why": "utilitarianism shapes welfare economics, public policy cost-benefit analysis, animal-rights philosophy, and effective altruism. Its emphasis on impartial impacts and measurable outcomes appeals to policymakers but raises hard questions about distribution, rights, and aggregation that drive ongoing debates in moral philosophy",
        "vs": "utilitarianism differs from deontological ethics (Kantian rule-following independent of consequences) in being consequentialist, from virtue ethics in centering acts and outcomes rather than character, and from contractualism in deriving rightness from aggregate utility rather than principles all could accept",
        "ex": "the trolley problem dramatizes utilitarian reasoning: most utilitarians say diverting the trolley to kill one rather than five is required because it maximizes lives saved. Critics counter that pushing one person off a bridge to stop the trolley intuitively differs, exposing tensions the doctrine struggles to resolve",
        "mis": "people think utilitarianism endorses any means to a good end. Mill and contemporary utilitarians argue that rules against killing, lying, and oppression generally maximize utility because exceptions corrode trust. Another myth is that it requires inhuman calculation; many practical defenses appeal to indirect, rule-based reasoning rather than constant computation",
    }

    T["the Romantic movement in literature"] = {
        "_cat": "arts_and_humanities",
        "what": "the literary movement spanning roughly 1780 to 1850, originating in Germany and Britain and spreading across Europe and the Americas, emphasizing imagination, emotion, individual experience, nature, and the sublime in reaction to Enlightenment rationalism and industrialization",
        "how": "early Romantics (Goethe, Schiller, Wordsworth, Coleridge) rejected neoclassical rules in favor of organic form, vernacular language, and the inner life. Second-wave Romantics (Byron, Shelley, Keats, Holderlin) explored alienation, revolutionary politics, and the limits of human striving. Gothic novels, lyric poetry, the historical novel, and the personal essay flourished. Movements in Russia, France, Spain, and the Americas developed national variants",
        "why": "Romanticism shaped modern conceptions of the artist as visionary, of nature as morally and aesthetically meaningful, and of the autonomous self as worthy subject. It influenced nationalism, environmentalism, and psychology, and its motifs (the sublime, the doomed hero, the fragment) recur across later art, film, and music",
        "vs": "Romanticism differs from neoclassicism in privileging emotion over decorum and genius over imitation, from realism in subordinating documentation to imaginative truth, and from modernism in retaining heroic subjectivity rather than fragmenting it. It differs from contemporaneous scientific positivism by its skepticism of rational sufficiency",
        "ex": "Wordsworth and Coleridge's 'Lyrical Ballads' (1798), particularly its preface, manifesto-like declared poetry the spontaneous overflow of powerful feelings recollected in tranquility, written in the language of ordinary speech. The volume launched English Romanticism and reset poetic norms for the nineteenth century",
        "mis": "people think Romanticism is sentimental flowery verse. The major Romantics wrestled with revolution, atheism, and despair as much as natural beauty; the era includes Frankenstein, the Ancient Mariner, and political poetry. Another myth is that it was unified; national variants and individual writers diverged sharply",
    }

    T["the function of myth in human cultures"] = {
        "_cat": "arts_and_humanities",
        "what": "the role that traditional narratives about gods, heroes, origins, and cosmic order play in transmitting values, organizing communities, providing existential meaning, and modeling the world in cultures everywhere across history",
        "how": "myths combine memorable narrative with symbolic figures who embody social roles, natural forces, or moral concepts. They are transmitted orally, ritually, in writing, and in art, and they evolve as communities reinterpret them. Anthropologists and scholars (Frazer, Eliade, Levi-Strauss, Campbell) have proposed structuralist, functionalist, and psychological accounts of why similar themes recur across unrelated cultures",
        "why": "myth provides cultural cohesion, ethical instruction, cosmological orientation, and ritual structure. Even modern secular societies have functional mythologies (national origin stories, founding heroes, scientific cosmologies). Understanding myth helps interpret literature, religion, politics, and the persistence of ritual in industrial life",
        "vs": "myth differs from history by its symbolic and timeless mode, from folktale by its sacred or cosmologically serious status, and from allegory by being lived rather than purely figurative. It differs from scientific cosmology in its purpose: orientation and meaning rather than predictive description",
        "ex": "creation myths around the world (Genesis, the Enuma Elish, Pangu, the Popol Vuh) all describe how a meaningful world emerged from chaos, but with culturally specific casts and ethical implications. The recurrence of certain motifs (separation of sky and earth, struggle with chaos monsters) illustrates both shared human concerns and cultural particularity",
        "mis": "people think myths are simply false stories. They are symbolic narratives whose truth value is not propositional in the scientific sense but communicative and orienting. Another myth is that modernity has dispensed with myth; functional mythologies pervade national identity, market ideology, and even popular science",
    }

    T["the development of the novel"] = {
        "_cat": "arts_and_humanities",
        "what": "the evolution of long prose fiction as a major literary form from late-seventeenth-century origins through eighteenth-century formalization (Defoe, Richardson, Fielding) to its nineteenth-century dominance and twentieth-century experimentation",
        "how": "the novel grew out of romance, chronicle, picaresque, letters, and journalism, distinguished by its sustained focus on individual psychology and contemporary social settings. Key shifts include the epistolary novel, the realist novel of bourgeois life, the historical novel (Scott), modernist interior monologue (Joyce, Woolf), and postmodern self-consciousness. National traditions (Russian, Latin American, Japanese) developed rich variants alongside English-language and continental European forms",
        "why": "the novel became the dominant literary form for representing individual experience and society in industrial modernity, shaped reading habits, and democratized literary culture through cheap print. It influenced and absorbed cinema, journalism, and now serialized streaming narrative",
        "vs": "the novel differs from epic poetry by its prose form and bourgeois subjects, from short fiction by length and developmental scope, from drama by interiority, and from history or biography by its imaginative freedom. It differs from earlier prose romance by realism and psychological complexity",
        "ex": "Cervantes's 'Don Quixote' (1605, 1615) is widely cited as the first modern novel for its self-aware treatment of fiction, complex protagonist, and sustained engagement with contemporary social reality. Its influence runs through Sterne, Flaubert, and twentieth-century metafiction",
        "mis": "people think the novel is in decline. Sales remain robust, with literary fiction increasingly global, and adjacent serialized forms (TV, web fiction) carry novelistic logic. Another myth is that the novel was always the central literary form; its dominance is recent in literary history's longer span",
    }

    T["the philosophy of Stoicism"] = {
        "_cat": "arts_and_humanities",
        "what": "a Hellenistic philosophical school founded by Zeno of Citium around 300 BCE that taught that virtue (consisting of practical wisdom, justice, courage, and temperance) is the only true good and that one should accept what is outside one's control while acting rightly within it",
        "how": "Stoicism distinguished between things 'up to us' (judgments, intentions, actions) and things 'not up to us' (health, wealth, reputation, others' choices). It taught practical exercises like negative visualization, daily reflection, and reframing impressions to align desire with virtue. Major figures include Cleanthes, Chrysippus, Seneca, Epictetus, and Marcus Aurelius. The system integrates physics (a rational world soul), logic, and ethics",
        "why": "Stoicism shaped Roman moral thought, influenced Christianity (especially through cardinal virtues and providence), and informed Enlightenment ethics and modern cognitive behavioral therapy (Beck and Ellis explicitly drew from Epictetus). A renewed popular interest since the 2000s has produced large audiences for Stoic-inspired self-help and ethical practice",
        "vs": "Stoicism differs from Epicureanism in valuing virtue over pleasure absence of pain, from skepticism in affirming knowable truths, from Christian ethics in lacking divine commands and grace, and from utilitarianism in prioritizing virtue over outcomes. It differs from Buddhist non-attachment by retaining engaged civic action",
        "ex": "Marcus Aurelius's 'Meditations', written as private exercises while emperor, repeatedly reminds him that anger, anxiety, and grief over events outside his control betray the Stoic discipline of focusing on his own judgments and virtues. The text became a foundational primary source of practical Stoic psychology",
        "mis": "people think Stoicism means suppressing emotion and being emotionless. Stoics distinguished destructive passions (pathē) from healthy emotions (eupatheiai); the goal is right relation to feelings, not suppression. Another myth is that Stoicism is passive resignation; it demands active virtuous engagement, accepting only that outcomes are not entirely in one's hands",
    }

    T["impressionist music"] = {
        "_cat": "arts_and_humanities",
        "what": "a style of late-nineteenth and early-twentieth-century European music, especially associated with Debussy and Ravel, that emphasizes mood, color, and atmosphere over traditional harmonic progression and developmental structures",
        "how": "impressionist composers used non-functional harmonies (whole-tone scales, modal scales, parallel chord motion), subtle orchestration with prominent harp, flute, and muted strings, and forms that prioritize texture and mood over development. They drew inspiration from symbolist poetry, visual art, and non-Western music (especially Javanese gamelan heard at the 1889 Paris Exposition). Tonal centers float and dissolve rather than resolve",
        "why": "impressionism transformed Western harmony, opening paths to twentieth-century modernism, jazz harmony, and film scoring. Its color-first orientation broadened what music could express and reshaped orchestration practice. It has shaped popular music too, audible in Bill Evans, Steely Dan, and contemporary scoring",
        "vs": "impressionist music differs from Romantic music by suppressing dramatic narrative and emphasizing static color, from contemporary expressionism (Schoenberg) by remaining tonal-adjacent rather than atonal, and from earlier French traditions by its focus on suggestion over explicit form. It differs from neoclassicism, which followed it as a reaction",
        "ex": "Debussy's 'Prelude to the Afternoon of a Faun' (1894) opens with a flute solo on a chromatic descent that establishes a dreamlike mood; the orchestration unfolds through shifting harmonic colors rather than thematic development, and the ending returns rather than concludes. The piece is often cited as a decisive break from Wagnerian tonal practice",
        "mis": "people think 'impressionism' was a label the composers embraced. Debussy disliked the term, borrowed from painting. Another myth is that impressionism is shapeless; the works have careful formal logic, just operating through color and gesture rather than thematic statement and resolution",
    }

    T["postmodern philosophy"] = {
        "_cat": "arts_and_humanities",
        "what": "a constellation of late-twentieth-century philosophical positions skeptical of universal narratives, fixed meanings, and foundational claims, especially associated with French thinkers (Foucault, Derrida, Lyotard, Deleuze) and their influence in literary theory, anthropology, and political theory",
        "how": "postmodern thought analyzes how knowledge, identity, and power are constructed through language, institutions, and historical contingency. Foucault traced how discourses constitute their subjects (madness, sexuality, criminality). Derrida's deconstruction probes texts for the binary oppositions and excluded terms that structure them. Lyotard's 'incredulity toward metanarratives' rejects grand stories of progress, reason, or emancipation. Methods are typically genealogical, textual, and rhetorical rather than systematic",
        "why": "postmodernism reshaped humanities scholarship from the 1970s through the 2000s, influenced legal theory, queer and gender studies, postcolonial studies, and architecture. Its critics (analytic philosophers, scientific realists, and many leftists) charge it with relativism, obscurantism, or political quietism, and the term has become a polemical target across the political spectrum",
        "vs": "postmodernism differs from modernism in rejecting heroic experimentation in favor of pastiche and skepticism about progress, from analytic philosophy in style and method, and from older skepticisms by its institutional and discursive focus rather than purely epistemological one. It differs from poststructuralism, with which it overlaps but is not identical",
        "ex": "Foucault's 'Discipline and Punish' (1975) traces how the modern prison emerged from a broader shift in techniques of power that produce docile, observable subjects through schools, hospitals, factories, and barracks. The concept of disciplinary power has been adopted across social sciences and policy critique",
        "mis": "people think postmodernism denies all truth. Most postmodern thinkers reject local, contextual claims about knowledge being shaped by discourses, not all truth indiscriminately. Another myth is that the field is unified; Foucault, Derrida, and Lyotard differ on much, and many associated thinkers reject the label",
    }

    T["the haiku tradition in Japan"] = {
        "_cat": "arts_and_humanities",
        "what": "a Japanese poetic form of three lines totaling seventeen morae (commonly approximated as 5-7-5 syllables in English) that traditionally evokes a moment, a season, and a juxtaposition or shift, descended from the opening verse of the longer linked-poetry form renga",
        "how": "the form uses a kigo (seasonal word) to anchor the moment in a particular time of year and a kireji (cutting word) to mark a shift between two images. Bashō (1644-1694) elevated haiku from courtly amusement to a serious poetic vehicle, exploring transience, nature, and inner experience. Buson and Issa each developed distinctive voices; Shiki modernized the form in the late nineteenth century, giving it the name haiku and the realist orientation of contemporary practice",
        "why": "haiku influenced twentieth-century world poetry (the Imagist movement, especially Pound), shaped Western perceptions of Japanese aesthetics, and became one of the most widely written and translated poetic forms globally. It distills attention to immediate experience and continues to evolve in Japanese, English, Spanish, and many other languages",
        "vs": "haiku differs from senryu in tone (haiku contemplates nature and the seasons; senryu is humorous and human-focused). It differs from tanka by its shorter length and from English-language imagism by its kigo and kireji conventions. It differs from Western miniature poetry traditions in its specific form and seasonal coding",
        "ex": "Basho's frog poem ('an old pond / a frog jumps in / sound of water') in seventeen Japanese morae captures a moment of stillness broken by sudden sound, with the season implicit. Hundreds of translations exist, each highlighting different facets of the original's compression and resonance",
        "mis": "people think haiku is just any 5-7-5 syllable poem. Traditional Japanese haiku counts morae (sound units), not English syllables, and includes kigo and kireji conventions. English haiku has its own conventions and need not strictly adhere to 5-7-5 to be recognized as haiku",
    }
