#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank part 3: tech, everyday_life, current_events."""


def register(T):
    # ===== TECH =====

    T["DNS resolution"] = {
        "_cat": "tech",
        "what": "the process of translating a human-readable domain name like example.com into the numerical IP address (e.g., 93.184.216.34) that computers use to route traffic. The Domain Name System is a hierarchical, distributed database queried by clients via UDP and TCP on port 53",
        "how": "a client asks its configured resolver. The resolver checks its cache; on miss it queries a root server, which directs to the .com TLD server, which directs to the authoritative server for example.com, which returns the A or AAAA record. The resolver caches the answer with a TTL and returns it. Modern resolvers also use DNSSEC for cryptographic verification and DoH/DoT for transport encryption",
        "why": "DNS is the internet's address book. Without it, users would memorize IPs that change frequently. DNS also enables load balancing (rotating multiple addresses), traffic steering (geographic routing), CDN selection, and email routing (MX records). Outages of major DNS providers like the 2016 Dyn attack make large swaths of the web unreachable",
        "vs": "DNS differs from a phone book by being decentralized, hierarchical, and dynamic. It differs from URL parsing (a client-side string operation) by requiring network queries and caching. Compared to ARP, which resolves IPs to MAC addresses on a local network, DNS resolves names to IPs across the global internet",
        "ex": "typing google.com into a browser triggers a chain: OS resolver checks cache, then asks the configured resolver (often the ISP's or 1.1.1.1 or 8.8.8.8). The resolver, on miss, walks the hierarchy: root . to com. to google.com. The authoritative answer with TTL of perhaps 300 seconds is cached and returned. The whole chain typically completes in 20-100 ms",
        "mis": "people think DNS just maps names to IPs once; resolvers cache aggressively, and TTLs determine how stale cached answers can be. Another myth is that DNS queries are confidential by default; classic DNS over UDP is unencrypted, observable by ISPs and any on-path attacker. DoH and DoT mitigate this but are not yet universal",
    }

    T["TLS handshake"] = {
        "_cat": "tech",
        "what": "the cryptographic negotiation at the start of a TLS connection that authenticates the server (and optionally the client), agrees on cipher suites, and establishes shared session keys. TLS 1.3 (2018) reduced the handshake to one round trip and removed many legacy options",
        "how": "in TLS 1.3, the client sends a ClientHello with supported cipher suites, key shares for ephemeral key exchange (X25519 or P-256), and extensions. The server responds with ServerHello selecting parameters, its certificate chain, a CertificateVerify signature, and Finished. The client verifies the certificate against its trust store, computes the shared key via Diffie-Hellman, and sends Finished. Application data flows under the negotiated keys",
        "why": "TLS underpins HTTPS, securing web browsing, email, and most modern application protocols. The handshake provides three guarantees: confidentiality (no eavesdropping), integrity (no tampering), and authentication of the server identity. Without it, modern e-commerce, banking, and password authentication on the open internet would be untenable",
        "vs": "TLS 1.3 differs from TLS 1.2 by combining many handshake steps, mandating forward-secret key exchange, and dropping outdated ciphers (RC4, CBC mode without HMAC, RSA key transport). TLS differs from IPsec (operates at the network layer) and SSH (similar layer but different protocol with separate session model and key infrastructure)",
        "ex": "when you visit https://example.com, your browser performs a TLS 1.3 handshake in about one round trip. After ClientHello and ServerHello plus certificate verification, both sides compute the same session keys via X25519 ephemeral Diffie-Hellman, then encrypt all subsequent HTTP/2 traffic. Total handshake adds maybe 30-100 ms over a TCP connection",
        "mis": "people think TLS only encrypts and forget the authentication piece; without certificate verification, encryption alone is vulnerable to active attackers. Another myth is that older TLS versions are still safe in practice; TLS 1.0 and 1.1 are deprecated and disabled in major browsers due to known weaknesses",
    }

    T["WebSockets vs Server-Sent Events"] = {
        "_cat": "tech",
        "what": "two complementary technologies for delivering server-pushed data to web clients beyond traditional HTTP request-response. WebSockets provide full-duplex bidirectional communication over a single TCP connection; Server-Sent Events (SSE) provide unidirectional server-to-client streaming over HTTP",
        "how": "WebSockets start with an HTTP upgrade request to switch protocols; once accepted, both sides exchange framed messages in either direction at any time. SSE is a long-lived HTTP response delivering text/event-stream data with named events and IDs, with the browser's EventSource API auto-reconnecting on drops. Both rely on persistent connections and avoid HTTP's per-request overhead",
        "why": "real-time features (chat, multiplayer games, collaborative editing, live dashboards, notifications) need server-initiated updates. Polling is wasteful; long-polling is fragile. WebSockets and SSE provide low-latency push without these costs. Together they enable the live web: Slack, Google Docs, financial tickers, and live sports updates",
        "vs": "WebSockets are bidirectional and binary-capable; SSE is server-to-client only and text-only. WebSockets need explicit reconnection logic; SSE handles it automatically. WebSockets traverse some firewalls poorly; SSE rides on standard HTTP and is easier to proxy. WebSockets need more careful framing of message types; SSE has a built-in named event format. Use WebSockets for chat and games, SSE for one-way feeds",
        "ex": "a stock ticker site can use SSE: the server pushes a price update every few seconds with named events, and the EventSource client renders them. A multiplayer game uses WebSockets: clients send player movements and the server broadcasts world state to all participants in real time, with bidirectional traffic flowing freely",
        "mis": "people use WebSockets for everything when SSE would suffice; for one-way streaming, SSE is simpler and more robust. Another myth is that WebSockets always provide low latency; they reduce per-message overhead but do not eliminate network and server delays. A third confusion is that WebSockets bypass HTTP entirely; they upgrade from HTTP and inherit much of its infrastructure",
    }

    T["public-key cryptography"] = {
        "_cat": "tech",
        "what": "a cryptographic system using pairs of mathematically related keys: a public key freely shared and a private key kept secret. Operations done with one key can be reversed only with the other, enabling encryption to a recipient's public key (only they can decrypt) and digital signatures with the sender's private key (anyone can verify)",
        "how": "RSA bases security on the difficulty of factoring large semiprimes; elliptic curve cryptography (ECC) uses point arithmetic on curves like Curve25519 or P-256 and offers comparable security with much smaller keys. Key generation produces a (public, private) pair from a hard problem in number theory. Encryption and signature schemes (RSA-OAEP, ECDSA, Ed25519) build on these primitives. Hybrid encryption uses public-key crypto to deliver a symmetric session key for bulk data",
        "why": "public-key crypto solves the key distribution problem: you can encrypt to someone you have never met, and you can prove a message comes from a specific party. Without it, modern HTTPS, signed software updates, code signing, encrypted messaging (Signal, WhatsApp), and digital signatures on financial transactions would not exist. It is the trust infrastructure of the digital economy",
        "vs": "public-key crypto differs from symmetric cryptography (AES, ChaCha20), which uses one shared key and is much faster but requires secure prior key sharing. It differs from hash functions, which provide integrity without secrets. Compared to post-quantum cryptography, classical public-key schemes (RSA, ECC) are vulnerable to large quantum computers running Shor's algorithm, motivating the migration to lattice-based and other quantum-resistant schemes",
        "ex": "when you visit an HTTPS site, the server presents a certificate containing its public key signed by a Certificate Authority. Your browser verifies the signature chain, then performs an Elliptic Curve Diffie-Hellman key exchange using ephemeral keys. The result is a shared symmetric key for the session, all bootstrapped from the server's public-key cryptography",
        "mis": "people think public-key encryption secures bulk data; it is too slow, so real systems use it to deliver a symmetric session key. Another myth is that bigger keys are linearly more secure; security grows logarithmically, and ECC achieves with 256 bits what RSA needs 3072 bits to match. A third confusion is that signing and encryption are the same operation reversed; modern schemes use distinct algorithms tuned to each purpose",
    }

    T["JWT tokens and their pitfalls"] = {
        "_cat": "tech",
        "what": "JSON Web Tokens (JWTs) are a compact, URL-safe means of representing claims to be transferred between two parties. A JWT consists of three Base64URL-encoded parts: a header specifying algorithm and type, a payload containing claims, and a signature over the first two parts. They are widely used for authentication and authorization in stateless web applications",
        "how": "a server signs a JWT with a secret (HMAC) or private key (RSA, EC) embedding user identity and expiration. The client stores it (often in a cookie or local storage) and presents it on subsequent requests. The server verifies the signature without database lookups, trusting embedded claims. Claims include iss (issuer), sub (subject), exp (expiration), and custom data",
        "why": "JWTs eliminate server-side session storage, simplifying horizontal scaling and microservice authentication. They are the de facto standard for OAuth 2.0 ID tokens (OpenID Connect) and API authentication. The compact format works in headers, cookies, and URL parameters across HTTP-based services",
        "vs": "JWTs differ from session tokens (random opaque strings indexed in a server-side store) by carrying their state in the token itself. They differ from API keys by having structured claims and expiration. Compared to PASETO (a more opinionated successor), JWTs are flexible to the point of footguns; PASETO restricts choices to safer defaults",
        "ex": "a login flow returns a JWT with sub=user_id, exp=now+1h, and roles=[admin]. The client sends Authorization: Bearer <jwt> on each request. The API verifies the HMAC signature, checks expiration, extracts roles, and authorizes the action. No database lookup needed, but no easy revocation either",
        "mis": "people think JWTs are encrypted; the standard JWT is signed but readable by anyone (use JWE for encryption). The infamous none algorithm vulnerability let attackers strip signatures by setting alg: none, accepted by naive verifiers. Another myth is that JWT enables instant revocation; without server-side checks, valid signed tokens remain accepted until expiration. Use short expirations and refresh tokens, or hybrid sessions with revocation lists",
    }

    T["zero-trust architecture"] = {
        "_cat": "tech",
        "what": "a security model that assumes no implicit trust based on network location. Every access request is authenticated, authorized, and continuously validated regardless of whether it originates inside or outside the organizational perimeter. The principle is never trust, always verify",
        "how": "implementation requires strong identity (multi-factor authentication, device attestation), microsegmentation of network services, least-privilege access policies enforced at every request, continuous monitoring for anomalies, and encrypted communication everywhere. Tools include identity providers (Okta, Azure AD), policy engines, software-defined perimeters, and behavioral analytics. Google's BeyondCorp is the canonical large-scale implementation",
        "why": "the traditional perimeter model (hard outside, soft inside) fails against insiders, lateral movement after breach, and remote/cloud workloads. High-profile breaches (Target, OPM, SolarWinds) all involved attackers gaining a foothold and moving laterally. Zero-trust eliminates the assumption that internal traffic is safe, which is essential for modern hybrid-cloud environments and remote workforces",
        "vs": "zero-trust differs from perimeter security (firewalls and VPNs) by removing the trusted-internal-network concept entirely. It differs from defense-in-depth by being a positive architectural principle, not just layered controls. Compared to ad hoc remote-access solutions, it provides consistent policy regardless of user location",
        "ex": "Google's BeyondCorp removes employee VPN dependence: every access to internal apps, from anywhere, requires user authentication with MFA, device certificate verification, and policy evaluation based on user role, device posture, and resource sensitivity. An employee on a laptop with patched OS gets access; the same employee on a jailbroken phone might be denied",
        "mis": "people think zero-trust is a product you can buy; it is an architectural principle implemented through many integrated components over time. Another myth is that it eliminates breaches; it limits blast radius after a compromise rather than preventing all initial intrusions. A third confusion is that VPNs are zero-trust; classic VPNs grant broad network access after authentication, the opposite of zero-trust principles",
    }

    T["GraphQL vs REST"] = {
        "_cat": "tech",
        "what": "two API design paradigms. REST exposes resources as URLs with HTTP verbs (GET, POST, PUT, DELETE) and standard status codes. GraphQL exposes a single endpoint accepting queries that specify exactly what data the client needs, typed via a schema, with one POST per query batch",
        "how": "REST APIs return fixed JSON shapes per endpoint; clients fetch what's there. GraphQL clients send queries describing the desired data shape; the server resolves each field. GraphQL schemas are statically typed, enabling tooling for autocomplete, introspection, and codegen. REST relies on documentation (OpenAPI/Swagger) for the same",
        "why": "GraphQL solves real REST pain points: over-fetching (getting data you don't need), under-fetching (multiple calls to assemble a view), and versioning fragility. Mobile apps especially benefit from a single tailored query. REST remains simpler for resource-CRUD APIs, easier to cache, and more familiar to operations teams. The choice is often pragmatic, not principled",
        "vs": "GraphQL has one endpoint with many possible queries; REST has many endpoints with mostly fixed responses. GraphQL is hard to cache at the HTTP layer (queries vary); REST caches naturally with HTTP semantics. GraphQL nests relationships; REST exposes them as separate resources. GraphQL is great for flexible read-heavy clients; REST excels at simple resource manipulation",
        "ex": "a mobile app showing a user's profile with their last 10 posts and 5 followers might need 3 REST calls (/users/123, /users/123/posts?limit=10, /users/123/followers?limit=5). One GraphQL query expresses the same thing in one round trip and returns exactly the fields used, saving bytes and latency",
        "mis": "people see GraphQL as objectively superior; for simple APIs, REST's HTTP semantics, caching, and tooling maturity often win. Another myth is that GraphQL eliminates over-fetching; on the server, naive resolvers can still trigger N+1 database queries unless DataLoader-style batching is implemented. A third confusion is that GraphQL is incompatible with REST; many systems use both, with GraphQL fronting a REST or microservice backend",
    }

    T["WebAssembly"] = {
        "_cat": "tech",
        "what": "a compact binary instruction format for a stack-based virtual machine designed as a portable compilation target for languages like C, C++, Rust, and Go. WebAssembly (Wasm) runs in browsers at near-native speed and is increasingly used outside browsers for edge computing, serverless, and plugin systems",
        "how": "compilers like Emscripten, Rustc with wasm32 target, and Go's wasm output produce .wasm modules. Browsers and runtimes (Node.js, Wasmtime, Wasmer) instantiate modules in a sandbox with explicit imports/exports. The instruction set is low-level (loads, stores, arithmetic) operating on linear memory; high-level languages compile their semantics down to these primitives. WASI (WebAssembly System Interface) standardizes a portable system call layer",
        "why": "Wasm enables performance-critical code in browsers (Figma, Photoshop on the Web, AutoCAD Web), language-agnostic plugins (Envoy filters, eBPF-like extension points), and portable serverless (Cloudflare Workers, Fastly Compute). It is the closest thing to a universal binary across operating systems and architectures since Java's JVM, with smaller runtime and stronger sandboxing",
        "vs": "Wasm differs from JavaScript by being a compilation target rather than a source language; it complements rather than replaces JS in browsers. It differs from JVM bytecode by simpler structure, tighter sandboxing, and broader language support out of the box. Compared to native code, Wasm sacrifices a bit of performance (5-15%) for portability and safety. Compared to containers, Wasm modules start in microseconds with much smaller footprints",
        "ex": "Figma's design tool runs much of its rendering and constraint-solving in Wasm compiled from C++, achieving desktop-grade performance in a browser tab. Cloudflare Workers run customer code as Wasm modules with cold starts under a millisecond, multi-tenant on shared hardware with kernel-grade isolation between tenants",
        "mis": "people think Wasm replaces JavaScript; in browsers it complements JS, with JS still handling DOM and orchestration. Another myth is that Wasm is browser-only; non-browser runtimes for edge and server use are growing rapidly. A third confusion is that any language compiles cleanly to Wasm; high-overhead runtimes (full Python, Java) require shipping their interpreter or VM, while AOT-compiled languages (Rust, Go, C++) target Wasm naturally",
    }

    T["JIT compilation"] = {
        "_cat": "tech",
        "what": "Just-In-Time compilation translates code to native machine instructions during program execution rather than ahead of time. Modern JITs profile the running program, optimize hot paths aggressively, and patch in optimized code while leaving cold paths interpreted",
        "how": "the runtime starts in interpretation or with a baseline compiler producing low-quality native code quickly. Profilers count function calls, loop iterations, and type observations. When a method becomes hot, an optimizing compiler (Graal, V8's TurboFan, .NET's RyuJIT) generates highly tuned native code, inlining, devirtualizing, and using observed types. Speculative optimizations install guards that, if violated, deoptimize back to less aggressive code",
        "why": "JIT enables dynamic languages (Python via PyPy, JavaScript via V8, Ruby via TruffleRuby, .NET CLR) to approach native-language performance while preserving runtime flexibility. Java's HotSpot, V8 in Chrome and Node.js, and .NET runtimes power vast amounts of modern software. Without JIT, dynamic and managed languages would be 10-100x slower than they are",
        "vs": "JIT differs from ahead-of-time (AOT) compilation, which produces native code before runtime, sacrificing profiling-driven optimization for predictable startup and smaller memory footprint. JIT differs from pure interpretation, which never generates native code. Compared to template JIT (one-pass simple code generation), tiered JIT (V8, HotSpot) interpolates between interpretation, baseline, and optimizing compilers based on hotness",
        "ex": "in V8, JavaScript code runs first in the Ignition interpreter while collecting type feedback. Hot functions move to TurboFan, which uses observed types to compile specialized native code: a function adding two numbers gets specialized to integer addition. If a non-integer arrives later, V8 deoptimizes and falls back, a trade-off that wins on average for typical JS programs",
        "mis": "people think JIT always wins on performance; for short-lived programs (CLI tools, scripts), JIT compilation overhead exceeds the benefits. AOT or interpretation may be faster end-to-end. Another myth is that JIT eliminates startup cost; modern systems mix interpreter, baseline, and optimizing tiers precisely because top-tier JIT is expensive. A third confusion is that JITs break security; modern JITs use techniques like W^X (writable XOR executable memory) to mitigate code injection",
    }

    T["cache hierarchies (L1, L2, L3)"] = {
        "_cat": "tech",
        "what": "the multi-level memory hierarchy on modern CPUs that bridges the speed gap between fast registers and slow main memory. L1 cache is small (32-128 KB per core) and fastest (3-5 cycle access). L2 is larger (256 KB-1 MB per core) and slower. L3 is largest (4-128 MB shared across cores) and slowest among caches but still much faster than DRAM",
        "how": "the CPU checks L1 first; on miss it checks L2, then L3, then main memory. Each level holds copies of recently or predictably used cache lines (typically 64 bytes). Inclusive policies (L3 contains everything in L1 and L2) simplify coherence; exclusive policies maximize total capacity. Cache coherence protocols (MESI, MOESI) keep multi-core caches consistent. Prefetchers predict and load data before it is requested",
        "why": "main memory access is roughly 100ns, while L1 is 1ns. Without caches, every memory access would block computation for hundreds of cycles. The hierarchy exploits temporal and spatial locality: recently-used and adjacent data are likely to be reused. A program with good cache behavior can run 10-100x faster than the same logic with cache-unfriendly access patterns",
        "vs": "L1 is split into instruction (L1i) and data (L1d) caches; L2 and L3 are unified. L1 is core-private; L3 is shared. Compared to TLBs (caches for virtual-to-physical address translation), data caches hold actual data, not address mappings. Compared to disk caches (page cache in OS, SSD DRAM cache), CPU caches operate at much smaller scales but vastly higher speeds",
        "ex": "iterating over a 2D array in C row-major order (the language default) hits cache lines sequentially; column-major iteration jumps across rows, missing cache repeatedly. The performance difference can be 10x for large arrays. Algorithm designers optimize for cache by tiling, blocking, and choosing data layouts that maximize sequential access",
        "mis": "people think more cores mean linearly faster code; if working sets don't fit in cache, more cores contend for memory bandwidth and gain little. Another myth is that L3 is just a bigger L1; access latency, associativity, and cost differ markedly. A third confusion is that caches are software-controlled; on x86 and ARM, they are largely transparent, with limited prefetch and flush instructions for fine-tuning",
    }

    T["row-store vs column-store databases"] = {
        "_cat": "tech",
        "what": "two physical layouts for storing relational tables. Row-store databases (Postgres, MySQL, Oracle) store all columns of a row contiguously, optimal for OLTP workloads that read or write whole rows. Column-store databases (Redshift, BigQuery, ClickHouse, DuckDB) store each column contiguously, optimal for OLAP analytic queries reading few columns over many rows",
        "how": "row-store reads pull entire rows from disk into memory, useful when a query needs most columns of a few rows. Column-store reads pull only requested columns, dramatically reducing IO for analytic queries scanning millions of rows but using just a few columns. Column stores compress better (similar values cluster) and vectorize SIMD-friendly aggregations across long arrays of one type",
        "why": "the right layout can change query performance by orders of magnitude. Analytic queries (SUM, AVG, GROUP BY) on billion-row tables can run in seconds on a column store and minutes on a row store. Conversely, OLTP workloads with small writes and full-row reads run efficiently on row stores and clumsily on column stores. Modern data warehouses use column stores almost universally",
        "vs": "row-store wins for OLTP: small reads/writes, full-row queries, high concurrency, easy ACID transactions. Column-store wins for OLAP: aggregations, analytic scans, columnar compression, SIMD vectorization. Hybrid systems (HTAP databases like SAP HANA, TiDB) try to bridge both. Compared to NoSQL, both are relational; the row/column distinction is independent of the relational/non-relational axis",
        "ex": "a query SELECT AVG(salary) FROM employees on a billion-row table reads only the salary column from a column store, scanning maybe 4-8 GB instead of 100+ GB. The same query with row-store reads every row entirely, hitting cold disk and DRAM extensively. ClickHouse can answer such queries in seconds; Postgres might take minutes",
        "mis": "people think column stores are universally faster; for OLTP workloads with row-level updates and small queries, they are typically slower than row stores. Another myth is that columnar storage means NoSQL; ClickHouse, Redshift, and BigQuery are SQL-compliant relational systems with columnar physical storage. A third confusion is that the choice is binary; many systems use hybrid layouts (Postgres with cstore_fdw, MySQL with column-store extensions)",
    }

    T["eventual consistency"] = {
        "_cat": "tech",
        "what": "a consistency model in distributed systems where, given no new updates, all replicas eventually converge to the same value. It contrasts with strong consistency, where every read sees the latest write immediately. Eventual consistency trades immediate read-after-write guarantees for higher availability and lower latency",
        "how": "writes propagate asynchronously across replicas via gossip, anti-entropy, or read-repair. Conflicts are resolved by last-write-wins (timestamp-based), CRDTs (data structures designed to merge automatically), or vector clocks identifying causality. Quorum-based systems (Cassandra, Riak) tune R+W > N to provide stronger consistency on demand within an eventually consistent base",
        "why": "in geographically distributed systems, requiring strong consistency means waiting for all replicas (or a majority) to acknowledge each write, adding round-trip latency over wide-area networks. Eventual consistency allows local writes that propagate in the background, supporting always-on user experiences (DNS, DynamoDB, S3, social-media feeds) where stale reads are acceptable for a brief window",
        "vs": "eventual consistency contrasts with strong (linearizable) consistency, which provides total order and immediate visibility but requires synchronization. It contrasts with causal consistency, which preserves cause-effect ordering across replicas but allows independent updates to reorder. Compared to read-your-writes session consistency, eventual is weaker; you might not even see your own previous write",
        "ex": "DNS is famously eventually consistent: when a domain's IP changes, the new value propagates over hours as TTLs expire on cached records. During propagation, different users may see different IPs, all valid. The system trades immediate global visibility for massive scale and resilience. Amazon S3's read-after-write was eventually consistent for years before becoming strong in 2020",
        "mis": "people see eventual consistency as broken; it is a deliberate engineering trade-off. Another myth is that all NoSQL is eventually consistent; many (Spanner, CockroachDB, MongoDB with majority writes) provide strong consistency. A third confusion is that eventually means reasonable time; without bounds, eventual could be months. Practical systems offer SLAs on convergence time",
    }

    # ===== EVERYDAY LIFE =====

    T["the time value of money"] = {
        "_cat": "everyday_life",
        "what": "the financial principle that a sum of money is worth more today than the same sum in the future, because money today can be invested to earn returns. The concept underlies present value, future value, discount rates, and virtually all financial decisions involving cash flows over time",
        "how": "to compare cash flows at different times, you discount future amounts to their present value using a discount rate reflecting risk and opportunity cost: PV = FV / (1+r)^n. Conversely, you compound present amounts to future values: FV = PV * (1+r)^n. The discount rate is typically the return you could earn on a similar-risk alternative",
        "why": "the principle drives capital budgeting (NPV analysis), bond pricing, mortgage calculations, retirement planning, and lottery payout decisions (lump sum vs annuity). Without it, decisions about long-term projects, leases, and loans cannot be made rationally. Every CFA, MBA, and finance textbook starts here because nothing else makes sense without it",
        "vs": "time value differs from inflation; even with zero inflation, money today is worth more because it can earn returns. It differs from nominal vs real interest rates: time value applies even when both are equal. Compared to behavioral discounting (which is often hyperbolic), the financial principle uses exponential discounting consistently",
        "ex": "a lottery offers $1 million now or $50,000 per year for 30 years (total $1.5M). At a 5% discount rate, the annuity's present value is about $769,000, less than the lump sum. Most rational analysis prefers the lump sum, though risk preferences, taxation, and self-control concerns may justify the annuity for some people",
        "mis": "people compare cash flows at different times directly without discounting, overestimating the value of long-term promises. Another myth is that the discount rate equals inflation; the right rate captures opportunity cost, which usually exceeds inflation. A third confusion is that time value applies only to investments; it applies equally to debts, insurance payouts, and any decision involving timing of money",
    }

    T["index funds vs active management"] = {
        "_cat": "everyday_life",
        "what": "two approaches to investing in financial markets. Index funds passively track a market benchmark (S&P 500, total stock market, MSCI World) by holding the constituent securities in proportion. Active management tries to beat the benchmark through stock picking, market timing, or sector rotation, charging higher fees for the attempt",
        "how": "index funds rebalance occasionally to match index changes, with expense ratios typically 0.03-0.20% and minimal turnover. Active funds employ analysts, run proprietary models, and trade aggressively, charging 0.5-2% in fees and triggering taxable events. The investor pays for skill if it exists; the question is whether skill exists net of fees",
        "why": "decades of academic research (starting with Sharpe, Fama, French) and practitioner data (S&P SPIVA, Morningstar) consistently show that 70-90% of active funds underperform their benchmark over 10+ years after fees. Bogle's 1976 founding of Vanguard popularized indexing; today it dominates flows and assets. The choice has trillions of dollars at stake annually",
        "vs": "index funds offer lower fees, broad diversification, tax efficiency, and predictable benchmark-tracking returns. Active funds offer the chance (rarely realized) to outperform, downside protection through tactical shifts (also rarely realized), and access to specific themes. Index funds are usually right for most investors most of the time; active management is justified only with strong evidence of skill specific to that manager and asset class",
        "ex": "$10,000 invested in 1990 in an S&P 500 index fund grew to about $200,000 by 2020 with dividends reinvested, at a 0.04% expense ratio. The same amount in the average actively managed equity fund grew to about $150,000-180,000 after fees. Over 30 years, the gap from compounding small fee differences becomes life-changing, illustrating Bogle's costs matter principle",
        "mis": "people think active management protects against bear markets; data show active funds usually fall as much or more than indexes during downturns, with worse recovery. Another myth is that index funds are riskless; they hold the full market exposure with no tactical defense. A third confusion is that active managers occasionally beat indexes (true) means they will continue to (rarely true); past outperformance does not predict future outperformance reliably",
    }

    T["dollar-cost averaging"] = {
        "_cat": "everyday_life",
        "what": "an investment strategy of buying a fixed dollar amount of an asset at regular intervals regardless of price. Over time, you buy more shares when prices are low and fewer when high, smoothing the average cost basis and reducing the impact of market volatility on a single entry point",
        "how": "decide an amount (e.g., $500/month) and a frequency (monthly, biweekly). Set automatic transfers from bank to broker, with the broker placing buy orders at market on the chosen date. Continue mechanically through bull and bear markets. Over decades, the strategy aggregates a position at a price near the average market level over the buying period",
        "why": "DCA solves three real problems: behavioral (lump-sum investing requires conviction at market peaks, scary), practical (you usually have new income flowing in, not a windfall), and risk-management (avoids catastrophic timing of putting it all in at a peak). It is the de facto strategy for 401(k) participants, automatic IRA contributions, and millions of small investors",
        "vs": "DCA differs from lump-sum investing, which puts all available capital in immediately. Studies show lump sum beats DCA about 65-70% of the time on average because markets rise more often than fall, but the variance is wider. DCA is smoother and behaviorally easier. It differs from value averaging, which adjusts contributions based on portfolio value to hit specific growth targets, more complex and rarely used by retail investors",
        "ex": "an investor contributes $500/month to an S&P 500 fund for 30 years through booms and busts. They buy at $300/share during the 2009 lows and $450 during 2020 highs. Their average cost basis ends up at around $320, well below most peak prices. Compounded over 30 years, the position grows to approximately $700,000-1,000,000 depending on returns",
        "mis": "people think DCA mathematically beats lump-sum; on expected return it does not. Its advantage is behavioral and practical rather than mathematical. Another myth is that you must DCA forever; many investors DCA into accumulation, then hold a long-term portfolio. A third confusion is that DCA protects against losses; over short periods it does little; its real benefit is over multi-decade investment horizons",
    }

    T["compound interest"] = {
        "_cat": "everyday_life",
        "what": "interest calculated on the initial principal plus the accumulated interest from previous periods, so interest itself earns interest. The formula is FV = P*(1+r/n)^(n*t), where P is principal, r is annual rate, n is compounding frequency, and t is years. Continuous compounding gives FV = P*e^(rt)",
        "how": "each period the account balance is multiplied by (1+r/n), so growth is exponential. More frequent compounding (daily vs annual) yields slightly more, with the limit being continuous compounding. The Rule of 72 estimates doubling time as 72/r% (so 6% doubles in 12 years, 8% in 9 years), accurate for moderate rates",
        "why": "compound interest is the engine of long-term wealth: a 22-year-old saving $200/month at 7% annual return has roughly $530,000 by age 65, while a 35-year-old needs $750/month to reach the same goal. It also explains why credit-card debt is so destructive: 20% APR balances double in under 4 years, often outpacing the borrower's repayment capacity",
        "vs": "compound interest differs from simple interest, where each period earns interest only on the original principal (linear growth). For a 30-year horizon at 7%, $10,000 grows to $76,000 with compound interest but only $31,000 with simple interest. Compounding differs from inflation, which works against money over time; real compound returns require nominal returns to exceed inflation",
        "ex": "Albert invests $5,000 at age 25 in a tax-advantaged account at 7% annual return and adds nothing more. By age 65, the account holds about $75,000. Berta invests $5,000 every year from age 35 to 65 at 7%. Despite contributing $150,000 versus Albert's $5,000, Berta ends with about $470,000. Albert's 10-year head start of compounding contributes roughly $75,000 from his single deposit; Berta's later start costs her decades of tail-end exponential growth",
        "mis": "people underestimate compound interest dramatically because exponential growth is non-intuitive; they expect linear growth and are surprised by the long tail. Another myth is that small differences in rate barely matter; over 30+ years, 7% versus 6% produces a 30% larger result. A third confusion is that compounding works only on investments; mortgages, credit-card balances, and student loans all compound, often unfavorably for borrowers",
    }

    T["mortgage amortization"] = {
        "_cat": "everyday_life",
        "what": "the schedule by which a mortgage's monthly payments are split between interest and principal over the loan's term. Early payments are mostly interest because the balance is large; later payments shift toward principal as the balance shrinks. The result is a level monthly payment that fully repays the loan by maturity",
        "how": "for a fixed-rate mortgage, the level monthly payment is computed from principal, interest rate, and term using the present-value-of-annuity formula. Each month, interest is charged on the remaining balance at the period rate, and the difference between the level payment and the interest goes to principal reduction. The amortization schedule lists every payment's split for the loan's life",
        "why": "understanding amortization changes home-buying decisions. In year 1 of a 30-year mortgage at 6%, only about 17% of each payment reduces principal; the rest is interest. Refinancing math, prepayment decisions, and the true cost of mortgage debt all hinge on amortization. Many borrowers who pay extra principal early shave years off the term and save tens of thousands in interest",
        "vs": "amortizing loans differ from interest-only loans (the entire principal remains until a balloon payment) and from negative-amortization loans (where minimum payments don't even cover interest, growing the balance). They differ from credit-card revolving debt, which has minimum payments but no fixed term. Compared to a HELOC, a fixed amortizing mortgage has predictable end-of-term payoff",
        "ex": "a $300,000 30-year fixed mortgage at 7% has a monthly payment of $1,996. Of the first month's payment, $1,750 is interest and $246 is principal. By month 360, $11.65 is interest and $1,984 is principal. Total interest paid over 30 years is about $419,000, more than the original loan amount, illustrating the cost of long-term mortgage debt",
        "mis": "people think their first few mortgage payments build equity meaningfully; in fact, in the first 5-10 years of a 30-year loan, you are paying mostly interest. Another myth is that paying extra is always smart; if your mortgage rate is below your alternative investment returns, math may favor investing. A third confusion is that biweekly payments are magic; they amount to one extra monthly payment per year, equivalent to simply paying 1/12 extra each month",
    }

    T["sleep cycles and REM"] = {
        "_cat": "everyday_life",
        "what": "the recurring pattern of sleep stages that the brain progresses through during a typical night. Each cycle (90-110 minutes) includes light sleep (N1, N2), deep slow-wave sleep (N3), and REM (rapid eye movement) sleep. Adults typically experience 4-6 cycles per night with shifting proportions",
        "how": "after falling asleep, the brain descends through N1 (transitional, minutes), N2 (sleep spindles and K-complexes, most of total sleep), and N3 (delta waves, deep sleep). N3 dominates early cycles; REM dominates later cycles, with the longest REM bout typically before waking. Brainstem and hypothalamic circuits regulate the cycling via adenosine accumulation, melatonin signaling, and GABA inhibition",
        "why": "different stages serve different functions. N3 is associated with physical recovery, growth-hormone release, and immune support. REM is associated with memory consolidation, especially procedural and emotional memory, and dream generation. Disrupting cycles by inadequate or fragmented sleep degrades cognition, mood, immune function, and metabolic regulation. Chronic sleep loss correlates with cardiovascular disease, diabetes, and depression",
        "vs": "REM sleep differs from non-REM by paradoxical brain activation (high-frequency EEG resembling waking) combined with muscle atonia preventing dream enactment. N3 differs from REM by slow large-amplitude EEG and minimal eye movement. Compared to wakefulness, all sleep stages reduce conscious awareness, but the brain remains highly active throughout, especially in REM",
        "ex": "an adult who sleeps 7-8 hours typically experiences 4-5 full cycles. Early cycles include 30-40 minutes of N3; later cycles cut N3 to minutes and stretch REM to 30+ minutes. Waking after 6 hours cuts off most REM sleep, leaving you with the deep-sleep portion but missing memory consolidation and emotional regulation associated with later REM. This is partly why short sleep correlates with mood disturbance and learning impairment",
        "mis": "people think REM is when most dreaming happens; vivid dreams occur in REM, but recall and dream-like content also occur in N2 and N3. Another myth is that you need exactly 8 hours; healthy adult needs vary from 6 to 9 hours, with quality (uninterrupted cycles) often more important than total time. A third confusion is that aging requires less sleep; older adults need similar amounts but their sleep architecture shifts toward earlier wakings and reduced N3",
    }

    T["aerobic vs anaerobic exercise"] = {
        "_cat": "everyday_life",
        "what": "two energy systems used during physical activity. Aerobic exercise (running, cycling, swimming at sustainable pace) uses oxygen to oxidize carbohydrates and fats, sustaining moderate effort for extended periods. Anaerobic exercise (sprinting, heavy lifting, HIIT) operates above sustainable oxygen delivery, relying on phosphocreatine and glycolysis with lactate accumulation",
        "how": "aerobic metabolism produces ATP through oxidative phosphorylation in mitochondria, yielding ~36 ATP per glucose molecule slowly but efficiently. Anaerobic glycolysis yields only 2 ATP per glucose but does it rapidly without oxygen, producing lactate as a byproduct. Above the lactate threshold (typically 70-85% of max heart rate for trained individuals), lactate accumulation outpaces clearance, limiting duration",
        "why": "different training stimuli produce different adaptations. Aerobic training increases mitochondrial density, capillarization, and stroke volume, improving endurance and cardiovascular health. Anaerobic training increases muscle fiber size, neuromuscular recruitment, and lactate tolerance, improving strength and power. Both contribute to overall fitness, longevity, and metabolic health, but in different ways",
        "vs": "aerobic exercise uses fat and carbohydrate at moderate intensities, with greater fat utilization at lower intensities (the so-called fat-burning zone, though total caloric burn can be higher at higher intensities). Anaerobic burns mostly glycogen rapidly. Aerobic produces sustained heart rate elevation (60-80% of max); anaerobic produces brief spikes near max. Both have cardiovascular benefits, but interval training (alternating both) may be especially efficient",
        "ex": "running a 5K at conversation pace is mostly aerobic: oxygen demand is met, fuel comes from glycogen and fat, and you can sustain the pace 20-30 minutes. Sprinting 200 meters at full effort is anaerobic: oxygen lags demand, lactate spikes, and you must recover before another effort. A boxing match alternates: aerobic between rounds, anaerobic during exchanges",
        "mis": "people think aerobic and anaerobic are mutually exclusive; in reality both systems contribute simultaneously, with the dominant one shifting with intensity. Another myth is that the fat-burning zone is the only way to lose weight; high-intensity anaerobic training also burns fat through afterburn (EPOC) and metabolic adaptations, often more total calories per minute. A third confusion is that lactate causes muscle soreness; delayed onset muscle soreness comes from microtears, not lactate, which clears within an hour",
    }

    T["cholesterol (HDL vs LDL)"] = {
        "_cat": "everyday_life",
        "what": "two major classes of lipoproteins that transport cholesterol in the blood. LDL (low-density lipoprotein) carries cholesterol from the liver to peripheral tissues and can deposit in arterial walls. HDL (high-density lipoprotein) transports cholesterol from tissues back to the liver for excretion, broadly considered protective",
        "how": "LDL particles arise from VLDL (very-low-density lipoprotein) made by the liver. They circulate, deliver cholesterol via the LDL receptor pathway, and are cleared by the liver. Excess LDL, especially small dense particles, can be retained in arterial intima where macrophages engulf them and form foam cells, the seed of atherosclerotic plaque. HDL acquires cholesterol from peripheral cells via ABCA1 and ABCG1 transporters and delivers it to the liver",
        "why": "elevated LDL and reduced HDL are major risk factors for cardiovascular disease, the leading cause of death globally. Statins reduce LDL by 30-50% and clinical trials show 20-25% reductions in heart attacks and strokes. Lifestyle factors (diet, exercise, weight, smoking) affect both. Knowing your lipid panel and managing it is among the highest-leverage health actions you can take",
        "vs": "LDL is the bad cholesterol because of its causal role in atherosclerosis; HDL is the good cholesterol for its reverse-transport role. Total cholesterol on its own is less informative than the LDL/HDL ratio. Triglycerides are a separate fraction associated with metabolic syndrome and small dense LDL. Lipoprotein(a) is a genetically determined particle that adds independent cardiovascular risk",
        "ex": "an adult with LDL of 160 mg/dL and HDL of 40 mg/dL has substantially elevated cardiovascular risk. A statin lowering LDL to 90 mg/dL plus exercise raising HDL to 55 mg/dL reduces 10-year heart-disease risk by perhaps 30-40%. Familial hypercholesterolemia, a genetic disorder with LDL receptor defects, can produce LDL above 250 from childhood, with early heart disease without treatment",
        "mis": "people view dietary cholesterol as the main driver of blood cholesterol; for most people, dietary saturated fat affects blood LDL more than dietary cholesterol does. Another myth is that high HDL is always protective; very high HDL (above 90 mg/dL) shows mixed cardiovascular benefit and may be a marker rather than a mechanism. A third confusion is that statins are dangerous; while they have side effects in some, the cardiovascular benefit dramatically outweighs harm in high-risk patients",
    }

    T["how an electric motor works"] = {
        "_cat": "everyday_life",
        "what": "a device that converts electrical energy into mechanical rotation by using the interaction between magnetic fields and current-carrying conductors. The fundamental principle is the Lorentz force on charges moving through a magnetic field, producing torque on a rotor",
        "how": "in a brushed DC motor, current flows through coils on the rotor inside a permanent magnetic field; the magnetic torque rotates the rotor, and a commutator switches current direction every half-turn to keep torque consistent. In an AC induction motor, alternating current in stator coils creates a rotating magnetic field that induces currents in the rotor, which then experiences torque pulling it along behind the rotating field",
        "why": "electric motors run essentially everything mechanical in modern life: appliances, fans, pumps, electric vehicles, factories, hard drives, robots. They are far more efficient than internal combustion (90% vs 25-30%), respond instantly, and run silently and cleanly. The shift to electric motors in transportation is driving energy and climate transitions",
        "vs": "DC motors are simpler and easier to control but use brushes that wear. AC induction motors are robust and don't need brushes but require AC power and are harder to control without electronics. Stepper motors give precise positioning at the cost of speed; servo motors combine encoders with control loops for accuracy. Brushless DC motors (used in drones, EVs) combine electronic commutation with the simplicity of permanent magnets for high efficiency and long life",
        "ex": "a Tesla Model 3 uses a permanent-magnet synchronous motor (front) and an induction motor (rear). The motor produces full torque from zero RPM, accelerating instantly. Variable-frequency inverters control the AC waveform to set speed and torque. The motor's regenerative braking works as a generator when slowing down, recovering energy back into the battery, an inversion of normal motor operation",
        "mis": "people think electric motors are inherently complex; the basic principle is just Lorentz force on a coil in a magnetic field. Another myth is that motors lose efficiency at high speeds; modern motors maintain 90%+ efficiency across wide speed ranges. A third confusion is that EV motors require rare earth elements; while many designs use them, induction motors and externally-excited synchronous motors avoid them entirely",
    }

    T["how solar panels generate electricity"] = {
        "_cat": "everyday_life",
        "what": "solar panels (photovoltaic modules) convert sunlight directly into electrical current using the photovoltaic effect in semiconductor materials, typically silicon. Photons strike the panel, excite electrons across the semiconductor's band gap, and an internal electric field at a p-n junction separates electrons and holes, driving current through an external circuit",
        "how": "each cell consists of crystalline silicon doped to form a p-n junction. Photons with energy above the band gap (about 1.1 eV for silicon, corresponding to wavelengths shorter than 1100 nm) excite electrons from valence to conduction band, creating electron-hole pairs. The junction's built-in field separates them, with electrons flowing to the n-side and holes to the p-side, producing DC current. Multiple cells wire in series to reach useful voltages, then inverters convert DC to AC for grid connection",
        "why": "solar PV is now the cheapest source of new electricity in many regions, with utility-scale projects under $30/MWh. Module costs fell roughly 90% from 2010 to 2020, driven by manufacturing scale (especially Chinese fabs), polysilicon process improvements, and cell architecture innovations. Solar plus storage is reshaping electricity markets and decarbonization pathways globally",
        "vs": "solar PV differs from solar thermal, which uses sunlight to heat fluid for steam turbines or hot-water systems. Crystalline silicon dominates over thin-film (CdTe, CIGS, perovskite) due to efficiency and durability, though thin-film is lighter and cheaper per watt in some niches. Compared to wind, solar generates during the day with no moving parts; wind generates day or night when wind blows. Both are intermittent and benefit from storage and grid flexibility",
        "ex": "a typical residential rooftop installation might be 8 kW (24 panels of 330 W each), generating about 11,000 kWh per year in a sunny climate, roughly equal to or exceeding the household's electricity consumption. Net metering credits exported electricity at retail rates in many jurisdictions, with payback periods of 5-10 years. Battery storage adds resilience and self-consumption at additional cost",
        "mis": "people think solar panels don't work in cold or cloudy conditions; cells actually become more efficient at lower temperatures, and diffuse light still produces output, though less than direct sun. Another myth is that manufacturing solar panels takes more energy than they ever produce; modern PV has an energy payback time of 1-3 years and operates 25-30 years, an excellent net-energy ratio",
    }

    T["smoke alarm types"] = {
        "_cat": "everyday_life",
        "what": "household smoke detectors that alert occupants to fire. Two primary detection technologies dominate residential market: ionization detectors (better at fast-flaming fires) and photoelectric detectors (better at slow-smoldering fires). Combination units detect both. Newer alarms integrate carbon monoxide detection",
        "how": "ionization alarms contain a tiny radioactive source (Americium-241) that ionizes air between two electrodes, producing a small steady current. Smoke particles disrupt the ionization, current drops, and the alarm sounds. Photoelectric alarms shine an LED across a chamber; smoke particles scatter light onto a sensor, which triggers the alarm. CO sensors use electrochemical cells or metal-oxide semiconductors that respond to CO molecules",
        "why": "smoke alarms cut fire-related death risk roughly in half and are required by code in most jurisdictions. Battery-powered units are inexpensive ($10-30) and lifesaving. Modern units use 10-year sealed lithium batteries, eliminating the chronic problem of dead-battery alarms. Replacing old alarms (ionization-only) with photoelectric or combination units is one of the highest-leverage home-safety upgrades available",
        "vs": "ionization alarms respond faster to fast-flaming fires (paper, gasoline) and slower to smoldering fires (mattress, electrical). Photoelectric is the inverse, responding faster to smoldering fires (the more common cause of fatalities, since slow smoke can build up overnight). Combination dual-sensor alarms cover both. Compared to heat detectors (used in kitchens to avoid nuisance alarms), smoke alarms detect earlier in most fires",
        "ex": "the U.S. National Fire Protection Association recommends placing alarms inside every bedroom, outside each sleeping area, and on every level, with photoelectric or combination units preferred. Interconnected alarms (wired or wireless) sound together throughout the house, alerting occupants in distant rooms when one detects smoke. Many states now mandate 10-year sealed-battery photoelectric or combination units in new construction",
        "mis": "people think any working alarm is sufficient; ionization-only alarms can take 15-30 minutes longer than photoelectric to detect smoldering fires, the kind that kill sleeping occupants overnight. Another myth is that the trace radioactivity in ionization alarms is dangerous; the dose is negligible. A third confusion is that alarms last forever; sensors degrade over 10 years, and any alarm older than that should be replaced regardless of battery status",
    }

    T["jet lag"] = {
        "_cat": "everyday_life",
        "what": "the temporary disturbance of sleep, alertness, mood, digestion, and cognitive performance that follows rapid travel across multiple time zones. The body's circadian rhythms (sleep-wake, hormone secretion, body temperature) remain set to the origin time and re-synchronize gradually to the destination",
        "how": "the suprachiasmatic nucleus in the hypothalamus serves as the master clock, entrained by light cues to local time. After rapid travel, the SCN's signal still reflects the origin time, while local light, meals, and activity push entrainment toward destination time. Adjustment takes roughly one day per time zone for eastward travel and somewhat faster for westward travel, with younger people adjusting faster than older",
        "why": "jet lag impairs business performance, sports outcomes (athletes traveling east-to-west across multiple zones perform measurably worse), and well-being on multi-day trips. Frequent flyers and shift workers experience chronic circadian misalignment, associated with increased cardiovascular disease, metabolic dysfunction, and cancer risk. Strategies to manage jet lag matter for both individuals and organizations",
        "vs": "jet lag differs from simple sleep deprivation by being primarily a circadian misalignment, not just lack of sleep. Eastward travel is generally harder than westward because lengthening your day (going west, like staying up late) is easier than shortening it (going east, like waking up early). Compared to shift-work disorder, jet lag is acute and resolves; chronic shift work imposes ongoing misalignment",
        "ex": "flying New York to Tokyo (14 hours ahead) means going to bed when your body thinks it's afternoon. Effective strategies include shifting bedtime earlier 2-3 days before departure, exposure to bright morning light at destination, melatonin 0.5-3 mg in the destination evening, and avoiding caffeine and naps during the wrong local hours. Full adjustment takes 7-10 days for a 14-hour shift",
        "mis": "people think melatonin is a sleep aid; it is a circadian time-cue, more useful for re-entraining your clock at correct times than for inducing sleep generally. Another myth is that you can power through jet lag with caffeine; this masks symptoms while delaying actual circadian resynchronization. A third confusion is that drinking on the plane helps you sleep through the flight; alcohol fragments sleep and dehydrates, worsening recovery",
    }

    T["altitude sickness"] = {
        "_cat": "everyday_life",
        "what": "a constellation of symptoms (headache, nausea, fatigue, shortness of breath) that develops when ascending too rapidly to high elevation, typically above 2500 meters. Severe forms include high-altitude pulmonary edema (HAPE) and high-altitude cerebral edema (HACE), both potentially fatal without descent",
        "how": "atmospheric pressure decreases with altitude, reducing partial pressure of oxygen even though the percentage in air remains 21%. The body responds by hyperventilating and increasing heart rate; over days, kidneys reduce bicarbonate and bone marrow produces more red blood cells. Acute mountain sickness reflects incomplete adjustment; HAPE and HACE result from fluid leakage in lung and brain tissue under hypoxic stress",
        "why": "altitude sickness affects mountaineers, trekkers, skiers, and travelers to high cities (La Paz, Lhasa, Cusco). Failed acclimatization on Everest expeditions has killed climbers; less dramatic AMS spoils plenty of vacations. Understanding prevention (gradual ascent, hydration) and treatment (descent, oxygen, medications) is essential for high-altitude travel safety",
        "vs": "AMS differs from simple shortness of breath by including systemic symptoms (headache, nausea, sleep disturbance). It differs from HAPE (pulmonary edema with cough, frothy sputum, severe breathlessness even at rest) and HACE (confusion, ataxia, drowsiness leading to coma) which are emergencies requiring immediate descent. Compared to physical conditioning's role, fitness does not protect against altitude sickness; physiological acclimatization is what matters",
        "ex": "trekkers ascending to Everest Base Camp at 5364 meters typically take 8-10 days from Lukla (2860 m) to allow gradual acclimatization. Climbing too fast (e.g., flying directly to a 4000-meter destination) triggers AMS in 25-50% of unacclimatized travelers within 6-12 hours. Acetazolamide (Diamox) prophylaxis reduces incidence by stimulating the breathing response. Symptoms not improving with rest require descent",
        "mis": "people think hiking experience prevents altitude sickness; experience helps with judgment, but AMS depends on physiological adaptation, not fitness. Another myth is that drinking lots of water prevents it; hydration helps but does not substitute for gradual ascent. A third confusion is that mild symptoms can be ignored; AMS can progress to HAPE or HACE within hours if ascent continues, so any worsening should prompt descent",
    }

    T["reading nutrition labels"] = {
        "_cat": "everyday_life",
        "what": "the practice of interpreting the standardized nutrition information panels on packaged foods. Labels in most countries display serving size, calories, macronutrients (fat, carbohydrate, protein), key micronutrients, and percent daily values. Understanding them is foundational to dietary self-management and informed food choice",
        "how": "the FDA-mandated U.S. label (revised 2016) lists servings per container, calories per serving, grams of total fat (with breakdowns of saturated and trans), cholesterol, sodium, total carbohydrate (with fiber, total sugars, added sugars), protein, and percent daily values for vitamin D, calcium, iron, and potassium based on a 2000-calorie reference. The ingredient list ranks by weight, so the first few ingredients dominate the food",
        "why": "labels are the primary tool for managing chronic conditions (diabetes, hypertension, hyperlipidemia), tracking macros for fitness, identifying allergens, and avoiding excessive added sugar and sodium. Public-health nutrition policy, food industry reformulation, and consumer choice all hinge on labeling. The 2016 added-sugar disclosure has measurably shifted product reformulation toward lower sugar",
        "vs": "labels differ from front-of-package marketing claims (low fat, all natural), which can mislead. They differ from menu calorie labeling at restaurants, which uses different reference points and granularity. Compared to detailed nutritional databases (USDA FoodData Central), labels offer a quick-reference subset suitable for store-aisle decisions",
        "ex": "a snack with 230 calories per serving and 4 servings per container actually delivers 920 calories if you eat the whole bag, a common pitfall. A yogurt with 12 g sugar might list 8 g added sugar, with the rest from natural lactose. A cereal claiming low-fat with 22 g sugar per serving is calorie-dense despite the headline claim. Reading the actual numbers prevents being misled by marketing",
        "mis": "people fixate on fat or calories without checking serving size, the foundation of every other number on the panel. Another myth is that organic or natural ingredients automatically mean healthy; organic sugar still spikes blood glucose. A third confusion is that low-sodium means salt-free; products labeled low-sodium still have meaningful amounts that count toward daily intake limits",
    }

    # ===== CURRENT EVENTS =====

    T["electric vehicle adoption"] = {
        "_cat": "current_events",
        "what": "the global transition from internal combustion engine vehicles to battery electric vehicles (BEVs), plug-in hybrids (PHEVs), and to a lesser degree fuel-cell EVs. EV market share has grown from under 1% in 2015 to roughly 18% of new global passenger vehicle sales by 2024, led by China (35%+), Europe (20%+), and lagging in the U.S. (~9%)",
        "how": "adoption is driven by falling battery costs (from $1100/kWh in 2010 to under $130/kWh by 2024), improving range and charging speeds, government subsidies and emissions mandates (EU 2035 ICE ban, California Zero-Emission Vehicle requirements), and expanding charging networks. Tesla's Supercharger network, BYD's vertical integration in China, and legacy automakers' pivot are reshaping competition",
        "why": "transportation accounts for roughly a quarter of global CO2 emissions, with passenger cars a large share. EVs powered by increasingly clean grids cut lifecycle emissions substantially even after accounting for battery manufacturing. They also reshape oil demand, electricity demand, urban air quality, and geopolitics around lithium, cobalt, and rare earths",
        "vs": "BEVs differ from PHEVs (which retain a smaller battery and a gasoline engine) by being fully electric. They differ from hybrids (no plug, smaller battery) entirely. Compared to fuel-cell vehicles, BEVs are more energy-efficient and have charging infrastructure ahead, while fuel cells may suit heavy trucking and shipping where battery weight is prohibitive",
        "ex": "Norway leads the world: by 2024, over 90% of new car sales were EVs, driven by tax exemptions, free tolls, bus-lane access, and abundant charging. China's BYD overtook Tesla as the largest EV manufacturer in 2023 and now sells more pure EVs than any other automaker. Tesla's Model Y was the world's best-selling vehicle in 2023 across all powertrains, a milestone for EV adoption",
        "mis": "people think EVs only shift emissions to power plants; lifecycle analyses including manufacturing and grid mix consistently show 30-70% lifecycle emission reductions versus comparable ICE vehicles, increasing as grids decarbonize. Another myth is that batteries fail quickly; modern EV batteries retain 80-90% capacity after 8-10 years and 200,000 km. A third confusion is that EV range anxiety remains acute; most modern EVs exceed 300 km, ample for typical daily use",
    }

    T["large language models and their limits"] = {
        "_cat": "current_events",
        "what": "AI systems trained on vast text corpora to predict the next token in a sequence, then aligned through supervised fine-tuning and reinforcement learning to follow instructions. Modern LLMs (GPT-4/5, Claude, Gemini, Llama) demonstrate broad linguistic competence, code generation, reasoning, and tool use, but exhibit hallucinations, brittleness, and bounded reasoning",
        "how": "transformer-based models with billions to trillions of parameters are pretrained on internet-scale text data using next-token prediction. Post-training combines supervised fine-tuning on human demonstrations and RLHF or similar methods to align outputs with helpfulness, harmlessness, and honesty objectives. Inference is autoregressive: each token sampled becomes part of the context for the next",
        "why": "LLMs have transformed knowledge work in roughly two years (2022-2024), with millions using them daily for writing, coding, customer service, search, and analysis. They are reshaping software development, education, customer support, and creative industries. Investment, regulation, and labor implications are reshaping technology policy globally",
        "vs": "LLMs differ from earlier NLP systems (rule-based, statistical, smaller neural networks) by their scale and emergent capabilities. They differ from search engines by generating novel text rather than retrieving documents. Compared to specialized AI (computer vision, speech, robotics), LLMs cover a broad task surface with one model. Compared to symbolic reasoning systems, they are much better at fluent language but weaker at provably correct logic",
        "ex": "GPT-4 in 2023 demonstrated the ability to pass the bar exam, write functional code from natural-language descriptions, reason through multi-step word problems, and discuss obscure topics. The same model would still confidently invent fake citations, misattribute quotes, fail simple counting tasks like counting letters in a word, and struggle with truly novel reasoning where pattern-matching from training data does not apply",
        "mis": "people anthropomorphize LLMs as understanding meaning; they predict tokens via learned statistical patterns, which can produce remarkable behavior but does not include grounded understanding or self-awareness. Another myth is that bigger always means better; scaling has slowed, and architecture, data quality, and post-training matter increasingly. A third confusion is that hallucinations are bugs to be patched; they reflect the fundamental architecture of probabilistic text prediction, mitigated but not eliminated by retrieval, citations, and tool use",
    }

    T["mRNA vaccine platforms"] = {
        "_cat": "current_events",
        "what": "vaccines that use synthetic messenger RNA encoding a pathogen's antigen, delivered via lipid nanoparticles, instructing the recipient's cells to produce the antigen and trigger an immune response. mRNA vaccines achieved their first widespread deployment with COVID-19 vaccines from Pfizer-BioNTech and Moderna in late 2020",
        "how": "researchers identify a target antigen (the SARS-CoV-2 spike protein in COVID vaccines), design mRNA encoding a stabilized version of it with codon optimization and modified nucleosides (pseudouridine) for stability and reduced inflammation, and encapsulate it in lipid nanoparticles that deliver the mRNA into cells. Cells translate the mRNA into the antigen protein, presenting it to the immune system, which generates antibodies and T-cell responses",
        "why": "mRNA platforms compress vaccine development timelines from years to months, enable rapid response to emerging pathogens, and allow easy sequence updates as variants arise. They also open new applications: cancer vaccines tailored to individual tumor antigens, treatments for genetic diseases by delivering replacement enzymes transiently, and vaccines for difficult targets like HIV, malaria, and cancer that conventional approaches have struggled with for decades",
        "vs": "mRNA vaccines differ from traditional inactivated or attenuated vaccines (which use weakened pathogens) by being entirely synthetic and protein-free. They differ from protein-subunit vaccines (which inject the antigen directly) by having the body produce the antigen itself, often eliciting stronger T-cell responses. Compared to viral-vector vaccines (AstraZeneca, J&J), mRNA avoids pre-existing immunity to the vector and can be redesigned in days rather than weeks",
        "ex": "BioNTech and Moderna had vaccine candidates within weeks of the SARS-CoV-2 sequence release in January 2020, entered clinical trials by March, and received emergency authorization in December 2020, an unprecedented timeline. Subsequent variant boosters (Omicron BA.5, XBB) demonstrated the platform's adaptability, with reformulated vaccines available within months of variant emergence",
        "mis": "people think mRNA changes your DNA; mRNA never enters the cell nucleus and degrades within days, with no mechanism for genetic modification. Another myth is that mRNA vaccines are unprecedented experimental technology; mRNA vaccine research has been ongoing for over 30 years, and the COVID vaccines built on extensive prior work in cancer immunotherapy and infectious disease. A third confusion is that vaccine immunity wanes proves vaccines failed; some waning is expected for any vaccine and does not negate the substantial protection during the most acute period",
    }

    T["the loneliness epidemic"] = {
        "_cat": "current_events",
        "what": "a public-health concern about widespread social isolation and subjective loneliness in many developed countries, declared by the U.S. Surgeon General in 2023 to be a public health crisis. Surveys show roughly half of American adults report frequent loneliness, with comparable trends in the UK, Japan, and other industrialized nations",
        "how": "drivers include declining marriage and birth rates, geographic mobility separating extended families, longer work hours, screen-mediated social interaction displacing in-person contact, decline of civic and religious organizations (Putnam's Bowling Alone thesis), and the COVID-19 pandemic's lasting effects. Loneliness disproportionately affects older adults, young adults, single people, and immigrants",
        "why": "chronic loneliness is associated with increased mortality (similar in magnitude to smoking 15 cigarettes a day according to some meta-analyses), cardiovascular disease, dementia, depression, and substance abuse. The effects on health systems, productivity, and life satisfaction make loneliness an economic as well as a moral issue. Policy responses include UK's Minister for Loneliness (2018), Japan's similar role (2021), and various community-revitalization programs",
        "vs": "loneliness differs from social isolation (the objective lack of contact) by being subjective: someone can be alone without feeling lonely or surrounded yet feel deeply lonely. It differs from depression, though they often co-occur; loneliness is specifically about perceived social connection deficit. Compared to introversion, loneliness is unwanted; introverts may prefer solitude without feeling lonely",
        "ex": "Cigna's 2018 and 2020 loneliness surveys found that about 60% of Americans report often feeling lonely, with rates highest among adults 18-22. The Harvard Study of Adult Development, the longest study of human happiness, found that the strength of social relationships is the single best predictor of physical and mental health in old age, far outweighing wealth, fame, or genes",
        "mis": "people think loneliness primarily affects the elderly; surveys show young adults often report higher rates than seniors. Another myth is that social media reduces loneliness; heavy social media use correlates with higher loneliness in many studies, though causation is debated. A third confusion is that loneliness is just an emotion to ride out; chronic loneliness produces measurable physiological changes (inflammation, cortisol dysregulation) that justify treating it as a health issue",
    }

    T["quantum computing progress"] = {
        "_cat": "current_events",
        "what": "the development of computers that exploit quantum-mechanical phenomena (superposition, entanglement, interference) to perform certain computations exponentially faster than classical computers. The field has progressed from early laboratory demonstrations to systems with hundreds of physical qubits and growing investment from IBM, Google, and dozens of startups",
        "how": "qubits can be implemented as superconducting circuits (IBM, Google), trapped ions (IonQ, Quantinuum), photons (PsiQuantum, Xanadu), or neutral atoms (QuEra, Atom Computing). Each platform has trade-offs in coherence time, gate fidelity, scalability, and cost. Quantum error correction overlays many physical qubits to make logical qubits; achieving fault tolerance with manageable overhead remains the central challenge",
        "why": "quantum computers promise breakthroughs in cryptography (Shor's algorithm threatens RSA and ECC), materials science and chemistry (simulating quantum systems classical computers struggle with), optimization, and machine learning. The cryptographic threat has triggered the migration to post-quantum cryptography in protocols like TLS. Drug discovery, fertilizer chemistry, and battery materials are leading near-term application areas",
        "vs": "quantum computers are not faster classical computers; they offer exponential speedups only for specific problem classes. Most everyday computation is unaffected. Quantum supremacy (a quantum computer outperforming classical ones on a specific contrived task) was claimed by Google in 2019 with Sycamore. Practical quantum advantage on problems of real-world value remains out of reach as of mid-decade",
        "ex": "IBM's 2023 Heron processor with 133 qubits and Google's Willow chip in 2024 with 105 qubits and a major error-correction milestone (logical qubit error rate decreasing exponentially with code distance) represent significant progress. Yet the systems run only short circuits before errors dominate. Realistic estimates for cryptographically relevant fault-tolerant quantum computers range from late 2020s to 2040s, with substantial uncertainty",
        "mis": "people think quantum computers are simply faster; for most tasks, classical computers will remain superior because quantum algorithms exist for only a narrow set of problems. Another myth is that they are just around the corner; while progress is real and accelerating, fault-tolerant systems suitable for breaking RSA-2048 keys are likely a decade or more away. A third confusion is that any vendor's qubit count is comparable; physical qubit count matters less than logical qubit count, gate fidelity, and connectivity, which differ vastly across platforms",
    }

    T["James Webb Space Telescope discoveries"] = {
        "_cat": "current_events",
        "what": "the scientific findings from the James Webb Space Telescope (JWST), launched on Christmas Day 2021 and operational at the L2 Lagrange point since mid-2022. JWST is the largest infrared space telescope ever flown, with a 6.5-meter segmented mirror, 100x more sensitive than Hubble in the infrared",
        "how": "JWST observes in mid- and near-infrared wavelengths (0.6-28 microns) blocked by Earth's atmosphere. Its sunshield keeps the optics passively cooled below 50 K. Spectrographs and cameras enable photometry, spectroscopy, and imaging across cosmic ages: from earliest galaxies to nearby exoplanet atmospheres. Highly oversubscribed observing time goes through a competitive proposal process",
        "why": "JWST has revealed unexpected populations of mature, massive galaxies in the very early universe (within 500 million years of the Big Bang), challenging existing galaxy formation models. It has measured atmospheres of dozens of exoplanets, detected molecular signatures including CO2, water vapor, and possibly biosignatures (controversial DMS detection on K2-18b). It has imaged star formation, planetary systems forming around young stars, and the structure of nearby galaxies in unprecedented detail",
        "vs": "JWST is not a replacement for Hubble but complements it by extending into infrared where Hubble is weak. Hubble continues operating in visible and ultraviolet. Compared to ground-based observatories (Extremely Large Telescope, Thirty Meter Telescope), JWST has the advantage of zero atmospheric absorption but smaller aperture. The Roman Space Telescope (planned launch ~2027) will provide wide-field infrared survey capability complementing JWST's deep-narrow approach",
        "ex": "JWST's First Deep Field, released July 2022, shows thousands of distant galaxies in a patch of sky the size of a grain of sand at arm's length, with light from galaxies as old as 13 billion years. The Carina Nebula image, also from first releases, shows star formation regions in detail that triggered widespread public engagement. Spectroscopy of WASP-39b detected sulfur dioxide and revealed photochemistry in an exoplanet atmosphere",
        "mis": "people think JWST replaced Hubble; both telescopes operate concurrently, complementing each other across wavelengths. Another myth is that early-universe galaxy findings disprove the Big Bang; they challenge specific galaxy formation timelines, not the cosmological framework. A third confusion is that biosignature claims (such as DMS) are confirmed; current detections are tentative and require further observations and modeling to assess robustness",
    }

    T["SpaceX and reusable rockets"] = {
        "_cat": "current_events",
        "what": "SpaceX's pioneering of partially and fully reusable orbital rockets, beginning with Falcon 9 first-stage landings in 2015 and continuing with Falcon Heavy and the in-development Starship system. Reusability dramatically lowered the cost of access to space, enabling Starlink's mass deployment and shifting the global launch market",
        "how": "Falcon 9 first stages return to a landing pad or autonomous drone ship after staging, using grid fins and Merlin engines for guidance and propulsive landing. Refurbishment between flights costs a fraction of building a new stage. Starship aims for full reusability with both stages returning to launch sites and being relaunched within hours, using Raptor methane-oxygen engines and stainless steel construction for thermal robustness",
        "why": "launch costs dropped from roughly $10,000/kg to LEO in the early 2010s to under $2,000/kg with Falcon 9 and projected to under $200/kg with Starship. The economic shift enables previously impossible missions: large satellite constellations, lunar architecture, eventual Mars settlement plans. Most national space programs are recalibrating around the new economics",
        "vs": "SpaceX's reusability differs from prior space-shuttle reusability, which involved expensive refurbishment between flights and ultimately did not achieve cost reductions. SpaceX automates landing and refurbishment, achieving Falcon 9 turnarounds in weeks and aiming for hours with Starship. Compared to expendable rockets (older Atlas V, Ariane 5), Falcon 9 with reusable booster cuts costs roughly in half; Starship aims for orders of magnitude further",
        "ex": "by mid-2024, SpaceX had launched Falcon 9 over 350 times, with first stages landing successfully on most missions and individual boosters flying 20+ missions each. Starship's fourth flight test in June 2024 achieved both stage soft splashdown after orbital trajectory, demonstrating the full reentry and landing profile. Starlink, dependent on cheap launch, surpassed 5 million subscribers in 2024",
        "mis": "people think SpaceX invented reusability; the X-15 and Space Shuttle had elements of reuse, but SpaceX achieved the first economically meaningful reuse. Another myth is that competitors will quickly catch up; Blue Origin's New Shepard is suborbital, ULA's Vulcan engines may be reusable but the booster is expended, and Chinese efforts are years behind. A third confusion is that Starship is operational; as of mid-2024 it is still in test flight phase, with operational missions likely 2025 or later",
    }

    T["misinformation and platform moderation"] = {
        "_cat": "current_events",
        "what": "the challenge of detecting and managing false or misleading information on online platforms (Facebook, X/Twitter, YouTube, TikTok), and the contested debate over how, whether, and by whom such moderation should occur. The issue intersects free speech, public health, election integrity, and platform liability",
        "how": "platforms employ content moderation teams, automated classifiers (often LLM-based by 2024), third-party fact-checkers, labeling systems, and community-notes mechanisms. Removed content is typically appealable. Approaches range from heavy intervention (removal, deboosting) to lighter touch (labels, link restrictions). Section 230 in the U.S. provides liability shields; the EU Digital Services Act imposes formal obligations",
        "why": "misinformation around elections, COVID-19, climate change, and ethnic conflict has demonstrably affected real-world behavior, public health (vaccine hesitancy), and democratic outcomes. At the same time, moderation can suppress legitimate speech, exhibit ideological bias, or amplify the very content it tries to address (Streisand effect). The tension between democratic discourse and harm reduction is the core policy challenge",
        "vs": "moderation differs from outright censorship by being conducted by private platforms rather than government, though boundaries blur with government communications and law. It differs from content recommendation algorithms which decide what to amplify (the more important policy lever according to many researchers). Compared to traditional media editorial choices, platform moderation operates at vastly larger scale with thinner human review per item",
        "ex": "Twitter's pre-2022 approach to COVID-19 misinformation labeled or removed millions of posts; Elon Musk's acquisition reversed many policies and reduced moderation staff. Meta has shifted between heavy moderation in 2020-2022 and lighter approaches in 2024-2025. The 2025 shift announcement to community notes by Meta marked a notable policy reversal. Each shift produces measurable changes in what content circulates and reaches users",
        "mis": "people see moderation as binary (free speech vs censorship) when in practice platforms make nuanced trade-offs, including labeling, deboosting, and contextual additions short of removal. Another myth is that algorithmic moderation is neutral; classifiers reflect training data biases and policy choices encoded by humans. A third confusion is that misinformation is solely an online phenomenon; offline word-of-mouth, partisan media, and political messaging contribute as much or more in many domains",
    }
