#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank part 2: history + arts_and_humanities."""


def register(T):
    # ===== HISTORY =====

    T["the Indus Valley civilization"] = {
        "_cat": "history",
        "what": "a Bronze Age civilization that flourished from roughly 3300 to 1300 BCE in the basins of the Indus River and adjacent Ghaggar-Hakra system in present-day Pakistan and northwest India, with major cities including Harappa, Mohenjo-daro, Dholavira, and Lothal",
        "how": "cities were built on a planned grid pattern with standardized fired-brick construction, sophisticated drainage and sewage, and large public granaries and baths. Trade networks reached Mesopotamia, Persia, and Central Asia, attested by Indus seals found at Sumerian sites. The civilization gradually declined around 1900 BCE, possibly due to monsoon shifts, river course changes, and ecological stress",
        "why": "the civilization rivaled contemporary Egypt and Mesopotamia in scale and sophistication and remains one of antiquity's great urban achievements. Its extensive use of standardized weights and measures, urban planning, and metallurgy seeded later South Asian civilizations. Its undeciphered script remains one of archaeology's enduring mysteries",
        "vs": "the Indus civilization differs from Mesopotamia in lacking obvious palaces, royal tombs, and explicit warrior iconography, suggesting a less hierarchical social order. It differs from Egypt by the absence of monumental tombs and grand temples. Compared to its contemporaries, its hallmark was practical urban infrastructure rather than dynastic display",
        "ex": "Mohenjo-daro had a population estimated at 35,000 to 40,000, with multistory brick houses, indoor plumbing connected to citywide drains, and the famous Great Bath, a tank with bitumen-sealed flooring used for ritual or communal bathing. The standardized brick ratios across hundreds of sites point to centralized regulation",
        "mis": "people picture the civilization as a small regional culture, but at its peak it covered roughly 1.25 million square kilometers, making it geographically the largest of the early civilizations. Another myth is that it ended in violent collapse; archaeological evidence points to gradual deurbanization, with rural successor cultures persisting for centuries",
    }

    T["the Han dynasty"] = {
        "_cat": "history",
        "what": "the Chinese imperial dynasty that ruled from 206 BCE to 220 CE (with a brief interregnum), founded by Liu Bang after the collapse of the Qin. Often considered a golden age of Chinese civilization, it consolidated Confucian governance, expanded territory dramatically, and gave its name to the dominant Han Chinese ethnicity",
        "how": "the Han adopted Confucian ideology while keeping Legalist administrative machinery, established a civil service examination system in embryonic form, standardized currency and writing, and built infrastructure including the early Silk Road. Emperor Wu (141-87 BCE) pushed the empire to its greatest extent, defeating the Xiongnu confederation, conquering parts of Korea, and opening sustained trade with Central Asia",
        "why": "the Han set patterns of Chinese government, scholarship, and identity that persisted for two millennia. The civil service ideal, the centrality of Confucian classics, the unity of bureaucracy and merit, and the Silk Road as a vector of cross-Eurasian exchange all date to the Han. Modern Chinese still call themselves people of Han",
        "vs": "the Han differed from the preceding Qin by softening Legalist harshness with Confucian rhetoric while retaining centralized administration. It differed from the later Tang by relying more on landed aristocrats and less on a fully developed exam system. Compared to the contemporary Roman Empire, the Han had similar scale (roughly 60 million people) and reach but different governance, with no slave-economy comparable to Rome's",
        "ex": "the historian Sima Qian, writing in the early Western Han, produced the Records of the Grand Historian, the model for all later Chinese dynastic histories. His narrative method and biographical structure shaped East Asian historiography for two thousand years and is still read as both literature and source",
        "mis": "people think the Han adopted Confucianism wholesale, but Han Confucianism was a syncretic system blending Confucian ethics with Legalist administrative tools and yin-yang cosmology. Another myth is that the Silk Road was a single road; it was a sprawling network of overland and maritime routes flowing both ways across Eurasia",
    }

    T["the Maya civilization"] = {
        "_cat": "history",
        "what": "a Mesoamerican civilization centered in the Yucatan Peninsula, Guatemala, Belize, and parts of Honduras and El Salvador, with a continuous tradition spanning roughly 2000 BCE to the Spanish Conquest. The Classic period (250 to 900 CE) saw the apex of monumental architecture, hieroglyphic writing, mathematics, and astronomy",
        "how": "the Maya built city-states (Tikal, Palenque, Calakmul, Copan) ruled by divine kings whose authority rested on dynastic descent, ritual performance, and warfare. They developed a complex calendar system (the Long Count, the 260-day Tzolkin, the 365-day Haab), a fully phonetic-logographic script, vigesimal mathematics including a positional zero, and sophisticated agricultural systems with raised fields and terraces",
        "why": "the Maya independently developed writing, mathematical zero, and astronomical observations comparable in precision to anything in the ancient Mediterranean, demonstrating that complex civilization arose multiple times. Their decipherment in the late 20th century rewrote understanding of pre-Columbian America. Modern Maya peoples (around 7 million) still speak Mayan languages and preserve cultural traditions",
        "vs": "the Maya differ from the Aztecs (Mexica) by being earlier, more decentralized, and never forming a single empire. They differ from the Inca by lacking metallurgy for tools and roads spanning continents, and by emphasizing writing more heavily. Compared to the Olmec, an earlier mother culture, the Maya elaborated on shared Mesoamerican ideas rather than originating them",
        "ex": "the Long Count calendar at Quirigua records dates back to 13 August 3114 BCE (the mythological starting point) and forward in calculations spanning millions of years. The bak'tun cycle ending on 21 December 2012 sparked modern doomsday speculation, but Maya texts treat it as a calendar reset, not an apocalypse, and several inscriptions calculate dates well beyond 2012",
        "mis": "people think the Maya disappeared; the Classic Maya political system collapsed around 900 CE, but Maya peoples persist today in Guatemala and southern Mexico in millions, speaking thirty-plus Mayan languages. Another myth is that Maya predicted the world's end in 2012; their calendar simply rolled over to a new bak'tun, no different from a millennial transition",
    }

    T["classical Greek democracy"] = {
        "_cat": "history",
        "what": "the political system that developed in the Greek city-state of Athens during the 5th and 4th centuries BCE, in which adult male citizens directly participated in decision-making through the Assembly, jury courts, and randomly selected councils. Cleisthenes' reforms in 508-507 BCE are conventionally taken as its foundation",
        "how": "the Assembly (Ekklesia) met about 40 times a year on the Pnyx, where any citizen could speak and vote on laws, war, and treaties. The Council of 500 (Boule), chosen by lot from the ten tribes, set the agenda. Juries of hundreds were drawn by lot to decide cases. Most magistracies were also filled by lottery, reflecting a deep belief that any citizen could perform civic functions and that random selection prevented oligarchic capture",
        "why": "Athenian democracy is the historical reference point for popular self-government, debated and emulated for 2500 years. Its institutions of public deliberation, equal speech (isegoria), accountability through randomly drawn juries, and citizen lawmaking informed Enlightenment political thought, the American and French revolutions, and modern conceptions of legitimacy",
        "vs": "Athenian democracy differs from modern representative democracy by using direct decision-making and sortition rather than elections, which Athenians considered oligarchic. It differs from Spartan and Roman political systems by its breadth of citizen participation. Compared to other Greek poleis like Thebes or Corinth, Athens pushed democratic institutions farther, while Sparta retained dual kingship and a mixed constitution",
        "ex": "ostracism allowed citizens once a year to write a name on a potsherd; if 6,000 were cast, the most-named person was banished for ten years without trial. Themistocles, the architect of the Persian Wars victory at Salamis, was ostracized in the 470s, illustrating both the power and the populism risks of direct democracy",
        "mis": "people equate Athenian democracy with universal participation, but only adult male citizens (perhaps 30,000 to 40,000 of a total population of around 250,000 including women, foreigners, and slaves) had political rights. Another myth is that it was unstable; it endured roughly two centuries with brief oligarchic interruptions, comparable to many modern republics",
    }

    T["the Roman Republic vs Empire transition"] = {
        "_cat": "history",
        "what": "the gradual political transformation of Rome from the senatorial Republic founded in 509 BCE to the imperial autocracy formally established under Augustus in 27 BCE. The transition spanned roughly a century of civil war, reform, and constitutional contortion that preserved republican forms while concentrating power in one person",
        "how": "the late Republic suffered from generals (Marius, Sulla, Pompey, Caesar) building personal armies, populist tribunes bypassing the Senate, and slave revolts. After Caesar's assassination in 44 BCE and renewed civil war, Octavian (Augustus) emerged victorious in 31 BCE at Actium. He preserved Senate, magistrates, and republican vocabulary while accumulating tribunician power, imperium over key provinces, and supreme religious authority, creating the principate",
        "why": "the transition is the prototype of how a republic with strong civic institutions can be hollowed out from within while keeping its forms intact. Cicero's correspondence and Tacitus' histories trace the moral and institutional decay; modern republics study Rome to understand executive aggrandizement, military politicization, and the slow death of checks and balances",
        "vs": "the Republic differed from the Empire in distributing power among annually elected magistrates, the Senate, and popular assemblies, with formal term limits and collegiality. The Empire concentrated power in a single princeps holding life-long imperium, with the Senate decoratively retained. The transition is gradual, not a single coup; constitutional formalities outlasted the substance by centuries",
        "ex": "Augustus famously claimed to have restored the Republic, returning powers to the Senate and people. The Senate then voted him special powers and titles repeatedly, including the right to summon the Senate, propose business first, and command all armies. The forms remained republican; the substance was monarchy in all but name",
        "mis": "people imagine Caesar made himself emperor; he was assassinated as dictator-for-life and never used the title imperator in the later monarchical sense. Augustus did the actual work of converting the system. Another myth is that the change was sudden; the late Republic had been drifting toward strongman politics for a century before Augustus formalized the new arrangement",
    }

    T["the Mongol Empire's expansion"] = {
        "_cat": "history",
        "what": "the rapid territorial expansion of the Mongol Empire under Genghis Khan and his successors from 1206 to roughly 1294, eventually creating the largest contiguous land empire in history, stretching from Korea to Eastern Europe and from Siberia to the Persian Gulf",
        "how": "Mongol military success rested on horse-archer mobility, decimal-organized armies (units of 10, 100, 1000, 10000), feigned-retreat tactics, integration of conquered peoples (Khitans, Chinese, Persians) for siege engineering and administration, brutal psychological warfare against resisting cities, and superb intelligence networks. Successors like Kublai Khan in China and Hulagu in Persia consolidated administration over settled populations",
        "why": "the Mongol conquests reshaped Eurasia. The Pax Mongolica enabled long-distance Silk Road trade and intellectual exchange that brought gunpowder, paper, and movable type westward and astronomical and medical knowledge eastward. Marco Polo's travels and ibn Battuta's journeys are direct products. The plague itself probably traveled west along Mongol trade routes, triggering the Black Death",
        "vs": "the Mongol expansion differs from earlier nomadic conquests (Huns, Avars) by its speed, scale, and ability to administer settled populations rather than just raiding. It differs from the contemporary Crusades by its global rather than regional scope. Compared to later European overseas empires, it built no maritime empire and depended on cavalry mobility rather than oceanic projection",
        "ex": "the 1241 invasion of Hungary and Poland saw Mongol forces under Subutai and Batu defeat European armies at Legnica and Mohi within days of each other, advancing within sight of Vienna before withdrawing on news of Ogedei Khan's death. Their tactical sophistication outmatched the heavy European cavalry comprehensively",
        "mis": "people see the Mongols only as destroyers, but post-conquest Mongol administration in Yuan China and Ilkhanid Persia patronized art, science, and religious tolerance. The empire's tax-gathering bureaucracy, postal relay system (yam), and standardized law (Yassa) were institutional innovations. Another myth is that it collapsed quickly; successor khanates ruled for 150-300 years",
    }

    T["the Crusades"] = {
        "_cat": "history",
        "what": "a series of religiously sanctioned military campaigns launched primarily by Latin Christians from 1095 to 1291 (numbered Crusades I-IX, with later expeditions through the 15th century) aimed at recovering and defending Jerusalem and the Holy Land from Muslim control, with additional crusades against pagan Slavs, Cathars, and political enemies",
        "how": "Pope Urban II's call at Clermont in 1095 promised remission of sins to participants, mobilizing tens of thousands of nobles and commoners. The First Crusade captured Jerusalem in 1099 and established Crusader States. Subsequent crusades responded to Muslim counteroffensives (Saladin's recapture of Jerusalem in 1187, the fall of Acre in 1291). Military orders (Templars, Hospitallers, Teutonic Knights) institutionalized permanent crusading forces",
        "why": "the Crusades reshaped relations among Latin Christianity, Byzantium, the Islamic world, and Jewish communities. They opened sustained Mediterranean trade for Italian city-states (Venice, Genoa), introduced Arabic learning to Western Europe, intensified anti-Jewish violence, deepened the Christian schism after the 1204 sack of Constantinople, and contributed to feudal restructuring as crusader nobles mortgaged or abandoned estates",
        "vs": "the Crusades differed from earlier Christian-Muslim conflicts by their explicitly papal sponsorship, plenary indulgences, and ideological framing as armed pilgrimages. They differed from later European colonialism by lacking sustained settler states (the Crusader kingdoms collapsed) and systematic economic exploitation. Compared to jihad in Islamic doctrine, crusade was a more ad hoc theological development",
        "ex": "the Fourth Crusade (1202-1204), originally aimed at Egypt, was diverted by Venetian financial interests and dynastic intrigue to attack Christian Constantinople, sacking the city and establishing the short-lived Latin Empire. The diversion fatally weakened Byzantium against later Ottoman expansion and deepened Orthodox-Catholic enmity to the present day",
        "mis": "people picture all Crusades as Christian-Muslim wars in the Holy Land, missing the Albigensian Crusade against Cathars in southern France, the Northern Crusades against Baltic pagans, and political crusades against Frederick II. Another myth is uniformly Christian victory; after the First Crusade, Christian forces lost more than they won, ending with total expulsion in 1291",
    }

    T["the Reconquista"] = {
        "_cat": "history",
        "what": "the centuries-long process by which Christian kingdoms in the Iberian Peninsula gradually reconquered territory from Muslim al-Andalus, conventionally dated from the Battle of Covadonga around 722 CE to the fall of Granada in 1492. Its conclusion coincided with the Catholic Monarchs' sponsorship of Columbus and the expulsion of Spanish Jews",
        "how": "small northern Christian polities (Asturias, Leon, Navarre, Aragon, Castile, Portugal) expanded southward in fits and starts, exploiting fragmentation of Muslim power into taifa kingdoms after 1031. Major milestones included Toledo's recapture in 1085, the Almohad defeat at Las Navas de Tolosa in 1212, the falls of Cordoba (1236) and Seville (1248), and the final conquest of Granada in 1492 by Ferdinand and Isabella",
        "why": "the Reconquista forged the political identities of Spain and Portugal, established the model of religious-territorial conflict that informed the Crusades and later colonial conquests, and produced the Iberian institutional template (military orders, missionary zeal, legalized expulsions) that shaped the colonization of the Americas. Without it, the political map of southwestern Europe and Latin America would be unrecognizable",
        "vs": "the Reconquista differed from the Crusades by being domestic rather than expeditionary, gradual rather than episodic, and without a single papal authorization. It differed from the Mongol expansion by being defensive in self-image, advancing slowly over centuries through frontier skirmishes and demographic resettlement rather than sweeping cavalry conquests",
        "ex": "El Cid (Rodrigo Diaz de Vivar, c. 1043-1099) embodied the messy Reconquista frontier: he served Christian and Muslim lords alike, was exiled by Alfonso VI, and ultimately captured Valencia in 1094 to rule it as his own lord. His career illustrates that the Reconquista was as much a contest among shifting Iberian polities as a Christian-Muslim binary",
        "mis": "people see the Reconquista as 800 years of continuous war, but most decades were peaceful with stable frontiers, taxation arrangements, and trade. Another myth is that it produced a single Spanish nation; Castile and Aragon remained separate crowns under Ferdinand and Isabella, and Portugal stayed independent. The myth of unbroken religious crusade was largely a 19th-century nationalist construction",
    }

    T["the Renaissance origins"] = {
        "_cat": "history",
        "what": "the cultural and intellectual movement that began in Italian city-states in the 14th century and spread across Europe through the 17th, characterized by renewed engagement with classical antiquity, humanist scholarship, perspective in art, and a shift toward observational science and individual achievement",
        "how": "Italian merchant wealth (especially in Florence, Venice, and Genoa), the patronage of families like the Medici, the influx of Greek scholars after the fall of Constantinople in 1453, the recovery of classical Latin and Greek texts in monastic libraries, and the printing press after 1450 combined to reshape education and arts. Humanist scholars privileged grammar, rhetoric, history, poetry, and moral philosophy over scholastic logic",
        "why": "the Renaissance reframed European intellectual life and laid foundations for the Scientific Revolution, the Reformation, and modern individualism. It produced Leonardo, Michelangelo, Raphael, Galileo, Erasmus, and Shakespeare. The institutions of secular education, the public art market, and the modern self-conception as historically situated all trace to Renaissance roots",
        "vs": "the Renaissance differs from the medieval period by privileging classical models over scholastic theology and pagan antiquity over biblical authority for many cultural questions. It differs from the Enlightenment by remaining religious in worldview while rebalancing toward human concerns. Compared to other revivals (Carolingian, Twelfth-Century Renaissance), it was deeper, broader, and more enduring",
        "ex": "Brunelleschi's 1418-1436 construction of the dome of Florence Cathedral combined classical proportions, mathematical analysis of forces, and innovative engineering (a herringbone brick pattern, cleverly designed scaffolding) to span 42 meters without a wooden centering frame, a feat unmatched since antiquity. The dome is the architectural emblem of the Renaissance synthesis of art, mathematics, and engineering",
        "mis": "people see the Middle Ages as a dark age the Renaissance rescued; the medieval period had its own flowering (Gothic cathedrals, scholasticism, agricultural and economic transformation). Another myth is that the Renaissance was secular; most patrons and topics remained religious, but the framing and techniques shifted",
    }

    T["the Hanseatic League"] = {
        "_cat": "history",
        "what": "a confederation of merchant guilds and market towns that dominated maritime trade in the North Sea, the Baltic, and the rivers of Northern Europe from the 13th to the 17th century, peaking in the 14th and 15th. At its height it included around 200 towns from Bruges to Novgorod",
        "how": "the League negotiated trade privileges, maintained shared warehouses (kontors) in foreign cities like London's Steelyard and Bergen's Bryggen, standardized weights and dispute resolution, defended sea lanes against pirates, and could collectively wage war and embargo. Decisions were made at periodic Hanseatic Diets at Lubeck, with cooperation generally enforced by mutual interest rather than formal hierarchy",
        "why": "the League pioneered transnational commercial institutions and a private legal order well before modern states. It moved bulk goods (Baltic grain, Russian furs, Scandinavian fish, Flemish cloth, English wool) across Northern Europe, knit together the post-Carolingian economic geography, and connected Russia to Western markets. Its decline tracked the rise of national states with their own mercantile ambitions",
        "vs": "the League differed from city-states like Venice or Genoa by being a network spread across a vast area rather than a single polity. It differed from feudal political institutions by being commercial, pragmatic, and primarily urban. Compared to Italian merchant republics, the Hansa traded bulk staples rather than luxuries and operated by consensus among more equal members",
        "ex": "the kontor at Novgorod, called Peterhof, allowed Hanseatic merchants to live in a walled compound trading German manufactures and West European cloth for Russian furs, wax, and honey. Strict rules required Hansa traders to use Hanseatic ships, employ Hanseatic apprentices, and avoid intermarriage. The compound functioned as an enclave of Lubeck commercial law in Russian territory",
        "mis": "people imagine the Hansa as a unified state, but it was a flexible commercial network without a king, capital, or permanent army; member towns chose involvement opportunistically. Another myth is that it died abruptly; the League slowly faded over the 16th and 17th centuries as Dutch and English shippers and the Thirty Years' War undermined its position",
    }

    T["the Black Death's social impact"] = {
        "_cat": "history",
        "what": "the demographic and societal aftermath of the bubonic plague pandemic that swept Eurasia from roughly 1346 to 1353, killing an estimated 30 to 60 percent of Europe's population (perhaps 75 to 200 million globally) and triggering systemic upheaval in labor, religion, family, and politics",
        "how": "with peasant population collapsed, surviving laborers commanded higher wages, eroding feudal labor obligations and triggering attempts to legislate wage caps (England's Statute of Labourers 1351, France's Ordonnance of 1351). Vacant tenancies allowed peasant remarriage and consolidation. Towns lost workforces; trade routes shifted. Religious life saw flagellant movements, anti-Jewish pogroms, and crises of papal authority",
        "why": "the Black Death is the cleanest large-scale demographic shock in European history and a natural experiment in how plague reshaped institutions. Many historians link it to the long-term decline of serfdom, the strengthening of peasant economic position, the diversification of late-medieval art (memento mori, danse macabre), and even ultimately to Reformation-era questioning of clerical authority",
        "vs": "the Black Death's impact differs from earlier plagues (Justinian) by hitting more populated and economically integrated societies. It differs from later epidemics (smallpox in the Americas) in that European societies recovered demographically over a century with their institutions evolving rather than collapsing. Compared to wars, it killed without distinction of class, exposing limits of feudal protection",
        "ex": "the English Peasants' Revolt of 1381 was rooted in post-plague labor politics. With wages constrained by law and a poll tax adding insult, peasants and craftsmen marched on London demanding abolition of serfdom. Although crushed militarily, the revolt accelerated the trend away from servile tenure; serfdom was effectively gone in England by 1500",
        "mis": "people think the Black Death simply equals 'plague' and was a one-time disaster; recurrent waves followed for three centuries, and the long-term institutional changes accumulated across these waves. Another myth is that it killed exactly one-third; mortality varied widely by region, with some areas losing over half and a few isolated zones largely spared",
    }

    T["the Hundred Years' War"] = {
        "_cat": "history",
        "what": "the intermittent series of conflicts between the kingdoms of England and France from 1337 to 1453, fought over English claims to the French crown, control of southwestern France (Aquitaine and Gascony), and Flemish trade. The war lasted 116 years and reshaped the political and military structures of both nations",
        "how": "early English victories at Crecy (1346), Poitiers (1356), and Agincourt (1415) showcased the English longbow against French heavy cavalry. The Treaty of Troyes (1420) recognized Henry V as heir to France. Joan of Arc's intervention at Orleans in 1429 reversed the tide. By 1453 the French had reclaimed all English-held territory except Calais. Both sides pioneered military reforms: standing armies, gunpowder artillery, and centralized taxation",
        "why": "the war forged English and French national identities, displaced feudal levies with paid professional armies, and triggered tax-and-bureaucracy state-building. France emerged with a stronger monarchy and territorial integrity; England turned away from continental ambitions toward maritime expansion and parliamentary politics. The war's economic strains contributed to the Wars of the Roses and to French royal centralization under Louis XI",
        "vs": "the Hundred Years' War differed from earlier dynastic wars by its scale, duration, and use of national identity rhetoric on both sides. It differed from later European wars by retaining feudal claims as casus belli even as the means of warfare modernized. Compared to the Crusades, it was secular and inheritable rather than religious and itinerant",
        "ex": "the Battle of Agincourt on 25 October 1415 saw an outnumbered, exhausted English army under Henry V annihilate a far larger French force in a few hours. English longbowmen positioned in muddy terrain decimated French cavalry charges; subsequent slaughter of high-status French prisoners (a controversial decision Henry justified on tactical grounds) symbolized the fading age of chivalric ransom warfare",
        "mis": "people imagine the war as continuous; it was punctuated by long truces and treaties, with active campaigning in roughly half the years. Another myth is that the longbow won the war single-handedly; longbows were decisive in major battles, but French recovery came from administrative reforms, gunpowder artillery in siege warfare, and political consolidation rather than weapon parity",
    }

    T["the Khmer Empire"] = {
        "_cat": "history",
        "what": "the Southeast Asian empire centered on present-day Cambodia that flourished from 802 to 1431 CE, dominating mainland Southeast Asia at its peak under Suryavarman II and Jayavarman VII. Its capital Angkor was one of the world's largest preindustrial cities, with sophisticated water management and monumental temple architecture",
        "how": "the empire rose by uniting earlier polities, extracting agricultural surplus from rice paddies fed by enormous reservoirs (barays) and irrigation networks, and projecting power through warfare and tributary relationships across modern Thailand, Laos, southern Vietnam, and parts of Malaysia. Hindu and later Mahayana Buddhist temple-building legitimized kings and concentrated labor and wealth into religious infrastructure",
        "why": "the Khmer Empire shaped Southeast Asian art, architecture, language, religion, and political culture. Angkor Wat remains an icon of Cambodian identity, depicted on the national flag. Khmer-derived institutions and aesthetics influenced Thai, Lao, and to some extent Vietnamese cultures. The hydraulic engineering at Angkor remains an object of study for resilience and collapse research",
        "vs": "the Khmer Empire differed from contemporaneous Chinese empires by being smaller and less bureaucratic, more dependent on charismatic kingship and temple economies. It differed from the later Thai kingdoms that succeeded it by retaining a more elaborate Hindu-Buddhist royal cult. Compared to the Indus or Maya, its water-management infrastructure surpassed both in scale and complexity",
        "ex": "Angkor Wat, built under Suryavarman II in the early 12th century as a Hindu temple to Vishnu, covers 162 hectares and is the largest religious monument in the world. Its bas-reliefs, stretching nearly a kilometer, depict the Mahabharata, the Ramayana, and the Churning of the Ocean of Milk, demonstrating deep absorption of Indian epic and cosmological traditions",
        "mis": "people think Angkor was abandoned suddenly; archaeological evidence shows a gradual decline over centuries, with droughts, sack by Ayutthaya in 1431, and shifting trade routes contributing. Another myth is that the Khmer Empire was always Hindu; later kings like Jayavarman VII converted to Mahayana Buddhism, leaving Buddhist temples like the Bayon",
    }

    T["the rise of the Ottoman Empire"] = {
        "_cat": "history",
        "what": "the emergence and rapid expansion of the Ottoman Turkish state from a small Anatolian beylik around 1300 into a major Eurasian empire by the late 15th century, capturing Constantinople in 1453 and extending across the Balkans, Anatolia, the Levant, Egypt, and the Hijaz by the early 16th century",
        "how": "early Ottomans exploited the weakness of the Byzantine Empire and Anatolian Seljuk successor states, recruiting Turkmen warriors, Christian renegades, and conquered subjects into a meritocratic military and administrative system. The Janissary corps, formed by the devshirme (a child-levy from Christian Balkan villages), created an elite slave-soldier force loyal to the sultan. Gunpowder artillery breached Constantinople's walls. Tax-farming and land-grant (timar) systems funded permanent forces",
        "why": "the Ottoman rise ended the Byzantine Empire after over a thousand years, dominated southeast European geopolitics for four centuries, blocked European overland routes to Asia (motivating Atlantic exploration), and created the religious-political framework that shaped the modern Middle East. The Eastern Question of the 19th century and many present-day Balkan and Levantine borders are direct Ottoman legacies",
        "vs": "the Ottomans differed from earlier Turkic states (Seljuks, Timurids) by building a durable bureaucratic state rather than a personal conquest realm. They differed from contemporaneous European monarchies by integrating diverse millets (religious communities) under Islamic law with significant communal autonomy. Compared to the Mongols, they sustained their reach through institutional depth rather than purely military mobility",
        "ex": "the conquest of Constantinople by Mehmed II on 29 May 1453 used massive bombards (one cast by the Hungarian engineer Orban with a 250-kilogram cannonball) to breach Theodosian walls that had held for a millennium. Mehmed's engineering of overland ship transport into the Golden Horn outflanked the Byzantine chain defenses, sealing the city's fate",
        "mis": "people picture the Ottomans as monolithically Turkish and Muslim; the empire was multilingual and multi-religious, with Greek, Slavic, Armenian, Arab, Jewish, and Albanian populations under varying degrees of communal autonomy. Another myth is rapid decline after 1683; the empire endured another 240 years and engaged in significant 19th-century reforms before its dissolution after WWI",
    }

    T["the rise of Mesopotamian city-states"] = {
        "_cat": "history",
        "what": "the emergence of the world's first urban civilizations in the alluvial plains between the Tigris and Euphrates rivers from roughly 4500 to 2300 BCE, beginning with Sumerian cities like Uruk, Ur, Eridu, Lagash, and Nippur, which produced cuneiform writing, codified law, monumental temples, and the earliest verified bureaucracies",
        "how": "irrigation agriculture supported population densities far above subsistence, requiring coordination of canal-building, dispute resolution, and surplus management. Temples (ziggurats) functioned as economic centers, accumulating tithes and managing agricultural land. The urgent record-keeping needs drove the invention of cuneiform on clay tablets around 3200 BCE in Uruk. Kings legitimized their rule through divine sponsorship and monumental works",
        "why": "Mesopotamia is where urbanism, writing, professional bureaucracy, large-scale public construction, codified law (Ur-Nammu, Hammurabi), and many features of organized religion first emerge in the historical record. Subsequent civilizations from Egypt to Greece to the Levant were shaped by Mesopotamian innovations transmitted through trade, conquest, and emulation",
        "vs": "Mesopotamian city-states differ from contemporaneous Egyptian civilization by their political fragmentation: rather than one Nile-spanning kingdom, the river plain held many rival cities. They differ from later empires (Akkadian, Babylonian, Assyrian) by being autonomous polities rather than imperial subjects. Compared to Indus cities, they show more elaborate religious and royal iconography",
        "ex": "Uruk in 3200 BCE had perhaps 40,000 to 80,000 residents within massive walls (later legend attributed them to Gilgamesh), the earliest large temples, and the first fully developed cuneiform tablets recording rations, ownership, and brewery accounts. The administrative workload alone required hundreds of literate scribes, evidence of full-time specialization",
        "mis": "people think Mesopotamia was always a single empire; for most of the third millennium BCE it was a patchwork of competing cities, only sporadically unified under figures like Sargon of Akkad. Another myth is that Sumerian cities were small; some had populations larger than most European cities had until the medieval period",
    }

    T["the spread of Buddhism along the Silk Road"] = {
        "_cat": "history",
        "what": "the diffusion of Buddhism from its Indian birthplace across Central Asia, China, Korea, Japan, and Southeast Asia between roughly the 1st century BCE and the 8th century CE, carried by missionaries, monks, and merchants along the overland and maritime trade routes collectively called the Silk Road",
        "how": "Buddhism was patronized by the Kushan Empire (1st-3rd centuries CE) in present-day Pakistan and Afghanistan, where Greco-Buddhist art combined Hellenistic and Indian aesthetics. Translators like Kumarajiva (4th-5th c.) rendered sutras into Chinese, while Chinese pilgrims like Faxian and Xuanzang journeyed to India for original texts. Royal patronage in China (Northern Wei, Tang), Korea, and Japan spread monastic Buddhism eastward, while maritime routes carried it to Sri Lanka and Southeast Asia",
        "why": "the spread reshaped the religious, philosophical, artistic, and political fabric of half a continent. East Asian civilizations absorbed Buddhist conceptions of compassion, rebirth, and monasticism into their existing Confucian, Daoist, and Shinto traditions. Buddhist art forms, temple architecture, printing technology (used to reproduce sutras), and ethical discourse all owe substantial debts to Silk Road transmission",
        "vs": "the spread of Buddhism along the Silk Road differs from later missionary religions like Christianity and Islam by being decentralized and largely peaceful, expanding through patronage and persuasion rather than conquest. It differs from the spread of Hinduism, which remained mostly within South Asia, in achieving genuine continental reach. Compared to Manichaeism, which also spread along the Silk Road, Buddhism rooted itself permanently in receiving cultures",
        "ex": "the Mogao Caves at Dunhuang, in northwestern China at a Silk Road junction, contain over 700 caves of Buddhist murals, sculptures, and manuscripts created from the 4th to 14th centuries. The Library Cave's hoard of texts in Sanskrit, Chinese, Tibetan, Sogdian, and Uighur (rediscovered in 1900) documents the multilingual Silk Road Buddhist world directly",
        "mis": "people think Buddhism reached China overnight; transmission was gradual over centuries, with translation, doctrinal misunderstandings, and adaptation to Chinese sensibilities producing distinctive schools (Chan, Pure Land). Another myth is that Buddhism remained pure in transmission; each receiving culture reshaped doctrines, iconography, and practices, producing the diverse traditions we see today",
    }

    T["the Ming dynasty's maritime expeditions"] = {
        "_cat": "history",
        "what": "seven vast naval voyages led by the eunuch admiral Zheng He between 1405 and 1433, sponsored by the Yongle and Xuande emperors of the Chinese Ming dynasty. The fleets visited Southeast Asia, the Indian subcontinent, the Persian Gulf, the Arabian Peninsula, and the East African coast as far as present-day Kenya",
        "how": "Zheng He commanded fleets of up to 300 ships and 27,000 men, with treasure ships rumored to exceed 120 meters in length. The expeditions traded silk, porcelain, and lacquerware for spices, ivory, gemstones, exotic animals (including a giraffe), and tribute from foreign rulers brought back to China for diplomatic ceremonies. They projected Ming prestige rather than seizing territory",
        "why": "the voyages demonstrated Chinese maritime capabilities that exceeded contemporary European fleets by an order of magnitude. They established temporary tributary networks across the Indian Ocean, gathered geographical and ethnographic knowledge, and shaped subsequent overseas Chinese diaspora communities in places like Malacca. Their abrupt termination is a recurring case study in why technological supremacy does not guarantee continued global engagement",
        "vs": "the Ming voyages differ from later European voyages of exploration by being state-sponsored, diplomatic rather than commercial in primary purpose, and not aimed at colonial conquest. They differ from earlier Song-era maritime trade by their scale and political symbolism. Compared to private merchant networks in the Indian Ocean, the expeditions imposed Ming hegemony temporarily without permanent occupation",
        "ex": "in 1414 Zheng He's fleet brought a giraffe from Bengal (originally from East Africa) to the Yongle emperor, who interpreted it as a qilin, an auspicious mythological creature whose appearance signaled a sage ruler. The episode illustrates how the voyages folded foreign novelties into Chinese cosmological symbolism while documenting actual long-distance contact",
        "mis": "people credit Zheng He with discovering the Americas (Gavin Menzies' speculative theory); no credible evidence supports this, and Ming records show the fleets focused on the Indian Ocean. Another myth is that the voyages ended due to backwardness; they ended because Confucian scholar-officials saw them as fiscally wasteful and rejected the eunuch-led project for ideological reasons",
    }

    T["the Reformation"] = {
        "_cat": "history",
        "what": "the religious upheaval of 16th-century Europe that produced Protestant Christianity by breaking with papal authority. Conventionally dated from Martin Luther's 95 Theses in 1517 against indulgences, the movement spread rapidly through Lutheran, Reformed (Calvinist), Anglican, and radical (Anabaptist) traditions, ending centuries of Western Christian religious unity",
        "how": "printed pamphlets, vernacular Bibles, and disputations let reformers like Luther, Zwingli, Calvin, and the English authorities reach mass audiences quickly. Princely conversion (Saxony, Hesse, Sweden, England) gave political protection. The Peace of Augsburg (1555) recognized cuius regio, eius religio, letting rulers choose. The Catholic Counter-Reformation responded with the Council of Trent (1545-1563), the Jesuits, and clarified doctrine and discipline",
        "why": "the Reformation broke the unity of Western Christianity, fueled the Wars of Religion (culminating in the Thirty Years' War), reshaped European politics by tying confession to sovereignty, and indirectly contributed to literacy (Bible reading), individualism, and capitalism (Weber's Protestant ethic thesis). It also opened space for religious pluralism that eventually became the basis of toleration in liberal political theory",
        "vs": "the Reformation differs from earlier reform movements (Wycliffe, Hus, conciliarism) by succeeding institutionally and creating durable parallel churches. It differs from the Renaissance, with which it overlapped, by emphasizing scriptural authority over classical recovery. Compared to schisms like East-West (1054), the Reformation produced multiple competing Protestant churches rather than a single rival",
        "ex": "Luther's translation of the New Testament from Greek into German (1522) and the full Bible (1534) used a written form of Saxon dialect that became standard High German, just as the King James Version (1611) shaped English. By making scripture accessible without clerical mediation, these translations operationalized the doctrine of sola scriptura and reshaped European literacy",
        "mis": "people think Luther wanted to start a new church; he initially sought reform within Catholicism, with the break solidifying only after his excommunication in 1521. Another myth is that the Reformation was theologically uniform; Lutherans, Calvinists, and Anabaptists fought each other on sacraments, predestination, and political authority almost as bitterly as they fought Rome",
    }

    T["the Scientific Revolution"] = {
        "_cat": "history",
        "what": "the transformation of European understanding of the natural world from roughly 1543 (Copernicus' De revolutionibus) to 1687 (Newton's Principia), in which experimental method, mathematical description, and mechanistic explanation displaced Aristotelian-scholastic natural philosophy as the dominant framework for inquiry",
        "how": "Copernicus proposed heliocentrism on mathematical-aesthetic grounds; Galileo combined telescopic observation with mathematical mechanics; Kepler derived planetary laws from Tycho Brahe's data; Descartes pushed mechanistic explanation; Bacon and Boyle articulated experimental method; Newton synthesized terrestrial and celestial mechanics under universal gravitation. New institutions (the Royal Society 1660, Academie des Sciences 1666) and journals routinized communication of results",
        "why": "the Revolution established the conceptual and methodological foundations of modern science: hypothesis, controlled experiment, mathematical modeling, peer-reviewed dissemination, and confidence in mechanical causation. Its successes underwrote the Industrial Revolution and reshaped Western philosophy, theology, and politics by suggesting that human reason could decode nature without ecclesiastical guidance",
        "vs": "the Scientific Revolution differs from medieval natural philosophy by privileging mathematical demonstration and controlled experiment over Aristotelian categorization and authority. It differs from later 19th-century professionalization of science by being conducted largely by gentleman amateurs and patronized scholars. Compared to the contemporary Renaissance, it focused on mechanism and prediction rather than recovery of classical learning",
        "ex": "Newton's Principia Mathematica (1687) demonstrated that the same inverse-square gravitational force governing falling apples on Earth governed the Moon's orbit and the orbits of all planets, unifying terrestrial and celestial mechanics under three laws of motion plus universal gravitation. The book's structure (axioms, propositions, proofs) deliberately echoed Euclid, signaling its claim to deductive certainty",
        "mis": "people see a sharp break with the past; many revolutionary figures (Copernicus, Newton, Kepler) retained substantial medieval and theological commitments and saw their work as illuminating divine creation. Another myth is that the Revolution proved the Catholic Church wrong on Galileo's heliocentrism in his lifetime; the Galileo trial was theological-political, and full vindication came centuries later",
    }

    T["the Enlightenment"] = {
        "_cat": "history",
        "what": "the 18th-century intellectual movement, especially in France, Britain, the German states, and the American colonies, that emphasized reason, empirical inquiry, individual rights, religious toleration, and critique of traditional authority. Major figures include Locke, Voltaire, Rousseau, Hume, Kant, Diderot, Smith, Jefferson, and Madison",
        "how": "Enlightenment thinkers operated through salons, coffee houses, learned societies, and a transnational republic of letters circulating books, pamphlets, and journals. Diderot and d'Alembert's Encyclopedie (1751-1772) systematized knowledge and embedded skeptical perspectives. Constitutional experiments, especially in revolutionary America and France, translated philosophical principles into political practice",
        "why": "the Enlightenment reshaped political theory (consent of the governed, separation of powers, natural rights), economics (Smith's market analysis), epistemology (Kant's critique of pure reason), and religion (deism, toleration). The U.S. Constitution, the French Declaration of the Rights of Man, modern liberalism, and human rights discourse all draw heavily on Enlightenment thought",
        "vs": "the Enlightenment differs from the Scientific Revolution by extending rational critique from nature to society, religion, and politics. It differs from the Renaissance by privileging reason and progress over classical recovery. Compared to the Romantic reaction that followed, it championed universalism, abstract reason, and progress where Romantics emphasized particularity, emotion, and tradition",
        "ex": "Locke's Two Treatises of Government (1689) argued that legitimate political authority rests on consent of the governed and that rulers who violate natural rights to life, liberty, and property may justifiably be replaced. Jefferson's Declaration of Independence (1776) translated Locke's framework almost directly into the founding charter of a new nation, illustrating Enlightenment ideas in concrete political action",
        "mis": "people imagine the Enlightenment as uniformly secular and anti-religious; many thinkers (Locke, Newton, Kant) were religious, advocating critique within rather than against faith. Another myth is that it was monolithic; Voltaire's anticlericalism, Rousseau's communitarianism, Hume's skepticism, and Kant's idealism are deeply different and frequently in tension",
    }

    T["the Spanish Civil War"] = {
        "_cat": "history",
        "what": "the 1936-1939 conflict between the Republican government of Spain (loyalists, including liberals, socialists, communists, anarchists) and Nationalist rebels led by General Francisco Franco. The Nationalists won, establishing Franco's dictatorship until his death in 1975",
        "how": "the war began with a partial military coup in July 1936 that failed to seize the country quickly. Nazi Germany and Fascist Italy supplied Franco with troops, aircraft (the Condor Legion), and material; the Soviet Union and the International Brigades supported the Republic; the Western democracies pursued a non-intervention policy that disadvantaged the Republic. Franco's slow grinding advance, combined with Republican infighting between communists and anarchists, sealed the outcome by 1939",
        "why": "the war was the first major battlefield of the broader European struggle between fascism, liberal democracy, and communism, foreshadowing World War II and demonstrating the lethality of strategic aerial bombing on civilians (Guernica). It produced foundational works of journalism (Orwell's Homage to Catalonia), photography (Capa), and art (Picasso's Guernica). Its long shadow shaped Spain's politics and historical memory into the 21st century",
        "vs": "the Spanish Civil War differs from a simple coup by becoming a three-year national conflict with foreign intervention. It differs from later ideological proxy wars (Korea, Vietnam) by being fought within Western Europe with explicitly democratic stakes. Compared to the Russian Civil War, it was shorter and the rebels rather than the establishment faction prevailed",
        "ex": "the bombing of the Basque town of Guernica on 26 April 1937 by the German Condor Legion at the request of Franco's forces destroyed the town and killed hundreds of civilians. Picasso's mural Guernica, painted within months for the Spanish Pavilion at the Paris World's Fair, made the atrocity an enduring symbol of indiscriminate aerial bombardment and inspired international outrage",
        "mis": "people see the war as a clean democracy-vs-fascism contest; the Republican side included revolutionary anarchists in Catalonia and Stalin-aligned communists who repressed rivals, complicating the moral picture. Another myth is that non-intervention was neutral; in practice it benefited the Nationalists, who received steady Axis support, while the Republic's Soviet aid was sporadic",
    }

    T["the Korean War"] = {
        "_cat": "history",
        "what": "the 1950-1953 conflict between North Korea (supported by China and the Soviet Union) and South Korea (supported by a U.S.-led United Nations coalition of 21 countries). Triggered by North Korea's invasion across the 38th parallel on 25 June 1950, the war ended in armistice with the peninsula divided roughly along the original line, technically still without a formal peace treaty",
        "how": "North Korean forces overran most of the South within weeks. MacArthur's Inchon landing (15 September 1950) reversed the tide; UN forces drove deep into the North. Chinese intervention in late October 1950 pushed UN forces back south of Seoul. The war then became a brutal stalemate along the 38th parallel for two years of trench warfare and aerial bombing. Negotiations dragged through 1951-1953, signing an armistice on 27 July 1953",
        "why": "the Korean War was the first hot war of the Cold War, set the precedent for limited UN-sponsored intervention, hardened the U.S.-Soviet rivalry, drove militarization of the U.S. economy and global posture (NSC-68 became operational), and established the Korean peninsula's enduring division. North and South Korea remain technically at war today, with profound geopolitical consequences for East Asia",
        "vs": "the Korean War differs from World War II in being a limited regional conflict deliberately constrained from escalating to nuclear use, despite MacArthur's recommendations. It differs from Vietnam by ending in stalemate rather than U.S. withdrawal under domestic pressure. Compared to other Cold War flashpoints (Berlin, Cuba), it was the only one to escalate to large-scale conventional combat",
        "ex": "the Inchon landing on 15 September 1950 was a high-risk amphibious operation against extreme tides and well-defended approaches that succeeded brilliantly, cutting North Korean supply lines and recapturing Seoul within weeks. It rescued the Pusan perimeter and showcased combined-arms naval-air-land operations, becoming a textbook study in operational art",
        "mis": "people call it the Forgotten War in the U.S., underestimating its scale: roughly 36,000 American dead, hundreds of thousands of South Korean military casualties, and an estimated 2-3 million Korean civilian dead north and south. Another myth is that it ended; only an armistice was signed, and tensions continue with periodic confrontations along the demilitarized zone",
    }

    T["the founding of the United Nations"] = {
        "_cat": "history",
        "what": "the establishment of the United Nations on 24 October 1945 with the entry into force of the UN Charter, signed at the San Francisco Conference earlier that year by 50 founding member states. The UN replaced the discredited League of Nations and aimed to prevent another world war through collective security, diplomacy, and cooperation",
        "how": "the Charter created the General Assembly (one state, one vote), the Security Council (five permanent members with veto: U.S., USSR, UK, France, China; ten elected non-permanent), the Secretariat under a Secretary-General, the Economic and Social Council, and the International Court of Justice. The Universal Declaration of Human Rights followed in 1948. Subsequent decades added specialized agencies (WHO, UNICEF, UNESCO) and peacekeeping operations",
        "why": "the UN institutionalized global cooperation on peace, human rights, development, and humanitarian relief. It legitimized decolonization (membership grew from 51 in 1945 to 193 today), provided forums for diplomacy across Cold War and post-Cold War divides, and codified international law (Genocide Convention, Refugee Convention, Law of the Sea). Critics emphasize its constraints; defenders note that the absence of WWIII is partly its achievement",
        "vs": "the UN differs from the League of Nations by including all major powers, having enforcement teeth (Security Council military authorization), and broader humanitarian and developmental mandates. It differs from regional bodies (EU, AU, ASEAN) by global scope. Compared to bilateral diplomacy, the UN provides standing institutions and norms rather than ad hoc agreements",
        "ex": "the 1948 Universal Declaration of Human Rights, drafted by a committee chaired by Eleanor Roosevelt, articulates 30 articles covering civil, political, economic, social, and cultural rights as universal and indivisible. Though non-binding, it has shaped national constitutions, international treaties, and human rights discourse worldwide for over seven decades",
        "mis": "people expect the UN to be a world government; it is a forum and coordinator of sovereign states with no independent military or revenue, dependent on members for both. Another myth is that the Security Council veto is a flaw; it is a deliberate feature accepting that great-power consent is necessary for enforcement, the lesson of the League's failure",
    }

    T["the abolition of slavery"] = {
        "_cat": "history",
        "what": "the long process by which slavery was legally ended across most of the world from the late 18th century through the 20th, beginning with abolition in revolutionary France (1794, restored briefly), Haiti (1804), the British Empire (1833), the United States (1865 by 13th Amendment), Brazil (1888), and continuing with anti-slavery treaties through the 20th century. Slavery in some form persists in residual and trafficking forms today",
        "how": "abolition combined moral-religious campaigning (Quakers, evangelical Protestants), legal challenge (Somerset case, 1772, in England), revolutionary upheaval (Haitian Revolution), economic shifts (industrialization reducing slavery's relative profitability in some regions but not all), war (the U.S. Civil War, 1861-1865), and international diplomacy (the 1815 Congress of Vienna's anti-slave-trade declaration, the 1885 Berlin Conference's anti-slavery clauses)",
        "why": "abolition was the largest single moral-political reform in human history, ending an institution older than written records and central to many economies. It triggered massive demographic, economic, and political transformations: emancipation in the U.S. South, post-emancipation labor regimes (sharecropping, indenture, peonage), the long civil rights struggle, and continued reckoning with slavery's legacies in modern racial inequality",
        "vs": "abolition differs from earlier manumissions, which freed individuals while preserving the institution, by ending slavery as a legal category. It differs across regions: peaceful and compensated in much of the British Empire, violent and uncompensated in the U.S., gradual through ameliorative laws in Brazil. Compared to serfdom abolition (Russia 1861), it spanned multiple continents and races and produced longer struggles for substantive freedom",
        "ex": "the British Slavery Abolition Act of 1833 freed roughly 800,000 enslaved people across the British Empire (excluding the East India Company territories initially) effective 1834, with formerly enslaved people forced to serve as apprentices for several years and slaveholders compensated 20 million pounds (about 40% of the Treasury's annual budget). The compensation was paid to slaveholders, not the enslaved, a fact that has resurfaced in modern reparations debates",
        "mis": "people think abolition immediately produced freedom and equality; emancipation typically led to indenture, sharecropping, peonage, vagrancy laws, or other coercive labor regimes for decades. Another myth is that abolition was driven primarily by economic obsolescence; slavery was profitable in many cases (cotton in the U.S. South was booming in 1860), and moral and political agitation drove the change",
    }

    # ===== ARTS & HUMANITIES =====

    T["the hero's journey"] = {
        "_cat": "arts_and_humanities",
        "what": "a narrative pattern identified by mythologist Joseph Campbell in The Hero with a Thousand Faces (1949), describing a recurrent structure in myths and stories across cultures. The hero leaves the ordinary world, undergoes trials in a special world, and returns transformed with knowledge or a boon for their community",
        "how": "Campbell's monomyth has 17 stages, often condensed to three acts: Departure (call to adventure, refusal, mentor, crossing the threshold), Initiation (tests, allies, enemies, supreme ordeal, reward), and Return (refusal of return, the magic flight, master of two worlds). Christopher Vogler's screenwriting adaptation shrank it to 12 steps, widely used in Hollywood story development",
        "why": "the framework is the most influential narrative analytic of the 20th century, used by Star Wars (Lucas explicitly cited Campbell), Pixar films, novels, video game design, and even self-help discourse. It gives writers a structural toolkit and audiences a sense of mythic resonance, even when the story is otherwise mundane",
        "vs": "the hero's journey differs from Aristotle's three-act structure by adding the symbolic separation-initiation-return pattern from comparative mythology. It differs from Vladimir Propp's Russian folktale morphology by emphasizing psychological transformation rather than functional plot moves. Compared to character-driven literary fiction, it foregrounds external action and symbolic stages",
        "ex": "Star Wars: Luke Skywalker living mundanely on Tatooine (ordinary world), receiving R2-D2's message (call), refusing initially, meeting Obi-Wan (mentor), leaving the planet (crossing the threshold), trials with the Empire (initiation), the Death Star battle (supreme ordeal), and returning to the Rebel base (return with elixir). Each of the original trilogy's three films traces a recognizable Campbellian arc",
        "mis": "people treat the journey as universal; many literary traditions (Japanese mono no aware, much of postmodern fiction, ensemble narratives) do not fit. Another myth is that following the structure guarantees a good story; many mediocre Hollywood films check every Campbellian box. The structure is descriptive, not prescriptive in any deep way",
    }

    T["unreliable narrators"] = {
        "_cat": "arts_and_humanities",
        "what": "a literary device in which the narrator's credibility is compromised, requiring readers to question their account of events. The unreliability may stem from limited knowledge, deception, mental illness, naivete, self-interest, or memory failure, and is typically signaled through inconsistencies the reader detects",
        "how": "writers create unreliability through internal contradictions, gaps that other characters fill differently, irony between narration and depicted events, stylistic markers (childlike syntax, evasions, defensive rhetoric), and reveal scenes that reframe earlier passages. The reader must do interpretive work to triangulate what actually happened, becoming an active participant in the text",
        "why": "unreliable narration produces dramatic irony, psychological depth, and engagement that straightforward narration cannot. It also raises epistemological questions about narrative truth, perspective, and the social construction of reality, making it central to modernist and postmodern fiction. Films and television (Fight Club, Rashomon, Mr. Robot) have widely adopted the technique",
        "vs": "an unreliable narrator differs from a third-person limited narrator with imperfect knowledge by being intentionally or psychologically distorted rather than just incomplete. It differs from a deceptive omniscient narrator (rare and structurally different) by embedding bias inside a character. Compared to multiple-narrator novels, unreliable narration concentrates the interpretive challenge in one voice",
        "ex": "Kazuo Ishiguro's The Remains of the Day uses Stevens, an English butler whose punctilious narrative style and deflections gradually reveal his self-deception about his employer's Nazi sympathies and his own unfulfilled love. The reader sees what Stevens cannot quite let himself see, producing the novel's quiet devastation through that very gap",
        "mis": "people think any first-person narrator is unreliable; only narrators whose distortion is significant and structurally important count. Another myth is that unreliable narration always involves a 'twist'; many of the best unreliable narrators (Stevens, Holden Caulfield, Humbert Humbert) reveal themselves through gradual accretion rather than a single shock revelation",
    }

    T["stream of consciousness"] = {
        "_cat": "arts_and_humanities",
        "what": "a narrative technique that depicts the multitudinous flow of thoughts, sensations, and impressions in a character's mind, often without conventional grammar, punctuation, or temporal order. The term originated with William James and was applied to literature notably for Joyce, Woolf, and Faulkner",
        "how": "techniques include free association, sentence fragments running into each other, internal monologue without quotation marks, abrupt shifts in time and focus, and integration of sensory and imaginative content. Punctuation may be reduced or eliminated; syntax may compress to follow thought rhythms rather than expository clarity",
        "why": "stream of consciousness aims to render subjective experience with greater fidelity than traditional realism, which presents thought as orderly and sequential. It expanded the novel's expressive range, opened psychological interiority for serious literary attention, and influenced film (montage, voiceover) and contemporary poetry. Modernism's distinctive textures owe much to it",
        "vs": "stream of consciousness differs from interior monologue (a related but tighter form with more grammatical structure) by being looser and more impressionistic. It differs from third-person narration with deep psychological access by abandoning the narrator's organizing presence. Compared to direct dialogue, it surfaces the unspoken and pre-verbal substrate of thought",
        "ex": "the closing Penelope chapter of Joyce's Ulysses presents Molly Bloom's thoughts in eight enormous unpunctuated sentences spanning forty pages, capturing memory, desire, irritation, and reverie as they actually flow before language disciplines them. The final Yes I said yes I will Yes resolves the day and the novel in a single rhythmic surge",
        "mis": "people think stream of consciousness is just disorganized writing; it is carefully crafted to feel disorganized while still encoding precise psychological content. Another myth is that it is always difficult; some writers (Woolf in To the Lighthouse) modulate it for clarity, while others (Faulkner in The Sound and the Fury) lean into challenge. Reading slowly and listening for voice transforms apparent obscurity",
    }

    T["magical realism"] = {
        "_cat": "arts_and_humanities",
        "what": "a literary mode in which magical or impossible events occur in an otherwise realistic narrative setting, presented matter-of-factly without narrative astonishment. The term was coined by German art critic Franz Roh in 1925 and most associated with Latin American writers like Garcia Marquez, Borges, Allende, and Carpentier",
        "how": "writers blend everyday reality with supernatural elements (ghosts, miracles, prolonged ascents), treating both with the same matter-of-fact tone. The narrative voice does not flag the magical as exceptional, requiring readers to accept it as part of the world. Cultural specificity, historical trauma, and political critique often inform the choice of which impossibilities to depict",
        "why": "magical realism gave Latin American literature global stature in the late 20th century and provided a powerful mode for narrating colonial trauma, indigenous worldviews, and political violence in ways realism cannot. It influenced authors worldwide (Rushdie's Midnight's Children, Murakami, Toni Morrison's Beloved) and is now a recognizable global literary mode",
        "vs": "magical realism differs from fantasy by being set in a recognizable real-world place rather than a secondary world. It differs from surrealism by being narratively coherent and politically engaged rather than aimed at unconscious dream-logic. Compared to gothic fiction, it presents the supernatural as woven into daily life rather than as horror or threat",
        "ex": "in Garcia Marquez's One Hundred Years of Solitude, a girl named Remedios the Beauty ascends bodily to heaven while folding sheets, and the narrative simply records this in passing alongside political events and family squabbles. Macondo's plagues of insomnia, rains lasting four years, and patriarch tied to a tree till death all coexist with bourgeois family life",
        "mis": "people equate magical realism with any fiction containing fantasy elements; the genre specifically denotes the matter-of-fact treatment within a realistic framework. Another myth is that it is exclusively Latin American; while the most famous practitioners are, the mode now spans many traditions. A third confusion is that magical events have allegorical decoded meanings; often they resist clean allegory and operate as cultural-political resonance",
    }

    T["Plato's theory of forms"] = {
        "_cat": "arts_and_humanities",
        "what": "the metaphysical doctrine, central to Plato's middle dialogues, that abstract universal Forms (or Ideas) exist independently of the changing physical world and constitute the true objects of knowledge. Particular things in the physical world participate in or imitate Forms imperfectly, and only the Forms are fully real and intelligible",
        "how": "Plato argues that physical objects change, perish, and admit of degrees, but knowledge requires unchanging objects. The Form of Beauty, of Justice, of Triangle exists eternally and unchangingly; physical instances are temporary participants. The Form of the Good is the ultimate Form, illuminating the rest as the sun illuminates the visible world (Republic Book VI). Knowledge proceeds through dialectic, ascending from particulars to Forms",
        "why": "the theory of Forms is one of the most influential philosophical proposals in history. It frames Western philosophy of universals, mathematics (Platonism in the philosophy of math holds numbers exist abstractly), theology (Augustine read Forms as ideas in the divine mind), and the perennial debate between rationalism and empiricism. Modern realism about scientific laws and abstract objects continues Platonist intuitions",
        "vs": "the theory differs from Aristotle's hylomorphism, which placed forms inside particular things rather than in a separate realm. It differs from nominalism, which denies that universals have independent reality, treating them as names for similarities. Compared to empiricism, Platonism makes mind-independent abstract reality the ground of knowledge, while empiricism builds knowledge from sensory experience",
        "ex": "consider triangles. Every drawn triangle is imperfect: the lines have width, the angles are slightly off, the pencil smudges. Yet the geometric proofs we make about triangles refer to perfectly straight lines and exact angles. The Form of Triangle is what the proofs are really about; physical triangles approximate it. Plato sees this as evidence that mathematical truth is about non-physical entities",
        "mis": "people think Forms float in space somewhere; they are not spatial at all. Another myth is that Plato's theory was monolithic; in dialogues like Parmenides he himself raised serious objections (the Third Man Argument). Aristotle's critique was so penetrating that it persuaded many of Plato's own students, an embarrassment Platonists have grappled with for 2,400 years",
    }

    T["empiricism vs rationalism"] = {
        "_cat": "arts_and_humanities",
        "what": "two opposed theories of the source and justification of knowledge in early modern philosophy. Empiricists (Locke, Berkeley, Hume) hold that knowledge derives primarily from sensory experience; rationalists (Descartes, Spinoza, Leibniz) argue that some substantial knowledge comes from reason alone, independent of experience",
        "how": "empiricists explain abstract concepts by tracing them to sense impressions, building complex ideas from simple ones (Locke's white-paper mind written on by experience). Rationalists posit innate ideas, deductive demonstration, and intuitive grasp of necessary truths (Descartes' clear and distinct ideas, Spinoza's geometric method, Leibniz's principle of sufficient reason). Each side wields characteristic arguments and counterexamples",
        "why": "the debate framed early modern epistemology and remains alive today in cognitive science (innate vs learned cognitive structures), philosophy of mathematics (Platonism vs constructivism), and AI (knowledge representation vs learning from data). Kant's synthesis aimed to integrate both: knowledge requires both sensory input and a priori cognitive structures, a position broadly inherited by modern accounts",
        "vs": "empiricism limits knowledge to what experience can support; rationalism extends it via pure reason. Empiricism is friendly to scientific method's reliance on observation and skeptical of metaphysics; rationalism is friendly to mathematics and metaphysical reasoning and skeptical of pure inductive generalization. Each side accuses the other of either trivializing knowledge or inflating it beyond justification",
        "ex": "consider 'all bachelors are unmarried.' Rationalists treat it as known a priori, true by analysis of concepts. Empiricists agree but argue it is empty (analytic), giving us no information about the world. Now consider 'every event has a cause.' Rationalists like Leibniz claim it as a necessary truth knowable by reason; Hume famously argued it is a habit of expectation, not justified a priori, illustrating the depth of disagreement over substantive principles",
        "mis": "people think the two camps were at war and one won; in reality, sophisticated empiricists granted some a priori knowledge (analytic truths), and sophisticated rationalists granted experience some role. Kant's critical philosophy made the distinction less binary by 1781. Another myth is that contemporary science is purely empiricist; mathematical theory and theoretical reasoning play indispensable rationalist-flavored roles",
    }

    T["the trolley problem"] = {
        "_cat": "arts_and_humanities",
        "what": "a thought experiment in moral philosophy posing whether to divert a runaway trolley from a track where it will kill five people onto a side track where it will kill one. Introduced by Philippa Foot in 1967 and developed by Judith Jarvis Thomson, the dilemma probes the moral significance of doing versus allowing harm and intention versus foresight",
        "how": "variations multiply: the bystander at the switch (most people say divert), the footbridge (push a large person off a bridge to stop the trolley, most refuse), the loop case, the surgeon harvesting organs from one to save five (almost universally refused). Each tweak isolates a moral consideration: physical contact, using someone as a means, foresight versus intent, doctrine of double effect",
        "why": "the trolley problem is the field's signature pump for intuitions about deontology, consequentialism, and the moral psychology underlying both. It surfaces in debates over self-driving car ethics, military targeting (collateral damage), triage in pandemics, and trolley-style policy choices in real bureaucracies. It also drove modern experimental philosophy and moral psychology by yielding cross-cultural data",
        "vs": "the trolley problem differs from broader policy ethics by simplifying away politics, knowledge uncertainty, and institutional context to isolate the moral structure. It differs from rule-based dilemmas (lying to save a life) by featuring physical action and proximate causation. Compared to virtue-ethics cases, it probes deontic intuitions rather than character",
        "ex": "in a typical study, around 90% endorse pulling the switch (sacrificing one to save five), but only 30-60% endorse pushing the large man off the footbridge despite the same body count, suggesting an intuition that using a person as a means is morally weightier than foreseen but unintended harm. Self-driving car designs grapple with whether algorithmically choosing pedestrians to spare resembles the switch case or the bridge case",
        "mis": "people think the trolley problem proves consequentialism (since most save five) or deontology (since most refuse the bridge); the experiment shows our intuitions are mixed and structurally sensitive. Another myth is that it is a useless armchair puzzle; engineers, ethicists, and policymakers grapple with structurally identical cases in autonomous-vehicle programming and triage protocols",
    }

    T["existentialism"] = {
        "_cat": "arts_and_humanities",
        "what": "a 19th-20th-century philosophical movement emphasizing individual existence, freedom, and choice. Existentialists hold that human beings define themselves through their decisions in a world without preordained meaning, and they confront anxiety, absurdity, and authenticity as fundamental conditions of existence",
        "how": "thinkers include Kierkegaard (faith and the leap), Nietzsche (will to power, eternal recurrence), Heidegger (Being and Time, Dasein, being-toward-death), Sartre (Being and Nothingness, radical freedom, bad faith), Camus (the absurd, Sisyphus), de Beauvoir (The Second Sex, ethics of ambiguity). The slogan existence precedes essence captures Sartre's claim that humans first exist and then through choice create their nature",
        "why": "existentialism shaped post-WWII European thought, theology (Tillich, Bonhoeffer, Buber), psychology (Frankl's logotherapy, May's existential psychology), literature (Beckett, Kafka), and popular discourse. It survives in everyday language (authenticity, bad faith) and in the persistent recognition that meaning is something humans make rather than discover preformed",
        "vs": "existentialism differs from earlier humanism by emphasizing radical freedom and the burden of choice rather than confidence in human reason. It differs from logical positivism by treating subjectively meaningful experience as central rather than dismissing it as cognitively meaningless. Compared to Eastern philosophies emphasizing self-emptiness, it underscores radical individuality, though dialogue between Zen and existentialism has been productive",
        "ex": "Sartre's example of bad faith: a waiter who plays his role too perfectly, denying his freedom by hiding behind the social script of waiterhood. He becomes what he does rather than recognizing he chooses to do it. The waiter could quit, change careers, refuse customers; pretending those options do not exist is the self-deception existentialists call bad faith",
        "mis": "people think existentialism preaches despair or nihilism; most existentialists insist on meaning-making despite the absence of preordained meaning. Sartre, Camus, and de Beauvoir all wrote ethical works treating freedom as the source of responsibility. Another myth is that it is just French postwar pessimism; its roots go to Kierkegaard and span theistic and atheistic, optimistic and tragic varieties",
    }

    T["the Ship of Theseus"] = {
        "_cat": "arts_and_humanities",
        "what": "an ancient thought experiment, recorded by Plutarch, asking whether the ship in which Theseus returned to Athens, with its planks gradually replaced one by one until none of the original remained, was still the same ship. Hobbes added the twist of reassembling the original planks elsewhere, asking which is the real ship",
        "how": "the puzzle exposes that 'same' is theory-dependent. Different criteria yield different answers: spatiotemporal continuity favors the gradually replaced ship; material composition favors the reassembled one; functional or memorial identity may favor either. Philosophers respond with theories like four-dimensionalism (objects are space-time worms), bundle theory (objects are bundles of properties), and pragmatic conventionalism",
        "why": "the puzzle is a stress test for theories of identity, persistence, and composition. It applies directly to organisms (your atoms turn over every few years), corporations (every employee replaced over decades), nations, brain transplants, and digital artifacts. Buddhist no-self doctrine, computational identity arguments in philosophy of mind, and legal questions about corporate continuity all engage Theseus-style problems",
        "vs": "the Ship of Theseus differs from sorites paradoxes (heaps, baldness) by raising questions about identity over time rather than vague predicates. It differs from teletransportation puzzles by featuring incremental rather than all-at-once change. Compared to personal identity puzzles, it removes the complication of consciousness while keeping the structural question",
        "ex": "the human body is a real-world Theseus case: most cells are replaced over decades, yet we treat persons as continuous identities. Legal contracts, marriages, and crimes presume that the person who acted years ago is the same as today, despite physical and psychological change. Disagreements about what makes a person the same person across time are the puzzle made flesh",
        "mis": "people think the puzzle has an answer waiting to be discovered; many philosophers conclude that identity is conventional or context-relative, not a deep metaphysical fact. Another myth is that it is a parlor trick; the same structural issue arises in serious legal, medical, and ethical questions about continuity, often with substantive consequences",
    }

    T["the circle of fifths"] = {
        "_cat": "arts_and_humanities",
        "what": "a visual diagram in music theory arranging the twelve pitches of the chromatic scale around a circle so that each adjacent pair is a perfect fifth apart. It encodes key signatures, related keys, and chord progressions in a single image",
        "how": "starting at C at the top and moving clockwise by perfect fifths: C, G, D, A, E, B, F#, C#, G#, D#, A#, F, and back to C. Each step adds a sharp to the key signature; counterclockwise adds a flat. Adjacent keys share six of seven scale tones, making them harmonically close. Inside the circle, the relative minor keys are placed: A minor opposite C major, E minor opposite G major, and so on",
        "why": "the circle is a pedagogical and compositional Swiss Army knife. It tells you key signatures at a glance, predicts smooth modulations, organizes chord families (tonic, dominant, subdominant), guides chord substitutions (tritone substitution sits opposite on the circle), and informs cadential motion. Jazz players use it for ii-V-I sequences moving around the circle, and pop songs frequently follow circle-derived progressions",
        "vs": "the circle of fifths differs from the chromatic scale (linear semitones) and the circle of fourths (the same diagram traversed counterclockwise). It differs from modal organization (Dorian, Mixolydian, etc.) by working in major-minor tonality. Compared to tone clocks in atonal theory, the circle assumes equal temperament and tonal hierarchy",
        "ex": "the song Hey Jude moves through I-V-IV-I in F major, exploring the immediate neighbors on the circle. Jazz standards like Autumn Leaves cycle through ii-V-I progressions that march around the circle: Cm7-F7-Bbmaj7, then Am7b5-D7-Gm. Composers from Bach (Well-Tempered Clavier through all 24 keys) to The Beatles use the circle's relationships",
        "mis": "people think the circle is just a memorization aid for key signatures, missing its predictive power for modulation and chord relations. Another myth is that it is universal across musical traditions; many traditions use different scales and tunings (just intonation, microtonal music) where the circle does not apply directly. The circle is a feature of equal-tempered tonal music, not music in general",
    }

    T["sonata form"] = {
        "_cat": "arts_and_humanities",
        "what": "a large-scale musical form that emerged in the Classical era (mid-18th century) consisting typically of three sections: exposition (presenting two contrasting themes in different keys), development (working out and modulating those themes), and recapitulation (returning to the original key with both themes). It is the most studied form in Western art music",
        "how": "the exposition states the first theme in the tonic, transitions to the dominant or relative major, presents a second theme there, and closes the section with a clear cadence. The development fragments, sequences, and combines themes through distant keys, building tension. The recapitulation restates both themes in the tonic key, resolving the tonal tension. A coda may extend the closing",
        "why": "sonata form structured the first movements of symphonies, sonatas, string quartets, and concertos throughout the Classical and Romantic eras. Mastering it is required to understand Mozart, Haydn, Beethoven, Schubert, Brahms, and beyond. Its narrative arc of statement, conflict, and resolution gave Western instrumental music its long-form drama",
        "vs": "sonata form differs from binary form (two sections, AB) by adding the development and the tonal-resolution function of the recapitulation. It differs from rondo form (recurring refrain with episodes) by its tonal logic. Compared to fugue, sonata form is keyboard-friendly large-scale and tonally directional rather than contrapuntally driven",
        "ex": "the first movement of Beethoven's Fifth Symphony exemplifies sonata form. The four-note motif and contrasting lyrical second theme appear in the exposition; the development stretches the motif through distant keys with extreme intensity; the recapitulation reasserts the tonic with the second theme now in C major, and a long coda drives to triumphant closure. The whole movement is structurally a sonata-allegro narrative",
        "mis": "people think sonata form is mechanical and template-bound; great composers play with the schema, delaying the second theme, deceiving the recapitulation, fusing development and recapitulation. Another myth is that any piece called a sonata uses sonata form; the term sonata refers to the genre (a multi-movement work for solo instrument or small ensemble), with sonata form typically used in just the first movement",
    }

    T["Impressionism"] = {
        "_cat": "arts_and_humanities",
        "what": "a French art movement of the 1870s and 1880s that broke with academic painting by emphasizing fleeting effects of light, atmospheric color, and everyday subjects rendered with visible brushstrokes. Core figures include Monet, Renoir, Degas, Pissarro, Sisley, Morisot, and Manet (loosely), with the term coined dismissively from Monet's Impression, Sunrise (1872)",
        "how": "Impressionists painted en plein air to capture changing light, used pure unmixed pigments laid side by side rather than blended on the palette, broke down forms into patches of color, embraced asymmetric compositions inspired by Japanese prints and photography, and depicted urban modernity (cafes, train stations, Parisian streets) and bourgeois leisure rather than mythology or grand history",
        "why": "Impressionism marked the start of modern art by treating painting as a record of perception rather than illusionistic representation. It liberated subsequent generations (Post-Impressionists, Fauves, Cubists) to push further into abstraction and color. Its commercial success eventually transformed the gallery system, dealer-critic networks, and the public's appetite for new visual languages",
        "vs": "Impressionism differs from academic Salon painting by rejecting smooth finish, idealized subjects, and heroic narratives. It differs from realism by emphasizing optical sensation rather than gritty social truth. Compared to Post-Impressionism (Cezanne, Van Gogh, Gauguin, Seurat), Impressionism stayed closer to perception while Post-Impressionists pursued structure, emotion, or symbolism beyond fleeting light",
        "ex": "Monet's Rouen Cathedral series (1892-1894) consists of over 30 paintings of the same facade at different times of day and weather, documenting how morning fog, afternoon sun, and overcast dusk transform the same stone surface into very different visual experiences. The series concretizes Impressionism's central insight that subject is inseparable from light, time, and perception",
        "mis": "people think Impressionists painted what they saw exactly; they used optical color theory and compositional decisions extensively, hardly transcribing reality. Another myth is that the movement was unified; the painters disagreed sharply on technique, subject, and politics, and grouped together more for exhibition purposes than aesthetic uniformity. Degas hated the term Impressionism applied to his work",
    }

    T["the rule of thirds"] = {
        "_cat": "arts_and_humanities",
        "what": "a compositional guideline in visual arts that divides an image into nine equal parts by two horizontal and two vertical lines, suggesting that important compositional elements be placed along these lines or at their intersections rather than centered. It is a heuristic, not a strict rule, derived from older proportional principles like the golden ratio",
        "how": "to apply, mentally overlay a 3x3 grid on the frame. Place the horizon along the upper or lower third rather than dead center. Position a subject's eyes along the upper third line and at one of the vertical thirds. Align secondary elements at other intersections to balance. Photographers' camera grids and many software cropping tools display the lines as guides",
        "why": "the rule produces images that feel dynamic and visually interesting rather than static and symmetrical. It is widely taught in photography, graphic design, painting, and cinematography because it codifies what experienced artists do intuitively. Knowing it lets beginners produce more engaging compositions almost immediately and gives advanced practitioners a baseline to deliberately violate",
        "vs": "the rule of thirds differs from centered composition (which can feel formal and confrontational, used deliberately in symbolism and portraiture). It differs from the golden ratio (a more mathematically elaborate proportional system, slightly different ratios but similar in spirit). Compared to leading lines and dynamic symmetry, the rule of thirds is simpler and more universally applicable as a starting point",
        "ex": "in landscape photography, placing the horizon at the lower third with sky in the upper two-thirds emphasizes the sky; placing it at the upper third with land in the lower two-thirds emphasizes terrain. In portraits, putting the subject's eyes at the upper-third line creates room for subject's gaze and avoids the static feel of dead-center placement",
        "mis": "people think the rule must be followed; many great compositions ignore it, using centered, golden-ratio, or dynamic symmetric arrangements deliberately. Another myth is that it makes images automatically good; composition is one factor among many (light, subject, timing). The rule is a starting tool, not a guarantee or a requirement",
    }

    T["the Indo-European language family"] = {
        "_cat": "arts_and_humanities",
        "what": "the largest language family in the world, spanning most of Europe, large parts of South Asia, the Iranian plateau, and via colonization the Americas and Australia. Its branches include Indo-Iranian, Slavic, Romance, Germanic, Celtic, Greek, Albanian, Armenian, Anatolian (extinct), and Tocharian (extinct), with around 3 billion native speakers today",
        "how": "the family was reconstructed via the comparative method, identifying systematic sound correspondences (Grimm's Law for Germanic consonant shifts, the centum-satem split) and shared vocabulary across Sanskrit, Greek, Latin, and other languages. From these correspondences linguists reconstruct Proto-Indo-European, the unattested ancestor spoken roughly 4500-2500 BCE, probably in the Pontic-Caspian steppe (Kurgan hypothesis) or Anatolia",
        "why": "the family's reconstruction founded historical and comparative linguistics in the 19th century and remains the gold standard for language relationship. It has illuminated prehistoric migrations (Indo-Aryan into India, Indo-European spread across Europe), enabled cognate studies that improve language learning, and provided a framework other families (Afroasiatic, Sino-Tibetan, Austronesian) emulated. Words like 'mother', 'father', 'two', and 'horse' have recognizable forms across all branches",
        "vs": "Indo-European differs from genetic isolates (Basque, Korean) and from other language families (Sino-Tibetan with its tonal monosyllabic profile, Afroasiatic with its consonantal roots). Within the family, branches differ markedly: English (Germanic) and Hindi (Indo-Iranian) sound nothing alike to laypersons but share deep grammatical and lexical structure visible to comparative analysis",
        "ex": "the words for 'three' across branches: Sanskrit trayas, Greek treis, Latin tres, Old English thri, Russian tri, Welsh tri, Persian se, Lithuanian trys. Systematic sound correspondences (initial t in most, s in Persian by regular sound change) confirm common origin rather than borrowing or coincidence. Hundreds of similar correspondences cement the genetic relationship",
        "mis": "people think Indo-European means European in origin; the homeland was on the Eurasian steppe, not in Europe per se, and the family includes major Asian languages. Another myth is that all languages descend from Proto-Indo-European; it is one family among many, with most of the world's language families (over 100) unrelated genetically",
    }

    T["the Sapir-Whorf hypothesis"] = {
        "_cat": "arts_and_humanities",
        "what": "a hypothesis in linguistics and cognitive science holding that the structure of a language influences or determines the cognition and worldview of its speakers. The strong form (linguistic determinism) claims language constrains thought; the weaker form (linguistic relativity) claims it shapes habitual cognitive tendencies",
        "how": "Edward Sapir and Benjamin Lee Whorf, working in the early 20th century, drew on Native American languages (Hopi, Navajo, Apache) to argue that grammatical and lexical differences correspond to differences in conceptualization. Modern empirical work tests whether speakers of languages with grammatical gender, color terms, spatial frames of reference, or evidentiality markers show measurably different perception and memory",
        "why": "the hypothesis bears on philosophy of language, cognitive science, second-language acquisition, translation theory, and political debates about minority language preservation. If language shapes thought even modestly, language policy, education, and technology design (search engines, translation tools) acquire ethical weight. Recent neuroimaging studies show language can shift attention, categorization, and memory in measurable ways",
        "vs": "the Sapir-Whorf hypothesis differs from Chomskyan universalism, which holds that all languages share a deep grammatical structure reflecting innate cognitive architecture. It differs from cognitive relativism by being empirically testable through experiment. Compared to behavioral evidence about cultural cognition, language effects are usually subtler than Whorf's strong claims suggested",
        "ex": "Russian has separate basic terms for light blue (goluboy) and dark blue (siniy). Studies show Russian speakers discriminate the boundary between these shades faster than English speakers, who use modifiers. Aboriginal languages with cardinal-direction-only spatial reference (Guugu Yimithirr, no left/right) train speakers to constantly track absolute orientation, even in dark rooms. These show measurable but modest cognitive effects of linguistic structure",
        "mis": "people think the hypothesis claims language fully determines thought (a position even Whorf did not consistently hold); modern research supports modest linguistic relativity, not strong determinism. Another myth is the famous claim that Eskimos have hundreds of words for snow; the figure is exaggerated and depends on counting morphemes. Genuine effects exist but are subtler than popular versions suggest",
    }
