#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank: everyday life and current events topics (fresh for batch H)."""


def register(T):
    T["how to read a rental lease"] = {
        "_cat": "everyday_life",
        "what": "the process of carefully reviewing a residential lease agreement before signing to understand the rent, term, deposit handling, maintenance responsibilities, restrictions, and termination procedures that will govern your tenancy",
        "how": "read the entire document, not just signature pages. Note the rent amount, due date, and any late-fee structure. Check the term length and whether it converts to month-to-month. Verify how the security deposit is held and returned, including any state-law limits. Identify who is responsible for utilities, repairs, pest control, and yard maintenance. Look for clauses on subletting, pets, guests, alterations, and renter's insurance. Confirm renewal and termination notice periods, including early-termination fees. Photograph any pre-existing damage and request written acknowledgment",
        "why": "leases are binding contracts that often default in the landlord's favor. Misunderstanding terms costs renters thousands in unexpected fees, withheld deposits, or stuck-in-lease situations. Reading before signing also flags clauses worth negotiating, since many landlords accept reasonable amendments before lease day",
        "vs": "a lease differs from a month-to-month rental agreement in fixing the term and rent for the full period; from a sublease, where the original tenant remains liable; and from a license, which lacks tenant protections. Commercial leases differ substantially from residential leases in default rules and tenant protections",
        "ex": "a tenant who signs without reading might miss a clause requiring 60 days' notice to vacate plus a two-month early-termination fee. If a job change requires moving in three months, that clause turns into thousands of dollars of obligation. Identifying it before signing allows negotiation or different unit selection",
        "mis": "people think any clause in a lease is enforceable. Many states limit late fees, deposit handling, and entry rights regardless of what the lease says, and one-sided clauses may be void. Another myth is that landlords cannot negotiate; in soft markets, terms like fees, pets, and start dates are often flexible if asked early",
    }

    T["how to choose a credit card"] = {
        "_cat": "everyday_life",
        "what": "the process of evaluating credit card offers based on your spending patterns, credit profile, and goals to pick one whose rewards, fees, interest rate, and benefits provide the most value over time",
        "how": "list your typical spending by category (groceries, dining, gas, travel) and pick a card whose rewards rate fits the largest categories. Compare annual fees against expected rewards; calculate the break-even spending. Check the APR if you might carry a balance, plus introductory rates and balance-transfer offers. Note signup bonuses and the spending requirements to earn them. Verify benefits like extended warranty, rental car coverage, lounge access, foreign transaction fees, and travel insurance. Apply only when your credit score is in a band the issuer accepts to avoid wasted hard inquiries",
        "why": "the right card can return hundreds to thousands of dollars per year through rewards and benefits while a poor choice piles on fees and interest. Credit utilization and on-time payments also affect your credit score, with lasting effects on mortgage rates, insurance, and even employment screening",
        "vs": "rewards cards differ from low-APR cards (which prioritize lower interest for carriers of balances) and from secured cards (which require deposits and target credit-building). Cash-back cards differ from points cards in flexibility and complexity, and store cards differ from general-purpose cards in narrower acceptance and often higher rates",
        "ex": "someone spending 600 dollars a month on groceries and 300 on gas could earn about 480 dollars per year on a 4 percent grocery and 3 percent gas card with no annual fee, versus 108 on a flat 1 percent card. The difference compounds over years and is real money returned for spending you would do anyway",
        "mis": "people think cards with lavish rewards always pay off. Annual fees, complicated reward redemption, and the temptation to overspend can erase the benefits. Another myth is that you must carry a balance to build credit; using a card and paying it in full each month builds credit while avoiding interest",
    }

    T["how to evaluate a used car before buying"] = {
        "_cat": "everyday_life",
        "what": "the systematic checks of a used vehicle's documents, history, condition, and behavior on the road that identify hidden problems and either justify the asking price or support negotiation or walking away",
        "how": "verify the title is clean and matches the seller; run the VIN through services that flag accidents, salvage titles, odometer rollback, and recalls. Inspect the body for paint mismatches, panel gaps, and rust. Check tire wear patterns and tread depth. Open the hood for fluid leaks, frayed belts, and corrosion. Run the engine cold, listen for knocks, and watch exhaust color on startup. Drive the car at city and highway speeds, brake hard, and turn at full lock both ways. Get a pre-purchase inspection from an independent mechanic at modest cost; their findings often save thousands or kill bad deals",
        "why": "a thorough inspection reveals the difference between a reliable car at fair price and a money pit. Mechanical issues invisible to a casual look (head gasket leaks, transmission slips, frame damage from accidents) can cost more than the car itself. The inspection also gives leverage to negotiate fair prices",
        "vs": "buying from a private seller differs from a dealer in price (lower) and in legal recourse (more limited). Certified pre-owned (CPO) programs from manufacturers cost more but include inspection, warranty, and inventory standards. Auctions are riskiest and require expert assessment",
        "ex": "a car with otherwise clean appearance but a small oil leak near the head gasket can hide a 2000-dollar repair. A pre-purchase inspection that catches it lets you either negotiate the price down or walk away. The 100-200 dollar inspection cost is small insurance against a much larger surprise",
        "mis": "people think low mileage proves reliability. Cars driven rarely can have stale fluids, dry seals, and rust, while higher-mileage cars driven steadily on highways often hold up well. Another myth is that a Carfax with no incidents guarantees no accidents; only reported incidents appear, so a physical inspection still matters",
    }

    T["how to compare home insurance policies"] = {
        "_cat": "everyday_life",
        "what": "the process of evaluating homeowner or renter insurance quotes by examining what is covered, what is excluded, the limits, the deductibles, and the insurer's reputation rather than focusing solely on premium",
        "how": "obtain quotes for the same coverage levels from several insurers. Verify dwelling coverage equals replacement cost (not market value), personal property limits are sufficient, and liability is at least 300000 dollars. Check exclusions for floods, earthquakes, sewer backup, and certain dog breeds. Compare deductibles and how percentage deductibles for hurricanes or hail apply. Add endorsements (jewelry, scheduled property, water backup) where useful. Review the insurer's financial strength rating (AM Best) and customer-service marks (J.D. Power, NAIC complaint ratios)",
        "why": "home insurance is the largest financial-loss protection many households carry. Underinsurance after a loss can cost tens to hundreds of thousands of dollars in uncovered rebuilding, while overpaying for unused features wastes money. Picking the wrong insurer can also delay or deny claims when they matter most",
        "vs": "homeowner insurance differs from renter insurance, which covers personal property and liability but not the building. It differs from condo insurance, which covers walls-in plus personal property while the HOA covers the structure. It differs from flood insurance and earthquake insurance, which are usually separate policies",
        "ex": "a home with a 500000-dollar replacement cost insured for 350000 because the owner used the market value risks tens of thousands in shortfall after a total loss. The mistake is common with older homes whose market value tracks land prices but whose rebuild cost reflects modern construction labor and materials",
        "mis": "people think the cheapest policy is the best. Premiums differ based on coverage and deductibles; a low premium often means lower limits or higher out-of-pocket exposure. Another myth is that flood is covered by standard policies; most exclude flood, requiring a separate NFIP or private policy",
    }

    T["how to negotiate a salary offer"] = {
        "_cat": "everyday_life",
        "what": "the conversation process by which a candidate responds to a job offer to seek improved compensation (base salary, bonus, equity, benefits, sign-on, vacation) before accepting, using market data and the employer's interest in hiring you as leverage",
        "how": "research market ranges (Glassdoor, levels.fyi, salary surveys, peers) and your own minimums and goals before the offer. When the offer arrives, thank them warmly and ask for time to consider. Make a counter that names a specific number or component change, justified by market data and your skills. Negotiate the full package, not just base. Be willing to walk away if the role and offer cannot meet your reasonable threshold. Get the final offer in writing before resigning your current role",
        "why": "negotiation has compounding effects: a higher starting salary anchors raises and future offers, often adding hundreds of thousands of dollars over a career. Most employers expect some negotiation; failing to negotiate often leaves money the employer was willing to pay on the table",
        "vs": "negotiating with a new employer differs from negotiating a raise with your current employer, which depends on internal compensation bands and approval cycles. Negotiating with a startup differs from a public company in equity component complexity. Salary negotiation differs from contract negotiation, where rates, scope, and IP terms all matter",
        "ex": "a candidate offered 110000 base could counter with 125000 backed by data showing peers at similar companies earn 120-130k for the role. Many employers accept or split the difference, returning thousands per year over the role's tenure. Equity, sign-on bonuses, and additional vacation often have flex even when base is anchored",
        "mis": "people think negotiation will rescind the offer. It rarely does for reasonable counters delivered respectfully; HR has often built negotiation room into the budget. Another myth is that salary is the only lever; sign-on bonus, equity, start date, vacation, remote-work flexibility, and title all negotiate with different elasticity",
    }

    T["how to interpret food expiration dates"] = {
        "_cat": "everyday_life",
        "what": "the meanings of date labels on packaged foods (use-by, best-by, sell-by, freeze-by) and how to assess whether a food is safe to consume past those dates by relying on the labeling system, sensory evaluation, and product type",
        "how": "in most countries, expiration labels indicate quality rather than safety, except for infant formula in the US (where 'use-by' is enforced). 'Sell-by' is for retailers; 'best-by' or 'best if used by' is the manufacturer's quality estimate; 'use-by' is closer to a safety estimate but still conservative for most products. After the date, evaluate by smell, appearance, and texture. Refrigerator and pantry storage temperatures, pasteurization, and sealing all extend safe windows. High-risk foods (meat, dairy, prepared salads) deserve more caution than shelf-stable goods (canned soups, crackers, dry pasta)",
        "why": "consumers throw away enormous quantities of safe food because they misread date labels. The USDA estimates 30-40 percent of US food is wasted, with confusion over dates a major contributor. Better label literacy saves money, reduces emissions, and avoids unnecessary waste",
        "vs": "best-by dates differ from use-by in being purely about quality, and from sell-by in being addressed to consumers rather than retailers. They differ from refrigeration safety windows once a package is opened (typically days to a week) and from canned-good shelf life (years). They differ from regulated dates on infant formula and prescription drugs",
        "ex": "yogurt with a best-by date a week past today is almost certainly fine if the seal is intact and it smells normal. Eggs typically last 3-5 weeks past sell-by if refrigerated; floating in water indicates they are old and should be discarded. Dry pasta years past best-by is usually safe but may have lost some texture",
        "mis": "people think dates mark immediate spoilage. Most products are safe well beyond, especially shelf-stable ones. Another myth is that smell tells you everything; some pathogens (Listeria, certain Salmonella) produce no off-odor, so high-risk foods deserve stricter date adherence than dry or canned goods",
    }

    T["how to safely use power tools at home"] = {
        "_cat": "everyday_life",
        "what": "the practices that minimize injury risk when operating circular saws, drills, sanders, grinders, and similar power tools for home repair and improvement projects",
        "how": "wear safety glasses always; add hearing protection for loud tools and a dust mask for sanding or cutting. Tie back hair and avoid loose clothing or jewelry that could catch in moving parts. Read the manual at least once. Keep a clean workspace with the workpiece firmly clamped or held. Use the right tool, blade, or bit for the material. Check for damaged cords and ensure GFCI protection on outdoor circuits. Unplug or remove battery before changing blades or bits. Keep both hands on the tool when running and let it stop completely before setting it down",
        "why": "power tools cause hundreds of thousands of injuries per year in the US, many preventable. A few minutes of preparation and attention removes most of the risk. The same habits also produce cleaner work because you are not fighting a misaligned setup or wrong tool",
        "vs": "DIY use differs from professional jobsite use mainly in frequency and tool quality, but the safety principles are identical. Hand tool safety differs in lower kinetic energy but similar eye and posture concerns. Power tool safety differs from welding or chemistry safety, which has additional fume and burn risks",
        "ex": "a circular saw used without a clamp on a small board can pinch and kick back violently, sending the board or saw toward the operator. Clamping the workpiece, supporting both sides of the cut, and keeping the saw's guard functional eliminates most of the risk. The minute spent setting up beats months of recovery from a finger injury",
        "mis": "people think experience replaces protection. Most serious injuries happen to experienced users in familiar settings, where attention drifts. Another myth is that gloves always help; loose gloves can catch in spinning bits and pull a hand into a tool, so for many uses a bare hand or close-fitting glove is safer",
    }

    T["how to read a weather radar map"] = {
        "_cat": "everyday_life",
        "what": "the skill of interpreting the colored returns on radar imagery (typically reflectivity in dBZ) to estimate where precipitation is, how intense it is, how it is moving, and what kinds of weather it might produce",
        "how": "radar transmits microwave pulses and measures reflected energy from precipitation; the strength is reported in dBZ (decibels of reflectivity). Light blue and green typically indicate light rain, yellow moderate, orange heavy, and red to magenta intense thunderstorms or hail. Animation loops show motion, helping you anticipate arrival times. Dual-pol radar adds shape information to distinguish rain from hail or debris. National Weather Service overlays add severe-weather warnings and storm tracks",
        "why": "real-time radar interpretation lets you make practical decisions: whether to bike home before a storm, whether a wedding venue needs to move indoors, when to take cover from a tornado warning. It also helps interpret forecasts and weather news with skepticism informed by actual conditions",
        "vs": "radar differs from satellite imagery, which shows clouds (including dry ones) but not precipitation directly. It differs from forecast maps, which model future conditions. It differs from lightning detection networks, which map separate phenomena. Each source complements the others",
        "ex": "a magenta core moving toward your area at 30 miles per hour from 20 miles west tells you you have about 40 minutes before heavy weather arrives, possibly with hail. The motion vector, displayed in many apps, plus the reflectivity intensity, is enough to plan routes home or move outdoor activities indoors",
        "mis": "people think radar shows what is overhead now perfectly. Radar has a beam height that increases with distance, so distant returns can miss low precipitation; nearby returns from below the lowest sweep can miss too. Another myth is that radar shows rain rate directly; it shows reflectivity, which translates to rain rate via assumptions that vary by storm type",
    }

    T["the renewed scrutiny of social media's effect on teens"] = {
        "_cat": "current_events",
        "what": "the policy and research debate intensifying since 2023 about whether social media platforms harm adolescent mental health, attention, and social development, with regulators, researchers, and platforms arguing about the magnitude of effects and appropriate responses",
        "how": "the US Surgeon General issued advisories in 2023 calling for action on adolescent social media use. State legislatures (Florida, Utah, Texas, New York) passed laws requiring parental consent or age verification, many partially blocked by courts. The EU's Digital Services Act imposes risk-assessment duties on large platforms. Researchers continue to publish mixed results: heavy use correlates with depression in observational data, but causal claims and effect sizes remain contested. Platforms have rolled out teen-specific defaults (private accounts, time limits, restricted DMs)",
        "why": "the issue affects roughly half of US teens (who report near-constant use) and shapes regulation, parenting practice, and platform design globally. It has become a flashpoint in debates over technology, free speech, parental rights, and child welfare, with rulings and laws likely to set precedents for AI-related regulation as well",
        "vs": "the current wave differs from earlier moral panics over television and video games by featuring more rigorous longitudinal data and active platform admissions of internal harm research (the 2021 Facebook Files). It differs from broader online-safety debates by focusing specifically on developmental and mental-health impacts in adolescents",
        "ex": "Australia's 2024 ban on social media access for under-16s, set to take effect in late 2025, requires platforms to take 'reasonable steps' to verify age. The law has drawn international attention as a test case for whether age-based restrictions can be enforced and whether they will reduce harms or simply push activity onto less-regulated platforms",
        "mis": "people think the scientific consensus is settled. Research is robust on correlations but disputed on causal effect sizes; some researchers argue effects are real but moderate, others that they are large, and a minority argue most evidence remains weak. Another myth is that any single intervention (ban, age verification, time limits) will solve the issue; effects are likely modest and require combined approaches",
    }

    T["the global push for AI safety frameworks"] = {
        "_cat": "current_events",
        "what": "the parallel and sometimes coordinated efforts since 2023 by major economies and international bodies to establish governance, transparency, and risk-management requirements for advanced artificial intelligence systems",
        "how": "the EU AI Act, agreed in late 2023 and rolling into effect through 2026, classifies systems by risk and imposes obligations on providers of general-purpose AI. The UK hosted AI Safety Summits at Bletchley Park (2023), Seoul (2024), and Paris (2025). The US has worked through executive orders, NIST frameworks, and bilateral agreements rather than major legislation. The G7 Hiroshima AI process, the OECD AI Principles, and bilateral US-China dialogues add multilateral context. AI companies have signed voluntary commitments on red-teaming, watermarking, and disclosure",
        "why": "AI capabilities are advancing faster than regulatory regimes, with implications for jobs, security, civil rights, and information ecosystems. The frameworks shape what models can be deployed, how they must be evaluated, and what accountability exists when they cause harm. Outcomes will affect global competition between the US, EU, and China, and the trajectory of AI development overall",
        "vs": "AI governance differs from earlier tech regulation (privacy, antitrust) in addressing risks that are partly speculative and rapidly evolving, requiring adaptive frameworks. It differs from biotech and nuclear regulation by lacking a centralized international body, while drawing analogies to those frameworks for inspiration. It differs from cybersecurity regulation by focusing on model behavior alongside system security",
        "ex": "the EU AI Act bans certain uses (social scoring, real-time biometric surveillance with exceptions), imposes strict requirements on high-risk uses (employment, credit, law enforcement), and sets transparency and risk-management duties for general-purpose AI. Compliance costs and definitions are still being clarified, with the AI Office publishing guidance through 2025-2026",
        "mis": "people think AI safety means only existential risk. The frameworks address near-term harms (bias, surveillance, job displacement, misinformation) far more than speculative scenarios. Another myth is that voluntary commitments suffice; most safety experts argue binding regulation is necessary, while industry positions vary on the scope and stringency",
    }

    T["the global energy transition's bottlenecks"] = {
        "_cat": "current_events",
        "what": "the practical constraints (grid capacity, permitting, supply chains, workforce, financing) that are slowing the deployment of renewable energy and electrification needed to meet 2030-2050 climate targets, despite rapid cost declines in solar, wind, and batteries",
        "how": "interconnection queues for new generation projects have ballooned globally; in the US alone, terawatts of capacity wait years for grid connection studies and upgrades. Permitting for transmission lines and offshore wind takes a decade in many jurisdictions. Supply chains for transformers, semiconductors, lithium, copper, and rare earths have hit shortages, raising costs. Skilled trades shortages slow installation of heat pumps and EV chargers. High interest rates after 2022 hurt the economics of capital-intensive clean energy",
        "why": "the IEA, IPCC, and national energy bodies all conclude the 2050 net-zero pathway requires installing renewables and electrifying end uses much faster than current rates. The bottlenecks decide whether decarbonization meets timelines or slips by years to decades, with corresponding climate, economic, and geopolitical consequences",
        "vs": "today's bottlenecks differ from earlier decades' cost barriers (now largely solved for solar and wind) by being structural and permitting-related rather than technological. They differ from oil-shock dynamics in being chronic supply expansion problems rather than acute shocks, and from past infrastructure builds (interstate highway, rural electrification) by the more dispersed and litigated regulatory environment",
        "ex": "the US offshore wind sector entered a crisis in 2023-2024 with project cancellations and renegotiations as inflation, supply chain issues, and interest rates rendered earlier contracts uneconomic. Vineyard Wind delivered first power in 2024 but at higher costs than originally projected, and several projects were paused or restructured",
        "mis": "people think the transition is bottlenecked by political will alone. Even with full political alignment, hard physical and regulatory bottlenecks slow deployment. Another myth is that markets solve these issues quickly; transmission and permitting reform require legislative and administrative changes that take years even when supported on paper",
    }

    T["the ongoing realignment of global trade patterns"] = {
        "_cat": "current_events",
        "what": "the post-2018 shift in international trade flows away from the deeply integrated, China-centric model of the 2000s-2010s toward a more fragmented, security-conscious, and regional pattern shaped by US-China rivalry, the pandemic, and Russia's invasion of Ukraine",
        "how": "the US imposed escalating tariffs and export controls on Chinese semiconductors, electric vehicles, and other technologies. Companies have pursued 'China plus one' strategies, expanding production in Vietnam, India, Mexico, and Eastern Europe. The CHIPS Act, IRA, and EU industrial policies subsidize domestic and allied production of chips, batteries, and clean energy. Russia's exclusion from Western financial systems after 2022 and ongoing sanctions have rerouted energy and commodity trade. Africa-China and South-South trade have grown alongside the realignment",
        "why": "the realignment affects supply chain costs, inflation, growth, geopolitics, and climate goals. It shifts production patterns, investment flows, and currency dynamics. Reshaping multinational supply chains takes years and capital, with implications for consumer prices, labor markets, and emissions across the world",
        "vs": "the current realignment differs from the 1980s globalization launch by going partly in reverse, from the late 1990s WTO-driven integration by adding security as a primary lens, and from earlier trade wars (Smoot-Hawley) by being more selective and combined with industrial policy. It differs from full deglobalization, which is overstated; trade volumes remain near record highs",
        "ex": "Mexico overtook China in 2023 as the largest source of US imports, reflecting both China-plus-one shifts and USMCA preferences. Investment in Mexican manufacturing zones, particularly auto and electronics components, has surged, although infrastructure and security challenges constrain how fast the shift can proceed",
        "mis": "people think globalization is reversing wholesale. Trade and FDI are reshaping rather than collapsing; total flows remain near record levels but their composition and directions are shifting. Another myth is that reshoring will restore manufacturing employment quickly; automation and labor market shifts mean new factories employ far fewer workers per unit of output than their predecessors",
    }

    T["how to plan a long-distance road trip"] = {
        "_cat": "everyday_life",
        "what": "the process of preparing a multi-day driving trip by mapping a route, scheduling stops, preparing the vehicle, packing essentials, and planning for fatigue, weather, and unexpected events",
        "how": "pick anchor destinations and use mapping tools to estimate driving time at realistic speeds (about 55-60 mph average including stops). Plan no more than 8-10 hours of driving per day, with rotation among drivers if possible. Service the vehicle (oil, tires, brakes, fluids) before leaving. Pack snacks, water, charging cables, paper backup directions, jumper cables or jump pack, basic tools, blanket, and weather-appropriate gear. Book lodging at least the first few nights so fatigue doesn't force a desperate stop. Watch weather along the route and adjust the daily plan to avoid driving through major storms",
        "why": "preparation prevents most of the things that derail road trips: vehicle breakdowns, exhaustion, weather closures, and the cascading effects when a tight schedule meets an unexpected delay. A few hours of preparation typically saves days of recovery and substantially improves the experience",
        "vs": "a road trip differs from flying in trading time for flexibility and luggage capacity, from a guided tour in self-direction and pace, and from a daily commute in scale and the planning required. It differs from camping trips that center on outdoor activities by treating the drive as a meaningful part of the experience",
        "ex": "a 2500-mile route from Boston to San Francisco at 8 hours of driving per day takes about 5 days minimum; building in a rest day in the middle and a buffer for weather makes 7 days realistic. Driving 14 hours daily to compress it leaves drivers exhausted, increasing accident risk and degrading the trip",
        "mis": "people think they can drive much longer per day than is safe. Fatigue cuts reaction times comparably to alcohol after long stretches; planning conservatively avoids the temptation to push past sensible limits. Another myth is that GPS makes paper backup unnecessary; in remote areas with no service, paper or offline maps still matter",
    }

    T["how to declutter a home methodically"] = {
        "_cat": "everyday_life",
        "what": "the process of systematically reducing household possessions to those that are useful, used, or genuinely valued, freeing space and reducing maintenance burden through repeatable decisions about each item",
        "how": "work room by room and category by category rather than randomly. Pull all items in a category (clothing, books, kitchen tools) into one place to see the full quantity. Decide each item's fate: keep, donate, sell, recycle, or trash. Apply consistent criteria (used in past year, would buy again today, fits the life you actually live). Discard immediately or set up a donation drop-off rotation so 'donate' piles do not become permanent fixtures. Repeat seasonally; major decluttering is rarely one-and-done",
        "why": "clutter increases cleaning time, decision fatigue, and stress; reduces usable space; and slows finding what you need. Methodical decluttering reduces these costs and saves money by exposing duplicates that prevent re-buying. It also forces clarification of priorities and habits in a way that one-room-at-a-time often does not",
        "vs": "decluttering differs from organizing, which arranges items in place without reducing them, and from minimalism, which is a lifestyle choice with stronger reduction. Methods like KonMari (joy-based), the 90/90 rule (used in past or next 90 days), and the four-box method (keep, donate, store, trash) differ in framing but share the systematic per-item decision discipline",
        "ex": "pulling all clothing onto a bed rather than judging items in the closet often reveals 60-80 percent of garments that are rarely worn, multiple duplicates, and items kept for sentimental rather than functional reasons. The shock of seeing the volume often unblocks decisions that drawer-by-drawer review never reaches",
        "mis": "people think decluttering is one weekend's work. Most households accumulate over years and reduce best in waves, with maintenance practices to prevent re-accumulation. Another myth is that selling everything recovers significant money; resale is slow and pays cents on the dollar for most items, so donation is usually faster and more valuable in time saved",
    }

    T["how to safely store food in a refrigerator"] = {
        "_cat": "everyday_life",
        "what": "the practices of temperature control, organization, and packaging that maximize how long food remains safe and pleasant to eat in a home refrigerator while minimizing cross-contamination",
        "how": "keep the refrigerator below 40 F (4 C) and the freezer at 0 F (-18 C); use a thermometer because dial settings vary. Store raw meats, poultry, and seafood on the bottom shelf in sealed containers to prevent drips onto produce or ready-to-eat foods. Keep eggs in the original carton on a shelf rather than the door, where temperature fluctuates. Separate produce: ethylene-producing fruits (apples, bananas) accelerate ripening of greens nearby. Cool hot foods to room temperature briefly before refrigerating, but no longer than two hours total. Label leftovers with dates and use within 3-4 days",
        "why": "improper storage causes most home food-borne illness through cross-contamination or temperature abuse. Correct storage extends safe windows, reduces waste, and preserves quality. The cost of a thermometer and basic organization is repaid quickly in less spoiled food and fewer stomach problems",
        "vs": "refrigerator storage differs from freezer storage, which extends life much longer at the cost of texture changes for some foods. It differs from pantry storage, where dry, sealed conditions allow shelf-stable goods to last months to years. It differs from commercial refrigeration in lacking strict temperature monitoring and regulation",
        "ex": "a roast chicken cooled and refrigerated within two hours, in a sealed container on a middle shelf, stays safe for 3-4 days. The same chicken left covered on the counter overnight enters the danger zone (40-140 F) and should not be eaten the next day, regardless of appearance",
        "mis": "people think food is safe as long as it smells fine. Pathogens like Listeria and some Salmonella strains produce no off-odor; relying on smell alone misses important risks. Another myth is that the refrigerator's coldest spot is the door; the door is usually the warmest, with bottom-back shelves coldest",
    }

    T["how to assess a stock for long-term investing"] = {
        "_cat": "everyday_life",
        "what": "the process of evaluating a publicly traded company's business, financials, valuation, and risks before deciding whether to hold its stock as a long-term investment, beyond simple price-momentum thinking",
        "how": "understand what the company does, who its customers are, and how it makes money. Read recent 10-K and 10-Q filings, focusing on revenue, margins, cash flow, debt, and how they have trended over years. Compare valuation metrics (P/E, P/B, EV/EBITDA, free-cash-flow yield) to peers and the company's history. Assess management quality, capital allocation, and ownership alignment. Consider risks: competition, regulation, technological change, customer concentration. Decide whether the price reflects expectations you think are reasonable or unreasonably bearish",
        "why": "rigorous evaluation distinguishes investing from gambling and provides the basis for holding through volatility. It also forces clarification of why you own something, which improves selling decisions when fundamentals change. Index investing remains the appropriate default for most people; individual-stock work pays off only with serious effort and durable temperament",
        "vs": "fundamental analysis differs from technical analysis, which uses price patterns to predict short-term moves. It differs from index investing, which avoids stock selection entirely. Value investing differs from growth investing in emphasizing current cash flows and assets rather than future expansion. Quantitative investing differs by using statistical models rather than narrative judgment",
        "ex": "an investor evaluating a software company would compare its rule-of-40 score (revenue growth plus operating margin), customer retention metrics, free-cash-flow conversion, and EV/sales multiple to peers. A company growing 30 percent with 15 percent operating margin trades at different multiples than one growing 10 percent at 30 percent margin, and the analysis clarifies whether the price is sensible",
        "mis": "people think they can identify winning stocks by intuition or news headlines. Most active investors underperform index funds over long horizons, and those who outperform usually have systematic processes and information advantages. Another myth is that valuation does not matter for great companies; even excellent businesses bought at extreme multiples can produce poor returns",
    }

    T["the post-2024 reorganization of US AI policy"] = {
        "_cat": "current_events",
        "what": "the shifts in US federal approaches to artificial intelligence following the 2024 election, including the rescission of certain Biden-era executive orders, refocusing of NIST and AI Safety Institute work, and new emphases on competitiveness and infrastructure",
        "how": "the new administration rescinded the 2023 Biden executive order on AI in early 2025 and issued new directives emphasizing competitiveness with China, deregulation of training compute reporting, and federal procurement of AI services. The AI Safety Institute reorganized under new leadership. State-level activity (California, Texas, Colorado) continued, sometimes filling federal gaps. International commitments at the Paris AI Action Summit (2025) showed divergence between US and EU approaches. Industry capital expenditures on data centers and chips reached unprecedented scale through 2025-2026",
        "why": "US policy choices shape what models are developed and deployed globally, since most leading AI labs are US-based or US-funded. The shifts affect alignment with EU regulations, US-China technology competition, transparency norms, and the pace at which safety practices become required versus voluntary. They also affect state-federal preemption fights still working through courts",
        "vs": "the current approach differs from the 2023-2024 EU-aligned, safety-centered framing by emphasizing competitiveness and reducing reporting burdens. It differs from a hypothetical industry self-regulation approach by retaining substantial procurement, security, and antitrust levers. It differs from China's centralized, state-aligned governance by keeping development largely in private hands within national-security guardrails",
        "ex": "the Stargate data center initiative announced in early 2025 commits hundreds of billions of dollars over years to AI infrastructure within the US, illustrating the administration's emphasis on physical and energy capacity as a competitiveness lever. The associated permitting and energy implications spill into climate, grid, and local zoning debates",
        "mis": "people think US AI policy is binary across administrations. Many constants persist (export controls on advanced chips to China, procurement standards, NIST frameworks), with shifts mostly at the margins of voluntary commitments and rule emphasis. Another myth is that policy is the dominant determinant of AI progress; capital, talent, and compute remain the largest drivers",
    }

    T["the rapid spread of GLP-1 weight-loss drugs"] = {
        "_cat": "current_events",
        "what": "the widespread adoption since 2022 of glucagon-like peptide-1 receptor agonists (semaglutide, tirzepatide) for weight management, beyond their original diabetes indication, with effects on patients, payers, food companies, and public health",
        "how": "weekly injections of semaglutide (Wegovy, Ozempic) or tirzepatide (Zepbound, Mounjaro) reduce appetite by mimicking gut hormones that signal satiety to the brain and slow gastric emptying. Patients lose 15-22 percent of body weight on average over 16-18 months, far above prior pharmacological options. Demand has outpaced supply, raising costs for self-pay patients to about 1000 dollars per month in the US. Insurance coverage varies widely; Medicare formally cannot cover for obesity (though that is contested), private plans have begun adding coverage with restrictions",
        "why": "obesity and its complications drive a major share of US healthcare spending. Effective drugs could reshape that arithmetic, but at high price tags and uncertainty about long-term effects when stopped (most regain weight). The drugs are also showing benefits in heart disease, sleep apnea, kidney disease, and possibly addictions, expanding their potential further. Effects on snack-food spending, alcohol consumption, and bariatric surgery are already visible",
        "vs": "GLP-1 drugs differ from earlier weight-loss medications (orlistat, phentermine) in efficacy and tolerability, from bariatric surgery in being reversible and non-invasive but losing weight back when stopped, and from lifestyle interventions in the magnitude of physiological appetite suppression they achieve. They differ from earlier diabetes drugs by showing strong cardiovascular benefits independent of glucose effects",
        "ex": "the SELECT trial published in 2023 showed semaglutide reduced major cardiovascular events by 20 percent in non-diabetic patients with obesity and pre-existing heart disease. The result transformed how cardiologists view obesity treatment and helped justify broader coverage despite the cost",
        "mis": "people think the drugs work without lifestyle change. Diet and activity still matter; trials combine the drugs with intensive support, and outcomes are best with both. Another myth is that the weight loss is permanent; observational follow-up shows that stopping the drug leads to substantial regain in most patients, suggesting many will need long-term therapy",
    }

    T["the housing supply-side reform debate"] = {
        "_cat": "current_events",
        "what": "the policy debate intensifying since 2021 over how to increase housing supply in expensive cities and metros through zoning reform, permitting streamlining, building-code adjustments, and public investment, in response to severe affordability pressures",
        "how": "California, Oregon, Washington, Massachusetts, and Minneapolis have liberalized zoning to allow duplexes, ADUs, or larger multifamily projects on previously single-family lots. Permitting reforms address review timelines, parking minimums, environmental review (CEQA, NEPA) abuses, and historic-preservation overuse. New York and Boston debate similar reforms. Internationally, Auckland's 2016 upzoning and Tokyo's national-level zoning offer examples of supply responses to liberalization. YIMBY (Yes In My Back Yard) coalitions have grown into significant political forces alongside traditional NIMBY opposition",
        "why": "housing costs have risen faster than incomes in most major metros, eroding household finances, geographic mobility, fertility, and the climate benefits of urban density. Reform proponents argue supply constraints are the dominant cause; opponents argue financialization, demand factors, and design quality matter as much. The outcome shapes income inequality, urban-rural politics, and decarbonization",
        "vs": "supply-side reforms differ from rent control (a demand- or price-side intervention) and from voucher expansion (a transfer to renters). They differ from public housing construction in working through private builders rather than government as developer. The current US debate differs from 1970s-1990s housing policy by foregrounding zoning rather than financing as the bottleneck",
        "ex": "Auckland's 2016 unitary plan upzoned much of the city to allow taller and denser development; subsequent academic studies attribute thousands of additional housing units and reduced rent growth versus nearby comparison areas to the reform. The case is cited frequently in US debates as evidence that zoning liberalization can move the needle on supply",
        "mis": "people think more housing means lower property values for existing owners. Empirical evidence is mixed and often shows neutral or even positive effects when reforms are well-designed. Another myth is that reform alone solves affordability; complementary investments (transit, infrastructure, vouchers) and sustained reform over years are usually needed",
    }
