"""Part 8: remaining math + science entries."""


def register_part_8(r):
    # ---- science: electrochemistry and batteries ----
    r("electrochemistry and batteries", "comparison",
      "Electrochemical cells differ between primary (single-use) and secondary (rechargeable) types. Primary cells like alkaline batteries undergo irreversible chemical reactions and are discarded when depleted. Secondary cells like lithium-ion, lead-acid, and NiMH undergo reversible reactions and can be recharged hundreds to thousands of times. Compared with capacitors, which store charge electrostatically and discharge nearly instantaneously, batteries store energy in chemical bonds and discharge over minutes to hours, with much higher energy density but lower power density. Compared with fuel cells, which continuously consume external fuel (typically hydrogen) to generate electricity, batteries store their reactants internally and have fixed capacity per charge. Among rechargeable chemistries, lithium-ion has the highest energy density (about 250 Wh/kg) but is more expensive and thermally sensitive than lead-acid (about 35 Wh/kg) used in cars or NiMH used in hybrid vehicles. Each chemistry trades off cost, energy density, power density, cycle life, safety, and temperature performance.")
    r("electrochemistry and batteries", "significance",
      "Electrochemistry and batteries matter because they enable portable electrical energy storage that powers everything from smartphones and laptops to electric vehicles and grid-scale storage. Lithium-ion batteries, with their combination of high energy density, decent power density, and adequate cycle life, have transformed personal electronics since the 1990s and are now driving the electrification of transportation and the integration of variable renewable energy into electric grids. Battery cost reductions of about 90 percent over the past decade have made electric vehicles competitive with combustion alternatives in many markets. Grid-scale batteries enable solar and wind power to displace fossil generation by storing energy from sunny or windy periods for use later. Future battery research aims at higher energy densities (solid-state lithium, lithium-sulfur), lower cost (sodium-ion, iron-air), longer life, and reduced reliance on critical materials like cobalt. Beyond energy storage, electrochemistry underpins sensors, electroplating, corrosion protection, electrolysis for green hydrogen production, and many industrial processes.")

    # ---- science: geomagnetic reversals ----
    r("geomagnetic reversals", "significance",
      "Geomagnetic reversals matter because Earth's magnetic field shields the surface from the solar wind and cosmic rays, and during reversals the field temporarily weakens and becomes more complex with multiple poles, potentially allowing more high-energy particles to reach the atmosphere and surface. The geological record shows that the field has reversed hundreds of times over Earth's history, with reversals occurring on irregular timescales averaging hundreds of thousands of years; the most recent full reversal was the Brunhes-Matuyama event about 780,000 years ago. Reversals themselves typically take thousands of years, during which the field may drop to 10 percent or less of its strength. The current field has been weakening at about 5 percent per century, prompting speculation about an upcoming reversal, though such weakening can also be transient. The biological and technological consequences of past reversals appear modest, but in modern times a major weakening could disrupt satellites, power grids, and migratory animal navigation. Studying past reversals using the magnetic record in lavas and sediments also provides timestamps used in geochronology.")

    # ---- science: phase transitions significance ----
    r("phase transitions of matter", "significance",
      "Phase transitions matter because they govern the behavior of materials in countless technological and natural settings. The freezing and melting of water shape weather, climate, and ecosystems, with the high latent heat of water moderating temperatures near oceans and ice sheets. Boiling and condensation power steam turbines that generate most of the world's electricity. Magnetic phase transitions underlie hard drives, transformer cores, and other devices. Superconducting transitions enable lossless current transmission in MRI magnets, particle accelerators, and quantum computers. Phase transitions in alloys (martensitic transformations) underpin shape-memory alloys used in stents and aerospace components. In food science, phase transitions govern crystallization in chocolate, ice cream, and frozen foods. In Earth science, phase transitions in mantle minerals at depth create seismic discontinuities and influence tectonic plate behavior. The universal scaling laws near continuous phase transitions, captured by renormalization group theory, link wildly different physical systems through shared critical behavior, illustrating that phase transitions are both practically important and theoretically deep.")

    # ---- science: polymer chemistry ----
    r("polymer chemistry", "definition",
      "Polymer chemistry is the branch of chemistry that studies polymers, which are large molecules built from many repeating subunits called monomers connected by covalent bonds. Natural polymers include proteins (built from amino acids), nucleic acids (DNA and RNA, built from nucleotides), polysaccharides (starch and cellulose, built from sugars), and natural rubber. Synthetic polymers, ranging from polyethylene and polystyrene to nylon and PET, are produced industrially in vast quantities for plastics, fibers, films, coatings, adhesives, and elastomers. The properties of polymers depend on the chemical nature of the monomers, the chain length and distribution (molecular weight), the geometry (linear, branched, cross-linked), and the arrangement of side groups (tacticity). Polymer chemistry studies how polymers are synthesized (addition polymerization, condensation polymerization, controlled radical polymerization), characterized, processed, and engineered to achieve specific physical, mechanical, optical, and chemical properties.")
    r("polymer chemistry", "mechanism",
      "Polymerization mechanisms fall into two main classes. Chain-growth (addition) polymerization adds monomers one at a time to the end of a growing active chain bearing a free radical, cation, or anion; common examples include polyethylene, polypropylene, and polystyrene synthesis. The mechanism involves initiation (creating an active species, typically by decomposing an initiator molecule), propagation (sequential monomer addition), and termination (deactivating the active end by combination, disproportionation, or chain transfer). Step-growth (condensation) polymerization joins monomers through reactions that may release small molecules (water, methanol) at each step; nylon, polyester, and polyurethane formation are examples. Each step in step-growth polymerization can in principle occur between any two compatible monomers or oligomers, building molecular weight more gradually than chain growth. Modern controlled polymerization techniques (ATRP, RAFT, anionic polymerization) achieve narrow molecular weight distributions and complex architectures (block copolymers, brushes, dendrimers) that enable advanced material properties.")

    # ---- science: tides and lunar gravity ----
    r("tides and lunar gravity", "definition",
      "Tides are the periodic rises and falls of sea level produced primarily by the gravitational pull of the Moon and, to a lesser extent, the Sun, modulated by the rotation of the Earth and the geometry of ocean basins. The Moon's gravity attracts the ocean (and the solid Earth) more on the near side than the far side, creating a difference in gravitational pull across the planet that stretches the oceans into a slight ellipsoid with bulges on both the lunar and anti-lunar sides. As Earth rotates, each location passes through these bulges, experiencing two high tides and two low tides each lunar day (about 24 hours and 50 minutes). The Sun's smaller tidal effect (about 46 percent of the Moon's despite the Sun's much greater mass, because tidal force depends on the inverse cube of distance) modulates this pattern, producing larger spring tides at new and full moon when Sun and Moon align, and smaller neap tides at first and third quarter when they pull at right angles.")
    r("tides and lunar gravity", "mechanism",
      "Tides arise from the gradient of gravitational attraction across an extended body, not from gravity itself. The Moon pulls the near side of Earth more strongly than its center, and the center more strongly than the far side; Earth's center 'falls' toward the Moon at an intermediate rate, leaving the near ocean accelerated toward the Moon and the far ocean apparently accelerated away (because Earth's center is pulled toward the Moon faster than the far ocean is). This produces two simultaneous tidal bulges. Earth's rotation under these bulges, combined with their slow drift due to the Moon's orbital motion, gives the roughly 12 hour 25 minute period between high tides at most coastal locations. Local effects (continental shelf width, basin shape, friction, resonances of basin oscillations) can vastly modify tidal range, producing huge tides in places like the Bay of Fundy (15+ meters) and barely measurable tides in other locations like the Mediterranean.")
    r("tides and lunar gravity", "comparison",
      "Lunar tides differ from solar tides in being roughly twice as large despite the Sun's much greater mass, because tidal force depends on the gradient of gravity (inverse cube of distance) while ordinary gravitational pull depends on the inverse square. The Moon's closer distance more than compensates for its smaller mass. Tides differ from ocean swells and waves driven by wind in being predictable from astronomy and operating on much longer timescales (semidiurnal vs. seconds-to-minutes for waves). Tides also differ from storm surges driven by atmospheric low pressure and wind setup, which can be unpredictable and dangerous when superimposed on high tides. Compared with atmospheric tides (similar phenomenon in the air column, much weaker but detectable), oceanic tides are far more visible and consequential. Compared with the small but measurable solid-Earth tides (centimeter-scale flexing of the rocky Earth itself by the same forces), oceanic tides are amplified by the ocean's fluidity and basin geometry.")
    r("tides and lunar gravity", "example",
      "The Bay of Fundy on Canada's east coast has the world's highest tides, with tidal ranges of up to 16 meters between low and high tide. The bay's funnel shape and the resonance between its natural oscillation period (about 13 hours) and the semidiurnal tidal forcing period amplify incoming tidal waves through constructive interference. Twice a day, water rushes in and out, exposing vast mudflats at low tide that are completely submerged hours later. Reversing falls and tidal bores (waves of incoming tide propagating up rivers) are spectacular phenomena visible at multiple locations in the bay. The example illustrates how local geometry can dramatically amplify the modest open-ocean tidal forcing into extreme local effects. Tidal energy projects in the bay aim to harvest some of this enormous flow for electricity. Similar but less extreme amplification occurs at many shelf seas worldwide; coastal tide tables are needed for navigation, fishing, and beach safety because of these geometric effects.")
    r("tides and lunar gravity", "significance",
      "Tides matter for navigation, coastal ecology, marine biology, and several engineering applications. Ports adjust ship traffic to tide schedules, since deep-draft vessels often need high tide to enter shallow harbors. Tidal flats and salt marshes are highly productive coastal ecosystems whose biology depends on the regular flooding and exposure cycles. Many marine organisms (mussels, barnacles, intertidal algae, certain fish, crabs) have evolved life cycles tightly coupled to tides, and reproductive synchronization in many coral and worm species depends on lunar phases. Tidal currents drive water exchange between coastal seas and the open ocean, with implications for sediment transport, nutrient distribution, and pollutant dispersion. Tidal forcing also drives mixing in the deep ocean that influences global thermohaline circulation. Tidal energy projects (in the Bay of Fundy, La Rance in France, the Sihwa Lake in South Korea) generate electricity from tidal flows. The slow tidal slowing of Earth's rotation (lengthening the day by about 1.7 milliseconds per century) and the Moon's recession from Earth (about 3.8 cm per year) are long-term consequences of tidal interactions.")
    r("tides and lunar gravity", "misconception",
      "A common misconception is that there is only one tidal bulge, on the side facing the Moon, with the second high tide each day being inexplicable. The two bulges arise from the differential gravity across Earth's diameter, not from a single attractive pull. Another misconception is that tidal forces are due to the Moon's atmospheric pressure or magnetic effects; they are purely gravitational. People also sometimes assume that the tides themselves prove that the Earth-Moon system is unstable; in fact, the system is in dynamic equilibrium, with energy slowly transferred from Earth's rotation to the Moon's orbit through tidal friction. The popular notion that human bodies experience meaningful 'tidal' effects from the Moon, used to justify lunar influences on health or behavior, has no scientific basis: tidal effects scale with size, and human-scale tidal forces from the Moon are vastly smaller than countless other unnoticed forces. Finally, the assumption that high tide always coincides with the Moon overhead misses that local resonances, friction, and continental geometry produce tide times that lag or lead the Moon's transit by hours.")

    # ---- math: Big-O notation ----
    r("Big-O notation", "definition",
      "Big-O notation describes the asymptotic upper bound on the growth rate of a function, used widely in computer science to characterize the worst-case time or space requirements of algorithms as a function of input size. Formally, f(n) = O(g(n)) means there exist positive constants c and N such that f(n) <= c times g(n) for all n >= N. Common categories from fastest to slowest growth include O(1) (constant), O(log n) (logarithmic), O(n) (linear), O(n log n) (linearithmic), O(n^2) (quadratic), O(n^3) (cubic), O(2^n) (exponential), and O(n!) (factorial). Sorting algorithms range from O(n^2) for selection or insertion sort to O(n log n) for merge sort and quicksort. Search trees provide O(log n) lookups; hash tables aim for O(1). Big-O captures scaling behavior for large inputs, ignoring constant factors and lower-order terms.")
    r("Big-O notation", "misconception",
      "A common misconception is that Big-O notation tells you which algorithm is faster in practice for any given input. Big-O describes asymptotic behavior, ignoring constants and lower-order terms; for small or moderate inputs, an O(n^2) algorithm with small constants can be faster than an O(n log n) algorithm with large constants. Another misconception is that Big-O gives the exact running time; it provides an upper bound on growth rate, not a precise prediction. People also sometimes confuse Big-O with Big-Theta (which gives a tight bound, both upper and lower) and Big-Omega (which gives a lower bound); using Big-O when Big-Theta is meant can be misleading. The distinction between worst-case, average-case, and best-case complexity is also often overlooked: quicksort is O(n^2) worst case but O(n log n) on average, making it competitive with merge sort in practice. Finally, Big-O analysis ignores cache effects, branch prediction, and other architectural details that significantly affect real-world performance.")

    # ---- math: Euclidean geometry axioms ----
    r("Euclidean geometry axioms", "comparison",
      "Euclid's axioms differ from modern axiom systems for geometry in their level of rigor and explicitness. Euclid stated five postulates and five common notions, but his proofs implicitly used additional assumptions (continuity, betweenness, congruence preserved by rigid motion) that he did not state. Modern foundations like David Hilbert's 1899 Foundations of Geometry give roughly twenty axioms organized into incidence, order, congruence, parallels, and continuity, providing a fully rigorous basis. Compared with non-Euclidean axiom systems that replace the parallel postulate with alternatives, Euclidean geometry uniquely satisfies the property that exactly one line through a point parallel to a given line. Compared with synthetic axiomatic geometry (working from axioms only), analytic geometry uses coordinates and algebra to derive the same results, with the equivalence formalized by Hilbert and others.")
    r("Euclidean geometry axioms", "significance",
      "Euclid's axioms matter because they established the model of axiomatic mathematics that has guided the discipline for over 2000 years. The Elements showed how a vast body of geometric knowledge could be derived from a small set of explicit assumptions through valid logical steps, becoming the most influential mathematics textbook in history. The realization that the parallel postulate could be denied without contradiction (yielding non-Euclidean geometries) in the 19th century shattered the assumption that Euclidean geometry was the unique geometry of physical space, and prepared the way for Einstein's general relativity in which space-time is curved rather than Euclidean. The axiomatic method, refined into modern foundational systems, underlies all of contemporary mathematics. Euclidean geometry also remains the practical geometry of everyday engineering, surveying, and architecture at scales where curvature of space is undetectable, and is the foundational geometry taught in schools worldwide.")

    # ---- math: Eulerian and Hamiltonian paths ----
    r("Eulerian and Hamiltonian paths", "definition",
      "An Eulerian path in a graph is a path that visits every edge exactly once. An Eulerian circuit (or Eulerian cycle) is an Eulerian path that begins and ends at the same vertex. A Hamiltonian path visits every vertex exactly once; a Hamiltonian cycle is a Hamiltonian path that begins and ends at the same vertex. The two concepts have superficially similar definitions but very different complexity: Euler's theorem (1736) provides a simple test for Eulerian paths (every vertex must have even degree for an Eulerian circuit; exactly two vertices may have odd degree for an Eulerian path), and efficient algorithms construct them in time linear in the number of edges. Hamiltonian paths and cycles, by contrast, are NP-complete to detect, with no known polynomial-time algorithm and no simple necessary-and-sufficient condition. The traveling salesman problem is the classic optimization version of finding minimum-weight Hamiltonian cycles.")
    r("Eulerian and Hamiltonian paths", "comparison",
      "Eulerian and Hamiltonian paths differ fundamentally in computational complexity and characterization. Eulerian paths visit every edge exactly once; Hamiltonian paths visit every vertex exactly once. Despite the symmetry of the definitions (edges vs. vertices), Euler's theorem gives a simple degree-based criterion for the existence of Eulerian paths and supports linear-time construction algorithms. No analogous simple criterion or efficient algorithm is known for Hamiltonian paths; deciding whether a graph has one is NP-complete. The contrast illustrates how seemingly similar problems can have radically different algorithmic difficulty. Euler's solution to the Konigsberg bridges problem in 1736 launched graph theory; Hamilton's icosian game from 1857 inspired Hamiltonian cycle research. Compared with the related Chinese postman problem (find a closed walk traversing every edge with minimum total cost), Eulerian circuits arise as the optimal solution when one exists.")
    r("Eulerian and Hamiltonian paths", "significance",
      "Eulerian and Hamiltonian paths matter because they appear in countless applications and exemplify the contrast between tractable and intractable graph problems. Eulerian paths apply to circuit board manufacturing (drawing all required wires with minimum lifts), DNA fragment assembly (de Bruijn graph methods rely on Eulerian paths in genome reconstruction), garbage collection routes (visiting every street), and snowplow routing. Hamiltonian paths and cycles arise in the traveling salesman problem and its variants, vehicle routing, scheduling problems, and circuit testing. Because Hamiltonian problems are NP-complete, practical instances are tackled by approximation algorithms, integer programming, branch-and-bound, and heuristic methods like genetic algorithms or simulated annealing. The contrast between the two problem types informs the broader theory of computational complexity: small structural changes in problem definitions can move them between complexity classes, with deep implications for what problems can be solved efficiently at scale.")

    # ---- math: Monte Carlo methods ----
    r("Monte Carlo methods", "definition",
      "Monte Carlo methods are computational techniques that use repeated random sampling to obtain numerical results, especially when deterministic methods are infeasible. Named after the casino in Monaco, the methods originated in the 1940s for nuclear weapons calculations at Los Alamos. The general idea is to model a system or quantity as the result of random processes, simulate those processes many times on a computer, and use the empirical distribution or average of the simulated outcomes to estimate the desired quantity. Common applications include numerical integration in high dimensions (where deterministic quadrature scales poorly), simulation of physical systems (Ising model, particle transport, molecular dynamics), Bayesian statistical inference (Markov chain Monte Carlo), financial option pricing, and rendering of computer graphics (path tracing). The method's accuracy improves as 1 / sqrt(N) where N is the sample size, regardless of the dimension of the problem, giving Monte Carlo a major advantage in high-dimensional settings.")
    r("Monte Carlo methods", "comparison",
      "Monte Carlo methods differ from deterministic numerical methods in trading exact answers for stochastic estimates whose accuracy improves with sample size. Compared with deterministic numerical integration (Simpson's rule, Gaussian quadrature) which converges fast in low dimensions but suffers exponentially with dimension, Monte Carlo's 1/sqrt(N) convergence is dimension-independent, making it the method of choice for high-dimensional integrals. Compared with quasi-Monte Carlo methods which use deterministic low-discrepancy sequences instead of pseudorandom numbers, ordinary Monte Carlo is simpler but quasi-Monte Carlo can converge faster (close to 1/N) for smooth integrands. Compared with Markov chain Monte Carlo (MCMC) for sampling from complex distributions, ordinary Monte Carlo requires direct sampling and so is limited to distributions for which sampling is easy. Compared with variance reduction techniques (importance sampling, control variates, antithetic variates), basic Monte Carlo is simpler but has higher variance for the same number of samples.")

    # ---- math: NP-completeness ----
    r("NP-completeness", "definition",
      "NP-completeness is a concept in computational complexity theory describing the hardest problems in the class NP. NP (nondeterministic polynomial time) consists of decision problems whose 'yes' instances can be verified in polynomial time given an appropriate certificate. P (polynomial time) consists of problems solvable in polynomial time. The famous P vs NP question asks whether these classes are equal. A problem is NP-hard if every problem in NP can be reduced to it in polynomial time; an NP-hard problem in NP is NP-complete. NP-complete problems are computationally equivalent: a polynomial-time algorithm for one would yield polynomial-time algorithms for all. The first NP-complete problem identified was Boolean satisfiability (SAT) by Cook and Levin in 1971, and Karp showed in 1972 that 21 other natural problems were also NP-complete, establishing a vast and growing catalog. Common NP-complete problems include traveling salesman, graph coloring, knapsack, Hamiltonian cycle, and subset sum.")
    r("NP-completeness", "mechanism",
      "NP-completeness works through polynomial-time reductions that translate one problem into another. To show problem A is NP-complete, one shows it is in NP (gives a polynomial-time verification procedure given a certificate) and shows it is NP-hard by reducing a known NP-complete problem to A in polynomial time. The reduction transforms instances of the known hard problem into equivalent instances of A such that an algorithm solving A would solve the hard problem (after the reduction). If A had a polynomial-time algorithm, the composition with the polynomial-time reduction would solve the hard problem in polynomial time, transferring tractability across the entire NP-complete class. The mechanism establishes a kind of equivalence among NP-complete problems: in terms of asymptotic worst-case complexity, they are equally hard, even though their structural details differ wildly. This equivalence is the basis for organizing intractable computational problems into a coherent theory.")
    r("NP-completeness", "comparison",
      "NP-complete problems differ from problems in P in being (probably) not solvable in polynomial time, though no proof exists yet that P is not equal to NP. NP-complete problems differ from problems that are merely NP-hard in being themselves in NP (the certificate for a yes instance can be verified efficiently); some NP-hard problems are not in NP (such as the optimization version of TSP, which asks for the minimum tour rather than just whether a tour of length at most k exists). NP-complete problems also differ from problems in PSPACE-complete (decidable in polynomial space but possibly requiring exponential time) and EXPTIME-complete classes, which are believed to be even harder. Compared with undecidable problems like the halting problem, NP-complete problems are decidable in principle but lack efficient algorithms. The catalog of NP-complete problems has grown to include thousands of natural problems across many domains, reinforcing the working assumption that no efficient general algorithm exists.")

    # ---- math: circle properties ----
    r("circle properties", "example",
      "A useful example of circle properties is computing the area of a circular sector and arc length. A circle of radius r has area pi r^2 and circumference 2 pi r. A sector subtending a central angle theta (in radians) has arc length r theta and sector area (1/2) r^2 theta. For radius 5 and angle pi/3 (60 degrees): arc length is 5 times pi/3, about 5.24; sector area is (1/2)(25)(pi/3), about 13.09. The inscribed angle theorem states that an inscribed angle (vertex on the circle) is half the central angle subtending the same arc, so a chord subtending a 60-degree central angle subtends a 30-degree inscribed angle from any other point on the major arc. Tangent lines to a circle from an external point have equal lengths, and the line from the external point to the center bisects the angle between the two tangents. These and other circle properties are foundational to geometry, trigonometry, and applications in engineering and design.")

    # ---- math: complex numbers ----
    r("complex numbers", "comparison",
      "Complex numbers extend the real numbers by introducing a unit imaginary number i with i^2 = -1, so that every complex number has the form a + bi where a and b are real. Compared with real numbers, complex numbers are algebraically closed: every nonconstant polynomial with complex coefficients has at least one complex root (the fundamental theorem of algebra), while polynomials over the reals can fail to have real roots (x^2 + 1 has no real roots). Complex numbers form a two-dimensional space that can be visualized as a plane (the complex plane), with addition behaving like vector addition and multiplication having a geometric interpretation as scaling and rotation. Compared with quaternions and other higher-dimensional number systems, complex numbers retain commutativity of multiplication. Compared with 2D real vectors, complex numbers come with an additional multiplication operation that has remarkable analytic and algebraic properties.")
    r("complex numbers", "example",
      "A standard example: solve x^2 + 4 = 0. Real solutions do not exist because x^2 is non-negative for real x. Allowing complex solutions: x^2 = -4, so x = plus or minus 2i. Verify: (2i)^2 = 4 i^2 = -4, confirming the solution. More substantively: compute (3 + 4i)(2 - i). Distribute: 6 - 3i + 8i - 4i^2 = 6 + 5i - 4(-1) = 10 + 5i. The modulus of a complex number z = a + bi is |z| = sqrt(a^2 + b^2); |3 + 4i| = sqrt(9 + 16) = 5. Euler's formula e^(i theta) = cos(theta) + i sin(theta) connects exponentials to trigonometry, with the special case e^(i pi) + 1 = 0 linking five fundamental constants. Complex numbers are essential in electrical engineering (representing AC currents and voltages), quantum mechanics (wavefunctions are complex-valued), signal processing (Fourier analysis), and many other applications where rotation, oscillation, or two-dimensional structure is intrinsic to the problem.")

    # ---- math: coordinate geometry ----
    r("coordinate geometry", "comparison",
      "Coordinate (analytic) geometry differs from synthetic (Euclidean) geometry in using algebra and number coordinates to describe geometric objects rather than working purely from axioms and constructions. Compared with synthetic geometry, coordinate methods systematize calculations: distances, angles, and intersections become algebraic equations rather than ruler-and-compass constructions. Coordinate geometry was Descartes' great innovation in 1637, providing a bridge between geometry and algebra that made many previously hard problems routine. Compared with vector geometry, coordinate geometry uses specific basis-dependent representations while vector methods often abstract away the coordinate choice. Compared with projective geometry, coordinate geometry typically uses Euclidean coordinates suited to flat space; projective coordinates handle the points at infinity needed for projective phenomena like perspective. Modern computational geometry, computer graphics, and machine learning all rely on coordinate representations to make geometric calculations tractable on digital computers.")
    r("coordinate geometry", "example",
      "An example: find the intersection of two lines given by 2x + 3y = 12 and x - y = 1. Solve the second for x: x = y + 1. Substitute: 2(y + 1) + 3y = 12, so 5y + 2 = 12, giving y = 2 and x = 3. The lines intersect at (3, 2). Verify: 2(3) + 3(2) = 12 and 3 - 2 = 1. To find the distance from a point (x_0, y_0) to a line ax + by + c = 0, use the formula |a x_0 + b y_0 + c| / sqrt(a^2 + b^2). For the point (1, 1) and the line 2x + 3y - 12 = 0: distance = |2 + 3 - 12| / sqrt(4 + 9) = 7 / sqrt(13), about 1.94. The example shows how coordinate algebra reduces geometric questions to symbol manipulation that can be performed mechanically and extended to higher dimensions and curved surfaces.")
    r("coordinate geometry", "significance",
      "Coordinate geometry matters because it converts geometric questions into algebraic computations, enabling the systematic and computational treatment of geometry. Modern computer graphics, computer-aided design, robotics, computer vision, GPS navigation, and geographic information systems all rely on coordinate geometry to represent objects and calculate spatial relationships. Calculus extends coordinate geometry to handle smooth curves and surfaces. Linear algebra generalizes coordinate methods to arbitrary dimensions. Differential geometry studies curves and surfaces using coordinate-based calculus. Coordinate geometry also bridges domains: physics relies on coordinate systems to express laws (with care for which coordinates are inertial); engineering uses coordinates for design and analysis; data science uses coordinate-based geometry to analyze high-dimensional data. The Cartesian coordinate system is so embedded in modern thought that we forget it was a major intellectual revolution.")
    r("coordinate geometry", "misconception",
      "A common misconception is that coordinate geometry is just about plotting points on a grid, missing its power to express and solve geometric problems algebraically. Another misconception is that coordinates are always Cartesian; polar, cylindrical, spherical, and many other coordinate systems suit different problems, with the right choice often making a calculation drastically easier. People also sometimes assume that coordinate calculations always give exact answers; floating-point arithmetic introduces errors that matter in practice for ill-conditioned problems (intersections of nearly parallel lines, points very close to constraint boundaries). Finally, the assumption that coordinate geometry replaces synthetic methods misses that synthetic proofs often reveal structure that coordinate calculations obscure; the two approaches complement each other, with coordinates valuable for computation and synthesis valuable for insight.")

    # ---- math: exponential growth and decay ----
    r("exponential growth and decay", "comparison",
      "Exponential growth differs from linear growth in scaling behavior: a linearly growing quantity adds a constant per time step, while an exponentially growing quantity multiplies by a constant per time step. Over enough time, exponential growth always overtakes any polynomial growth. Compared with logistic growth (which starts exponentially but saturates as resources or capacity are exhausted), exponential growth is unbounded and unrealistic for most real systems over long times. Compared with exponential decay, growth has a positive rate constant and the quantity increases without bound, while decay has a negative rate constant and the quantity decreases toward zero (or some baseline). Exponential and logarithmic functions are inverses; the doubling time for exponential growth (about 0.693 / r where r is the rate constant) and the half-life for decay (also 0.693 / |r|) capture the timescales involved. Compared with power-law behavior often seen in network science and physics, exponential laws have a characteristic timescale while power laws have none.")
    r("exponential growth and decay", "significance",
      "Exponential growth and decay matter because they describe many real-world processes including population growth, radioactive decay, compound interest, viral disease spread, electronic circuit transients, drug metabolism, and bacterial multiplication. Understanding exponential dynamics is essential to interpreting epidemics (cumulative cases initially grow exponentially before slowing as susceptible populations are exhausted or interventions take hold), evaluating long-term financial decisions (compound interest dramatically rewards early saving and punishes early debt), assessing climate impacts (greenhouse gas concentrations and the resulting warming respond exponentially to emissions over relevant timescales), and dating ancient materials (radiocarbon dating uses the known half-life of carbon-14). Many human-caused environmental and technological challenges are essentially failures to anticipate exponential dynamics, where slow initial growth is dismissed until rapid late-stage growth makes intervention difficult or impossible. Recognizing exponential signatures and reasoning about doubling times are basic numeracy skills with broad applicability.")
    r("exponential growth and decay", "example",
      "Compound interest at 7 percent per year on $1000 grows exponentially: after 10 years, $1000 times (1.07)^10, about $1967, nearly doubling. After 20 years, about $3870; after 30 years, about $7612; after 40 years, about $14,974. The 'rule of 72' approximates doubling time as 72 / interest rate (in percent), so 7 percent gives doubling in about 10 years, matching the calculation. Radioactive decay illustrates the inverse: carbon-14 has a half-life of 5,730 years, so a sample with 100 percent of natural C-14 today would have 50 percent after 5,730 years, 25 percent after 11,460 years, 12.5 percent after 17,190 years, and so on. After about 50,000 years (about 10 half-lives) only 0.1 percent remains, marking the practical limit of radiocarbon dating. The exponential factor 2^n shrinks below detectability faster than intuition typically expects, just as compound interest grows faster than intuition expects.")
    r("exponential growth and decay", "misconception",
      "A common misconception is that exponential growth is fast in absolute terms; in fact, exponential growth can appear slow in early stages and only later becomes overwhelming. Many epidemics and viral phenomena go unappreciated until late-stage exponential growth has already locked in much of the eventual scale. Another misconception is that exponential growth can continue indefinitely; in real systems, resource limits, environmental feedbacks, or interventions invariably slow growth, often through logistic or other saturating dynamics. People also sometimes confuse 'exponential' with 'rapid' more loosely, calling any rapid growth exponential without checking whether the rate constant is constant; true exponential growth has a fixed doubling time, while merely rapid growth may not. Finally, the assumption that small percentage rates produce small absolute changes ignores compounding; 1 percent annual growth doubles in about 70 years, a substantial change over generational timescales.")

    # ---- math: floating-point representation ----
    r("floating-point representation", "mechanism",
      "Floating-point representation works by storing real numbers in a sign-exponent-mantissa format analogous to scientific notation. The IEEE 754 standard, used by most modern hardware, defines double-precision (64-bit) format with 1 sign bit, 11 exponent bits, and 52 mantissa bits, representing numbers as (-1)^s times 1.m times 2^(e - 1023). The exponent ranges from about -1022 to +1023, giving values from roughly 10^-308 to 10^+308. Special bit patterns encode infinities, signed zeros, denormalized numbers near zero, and NaN (not-a-number) for indeterminate operations. The 52-bit mantissa gives about 15-17 decimal digits of precision. Single-precision (32-bit, 7-9 decimal digits) is faster on some hardware and used in graphics; half-precision (16-bit, 3-4 digits) is increasingly used in machine learning. The mechanism trades off representable range, precision, and storage; floating point cannot exactly represent most decimal fractions, leading to rounding errors that accumulate in long computations.")
    r("floating-point representation", "significance",
      "Floating-point representation matters because it makes scientific and engineering computation feasible on digital computers, but it introduces subtleties that have caused real-world disasters when ignored. Almost all numerical software relies on floating-point arithmetic. The Patriot missile failure during the Gulf War (1991) was traced to accumulated floating-point error in time tracking. The Ariane 5 rocket explosion (1996) was caused by an unhandled floating-point overflow during inertial guidance computation. Beyond such dramatic cases, day-to-day issues like 0.1 + 0.2 not equaling exactly 0.3 reflect the inability of binary floating-point to represent decimal fractions exactly. Numerical analysis studies how to organize calculations to maintain precision (avoiding catastrophic cancellation, using stable algorithms, controlling condition numbers). Modern machine learning has driven interest in lower-precision formats (bfloat16, FP8) that trade accuracy for speed and energy efficiency. Hardware support for floating point in CPUs and GPUs has been a major engineering investment for decades.")

    # ---- math: fractal geometry ----
    r("fractal geometry", "misconception",
      "A common misconception is that fractals are merely pretty computer-generated images. Fractals were rigorous mathematical objects long before they could be visualized on computers, with examples like the Cantor set, Koch snowflake, and Sierpinski triangle dating to the late 19th and early 20th centuries. Another misconception is that all rough or irregular shapes are fractals; true fractals exhibit self-similarity (scale invariance) and non-integer fractal dimension, properties that not every irregular shape has. People also sometimes assume that fractals exist only as mathematical abstractions; many natural phenomena (coastlines, mountain profiles, blood vessel networks, snowflakes, fern leaves, river drainage patterns) approximate fractal scaling over a range of scales, with the scaling breaking down at very small or very large scales. Finally, the popular notion that fractals have 'infinite detail' is a useful approximation but applies only to mathematical fractals; physical fractals are bounded above and below by physical scales (atomic spacing, system size).")

    # ---- math: graph theory basics ----
    r("graph theory basics", "definition",
      "Graph theory is the branch of mathematics studying graphs, mathematical structures consisting of vertices (also called nodes) connected by edges. Graphs can be directed (edges have an orientation, going from one vertex to another) or undirected; weighted (edges carry numerical values like distances or capacities) or unweighted; simple (at most one edge between any two vertices, no self-loops) or with multiple edges and loops allowed. Common graph concepts include path (a sequence of vertices connected by edges), cycle (a closed path), connected components, degree (number of edges at a vertex), trees (connected acyclic graphs), and bipartite graphs (vertices split into two sets with edges only between sets). Algorithms on graphs include breadth-first and depth-first search, Dijkstra's shortest path, Kruskal's and Prim's minimum spanning tree, max-flow min-cut, and many others. Graph theory has deep mathematical theory and pervasive applications.")
    r("graph theory basics", "mechanism",
      "Graph theory works by abstracting structures as vertices and edges, then applying algorithms and theorems that exploit graph structure. Adjacency lists or matrices represent graphs in computers, supporting efficient queries and modifications. Traversal algorithms (BFS for shortest hops, DFS for connected components and cycle detection) explore graphs systematically. Shortest-path algorithms (Dijkstra for non-negative weights, Bellman-Ford for general weights, Floyd-Warshall for all-pairs) solve routing problems. Spanning tree algorithms (Kruskal, Prim) build minimum-cost networks. Flow algorithms (Ford-Fulkerson, Edmonds-Karp, push-relabel) solve maximum-flow and minimum-cut problems with applications in transportation, scheduling, and image segmentation. Matching algorithms find pairings in bipartite graphs (used in assignment problems). Network analysis tools compute centrality, clustering, community detection, and many other structural metrics that reveal hidden patterns in large graphs derived from social networks, the internet, biological networks, and infrastructure.")
    r("graph theory basics", "significance",
      "Graph theory matters because graphs are a universal model for relational data and discrete structure. Social networks (Facebook friend graphs, Twitter follower graphs) are graphs; the World Wide Web is a graph (web pages as vertices, hyperlinks as edges); the internet itself is a graph of routers and connections; transportation networks, electrical grids, supply chains, biological interaction networks, and many other systems all admit graph representations. Algorithms on these graphs power Google search (PageRank computes a measure on the web graph), GPS navigation (shortest path through road graphs), social-media feed ranking, recommendation systems, fraud detection, drug discovery (protein interaction networks), and countless other applications. Beyond applications, graph theory has rich mathematical content: Ramsey theory, extremal combinatorics, algebraic and spectral graph theory, random graph theory, and graph coloring all connect to broader mathematics. The four-color theorem, the proof that every planar graph can be colored with four colors, was the first major theorem proved with computer assistance.")

    # ---- math: hyperbolic geometry ----
    r("hyperbolic geometry", "comparison",
      "Hyperbolic geometry differs from Euclidean geometry in replacing the parallel postulate with the assertion that through a point not on a given line, infinitely many lines parallel to the given line exist. This single change cascades through the geometric structure: triangles have angle sums less than 180 degrees (with the deficit proportional to area), the area of a circle grows exponentially with radius, and similar triangles must be congruent. Compared with elliptic (spherical) geometry, where there are no parallel lines and triangle angles sum to more than 180 degrees, hyperbolic and elliptic geometries are the two non-Euclidean alternatives. Compared with Euclidean geometry as the geometry of flat space, hyperbolic geometry is the geometry of constant negative curvature, with several models (Poincare disk, Poincare half-plane, Klein disk, hyperboloid) representing the same underlying geometry in different ways.")
    r("hyperbolic geometry", "mechanism",
      "Hyperbolic geometry can be developed axiomatically from a modified set of axioms (replacing the parallel postulate) or constructed via models embedded in Euclidean space. The Poincare disk model represents the hyperbolic plane as the interior of a Euclidean disk, with hyperbolic lines being arcs of circles meeting the boundary at right angles, and angles measured as in Euclidean geometry but distances measured by a metric that diverges at the boundary. The Poincare half-plane model represents the hyperbolic plane as the upper half of the Euclidean plane, with hyperbolic lines being vertical lines or semicircles centered on the boundary axis. The Klein disk model uses straight chords for lines but distorts angles. The hyperboloid model embeds the hyperbolic plane as one sheet of a two-sheeted hyperboloid in 3D Minkowski space. All these models satisfy the same axioms and yield the same geometric theorems, with the choice of model dictated by which calculations are easier.")
    r("hyperbolic geometry", "example",
      "M. C. Escher's woodcut series 'Circle Limit' provides a famous artistic example of hyperbolic geometry. The four prints depict the Poincare disk filled with repeating patterns of fish, angels, devils, and similar figures. As figures approach the disk's boundary, they appear to shrink in Euclidean terms but are all the same hyperbolic size, illustrating that the Poincare disk's metric makes the boundary infinitely far from the center. The patterns repeat under hyperbolic isometries that look like Mobius transformations in the model. Mathematically, the underlying tessellations are by triangles or other polygons whose hyperbolic angles sum correctly for the desired tiling; many such tilings (like the order-7 triangular tiling) have no Euclidean analog because Euclidean triangles cannot tile with seven meeting at each vertex without curvature. Other examples include the geometry of saddle-shaped surfaces, certain crystallographic structures, and the AdS/CFT correspondence in theoretical physics.")
    r("hyperbolic geometry", "significance",
      "Hyperbolic geometry matters because it shattered the long-held belief that Euclidean geometry was the unique consistent geometry, opening the way for general non-Euclidean and curved spaces in mathematics and physics. The realization in the 19th century that hyperbolic geometry was as logically consistent as Euclidean geometry forced a profound reassessment of the relationship between mathematics and physical space. Einstein's general relativity uses curved spacetime that is generally neither Euclidean nor uniformly curved; locally hyperbolic regions appear in negative-curvature solutions. Hyperbolic geometry also appears in cosmology (open universes have hyperbolic spatial geometry), in the AdS/CFT correspondence linking gravity in anti-de Sitter space to gauge theories on its boundary, and in the geometry of complex networks (which often have negatively-curved hyperbolic embeddings). Hyperbolic surfaces play roles in string theory, in the Mostow rigidity theorem of geometric topology, and in computer science via efficient embeddings of hierarchical data.")
    r("hyperbolic geometry", "misconception",
      "A common misconception is that hyperbolic geometry is exotic or contradicts Euclidean geometry; in fact, both are internally consistent and describe different (purely mathematical) spaces, with neither being 'wrong.' Another misconception is that hyperbolic geometry requires extra dimensions; the hyperbolic plane is two-dimensional, just as the Euclidean plane is, and can be studied entirely within two dimensions. People also sometimes assume that hyperbolic geometry's failure of similar triangles being non-congruent is a defect; on the contrary, it is a feature reflecting that scale matters in negatively curved space, just as it does in spherical geometry. Finally, the popular notion that the Poincare disk model is the 'real' hyperbolic plane, with apparent shrinking of figures near the boundary, misrepresents that all points are hyperbolically equivalent and that the visualization distortions are model-dependent rather than features of the geometry itself.")

    # ---- math: knot theory ----
    r("knot theory", "definition",
      "Knot theory is the mathematical study of knots: closed curves embedded in three-dimensional space, considered up to continuous deformation that does not allow the curve to pass through itself. Two knots are equivalent if one can be deformed into the other without breaking the loop. The simplest knot is the unknot (a plain circle); other examples include the trefoil knot (the simplest nontrivial knot, having three crossings) and the figure-eight knot (four crossings). Knots are studied through invariants: properties that are the same for equivalent knots, used to distinguish inequivalent ones. Important invariants include the crossing number (minimum number of crossings in any diagram), the Alexander polynomial, the Jones polynomial (whose discovery in 1984 led to a breakthrough in the field), and various homology theories (Khovanov homology). Generalizations to links (collections of knotted loops) and to higher-dimensional analogs broaden the field.")
    r("knot theory", "mechanism",
      "Knot theory works by representing knots as diagrams (projections onto a plane with over/under crossing information at each crossing) and studying which diagrams represent the same knot. Reidemeister proved in 1927 that two diagrams represent equivalent knots if and only if they can be connected by a sequence of three local moves (Reidemeister moves: I twists a strand, II passes one strand over another then back, III passes a strand over a crossing). Knot invariants are values associated with knots that are unchanged by Reidemeister moves; an invariant that distinguishes two knots proves they are inequivalent. The Alexander polynomial and Jones polynomial are computed from a diagram by recursive rules at each crossing and can be shown to be invariant under Reidemeister moves. Knot invariants enable computer enumeration of knots: tables of all prime knots up to large crossing numbers are now standard.")
    r("knot theory", "example",
      "The trefoil knot is the simplest nontrivial example. It can be drawn as a closed curve with three crossings forming a three-fold symmetric pattern. There are actually two distinct trefoils (the left-handed and right-handed forms), which are mirror images and not equivalent through any continuous deformation in 3D space (a property called chirality). The Alexander polynomial of the trefoil is t^2 - t + 1; the Jones polynomial is -t^4 + t^3 + t. Either polynomial differs from that of the unknot (which is just 1 for both polynomials), proving that the trefoil cannot be untied without breaking the loop. The same techniques apply to far more complex knots, including those used in DNA topology (DNA molecules can become physically knotted, with topoisomerase enzymes responsible for unknotting), in chemistry (synthetic molecular knots have been built and studied), and in the study of anyons in topological quantum computing.")

    # ---- math: linear programming ----
    r("linear programming", "mechanism",
      "Linear programming maximizes or minimizes a linear objective function subject to linear equality and inequality constraints. The simplex method, developed by George Dantzig in 1947, traverses vertices of the feasible polytope (the convex region of solutions satisfying all constraints), moving from vertex to vertex along edges that improve the objective until no improving move is possible. Geometrically, the optimal solution always lies at a vertex if one exists, because the objective is linear and the feasible region is convex. Interior point methods, developed in the 1980s, take a different approach: starting inside the feasible region, they follow a curved path through the interior toward the optimum, with each step solving a system of linear equations. Both methods solve practical linear programs efficiently; simplex has good practical performance despite worst-case exponential complexity, while interior point methods have polynomial-time worst-case bounds and excel on certain problem structures.")
    r("linear programming", "significance",
      "Linear programming matters because it solves an enormously wide range of optimization problems efficiently and is the workhorse of operations research, supply chain management, transportation planning, finance, and many other fields. Industrial applications include refinery scheduling, airline crew scheduling, telecommunications routing, electric power dispatch, hospital staff scheduling, and food blending. The dietary applications that helped motivate Dantzig's original work continue: large agricultural and food processing operations use linear programming to formulate animal feeds and food products at minimum cost subject to nutritional constraints. The market for linear programming software is in the hundreds of millions of dollars annually. Beyond direct applications, linear programming serves as a building block for more complex optimization techniques: branch-and-bound for integer programming, decomposition methods for very large problems, and convex relaxations of nonconvex problems. The duality theory of linear programming has theoretical implications across optimization and game theory.")
    r("linear programming", "example",
      "A simple example: a small farm wants to plant wheat and corn to maximize profit. Wheat earns $200 per acre; corn earns $300 per acre. The farm has 100 acres and 240 hours of labor available. Wheat requires 2 hours of labor per acre; corn requires 4 hours per acre. Maximize 200 w + 300 c subject to w + c <= 100 (acreage), 2 w + 4 c <= 240 (labor), w >= 0, c >= 0. Geometrically, the feasible region is a polygon in the (w, c) plane, and the optimum is at one of its vertices. Solving: at the corner (40, 60), profit is 8000 + 18000 = 26000 (uses 40 + 60 = 100 acres and 80 + 240 = 320 hours, exceeds labor). Recompute: corners are (0, 0), (100, 0) profit 20000, (0, 60) profit 18000 with 240 labor, and the intersection of w + c = 100 and 2w + 4c = 240 at (80, 20) profit 22000. Optimum is (80, 20), planting 80 acres of wheat and 20 of corn for $22,000 profit.")

    # ---- math: logarithms ----
    r("logarithms", "significance",
      "Logarithms matter because they convert multiplication into addition, exponentiation into multiplication, and exponential relationships into linear ones, simplifying many calculations and revealing patterns that would otherwise be hidden. Before electronic calculators, logarithm tables and slide rules made multiplication of large numbers feasible by hand; logarithms underlay essentially all engineering computation for centuries. Today, logarithms appear in scales like decibels (sound intensity), Richter magnitude (earthquake energy), pH (hydrogen ion concentration), and stellar magnitudes (brightness), where each unit corresponds to a multiplicative factor in the underlying quantity. Information theory uses logarithms to measure information content (bits as log base 2 of equally likely outcomes). Computational complexity often uses logarithms (binary search is O(log n), efficient sorting is O(n log n)). Statistics uses logarithms for log-likelihood maximization, log-odds in logistic regression, and log-transformations to normalize skewed data. Even music notation uses logarithmic frequency scaling (each octave doubles the frequency).")

    # ---- math: non-Euclidean geometry ----
    r("non-Euclidean geometry", "mechanism",
      "Non-Euclidean geometries work by replacing Euclid's parallel postulate with alternative axioms while keeping the other axioms of geometry intact. In hyperbolic geometry, through a point not on a given line there are infinitely many lines that do not intersect the given line. In elliptic (spherical) geometry, no lines are parallel: any two great circles on a sphere intersect at two antipodal points. The mechanism by which these alternatives produce consistent geometries is that they correspond to spaces of constant negative or positive curvature respectively, in contrast to the flat (zero curvature) Euclidean plane. Concrete models embed these geometries in Euclidean space: spherical geometry on the surface of an ordinary sphere, hyperbolic geometry in the Poincare disk or hyperboloid models. The same axiomatic system can be realized in different models, all sharing the same theorems but differing in how distances and angles are computed.")
    r("non-Euclidean geometry", "comparison",
      "Non-Euclidean geometries differ from Euclidean geometry in their treatment of parallel lines and the resulting global properties. In Euclidean geometry, triangle angle sums are exactly 180 degrees and similar triangles can be of any size. In hyperbolic geometry, angle sums are less than 180 degrees with the deficit proportional to area, and there are no similar triangles of different sizes. In elliptic geometry, angle sums exceed 180 degrees, with the excess proportional to area; great circles serve as 'lines' on a sphere. Compared with each other, hyperbolic and elliptic geometries are limit cases of constant negative and positive curvature; Euclidean geometry is the borderline zero-curvature case. Compared with general curved spaces (Riemannian geometry), the three classical geometries are the ones with constant curvature; general Riemannian manifolds have curvature that varies from point to point, with general relativity using such varying curvature to describe gravity.")
    r("non-Euclidean geometry", "example",
      "Spherical (elliptic) geometry on the Earth is a familiar example. Lines in spherical geometry are great circles (circles whose plane passes through the sphere's center, like the equator and meridians); they are the geodesics, the shortest paths between two points on the sphere. Two great circles always intersect at two antipodal points, so there are no parallel lines. Spherical triangles formed by three great-circle arcs have angle sums exceeding 180 degrees: a triangle with vertices at the north pole, on the equator at 0 longitude, and on the equator at 90 longitude has three right angles, summing to 270 degrees. Long-distance flights follow great-circle routes (which look curved on a flat Mercator map but are the shortest paths on the sphere). Navigators have computed with spherical geometry for centuries. Hyperbolic geometry has Escher's Circle Limit prints and certain saddle-shaped surfaces as visual examples but is harder to perceive directly because it cannot be globally embedded in three-dimensional Euclidean space without distortion.")

    # ---- math: numerical stability ----
    r("numerical stability", "definition",
      "Numerical stability refers to how well a numerical algorithm or computation resists the amplification of small errors (in input data or in intermediate computations from finite-precision arithmetic) into large errors in the final result. A stable algorithm produces results close to the exact answer for slightly perturbed input; an unstable algorithm can produce wildly wrong results from small input perturbations or rounding. The condition number of a problem measures the sensitivity of the exact solution to perturbations in the input, separate from the algorithm; a well-conditioned problem has a small condition number. Numerical stability is a property of an algorithm; conditioning is a property of the underlying mathematical problem. Even well-conditioned problems can be solved poorly by unstable algorithms, and ill-conditioned problems are challenging to solve accurately by any algorithm.")
    r("numerical stability", "example",
      "A classic example of instability is computing the smaller root of a quadratic equation by the standard formula. For x^2 + bx + c = 0 with b much larger than sqrt(b^2 - 4c), the smaller root involves the difference of two nearly equal large numbers, with substantial cancellation and loss of precision. For b = 1000 and c = 1: the standard formula gives roots from (-1000 +/- sqrt(996)) / 2; the smaller root involves -500 + sqrt(249), about -500 + 15.78, which loses three or more digits of precision. The remedy is to use the alternative formula x_smaller = -2c / (b + sign(b) sqrt(b^2 - 4c)), which avoids the dangerous subtraction and gives the smaller root accurately. The example shows that algebraically equivalent formulas can have very different numerical behavior, and that paying attention to which operations involve catastrophic cancellation is essential for accurate computation.")
    r("numerical stability", "mechanism",
      "Numerical stability problems arise from the finite precision of floating-point arithmetic, which represents most numbers approximately and rounds intermediate results. Catastrophic cancellation occurs when two nearly equal numbers are subtracted, leaving only a few significant digits in the result. Accumulation of rounding errors can build up over many operations, especially in long iterative computations. Ill-conditioned matrices amplify input perturbations into large solution changes, so even backward-stable algorithms (which produce the exact solution to a slightly perturbed problem) can give large forward errors when the problem itself is ill-conditioned. The mechanisms for ensuring stability include reformulating algorithms to avoid catastrophic cancellation, using higher-precision arithmetic for critical sections, applying iterative refinement (computing residuals and correcting solutions), and choosing algorithms designed for the specific structure of the problem (Cholesky for symmetric positive-definite systems, QR decomposition for least squares).")
    r("numerical stability", "misconception",
      "A common misconception is that more precision (using double instead of single precision, or extended precision) automatically fixes numerical stability problems. While higher precision shifts the threshold of trouble, it does not fundamentally solve issues with unstable algorithms or ill-conditioned problems; switching from double to quadruple precision merely delays the failure rather than preventing it. Another misconception is that a small residual indicates a small error in the solution; in ill-conditioned problems, the residual can be small while the solution is far from correct. People also sometimes assume that stability problems are exotic and unlikely to affect everyday computation; in fact, ill-conditioned matrices arise naturally in many practical settings (interpolating polynomials at evenly spaced points, certain optimization problems, regression with collinear predictors), and naive code can fail dramatically without warning. Numerical analysis as a discipline exists precisely to identify and address these issues with rigorous theory and tested algorithms.")
    r("numerical stability", "comparison",
      "Numerical stability differs from algorithmic complexity in that complexity describes how computation time scales with input size, while stability describes how output errors scale with input perturbations. An algorithm can be fast but unstable, slow but stable, or fast and stable. Compared with conditioning of a problem, stability is a property of an algorithm: well-conditioned problems can be solved unstably and ill-conditioned problems can have stable algorithms (though no algorithm can fully overcome ill-conditioning). Compared with verification (checking that an algorithm correctly implements a specification), stability concerns the propagation of errors from finite-precision arithmetic, separate from logic correctness. Compared with backward and forward error analysis (different ways of accounting for the discrepancy between exact and computed solutions), stability is the framework that connects them, with backward stability (the computed solution is exact for a perturbed input) implying acceptable forward error when the problem is well-conditioned.")
    r("numerical stability", "significance",
      "Numerical stability matters because nearly all scientific and engineering computation depends on numerical methods, and unstable computations can produce silently wrong results that lead to bad decisions or system failures. Catastrophic events traceable to numerical issues include the Patriot missile failure in 1991 (timing errors from accumulated rounding), the Ariane 5 rocket loss in 1996 (overflow in inertial reference system), and the Sleipner A oil platform collapse in 1991 (errors in finite-element mesh). Modern numerical libraries (LAPACK, BLAS, NumPy, scientific Python ecosystem) embed decades of accumulated knowledge about stable algorithms, allowing users to perform reliable computations without re-deriving the underlying theory. Understanding stability and conditioning is essential for anyone writing numerical code, choosing appropriate algorithms, and interpreting results, especially in fields like scientific computing, machine learning, finance, and engineering simulation where errors compound through long computational pipelines.")

    # ---- math: quaternions ----
    r("quaternions", "comparison",
      "Quaternions extend complex numbers to four dimensions: a quaternion has the form a + bi + cj + dk where i, j, k are units satisfying i^2 = j^2 = k^2 = ijk = -1 and the noncommutative relations ij = k, ji = -k, and so on. Compared with complex numbers, quaternions retain associativity and the multiplicative norm property but lose commutativity. Compared with general 4D vectors, quaternions have a multiplication operation that gives them ring structure. Compared with matrices for 3D rotations, quaternions provide a compact (4 numbers vs. 9 for a 3x3 matrix) and numerically robust representation that avoids gimbal lock and is easy to interpolate (slerp algorithm). Compared with rotation vectors (axis-angle representation), quaternions support easier composition of rotations through quaternion multiplication. Modern computer graphics, robotics, aerospace navigation, and molecular dynamics often use quaternions for their advantages in 3D rotation representation.")
    r("quaternions", "definition",
      "Quaternions are a four-dimensional number system invented by William Rowan Hamilton in 1843 that extends the complex numbers and provides a natural algebra for representing rotations in three-dimensional space. A quaternion is a sum a + bi + cj + dk where a, b, c, d are real numbers and i, j, k are imaginary units satisfying Hamilton's relations: i^2 = j^2 = k^2 = ijk = -1, with ij = k, jk = i, ki = j, ji = -k, kj = -i, ik = -j. Quaternion addition is component-wise; quaternion multiplication uses the relations among i, j, k and is associative but not commutative. The norm of a quaternion is sqrt(a^2 + b^2 + c^2 + d^2), and unit quaternions (norm 1) form a sphere in 4D space that doubly covers the rotation group of 3D space. Quaternions are the simplest example of a noncommutative division algebra over the reals.")

    # ---- math: radians vs degrees ----
    r("radians vs degrees", "example",
      "An example illustrating the use of radians: compute the arc length of a circular sector. For a circle of radius 5 with central angle 60 degrees, first convert: 60 degrees equals pi/3 radians, since 360 degrees equals 2 pi radians. Arc length equals radius times angle (in radians), giving 5 times pi/3, about 5.24 units. Using degrees directly without converting would give a meaningless number. Similarly, the formula for the area of a circular sector is (1/2) r^2 theta with theta in radians; for the same example, area equals (1/2)(25)(pi/3), about 13.09 square units. In calculus, the derivative of sin(x) equals cos(x) only when x is in radians; if x were in degrees, the derivative would be (pi/180) cos(x). The radian-based formulas are clean because radians are defined as the dimensionless ratio of arc length to radius, making them the natural unit for angle in mathematical analysis.")
    r("radians vs degrees", "misconception",
      "A common misconception is that radians and degrees are interchangeable units that can be substituted freely; in many formulas (calculus derivatives of trig functions, arc length, sector area), the formulas hold only when angles are in radians, and using degrees gives wrong answers without an explicit conversion factor. Another misconception is that radians are unnecessarily complicated; they are actually the natural mathematical unit because they are dimensionless (ratio of arc length to radius), making formulas cleaner. People also sometimes assume that 360 degrees in a circle is intrinsic; the choice of 360 dates to ancient Babylonian astronomy and is fundamentally arbitrary, while 2 pi radians for a full circle reflects the geometric definition of angle. Finally, calculator users often forget to set the angle mode (degrees or radians) appropriately, leading to silently wrong answers; the same formula sin(30) gives 0.5 in degree mode but -0.988 in radian mode, illustrating the practical importance of unit awareness.")
    r("radians vs degrees", "significance",
      "Radians matter because they are the natural unit for angle in mathematical analysis, simplifying formulas and revealing structural relationships that degree-based versions obscure. The derivative of sin(x) is cos(x) only when x is in radians; with degrees, an awkward factor of pi/180 appears. The Taylor series for sine and cosine, the small-angle approximations sin(x) approximately x and cos(x) approximately 1 - x^2/2, the relationship between angular velocity and linear velocity (v = r omega), and many other formulas all work cleanly in radians. Degrees remain useful in everyday contexts, navigation, and engineering because of historical convention and the convenient divisibility of 360. Higher mathematics, physics, and engineering computation usually convert to radians for analytical work and convert back to degrees only for human-readable output. Understanding both systems and converting fluently between them is a basic skill for scientific and engineering work.")

    # ---- math: the FFT ----
    r("the FFT (fast Fourier transform)", "comparison",
      "The fast Fourier transform (FFT) computes the discrete Fourier transform (DFT) of an n-point signal in O(n log n) operations rather than the O(n^2) of direct computation. Compared with naive DFT computation, the FFT is dramatically faster for moderately large signals (a 1024-point transform is about 100 times faster, and a 1-million-point transform is about 50,000 times faster). Compared with continuous Fourier transforms applied to analog signals, the FFT works on sampled discrete data and is the workhorse of digital signal processing. Compared with related algorithms like the discrete cosine transform (DCT) used in JPEG and many other compression formats, FFT and DCT differ mostly in boundary conditions and basis functions; both are efficient in O(n log n) time. Compared with wavelet transforms which use localized basis functions of varying scale, FFT uses globally supported sinusoidal basis functions, making it ideal for stationary signals but less suited to transient features.")
    r("the FFT (fast Fourier transform)", "misconception",
      "A common misconception is that the FFT requires the input length n to be a power of 2; while the original Cooley-Tukey algorithm works most cleanly for power-of-2 lengths, modern FFT libraries (FFTW, MKL, cuFFT) handle arbitrary lengths efficiently using mixed-radix algorithms, with composite numbers benefiting most. Another misconception is that the FFT 'finds frequencies' in some absolute sense; it computes the discrete Fourier transform of a sampled signal, which is the projection onto a finite set of complex exponentials at frequencies determined by the sampling rate and signal length. People also sometimes assume that the FFT is the same as the continuous Fourier transform; the DFT is its discrete analog and approximates the continuous transform under appropriate sampling and windowing conditions, with care needed to avoid aliasing and spectral leakage. Finally, the FFT's output is complex-valued, and misinterpreting the relationship between magnitude, phase, and the original signal is a common source of error in applications.")
    r("the FFT (fast Fourier transform)", "significance",
      "The FFT matters because it made digital signal processing practical at scale, with consequences ranging from telephone networks to medical imaging to audio compression. Without an O(n log n) algorithm, transforming a typical audio signal (millions of samples) would require trillions of operations and be infeasible; with the FFT, the same transform takes milliseconds. Modern applications include audio compression (MP3, AAC), image compression (JPEG, related to DCT), digital communications (OFDM modulation in WiFi, 4G/5G, DSL), seismic data analysis, MRI image reconstruction, radar and sonar processing, spectroscopy, gravitational wave detection (LIGO uses FFT for noise characterization), and many more. The Cooley-Tukey FFT algorithm published in 1965 (with earlier discoveries by Gauss and others) is widely cited as among the most important algorithms of the 20th century. Hardware implementations of the FFT are built into many digital signal processors and are available as efficient libraries on essentially every computer architecture.")

    # ---- math: the Pythagorean theorem ----
    r("the Pythagorean theorem", "significance",
      "The Pythagorean theorem matters because it is the fundamental relationship in Euclidean geometry between the sides of a right triangle and underlies the definition of distance in coordinate geometry. The theorem states that in any right triangle, the square of the length of the hypotenuse equals the sum of the squares of the lengths of the other two sides. Beyond its direct geometric content, the theorem extends naturally to Euclidean distance in any number of dimensions: the distance between two points equals the square root of the sum of the squares of their coordinate differences. This formula underlies essentially all of Euclidean geometry, calculus on Euclidean spaces, optimization (least squares regression minimizes Euclidean distance), and engineering applications from surveying to GPS positioning. The theorem also appears in special relativity (the spacetime interval is a Pythagorean-like combination of spatial and temporal differences with a sign flip) and in quantum mechanics (probabilities are squared magnitudes of complex amplitudes that combine Pythagorean-style).")
    r("the Pythagorean theorem", "mechanism",
      "The Pythagorean theorem can be proved many ways, with hundreds of distinct proofs known. One classical proof uses similar triangles: drop a perpendicular from the right angle to the hypotenuse, dividing the original triangle into two smaller right triangles each similar to the original. The similarity gives proportions among the sides that, when manipulated, yield the relationship a^2 + b^2 = c^2 between the legs and hypotenuse. Another proof uses areas: arrange four copies of the triangle around a square of side c, leaving a central square of side b - a, and compare areas. Algebraically, a^2 + b^2 = c^2 follows from the law of cosines (c^2 = a^2 + b^2 - 2ab cos(C)) when the angle C is 90 degrees and cos(C) = 0. The mechanism by which the theorem 'works' is the special role of perpendicularity (orthogonality), which generalizes to inner product spaces where the same Pythagorean relation holds for orthogonal vectors.")
    r("the Pythagorean theorem", "comparison",
      "The Pythagorean theorem is a special case of the law of cosines, which states c^2 = a^2 + b^2 - 2ab cos(C) for any triangle with sides a, b, c and the angle C opposite side c. When C is 90 degrees, cos(C) is 0 and the law of cosines reduces to the Pythagorean theorem. Compared with the law of sines (which relates sides and opposite angles by ratios), the law of cosines and the Pythagorean theorem relate squared lengths. Compared with the spherical Pythagorean theorem (cos(c/R) = cos(a/R) cos(b/R) for a right triangle on a sphere of radius R), the planar version is the limit as R goes to infinity. Compared with the hyperbolic Pythagorean theorem (cosh(c) = cosh(a) cosh(b) for a right triangle in hyperbolic geometry), the planar version is again a limit. Each non-Euclidean version reduces to the planar one when curvature is small or distances are short.")

    # ---- math: the four-color theorem ----
    r("the four-color theorem", "definition",
      "The four-color theorem states that any planar map can be colored with at most four colors so that no two adjacent regions share the same color, where adjacent means sharing more than a single point of boundary. The theorem was conjectured in 1852 by Francis Guthrie and proven only in 1976 by Kenneth Appel and Wolfgang Haken using extensive computer assistance. Their proof reduced the infinite space of possible maps to a finite set of approximately 1,500 unavoidable configurations and showed each was four-reducible, requiring computer verification of cases beyond what humans could check by hand. The proof was historically significant as the first major mathematical theorem proved with essential help from a computer, and it generated debate about the nature of mathematical proof. Subsequent simplifications (Robertson, Sanders, Seymour, and Thomas in 1996) reduced the case count and provided cleaner verification, but the proof still relies on computer-checked enumeration.")
    r("the four-color theorem", "example",
      "The map of US states is a familiar example where four colors suffice. Coloring states so no two bordering states share a color requires careful planning but never more than four distinct colors. The four-color theorem guarantees this for any map, including ones with much more complex shapes than US states. A related but easier example is checkerboard coloring, which uses only two colors; any bipartite planar graph (like checkerboards) can be two-colored. More interesting are maps where four colors are actually necessary: consider a central region surrounded by three regions that all touch each other and the center, like a pie with three wedges and a small central disk; this configuration forces a fourth color for the central region. The example shows that the four-color upper bound is tight: some maps require exactly four colors, and no fewer suffice in general.")
    r("the four-color theorem", "significance",
      "The four-color theorem matters historically as a milestone in computational mathematics and as a long-standing open problem that resisted purely human proof for over a century. The Appel-Haken computer-assisted proof in 1976 sparked debate about what constitutes a valid mathematical proof: must a proof be checkable by humans, or is computer verification of finite cases acceptable? Mathematicians have largely accepted computer-assisted proofs in this and other cases (the Kepler conjecture about sphere packing, the proof of the boolean Pythagorean triples problem) when the algorithms are themselves verified. Beyond its meta-mathematical interest, the four-color theorem connects to graph coloring problems with practical applications: scheduling (assigning time slots so conflicting events do not overlap), register allocation in compilers (assigning registers to variables so simultaneously live variables get different registers), frequency assignment in cellular networks, and Sudoku puzzles. The chromatic number generalization extends to arbitrary graphs and remains computationally hard (NP-hard) in general.")
    r("the four-color theorem", "misconception",
      "A common misconception is that the four-color theorem applies to all maps; it applies specifically to planar maps where regions are simply connected (each region is a single connected piece) and adjacency means sharing a border segment, not just a corner point. Maps on a torus or other higher-genus surfaces require more colors (seven on a torus). Maps with non-simply-connected regions (like one country with disconnected exclaves all needing the same color) can require more than four colors. Another misconception is that a four-coloring is unique; many distinct colorings typically work for a given map. People also sometimes think the proof is trivial because the answer is simple; the proof is highly nontrivial and requires hundreds of pages of analysis plus computer checking. Finally, the assumption that a 'simple' proof must exist has driven decades of attempts; while simplifications have been found, no proof avoiding computer verification of substantial case analysis has emerged.")

    # ---- math: the pigeonhole principle ----
    r("the pigeonhole principle", "definition",
      "The pigeonhole principle states that if more pigeons are placed into pigeonholes than there are holes, then at least one hole must contain more than one pigeon. Generalized: if n + 1 or more objects are placed into n boxes, then at least one box contains at least two objects. The strong pigeonhole principle: if N objects are placed into k boxes, then at least one box contains at least ceiling(N/k) objects. Despite its almost trivial statement, the pigeonhole principle yields surprisingly powerful conclusions. It is used to prove existence of certain combinatorial configurations without constructing them explicitly. The principle is one of the most basic and widely used tools in combinatorial reasoning, often invoked by name in mathematical proofs across discrete mathematics, number theory, and computer science.")
    r("the pigeonhole principle", "mechanism",
      "The pigeonhole principle works by counting: if we try to assign N objects to k holes with each hole getting at most one object, we can accommodate at most k objects, so any larger N forces some hole to receive multiple objects. The strong version generalizes by considering the average load: if N objects are distributed among k holes, the average is N/k objects per hole, and at least one hole must equal or exceed the average, hence at least ceiling(N/k). The mechanism by which the principle proves nontrivial results is through clever choice of pigeons and holes. A typical proof identifies the objects to be placed and the categories that constitute holes, shows the count exceeds the number of categories, and concludes that some category must contain multiple objects with consequences for the original problem.")
    r("the pigeonhole principle", "comparison",
      "The pigeonhole principle differs from probabilistic counting arguments in being an exact deterministic statement rather than an expected-value bound. Compared with the probabilistic method (which proves existence by showing the probability of a desired structure is positive), pigeonhole gives certainty when the count exceeds capacity. Compared with double counting (counting the same set in two ways and equating the results), pigeonhole specifically addresses the consequences of distributing items into categories. Compared with the Ramsey theory results (which guarantee monochromatic substructures in colored configurations), pigeonhole is often the starting point for Ramsey-type arguments. Despite the simplicity of its statement, the pigeonhole principle is qualitatively different from arithmetic counting in producing existence claims that would be hard to prove constructively.")
    r("the pigeonhole principle", "misconception",
      "A common misconception is that the pigeonhole principle requires a particular structure or order on the objects; it works purely on counts, regardless of the nature of the objects or the assignment. Another misconception is that the principle's results are obvious and don't merit proof; many surprising mathematical results have pigeonhole proofs that are not at all obvious in advance. People also sometimes apply the principle incorrectly by miscounting either the pigeons or the holes; the choice of what plays the role of each is often the creative step in a pigeonhole argument. Finally, the assumption that pigeonhole gives constructive results is wrong; it shows that some configuration exists without identifying which, so it is fundamentally a non-constructive existence argument that may give no information about how to find the configuration.")
    r("the pigeonhole principle", "example",
      "A classic example: among any 13 people, at least two share a birth month. There are 12 months (holes) and 13 people (pigeons), so at least one month must contain at least two birthdays. Another example: in any sequence of 11 distinct integers chosen from 1 to 20, some pair must sum to 21. Pair the numbers as (1, 20), (2, 19), ..., (10, 11), giving 10 pairs (holes); 11 numbers (pigeons) must include both members of some pair. A more substantial example: among any 5 points placed in a unit square, two points must be within sqrt(2)/2 of each other. Divide the square into 4 unit-quarter squares (each a 1/2 by 1/2 square); 5 points in 4 holes means two points share a quarter, and two points in a 1/2 by 1/2 square are at most sqrt(2)/2 apart. Pigeonhole repeatedly produces such elegant existence proofs.")

    # ---- math: the traveling salesman problem ----
    r("the traveling salesman problem", "definition",
      "The traveling salesman problem (TSP) asks for the shortest possible route that visits each city in a given list exactly once and returns to the origin city. Formally, given n cities and pairwise distances between them, find a Hamiltonian cycle of minimum total weight. The TSP is one of the most studied combinatorial optimization problems and is NP-hard, meaning no polynomial-time exact algorithm is known and one is widely believed not to exist. Variants include the symmetric TSP (distances are the same in both directions, equivalent to undirected edges), the asymmetric TSP (distances may differ by direction), the Euclidean TSP (cities are points in the plane with straight-line distances), and the metric TSP (distances satisfy the triangle inequality). Despite its computational difficulty, instances with thousands or even tens of thousands of cities can be solved to optimality with sophisticated software like Concorde.")
    r("the traveling salesman problem", "mechanism",
      "TSP solvers combine exact and heuristic methods. For exact solution, integer programming formulations using cutting-plane algorithms (subtour elimination, comb inequalities) and branch-and-cut have made huge instances tractable. For heuristic solution, the nearest-neighbor heuristic (start anywhere, always go to the nearest unvisited city) and Christofides' algorithm (which achieves a 1.5x optimal bound for metric TSP) provide quick reasonable solutions. Local search methods like 2-opt and 3-opt iteratively improve tours by swapping edges. Lin-Kernighan and its variants are among the most effective practical heuristics, often finding solutions within fractions of a percent of optimal. Genetic algorithms, simulated annealing, and ant colony optimization provide alternative metaheuristic approaches. Modern TSP software combines these methods, often using heuristics to find high-quality starting solutions and then exact methods to verify or improve optimality.")
    r("the traveling salesman problem", "comparison",
      "The TSP is closely related to but distinct from several other graph problems. Compared with the shortest path problem (find the shortest route from A to B), TSP is much harder because all cities must be visited, requiring choices at every city rather than greedy selection. Compared with the Hamiltonian cycle problem (does a Hamiltonian cycle exist?), TSP is the optimization version asking for the shortest such cycle; both are NP-hard. Compared with the Chinese postman problem (find a closed walk visiting every edge with minimum cost), TSP visits every vertex while the Chinese postman visits every edge. Compared with vehicle routing problems (multiple vehicles, capacity constraints, time windows), TSP is the simpler single-vehicle special case. Compared with the assignment problem (find a matching of minimum cost in a bipartite graph), TSP has additional sequential structure making it harder. The TSP serves as a benchmark for combinatorial optimization techniques and inspires algorithmic developments that often transfer to related problems.")

    # ---- math: the unit circle ----
    r("the unit circle", "significance",
      "The unit circle matters because it provides the geometric definition of trigonometric functions and underlies the analysis of periodic phenomena throughout mathematics, science, and engineering. The unit circle is the circle of radius 1 centered at the origin in the coordinate plane, defined by x^2 + y^2 = 1. For any angle theta measured from the positive x-axis, the point on the unit circle at that angle has coordinates (cos(theta), sin(theta)), making the unit circle the geometric realization of trigonometric functions. From this single picture, identities like sin^2(theta) + cos^2(theta) = 1 are immediate (just the equation of the circle), the periodicity of sine and cosine reflects going all the way around the circle, and identities involving sums and differences of angles follow from basic geometric facts about rotations. The unit circle generalizes to higher-dimensional spheres and to the complex unit circle (where multiplication by e^(i theta) implements rotation), making it foundational across mathematics.")
    r("the unit circle", "example",
      "An example: find sine and cosine for angles at the standard reference points. At theta = 0, the point on the unit circle is (1, 0), so cos(0) = 1 and sin(0) = 0. At theta = pi/2 (90 degrees), the point is (0, 1), so cos(pi/2) = 0 and sin(pi/2) = 1. At theta = pi (180 degrees), (-1, 0), giving cos(pi) = -1 and sin(pi) = 0. At theta = pi/4 (45 degrees), the point is (sqrt(2)/2, sqrt(2)/2), so cos and sin are both sqrt(2)/2. At theta = pi/3 (60 degrees), (1/2, sqrt(3)/2), so cos(pi/3) = 1/2 and sin(pi/3) = sqrt(3)/2. At theta = pi/6 (30 degrees), (sqrt(3)/2, 1/2). The unit circle visualization makes these standard values memorable and connects them to geometric constructions like 30-60-90 and 45-45-90 triangles inscribed in the circle.")

    # ---- math: topology basics ----
    r("topology basics", "definition",
      "Topology is the branch of mathematics studying properties of spaces preserved under continuous deformation: stretching, squeezing, twisting, but not tearing or gluing. Two spaces are topologically equivalent (homeomorphic) if there is a continuous bijection with continuous inverse between them. From a topological standpoint, a coffee cup and a doughnut are equivalent (both are surfaces with one hole), while a sphere and a doughnut are not. Topology generalizes from familiar geometric objects (curves, surfaces, manifolds) to abstract topological spaces defined by a collection of open sets satisfying axioms (closed under finite intersections, arbitrary unions, contains the empty set and the whole space). Subfields include point-set topology (general properties of topological spaces), algebraic topology (using algebraic invariants like fundamental groups, homology, cohomology to distinguish spaces), and differential topology (smooth manifolds and their structure). Topology connects deeply to geometry, analysis, and algebra and underlies modern formulations of physics from gauge theory to condensed matter.")

    # ---- math: triangle congruence and similarity ----
    r("triangle congruence and similarity", "definition",
      "Two triangles are congruent if they have the same shape and size: corresponding sides have equal lengths and corresponding angles have equal measures. Two triangles are similar if they have the same shape but possibly different sizes: corresponding angles are equal and corresponding sides are proportional. Several criteria establish congruence without checking all six measurements: side-side-side (SSS) requires three pairs of equal corresponding sides; side-angle-side (SAS) requires two sides and the included angle; angle-side-angle (ASA) requires two angles and the included side; angle-angle-side (AAS) requires two angles and a non-included side; for right triangles, hypotenuse-leg (HL) suffices. Similarity criteria include angle-angle (AA), since two pairs of equal angles force the third pair to also be equal; side-side-side similarity (SSS), where all sides are proportional; and side-angle-side similarity (SAS), where two sides are proportional with an equal included angle.")
    r("triangle congruence and similarity", "mechanism",
      "Congruence and similarity work through the rigidity of triangles under given constraints. Once you specify enough information (three sides, or two sides and the included angle, etc.), the triangle is uniquely determined up to position and orientation, with no freedom for variation. The mechanism by which the criteria succeed is that they provide enough constraints to fix all unspecified measurements: in SSS, the three sides determine the angles via the law of cosines; in SAS, the third side follows from the law of cosines and then the remaining angles from the law of sines. Similarity works analogously but allows scaling: equal angles force equal shape, and the proportionality constant is determined by the size ratio. Importantly, side-side-angle (SSA) is generally not a valid congruence criterion because it can determine zero, one, or two distinct triangles depending on the specific values (the ambiguous case in trigonometry).")

    # ---- math: trigonometric identities ----
    r("trigonometric identities", "mechanism",
      "Trigonometric identities work by exploiting relationships among trigonometric functions that follow from their geometric and analytic definitions. The Pythagorean identities (sin^2 + cos^2 = 1, 1 + tan^2 = sec^2, 1 + cot^2 = csc^2) follow directly from the unit-circle definition of sine and cosine. Sum and difference formulas (sin(a + b) = sin(a) cos(b) + cos(a) sin(b)) follow from rotation matrices or geometric constructions. Double-angle and half-angle formulas follow as special cases. Product-to-sum and sum-to-product formulas are convenient rearrangements. Each identity provides an algebraic substitution that simplifies expressions, evaluates limits, computes integrals, or solves equations involving trig functions. The mechanism by which these identities help in calculations is by converting between forms (sums vs. products, individual angles vs. multiple angles) so that the form most amenable to the next step in the calculation is available.")
    r("trigonometric identities", "significance",
      "Trigonometric identities matter because they enable manipulation of expressions involving trigonometric functions, essential to integration, equation solving, signal processing, and physics. In calculus, identities like sin^2(x) = (1 - cos(2x))/2 convert powers of trig functions into linear combinations that integrate easily. In differential equations, identities transform between forms compatible with operator methods. In Fourier analysis, the orthogonality of sines and cosines relies on integrals computed via product-to-sum identities. In electrical engineering, AC circuit analysis uses identities to combine sinusoids of the same frequency. In physics, identities simplify expressions for wave superposition, oscillator dynamics, and rotational motion. In computer graphics, identities optimize transformations and rotations. The identities also reveal deep structure: Euler's formula e^(i x) = cos(x) + i sin(x) embeds all trig identities in the algebra of complex exponentials, often providing the cleanest derivations.")
