#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank: technology topics (fresh for batch H)."""


def register(T):
    T["how an SQL query optimizer plans execution"] = {
        "_cat": "technology",
        "what": "the database component that translates a declarative SQL query into an efficient procedural execution plan by enumerating alternatives, estimating costs from table statistics, and choosing the cheapest plan within a search budget",
        "how": "the optimizer parses the SQL into a logical plan, applies rewrite rules (predicate pushdown, join reordering, subquery flattening), and enumerates physical operators (index scan, hash join, merge join, nested loop). It estimates row counts using histograms and cardinality models, computes IO and CPU costs for each operator, and uses dynamic programming or System R-style enumeration to find the lowest-cost plan. The chosen plan is cached for reuse",
        "why": "query optimization decides whether a query runs in milliseconds or hours. Modern OLAP and OLTP workloads depend on the optimizer making good choices over schemas with hundreds of tables and indexes. Bad cardinality estimates are the leading cause of slow queries in production",
        "vs": "rule-based optimizers (older Oracle, simple SQL engines) differ from cost-based optimizers (Postgres, modern SQL Server, Snowflake) by applying fixed transformations rather than estimating costs. Volcano-style optimizers differ from Cascades by their search strategy, and adaptive query execution differs by allowing replanning mid-query",
        "ex": "Postgres EXPLAIN on a 3-table join shows estimated row counts and chosen join order. If the estimates are wrong (skewed data, missing statistics), the optimizer might pick a nested loop join over a billion-row table when a hash join would be 1000 times faster. ANALYZE refreshes the statistics it relies on",
        "mis": "people think the optimizer always chooses the best plan. It picks the cheapest plan it considers within its search budget; complex queries can have plan spaces too large to enumerate, and bad statistics or hint mismatches mislead it. Another myth is that adding indexes always helps; too many indexes confuse the optimizer and slow writes",
    }

    T["how OAuth 2.0 authorizes API access"] = {
        "_cat": "technology",
        "what": "an authorization framework that lets a third-party application obtain limited access to a user's resources on a service without giving it the user's credentials, by exchanging consent for access tokens via a defined flow",
        "how": "the user is redirected to the resource server's authorization endpoint, where they log in and consent to specific scopes. The server returns an authorization code to the client's redirect URI. The client exchanges the code (plus its client secret) at the token endpoint for an access token and refresh token. The client sends the access token with each API request; the resource server validates it and serves data within the granted scopes. Refresh tokens replace expired access tokens without re-prompting the user",
        "why": "OAuth 2.0 is the de facto standard for delegated authorization on the web, powering 'Sign in with Google/Apple/GitHub', third-party integrations on every major platform, and mobile-app access to cloud services. Without it, every integration would require sharing passwords",
        "vs": "OAuth 2.0 differs from OAuth 1.0 by removing per-request signing in favor of TLS, simplifying client code at the cost of relying on transport security. It differs from OpenID Connect, which adds an identity layer (ID tokens) on top of OAuth. It differs from API keys, which are static and lack user context or fine-grained scopes",
        "ex": "a calendar app requesting access to your Google Calendar redirects you to accounts.google.com, you grant 'read events' scope, the app receives a code, exchanges it for an access token, and starts pulling events. You can revoke access at any time without changing your Google password",
        "mis": "people think OAuth 2.0 is authentication. It is authorization; OpenID Connect adds authentication on top. Another myth is that OAuth tokens are inherently secure; they must be transmitted over TLS, scoped narrowly, and short-lived, with refresh tokens kept server-side, or compromise becomes severe",
    }

    T["how content-addressable storage works"] = {
        "_cat": "technology",
        "what": "a storage architecture that retrieves data by a cryptographic hash of its content rather than by location, so identical content always has the same address and any tampering changes the address",
        "how": "when data is stored, the system computes a hash (typically SHA-256 or similar) and uses it as the key. Lookups by hash retrieve the original data; clients verify by recomputing the hash. Deduplication is automatic since identical content collides on the same address. Trees of content addresses (Merkle trees) verify large collections by hashing children up to a single root",
        "why": "content addressing underlies Git (every commit references trees of file blobs by hash), IPFS, Docker image layers, modern backup systems, and blockchain. It enables tamper-evidence, deduplication, distributed caching, and reproducible builds, fundamentally changing how distributed systems handle data identity",
        "vs": "content-addressable storage differs from location-addressable storage (file paths, URLs), where the same data can have many addresses and the same address can change content over time. It differs from key-value stores, which use arbitrary keys, by deriving keys from content. It differs from databases, which support queries beyond exact lookup",
        "ex": "Git uses SHA-1 (transitioning to SHA-256) hashes to identify blobs, trees, and commits. Two files with the same contents have the same blob hash regardless of name or path, so Git deduplicates automatically and can verify history integrity by walking parent commit hashes",
        "mis": "people think hash collisions undermine content addressing. Cryptographic hashes have collision probability so low that any practical collision implies a break of the algorithm, not random chance. Another myth is that content addressing makes mutation impossible; you mutate by storing new content and updating a separate name-to-hash pointer (Git refs, IPNS)",
    }

    T["how a write-ahead log ensures durability"] = {
        "_cat": "technology",
        "what": "a database technique where every change is first recorded sequentially to a log on persistent storage and synced before the in-memory state is updated, so a crash can be recovered by replaying the log",
        "how": "before modifying a database page in memory, the system writes a log record describing the change (page id, before-image, after-image, transaction id) to the WAL and fsyncs it to disk. Pages can be flushed lazily; the in-memory state moves ahead of the on-disk pages, but the log records the truth. On crash, recovery replays committed transactions from the log and undoes uncommitted ones, bringing the database to a consistent state",
        "why": "WAL gives ACID durability and atomicity efficiently: a single sequential disk write per transaction, instead of many random writes. It enables crash recovery, point-in-time restore, replication (ship the log), and incremental backups. Most production databases (Postgres, MySQL, SQLite, Oracle, SQL Server) center on a WAL",
        "vs": "WAL differs from shadow paging (used by older systems and SQLite alternatives), which writes copies and atomically swaps. It differs from full-page checkpoints, which are heavier. It differs from append-only stores like LSM trees, which use a different durability model based on immutable sorted runs and a memtable journal",
        "ex": "Postgres pgbench transactions write WAL records to pg_wal, sync them on commit, and only later flush dirty pages during checkpoints. Replication ships pg_wal segments to standbys, which replay them to stay in sync. After a crash, the postmaster runs WAL recovery before accepting connections",
        "mis": "people think WAL slows writes. The sequential log write is much faster than random page writes; WAL accelerates rather than slows commits. Another myth is that WAL alone makes the database 'safe'; durability also requires fsync to honor flush semantics, which some filesystems and disks have notoriously violated",
    }

    T["how WebRTC enables peer-to-peer media"] = {
        "_cat": "technology",
        "what": "a browser standard that lets two endpoints exchange real-time audio, video, and data directly without a server in the media path, using established codecs, encrypted transport, and NAT traversal techniques",
        "how": "peers exchange offer/answer SDP descriptions through a signaling server (typically WebSocket), describing codecs and network candidates. ICE gathers candidate addresses (host, server-reflexive via STUN, relayed via TURN if needed) and connectivity checks pick a working pair. DTLS handshakes establish keys, then SRTP encrypts media and SCTP handles data channels. Codec negotiation typically settles on Opus for audio and VP8/VP9/AV1/H.264 for video",
        "why": "WebRTC powers Google Meet, Discord, Microsoft Teams (web), customer support video, browser-based games, and most modern in-browser real-time products. It removed the need for plugins like Flash or proprietary clients and made low-latency media a web platform feature",
        "vs": "WebRTC differs from HLS or DASH streaming, which are server-to-client and tolerate seconds of latency. It differs from WebSockets, which are general-purpose duplex but lack media optimizations. It differs from SIP/RTP stacks of legacy VoIP in being built into browsers and using TLS-derived security from the start",
        "ex": "a one-on-one Meet call exchanges SDP via a Google signaling server, ICE finds a path (often peer-to-peer when networks allow, otherwise relayed via TURN), and Opus + VP9 streams flow encrypted between browsers. Larger group calls use Selective Forwarding Units that mix WebRTC with server-side routing",
        "mis": "people think WebRTC is always peer-to-peer. Behind symmetric NATs or for group calls, traffic is relayed; the 'P2P' label refers to the API model more than the network path. Another myth is that WebRTC has no signaling; the signaling channel is required but deliberately unspecified to fit any application",
    }

    T["how a kernel handles a system call"] = {
        "_cat": "technology",
        "what": "the controlled mechanism by which a user-space program requests a privileged service from the operating system kernel, transitioning briefly into kernel mode to perform the operation and returning a result",
        "how": "the program loads syscall arguments into registers and executes a special instruction (syscall on x86-64, svc on ARM64). The CPU switches to kernel mode and jumps to a fixed entry point. The kernel saves user state, dispatches based on the syscall number to the appropriate handler (read, write, mmap, futex), validates arguments, performs the operation, sets a return value, and resumes the user program. The transition costs hundreds of nanoseconds plus any work done",
        "why": "system calls are the boundary between every user program and the kernel-managed resources it depends on (files, sockets, memory, time, scheduling). Their cost shapes high-performance design: io_uring batches syscalls, async runtimes minimize blocking calls, and copy-on-write fork avoids redundant entries",
        "vs": "system calls differ from library calls (which run entirely in user space) and from interrupts (which originate from hardware rather than user requests). They differ from VDSO calls (gettimeofday) that the kernel maps read-only into user space to avoid the mode transition entirely",
        "ex": "calling read(fd, buf, n) on Linux executes a syscall instruction with rax=0, rdi=fd, rsi=buf, rdx=n. The kernel validates the file descriptor, may block waiting for data, copies bytes from the kernel buffer to user buf, and returns the count or error. perf or strace can show every syscall a process makes",
        "mis": "people think syscalls are slow because of the mode switch. The bare transition is fast (~100ns); slowness usually comes from the work the kernel does (IO waits, contention). Another myth is that all kernel access is via syscalls; signals, /proc reads, and shared memory expose other surfaces",
    }

    T["how columnar storage accelerates analytics"] = {
        "_cat": "technology",
        "what": "a data layout where values of the same column are stored contiguously rather than rows being grouped together, enabling fast scans, high compression, and CPU-efficient query execution for analytical workloads",
        "how": "instead of storing complete rows, the storage engine writes each column as its own contiguous array, often grouped into row groups. Each column compresses well because adjacent values share types and distributions; common encodings include dictionary, run-length, and bit-packing. Queries that touch few columns read only those columns from disk, and vectorized execution processes batches of column values with SIMD",
        "why": "columnar formats (Parquet, ORC, Arrow, columnar engines like ClickHouse, DuckDB, BigQuery, Snowflake) are the foundation of modern analytics. Compression ratios of 5-20x are routine; queries reading only a few columns avoid 90 percent of IO. They make multi-terabyte analytics feasible on modest hardware",
        "vs": "columnar storage differs from row storage (Postgres heap tables, MySQL InnoDB), which is faster for OLTP fetches of full rows but slower for column-wide aggregates. It differs from key-value or document stores, which optimize for different access patterns. Hybrid systems (HTAP) try to combine both",
        "ex": "a sales table with 100 columns and a billion rows queried as 'SELECT SUM(amount) WHERE date BETWEEN ... GROUP BY country' reads only date, amount, and country in a columnar store. In Parquet on S3, that scan can finish in seconds where a row-store full scan would take minutes",
        "mis": "people think columnar always wins. It loses for workloads dominated by single-row reads or many-column inserts, which is why OLTP databases stick with rows. Another myth is that columnar means no indexes; modern engines combine column statistics, zone maps, and bloom filters to skip data without traditional B-tree indexes",
    }

    T["how a distributed lock service like ZooKeeper works"] = {
        "_cat": "technology",
        "what": "a coordination service that exposes a hierarchical filesystem-like namespace of small data nodes (znodes) replicated across an odd-numbered ensemble, with strong consistency guarantees that let clients implement distributed locks, leader election, and configuration",
        "how": "ZooKeeper runs an ensemble using the Zab consensus protocol, similar to multi-Paxos. One server is the leader; followers replicate writes. Clients connect to any server, but writes are forwarded to the leader and committed only after a quorum acknowledges. Ephemeral znodes vanish when the creating session ends; sequential znodes get monotonic suffixes. Watches notify clients of changes. Locks use ephemeral sequential znodes: the smallest-numbered node holds the lock; others watch the next-smaller node",
        "why": "ZooKeeper has been the coordination backbone of Hadoop, HBase, Kafka (until KRaft), Solr, and many in-house systems. It provides strong primitives that are otherwise hard to build correctly in a distributed system; getting locking and leader election wrong has been a perennial source of split-brain bugs",
        "vs": "ZooKeeper differs from etcd (Raft-based, gRPC, used by Kubernetes) and Consul (Raft + service discovery) in protocol and ecosystem. It differs from Redis-based locking, which lacks the same consensus guarantees and can fail under partitions. It differs from a database lock table, which works only within one database",
        "ex": "Kafka brokers historically used ZooKeeper for cluster membership, controller election, and topic metadata. Each broker registers an ephemeral znode; the controller is the broker that successfully creates a special znode. If the controller crashes, its ephemeral node disappears, and another broker takes over",
        "mis": "people think ZooKeeper scales horizontally for write throughput. Adding nodes increases read throughput but not writes (and can slow them, since quorum size grows). Another myth is that ZooKeeper handles large data; znodes are limited to 1 MB by design and best kept under a few KB",
    }

    T["how zero-copy networking improves throughput"] = {
        "_cat": "technology",
        "what": "a set of techniques that eliminate redundant memory copies between user space and kernel buffers when sending data over the network, often by mapping or referencing pages directly rather than copying them",
        "how": "traditional sockets read disk data into a kernel buffer, copy to user space, and copy back to a socket buffer for transmission, four context switches and three copies. Zero-copy paths like sendfile() instruct the kernel to copy directly from the page cache to the socket, eliminating user-space copies. splice() pipes between file descriptors. io_uring with registered buffers and direct splice performs even less work. RDMA goes further by letting NICs read application memory directly",
        "why": "zero-copy is critical for high-throughput servers: web caches, video CDNs, file servers, and message queues like Kafka. At 100 Gbps line rate, each avoided copy frees substantial CPU; some systems would be CPU-bound long before saturating the NIC otherwise",
        "vs": "zero-copy differs from buffer pooling (which still copies but reuses memory), from generic asynchronous IO (which is about non-blocking, not avoiding copies), and from kernel bypass like DPDK, which is more aggressive (the entire stack is in user space) and not zero-copy in the same sense",
        "ex": "Kafka's broker uses sendfile() to deliver log segments to consumers, copying directly from the page cache to the socket. The same technique gives nginx its high static-file throughput on Linux. With io_uring, even produce paths can avoid extra copies",
        "mis": "people think zero-copy means literally zero memory traffic. There are still DMA transfers and cache effects; 'zero-copy' refers specifically to eliminating CPU-driven copies. Another myth is that it always wins; for small messages, the copy is cheap, and the bookkeeping for zero-copy can outweigh the savings",
    }

    T["how progressive web apps work"] = {
        "_cat": "technology",
        "what": "web applications that use service workers, web app manifests, and modern browser APIs to deliver app-like experiences from a URL, with offline support, install-to-home-screen, push notifications, and background sync",
        "how": "a service worker is a JavaScript file that runs in the background, intercepting network requests via a fetch event handler so it can serve cached responses or queue writes when offline. A web app manifest describes name, icons, start URL, and display mode for installation. Browsers prompt to install when criteria are met. Push messages, periodic background sync, and the Cache and IndexedDB APIs enable functionality that previously required native apps",
        "why": "PWAs let teams ship a single codebase that runs cross-platform, installs from any URL, and updates without app stores. They power Twitter Lite, Pinterest, Starbucks, and many enterprise tools, often replacing legacy mobile apps when reach matters more than deep platform integration",
        "vs": "PWAs differ from native apps in being installable from URLs without a store and limited to web platform APIs (no full filesystem, limited Bluetooth on iOS). They differ from Electron-style desktop apps in not bundling a runtime; the browser is the runtime. They differ from plain web pages in offering offline, push, and install capabilities",
        "ex": "Twitter Lite cut bandwidth use sharply by combining a service worker that caches the shell and recent timeline data with selective image loading. Users on slow networks could still scroll cached content offline, and an install prompt offered a home-screen icon that launched the app full-screen",
        "mis": "people think PWAs replace native apps in every domain. Heavy gaming, deep system integration, and certain device APIs still favor native. Another myth is that service workers run continuously; they are event-driven and can be terminated by the browser when idle, requiring careful state design",
    }

    T["how a Bloom filter saves memory"] = {
        "_cat": "technology",
        "what": "a space-efficient probabilistic data structure that tests whether an element belongs to a set, using a bit array and multiple hash functions to give no false negatives but a controlled false positive rate",
        "how": "initialize a bit array of m zeros. To insert an element, hash it with k independent hash functions to get k positions and set those bits. To query, hash with the same k functions; if any of those bits is zero, the element is definitely absent; if all are set, the element is probably present (subject to false positive probability that grows with load). Sizing m and k for the expected number of elements n controls the false positive rate",
        "why": "Bloom filters let large databases skip disk reads, networks deduplicate requests, and crawlers avoid revisiting URLs, all with kilobytes where exact sets would require megabytes. LSM-tree storage engines (Cassandra, RocksDB, LevelDB) use them on every SSTable; CDNs and caches use them to short-circuit lookups",
        "vs": "Bloom filters differ from hash sets in trading exactness for space, from cuckoo filters in using bits without item residues (cuckoo filters allow deletions), and from count-min sketches, which estimate frequencies rather than membership. They differ from quotient filters, which support better cache behavior and merging",
        "ex": "Chrome historically used a Bloom filter of malicious URLs as a first check before contacting Safe Browsing servers. The filter occupies a small download yet rules out the vast majority of safe URLs without a network round trip. Apparent matches trigger a definitive server check",
        "mis": "people think Bloom filters give exact answers. They guarantee no false negatives but allow false positives; the trick is choosing parameters so the false positive rate is acceptable. Another myth is that you can delete from them easily; standard Bloom filters do not support deletion (counting Bloom filters do, at extra space)",
    }

    T["how a hash function avoids collisions"] = {
        "_cat": "technology",
        "what": "a function that maps inputs of arbitrary size to fixed-size outputs (digests) such that small changes in input produce dramatically different outputs and finding two inputs with the same digest is computationally infeasible for cryptographic versions",
        "how": "non-cryptographic hashes (FNV, MurmurHash, xxHash) optimize for speed and uniform distribution to spread keys evenly across hash table buckets. Cryptographic hashes (SHA-256, SHA-3, BLAKE3) add resistance to collision and preimage attacks through extensive mixing of internal state. The Merkle-Damgard or sponge construction processes input in blocks, mixing bits across rounds so that each output bit depends on every input bit",
        "why": "hash functions underlie hash tables (the most-used data structure in software), content-addressable storage, digital signatures, password storage (with salts and slow KDFs), blockchains, deduplication, and fingerprinting. Collision resistance is what makes a digest a usable identity for content; it is the reason Git, Docker, and BitTorrent work",
        "vs": "non-cryptographic hashes differ from cryptographic ones in optimizing for speed at the cost of attack resistance; using a fast hash to verify integrity against an adversary is unsafe. Hashing differs from encryption in being one-way (no decryption) and from MACs in not depending on a secret key by default",
        "ex": "Git stores every blob, tree, and commit by its SHA-1 (transitioning to SHA-256) digest; identical content gives identical digests, enabling deduplication, while any change cascades through parent hashes, making history tamper-evident. The same construction shows up in Merkle trees throughout cryptography",
        "mis": "people think a hash function should be reversible. Cryptographic hashes are designed to be one-way; reversing them would break their security guarantees. Another myth is that any hash works for passwords; password hashes need slow, memory-hard KDFs (Argon2, bcrypt, scrypt) to resist offline attacks, not fast generic hashes",
    }

    T["how garbage collection algorithms differ"] = {
        "_cat": "technology",
        "what": "the family of automatic memory management algorithms that reclaim memory no longer reachable from program roots, with major variants including reference counting, mark-and-sweep, copying, generational, and concurrent collectors",
        "how": "reference counting tracks references at each assignment and frees objects when counts hit zero, simple but unable to reclaim cycles. Mark-and-sweep traverses references from roots, marking reachable objects, and reclaims unmarked ones. Copying collectors split heap halves and move live objects to a fresh region, compacting as they go. Generational collectors exploit the observation that most objects die young by collecting a young generation frequently and an old generation rarely. Concurrent collectors interleave work with the mutator to reduce pause times",
        "why": "GC choice shapes the latency, throughput, and footprint of every managed-language application. JVMs ship multiple collectors (G1, ZGC, Shenandoah) tunable for different latency targets. Go's concurrent tricolor collector aims for sub-millisecond pauses; Python's ref counting plus cycle collector trades off differently. Choosing or tuning is a frequent performance lever",
        "vs": "GC differs from manual memory management (C, C++) in safety vs predictable cost, from arenas/region-based allocation in returning individual objects rather than bulk-freeing, and from Rust's ownership model in deferring lifetime decisions to runtime rather than the compiler",
        "ex": "ZGC in modern JVMs uses load barriers and colored pointers to relocate objects concurrently, achieving multi-terabyte heaps with sub-millisecond pauses. Earlier collectors like CMS would pause for tens of milliseconds; G1 splits the heap into regions for predictable, configurable pause goals",
        "mis": "people think GC always pauses programs. Modern concurrent collectors do most work alongside execution; pause times are now often dominated by stack scanning and barriers, not heap traversal. Another myth is that GC eliminates memory leaks; you can still leak by holding references unintentionally (caches, listeners), keeping objects reachable",
    }
