#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank: history topics (fresh for batch H)."""


def register(T):
    T["the Tokugawa shogunate"] = {
        "_cat": "history",
        "what": "the military government that ruled Japan from 1603 to 1868 under successive Tokugawa shoguns, instituting a rigid social hierarchy and the sakoku policy of restricted foreign contact, presiding over more than two centuries of internal peace",
        "how": "after victory at Sekigahara in 1600, Tokugawa Ieyasu was named shogun in 1603 and built a centralized feudal order. Daimyo (regional lords) were required to alternate residence in Edo (sankin-kotai), draining their resources. Christianity was suppressed and most foreign trade was confined to the Dutch outpost at Dejima in Nagasaki. Confucian-influenced laws codified samurai, peasant, artisan, and merchant ranks. Cities, commerce, and a sophisticated culture of woodblock prints, kabuki, and haiku flourished alongside the formal restrictions",
        "why": "the Tokugawa era shaped modern Japan: long peace allowed urbanization and a literate commercial class, while sakoku created the cultural distinctiveness that the Meiji period would later launch into the world. Its end at the hands of Western pressure (Perry's black ships) catalyzed Japan's rapid modernization",
        "vs": "the Tokugawa shogunate differs from the earlier Kamakura and Ashikaga shogunates by the depth of central control and the length of internal peace. It differs from contemporaneous Qing China by its samurai-centered hierarchy and from European feudalism in lacking serfdom on the European model",
        "ex": "the sankin-kotai system required daimyo to spend alternating years in Edo, leaving family members as hostages when they returned to their domains. The system tied lords to the capital, drained their treasuries on travel and dual residences, and made overt rebellion almost impossible",
        "mis": "people think Tokugawa Japan was completely isolated. Trade and information flowed through Dejima, Korean embassies, and Ryukyu; Japanese scholars studied Western science via 'rangaku' (Dutch learning). Another myth is that the era was static; commerce, urban culture, and a money economy transformed daily life",
    }

    T["the Achaemenid Persian Empire"] = {
        "_cat": "history",
        "what": "the empire founded by Cyrus the Great around 550 BCE that grew to span from the Indus Valley to the Aegean, the largest empire of its time, governed through satrapies, royal roads, and a famously tolerant policy toward subject peoples",
        "how": "Cyrus conquered the Medes, Lydia, and Babylon, releasing the Jews from exile and respecting local religions. Cambyses added Egypt; Darius I systematized the empire into satrapies (provinces) under royal inspectors, built the Royal Road from Susa to Sardis, standardized coinage (the daric), and developed a postal system. Aramaic served as the lingua franca of administration. The empire collapsed under Alexander the Great between 334 and 330 BCE",
        "why": "the Achaemenids set durable templates for imperial administration (provincial governance, transport networks, multilingual rule) that influenced successors from the Seleucids to the Romans to the Islamic caliphates. Their religious tolerance and infrastructure sustained an unprecedented multicultural empire and shaped the world the Greeks fought against",
        "vs": "the Achaemenids differed from contemporary Greek city-states in scale, multiethnic composition, and centralized monarchy. They differed from later Persian dynasties (Parthian, Sasanian) in administrative style and Zoroastrian role. They differed from Assyrian predecessors by combining military power with conciliatory governance",
        "ex": "the Cyrus Cylinder, a baked-clay artifact from Babylon, records Cyrus's claim to have respected local gods and freed deportees. Modern scholars debate how literally to read its rhetoric, but it remains the most cited symbol of Achaemenid policy and an early model of imperial tolerance",
        "mis": "people think the Persian Wars were a clash of equals. Persia was vastly larger and richer than the Greek states; the Greek victory at Salamis was significant locally but barely dented the empire's overall power. Another myth is that the Achaemenids were monolithic Zoroastrians; religious practice across the empire varied widely",
    }

    T["the Songhai Empire of West Africa"] = {
        "_cat": "history",
        "what": "the largest precolonial state in West Africa, dominant from roughly 1464 to 1591, centered on the Niger River bend with capitals at Gao and Timbuktu, controlling the trans-Saharan gold and salt trade and producing a flowering of Islamic scholarship",
        "how": "Sunni Ali expanded Songhai through cavalry-driven conquests, capturing Timbuktu in 1468. His successor Askia Muhammad Toure professionalized administration, divided the realm into provinces under appointed governors, standardized weights and taxation, and made the hajj with a famous gold-laden caravan. Trans-Saharan caravans linked Songhai gold to North African and Mediterranean markets through Tuareg and Berber middlemen. The empire fell in 1591 when a Moroccan force armed with firearms defeated the Songhai cavalry at the Battle of Tondibi",
        "why": "Songhai connected sub-Saharan gold to global trade, sustained the libraries and madrasas of Timbuktu and Djenne, and shaped Islamic intellectual life across the Sahel. Manuscripts surviving in Timbuktu still preserve scholarly production from the era. Songhai's collapse contributed to political fragmentation that left the region vulnerable to later European incursions",
        "vs": "Songhai differed from its predecessors Ghana and Mali by its scale, river-centered logistics, and tighter administration. It differed from contemporary North African dynasties by being sub-Saharan and trans-Saharan in orientation, and from coastal West African states by being riverine and oriented inland to the desert trade",
        "ex": "the libraries of Timbuktu, particularly the Sankore complex, housed tens of thousands of manuscripts on theology, law, astronomy, and medicine. Many survived in private family collections and were partially digitized in the 21st century, recovering an intellectual heritage long invisible to Western historiography",
        "mis": "people think precolonial West Africa was illiterate or stateless. Songhai's bureaucracy, jurisprudence, and manuscript culture refute this. Another myth is that gold flowed only outward; Songhai imported salt, horses, books, and luxury goods through the trans-Saharan exchange",
    }

    T["the Bantu expansion"] = {
        "_cat": "history",
        "what": "the gradual migration of Bantu-speaking peoples from a homeland in present-day Cameroon and Nigeria across most of sub-Saharan Africa over roughly three thousand years, spreading agriculture, ironworking, and a related family of languages now spoken by hundreds of millions",
        "how": "starting around 3000 BCE, communities expanded southward and eastward in waves, carrying yam and later millet/sorghum cultivation, livestock, and ironworking technologies into rainforest and savanna environments previously occupied mostly by hunter-gatherers. Migration was likely driven by population growth and the productivity advantage of agriculture. By the early centuries CE, Bantu speakers had reached the Great Lakes; by the first millennium they reached southern Africa, encountering or absorbing earlier Khoisan-speaking populations",
        "why": "the expansion is one of the most consequential demographic events in African history, distributing related languages across a continent, transforming ecologies through agriculture and metallurgy, and laying foundations for later kingdoms and modern nation-states. Linguistics and archaeogenetics keep refining the timeline and routes",
        "vs": "the Bantu expansion differs from later movements like the Atlantic slave trade in being voluntary and gradual, and from Indo-European expansions across Eurasia by the lack of horse-based mobility. It differs from the Austronesian expansion by being continental rather than maritime, although both cover comparable distances and produce shared linguistic structure",
        "ex": "modern Swahili, Zulu, Shona, Lingala, and Kikongo are all Bantu languages despite separating populations spread across thousands of kilometers. Cognate vocabulary, regular sound correspondences, and shared grammatical structure attest to the common origin tens of centuries ago",
        "mis": "people think the Bantu expansion was a coordinated invasion. It was a slow demographic process spread across millennia, with frequent contact, intermarriage, and language adoption. Another myth is that it displaced indigenous populations everywhere; in many regions, hunter-gatherer communities persisted alongside or absorbed Bantu newcomers",
    }

    T["the Treaty of Versailles and its aftermath"] = {
        "_cat": "history",
        "what": "the 1919 peace treaty ending World War I that imposed territorial losses, military restrictions, and reparations on Germany while creating the League of Nations, shaping interwar Europe and contributing to the conditions for World War II",
        "how": "the Big Four (Wilson of the US, Lloyd George of the UK, Clemenceau of France, Orlando of Italy) negotiated terms at Paris while excluding Germany. Germany lost colonies, Alsace-Lorraine to France, and territories to Poland; the army was capped at 100000 men, with no air force or submarines; the Rhineland was demilitarized; and Article 231 (the war guilt clause) assigned Germany responsibility, justifying reparations later set at 132 billion gold marks. The League of Nations was established but the US Senate refused to ratify, undermining the order from the start",
        "why": "the treaty is widely credited with sowing resentment that Hitler exploited, while also creating the modern Polish and Czechoslovak states and the League framework that informed the later UN. Historians debate whether it was too harsh, too lenient, or simply unenforced; the failure of enforcement after 1935 was decisive",
        "vs": "Versailles differed from later peace settlements (Trianon, Saint-Germain, Sevres) handling other Central Powers, and from the post-WWII settlements that combined occupation with massive reconstruction (Marshall Plan). It differed from earlier treaties (Vienna 1815) by attempting collective security through a permanent international body",
        "ex": "the Ruhr crisis of 1923 occurred when France and Belgium occupied Germany's industrial heartland after reparations defaults, triggering hyperinflation as Germany printed money to support striking workers. The episode helped radicalize politics and is often cited as a direct line from Versailles to the Weimar Republic's instability",
        "mis": "people think Versailles caused World War II directly. The treaty mattered, but the path to war ran through the Depression, weak collective security, and choices by leaders in the 1930s. Another myth is that Germany was uniquely punished; the broader settlements dismantled empires and created instability across Central and Eastern Europe",
    }

    T["the Iranian Revolution of 1979"] = {
        "_cat": "history",
        "what": "the popular movement that overthrew the Pahlavi monarchy of Mohammad Reza Shah and established the Islamic Republic of Iran under Ayatollah Ruhollah Khomeini, transforming the regional and global political landscape",
        "how": "rapid modernization, oil-fueled inequality, SAVAK repression, and clerical opposition combined into mass protests through 1978. Strikes paralyzed the oil industry; the Shah left in January 1979; Khomeini returned from exile in February. A referendum established an Islamic Republic, and a new constitution institutionalized clerical rule under a Supreme Leader. The seizure of the US embassy in November 1979 led to a 444-day hostage crisis that froze US-Iran relations",
        "why": "the revolution reshaped the Middle East: it removed a key US ally, energized Islamist movements globally, triggered the Iran-Iraq War (1980-1988) and lasting US sanctions, and inaugurated a unique theocratic constitutional system. Its consequences continue to shape regional alignments, nuclear politics, and the gulf-Israel-Iran triangle",
        "vs": "the Iranian Revolution differed from earlier 20th-century revolutions (Russian, Chinese, Cuban) by its religious rather than Marxist ideology and from the contemporaneous wave of Islamic activism in Sunni-majority countries by its Shia clerical leadership and successful capture of state power",
        "ex": "the establishment of velayat-e faqih (guardianship of the jurist) under the new constitution gave the Supreme Leader authority over the military, judiciary, and major policy, with elected officials operating within those bounds. This dual structure persists, with Khamenei succeeding Khomeini in 1989",
        "mis": "people think the revolution was purely Islamist from the start. It involved a broad coalition (leftists, liberals, nationalists, clerics) that the clerical wing outmaneuvered and suppressed in the months after victory. Another myth is that it was anti-Western from inception; many revolutionaries initially expected normal relations with the US",
    }

    T["the rise of the United States as a global power"] = {
        "_cat": "history",
        "what": "the transformation of the United States from a regional western-hemisphere power in 1898 to a globally dominant economic, military, and cultural power by 1945, accelerated by two world wars and a deliberate postwar order-building project",
        "how": "the Spanish-American War (1898) projected US power into the Caribbean and Pacific. WWI made the US the world's leading creditor; the interwar period saw retreat into nominal isolation but continued economic dominance. WWII industrial mobilization built unmatched capacity; the Bretton Woods system, Marshall Plan, NATO, GATT, and the UN under US leadership embedded American power in institutions. Nuclear weapons, dollar reserve status, and technological leadership underpinned the new order",
        "why": "the postwar US order shaped trade, finance, security, and culture for the rest of the twentieth century and beyond. Its relative decline since the 1970s and the rise of China have made debates about its durability central to current geopolitics. The decisions made between 1944 and 1949 still constrain global politics decades later",
        "vs": "US ascendancy differed from prior British primacy in being more institutionalized, less colonial in form, and reliant on alliances rather than direct rule. It differed from its Soviet rival by combining military with economic and cultural reach. It differed from earlier hegemonies in its willingness to tie itself into multilateral institutions rather than rule unilaterally",
        "ex": "the Marshall Plan delivered about 13 billion dollars (over 150 billion in today's dollars) to Western Europe between 1948 and 1952, funding reconstruction, opening markets to US goods, and binding recipients politically to the West. It is often cited as the most successful foreign-aid program in history",
        "mis": "people think US dominance was foreordained. It depended on specific contingencies, including European self-destruction in two wars and Chinese internal conflict; without those, the US might have remained a great but not dominant power. Another myth is that US institutions guarantee continued primacy; institutional advantages erode without continued investment and credible commitments",
    }

    T["the Russian Revolution of 1917"] = {
        "_cat": "history",
        "what": "the year of two revolutions in Russia: the February Revolution that overthrew Tsar Nicholas II and established a Provisional Government, and the October Revolution that brought the Bolsheviks under Lenin to power, ending Romanov rule and inaugurating the Soviet era",
        "how": "WWI strained the empire's economy, military, and politics. Bread shortages and strikes in Petrograd in February (March, new style) led to abdication and a Provisional Government. The Petrograd Soviet of workers and soldiers shared power. Lenin returned from exile via Germany and pressed 'Peace, Land, Bread' and 'All Power to the Soviets'. After failed offensives and the Kornilov affair, the Bolsheviks seized key buildings in October, dissolved the Constituent Assembly in January 1918, and launched a civil war that lasted until 1922",
        "why": "the revolution created the world's first sustained socialist state, redrew the European order, inspired and constrained leftist movements globally for the rest of the century, and shaped Cold War geopolitics. Its disasters (Stalinism, famine, terror) loom equally large, but its initial promises and machinery influenced even non-Soviet welfare states and decolonization movements",
        "vs": "the Russian Revolution differed from the French in its industrial-era setting, the explicit role of a vanguard party, and the global ideological aftermath. It differed from later revolutions modeled on it (Chinese, Cuban, Vietnamese) by occurring without a strong peasant army doctrine, and from Soviet successor revolutions by its unique conjuncture of war, autocracy, and revolutionary parties",
        "ex": "Lenin's April Theses, delivered upon his return, demanded no support for the Provisional Government, transfer of power to soviets, and immediate peace. The bold program reoriented Bolshevik strategy and laid the conceptual groundwork for the October coup",
        "mis": "people think one revolution overthrew the Tsar. The February Revolution did that; the Bolsheviks took power eight months later from the Provisional Government, not from the Tsar. Another myth is that October was a mass uprising; it was a relatively small, well-organized seizure of key institutions, with mass involvement coming during the civil war",
    }

    T["the abolition movement in the 19th century Atlantic"] = {
        "_cat": "history",
        "what": "the transnational movement that ended legal slavery and the transatlantic slave trade across the British Empire, France, the Spanish empire, the United States, and Brazil between roughly 1807 and 1888, combining moral campaigning, slave resistance, economic shifts, and political reform",
        "how": "British abolitionists led by Wilberforce, Clarkson, and Equiano achieved the abolition of the slave trade in 1807 and slavery in the empire in 1833. The French Republic abolished slavery in 1794 (reinstated by Napoleon, abolished again in 1848). The US ended trade in 1808 and slavery in 1865 after the Civil War. Brazil abolished in 1888. Slave revolts (Haiti, Jamaica, Demerara, Nat Turner), free Black activists, evangelical religious networks, and gradual economic change all contributed",
        "why": "abolition reshaped the Atlantic world's economy, demography, and ethics, becoming a precedent for later human rights movements. Its incompleteness (sharecropping, Jim Crow, post-slavery indentured labor in the Caribbean and Asia) shaped racial inequalities still visible today, and its memory animates contemporary debates over reparations, monuments, and historical responsibility",
        "vs": "abolitionism differed from earlier antislavery sentiment by becoming a mass political movement with sustained organizations and parliamentary tactics. It differed across countries: gradual emancipation with compensated owners in Britain, sudden uncompensated emancipation through war in the US, top-down emancipation under pressure in Brazil. It differed from contemporary anti-serfdom movements in Russia and East Asia by its racial dimension",
        "ex": "the British Slave Compensation Commission paid about 20 million pounds (a substantial fraction of the budget) to slaveholders in 1834, while freed people received nothing. Records of the payments, made public in modern times, have anchored historical accountability projects tracing fortunes built on slavery into present-day institutions",
        "mis": "people think abolition was driven entirely by Northern moral progress in the US case or by lone heroes elsewhere. Slave revolts and resistance, especially in Saint-Domingue (Haiti), Jamaica, and the US, played major roles. Another myth is that abolition ended exploitation; sharecropping, convict leasing, and indentured systems substituted for slavery in many places",
    }

    T["the Vietnam War"] = {
        "_cat": "history",
        "what": "the long armed conflict in Southeast Asia from the 1950s through 1975 in which communist North Vietnam (with NLF/Viet Cong allies in the South) fought South Vietnam and its US patron, ending in North Vietnamese victory and Vietnamese reunification",
        "how": "after the 1954 Geneva Accords partitioned Vietnam following French defeat, the US backed South Vietnam against Ho Chi Minh's North. US involvement deepened from advisors to combat troops after the 1964 Gulf of Tonkin incident, peaking around 1968 with over half a million US personnel. The Tet Offensive in 1968 broke US public confidence; Nixon's Vietnamization shifted combat back to South Vietnamese forces; the Paris Peace Accords in 1973 led to US withdrawal, and Saigon fell to the North in 1975",
        "why": "the war reshaped American politics (the Vietnam syndrome), the Cold War (showing limits of US military power), Southeast Asia (the Khmer Rouge rise was related), and military doctrine (counterinsurgency, all-volunteer forces, congressional war powers). Its memory continues to shape US foreign policy debates over interventions",
        "vs": "Vietnam differed from earlier US wars in being undeclared and increasingly unpopular, from the Korean War in lacking decisive battlefield resolution, and from later conflicts (Iraq, Afghanistan) in conscription's role and the scale of mass mobilization in opposition. It differed from European colonial wars by occurring during decolonization with both superpowers indirectly involved",
        "ex": "Operation Rolling Thunder dropped more bombs on North Vietnam between 1965 and 1968 than the entire US bomb tonnage in WWII's European theater. Despite the volume, it failed to break the North's will, illustrating limits of strategic bombing against a determined adversary in a guerrilla-warfare context",
        "mis": "people think the US lost militarily in the field. The US won most large-unit engagements but lost politically, unable to translate tactical success into a sustainable South Vietnamese state. Another myth is that the war was primarily ideological; for Vietnamese, it was also a continuation of decades-long anti-colonial struggle",
    }

    T["the partition of the Ottoman Empire"] = {
        "_cat": "history",
        "what": "the dissolution of the Ottoman Empire after WWI through the Treaty of Sevres (1920), Treaty of Lausanne (1923), and intervening Turkish War of Independence, redrawing the borders of the modern Middle East and creating mandates and successor states whose boundaries largely persist",
        "how": "the empire entered WWI on Germany's side and was defeated. Britain and France had secretly agreed to divide its Arab provinces in the Sykes-Picot Agreement (1916). The Treaty of Sevres dismembered the empire, but Turkish nationalists under Mustafa Kemal Ataturk fought back, expelled Greek forces, and forced the Treaty of Lausanne, which recognized the Republic of Turkey within roughly current borders. Britain assumed mandates over Iraq, Palestine, and Transjordan; France over Syria and Lebanon. The Hejaz briefly became independent before Saudi conquest",
        "why": "the partition created the modern Middle East's borders, planted the seeds of the Israeli-Palestinian conflict (Balfour Declaration), Kurdish dispossession, and Arab grievances about broken wartime promises (Hussein-McMahon correspondence). Many subsequent conflicts trace directly to choices made between 1916 and 1923",
        "vs": "the Ottoman partition differed from contemporary German and Austro-Hungarian dismemberments by replacing a long-standing Islamic empire with mandate territories rather than nation-states from the start. It differed from later decolonization by being orchestrated externally without significant local political institutions to inherit power",
        "ex": "the modern borders of Iraq combine three Ottoman vilayets (Mosul, Baghdad, Basra) into a single mandate under British rule, joining diverse Sunni Arab, Shia Arab, and Kurdish populations. The combination has been a source of instability through the Hashemite kingdom, Baathist republic, US-led invasion, and post-2003 conflicts",
        "mis": "people think the borders were drawn arbitrarily on a map. They mostly followed Ottoman provincial boundaries adjusted by negotiation, sometimes reflecting ethnic geography, often not. Another myth is that Sykes-Picot is the dominant cause of regional dysfunction; the Treaty of Lausanne and subsequent decisions through 1948 mattered as much",
    }

    T["the Civil Rights Movement in the United States"] = {
        "_cat": "history",
        "what": "the mass movement primarily by African Americans from the 1950s through the 1960s that ended de jure racial segregation, secured voting rights, and reshaped American law and society through nonviolent direct action, legal strategy, and federal legislation",
        "how": "NAACP litigation produced Brown v. Board (1954) overturning school segregation. The Montgomery Bus Boycott (1955-1956) launched mass nonviolent action led by Martin Luther King Jr. and others. Sit-ins, Freedom Rides, the March on Washington (1963), and the Birmingham campaign forced federal action. Congress passed the Civil Rights Act (1964), Voting Rights Act (1965), and Fair Housing Act (1968). State-level organizing, especially in the South, faced violent resistance but built durable political change",
        "why": "the movement transformed US law, politics, and culture, ending Jim Crow segregation, expanding voting access, and inspiring later movements (women's, LGBTQ, disability rights, anti-apartheid). Its incomplete victories (de facto segregation, mass incarceration, voter suppression) frame current civil rights debates",
        "vs": "the movement differed from earlier civil rights activism (Ida B. Wells, NAACP's anti-lynching campaigns) in scale and federal response, from Black nationalist alternatives (Malcolm X, later Black Panthers) in nonviolent tactics, and from contemporaneous decolonization in operating within rather than against an existing nation-state",
        "ex": "the Selma to Montgomery marches in 1965, particularly 'Bloody Sunday' on the Edmund Pettus Bridge, generated national outrage that pressured Congress to pass the Voting Rights Act within months. The episode shows how strategic direct action could leverage media attention into legislation",
        "mis": "people think the movement is over and successful. Voting rights have eroded since the 2013 Shelby County decision; school resegregation has accelerated; wealth gaps persist. Another myth is that the movement was monolithic; it included sharp internal disagreements about tactics, goals, and the role of religion",
    }
