#!/usr/bin/env python3
"""Block 6: Debugging, unit/integration patterns, misc (items 116-160)."""
import json
from pathlib import Path

samples = []

def add(system, user, assistant, followup=None):
    msgs = [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
        {"role": "assistant", "content": assistant},
    ]
    if followup:
        msgs.append({"role": "user", "content": followup[0]})
        msgs.append({"role": "assistant", "content": followup[1]})
    samples.append({"messages": msgs, "tools": [], "domain": "code"})


add(
    "You are a Python debugging expert.",
    "Show me how to use pdb effectively.",
    "Insert `breakpoint()` (Python 3.7+) or `import pdb; pdb.set_trace()`.\n\n```python\ndef process(items):\n    total = 0\n    for i, item in enumerate(items):\n        if item.amount > 100:\n            breakpoint()   # drops into pdb here\n        total += item.amount\n    return total\n```\n\nKey commands:\n- `n` next line (step over)\n- `s` step into\n- `c` continue\n- `r` run until function returns\n- `l` list source around current line; `ll` longer list\n- `p expr` / `pp expr` print / pretty-print\n- `!expr` execute Python (prefix needed only when it collides with a command)\n- `w` where — show stack\n- `u` / `d` move up/down the stack\n- `b file:line` set breakpoint; `b` alone lists them; `cl n` clears\n- `q` quit\n- `interact` drop into a full REPL in the current frame\n\nUseful env var:\n\n```bash\nPYTHONBREAKPOINT=ipdb.set_trace python app.py\nPYTHONBREAKPOINT=0 python app.py   # disable all breakpoint() calls\n```\n\nThe second form lets you leave `breakpoint()` calls in and disable them via env at deploy time.",
)

add(
    "You are a debugging expert.",
    "Use pdb to debug a failing pytest test.",
    "Three options: `--pdb`, `pytest.set_trace()`, or `breakpoint()`.\n\n```bash\npytest --pdb                    # drop into pdb on first failure\npytest --pdb -x                 # stop at first failure AND drop into pdb\npytest --pdb --pdbcls=IPython.terminal.debugger:TerminalPdb   # use ipdb\n```\n\nOr manually in the test:\n\n```python\ndef test_process():\n    items = [...]\n    breakpoint()                  # stops here when run\n    result = process(items)\n    assert result == 42\n```\n\npytest captures stdout by default, which swallows pdb's prompt. Use `-s` to disable capture:\n\n```bash\npytest -s --pdb\n```\n\nUseful from inside pdb during a failing test:\n- `!pytest_item.name` and other pytest internals\n- `frame.f_locals` via `p locals()`\n- `!import pprint; pprint.pprint(result)` to inspect\n\nFor post-mortem on the last failure without rerunning:\n\n```python\nimport pdb; pdb.pm()   # after a REPL import\n```\n\nOr from the shell, `python -m pdb -c continue myscript.py` runs and drops into pdb on unhandled exception.",
)

add(
    "You are a debugging expert.",
    "How do I profile a Python program to find bottlenecks?",
    "`cProfile` for function-level; `py-spy` for production; `line_profiler` for hot functions.\n\n```bash\n# cProfile: built-in, no instrumentation\npython -m cProfile -o out.prof myscript.py\npython -m pstats out.prof\n# inside pstats: sort cumulative, stats 20\n\n# snakeviz: interactive flame-chart viewer\npip install snakeviz\nsnakeviz out.prof\n```\n\n```python\nimport cProfile, pstats\n\nprofiler = cProfile.Profile()\nprofiler.enable()\nrun_slow_thing()\nprofiler.disable()\npstats.Stats(profiler).sort_stats(\"cumulative\").print_stats(20)\n```\n\nFor a live process without modifying code:\n\n```bash\npip install py-spy\npy-spy record -o flame.svg --pid 12345 --duration 30\npy-spy top --pid 12345\n```\n\nLine-level:\n\n```bash\npip install line_profiler\nkernprof -l -v myscript.py   # decorate target funcs with @profile\n```\n\nRule of thumb: start with cProfile + snakeviz. Drop to line_profiler only after you have identified the single hot function. `py-spy` is the answer for production because it attaches without code changes.",
)

add(
    "You are a debugging expert.",
    "Find a memory leak with tracemalloc.",
    "`tracemalloc` tracks allocations and can diff snapshots.\n\n```python\nimport tracemalloc\n\ntracemalloc.start(25)   # keep 25 frames of traceback per allocation\n\nsnap1 = tracemalloc.take_snapshot()\nrun_suspect_code()\nsnap2 = tracemalloc.take_snapshot()\n\nstats = snap2.compare_to(snap1, \"lineno\")\nfor s in stats[:10]:\n    print(s)\n    for line in s.traceback.format():\n        print(\"   \", line)\n```\n\nOutput example:\n\n```\n/myapp/cache.py:42: size=10.2 MiB (+10.2 MiB), count=100000 (+100000)\n  File \"/myapp/cache.py\", line 42\n    self._store.append(item)\n```\n\nFilter what to track:\n\n```python\nsnap = tracemalloc.take_snapshot()\nsnap = snap.filter_traces((\n    tracemalloc.Filter(False, \"<frozen importlib._bootstrap>\"),\n    tracemalloc.Filter(True, \"<my pkg path>/*\"),\n))\n```\n\nTop allocators without diff:\n\n```python\ntop = snap.statistics(\"lineno\")\nfor entry in top[:10]:\n    print(entry)\n```\n\nFor suspected cycles, combine with `objgraph` or `gc.get_referrers`. `tracemalloc` is the right first tool because it is stdlib and shows allocation site, not just object identity.",
)

add(
    "You are a debugging expert.",
    "Use the gc module to debug reference cycles.",
    "Enable `DEBUG_SAVEALL` and inspect what the collector found.\n\n```python\nimport gc\n\ngc.set_debug(gc.DEBUG_SAVEALL | gc.DEBUG_UNCOLLECTABLE)\n\nclass Node:\n    def __init__(self):\n        self.peer = None\n\ndef make_cycle():\n    a = Node(); b = Node()\n    a.peer = b\n    b.peer = a\n    return a, b\n\nmake_cycle()\ngc.collect()\nfor obj in gc.garbage:\n    print(type(obj), id(obj))\n```\n\n`gc.garbage` holds uncollectable objects (those with `__del__` participating in a cycle). `DEBUG_SAVEALL` keeps every collected object around for inspection, useful but leaks memory — only use in diagnosis mode.\n\nFor inspecting what is keeping an object alive:\n\n```python\nimport gc\nimport sys\n\ndef referrers_of(obj):\n    refs = gc.get_referrers(obj)\n    for r in refs:\n        if r is sys._getframe() or r is refs:\n            continue\n        print(type(r), id(r))\n\n# only use for debugging; very slow\n```\n\nPrefer weakref or explicit teardown to breaking cycles rather than relying on gc. In most Python 3 code, cycles get collected automatically — you only reach for gc tools when `__del__` or large cycles cause measurable issues.",
)

add(
    "You are a debugging expert.",
    "How do I debug a process that is hung with py-spy?",
    "Attach to the PID and dump the stack without stopping the process.\n\n```bash\npip install py-spy\n\npy-spy dump --pid 12345\n# one-shot stack of every thread\n\npy-spy top --pid 12345\n# live top-like view of what is executing\n\npy-spy record -o profile.svg --pid 12345 --duration 30\n# flame graph of where time is actually spent\n```\n\nSample `py-spy dump` output:\n\n```\nThread 0x7fabc (MainThread)\n    0: get (lib.py:42)\n    1: fetch (service.py:17)\n    2: main (app.py:8)\nThread 0x7fxyz (pool-0)\n    0: recv (socket.py:586)   <- stuck in a blocking recv\n```\n\nReveals:\n- **Hang in socket.recv** — network or process on other end is stuck\n- **Hang in Lock.acquire** — deadlock; look at what other thread holds the lock\n- **Hang in sleep** — intentional backoff, probably not the problem\n\nFor stuck tests, `pytest --timeout=30` (pytest-timeout) auto-dumps faulthandler traceback on timeout. `faulthandler.register(signal.SIGUSR1)` lets you `kill -SIGUSR1 PID` to force a traceback print.",
)

add(
    "You are a unit testing expert.",
    "Explain the difference between unit and integration tests.",
    "Scope, speed, and what a failure means.\n\n```python\n# unit: isolated, fast, targets one function/class\ndef test_format_price_unit():\n    from myapp.fmt import format_price\n    assert format_price(1999) == \"$19.99\"\n    assert format_price(0) == \"$0.00\"\n\n# integration: multiple components wired together, often touches IO\ndef test_checkout_integration(client, db):\n    resp = client.post(\"/checkout\", json={\"cart\": [\"sku-1\"]})\n    assert resp.status_code == 200\n    order = db.query(Order).one()\n    assert order.total_cents == 1999\n```\n\n| Dimension | Unit | Integration |\n|---|---|---|\n| Runtime | ms | 100ms-seconds |\n| Scope | one function | API boundary |\n| Setup | in-memory / mocks | real DB / Redis / filesystem |\n| When to run | every save | every PR |\n| On failure | clearly which unit broke | may be unclear which component |\n\nPyramid heuristic: 70% unit, 20% integration, 10% end-to-end. Unit tests are fast enough to run on every keystroke; integration tests verify that the mocked seams match reality; e2e tests check the whole stack.\n\nBoth are valuable. Unit tests alone miss wiring bugs; integration tests alone are slow and pinpoint problems poorly. You need both, layered.",
)

add(
    "You are a testing expert.",
    "Write a unit test for a function that takes many collaborators.",
    "Inject collaborators and pass fakes in tests.\n\n```python\n# myapp/orders.py\nfrom dataclasses import dataclass\n\n@dataclass\nclass OrderService:\n    db: object        # has save()\n    mailer: object    # has send()\n    clock: object     # callable returning datetime\n\n    def place(self, user_id, items):\n        total = sum(i.price for i in items)\n        order = {\"user_id\": user_id, \"total\": total, \"at\": self.clock()}\n        self.db.save(order)\n        self.mailer.send(to=user_id, subject=\"confirm\", body=str(order))\n        return order\n```\n\n```python\n# tests/test_orders.py\nfrom datetime import datetime\nfrom unittest.mock import MagicMock\nfrom myapp.orders import OrderService\n\ndef test_place_order_saves_and_emails():\n    db = MagicMock()\n    mailer = MagicMock()\n    clock = MagicMock(return_value=datetime(2026, 1, 1))\n    svc = OrderService(db=db, mailer=mailer, clock=clock)\n\n    class Item: price = 100\n    order = svc.place(user_id=42, items=[Item(), Item()])\n\n    assert order[\"total\"] == 200\n    db.save.assert_called_once_with(order)\n    mailer.send.assert_called_once()\n    clock.assert_called_once()\n```\n\nDependency injection is what makes this testable. The production code accepts protocols/ducks; the test passes mocks. No `patch` needed, no module-level globals, no fragility.",
)

add(
    "You are a testing expert.",
    "Show me a test using factory_boy for generating test data.",
    "Declarative factory per model, supports sequences and sub-factories.\n\n```python\nimport factory\nfrom dataclasses import dataclass\n\n@dataclass\nclass User:\n    id: int\n    email: str\n    name: str\n\n@dataclass\nclass Post:\n    id: int\n    author: User\n    title: str\n    body: str\n\nclass UserFactory(factory.Factory):\n    class Meta:\n        model = User\n\n    id = factory.Sequence(lambda n: n + 1)\n    email = factory.LazyAttribute(lambda o: f\"user{o.id}@x.com\")\n    name = factory.Faker(\"name\")\n\nclass PostFactory(factory.Factory):\n    class Meta:\n        model = Post\n\n    id = factory.Sequence(lambda n: n + 1)\n    author = factory.SubFactory(UserFactory)\n    title = factory.Faker(\"sentence\", nb_words=4)\n    body = factory.Faker(\"paragraph\")\n\ndef test_default_post():\n    p = PostFactory()\n    assert p.author.email.endswith(\"@x.com\")\n    assert p.title and p.body\n\ndef test_post_with_known_author():\n    user = UserFactory(name=\"Alice\")\n    post = PostFactory(author=user, title=\"Hello\")\n    assert post.author.name == \"Alice\"\n    assert post.title == \"Hello\"\n```\n\nFor Django/SQLAlchemy models, use `DjangoModelFactory` / `SQLAlchemyModelFactory` which also save() the object. Sequences produce unique PK-safe values. Overrides at call site win over factory defaults.",
)

add(
    "You are a testing expert.",
    "How do I test async code with pytest-asyncio?",
    "Install `pytest-asyncio` and decorate tests with `@pytest.mark.asyncio`.\n\n```python\n# conftest.py or pyproject.toml\n# [tool.pytest.ini_options]\n# asyncio_mode = \"auto\"   # every async def is a test; no decorator needed\n\nimport asyncio\nimport pytest\n\nasync def fetch(url):\n    await asyncio.sleep(0.01)\n    return f\"got {url}\"\n\n@pytest.mark.asyncio\nasync def test_fetch():\n    result = await fetch(\"http://x\")\n    assert result == \"got http://x\"\n\n@pytest.fixture\nasync def client():\n    c = {\"conns\": 0}\n    c[\"conns\"] += 1\n    yield c\n    c[\"conns\"] -= 1\n\n@pytest.mark.asyncio\nasync def test_with_fixture(client):\n    assert client[\"conns\"] == 1\n```\n\nModes:\n- `asyncio_mode = \"auto\"` — any async test runs; no marker needed\n- `asyncio_mode = \"strict\"` (default) — must mark each test\n\nEvent loop policy: per-test by default. For session-scoped async fixtures, use `@pytest_asyncio.fixture(scope=\"session\")` and set `event_loop_policy` accordingly. For HTTP, `httpx.AsyncClient` + `respx` is the go-to combo.",
)

add(
    "You are a testing expert.",
    "Show testing of a websocket handler.",
    "Spin the server in-process and use a client to exchange messages.\n\n```python\nimport asyncio\nimport pytest\nimport websockets\n\nasync def echo_handler(ws):\n    async for msg in ws:\n        await ws.send(f\"echo:{msg}\")\n\n@pytest.fixture\nasync def server():\n    server = await websockets.serve(echo_handler, \"127.0.0.1\", 0)\n    port = server.sockets[0].getsockname()[1]\n    yield f\"ws://127.0.0.1:{port}\"\n    server.close()\n    await server.wait_closed()\n\n@pytest.mark.asyncio\nasync def test_echo(server):\n    async with websockets.connect(server) as ws:\n        await ws.send(\"hello\")\n        reply = await ws.recv()\n        assert reply == \"echo:hello\"\n\n@pytest.mark.asyncio\nasync def test_multi_messages(server):\n    async with websockets.connect(server) as ws:\n        for i in range(5):\n            await ws.send(f\"msg{i}\")\n            assert await ws.recv() == f\"echo:msg{i}\"\n```\n\nPort 0 asks the OS for an unused port, crucial under `pytest-xdist` so workers do not collide. `wait_closed()` ensures no resource warnings leak between tests. For FastAPI's websockets, `TestClient` has a `websocket_connect` context manager that is even simpler.",
)

add(
    "You are a testing expert.",
    "How do I write tests that exercise a real Docker container with testcontainers?",
    "`testcontainers` spins containers and tears them down; clean API.\n\n```python\n# pip install testcontainers[postgres,redis]\nimport pytest\nimport psycopg\nfrom testcontainers.postgres import PostgresContainer\nfrom testcontainers.redis import RedisContainer\n\n@pytest.fixture(scope=\"session\")\ndef postgres():\n    with PostgresContainer(\"postgres:16-alpine\") as pg:\n        yield pg.get_connection_url()\n\n@pytest.fixture(scope=\"session\")\ndef redis():\n    with RedisContainer(\"redis:7-alpine\") as r:\n        yield r.get_connection_url()\n\ndef test_postgres_insert(postgres):\n    with psycopg.connect(postgres) as conn:\n        conn.execute(\"CREATE TABLE IF NOT EXISTS t (id serial, v text)\")\n        conn.execute(\"INSERT INTO t (v) VALUES ('hello')\")\n        conn.commit()\n        row = conn.execute(\"SELECT v FROM t\").fetchone()\n        assert row[0] == \"hello\"\n\ndef test_redis(redis):\n    import redis as r\n    client = r.Redis.from_url(redis)\n    client.set(\"k\", \"v\")\n    assert client.get(\"k\") == b\"v\"\n```\n\nContainers spin up once per session, get random host ports (xdist-safe), and are removed on teardown. Use `testcontainers` for integration tests against the *real* versions of your dependencies instead of mocks that drift from reality.",
)

add(
    "You are a testing expert.",
    "Write snapshot tests with syrupy.",
    "`syrupy` stores serialized expected values and compares on rerun.\n\n```python\n# pip install syrupy\ndef render_report(data):\n    return {\"total\": sum(d[\"amount\"] for d in data),\n            \"count\": len(data),\n            \"items\": sorted(data, key=lambda d: d[\"amount\"])}\n\ndef test_report(snapshot):\n    result = render_report([\n        {\"id\": \"a\", \"amount\": 10},\n        {\"id\": \"b\", \"amount\": 5},\n        {\"id\": \"c\", \"amount\": 20},\n    ])\n    assert result == snapshot\n```\n\nFirst run: `syrupy` saves the value to `__snapshots__/test_report.ambr`. Subsequent runs: actual is compared against the stored snapshot.\n\nWhen the expected output legitimately changes, update snapshots:\n\n```bash\npytest --snapshot-update   # regenerate snapshots for current run\n```\n\nReview the diff in git before committing. Snapshot tests are great for:\n- Structured output that would be tedious to spell out (large JSON)\n- Rendered templates (HTML, emails)\n- CLI help text\n\nAntipattern: large/binary outputs. The diff is unreadable and the update becomes blind. For those, write targeted assertions instead.",
)

add(
    "You are a testing expert.",
    "Show me pytest-benchmark usage.",
    "Call the code under test via the `benchmark` fixture.\n\n```python\n# pip install pytest-benchmark\ndef slow_sum(n):\n    total = 0\n    for i in range(n):\n        total += i\n    return total\n\ndef test_slow_sum_bench(benchmark):\n    result = benchmark(slow_sum, 10_000)\n    assert result == sum(range(10_000))\n\ndef test_parametrized_bench(benchmark):\n    # pass kwargs\n    result = benchmark.pedantic(slow_sum,\n                                 args=(10_000,),\n                                 iterations=10,\n                                 rounds=5)\n    assert result == sum(range(10_000))\n```\n\nRun and save baseline:\n\n```bash\npytest --benchmark-save=baseline\n# ...make changes...\npytest --benchmark-compare=baseline\n```\n\nOutput shows mean, stddev, and ops/s, with a delta column vs the baseline. Fail the run on regression:\n\n```bash\npytest --benchmark-compare=baseline --benchmark-compare-fail=mean:10%\n```\n\nAny test whose mean is 10% slower than baseline fails. Perfect as a CI guard on performance-sensitive code. Alternatives: `pyperf` for standalone microbenchmarks, `asv` (airspeed velocity) for longitudinal performance tracking across commits.",
)

add(
    "You are a debugging expert.",
    "Use the icecream library for quick debug prints.",
    "`icecream` prints expression + value + location with one call.\n\n```python\n# pip install icecream\nfrom icecream import ic\n\ndef process(xs):\n    total = 0\n    for x in xs:\n        ic(x)            # ic| x: 1    (shows variable name and value)\n        total += x * 2\n    ic(total)\n    return total\n\nprocess([1, 2, 3])\n# ic| x: 1\n# ic| x: 2\n# ic| x: 3\n# ic| total: 12\n```\n\nUseful features:\n\n```python\nic.configureOutput(prefix=\"DEBUG | \", includeContext=True)\n# now each line prefixes with file:line\n\nic.enable()       # default\nic.disable()      # silent\n\n# make ic globally available without importing (intended only for dev)\nimport builtins\nbuiltins.ic = ic\n```\n\nCompared to `print(f\"x={x}\")`:\n- Auto-prints the expression text, so no duplication\n- Tagged with file:line for easy removal\n- Trivially disableable via env check\n\nDo not ship `ic` calls to production; it is a dev-time tool. Pair with a lint rule (`ruff select=T100`) to catch leftover calls in CI.",
)

add(
    "You are a debugging expert.",
    "How do I use the rich library to improve traceback readability?",
    "Install the traceback handler at startup.\n\n```python\n# pip install rich\nfrom rich.traceback import install\ninstall(show_locals=True, width=120, word_wrap=True)\n\ndef outer():\n    inner({\"key\": \"value\"})\n\ndef inner(data):\n    return data[\"missing\"]\n\nouter()\n```\n\nRich renders tracebacks with syntax highlighting, shows the values of local variables at each frame, and word-wraps long lines to terminal width. `show_locals=True` is invaluable for \"what was `data` when this exploded?\".\n\nAs a pytest plugin:\n\n```bash\npip install pytest-rich\npytest              # tracebacks rendered with rich automatically\n```\n\nOr integrate with logging:\n\n```python\nimport logging\nfrom rich.logging import RichHandler\n\nlogging.basicConfig(\n    level=logging.INFO,\n    handlers=[RichHandler(rich_tracebacks=True, tracebacks_show_locals=True)],\n    format=\"%(message)s\",\n)\n```\n\nIn production, disable rich tracebacks (they leak local values to logs, which may include secrets). Use JSON logging there and save rich output for local dev and tests.",
)

add(
    "You are a debugging expert.",
    "Show how to use faulthandler for crash debugging.",
    "`faulthandler` dumps tracebacks on segfault or deadlock.\n\n```python\nimport faulthandler\nimport signal\n\nfaulthandler.enable()  # prints traceback on SIGSEGV/SIGFPE/SIGABRT/SIGBUS\n\n# user-triggered dump: kill -SIGUSR1 <pid> to dump all threads\nfaulthandler.register(signal.SIGUSR1, all_threads=True)\n\n# timeout watchdog: if the process hangs for 60s, dump threads\nfaulthandler.dump_traceback_later(60, repeat=True)\n```\n\nNow a C-level crash does not silently exit — you get a Python traceback pinpointing the call. `SIGUSR1` is how you debug live hangs without py-spy: sending the signal makes the process dump its current stack for every thread.\n\nIn a script:\n\n```bash\npython -X faulthandler myapp.py\nPYTHONFAULTHANDLER=1 python myapp.py\n```\n\nBoth enable faulthandler at startup, catching early-boot crashes before user code runs.\n\nFor pytest, `pytest --timeout=30 --timeout-method=signal` (requires `pytest-timeout`) uses faulthandler to dump tracebacks of stuck tests and then kills them. Essential for CI where hung tests otherwise consume the full job timeout.",
)

add(
    "You are a debugging expert.",
    "Dump the call stack of every thread at an arbitrary point.",
    "`sys._current_frames()` + `traceback.format_stack` gives a per-thread view.\n\n```python\nimport sys\nimport threading\nimport traceback\n\ndef dump_all_threads():\n    frames = sys._current_frames()\n    lines = []\n    for tid, frame in frames.items():\n        name = next((t.name for t in threading.enumerate() if t.ident == tid),\n                    f\"tid={tid}\")\n        lines.append(f\"=== Thread {name} ({tid}) ===\")\n        lines.extend(traceback.format_stack(frame))\n    return \"\\n\".join(lines)\n\nimport signal\nsignal.signal(signal.SIGUSR2, lambda sig, frame: print(dump_all_threads()))\n```\n\nNow `kill -SIGUSR2 <pid>` prints one combined dump of every Python thread's stack.\n\nIntegrate with a long-running service:\n\n```python\nimport logging\nlog = logging.getLogger(__name__)\n\n@app.route(\"/_debug/threads\")\ndef thread_dump():\n    return dump_all_threads(), 200, {\"Content-Type\": \"text/plain\"}\n```\n\nA protected debug endpoint is handy for diagnosing hangs in staging. Comparable to Java's `jstack`. For GIL-aware analysis, `py-spy dump` remains the best external tool; `sys._current_frames` is the in-process equivalent with no dependency.",
)

add(
    "You are a testing expert.",
    "Explain test doubles: dummy, fake, stub, spy, mock.",
    "Five flavours distinguished by intent (per Meszaros / Fowler).\n\n```python\nfrom unittest.mock import MagicMock\n\n# Dummy: passed but never used. Satisfies a signature.\ndummy_logger = None\nservice = Service(logger=dummy_logger)  # Service never calls logger here\n\n# Fake: working implementation with a shortcut unfit for production\nclass InMemoryRepo:\n    def __init__(self): self._data = {}\n    def save(self, obj): self._data[obj.id] = obj\n    def get(self, id): return self._data[id]\n\n# Stub: returns canned responses. State verification.\nstub_clock = lambda: datetime(2026, 1, 1)\n\n# Spy: real behavior + records calls\nspy_email = MagicMock(wraps=real_email_service)\n\n# Mock: pre-programmed expectations. Behavior verification.\nmock_db = MagicMock()\nmock_db.save.return_value = None\n# test asserts mock_db.save was called with specific args\n```\n\nThe terms are fuzzy in practice; `unittest.mock.Mock` can play any of these roles. What matters: **state verification** (did the result end up correct?) vs **behavior verification** (were the right calls made?). Prefer state when you can — it is more resilient to refactors. Use behavior checks when the effect is the call itself (an email was sent, a webhook fired).",
)

add(
    "You are a packaging expert.",
    "Write a conftest.py that adds useful pytest options.",
    "`pytest_addoption` and hook wiring in one file.\n\n```python\n# conftest.py\nimport os\nimport pytest\n\n\ndef pytest_addoption(parser):\n    parser.addoption(\n        \"--integration\",\n        action=\"store_true\",\n        default=False,\n        help=\"run integration tests (needs docker)\",\n    )\n    parser.addoption(\n        \"--env\",\n        default=os.environ.get(\"TEST_ENV\", \"local\"),\n        help=\"target env: local / staging / ci\",\n    )\n    parser.addoption(\n        \"--seed\",\n        type=int,\n        default=None,\n        help=\"deterministic seed for rng\",\n    )\n\n\n@pytest.fixture\ndef env(request):\n    return request.config.getoption(\"--env\")\n\n\ndef pytest_configure(config):\n    config.addinivalue_line(\"markers\", \"integration: needs docker\")\n    config.addinivalue_line(\"markers\", \"slow: takes >5s\")\n\n\ndef pytest_collection_modifyitems(config, items):\n    if config.getoption(\"--integration\"):\n        return\n    skip = pytest.mark.skip(reason=\"pass --integration to run\")\n    for item in items:\n        if \"integration\" in item.keywords:\n            item.add_marker(skip)\n\n\n@pytest.fixture(autouse=True)\ndef seed_random(request):\n    seed = request.config.getoption(\"--seed\")\n    if seed is not None:\n        import random\n        random.seed(seed)\n```\n\nNow `pytest --integration --env=ci --seed=42` runs the integration suite deterministically.",
)

add(
    "You are a debugging expert.",
    "Debug an async function with asyncio debug mode.",
    "`PYTHONASYNCIODEBUG=1` or `asyncio.run(main(), debug=True)`.\n\n```python\nimport asyncio\n\nasync def slow():\n    await asyncio.sleep(0.2)\n\nasync def main():\n    await slow()\n    # forgot to await: leaks a coroutine\n    slow()\n\nasyncio.run(main(), debug=True)\n```\n\nDebug mode surfaces:\n- Coroutines that were never awaited (with source location of creation)\n- Callbacks that block the event loop for too long (> 100ms by default)\n- Tasks that were not awaited or cancelled\n- Warnings on exception-in-task that never got retrieved\n\nOutput looks like:\n\n```\nRuntimeWarning: coroutine 'slow' was never awaited\nExecuting <Task pending name='Task-1' coro=<main() running at app.py:7>> took 0.201 seconds\n```\n\nRun from CLI without code changes:\n\n```bash\nPYTHONASYNCIODEBUG=1 python app.py\nPYTHONDEVMODE=1 python app.py   # dev mode enables asyncio debug + resource warnings + more\n```\n\nDev mode (`-X dev` or `PYTHONDEVMODE=1`) should be your CI default for async projects. It is slower but catches a large class of latent bugs at test time.",
)

add(
    "You are a testing expert.",
    "Show a pattern for contract testing between services.",
    "Use schemathesis (OpenAPI) or a shared schema module.\n\n```python\n# pip install schemathesis\nimport schemathesis\n\nschema = schemathesis.from_uri(\"http://localhost:8000/openapi.json\")\n\n@schema.parametrize()\ndef test_api_contract(case):\n    response = case.call()\n    case.validate_response(response)\n```\n\nFor each operation in your OpenAPI spec, schemathesis generates many valid requests (via Hypothesis), sends them, and checks that each response conforms to the schema. Finds:\n- Response shapes that violate the documented schema\n- 500s on edge-case inputs\n- Security header regressions\n- Response-body nulls where non-null is required\n\nProvider-side contract test (using pact-python):\n\n```python\nfrom pact import Consumer, Provider\n\npact = Consumer(\"web\").has_pact_with(Provider(\"api\"))\npact.start_service()\n\nexpected = {\"user_id\": 42, \"name\": \"alice\"}\n(pact\n .given(\"user 42 exists\")\n .upon_receiving(\"a request for user 42\")\n .with_request(\"get\", \"/users/42\")\n .will_respond_with(200, body=expected))\n\nwith pact:\n    result = my_client.get_user(42)\n    assert result == expected\n```\n\nPact records the consumer's expectations; the provider replays them in its own test suite. Catches contract drift without real cross-service integration.",
)

add(
    "You are a debugging expert.",
    "How do I use sys.settrace to implement custom tracing?",
    "`sys.settrace` registers a callback invoked on each line.\n\n```python\nimport sys\n\ndef tracer(frame, event, arg):\n    if event == \"call\":\n        code = frame.f_code\n        if code.co_filename.endswith(\"myapp/core.py\"):\n            print(f\"-> {code.co_name}({frame.f_locals})\")\n            return tracer\n    elif event == \"return\":\n        print(f\"<- {frame.f_code.co_name} => {arg}\")\n    return tracer\n\nsys.settrace(tracer)\n\nfrom myapp.core import process\nprocess([1, 2, 3])\n\nsys.settrace(None)\n```\n\nEvents:\n- `call` — function entry\n- `line` — next source line about to execute\n- `return` — function returning (`arg` is return value)\n- `exception` — exception raised (`arg` is `(type, value, tb)`)\n- `opcode` — per bytecode (enable with `frame.f_trace_opcodes = True`)\n\nReturn the same function to continue tracing into the next frame; return `None` to stop tracing that frame.\n\nUse cases: implementing coverage, profilers, debuggers. For anything performance-sensitive use `sys.setprofile` (called once per call/return, not per line). Beware: the pure Python tracer is slow (~100x overhead). coverage.py uses a C extension tracer for production-grade measurement.",
)

add(
    "You are a testing expert.",
    "Write a property-based round-trip test for a config parser.",
    "Combine Hypothesis with a custom strategy that builds valid configs.\n\n```python\nfrom hypothesis import given, strategies as st\nimport configparser\nimport io\n\nsafe_key = st.text(\n    alphabet=\"abcdefghijklmnopqrstuvwxyz_0123456789\",\n    min_size=1, max_size=20,\n)\nsafe_val = st.text(\n    alphabet=\"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ \",\n    max_size=50,\n).map(str.strip).filter(bool)\n\nconfig_st = st.dictionaries(\n    keys=safe_key,\n    values=st.dictionaries(keys=safe_key, values=safe_val, max_size=5),\n    min_size=1, max_size=3,\n)\n\n@given(config_st)\ndef test_config_roundtrip(data):\n    cp = configparser.ConfigParser()\n    cp.read_dict(data)\n    buf = io.StringIO()\n    cp.write(buf)\n\n    cp2 = configparser.ConfigParser()\n    cp2.read_string(buf.getvalue())\n\n    parsed = {s: dict(cp2.items(s)) for s in cp2.sections()}\n    assert parsed == data\n```\n\nRestrict alphabets because configparser has escape rules for `=`, `:`, `;`, and leading spaces. The filter `.map(str.strip).filter(bool)` drops empties. A round-trip property \"write then read equals original\" catches a surprising amount of escape, encoding, and whitespace handling bugs that hand-picked tests miss.",
)

add(
    "You are a testing expert.",
    "Test a CLI built with argparse.",
    "Call `parser.parse_args(argv)` directly or invoke via `subprocess`.\n\n```python\nimport argparse\nimport pytest\n\ndef build_parser():\n    p = argparse.ArgumentParser(prog=\"tool\")\n    p.add_argument(\"--count\", type=int, default=1)\n    p.add_argument(\"--verbose\", action=\"store_true\")\n    p.add_argument(\"target\")\n    return p\n\ndef test_parses_required():\n    args = build_parser().parse_args([\"--count\", \"3\", \"foo\"])\n    assert args.count == 3\n    assert args.target == \"foo\"\n    assert args.verbose is False\n\ndef test_missing_target_errors(capsys):\n    with pytest.raises(SystemExit) as exc:\n        build_parser().parse_args([])\n    assert exc.value.code == 2\n    assert \"required\" in capsys.readouterr().err\n\ndef test_verbose_flag():\n    args = build_parser().parse_args([\"--verbose\", \"bar\"])\n    assert args.verbose is True\n```\n\nKeep parser construction in a pure function so tests do not need to mock `sys.argv`. If the CLI has a `main()` that drives IO, split: `main(argv=None)` uses `sys.argv[:1]` if None, so tests can pass an explicit list.\n\nFor click/typer, prefer the framework's runner (`CliRunner`) — it captures exit codes, stdout/stderr, and raised exceptions in one structured result.",
)

add(
    "You are a testing expert.",
    "How do I test that a function is pure (no side effects)?",
    "Wrap collaborators that would produce side effects with spies, and assert they are untouched.\n\n```python\nfrom unittest.mock import MagicMock\n\ndef slug(title):\n    # claimed to be pure\n    return title.lower().strip().replace(\" \", \"-\")\n\ndef test_pure_slug_no_side_effects(monkeypatch):\n    # spy on things that COULD be accidentally used\n    import builtins\n    fake_open = MagicMock()\n    fake_print = MagicMock()\n    monkeypatch.setattr(builtins, \"open\", fake_open)\n    monkeypatch.setattr(builtins, \"print\", fake_print)\n\n    import os, random\n    monkeypatch.setattr(os.environ, \"__getitem__\", MagicMock(side_effect=KeyError))\n    spy_random = MagicMock(wraps=random.random)\n    monkeypatch.setattr(random, \"random\", spy_random)\n\n    out = slug(\"Hello World \")\n    assert out == \"hello-world\"\n    fake_open.assert_not_called()\n    fake_print.assert_not_called()\n    spy_random.assert_not_called()\n```\n\nThis test verifies `slug` did not open files, print, read env, or consume randomness. Combine with property-based testing to also verify determinism:\n\n```python\nfrom hypothesis import given, strategies as st\n\n@given(st.text())\ndef test_slug_deterministic(s):\n    assert slug(s) == slug(s)\n```\n\nCalling twice gives the same answer — the minimum bar for a pure function.",
)

add(
    "You are a debugging expert.",
    "Explain and use pytest --lf --ff --nf --sw options.",
    "Cache-backed flags for incremental re-runs.\n\n```bash\npytest --lf     # last-failed: run only tests that failed last run\npytest --ff     # failed-first: failing tests before the rest\npytest --nf     # new-first: newly discovered tests run first\npytest --sw     # stepwise: stop at first failure, next run resumes there\npytest --sw --stepwise-skip   # skip the last failure and continue\n```\n\nTypical workflow while fixing a regression:\n\n```bash\npytest                 # full run, identifies 3 failures\npytest --lf -x         # re-run only those 3, stop at first\n# ... fix code ...\npytest --lf            # re-run the 3; 1 still fails\npytest --sw            # work through failures one at a time\npytest                 # full run again to confirm nothing else broke\n```\n\nConfigure where the cache lives:\n\n```toml\n[tool.pytest.ini_options]\ncache_dir = \".pytest_cache\"\n```\n\nAdd `.pytest_cache/` to `.gitignore`. Cache files are just text; `pytest --cache-show` prints them, `pytest --cache-clear` resets. These flags are the biggest wall-clock savings in day-to-day pytest work and cost nothing to enable.",
)

add(
    "You are a testing expert.",
    "Create a fixture that captures logs and lets me assert on them.",
    "Use pytest's built-in `caplog`; it is often sufficient.\n\n```python\nimport logging\nimport pytest\n\ndef warn_if_large(n):\n    log = logging.getLogger(\"svc\")\n    if n > 100:\n        log.warning(\"n=%d is large\", n)\n    return n * 2\n\ndef test_warns_when_large(caplog):\n    with caplog.at_level(logging.DEBUG, logger=\"svc\"):\n        warn_if_large(200)\n    warnings = [r for r in caplog.records if r.levelno == logging.WARNING]\n    assert len(warnings) == 1\n    assert \"n=200 is large\" in warnings[0].getMessage()\n    assert warnings[0].name == \"svc\"\n\ndef test_quiet_when_small(caplog):\n    with caplog.at_level(logging.DEBUG):\n        warn_if_large(5)\n    assert not [r for r in caplog.records if r.levelno >= logging.WARNING]\n```\n\nFor structlog, a small adapter:\n\n```python\n@pytest.fixture\ndef structlog_capture():\n    from structlog.testing import LogCapture\n    cap = LogCapture()\n    import structlog\n    structlog.configure(processors=[cap])\n    return cap\n\ndef test_structlog(structlog_capture):\n    import structlog\n    structlog.get_logger().info(\"user\", user_id=42)\n    assert structlog_capture.entries == [{\"event\": \"user\", \"user_id\": 42, \"log_level\": \"info\"}]\n```",
)

add(
    "You are a testing expert.",
    "Show me a fixture using yield for setup/teardown with exception safety.",
    "yield-based fixtures run teardown even if the test raises.\n\n```python\nimport pytest\n\nclass TempResource:\n    def __init__(self):\n        self.open = False\n        self.cleanup_count = 0\n    def start(self):\n        assert not self.open\n        self.open = True\n    def stop(self):\n        self.open = False\n        self.cleanup_count += 1\n\n@pytest.fixture\ndef resource():\n    r = TempResource()\n    r.start()\n    try:\n        yield r\n    finally:\n        r.stop()\n    # or simpler, since pytest wraps the yield in try/finally itself:\n    # yield r\n    # r.stop()\n\ndef test_happy_path(resource):\n    assert resource.open is True\n\ndef test_raises_but_cleans_up(resource):\n    try:\n        assert resource.open is True\n        raise RuntimeError(\"boom\")\n    except RuntimeError:\n        pass\n    # r.stop() still runs on teardown after test exits\n```\n\nYou can verify teardown happens by checking a module-level counter in a follow-up test or via `request.addfinalizer(...)`. pytest internally wraps the yield so teardown executes regardless of test outcome, which is why `yield` is the preferred fixture style over the older `finalizer` pattern.",
)

add(
    "You are a debugging expert.",
    "Make pytest drop into ipdb on failure.",
    "Pass `--pdbcls`.\n\n```bash\npip install ipdb\npytest --pdb --pdbcls=IPython.terminal.debugger:TerminalPdb -s\n```\n\n`-s` is important: without it pytest captures stdout and you cannot see the ipdb prompt.\n\nPin it in pyproject.toml so the whole team gets the nicer debugger:\n\n```toml\n[tool.pytest.ini_options]\naddopts = \"--pdbcls=IPython.terminal.debugger:TerminalPdb\"\n```\n\nFor pudb (visual debugger):\n\n```bash\npip install pudb\nPYTHONBREAKPOINT=pudb.set_trace pytest --pdb\n```\n\nSet `PYTHONBREAKPOINT` globally so `breakpoint()` anywhere uses your preferred debugger:\n\n```bash\nexport PYTHONBREAKPOINT=ipdb.set_trace\n# or for VS Code's debugger protocol:\nexport PYTHONBREAKPOINT=debugpy.breakpoint\n```\n\nThe `breakpoint()` builtin in Python 3.7+ respects `PYTHONBREAKPOINT`, so you can switch debuggers without touching source. `PYTHONBREAKPOINT=0` disables every `breakpoint()` call — useful in production as a safety net against leftover debug calls.",
)

add(
    "You are a packaging expert.",
    "Show me a .gitignore for a typical Python project.",
    "Cover virtualenvs, build artifacts, caches, and IDE files.\n\n```gitignore\n# Byte-compiled\n__pycache__/\n*.py[cod]\n*$py.class\n*.so\n\n# Virtualenvs\n.venv/\nvenv/\nenv/\n.python-version\n\n# Packaging / distribution\nbuild/\ndist/\n*.egg-info/\n*.egg\nwheels/\n\n# Tools and caches\n.pytest_cache/\n.mypy_cache/\n.ruff_cache/\n.hypothesis/\n.tox/\n.nox/\n.coverage\n.coverage.*\ncoverage.xml\nhtmlcov/\n.pyre/\n\n# Jupyter\n.ipynb_checkpoints/\n\n# Dependency manager caches (not their locks, which you commit!)\n.uv-cache/\n\n# IDE\n.vscode/\n.idea/\n*.swp\n*.swo\n\n# OS\n.DS_Store\nThumbs.db\n```\n\n**Do** commit:\n- `pyproject.toml`, `uv.lock`, `poetry.lock`, `requirements*.txt`\n- `.pre-commit-config.yaml`\n- `.github/workflows/*`\n- `.python-version` if using pyenv for dev\n\n**Do not** commit:\n- `.env` files with secrets (use `.env.example` instead)\n- `coverage.xml` (CI generates it each run)\n- `node_modules/` or site-packages\n\nStart from the canonical GitHub Python `.gitignore` template and prune what you do not use.",
)

add(
    "You are a testing expert.",
    "Write a fixture that mocks a single module's function for the whole test module.",
    "Use an autouse, module-scoped fixture.\n\n```python\nimport pytest\nfrom unittest.mock import patch\n\n@pytest.fixture(autouse=True, scope=\"module\")\ndef fake_network():\n    with patch(\"myapp.client.requests.get\") as mock:\n        mock.return_value.status_code = 200\n        mock.return_value.json.return_value = {\"ok\": True}\n        yield mock\n\ndef test_a():\n    from myapp.client import fetch\n    assert fetch() == {\"ok\": True}\n\ndef test_b():\n    from myapp.client import fetch\n    assert fetch(\"override\") == {\"ok\": True}\n```\n\nEvery test in the module runs with `requests.get` replaced. Because scope is `module`, the patch is applied once for the whole file and unwound when the module's tests finish.\n\nBeware two gotchas:\n1. **Mock state leaks** across tests: `mock.call_count` accumulates. If a test needs counts, either reset in a nested fixture or switch to function-scoped.\n2. **Don't combine module-scoped `patch` with parallel xdist on the same module** — xdist runs tests in order per worker, so this is safe, but it is worth knowing the mock is shared state.\n\nTrade-off: faster and cleaner code when the patch is uniform. For cases where tests need different mock behaviors, use a function-scoped mocker fixture instead.",
)

add(
    "You are a debugging expert.",
    "How do I use pdb's post-mortem mode on an unhandled exception?",
    "Run the script with `python -m pdb` or call `pdb.pm()` after the crash.\n\n```bash\npython -m pdb -c continue myscript.py\n# -c continue starts by running until the exception; drops into pdb post-mortem\n```\n\nInside an interactive session:\n\n```python\n>>> import pdb\n>>> crash()\nTraceback (most recent call last):\n  ...\nValueError: bad input\n>>> pdb.pm()          # drops into pdb at the crash site\n(Pdb) l\n(Pdb) p locals()\n(Pdb) u               # move up the stack\n```\n\nAutomatic post-mortem on any unhandled exception:\n\n```python\n# debughook.py\nimport sys, pdb\n\ndef excepthook(type_, value, tb):\n    pdb.post_mortem(tb)\n\nsys.excepthook = excepthook\n```\n\n`python -i script.py` runs the script, leaves you at an REPL on exit/crash, so you can `pdb.pm()` manually. Pytest exposes this via `--pdb`; Django has `--pdb` in shell_plus. Post-mortem is the single best reason to prefer pdb over print-debugging: you see the real stack at the moment of failure, with all locals, rather than deducing them from incomplete logs.",
)

add(
    "You are a testing expert.",
    "Configure pytest-sugar for prettier output.",
    "Install and it takes effect automatically.\n\n```bash\npip install pytest-sugar\npytest   # progress bar, emoji status, instant failure report\n```\n\nDisable if you want plain output:\n\n```bash\npytest -p no:sugar\n```\n\nOr disable per-run:\n\n```toml\n[tool.pytest.ini_options]\naddopts = \"-p no:sugar --tb=short\"\n```\n\nAlternatives and companions:\n\n- `pytest-rich` — rich-library-powered output, closer to structured panels\n- `pytest-clarity` — better assertion diffs for complex objects\n- `pytest-split` — split tests into parallel groups by duration, complementary to xdist\n- `pytest-icdiff` — colorful `icdiff` for large object comparisons\n- `pytest-reverse` — run tests in reverse order to surface ordering dependencies\n\nOn CI, skip the fancy UI (`-p no:sugar`) to keep logs grep-friendly and machine-readable. Use JUnit XML for parseable output:\n\n```bash\npytest --junitxml=report.xml\n```\n\nUpload the XML to CI dashboards (GitHub test-reporter, CircleCI's `store_test_results`, GitLab's `reports:junit`) for clickable failures in the web UI.",
)

add(
    "You are a testing expert.",
    "Test thread-safety of a function with concurrent.futures.",
    "Submit many parallel calls and assert invariants.\n\n```python\nimport threading\nimport pytest\nfrom concurrent.futures import ThreadPoolExecutor, as_completed\n\nclass Counter:\n    def __init__(self):\n        self.n = 0\n        self._lock = threading.Lock()\n    def inc(self):\n        with self._lock:\n            self.n += 1\n\ndef test_thread_safe_counter():\n    c = Counter()\n    per_thread = 1000\n    threads = 10\n    with ThreadPoolExecutor(max_workers=threads) as pool:\n        futures = [pool.submit(c.inc) for _ in range(threads * per_thread)]\n        for f in as_completed(futures):\n            f.result()\n    assert c.n == threads * per_thread\n\ndef test_without_lock_is_racy():\n    class Bad:\n        def __init__(self): self.n = 0\n        def inc(self): self.n += 1\n    b = Bad()\n    total = 10_000\n    with ThreadPoolExecutor(max_workers=20) as pool:\n        for _ in range(total):\n            pool.submit(b.inc)\n    # no assertion — because of GIL this often but not always loses updates.\n    # for a truly reliable race demonstration, test with free-threaded Python 3.13t\n```\n\nThread tests can be flaky because races are probabilistic. Increase work per test to make races more likely, or run under free-threaded `python3.13t` where the GIL is off and contention is real. For deterministic concurrency testing, `pytest-shutil` / `pytest-timeout` guard against hangs.",
)

add(
    "You are a packaging expert.",
    "Set up a Makefile for common project tasks.",
    "A Makefile keeps commands discoverable and identical across machines.\n\n```makefile\n.PHONY: help setup test lint format type cov clean build publish\n.DEFAULT_GOAL := help\n\nPY := .venv/bin/python\nUV := uv\n\nhelp:\n\t@awk 'BEGIN {FS = \":.*?## \"} /^[a-zA-Z_-]+:.*?## / {printf \"  %-12s %s\\n\", $$1, $$2}' $(MAKEFILE_LIST)\n\nsetup:  ## create venv and install deps\n\t$(UV) sync --all-extras\n\t$(UV) run pre-commit install\n\ntest:   ## run the test suite\n\t$(UV) run pytest -n auto\n\nlint:   ## lint with ruff\n\t$(UV) run ruff check .\n\nformat: ## format with ruff\n\t$(UV) run ruff format .\n\ntype:   ## type check with mypy\n\t$(UV) run mypy src\n\ncov:    ## run tests with coverage\n\t$(UV) run pytest --cov=myapp --cov-report=html --cov-report=term-missing\n\nclean:  ## remove caches and build artifacts\n\trm -rf build dist *.egg-info .pytest_cache .mypy_cache .ruff_cache htmlcov .coverage .hypothesis\n\nbuild:  ## build sdist + wheel\n\t$(UV) build\n\npublish: build ## publish to PyPI (trusted publishing preferred)\n\t$(UV) run twine upload dist/*\n```\n\n`make help` lists every target (the awk parses `## comments`). Use tab indentation, not spaces, because Make is picky. Commit the Makefile and document the three commands newcomers need: `make setup`, `make test`, `make lint`.",
)

add(
    "You are a testing expert.",
    "How do I run a single pytest test by name?",
    "Use the `::` selector.\n\n```bash\npytest tests/test_user.py                           # whole file\npytest tests/test_user.py::test_create              # one function\npytest tests/test_user.py::TestUser::test_create    # class + method\npytest tests/test_user.py::test_create[case-3]      # one parametrized case\n\n# by keyword (substring match across node ids)\npytest -k \"create and not admin\"\npytest -k \"login or logout\"\n\n# by marker\npytest -m slow\npytest -m \"not slow\"\n\n# combine\npytest -k login -m \"not slow\"\n```\n\nYou can copy the ID straight out of a failure report:\n\n```\nFAILED tests/test_user.py::TestUser::test_create[alice]\n```\n\nRerun that exact one:\n\n```bash\npytest \"tests/test_user.py::TestUser::test_create[alice]\"\n```\n\n(Quote the string so the shell does not interpret `[]`.)\n\nTo list tests without running them:\n\n```bash\npytest --collect-only -q     # quiet listing\npytest --collect-only -q | grep create\n```\n\nUse `-k` for quick exploratory filtering, `-m` for markers (slow, integration, smoke), and `::` when you know the exact node.",
)

add(
    "You are a testing expert.",
    "Write a regression test from a bug report with minimal repro.",
    "Capture the exact input and expected output, then add `@example` if property-based.\n\n```python\n# bug: parse_duration returned 60 for \"1m\" but 0 for \"1 m\" (space)\nimport pytest\nfrom myapp.time import parse_duration\n\n@pytest.mark.parametrize(\"raw, expected\", [\n    # original docstring cases still pass\n    (\"1s\", 1),\n    (\"1m\", 60),\n    (\"1h\", 3600),\n    # regression for issue #187\n    (\"1 m\", 60),\n    (\"2 h 30 m\", 2 * 3600 + 30 * 60),\n    (\"  1s  \", 1),\n])\ndef test_parse_duration_regression_187(raw, expected):\n    assert parse_duration(raw) == expected\n```\n\nFor Hypothesis tests, pin the specific failing example so it never slips:\n\n```python\nfrom hypothesis import given, example, strategies as st\n\n@given(st.text())\n@example(s=\"1 m\")  # from issue #187\n@example(s=\"2 h 30 m\")\ndef test_parse_duration_property(s):\n    try:\n        n = parse_duration(s)\n    except ValueError:\n        return\n    assert isinstance(n, int) and n >= 0\n```\n\nReference the bug number in the test name, parametrize with the failing input, and keep the old passing cases alongside. A regression test's job is one-shot: \"does this specific bug come back?\" Stay targeted.",
)

add(
    "You are a testing expert.",
    "How do I randomize test execution order to catch order dependencies?",
    "`pytest-randomly` shuffles tests each run with a printed seed.\n\n```bash\npip install pytest-randomly\npytest                          # tests run in random order\npytest -p no:randomly           # disable for one run\npytest --randomly-seed=1234     # reproduce a specific ordering\npytest --randomly-seed=last     # re-use the previous run's seed\n```\n\nOn failure, the output begins with:\n\n```\nUsing --randomly-seed=2026041701\n```\n\nCopy that seed into a second run to reproduce the exact failure order. Combine with `--lf` to focus on just the failing tests in that order.\n\nWhy randomize: flakiness from test order is one of the most common CI horror stories. A test might pass in alphabetical order because an earlier test left a row in the database; under randomization, it fails, and you learn about the coupling now instead of during a release.\n\n`pytest-randomly` also seeds `random.seed`, `numpy.random.seed`, and the Python hash seed deterministically per session, so probabilistic code within tests is also reproducible once the seed is known.",
)

add(
    "You are a testing expert.",
    "Show me a pattern for golden-file tests (expected output in a file).",
    "Read the expected output from a file; regenerate with an env flag.\n\n```python\nimport os\nfrom pathlib import Path\nimport pytest\n\nGOLDEN_DIR = Path(__file__).parent / \"golden\"\nUPDATE = os.environ.get(\"UPDATE_GOLDEN\") == \"1\"\n\ndef golden(name: str, actual: str):\n    path = GOLDEN_DIR / name\n    if UPDATE:\n        path.parent.mkdir(parents=True, exist_ok=True)\n        path.write_text(actual)\n        return\n    expected = path.read_text()\n    assert actual == expected, (\n        f\"{name} differs; run UPDATE_GOLDEN=1 pytest to regenerate\"\n    )\n\ndef test_report_renders():\n    from myapp.report import render\n    out = render(sample_data())\n    golden(\"report.txt\", out)\n\ndef test_cli_help_text():\n    import subprocess\n    out = subprocess.check_output([\"mytool\", \"--help\"], text=True)\n    golden(\"cli_help.txt\", out)\n```\n\nRun:\n\n```bash\npytest                            # verify against stored golden\nUPDATE_GOLDEN=1 pytest            # regenerate the files after intentional changes\n```\n\nReview the diff in git before committing regenerated files. Golden files shine for:\n- Generated configuration (Terraform, k8s YAML)\n- Reports, emails, help text\n- Structured CLI output\n\n`syrupy` formalizes this pattern with auto-update and per-test isolation.",
)

add(
    "You are a debugging expert.",
    "How do I debug slow imports on Python startup?",
    "`python -X importtime` logs every import with its time contribution.\n\n```bash\npython -X importtime myscript.py 2> imports.log\n\n# or pipe to the built-in formatter\npython -X importtime myscript.py 2>&1 | grep import >tmp\ntuna tmp   # pip install tuna — interactive HTML view\n```\n\nOutput columns: `import time (self) | import time (cumulative) | imported package`. Cumulative is what matters for \"why is startup slow\" questions. Look for surprises: large libraries pulled in by a small helper, conditional imports actually evaluated, or module-level IO.\n\nExample output interpretation:\n\n```\nimport time:       150 |      8312 | pandas\n```\n\npandas cost 8.3ms itself and pulled in a subtree totaling 150ms. If you only import pandas for one function, consider lazy-import:\n\n```python\ndef plot(data):\n    import pandas as pd     # defer cost until first call\n    import matplotlib.pyplot as plt\n    ...\n```\n\nCommon wins: move heavy imports into the function that uses them, replace `from x import *`, avoid `__init__.py` side effects. Startup time matters for CLIs, serverless handlers, and test suites — an extra second multiplied by every test run adds up.",
)

add(
    "You are a testing expert.",
    "Show me how to use mutation testing with mutmut.",
    "`mutmut` mutates your source and verifies tests catch the mutations.\n\n```bash\npip install mutmut\nmutmut run --paths-to-mutate=src/myapp/\n# mutmut makes a swap (e.g. `+` -> `-`), runs tests, records if they fail\n\nmutmut results    # see stats\nmutmut show       # see survivors (mutations tests did NOT catch)\nmutmut show 17    # details of a specific mutation\nmutmut html       # browsable report\n```\n\nA high mutation score means your tests actually distinguish correct from incorrect behavior. A test suite with 100% line coverage but poor mutation score is a suite that runs code without asserting on it.\n\nConfig in `setup.cfg` or `pyproject.toml`:\n\n```toml\n[tool.mutmut]\npaths_to_mutate = \"src/myapp/\"\ntests_dir = \"tests/\"\nbackup = false\n```\n\nExpect:\n- First run is slow (one test-suite run per mutation). Use a fast subset (`--runner=\"pytest -x --tb=no -q\"`).\n- Mutation testing on every CI run is usually overkill; run nightly or on release.\n- Some mutations are equivalent (change `x + 0` to `x - 0`) and cannot be killed. Mark them as ignored.\n\nAlternative: `cosmic-ray` with richer mutation operators but more setup.",
)

add(
    "You are a packaging expert.",
    "Configure Python project for PyPI trusted publishing via GitHub.",
    "Configure PyPI, remove tokens, run release workflow with OIDC.\n\n1. On PyPI (project settings -> Publishing -> Add a new pending publisher):\n   - Owner: your-github-username\n   - Repository: your-repo\n   - Workflow: `release.yml`\n   - Environment: `pypi` (optional but recommended)\n\n2. On GitHub (repository -> Settings -> Environments -> New environment `pypi`):\n   - Required reviewers (optional): an extra human gate\n   - Deployment branches: tags only, pattern `v*`\n\n3. `.github/workflows/release.yml`:\n\n```yaml\nname: release\non:\n  push:\n    tags: [\"v*\"]\n\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v5\n      - uses: actions/setup-python@v6\n        with: { python-version: \"3.12\" }\n      - run: pip install build\n      - run: python -m build\n      - uses: actions/upload-artifact@v4\n        with: { name: dist, path: dist/ }\n\n  publish:\n    needs: build\n    runs-on: ubuntu-latest\n    environment: pypi\n    permissions:\n      id-token: write\n    steps:\n      - uses: actions/download-artifact@v4\n        with: { name: dist, path: dist/ }\n      - uses: pypa/gh-action-pypi-publish@release/v1\n```\n\nNo `PYPI_TOKEN` secret needed. Push a tag `v1.2.3` and release. Short-lived OIDC tokens eliminate long-lived credentials entirely.",
)

add(
    "You are a testing expert.",
    "How do I avoid network calls in tests?",
    "Use `pytest-socket` to ban network globally and whitelist loopback.\n\n```bash\npip install pytest-socket\n```\n\n```toml\n[tool.pytest.ini_options]\naddopts = \"--disable-socket --allow-hosts=127.0.0.1,localhost\"\n```\n\nNow any test that accidentally hits a real socket (DNS, HTTP, anything) fails loudly:\n\n```\nSocketBlockedError: A test tried to use socket.socket.\n```\n\nThe `--allow-hosts` exception lets integration tests talk to test containers running on loopback without opening the door wide.\n\nWhitelist per-test:\n\n```python\nimport pytest\n\n@pytest.mark.enable_socket\ndef test_integration_real_api():\n    ...\n\n@pytest.mark.allow_hosts([\"api.example.com\"])\ndef test_specific_host():\n    ...\n```\n\nFor HTTP specifically, `responses` (requests) / `respx` (httpx) / `aioresponses` (aiohttp) mock the client before pytest-socket ever kicks in, which is cheaper than a socket-level ban. Combine both: `pytest-socket` as the safety net, HTTP mocks as the primary tool.",
)

add(
    "You are a testing expert.",
    "Write a global conftest fixture that times each test.",
    "Use pytest hooks to record and report timings.\n\n```python\n# conftest.py\nimport time\nimport pytest\n\n_starts = {}\n\n@pytest.hookimpl(hookwrapper=True)\ndef pytest_runtest_call(item):\n    _starts[item.nodeid] = time.perf_counter()\n    yield\n\n@pytest.hookimpl(hookwrapper=True)\ndef pytest_runtest_logreport(report):\n    yield\n    if report.when == \"call\":\n        start = _starts.get(report.nodeid)\n        if start is not None:\n            elapsed = time.perf_counter() - start\n            if elapsed > 1.0:\n                print(f\"SLOW: {report.nodeid} took {elapsed:.2f}s\")\n\n\ndef pytest_terminal_summary(terminalreporter, exitstatus):\n    # print the 10 slowest tests; pytest has a built-in for this\n    pass\n```\n\nOr just use the built-in flag:\n\n```bash\npytest --durations=10        # top 10 slowest\npytest --durations=0         # all test durations, sorted\npytest --durations-min=1.0   # only those over 1.0s\n```\n\nOn CI, add `--durations=20` to get a visible list of slow outliers in every run. Trending those in a dashboard surfaces test suite regressions before they become \"why is CI 30 minutes now?\".",
)

add(
    "You are a testing expert.",
    "Explain xdist groups for tests that cannot be parallelized.",
    "Use `@pytest.mark.xdist_group` with `--dist=loadgroup`.\n\n```python\nimport pytest\n\n@pytest.mark.xdist_group(\"port-5432\")\ndef test_pg_insert(pg_conn):\n    ...\n\n@pytest.mark.xdist_group(\"port-5432\")\ndef test_pg_select(pg_conn):\n    ...\n\n@pytest.mark.xdist_group(\"global-state\")\ndef test_mutates_module_state():\n    ...\n```\n\nRun:\n\n```bash\npytest -n auto --dist=loadgroup\n```\n\nTests with the same group name always land on the same worker. Different groups may run in parallel on different workers. Tests without a group participate in normal `load` distribution.\n\nPatterns that require grouping:\n- Shared module-level state that is not thread-safe\n- A fixed external port (shared DB container, locked file)\n- Monkey-patched globals that bleed across the process\n\nBetter: eliminate the shared state so all tests can run in parallel. Per-worker resources via `pytest-xdist`'s `worker_id`:\n\n```python\nimport os, pytest\n\n@pytest.fixture(scope=\"session\")\ndef worker_port():\n    wid = os.environ.get(\"PYTEST_XDIST_WORKER\", \"gw0\")\n    base = 5432\n    return base + int(wid.removeprefix(\"gw\"))\n```\n\nEach worker gets its own port; no groups, no contention.",
)

add(
    "You are a debugging expert.",
    "How do I profile memory per line with memray?",
    "`memray` is a modern memory profiler with flame graphs and diff.\n\n```bash\npip install memray\n\nmemray run -o profile.bin myscript.py\nmemray flamegraph profile.bin                  # opens HTML flamegraph\nmemray table profile.bin                       # text table\nmemray stats profile.bin                       # summary\nmemray tree profile.bin                        # tree view\n```\n\nWith pytest:\n\n```bash\npip install pytest-memray\npytest --memray                  # reports memory for each test\npytest --memray --memray-bin-path=/tmp/mem\n```\n\n```python\nimport pytest\n\n@pytest.mark.limit_memory(\"10 MB\")\ndef test_stays_under_10mb():\n    # fails if allocations exceed 10 MB\n    build_big_thing()\n\n@pytest.mark.limit_leaks(\"100 KB\")\ndef test_no_leak():\n    process_stream()\n```\n\nThe flamegraph points directly at the lines allocating the most memory. For live processes (server already running), memray has an attach mode:\n\n```bash\nmemray attach <pid>\n```\n\nCompared to tracemalloc: memray has lower overhead, richer UI, and supports native extensions. Use memray when you can install extra tooling; tracemalloc when you want zero-dep diagnostics.",
)

add(
    "You are a testing expert.",
    "Reuse pytest configuration across many small packages in a monorepo.",
    "Put shared config in a root `pyproject.toml` and conftest, reference per-package.\n\n```\nmonorepo/\n  pyproject.toml          # root pytest + ruff + mypy config\n  conftest.py             # global fixtures/hooks\n  packages/\n    foo/\n      pyproject.toml      # package-specific overrides if needed\n      src/foo/\n      tests/\n    bar/\n      pyproject.toml\n      src/bar/\n      tests/\n```\n\nRoot `pyproject.toml`:\n\n```toml\n[tool.pytest.ini_options]\ntestpaths = [\"packages/*/tests\"]\naddopts = \"-ra --strict-markers --strict-config\"\nmarkers = [\n    \"slow\", \"integration\",\n]\n\n[tool.ruff]\nsrc = [\"packages/*/src\"]\n\n[tool.mypy]\nfiles = [\"packages/*/src\"]\n```\n\nPer-package overrides inherit root and can extend:\n\n```toml\n# packages/foo/pyproject.toml\n[tool.pytest.ini_options]\naddopts = \"-ra -m 'not slow'\"\n```\n\nRun from root:\n\n```bash\npytest                              # all packages\npytest packages/foo                 # only foo\npytest -m integration               # only integration across packages\n```\n\nShared fixtures go in the root `conftest.py`; package-specific ones in `packages/foo/tests/conftest.py`. pytest walks upward from the test location, so both apply without imports.",
)

add(
    "You are a testing expert.",
    "How do I handle flaky tests gracefully while a fix is in progress?",
    "Use `pytest-rerunfailures` and mark the test, but keep a ticket open.\n\n```bash\npip install pytest-rerunfailures\npytest --reruns=3 --reruns-delay=1\n```\n\nPer-test with a marker:\n\n```python\nimport pytest\n\n@pytest.mark.flaky(reruns=3, reruns_delay=2)\ndef test_sometimes_racy():\n    ...\n\n@pytest.mark.flaky(reruns=3, condition=\"os.name == 'nt'\")\ndef test_windows_only_flake():\n    ...\n```\n\nAlternatives:\n\n```python\n# pytest-repeat: run same test N times to catch intermittent failures before they hit CI\npytest --count=10 tests/test_race.py\n\n# pytest-flakefinder: run all tests many times\npytest --flake-finder --flake-runs=5\n```\n\nRules for handling flakes:\n1. Always open a ticket. Re-running hides the bug, it does not fix it.\n2. Investigate the cause: usually timing, test-order dependency, or external-service variability.\n3. Do not `rerun` integration tests blindly — that masks real infrastructure instability.\n4. Remove the `@pytest.mark.flaky` once fixed.\n\nA healthy suite has <1% flake rate. Above that, the noise drowns real signal and engineers start auto-merging past red builds.",
)


Path("/tmp/gen_block_6.json").write_text(json.dumps(samples))
print(f"Block 6: {len(samples)}")
