#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank part 2 of 3: science and math topics."""


def register(T):
    # ===== SCIENCE =====

    T["the Coriolis effect"] = {
        "_cat": "science",
        "what": "an apparent deflection of moving objects observed in a rotating reference frame, most familiar as the rightward deflection of winds and currents in the Northern Hemisphere and leftward in the Southern Hemisphere caused by Earth's rotation",
        "how": "in an inertial frame, an object in motion travels in a straight line, but the ground beneath it rotates with the Earth. From the ground's perspective, the object appears to curve. The deflection magnitude is proportional to the object's speed, the sine of latitude, and twice the planet's angular velocity, with no deflection at the equator and maximum at the poles",
        "why": "the effect shapes large-scale atmospheric and oceanic circulation, sets the rotation direction of cyclones and hurricanes, drives the trade winds, and constrains long-range artillery and missile trajectories. Meteorology and oceanography are unintelligible without it",
        "vs": "unlike a real force such as gravity, the Coriolis force is a fictitious or inertial force that exists only in the rotating frame of an observer; from space it disappears. It also differs from the centrifugal force, which acts radially outward, while Coriolis acts perpendicular to the velocity vector",
        "ex": "a hurricane in the Atlantic spins counterclockwise because air flowing inward toward the low-pressure center is deflected to the right of its motion. Long-range artillery shells fired north in mid-latitudes drift several hundred meters east due to Coriolis deflection over their flight time",
        "mis": "people believe the Coriolis effect determines which way water spirals down a bathroom sink. At that scale the effect is utterly swamped by basin shape, residual swirl from filling, and tap geometry. Coriolis only dominates over horizontal scales of hundreds of kilometers and time scales of hours or longer",
    }

    T["quantum tunneling"] = {
        "_cat": "science",
        "what": "a quantum-mechanical phenomenon in which a particle passes through a potential energy barrier that, by classical mechanics, it lacks the energy to surmount. The particle's wavefunction extends into and through the barrier with exponentially decaying amplitude",
        "how": "in the Schrodinger equation, the wavefunction inside a barrier higher than the particle's energy decays exponentially rather than vanishing. If the barrier is thin enough, a nonzero amplitude leaks through to the other side, where the wavefunction resumes oscillating. The transmission probability falls exponentially with barrier width and the square root of the height-energy gap",
        "why": "tunneling drives nuclear fusion in stars (protons would otherwise never overcome Coulomb repulsion), powers alpha decay, enables the scanning tunneling microscope to image individual atoms, and underlies flash-memory programming and tunnel diodes. Without it, the Sun would not shine",
        "vs": "tunneling differs from classical barrier crossing where energy must equal or exceed the barrier height. It differs from quantum reflection (a particle bouncing off a barrier despite having more than enough energy) in that tunneling penetrates a barrier that classically should reflect it. It also differs from over-the-top thermal activation, which dominates at high temperatures",
        "ex": "in a scanning tunneling microscope, a sharp metal tip held about a nanometer above a conducting surface drives a tiny tunneling current across the vacuum gap. The current depends so sensitively on distance (changing by a factor of ten per angstrom) that scanning the tip across the surface maps individual atoms with sub-angstrom resolution",
        "mis": "people think tunneling lets particles teleport, but the wavefunction is continuous on both sides and the particle's probability density inside the barrier is real, not zero. Another myth is that tunneling violates energy conservation; energy is conserved on average, with the brief barrier traversal allowed by the time-energy uncertainty relation",
    }

    T["Bose-Einstein condensates"] = {
        "_cat": "science",
        "what": "a state of matter formed when bosons (particles with integer spin) are cooled to within a billionth of a degree of absolute zero, at which point a macroscopic fraction of them collapses into the lowest available quantum state and behaves as a single coherent quantum entity",
        "how": "as temperature drops, the de Broglie wavelength of each atom grows until it overlaps with neighbors. Below a critical temperature, identical bosons preferentially occupy the ground state because Bose-Einstein statistics favor multiple particles in the same state. Laser cooling and evaporative cooling in magnetic traps reach the required temperatures, typically 100 nanokelvin",
        "why": "BECs let physicists probe quantum mechanics at human scales: the condensate has a single wavefunction kilometers wide compared to atomic dimensions. They enable atom interferometers of extreme precision, model superfluidity and superconductivity, simulate condensed-matter Hamiltonians, and test fundamental physics like CPT invariance",
        "vs": "BECs differ from ordinary gases (random thermal motion) and from solids (frozen lattice positions) by being macroscopically quantum coherent. They differ from superconductors, where Cooper pairs of electrons condense, in that BECs involve neutral atoms and lack the charged-current properties. They differ from fermionic condensates of paired fermions like helium-3",
        "ex": "the 1995 BEC of rubidium-87 atoms by Cornell, Wieman, and Ketterle (Nobel Prize 2001) cooled about 2000 atoms below 170 nanokelvin in a magnetic trap. Time-of-flight imaging showed a sharp central peak rising above the thermal cloud, the unmistakable signature of macroscopic ground-state occupation",
        "mis": "people think a BEC is just a very cold gas, but it is a genuinely new phase characterized by macroscopic phase coherence and superfluidity. Another myth is that BECs require special exotic atoms; almost any boson works (rubidium, sodium, hydrogen, lithium-7), and even photons in dye-filled microcavities have been condensed",
    }

    T["the uncertainty principle"] = {
        "_cat": "science",
        "what": "a fundamental quantum-mechanical limit on how precisely certain pairs of complementary observables can be simultaneously known. Heisenberg's relation states that the product of position and momentum uncertainties is at least h-bar over two, with similar relations for energy-time and other conjugate pairs",
        "how": "the principle follows mathematically from non-commuting operators in quantum theory: if two observables are represented by operators that do not commute, their values cannot be simultaneously definite in any quantum state. The position and momentum operators have a commutator equal to i*h-bar, which yields the uncertainty product directly via the Robertson-Schrodinger inequality",
        "why": "the principle constrains every measurement at quantum scales, sets the zero-point energy of bound systems, stabilizes atoms against electron collapse into nuclei, governs the resolution of microscopes and particle accelerators, and underlies the Casimir effect and vacuum fluctuations in quantum field theory",
        "vs": "the uncertainty principle differs from measurement disturbance in classical physics, which is in principle reducible by gentler measurement, in that no measurement protocol can ever beat the quantum bound. It also differs from statistical uncertainty over an ensemble; even individual quantum states have built-in spread",
        "ex": "an electron confined to a region the size of an atomic nucleus would have a momentum uncertainty so large that its kinetic energy would exceed the binding energy of any nucleus, which is why electrons orbit nuclei rather than being captured by them. Likewise, the energy-time relation lets virtual particles fluctuate from the vacuum on timescales h-bar over their energy",
        "mis": "people think the uncertainty principle is about the observer disturbing the system. While Heisenberg's original microscope argument used disturbance heuristics, the modern formulation is a property of the wavefunction itself, present even when no measurement is made. Another myth is that it applies to all observable pairs; only non-commuting (conjugate) pairs are constrained",
    }

    T["chirality in molecules"] = {
        "_cat": "science",
        "what": "the geometric property of a molecule that makes it non-superimposable on its mirror image, like a left and right hand. Chiral molecules exist as pairs of enantiomers, often centered on a carbon atom bonded to four different groups, with identical scalar properties but opposite optical rotation",
        "how": "a chiral center, typically a tetrahedral carbon with four distinct substituents, creates two arrangements that cannot be rotated into one another. R and S designations come from the Cahn-Ingold-Prelog priority rules. Chemists separate enantiomers via chiral chromatography, asymmetric synthesis with chiral catalysts, or selective crystallization with a chiral resolving agent",
        "why": "biology is profoundly chiral: proteins use only L-amino acids, DNA only D-sugars, and enzymes are exquisitely sensitive to handedness. Drug efficacy and toxicity often differ dramatically between enantiomers, which is why the FDA increasingly requires single-enantiomer formulations and why chiral synthesis is a multi-billion-dollar industry",
        "vs": "chirality differs from cis-trans isomerism, which involves spatial arrangement around a double bond rather than mirror-image relationships. It differs from constitutional isomerism (different connectivity) and from conformational variation (interconvertible by rotation). Two enantiomers have identical melting points, NMR spectra, and most reactions; only chiral environments distinguish them",
        "ex": "carvone has two enantiomers: (R)-carvone smells like spearmint, while (S)-carvone smells like caraway, because olfactory receptors in the nose are themselves chiral. Thalidomide's tragic 1960s history is the canonical pharmaceutical example: one enantiomer treated morning sickness, the other caused severe birth defects",
        "mis": "people think enantiomers behave identically in all contexts; they only behave identically in achiral environments. In a chiral environment (every biological system, every chiral solvent, every polarized-light measurement), enantiomers can behave wildly differently. Another myth is that chiral synthesis is exotic; it is now routine pharmaceutical practice",
    }

    T["polymer chemistry"] = {
        "_cat": "science",
        "what": "the study of macromolecules built from many repeating monomer units linked by covalent bonds. Polymers include synthetic plastics (polyethylene, nylon, polystyrene), elastomers (rubber), fibers (polyester, Kevlar), and biological macromolecules (proteins, DNA, cellulose)",
        "how": "monomers join through addition polymerization (free radicals propagating across double bonds, as in polyethylene) or condensation polymerization (loss of small molecules like water during bond formation, as in nylon). Chain length, branching, cross-linking, and tacticity determine bulk properties. Catalysts like Ziegler-Natta enable controlled stereochemistry and chain-length distributions",
        "why": "polymers underpin modern material life: packaging, clothing, electronics, vehicles, medical devices, and adhesives are mostly polymeric. Tailoring chain architecture lets chemists tune density, strength, transparency, conductivity, and biodegradability. Without synthetic polymers, no plastic bottles, no airbags, no contact lenses, no MRI gradients",
        "vs": "polymers differ from small molecules in that they are statistical mixtures of chain lengths rather than discrete species, so properties depend on distributions (number-average vs weight-average molecular weight). Thermoplastics (reversibly meltable) differ from thermosets (cross-linked, infusible). Linear vs branched vs cross-linked architectures yield very different mechanical responses",
        "ex": "ultra-high-molecular-weight polyethylene (UHMWPE) used in artificial hip joints has chains of millions of carbons each, giving extreme abrasion resistance. Kevlar, an aromatic polyamide with rigid rod-like chains aligned by liquid-crystalline processing, is so strong by weight that bullet-resistant vests use only a few millimeters of woven fabric",
        "mis": "people think all plastics are interchangeable, but a single bond in a monomer (carbon-carbon vs carbon-oxygen, all-carbon vs aromatic) reshapes performance entirely. Another myth is that biodegradable always means good; many bioplastics need industrial composting at controlled temperature and humidity to break down, not ordinary landfill conditions",
    }

    T["molecular orbital theory"] = {
        "_cat": "science",
        "what": "a quantum-mechanical model of bonding in which atomic orbitals on neighboring atoms combine to form molecular orbitals that span the whole molecule. Electrons fill these molecular orbitals according to the Aufbau principle, the Pauli exclusion principle, and Hund's rule, giving rise to bonding, antibonding, and nonbonding states",
        "how": "linear combinations of atomic orbitals (LCAO) yield molecular orbitals: in-phase combinations produce bonding orbitals lower in energy than the parent atomic orbitals, out-of-phase combinations produce antibonding orbitals higher in energy. Symmetry constrains which atomic orbitals can mix. Filling order then determines bond order, magnetism, and ionization energies",
        "why": "MO theory explains phenomena that simple Lewis structures cannot: oxygen's paramagnetism, the bond order of fractional values, the colors of organic dyes, the conductivity of conjugated polymers, and the electronic structure of metal complexes. It is the foundation of computational chemistry and quantum-chemical methods like DFT and Hartree-Fock",
        "vs": "MO theory differs from valence bond theory, which views bonding as overlapping localized atomic orbitals between specific pairs of atoms. MO is delocalized; VB is localized. For ground-state energies, modern MO methods (post-Hartree-Fock, DFT) are usually more accurate, while VB language remains intuitive for chemists drawing structures and predicting reactivity",
        "ex": "molecular oxygen has a bond order of two but two unpaired electrons in its degenerate antibonding pi-star orbitals, making it paramagnetic, a fact MO theory predicts directly but Lewis dot structures cannot. Liquid oxygen is famously sticky to a magnet because of this paramagnetism",
        "mis": "people think MO theory and VB theory contradict each other; they are equivalent when carried to convergence, just expressed in different basis sets. Another myth is that MOs are physical objects; they are mathematical solutions of a one-electron approximation, useful for thinking but not directly observable",
    }

    T["the citric acid cycle"] = {
        "_cat": "science",
        "what": "also called the Krebs cycle or TCA cycle, a series of eight enzymatic reactions in the mitochondrial matrix that oxidizes the acetyl group of acetyl-CoA to two carbon dioxide molecules, capturing the energy as NADH, FADH2, and GTP. It is the central hub of aerobic metabolism for carbohydrates, fats, and amino acids",
        "how": "acetyl-CoA condenses with oxaloacetate to form citrate, which is rearranged to isocitrate, oxidatively decarboxylated to alpha-ketoglutarate (releasing CO2 and NADH), further oxidized and decarboxylated to succinyl-CoA (more CO2 and NADH), then converted through succinate, fumarate, malate, and back to oxaloacetate, generating GTP, FADH2, and another NADH along the way",
        "why": "the cycle is the metabolic crossroads of cellular life. Its NADH and FADH2 feed the electron transport chain, producing roughly two-thirds of the ATP your cells make. Its intermediates also serve as precursors for amino acids, heme, and fatty acid synthesis, so the cycle runs in both catabolic and biosynthetic directions",
        "vs": "the cycle differs from glycolysis (cytoplasmic, anaerobic-capable, produces pyruvate and a small amount of ATP) by being mitochondrial, strictly aerobic in net flux, and producing the bulk of reducing equivalents. It differs from the urea cycle (nitrogen disposal) and the pentose phosphate pathway (NADPH and ribose generation) in central role",
        "ex": "during sustained aerobic exercise, your skeletal muscle mitochondria run the cycle at high flux: pyruvate from glucose enters as acetyl-CoA, fatty acids from beta-oxidation enter as acetyl-CoA, and oxaloacetate is regenerated cycle after cycle. Citrate transported out of mitochondria becomes the carbon source for fatty acid synthesis when energy is plentiful",
        "mis": "people think the cycle directly produces large amounts of ATP, but each turn yields only one GTP. The huge ATP output comes downstream when NADH and FADH2 donate electrons to the electron transport chain. Another myth is that it runs only in the catabolic direction; many intermediates flow outward as biosynthetic precursors continually",
    }

    T["mitosis vs meiosis"] = {
        "_cat": "science",
        "what": "two distinct types of eukaryotic cell division. Mitosis produces two genetically identical diploid daughter cells from one parent and is responsible for growth and tissue repair. Meiosis produces four genetically distinct haploid daughter cells from one diploid parent and is responsible for forming gametes (sperm and eggs)",
        "how": "mitosis is one round of DNA replication followed by one division: prophase, metaphase, anaphase, telophase, separating sister chromatids. Meiosis is one round of replication followed by two divisions. Meiosis I separates homologous chromosomes (with crossing-over recombination during prophase I) and is reductional; meiosis II separates sister chromatids like mitosis",
        "why": "mitosis lets multicellular organisms grow from one cell to trillions and replace lost tissue without genetic drift. Meiosis generates genetic variation through independent assortment and recombination, which is the raw material of natural selection, and halves chromosome count so fertilization restores diploidy without doubling each generation",
        "vs": "mitosis preserves chromosome number and genome identity; meiosis halves the number and reshuffles the genome. Mitosis has one division producing two cells; meiosis has two divisions producing four. Mitosis happens in nearly every dividing somatic cell; meiosis happens only in germ-line cells. Crossing-over occurs in meiosis I, never in mitosis under normal conditions",
        "ex": "a fertilized human egg with 46 chromosomes divides by mitosis trillions of times to build the body, every cell genetically identical (barring mutation). When that body matures, germ-line cells in the gonads undergo meiosis: a primary spermatocyte with 46 chromosomes produces four sperm with 23 each, every sperm genetically distinct because of recombination",
        "mis": "people think meiosis is just a fancier mitosis; in fact, the mechanics are deeply different in meiosis I where homologous chromosomes pair, recombine, and segregate together. Another myth is that recombination is rare; on average each human chromosome experiences one or two crossovers per meiosis, so every gamete is genetically unique",
    }

    T["genetic mutation types"] = {
        "_cat": "science",
        "what": "permanent changes in DNA sequence, classified by scale and effect. Point mutations alter single bases (substitutions split into transitions and transversions); indels insert or delete bases; large-scale changes include duplications, inversions, translocations, and copy-number variants. By coding effect: silent, missense, nonsense, frameshift",
        "how": "mutations arise from DNA-replication errors, spontaneous deamination of cytosine to uracil, oxidative damage producing 8-oxoguanine, UV-induced thymine dimers, ionizing radiation breaking strands, and chemical mutagens forming adducts. Repair systems (mismatch repair, base excision, nucleotide excision, double-strand break repair) catch most lesions, but escapes accumulate as inheritable mutations",
        "why": "mutations are the raw material of evolution and the origin of inherited disease and cancer. Single-base changes can convert a normal gene to an oncogene, abolish enzyme activity in a metabolic disorder, or shift binding affinity of a protein. Conversely, beneficial mutations underlie adaptation, antibiotic resistance, and species divergence",
        "vs": "silent mutations leave the encoded amino acid unchanged because of codon redundancy. Missense substitutes one amino acid for another with variable functional impact. Nonsense introduces a premature stop codon, usually truncating the protein. Frameshift indels (not multiples of three) shift every downstream codon and almost always destroy function. Large structural variants reshape entire chromosomes",
        "ex": "sickle cell anemia is a single missense mutation: a single A-to-T substitution in the beta-globin gene changes glutamate to valine at position six, causing hemoglobin to polymerize when deoxygenated and deforming red blood cells. Cystic fibrosis is most often a three-base deletion (delta F508) that removes one amino acid from the CFTR chloride channel",
        "mis": "people think all mutations are harmful, but the vast majority are neutral (in noncoding DNA or causing silent codon changes), and a small fraction are beneficial. Another myth is that mutations only happen in germ cells; somatic mutations accumulate continuously in body cells throughout life and drive cancer and aging",
    }

    T["the immune response"] = {
        "_cat": "science",
        "what": "the coordinated reaction of the body's defensive cells and molecules to detect, contain, and eliminate pathogens or abnormal cells. It has two arms: innate immunity (rapid, generic, pattern-based) and adaptive immunity (slower, specific, memory-forming, mediated by B and T lymphocytes)",
        "how": "innate cells like macrophages and neutrophils recognize pathogen-associated patterns via receptors such as Toll-like receptors and respond within minutes by phagocytosis and cytokine release. Dendritic cells present antigens to T cells in lymph nodes, activating helper and cytotoxic T-cell clones. B cells produce antibodies that neutralize, opsonize, or fix complement onto pathogens. Memory cells persist for years to decades",
        "why": "without immune defense, even minor infections become lethal, as seen in severe combined immunodeficiency. With a properly tuned immune system, you survive thousands of microbial encounters per day. Vaccines exploit memory formation to prepare immunity before exposure; cancer immunotherapy weaponizes T cells against tumors; transplant medicine fights against the system's tendency to reject foreign tissue",
        "vs": "innate immunity is pattern-based and immediate; adaptive immunity is antigen-specific and develops over days. Humoral immunity (antibodies, B cells) handles extracellular pathogens; cellular immunity (cytotoxic T cells) handles intracellular ones. Tolerance keeps the system from attacking self; allergy and autoimmunity arise when tolerance fails. Active immunity follows infection or vaccination; passive immunity comes pre-formed (maternal antibodies, immunoglobulin therapy)",
        "ex": "after a flu vaccine, dendritic cells take up the inactivated viral antigens, migrate to lymph nodes, and present peptides to naive T cells. Helper T cells activate B cells specific to the antigens, which mature into plasma cells secreting neutralizing antibodies and into memory cells. Months later, when live virus arrives, memory B and T cells respond within hours instead of days",
        "mis": "people think a stronger immune response is always better; in fact overactive immunity drives cytokine storms, autoimmunity, and severe allergic reactions. Another myth is that boosting immunity with supplements is straightforward; nutrient deficiencies impair immunity, but extra micronutrients beyond sufficiency rarely help and can harm",
    }

    T["the human microbiome"] = {
        "_cat": "science",
        "what": "the trillions of microorganisms (bacteria, archaea, fungi, viruses) inhabiting human body sites, especially the gut, skin, mouth, and urogenital tract. The collective genome of these microbes outnumbers human genes by roughly 100 to 1 and contributes substantially to digestion, immunity, and metabolism",
        "how": "microbes colonize body surfaces from birth, shaped by mode of delivery, breastfeeding, diet, antibiotics, and environment. They break down dietary fiber to short-chain fatty acids, synthesize vitamins (K, several B vitamins), train the developing immune system, exclude pathogens by occupying niches, and modulate host gene expression via metabolites that reach distant organs through blood",
        "why": "microbiome composition correlates with obesity, diabetes, inflammatory bowel disease, allergies, autism, depression, and response to cancer immunotherapy. Fecal microbiota transplants cure recurrent C. difficile infection at rates above ninety percent. Antibiotic stewardship and dietary fiber recommendations both rest on microbiome research",
        "vs": "the microbiome differs from infections in being a stable, mostly beneficial ecology rather than a transient pathogen. It differs from individual microbes in that ecological diversity and balance matter more than any single species. Compared to the host genome, which is fixed, the microbiome is dynamic and modifiable on timescales of days through diet and probiotics",
        "ex": "germ-free mice raised without microbes have abnormal immune development, reduced gut motility, altered bone density, and even behavioral differences. Colonizing them with conventional gut microbes reverses many phenotypes within weeks, demonstrating that the microbiome shapes physiology far beyond simple digestion",
        "mis": "people think the microbiome is mostly bacterial, ignoring the substantial archaeal, fungal, and viral components. Another myth is that probiotic supplements colonize permanently; most pass through transiently and require continued intake. A third is that we have ten times more microbial cells than human cells; the actual ratio is closer to one to one with high variability",
    }

    T["mitochondrial DNA"] = {
        "_cat": "science",
        "what": "a small circular DNA molecule of about 16,569 base pairs found inside mitochondria, separate from the nuclear genome. It encodes 37 genes (13 proteins of the electron transport chain, 22 transfer RNAs, 2 ribosomal RNAs) and is inherited almost exclusively from the mother",
        "how": "mitochondrial DNA replicates independently of the cell cycle, with multiple copies per mitochondrion and hundreds to thousands of mitochondria per cell. Heteroplasmy means a mix of variant copies coexists; replicative segregation during cell division can shift heteroplasmy levels dramatically over generations. Maternal inheritance results from sperm mitochondria being targeted for destruction after fertilization",
        "why": "mtDNA mutations cause distinctive disorders (Leber's hereditary optic neuropathy, MELAS, MERRF, Kearns-Sayre) with characteristic threshold effects: only above a heteroplasmy level does dysfunction appear. mtDNA is also a powerful tool for tracing maternal lineages in evolutionary genetics, forensics, and ancient DNA studies because it is abundant, robust, and uncomplicated by recombination",
        "vs": "mtDNA differs from nuclear DNA in being circular, much smaller, not bound to histones, and inherited maternally rather than biparentally. Its mutation rate is about ten times higher than nuclear DNA due to oxidative damage and weaker repair. It uses a slightly modified genetic code (UGA codes for tryptophan instead of stop in vertebrate mitochondria)",
        "ex": "Mitochondrial Eve, the most recent common matrilineal ancestor of all living humans, lived in Africa roughly 150,000-200,000 years ago. Tracking mtDNA haplogroups (L, M, N and their descendants) across populations has reconstructed major human migrations including the out-of-Africa expansion and the peopling of the Americas",
        "mis": "people think Mitochondrial Eve was the only woman alive at her time; many women lived alongside her, but only her matrilineal line has unbroken female-to-female descendants today. Another myth is that mtDNA never recombines; rare paternal leakage and recombination do occur but at vanishingly low rates that do not invalidate phylogenetic analyses",
    }

    T["epigenetics"] = {
        "_cat": "science",
        "what": "the study of heritable changes in gene expression that do not involve changes in the underlying DNA sequence. Major mechanisms include DNA methylation (typically at CpG sites), histone modifications (acetylation, methylation, phosphorylation), and noncoding RNAs that direct chromatin states",
        "how": "DNA methyltransferases add methyl groups to cytosine in CpG contexts, often silencing nearby gene expression by recruiting repressive complexes. Histone-modifying enzymes write, erase, and read marks like H3K4me3 (active promoters) and H3K27me3 (repressed regions). These marks shape chromatin structure, transcription factor accessibility, and ultimately whether genes are on or off in a given cell type",
        "why": "epigenetics explains how a single genome produces hundreds of cell types: every neuron and liver cell shares your DNA but expresses very different gene programs. Disrupted epigenetic regulation drives cancer, fragile X syndrome, Beckwith-Wiedemann syndrome, and aging. Drugs targeting epigenetic enzymes (DNMT inhibitors, HDAC inhibitors) treat several blood cancers",
        "vs": "epigenetics differs from genetic mutation in that the DNA sequence is unchanged; the modifications sit on top. It differs from transient gene regulation by being heritable through cell divisions and sometimes across generations. Compared to imprinted parental effects, epigenetics is broader and includes random as well as programmed marks",
        "ex": "X-chromosome inactivation in female mammals randomly silences one of the two X chromosomes in each cell early in development, then maintains the silenced state through every subsequent division by epigenetic memory. Calico cats display this directly: each patch of fur color reflects which X was silenced in that founder cell",
        "mis": "people think Lamarckian inheritance is back; transgenerational epigenetic inheritance in mammals is rare and mostly cleared between generations. Another myth is that lifestyle reliably reprograms your epigenome to fix problems; most lifestyle effects on methylation are modest and tissue-specific, not the wholesale rewriting popular media suggests",
    }

    T["central dogma of molecular biology"] = {
        "_cat": "science",
        "what": "Francis Crick's 1958 framework describing the flow of genetic information in cells: DNA is transcribed into RNA, and RNA is translated into protein. The dogma asserts that information cannot flow back from protein to nucleic acid, though specific exceptions like reverse transcription do exist",
        "how": "RNA polymerase reads a DNA template and synthesizes a complementary messenger RNA. The mRNA exits the nucleus, binds the ribosome, and codons are read three bases at a time. Transfer RNAs charged with amino acids deliver each amino acid as the ribosome catalyzes peptide bond formation, producing a polypeptide that folds into a functional protein",
        "why": "the dogma is the conceptual scaffold for genetics, molecular medicine, and biotechnology. Understanding that genes code for proteins via mRNA enabled gene therapy, mRNA vaccines, recombinant insulin, monoclonal antibodies, and CRISPR. Without it, every modern biological discipline would be operating in the dark",
        "vs": "the dogma differs from earlier ideas that proteins were the heritable material. It differs from later refinements that emphasize regulation: noncoding RNAs, riboswitches, and epigenetic marks all modulate the simple DNA-to-RNA-to-protein flow. Reverse transcription (RNA to DNA) and prion-style protein propagation are recognized exceptions but do not overturn the central principle",
        "ex": "an mRNA vaccine for COVID-19 introduces synthetic mRNA encoding the spike protein. Cells take up the mRNA, ribosomes translate it into spike protein on the cell surface, and the immune system mounts a response. The dogma plays out from injection through immune memory in a few days",
        "mis": "people interpret the dogma as forbidding any reversal of information flow, but Crick's original statement specifically excluded reverse transcription only as standard practice, not in principle. Another myth is that one gene equals one protein; alternative splicing, post-translational modification, and noncoding RNAs make the relationship many-to-many",
    }

    # ===== MATH =====

    T["systems of equations"] = {
        "_cat": "math",
        "what": "a collection of two or more equations sharing the same set of unknown variables, where a solution is any assignment of values that simultaneously satisfies every equation. They are classified by linearity, by number of equations versus unknowns, and by whether solutions exist (consistent vs inconsistent) and are unique",
        "how": "linear systems are solved by substitution, elimination (Gaussian or Gauss-Jordan), Cramer's rule via determinants, or matrix methods using the inverse or LU decomposition. Nonlinear systems require iterative methods like Newton-Raphson, often after good initial guesses. Geometrically, each linear equation in two variables is a line, and the solution is their intersection point",
        "why": "systems model essentially every constrained quantitative problem: chemical balancing, electrical circuit analysis, supply-demand equilibrium, structural force balances, and least-squares regression. Computer graphics, robotics, optimization, and machine learning routinely solve linear systems with millions of unknowns",
        "vs": "consistent systems have at least one solution; inconsistent systems have none (parallel lines that never meet). Determined systems with as many equations as unknowns typically have one unique solution; underdetermined systems have infinitely many; overdetermined systems are usually inconsistent and best handled by least-squares approximation",
        "ex": "balancing the chemical equation aC2H6 + bO2 -> cCO2 + dH2O reduces to a linear system in four unknowns from atomic conservation: 2a = c (carbon), 6a = 2d (hydrogen), 2b = 2c + d (oxygen). Solving gives a=2, b=7, c=4, d=6, so the balanced equation is 2C2H6 + 7O2 -> 4CO2 + 6H2O",
        "mis": "people think a system with three equations always has a solution if it has three unknowns; the equations may be redundant or contradictory. Another myth is that solving by substitution always works; for large systems, elimination and matrix methods scale far better, and substitution becomes algebraically intractable",
    }

    T["matrices and determinants"] = {
        "_cat": "math",
        "what": "a matrix is a rectangular array of numbers arranged in rows and columns that represents a linear transformation between vector spaces. The determinant is a scalar function of square matrices that captures how the transformation scales volumes and whether it preserves or reverses orientation",
        "how": "matrices are added componentwise and multiplied row-by-column with the standard rule. Determinants are computed by cofactor expansion, row reduction with sign tracking, or specialized formulas (2x2: ad - bc; 3x3: rule of Sarrus). For large matrices, LU decomposition gives the determinant as the product of pivots in O(n^3) time. Geometrically, abs(det A) is the volume of the image of the unit cube under A",
        "why": "matrices encode linear transformations cleanly, letting computers handle rotations, projections, and least-squares fits with bulk operations. Determinants detect singularity (det = 0 means non-invertible), compute volumes in change-of-variable formulas for integration, and express cross products and orientations in geometry",
        "vs": "matrices contrast with scalars (single numbers) and vectors (1D arrays) as 2D arrays. Square matrices have determinants; rectangular ones do not. Determinants differ from traces (sum of diagonal): both are invariants but capture different information. The determinant is also distinct from the rank (number of linearly independent rows or columns)",
        "ex": "a 2D rotation by angle theta has matrix [[cos, -sin], [sin, cos]] with determinant 1, confirming it preserves areas and orientation. A reflection across the x-axis has matrix [[1, 0], [0, -1]] with determinant -1, indicating it preserves area but flips orientation. A scaling by factor k along both axes has determinant k^2",
        "mis": "people think matrix multiplication is commutative; it is not in general, and the order matters fundamentally for transformations. Another myth is that the determinant has no geometric meaning; it is precisely the signed volume scaling factor of the transformation. A third confusion is that a zero determinant just means small; it means the transformation collapses some dimension entirely",
    }

    T["abstract algebra applications"] = {
        "_cat": "math",
        "what": "the use of group, ring, field, and module theory to solve concrete problems across mathematics, computer science, physics, and cryptography. Despite its abstract reputation, the framework yields surprisingly practical algorithms and structural insights",
        "how": "Galois theory determines which polynomial equations have solutions in radicals (the answer for general degree-five polynomials is no, the Abel-Ruffini theorem). Group theory classifies symmetries of crystals, molecules, and physical theories. Finite fields underpin error-correcting codes (Reed-Solomon) and elliptic-curve cryptography. Ring theory governs polynomial factorization algorithms used in computer algebra systems",
        "why": "the abstractions reveal that disparate problems share structure, so a result proven once in a general setting transfers to many concrete cases. CDs and DVDs use Reed-Solomon codes (finite-field arithmetic) to recover from scratches. Elliptic-curve TLS protects most of HTTPS traffic. Crystallographers classify all 230 space groups using group theory, organizing the entire solid-state world",
        "vs": "abstract algebra differs from elementary algebra by abstracting away the specific objects (numbers, polynomials) and focusing on operations and their properties. It differs from linear algebra by working with general algebraic structures rather than vector spaces over fields. Compared to category theory, abstract algebra remains within specific structures while category theory abstracts the relationships between them",
        "ex": "AES encryption operates on bytes interpreted as elements of the finite field GF(2^8), with the irreducible polynomial x^8 + x^4 + x^3 + x + 1. The S-box substitution and MixColumns step are concrete computations in this field, and their algebraic properties give AES its diffusion and resistance to linear cryptanalysis",
        "mis": "people think abstract algebra is too abstract for engineering use; in fact every internet transaction relies on it through public-key cryptography. Another myth is that you need years of preparation to apply it; basic group and field theory suffice for most practical algorithms in coding and cryptography",
    }

    T["non-Euclidean geometry"] = {
        "_cat": "math",
        "what": "geometries developed by abandoning Euclid's parallel postulate. Hyperbolic geometry replaces it with a postulate allowing infinitely many parallels through a point; elliptic (spherical) geometry allows none. Both are internally consistent, demonstrating that Euclid's geometry is not the only logically possible one",
        "how": "in hyperbolic geometry, the angle sum of a triangle is less than 180 degrees and decreases with area. In elliptic geometry, angle sums exceed 180 and lines (great circles) always intersect. Models like the Poincare disk for hyperbolic and the sphere itself for elliptic let mathematicians visualize these spaces using familiar Euclidean tools",
        "why": "non-Euclidean geometry liberated mathematics from the assumption that Euclid was uniquely true and prepared the ground for general relativity, where spacetime is curved by mass-energy. Modern cosmology asks empirically which geometry the universe has on cosmic scales (currently flat to within measurement error, but not by necessity)",
        "vs": "Euclidean geometry has zero curvature, parallel lines that never meet, and triangle angles summing to exactly 180. Hyperbolic has constant negative curvature, infinitely many parallels, angle sums under 180. Elliptic has constant positive curvature, no parallels, angle sums over 180. Riemannian geometry generalizes further to varying curvature",
        "ex": "the surface of the Earth is approximately elliptic on global scales: a triangle with vertices at the North Pole, Quito, and Nairobi has three nearly right angles, summing to about 270 degrees. Pilots flying great-circle routes are doing elliptic geometry whether they realize it or not, taking the shortest path on a curved surface",
        "mis": "people think non-Euclidean geometry is exotic and useless, but GPS systems incorporate general relativity (which uses curved geometry) to keep position accuracy within meters; ignoring it would accumulate kilometers of error per day. Another myth is that you cannot visualize hyperbolic space; the Poincare disk and Beltrami-Klein models make it quite tractable",
    }

    T["topology basics"] = {
        "_cat": "math",
        "what": "the branch of mathematics studying properties preserved under continuous deformation: stretching, bending, twisting without tearing or gluing. Topology asks not how big or curved an object is but what holes and connections it has, treating a coffee mug and a doughnut as topologically identical",
        "how": "open sets axiomatize the notion of nearness without distance. Continuous functions are defined by preimages of open sets being open. Topological invariants like the fundamental group, Euler characteristic, and homology groups distinguish spaces that cannot be continuously deformed into each other. Compactness, connectedness, and orientability classify spaces by global structure",
        "why": "topology underlies modern geometry, analysis, and physics. Knot theory in topology is used in DNA biology and cryptography. Topological data analysis extracts features from high-dimensional data. Topological insulators in condensed matter exploit topological protection for robust quantum states, with applications to spintronics and quantum computing",
        "vs": "topology differs from geometry by ignoring lengths, angles, and exact shapes, focusing only on qualitative connectivity. It differs from set theory by adding structure (the open sets) that makes continuity meaningful. Differential topology adds smoothness; algebraic topology uses groups to classify spaces; point-set topology studies the basic axioms",
        "ex": "a coffee mug and a torus are homeomorphic: you can continuously deform one into the other through stretching the handle into the hole. A sphere is not homeomorphic to a torus because the sphere has Euler characteristic 2 while the torus has 0. Knots are studied as embeddings of circles in 3-space up to ambient isotopy, with invariants like the Jones polynomial distinguishing them",
        "mis": "people think topology is just about exotic shapes, missing its central role in modern analysis where every theorem about continuity, convergence, and limits relies on topological foundations. Another myth is that all surfaces look alike topologically; the genus (number of holes) and orientability give a clean classification of compact surfaces",
    }

    T["fractal geometry"] = {
        "_cat": "math",
        "what": "the study of geometric objects that exhibit self-similarity across scales and whose dimension is typically non-integer. Coined by Benoit Mandelbrot in 1975, fractals capture the irregular, scale-invariant structure of coastlines, mountain ranges, blood vessels, and cosmological matter distributions",
        "how": "fractals are generated by recursive rules (the Cantor set, Koch snowflake, Sierpinski triangle), iterated function systems, or iteration of complex-plane maps (Mandelbrot and Julia sets). The Hausdorff or box-counting dimension quantifies how detail scales: doubling the magnification of the Koch curve reveals about 4 times more detail, giving dimension log(4)/log(3) approximately 1.26",
        "why": "fractal models match natural objects far better than smooth Euclidean shapes. Coastlines, river networks, lung bronchial trees, neuron arborizations, and turbulence all show fractal scaling. Computer graphics generates realistic terrain, clouds, and plants procedurally with fractals. Compression algorithms exploit self-similarity in image data",
        "vs": "fractals differ from classical geometric shapes (circles, polygons) by having infinite detail at every scale and typically non-integer dimension. They differ from random shapes by having statistical or exact self-similarity rather than arbitrary irregularity. Compared to chaos theory, fractals are the geometric counterpart to chaotic dynamics",
        "ex": "the Mandelbrot set, defined as complex numbers c for which iterating z -> z^2 + c starting at z=0 stays bounded, has an infinitely detailed boundary with structures resembling smaller copies of itself at every magnification. Zooming into any part reveals new spirals, baby Mandelbrots, and never-before-seen patterns, all generated by the same simple iteration",
        "mis": "people think fractals must be exactly self-similar, but most natural fractals are only statistically self-similar: a magnified piece looks like the whole in distribution, not pixel-for-pixel. Another myth is that fractals are mere curiosities; they are essential to modeling natural phenomena and underlie practical algorithms in graphics and signal processing",
    }

    T["partial derivatives"] = {
        "_cat": "math",
        "what": "the derivative of a multivariable function with respect to one variable while holding the others constant. For f(x, y), the partial derivative with respect to x measures how f changes as x varies with y fixed, written df/dx (or pronounced 'partial f partial x')",
        "how": "compute partial derivatives by treating other variables as constants and applying the usual single-variable rules (power, product, chain). Higher-order partials chain by repeated differentiation. Mixed partials commute under modest smoothness conditions (Clairaut's theorem). The gradient assembles all first-order partials into a vector that points in the direction of steepest ascent",
        "why": "partial derivatives are the foundation of multivariable calculus, optimization, and physics. Gradient descent in machine learning uses them to find loss minima. Maxwell's equations, the Navier-Stokes equations, and the heat equation are partial differential equations. Sensitivity analysis in economics asks how output changes as one input varies",
        "vs": "partial derivatives differ from total derivatives, which account for how all variables change along a path. They differ from directional derivatives, which measure rate of change along an arbitrary direction, not just along a coordinate axis. The gradient is the natural object built from partials and dotted with a direction gives the directional derivative",
        "ex": "for the temperature distribution T(x, y, z, t) in a room, dT/dx tells you how temperature changes as you walk east at fixed height, depth, and time. Optimization of f(x, y) at a critical point sets both df/dx and df/dy to zero, generalizing the single-variable condition that the derivative vanishes",
        "mis": "people think partial derivatives compose like ordinary derivatives, but the chain rule for multivariable functions has multiple terms: df/dt = df/dx * dx/dt + df/dy * dy/dt when x and y both depend on t. Another myth is that partial and total derivatives are interchangeable; they coincide only when other variables genuinely stay fixed",
    }

    T["the Laplace transform"] = {
        "_cat": "math",
        "what": "an integral transform that converts a function f(t) of time into a function F(s) of complex frequency, defined by integrating f(t) * exp(-st) over t from 0 to infinity. It turns differentiation in t into multiplication by s, converting differential equations into algebraic ones",
        "how": "compute F(s) directly from the integral or use a table of standard transforms (constants, exponentials, sines, polynomials) combined with linearity, shifting, and convolution rules. Solve a differential equation by transforming both sides, doing algebra in the s domain, then inverting via partial fractions or contour integration to recover f(t)",
        "why": "the Laplace transform is the workhorse of control theory, electrical circuit analysis, mechanical vibration analysis, and signal processing. Engineers analyze stability and transient response by examining poles and zeros of transfer functions in the s plane. Without it, analyzing complex linear systems with initial conditions would require painful direct integration",
        "vs": "the Laplace transform differs from the Fourier transform by integrating only over positive time (causal signals) and using a complex variable s = sigma + i*omega rather than purely imaginary. Fourier captures steady-state frequency content; Laplace handles transients and initial conditions. The Z-transform is the discrete-time analog used in digital signal processing",
        "ex": "an RLC circuit's voltage equation is a second-order ODE with initial conditions. Taking the Laplace transform yields a polynomial equation in s for the transformed voltage. Solving algebraically and inverting gives the time-domain response, with poles in the s plane revealing damping and oscillation frequency directly from their real and imaginary parts",
        "mis": "people think the Laplace transform always gives the easiest path; for some problems, direct numerical integration or eigenfunction expansion is simpler. Another myth is that it works only for linear systems; it does, and that is its strength, but nonlinear problems need other tools like perturbation methods or numerical simulation",
    }

    T["confidence intervals"] = {
        "_cat": "math",
        "what": "a range of plausible values for an unknown population parameter computed from sample data, accompanied by a confidence level (commonly 95%) that quantifies the procedure's long-run reliability: 95% of intervals constructed this way from independent samples will contain the true parameter",
        "how": "for a sample mean from a normal population with known variance, the 95% interval is the sample mean plus or minus 1.96 standard errors. For unknown variance you use the t-distribution; for proportions, the Wilson or Wald interval. Bootstrap methods generate intervals by resampling and computing percentiles, useful when distributional assumptions are doubtful",
        "why": "confidence intervals communicate parameter uncertainty far better than point estimates. They are central to clinical trials (effect sizes with bounds), polling (margin of error), economics (forecasted GDP ranges), and quality control (process capability). A wide interval signals more data is needed; a narrow one supports decisions",
        "vs": "confidence intervals differ from prediction intervals, which cover individual future observations rather than parameters and are typically wider. They differ from credible intervals in Bayesian statistics, which directly express posterior probability of the parameter lying in the range, while confidence intervals make a frequentist coverage claim about the procedure",
        "ex": "a clinical trial reports treatment reduces blood pressure by 5 mmHg with 95% CI of [2, 8]. Since zero is not in the interval, the effect is statistically significant at alpha 0.05. A competing trial reports 10 mmHg with CI [-2, 22]; the wide interval and inclusion of zero indicate insufficient evidence despite the larger point estimate",
        "mis": "people interpret a 95% CI as a 95% probability that the true parameter lies in the specific interval; under frequentist inference, the parameter is fixed and the interval is random, so once computed the probability is either 0 or 1. The 95% applies to the procedure across many hypothetical samples. Another myth is that nonoverlapping CIs prove a difference; they are conservative, and partial overlap can still permit a significant difference",
    }

    T["the Monty Hall problem"] = {
        "_cat": "math",
        "what": "a probability puzzle based on the game show Let's Make a Deal. A contestant picks one of three doors hiding a prize behind one and goats behind the others. The host (knowing the contents) opens a different door revealing a goat and offers a switch. Should the contestant switch?",
        "how": "the answer is yes: switching wins with probability 2/3, staying wins with 1/3. Initial pick has 1/3 chance of being correct, leaving 2/3 chance the prize is behind one of the other two. The host's reveal does not change the original probability, but concentrates the remaining 2/3 onto the single unopened other door, since the host always reveals a goat",
        "why": "the puzzle is a textbook demonstration of how conditional probability differs from intuitive reasoning. It exposes the importance of carefully modeling what the data-generating process knows and chooses, not just what events occurred. The same logic appears in medical testing, search-and-rescue, and Bayesian updating with informed observers",
        "vs": "the Monty Hall problem differs from the superficially similar three-prisoners problem only in surface details, both turning on the same conditional logic. It differs from the boy-girl paradox in that the host's behavior provides information (he never reveals the prize), while sibling problems hinge on how you sample families",
        "ex": "simulate it: pick door 1, prize randomly behind any door. If behind 1, host opens 2 or 3, switching loses. If behind 2, host opens 3, switching wins. If behind 3, host opens 2, switching wins. Two of three uniformly random scenarios reward switching. Run a million trials and the empirical win rate for switching converges to 2/3",
        "mis": "people insist the two remaining doors are 50-50 because there are two doors and one has the prize. This ignores that the host's choice is constrained by the contestant's pick and the prize's location. Another myth is that Monty Hall depends on the host being malicious; it requires only that the host knows the contents and always reveals a goat",
    }

    T["graph theory basics"] = {
        "_cat": "math",
        "what": "the mathematical study of graphs, structures consisting of vertices (nodes) connected by edges. Graphs may be directed or undirected, weighted or unweighted, and they model networks of all kinds: social ties, road maps, electrical circuits, web pages, and molecular bonds",
        "how": "key concepts include degree (edges per vertex), paths and cycles, connectivity, trees (acyclic connected graphs), bipartite structure, planarity, and coloring. Algorithms compute shortest paths (Dijkstra, Bellman-Ford), spanning trees (Prim, Kruskal), maximum flow (Ford-Fulkerson), and component decomposition (Tarjan, Kosaraju) in polynomial time",
        "why": "graphs are the lingua franca of network problems. Internet routing solves shortest-path problems on autonomous-system graphs; social networks analyze centrality and community structure; chemists encode molecules as labeled graphs; dependency resolvers in package managers do topological sort. Without graph theory, network science would not exist",
        "vs": "graphs differ from trees by allowing cycles and multiple paths between nodes; trees are a special case. They differ from hypergraphs, where edges can connect more than two vertices. Compared to matrices, graphs offer combinatorial structure that pure linear algebra obscures, though every graph has equivalent matrix representations (adjacency, incidence, Laplacian)",
        "ex": "the seven bridges of Konigsberg, posed as a walking puzzle and solved by Euler in 1736, asked whether one could cross every bridge exactly once. Euler showed it impossible by translating to a graph and proving such a circuit requires every vertex to have even degree, a result that founded both graph theory and topology",
        "mis": "people think graph theory is mostly visual, but most useful graphs (web graph with billions of nodes, social networks, molecular graphs) are processed as data structures, not pictures. Another myth is that graph problems are uniformly easy; many (graph coloring, traveling salesman, subgraph isomorphism) are NP-hard and must be approximated in practice",
    }

    T["combinatorics basics"] = {
        "_cat": "math",
        "what": "the mathematics of counting, arrangement, and selection of discrete structures. It includes permutations (ordered arrangements), combinations (unordered selections), partitions, generating functions, and inclusion-exclusion, with applications across probability, algorithm analysis, and discrete optimization",
        "how": "fundamental tools: the multiplication principle (k independent choices yield product of options), the addition principle (mutually exclusive cases sum), permutations P(n, k) = n!/(n-k)!, combinations C(n, k) = n!/(k!(n-k)!), and the binomial theorem for expanding (a + b)^n. Generating functions encode sequences as power series whose algebra mirrors combinatorial operations",
        "why": "combinatorics underlies probability (counting outcomes), cryptography (key spaces, password complexity), algorithm analysis (running times of search and sort), coding theory (error-correcting codes), and statistical mechanics (counting microstates). Every discrete probability calculation is fundamentally a combinatorial argument",
        "vs": "combinatorics differs from continuous mathematics by working with discrete, often finite structures. Within combinatorics, enumerative combinatorics counts; extremal combinatorics finds maximum or minimum sizes under constraints; algebraic combinatorics uses algebra to count; probabilistic combinatorics applies probability to existence proofs (Erdos's probabilistic method)",
        "ex": "the number of distinct seven-card poker hands from a 52-card deck is C(52, 7) = 133,784,560. The number of orderings of letters in 'MISSISSIPPI' is 11! / (4! * 4! * 2! * 1!) = 34,650 because of repeated letters. Both follow directly from basic permutation and combination formulas applied carefully",
        "mis": "people confuse permutations and combinations: order matters for permutations, not for combinations. Another myth is that the binomial coefficient is always small for moderate n; C(100, 50) is a 30-digit number, which is why estimates often use Stirling's approximation. A third confusion is that inclusion-exclusion applies only to two sets; it generalizes to any finite collection",
    }

    T["the pigeonhole principle"] = {
        "_cat": "math",
        "what": "the elementary observation that if n items are placed into m containers and n > m, at least one container holds more than one item. The general form: placing n items into m bins forces some bin to contain at least ceiling(n/m) items. Trivial-sounding but unexpectedly powerful",
        "how": "apply by choosing items, choosing bins (the hard creative step), and counting. Many proofs proceed by contradiction: assume no bin has the required number, then count an upper bound that violates the total. Generalized pigeonhole and probabilistic refinements (Erdos-Ko-Rado, Ramsey theory) extend the principle into deep combinatorics",
        "why": "the principle yields surprisingly strong existence results without construction: among any 13 people, two share a birth month; in any 51 numbers from 1 to 100, two are coprime; in a graph of n>=2 vertices, two have the same degree. Algorithm correctness proofs, hash-collision arguments, and number-theoretic existence theorems often hinge on pigeonhole",
        "vs": "the pigeonhole principle differs from probabilistic arguments by being deterministic and exact, not probabilistic. It differs from Ramsey theory, which uses pigeonhole repeatedly to prove the existence of large structured substructures. Compared to direct construction, pigeonhole is non-constructive: it shows something exists without exhibiting it",
        "ex": "in any group of 367 people, at least two share a birthday because there are only 366 possible birthdays. A subtler example: in any sequence of 11 distinct integers from 1 to 100, some two have a difference divisible by 10, since each integer falls into one of ten residue classes mod 10 and 11 items into 10 classes forces a repeat",
        "mis": "people see pigeonhole as trivial and miss its power; many Olympiad problems and research-level results use it as a key step. Another myth is that pigeonhole gives sharp bounds; often you must construct the bins cleverly, since the obvious binning yields weaker results than an inspired one",
    }

    T["the prisoner's dilemma"] = {
        "_cat": "math",
        "what": "a classic two-player game in game theory illustrating how rational individual decisions can produce collectively worse outcomes. Each prisoner privately chooses to cooperate or defect; mutual cooperation gives moderate rewards, mutual defection gives punishments, but unilateral defection gives the highest payoff while the cooperator gets the lowest",
        "how": "with payoffs structured so defecting always beats cooperating regardless of the other's choice, defection is the dominant strategy and the unique Nash equilibrium of the one-shot game. Yet both players defecting yields a worse outcome than both cooperating. In iterated versions, strategies like tit-for-tat (cooperate first, then mirror) sustain cooperation through reciprocity",
        "why": "the dilemma models real conflicts where individual incentives diverge from collective welfare: arms races, climate negotiations, antibiotic overprescription, oligopoly pricing, and trust on the internet. It motivates institutions (laws, treaties, reputation systems) that change payoffs to make cooperation individually rational",
        "vs": "the prisoner's dilemma differs from coordination games where any single equilibrium suits all (driving on the same side of the road) and from zero-sum games where one wins exactly what the other loses. It differs from the stag hunt, where cooperation is a Nash equilibrium but risk-averse players still defect to safer alternatives",
        "ex": "Cold War nuclear arms reduction had prisoner's dilemma structure: each superpower wanted the other to disarm while staying armed itself. Verified bilateral treaties (SALT, START) changed the game by making mutual cooperation enforceable through inspection regimes. In commerce, two duopolists each face the temptation to undercut on price, leading to Bertrand-style price wars unless tacit collusion holds",
        "mis": "people treat the dilemma as proof that cooperation never emerges; Axelrod's tournaments showed iterated tit-for-tat cooperates remarkably well in repeated play. Another myth is that the dilemma proves selfishness wins; it shows that rational selfishness can fail collectively, which is precisely why we build cooperative institutions",
    }

    T["the unit circle"] = {
        "_cat": "math",
        "what": "the circle of radius 1 centered at the origin in the Cartesian plane. Each point on the circle has coordinates (cos theta, sin theta) where theta is the angle measured counterclockwise from the positive x-axis. The unit circle is the geometric foundation of trigonometry",
        "how": "the unit circle defines sine and cosine for any real angle. Special angles (0, pi/6, pi/4, pi/3, pi/2, ...) correspond to coordinates with exact algebraic values. Tangent is sin/cos, the y-coordinate divided by the x-coordinate. The Pythagorean identity sin^2 + cos^2 = 1 follows immediately from the equation x^2 + y^2 = 1 of the unit circle itself",
        "why": "the unit circle generalizes trigonometry from right triangles (limited to acute angles) to all real and complex numbers, enabling Fourier analysis, complex exponentials via Euler's formula e^(i*theta) = cos theta + i sin theta, and any periodic phenomenon. Engineering analyses of waves, oscillations, signals, and rotations all start at the unit circle",
        "vs": "the unit circle differs from a generic circle by being centered at the origin with radius 1, eliminating scaling and translation factors. It differs from the right-triangle definitions of trigonometric functions by working for all angles including negative and obtuse. Compared to the unit interval on the real line, it captures cyclic rather than linear structure",
        "ex": "to find sin(7*pi/6), locate the angle 7*pi/6 (210 degrees, third quadrant) on the unit circle. Reference angle is pi/6 (30 degrees) below the negative x-axis. So sin(7*pi/6) = -sin(pi/6) = -1/2 and cos(7*pi/6) = -sqrt(3)/2. The unit-circle picture turns this into a quick mental computation, no calculator needed",
        "mis": "students think trigonometry is bounded to acute angles; the unit circle extends it to all angles and reveals the periodicity that triangles obscure. Another myth is that radians are an exotic unit; they are the natural choice because arc length on the unit circle equals the angle in radians, making derivatives of sin and cos clean",
    }

    T["complex numbers"] = {
        "_cat": "math",
        "what": "numbers of the form a + bi where a and b are real and i is the imaginary unit satisfying i^2 = -1. Together they form the complex plane, with addition by component and multiplication that combines magnitudes and adds angles, making them the algebraic completion of the reals",
        "how": "addition: (a + bi) + (c + di) = (a+c) + (b+d)i. Multiplication: (a + bi)(c + di) = (ac - bd) + (ad + bc)i. Polar form r*e^(i*theta) with r = sqrt(a^2 + b^2) and theta = atan2(b, a) makes multiplication trivial: just multiply magnitudes and add angles. Euler's formula e^(i*theta) = cos theta + i sin theta unifies trigonometry and exponentials",
        "why": "complex numbers solve every polynomial equation (the fundamental theorem of algebra), describe AC circuits with phase, encode rotations cleanly, drive Fourier analysis, and underlie quantum mechanics where wavefunctions are intrinsically complex-valued. Signal processing, control theory, and electromagnetism would be unworkable without them",
        "vs": "complex numbers differ from real numbers by being two-dimensional and algebraically closed (every polynomial has a complex root). They differ from vectors by having a multiplication that combines magnitudes and angles, not just componentwise. Compared to quaternions, complex numbers are the 2D rotation algebra; quaternions extend to 3D",
        "ex": "an alternating-current circuit with sinusoidal voltage V*sin(omega*t) and a coil's current lagging by phase phi can be analyzed with complex impedance Z = R + i*omega*L. Ohm's law extends to V = I*Z, and computing power, resonance, and frequency response reduces to algebra in the complex plane rather than messy real-number trigonometric manipulations",
        "mis": "people think 'imaginary' means fictitious or unphysical, a historical accident of naming. Complex numbers are as real as negatives or fractions and indispensable in physics. Another myth is that they are only useful as a calculational trick; in quantum mechanics they are fundamental, not eliminable",
    }

    T["mathematical induction"] = {
        "_cat": "math",
        "what": "a proof technique establishing that a statement P(n) holds for all natural numbers n by proving two steps: a base case (P(1) is true) and an inductive step (if P(k) is true, then P(k+1) is true). Together these imply P(n) for every n via the well-ordering of the natural numbers",
        "how": "structure: state P(n), verify P(1), assume P(k) holds (the inductive hypothesis), prove P(k+1) using that hypothesis. Variants include strong induction (assume P holds for all values up to k) and structural induction over recursive data types like trees and lists. Properly applied, induction transforms an infinite claim into two finite arguments",
        "why": "induction is the workhorse of discrete mathematics, computer science, and number theory. Algorithm correctness proofs, recurrence solutions, identity-checking, and combinatorial counting all use induction. Formal verification systems and proof assistants like Coq and Lean rely on it as a core inference rule",
        "vs": "induction differs from deduction by leveraging the structure of the natural numbers (or other well-ordered set) to extend a finite argument to infinity. It differs from empirical induction in science by being a strict logical rule, not pattern-matching from examples. Compared to direct proof, induction is essential when statements depend on a parameter ranging over an infinite set",
        "ex": "prove 1 + 2 + ... + n = n(n+1)/2. Base: n=1 gives 1 = 1(2)/2 = 1, true. Step: assume true at k, so 1 + ... + k = k(k+1)/2. Then 1 + ... + k + (k+1) = k(k+1)/2 + (k+1) = (k+1)(k+2)/2, which is the formula at k+1. Therefore by induction, true for all n",
        "mis": "people forget the base case, assuming the induction step alone proves the result; without anchoring at n=1, you have nothing. Another myth is that induction requires the statement to be true; many beginners assume P(k) without proof, but the inductive hypothesis is a conditional, valid only as a stepping stone to P(k+1)",
    }
