#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank part 3 of 4: more technology + history (fresh for batch F)."""


def register(T):
    # ===== TECHNOLOGY (continued) =====

    T["how a kernel scheduler picks the next process"] = {
        "_cat": "technology",
        "what": "the kernel component that decides which runnable thread runs on each CPU at each moment, balancing fairness, throughput, latency, and priority across competing workloads",
        "how": "Linux's Completely Fair Scheduler (CFS) tracks each task's virtual runtime, weighted by nice value, in a red-black tree keyed by vruntime. The leftmost (least-run) task gets the CPU. On preemption, vruntime is updated, the task is reinserted, and the next leftmost task runs. Real-time scheduling classes (SCHED_FIFO, SCHED_RR) override CFS for tasks with strict latency requirements",
        "why": "scheduling determines interactive responsiveness, server tail latency, and energy efficiency on every modern device. A bad scheduler can leave a system feeling sluggish even when CPU is idle on average; a good one keeps interactive apps snappy under load and lets batch jobs use slack time efficiently",
        "vs": "the kernel scheduler differs from a userspace task scheduler (like the one in a thread pool or coroutine runtime) in that it preempts arbitrary code on a hardware tick, not just at cooperative yield points. It differs from a job scheduler (Slurm, Kubernetes), which assigns jobs to whole machines",
        "ex": "on a laptop, opening a browser tab while compiling code keeps the UI responsive because CFS gives the briefly-active browser threads small but rapid CPU slices, whereas the long-running compiler is content with bulk time. Without fair scheduling, either the UI would freeze or compilation would stall",
        "mis": "people think 'higher priority' means more CPU time always. Nice values and weights mean a high-priority task gets more time only when it competes for CPU; if it sleeps, others run. Another myth is that more CPUs always speeds up everything; tasks that synchronize heavily can slow down on more cores due to contention",
    }

    T["public-key authentication for SSH"] = {
        "_cat": "technology",
        "what": "an SSH login mechanism that proves a user's identity by demonstrating possession of a private key whose corresponding public key is listed in the server's authorized_keys file, replacing or supplementing password authentication",
        "how": "the user generates a keypair (commonly Ed25519 or RSA-3072+). The public key is appended to ~/.ssh/authorized_keys on the server. On connection, the server picks a challenge, the client signs it with the private key, and the server verifies the signature using the stored public key. Optionally an SSH agent caches the unlocked private key for the session",
        "why": "key-based auth resists password guessing, phishing for typed credentials, and credential reuse. It is the standard for server administration, CI/CD deployment, and Git hosting (GitHub, GitLab). Disabling password login closes the most common brute-force attack surface entirely",
        "vs": "public-key auth differs from password auth (vulnerable to brute force and reuse), from Kerberos (which uses tickets from a central KDC), from OAuth/SAML (web-flow protocols not designed for shells), and from certificate-based SSH (which uses signed certificates with expiry rather than raw public keys)",
        "ex": "a developer pushing to GitHub generates an Ed25519 keypair with ssh-keygen, uploads the public key in the GitHub UI, and from then on git push uses SSH key auth automatically. Compromising the laptop is now the only way to impersonate the developer, vs guessing a reused password",
        "mis": "people think the server learns the private key. It never sees it; only signatures cross the wire. Another myth is that adding a passphrase to the private key prevents server-side compromise; the passphrase only protects the key file at rest on the client",
    }

    T["how a hash table handles collisions"] = {
        "_cat": "technology",
        "what": "the strategy a hash-table implementation uses to store multiple keys whose hash values map to the same bucket, the central design choice that determines its performance under load",
        "how": "two main families: separate chaining stores collided entries in a linked list or small structure attached to each bucket, with lookup walking the chain. Open addressing stores all entries directly in the table and probes alternative slots on collision, using linear probing, quadratic probing, or double hashing. Open addressing tends to be cache-friendlier; chaining handles high load factors more gracefully",
        "why": "collision handling sets the practical performance of every hash-based data structure, which means dictionaries, sets, caches, and database indexes. The wrong choice or a weak hash function can degrade O(1) average-case lookups to O(n) worst case, occasionally making services unavailable",
        "vs": "hash-table collision handling differs from balanced-BST organization (sorted, O(log n) ops, no hashing needed) and from cuckoo hashing (a special open-addressing scheme that guarantees O(1) worst-case lookups by displacing colliding items into one of two possible slots)",
        "ex": "Python's built-in dict uses open addressing with perturbation-based probing. Java's HashMap uses chaining with linked lists, switching to a balanced tree per bucket once a chain exceeds a threshold to defend against pathological inputs",
        "mis": "people assume any hash function avoids collisions. By the pigeonhole principle, collisions are inevitable once you have more keys than buckets, and even before that, the birthday paradox makes them likely. Another myth is that collision handling is internal magic; choosing chaining vs open addressing affects API behavior under iteration and resize",
    }

    T["virtual memory paging"] = {
        "_cat": "technology",
        "what": "the OS mechanism that gives each process its own virtual address space, mapped to physical memory in fixed-size pages (commonly 4 KiB), with translation handled transparently by the CPU's MMU using page tables",
        "how": "when a process accesses a virtual address, the CPU's MMU walks the page table (often multi-level, like x86-64's four levels) to find the physical frame, caching translations in the TLB. Pages can be marked present, dirty, accessible, executable, or absent. Absent pages trigger page faults, which the OS resolves by loading from disk (swap or memory-mapped file) or zeroing fresh pages",
        "why": "paging enables process isolation, demand loading, copy-on-write fork, memory-mapped files, swap to disk, security via NX bits and ASLR, and the illusion of more memory than physically present. Modern OSes are unimaginable without it",
        "vs": "paging differs from segmentation (variable-sized regions, largely deprecated in current 64-bit OSes) and from base-and-limit register schemes (no virtualization, just bounds checking). It differs from virtual machines, which add a second layer of address translation to virtualize the entire OS",
        "ex": "fork() in Linux uses copy-on-write paging: the child shares all parent pages marked read-only, with copies happening lazily on the first write. This makes fork+exec cheap even for processes using gigabytes of memory",
        "mis": "people think virtual memory means swap to disk. Swap is one feature on top of paging, not the whole story; even systems without swap rely on paging for isolation, demand loading of executables, and shared libraries. Another myth is that more swap always helps; aggressive swapping can collapse system performance if working sets exceed RAM",
    }

    # ===== HISTORY =====

    T["the Bronze Age collapse"] = {
        "_cat": "history",
        "what": "the rapid disintegration of nearly every Late Bronze Age civilization in the eastern Mediterranean and Near East between roughly 1200 and 1150 BCE, including the Mycenaeans, Hittites, and Egyptian New Kingdom's expansion, ushering in centuries of relative obscurity (the Greek 'Dark Age')",
        "how": "no single cause is agreed. A combination of severe drought (documented in tree rings and ice cores), earthquakes, internal social unrest, and raids by the loosely defined 'Sea Peoples' overwhelmed interconnected palace economies. Long-distance trade in tin and copper (essential for bronze) collapsed, undermining elite power and centralized record keeping. Cities were sacked or abandoned, literacy was lost in some regions for centuries",
        "why": "the collapse marks one of the few near-total resets of complex civilization in recorded history. It cleared the political stage for new powers (Phoenicians, Greeks, Israelites) and for the Iron Age, since iron's wider availability mattered most after the bronze trade network broke. It is a frequent case study in systems-collapse models",
        "vs": "the Bronze Age collapse differs from the fall of Rome (slower, regional, with continuity east) and from the 17th-century general crisis (a recovery, not a collapse). It is broader than a single conquest like the fall of Babylon and represents a synchronous failure of multiple polities sharing trade and ecological dependencies",
        "ex": "the Hittite capital Hattusa was burned and abandoned around 1200 BCE; the Mycenaean palaces (Pylos, Mycenae, Thebes) were destroyed in roughly the same window; Ugarit, a thriving port city in modern Syria, was destroyed and never reoccupied. Egyptian inscriptions from Ramesses III describe repelling waves of Sea Peoples around 1175 BCE",
        "mis": "people pin the collapse on the Sea Peoples alone. Modern scholarship sees them as one symptom of a larger crisis, not the prime cause. Another myth is that the Dark Age that followed was uniformly bleak; some regions, especially Cyprus and the Levantine coast, recovered relatively quickly with new political forms",
    }

    T["the Mauryan Empire under Ashoka"] = {
        "_cat": "history",
        "what": "the South Asian empire founded by Chandragupta Maurya in 322 BCE and consolidated by his grandson Ashoka the Great (reigned roughly 268-232 BCE), which at its peak covered most of the Indian subcontinent and is famous for Ashoka's adoption of Buddhism after the Kalinga War",
        "how": "Chandragupta and his successor Bindusara built a centralized administration with a capital at Pataliputra, taxes assessed on agricultural output, a network of roads and rest houses, and regional governors. Ashoka inherited the system, conquered Kalinga in a famously bloody campaign around 261 BCE, and then committed to non-violence (ahimsa) and Buddhist principles, codifying his policies in stone edicts across the empire",
        "why": "the Mauryan Empire is the first large-scale political unification of South Asia and a model later empires (Gupta, Mughal) measured themselves against. Ashoka's rock and pillar edicts are the earliest substantial Indian inscriptions and a primary source for state-sponsored Buddhism, which spread along trade routes to Sri Lanka, Central Asia, and beyond",
        "vs": "the Mauryan Empire differs from contemporaneous Hellenistic kingdoms (smaller, Greek-speaking elite over diverse populations) and from later Indian empires (Gupta was more decentralized, Mughal was Persian-influenced and Muslim-led). Ashoka's pacifist turn distinguishes him from most ancient conquerors, who celebrated victories on monuments",
        "ex": "the Sarnath Lion Capital, an Ashokan pillar topped by four lions, is the national emblem of modern India and adorns its currency. The Lions guarded one of the locations where the Buddha first taught, marking Ashoka's royal patronage of Buddhism and the empire's reach",
        "mis": "people treat Ashoka as a pure pacifist after Kalinga. He maintained a standing army, capital punishment in some cases, and central authority; ahimsa shaped policy but did not dismantle the state. Another myth is that the Mauryan Empire converted India to Buddhism; popular religion remained diverse, and Hindu traditions continued to dominate after the empire's fall",
    }

    T["the Tang dynasty's golden age"] = {
        "_cat": "history",
        "what": "the period of Chinese imperial rule from 618 to 907 CE, often considered a high point of Chinese civilization for its territorial reach, cosmopolitan culture, civil-service reforms, and flourishing of poetry, painting, and Buddhism",
        "how": "the Tang inherited the Sui dynasty's Grand Canal and centralized institutions, then expanded examinations as a route into the bureaucracy, reorganized land distribution under the equal-field system, and projected military power into Central Asia, Korea, and Vietnam. Chang'an, the capital, hosted Persian, Arab, Sogdian, Korean, and Japanese diplomats, merchants, and monks",
        "why": "the Tang is the model classical China against which later eras are measured. Its poetry (Li Bai, Du Fu, Wang Wei) is considered the canonical pinnacle of Chinese literature; its trade along the Silk Road sustained Eurasian connectivity; its administrative reforms shaped East Asian governance for a millennium, including in Japan and Korea",
        "vs": "the Tang differs from the preceding Sui (short, aggressive, fell from overreach) and the following Song (more inward, commercially advanced, militarily weaker). It is more cosmopolitan than the later Ming, which restricted foreign trade, and more centralized than the Eastern Han at its decline",
        "ex": "the An Lushan Rebellion (755-763) shattered the Tang's mid-dynasty stability. A frontier general of Sogdian and Turkic descent led a revolt that emptied Chang'an, killed millions, and forced the imperial court to depend on regional military governors, weakening central control for the dynasty's remaining 150 years",
        "mis": "people think Tang China was uniformly Confucian. The Tang court patronized Buddhism heavily; Empress Wu Zetian, the only woman to rule China in her own name, used Buddhist symbolism to legitimize her reign. Another myth is that the Tang fell to barbarian invasion; the actual end came through internal warlordism after 50 years of decay following the rebellion",
    }

    T["the Atlantic slave trade's economic structure"] = {
        "_cat": "history",
        "what": "the trans-Atlantic trafficking and forced labor system that, between the 16th and 19th centuries, transported an estimated 12.5 million enslaved Africans to the Americas, organized around triangular trade routes linking Europe, West Africa, and American plantations",
        "how": "European powers, especially Portugal, Britain, France, the Netherlands, and Spain, traded manufactured goods, firearms, and alcohol to West African coastal kingdoms in exchange for captives. Captives endured the Middle Passage in horrendous conditions, with mortality rates of 10 to 20 percent on average. Survivors were sold for plantation labor producing sugar, tobacco, coffee, indigo, and cotton, which were shipped back to Europe and reinvested",
        "why": "the trade was the foundation of plantation capitalism in the Americas, the financial rise of port cities like Liverpool, Bristol, Bordeaux, and Amsterdam, and the wealth that funded early industrialization. It also entrenched racial slavery, killed millions, and shaped the demographics, languages, and cultures of the entire Atlantic world. Its abolition in the 19th century was one of the largest moral movements in history",
        "vs": "the Atlantic slave trade differs from the older trans-Saharan slave trade (smaller volume, longer duration, predominantly female captives) and from the Indian Ocean slave trade. It differs from indentured servitude in scale, brutality, hereditary status, and explicit racial coding, although the boundaries blurred at times",
        "ex": "Liverpool's 18th-century rise as a global port was tightly bound to the slave trade. By the 1790s, roughly 80 percent of British slaving voyages departed from Liverpool, and the city's banks, insurance, and shipbuilding industries were heavily capitalized by trade profits, which compounded into the Industrial Revolution",
        "mis": "people think Africans were uninvolved in the trade. African coastal polities and merchant networks were active participants, often capturing inland populations to sell. This does not lessen European responsibility for creating sustained, large-scale demand and the racial ideologies that justified it. Another myth is that abolition ended forced labor; sharecropping, debt peonage, and convict leasing replaced it in many regions",
    }

    T["the unification of Italy (Risorgimento)"] = {
        "_cat": "history",
        "what": "the 19th-century political and social movement that unified the patchwork of Italian states (Piedmont-Sardinia, the Papal States, the Two Sicilies, Lombardy-Venetia, and others) into the Kingdom of Italy, achieved primarily between 1859 and 1870",
        "how": "the Kingdom of Sardinia, led by Prime Minister Camillo di Cavour, used diplomacy and war (allying with France against Austria in 1859) to expand. Giuseppe Garibaldi's volunteer Red Shirts conquered the south in 1860 and handed it to King Victor Emmanuel II. Plebiscites ratified annexations. Venice was added in 1866 after war with Austria; Rome was taken in 1870 when France withdrew its protective garrison during the Franco-Prussian War",
        "why": "Italian unification reshaped European politics, ended over 1300 years of fragmented Italian states, removed the Pope's temporal power, and created a new great power that would reshape Mediterranean and African politics. It is also a defining example of 19th-century nationalism, sometimes contrasted with the parallel German unification under Prussia",
        "vs": "the Risorgimento differs from German unification (more militarized, Prussian-led, less ideological) and from later Italian fascism (which used Risorgimento myths but was a 20th-century authoritarian project). It differs from earlier failed liberal revolutions in 1848 by succeeding through realpolitik rather than spontaneous uprising",
        "ex": "Garibaldi's Expedition of the Thousand in 1860 sailed from Genoa with about 1000 volunteers, landed in Sicily, defeated Bourbon forces in a campaign of stunning speed, and crossed to Naples, all within five months. He then voluntarily handed his conquests to Victor Emmanuel, an act of restraint that secured the unified kingdom",
        "mis": "people imagine unification as a popular national awakening. Italian was a literary language spoken by perhaps 10 percent of the peninsula at unification; most subjects spoke regional languages and had little notion of an Italian nation. The famous quote 'we have made Italy, now we must make Italians' (attributed to D'Azeglio) captures the gap. Another myth is that unification solved north-south economic divides; it arguably worsened them",
    }

    T["the Heian period in Japan"] = {
        "_cat": "history",
        "what": "the era of Japanese history from 794 to 1185 CE, named for the capital Heian-kyo (modern Kyoto), characterized by the dominance of the Fujiwara aristocracy, refined court culture, and the production of canonical Japanese literature",
        "how": "after moving the capital from Nara to escape Buddhist political influence, emperors gradually delegated power to the Fujiwara family, who supplied imperial consorts and served as regents. Court culture revolved around aesthetic refinement: poetry, calligraphy, music, and elaborate dress codes. The phonetic kana scripts emerged, allowing women of the court to write in Japanese rather than classical Chinese, producing some of the period's greatest literature",
        "why": "the Heian period defined Japanese aesthetics for the next thousand years (the concept of mono no aware, the wabi-sabi tradition, court gardens, kana literature). Lady Murasaki's Tale of Genji, written around 1010, is often called the world's first psychological novel. The period's idealized court life shaped later Japanese self-image even after the warrior class displaced the aristocracy",
        "vs": "the Heian differs from the earlier Nara period (Chinese-modeled, Buddhist-dominated capital) and from the following Kamakura period (military government under shoguns, samurai dominance). It contrasts with contemporaneous Tang and Song China, on which it drew but from which it diverged into a distinctly Japanese cultural synthesis",
        "ex": "Sei Shonagon's Pillow Book, a collection of observations and lists by an early-11th-century court lady, captures the period's aesthetic sensibility: lists of 'things that quicken the heart' or 'things that cannot be compared' alternate with sharp social observation. It survives as a defining Heian text alongside the Tale of Genji",
        "mis": "people imagine the Heian as a peaceful flowering of culture. The court's elegance rested on rural estates whose taxes increasingly evaded central control, and provincial warrior clans (the Taira and Minamoto) accumulated power that erupted in the Genpei War (1180-1185), ending the period. Another myth is that Heian women had freedom; they were politically constrained but had far more literary visibility than in many parallel cultures",
    }

    T["the partition of Africa at the Berlin Conference"] = {
        "_cat": "history",
        "what": "the 1884-1885 conference in Berlin convened by Otto von Bismarck where European powers and the United States agreed on rules for colonizing and dividing Africa, formalizing the 'Scramble for Africa' that placed roughly 90 percent of the continent under European control by 1914",
        "how": "fourteen powers attended, with no African representation. The General Act established principles: powers claiming territory had to demonstrate effective occupation, free trade and navigation on the Congo and Niger rivers, and notification to other powers of new claims. The Congo Free State was assigned to King Leopold II of Belgium personally. Subsequent treaties drew specific borders, often along straight lines ignoring ethnic, linguistic, or geographic realities",
        "why": "the Berlin Conference accelerated and legitimized colonial conquest, established borders that would persist after independence (and still cause ethnic conflict today), and underwrote decades of extraction, forced labor, and violence, most infamously in the Congo. It marks the high tide of European imperialism and the start of dependencies that shape African economies and politics into the 21st century",
        "vs": "the Berlin Conference differs from earlier informal colonialism (coastal trade posts without territorial claims) and from later 20th-century decolonization frameworks. It differs from settler-colonial projects (like North America or Australia) in scale and intensity of resource extraction, although large settler populations did emerge in southern and east Africa",
        "ex": "the borders drawn for what became the Democratic Republic of the Congo enclosed hundreds of distinct ethnic groups in an area roughly the size of western Europe, ruled by a personal fiefdom of Leopold II until 1908 in which atrocities, killing, and forced rubber harvest led to an estimated population decline of millions. Many such borders survive almost unchanged today",
        "mis": "people think the conference physically drew most African borders. Many borders were drawn later in bilateral treaties; the conference set rules of engagement. Another myth is that European powers brought stability; they imposed extractive regimes whose collapse during decolonization in many places left fragile states with arbitrary borders, a legacy still being negotiated",
    }

    T["the Suez Crisis of 1956"] = {
        "_cat": "history",
        "what": "an international crisis triggered by Egyptian President Gamal Abdel Nasser's nationalization of the Suez Canal Company in July 1956, leading to a coordinated invasion by Britain, France, and Israel in October-November and a humiliating Anglo-French withdrawal under U.S. and Soviet pressure",
        "how": "Britain and France, the canal's principal users and former owners, secretly arranged with Israel that Israel would invade the Sinai, after which Britain and France would 'intervene' to separate the combatants and seize the canal. Operations went forward but the United States, alarmed at the threat to oil markets and Cold War alliances, threatened economic sanctions against Britain. The Soviet Union threatened nuclear retaliation. Britain and France withdrew within weeks, and a UN peacekeeping force took over the canal zone",
        "why": "the crisis marked the definitive end of Britain and France as independent great powers and revealed that postwar military adventures could no longer be conducted without U.S. consent. It elevated Nasser as a leader of pan-Arab nationalism, accelerated decolonization, and demonstrated the United Nations' role as a real (if uneven) constraint on traditional colonialism",
        "vs": "the Suez Crisis differs from later Arab-Israeli wars (1967, 1973) in being primarily about colonial property and Cold War alignment rather than territorial conflict between Israel and Arab states. It differs from earlier 20th-century interventions in being explicitly halted by superpower pressure rather than military exhaustion",
        "ex": "British Prime Minister Anthony Eden, the architect of the operation, resigned in January 1957 citing health; the political damage was decisive. The Eisenhower administration, despite leading NATO with Britain, refused to support sterling under speculative attack until withdrawal began, a bluntly effective use of financial leverage",
        "mis": "people think the U.S. supported its NATO allies in the operation. Eisenhower was furious at being kept in the dark and saw the operation as a relic of imperial behavior that would push Arab states toward the Soviet Union. Another myth is that the canal returned to international control; Egypt has owned and operated it ever since, with revenue funding its national development",
    }
