#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank: current_events + extra topics (fresh for batch G)."""


def register(T):
    # current_events
    T["the rise of electric vehicles in 2024-2026"] = {
        "_cat": "current_events",
        "what": "the ongoing global transition from internal-combustion to battery-electric passenger vehicles, marked by rapid Chinese production growth, US/EU industrial policy support, infrastructure buildout, and market shakeouts as legacy automakers compete with native EV firms",
        "how": "Chinese manufacturers (BYD, Geely, SAIC, Li Auto, Nio) achieved scale in lithium-ion battery production and vertically integrated EV supply chains, undercutting global competitors on price. The EU and US imposed tariffs on Chinese EVs and subsidized domestic production via the Inflation Reduction Act and EU Green Deal Industrial Plan. Charging networks expanded; battery costs continued to fall; range and charging speeds improved. Global EV market share rose from under 5 percent of new sales in 2020 to roughly 20 percent in 2025, with China at over 40 percent and Europe near 25 percent",
        "why": "passenger transport accounts for about 8 percent of global CO2 emissions; widespread EV adoption is essential for climate goals. The transition reshapes auto industry employment (fewer powertrain components, different skill mix), oil demand projections, electricity generation needs, and industrial competition between China, Europe, and the US. Mineral supply chains for lithium, nickel, cobalt, and rare earths have become geopolitical priorities",
        "vs": "the current EV transition differs from earlier alternative-fuel waves (1990s electric, hydrogen, hybrid) in scaling commercially rather than stalling, and in being driven by both regulation and consumer choice rather than by oil-price spikes. It differs from the smartphone transition in requiring concurrent infrastructure (charging, grid upgrades) rather than slipping into existing networks",
        "ex": "BYD overtook Tesla in 2023 as the world's largest EV maker by units, selling over 3 million electrified vehicles annually by 2024. Its Seagull model retails in China for around 10000 dollars, demonstrating cost levels Western manufacturers struggle to match without heavy subsidies",
        "mis": "people think EVs are emissions-free. They produce no tailpipe emissions, but lifecycle emissions depend on the electricity mix and battery production; on most modern grids, EVs still produce roughly half the lifecycle emissions of comparable ICE vehicles, with the gap widening as grids decarbonize. Another myth is that EV batteries last only a few years; modern packs typically retain 80 percent capacity beyond 200000 km",
    }

    T["the post-2023 GLP-1 weight-loss medication wave"] = {
        "_cat": "current_events",
        "what": "the surge in prescriptions and societal attention around glucagon-like peptide-1 receptor agonist medications (semaglutide as Wegovy and Ozempic, tirzepatide as Mounjaro and Zepbound) for both type 2 diabetes and obesity, after randomized trials showed average weight reductions of 15 to 22 percent",
        "how": "GLP-1 agonists mimic an endogenous hormone that signals satiety and slows gastric emptying, reducing food intake and improving glycemic control. Once-weekly injectable formulations made adherence practical for chronic use. The 2021 Wegovy and 2023 Zepbound approvals for chronic weight management triggered massive demand that outstripped supply, drove Novo Nordisk and Eli Lilly to aggressive capacity expansion, and pushed insurers, employers, and government health systems to negotiate access",
        "why": "obesity affects over 40 percent of US adults and is a key driver of diabetes, cardiovascular disease, sleep apnea, and joint disease. Effective pharmacotherapy of this magnitude could shift trajectories of multiple chronic conditions, reduce demand for joint replacement and bariatric surgery, and reshape food consumption patterns. It also strains healthcare budgets at current pricing (over 1000 dollars per month before insurance and rebates), prompting debates about value, access, and long-term use",
        "vs": "GLP-1 drugs differ from earlier weight-loss medications (sibutramine, orlistat, phentermine-topiramate) in efficacy, magnitude of weight loss, and side-effect profile. They differ from bariatric surgery in being noninvasive but requiring continued use to maintain effect. They differ from lifestyle interventions in delivering reliable, large-magnitude effects that sustained behavior change rarely matches at population scale",
        "ex": "the SELECT trial, published in 2023, showed that semaglutide 2.4 mg reduced major adverse cardiovascular events by 20 percent in adults with overweight or obesity and pre-existing cardiovascular disease, independent of diabetes status. This expanded the medical case for GLP-1 use beyond glycemic and weight outcomes alone",
        "mis": "people think GLP-1 drugs are quick weight-loss tools. They are chronic medications: stopping leads to substantial weight regain over months. Another myth is that they are unsafe long-term; multi-year safety data from diabetes use are reassuring, but very-long-term effects on muscle, bone, and a treatment-naive obese population are still being characterized",
    }

    T["the housing affordability crisis in major cities"] = {
        "_cat": "current_events",
        "what": "the persistent shortage of affordable housing in major global cities, where home prices and rents have outpaced wages over decades, driving displacement, lengthening commutes, suppressing fertility, and reshaping politics in places from San Francisco and Toronto to London, Sydney, and Berlin",
        "how": "constrained supply (zoning restrictions, lengthy permitting, NIMBY opposition, infrastructure shortfalls) collides with rising demand (productive metropolitan job markets, immigration, household downsizing). Investor purchases, short-term rentals, and second homes contribute at the margin in some markets. Construction productivity has stagnated for decades. Interest rate rises since 2022 froze owners in place but kept new buyers out. Policy responses range from upzoning (Auckland, Minneapolis) to vacancy taxes, rent stabilization, and large-scale public housing construction (Vienna's enduring model)",
        "why": "housing is the largest line in most household budgets; affordability shapes labor mobility, urban productivity, family formation, retirement security, and political stability. The crisis correlates with declining trust in institutions, rising support for populist movements, and fertility declines that reshape demographics. Cities that resolve it will gain competitive advantage; those that do not will hollow out",
        "vs": "the current crisis differs from earlier housing manias (US 2006, Japan 1989, Spain 2007) in being driven primarily by chronic supply constraints rather than speculative bubbles, and in not resolving via crash. It differs across regions: anglophone cities lean on mortgage debt and homeownership, while continental Europe leans more on long-term rental markets",
        "ex": "Auckland upzoned about three quarters of its residential land in 2016, allowing duplexes and triplexes in former single-family zones. Within five years, building permits doubled and rents grew slower than the rest of New Zealand, providing one of the cleanest natural experiments showing supply increases can ease housing costs",
        "mis": "people think foreign buyers are the main cause. Even in markets with significant foreign demand (Vancouver, Sydney), domestic constraints on supply explain most of the price level. Another myth is that rent control fixes affordability; targeted protections help current tenants, but blanket controls often reduce new construction and degrade existing stock",
    }

    T["the geopolitics of critical minerals"] = {
        "_cat": "current_events",
        "what": "the strategic competition over lithium, cobalt, nickel, rare earth elements, copper, graphite, and other inputs for batteries, wind turbines, EVs, and electronics, where supply concentration and processing dominance (much of it Chinese) have made minerals central to industrial and security policy",
        "how": "China dominates processing for most rare earths, graphite, and large shares of lithium and cobalt refining, even when mining occurs elsewhere. The Democratic Republic of Congo produces about 70 percent of mined cobalt; Indonesia leads in nickel; Chile and Australia dominate lithium mining. Western governments are funding alternative supplies (US Inflation Reduction Act, EU Critical Raw Materials Act, Japan-Australia partnerships), while accepting that diversification will take a decade. Recycling, substitution (LFP batteries reduce cobalt), and exploration are all parts of the response",
        "why": "the energy transition and digital economy depend on these inputs; supply disruption can stall EV and renewable rollouts, military procurement, and electronics manufacturing. Strategic stockpiles, ESG concerns about mining conditions, and tensions over China's processing dominance shape industrial policy globally. The 2010 Senkaku-related Chinese rare earth export curbs to Japan demonstrated the leverage of supply concentration",
        "vs": "critical minerals differ from oil in being capital-intensive to develop and in needing complex processing, in having more substitutes (in many but not all applications), and in being concentrated by processing rather than by reserves. They differ from semiconductors in scale (mineral plants are smaller capex than fabs) and in environmental impact",
        "ex": "the EU's 2024 Critical Raw Materials Act sets targets that no single non-EU country supplies more than 65 percent of any strategic raw material, that 10 percent of consumption come from EU mining, 40 percent from EU processing, and 25 percent from EU recycling by 2030. Meeting these targets requires permitting reform, investment, and political will that the policy now tries to mobilize",
        "mis": "people think rare earths are actually rare. Most are reasonably abundant in Earth's crust; the difficulty is finding economically concentrated deposits and processing them cleanly. Another myth is that recycling alone can substitute for mining at scale; closed-loop recycling will grow but will not meet rapidly expanding demand for at least the next decade",
    }

    T["the global semiconductor supply race"] = {
        "_cat": "current_events",
        "what": "the geopolitical and industrial competition to secure leading-edge chip design and manufacturing capability, which has driven the US CHIPS and Science Act, the EU Chips Act, Japan's Rapidus venture, and tightened export controls on advanced lithography, especially toward China",
        "how": "TSMC in Taiwan dominates leading-edge logic manufacturing (3 nm and below), with Samsung and Intel chasing. ASML in the Netherlands is the sole supplier of EUV lithography. The US restricts ASML, Nvidia, and others from selling the most advanced equipment and accelerators to China, while subsidizing onshore fabs (TSMC Arizona, Intel Ohio, Samsung Texas). China responds with its own subsidies, alternative architectures, and accelerated deployment of older-node capacity",
        "why": "leading-edge chips power AI, smartphones, automotive electronics, and defense systems. Concentration of cutting-edge fabs in Taiwan creates strategic vulnerability tied to Taiwan Strait stability. The race shapes industrial policy, immigration of skilled engineers, supply chain resilience, and the trajectory of AI progress. Trillions of dollars in capex and policy support flow from these calculations",
        "vs": "the current chip race differs from the 1980s US-Japan rivalry in being more globally entangled and centered on a single critical-equipment chokepoint (EUV) rather than DRAM commodity competition. It differs from the rare earths and battery races in the depth of capital and engineering required: a leading-edge fab costs over 20 billion dollars and takes years to commission",
        "ex": "TSMC's Arizona fabs, partly funded by 6.6 billion dollars in CHIPS Act grants, will produce 3 nm and 2 nm chips for Apple, Nvidia, and AMD. The first fab began limited production in 2024; ramp to commercial volumes is expected by 2026, making it the most advanced US-soil capacity in over a decade",
        "mis": "people think a few years of investment can replicate Taiwanese manufacturing. The supply chain depends on hundreds of specialized suppliers, decades of tacit engineering knowledge, and a tightly integrated workforce that does not transfer quickly. Another myth is that the export controls are airtight; older-node chips, smuggling, and indigenous capacity at 7 nm have all blunted them",
    }

    T["the post-2022 surge in artificial intelligence capability"] = {
        "_cat": "current_events",
        "what": "the wave of dramatic capability gains in large language models and multimodal systems following the 2022 release of ChatGPT, marked by rapid scaling, billion-dollar training runs, mainstream consumer adoption, and intense regulatory and economic responses",
        "how": "the gains stem from the transformer architecture, scaling laws relating performance to compute, data, and parameters, and innovations like reinforcement learning from human feedback (RLHF) and Constitutional AI for alignment. Industry has poured tens of billions of dollars into training infrastructure (Nvidia GPUs, TPU clusters), datacenter buildouts, and proprietary data deals. Capabilities that took years of research now leap quarterly: longer context, native multimodality, agentic tool use, code generation, and reasoning are all advancing in parallel",
        "why": "AI is transforming knowledge work, software engineering, customer support, content creation, and scientific research. It is reshaping labor markets, intellectual property law, education, energy demand (datacenter electricity is straining grids), and national security. It is also surfacing unresolved questions around bias, misinformation, copyright, autonomous decision-making, and existential risk that policy is racing to catch up with",
        "vs": "the current AI wave differs from earlier hype cycles (1980s expert systems, 2010s deep learning) in producing immediate productivity gains, in widespread consumer use, and in capital intensity. It differs from prior software platform shifts in compounding so rapidly that benchmarks become saturated within months. Foundation models differ from older task-specific systems by being broadly capable from a single training run",
        "ex": "GPT-4, Claude, Gemini, and Llama 3 have demonstrated near-human or super-human performance on programming benchmarks, professional licensing exams, and graduate-level reasoning tasks. Anthropic's Claude Opus 4.7 and OpenAI's GPT-5 generation extended these gains into agentic workflows where models autonomously use tools and complete multi-step tasks unattended over hours",
        "mis": "people think current AI is conscious or genuinely understanding. Models are sophisticated pattern matchers; their fluency and reasoning are emergent from scale rather than evidence of subjective experience. Another myth is that progress will plateau soon; while specific benchmarks saturate, capability across new modalities (video, robotics, science) keeps expanding, and inference-time reasoning techniques have created new scaling axes",
    }

    T["the climate adaptation pivot"] = {
        "_cat": "current_events",
        "what": "the shift in climate policy and infrastructure investment toward preparing for unavoidable warming impacts (heatwaves, sea level rise, drought, wildfire, more intense storms) alongside continued mitigation, recognizing that already-locked-in warming makes adaptation a parallel necessity rather than a fallback",
        "how": "governments are revising flood and fire hazard maps, hardening transportation and water infrastructure, retreating from chronically flooded coastlines, redesigning building codes for extreme heat, expanding cooling-center networks, restoring wetlands as buffers, and updating insurance regulation to reflect new risk distributions. The 2015 Paris Agreement explicitly elevated adaptation alongside mitigation; subsequent COPs created loss-and-damage funding mechanisms for poorer countries bearing impacts they did not cause",
        "why": "even with aggressive emissions cuts, the climate system has substantial committed warming through the late twenty-first century. Adapting infrastructure and societies is not optional but timing matters: investments now are far cheaper than emergency rebuilds later. Adaptation is also a justice issue, since the most exposed populations contributed least to emissions and have the fewest resources",
        "vs": "adaptation differs from mitigation (which targets emissions and the ultimate cause) and from climate engineering (which proposes deliberate intervention in the climate system). It differs from disaster response in being proactive and structural. The two fields once competed for attention; current policy treats them as complementary",
        "ex": "the Netherlands' Room for the River program rebuilt floodplains and lowered embankments along major rivers, designed to handle higher peak flows expected from climate change. New York City's post-Sandy resilience plan included Lower Manhattan flood walls, hardened subway entrances, and revised zoning. Both projects ran into the billions of euros and dollars but represent the scale of investment now considered routine",
        "mis": "people think focusing on adaptation means giving up on mitigation. Both are needed: adaptation handles unavoidable change, mitigation limits how much change has to be adapted to. Another myth is that adaptation is mainly for poor countries; wealthy coastal cities, agricultural regions, and forest interfaces all face costly adaptation needs and have begun major projects",
    }

    T["the cost-of-living and inflation cycle since 2021"] = {
        "_cat": "current_events",
        "what": "the multi-year burst of consumer-price inflation that began in 2021 across most advanced economies, peaked in 2022 at 9.1 percent in the US and over 10 percent in much of Europe, and gradually subsided through 2023 and 2024 under aggressive central bank tightening",
        "how": "post-pandemic supply chain disruptions, fiscal stimulus boosting demand, energy shocks from the 2022 Russian invasion of Ukraine, and labor market tightness combined to push prices up across goods, services, food, and energy. Central banks raised policy rates from near zero to multi-decade highs (Fed funds rate to 5.5 percent, ECB deposit rate to 4 percent, Bank of England base rate to 5.25 percent) over 2022-2023. Inflation responded with a lag, settling closer to target by mid-2024 in most economies, with services and shelter inflation persistently slower to come down",
        "why": "the inflation episode reshaped politics in many democracies (incumbents lost ground or office), strained low-income households disproportionately, slowed housing markets through high mortgage rates, and forced central banks to relearn lessons about supply shocks and expectation management. Real wages took years to recover purchasing power, and the political consequences continue to unfold",
        "vs": "the 2021-2024 inflation differs from the 1970s stagflation in being driven by transient supply disruptions and post-pandemic demand surges rather than wage-price spirals embedded in expectations. It differs from emerging-market inflation in originating mostly in supply rather than monetary disorder. Disinflation since 2023 has so far avoided the deep recessions that accompanied earlier disinflation episodes",
        "ex": "US grocery prices rose roughly 25 percent between January 2020 and December 2024, even as headline annual inflation cooled. Egg prices spiked over 60 percent year-over-year at one point amid avian flu outbreaks. The lived experience of higher price levels persisted long after annual inflation rates returned near 2 percent target",
        "mis": "people think inflation falling means prices are dropping. Disinflation means prices are rising more slowly; outright price decreases (deflation) is a separate and rarer phenomenon. Another myth is that this inflation was purely monetary; analyses attribute roughly half to supply disruptions, roughly a third to demand-pull, and the remainder to energy and food shocks, with proportions varying by country",
    }

    T["the demographic shift in major economies"] = {
        "_cat": "current_events",
        "what": "the structural aging and slowing growth of populations in most advanced economies and increasingly in middle-income ones (China, Korea, southern Europe), driven by below-replacement fertility, longer lifespans, and slower or net-negative immigration in some regions",
        "how": "fertility rates have fallen below the replacement level of 2.1 in over half the world's countries. South Korea reached 0.72, Italy and Spain hover around 1.2, China dipped to 1.0. Populations age as cohort sizes shrink and life expectancy lengthens. Working-age populations peak and then contract, raising old-age dependency ratios. Immigration partially offsets the trend in receiving countries (US, Canada, Australia, Germany) but is politically contested. China's working-age population has been shrinking since 2012; Japan's since 1995",
        "why": "demographic shifts compress labor supply, raise pension and healthcare costs, slow GDP growth potential, depress real interest rates, reshape housing markets, and create political pressure on welfare states and immigration policy. Countries that age faster than they grow rich (China, Russia, much of Eastern Europe) face especially difficult transitions. Long-run productivity, automation, and immigration policy will determine outcomes",
        "vs": "the current demographic shift differs from earlier transitions (the demographic transition's first wave in the nineteenth and twentieth centuries) in occurring at much higher absolute incomes and lifespans. It differs across regions: Africa is still in early-transition rapid growth; East Asia is in late-transition rapid aging; Europe is in low-stable below-replacement equilibrium with substantial immigration",
        "ex": "Japan's working-age population has shrunk by roughly 13 million since 1995, while its elderly cohort has grown sharply. The country has responded with extensive automation in manufacturing and services, a higher female labor force participation rate, gradual increases in immigration, and a rising effective retirement age. Even so, GDP growth has averaged below 1 percent for thirty years",
        "mis": "people think more babies will fix the problem quickly. Even a sudden return to replacement fertility takes 20 to 25 years to expand the working-age population. Another myth is that immigration alone can solve aging; absolute scales (China would need tens of millions of immigrants annually for decades) make it impractical at the upper bound, even where politically possible",
    }

    # extra science to round out
    T["how vaccines induce immune memory"] = {
        "_cat": "science",
        "what": "the process by which vaccines train the adaptive immune system to recognize and rapidly respond to specific pathogens by exposing it to antigens (whole inactivated pathogens, subunits, or genetic instructions) without causing disease, generating long-lived memory B and T cells",
        "how": "after vaccination, dendritic cells take up antigen and migrate to lymph nodes, where they present it to naive T cells. Helper T cells activate B cells with matching B-cell receptors. Activated B cells proliferate, undergo somatic hypermutation, and class-switch antibodies. A subset becomes long-lived memory B cells in the bone marrow that can rapidly secrete antibodies on re-exposure. Memory T cells (central memory, effector memory) persist for years to decades, enabling fast and specific responses to natural infection",
        "why": "vaccination has eradicated smallpox, eliminated polio in most of the world, and prevents an estimated 4 to 5 million deaths annually. Childhood immunization is among the most cost-effective interventions in public health. Understanding immune memory underpins vaccine design, schedule decisions (boosters, primary series), and strategy for emerging pathogens",
        "vs": "vaccine-induced immunity differs from passive immunity (transferred antibodies, like maternal IgG or monoclonal therapeutics), which gives immediate protection but no memory and wanes within weeks to months. It differs from natural infection, which often produces broader immunity but at the cost of disease morbidity and mortality, and from herd immunity, a population-level phenomenon that requires individual immunity to be widespread",
        "ex": "the measles vaccine produces durable, often lifelong immunity after a two-dose schedule. Antibody titers remain detectable decades later, and memory cells respond rapidly to exposure, breaking transmission chains. Drops in vaccination coverage have led to measles resurgences in the US, Europe, and parts of Africa over the past decade",
        "mis": "people think vaccines cause the diseases they prevent. Inactivated, subunit, and mRNA vaccines cannot cause disease at all; live attenuated vaccines can cause mild forms in immunocompromised recipients but not in healthy ones. Another myth is that natural immunity is always superior; for many pathogens (HPV, tetanus, diphtheria), vaccine-induced immunity is broader and longer-lasting than that produced by natural exposure",
    }

    T["how the kidneys filter blood"] = {
        "_cat": "science",
        "what": "the paired retroperitoneal organs that remove waste, regulate blood volume, electrolytes, pH, and blood pressure by filtering roughly 180 liters of plasma daily through about a million nephrons, reabsorbing most of the filtrate, and excreting the remainder as urine",
        "how": "blood enters glomerular capillaries under pressure. Water, ions, glucose, urea, and other small molecules pass through the filtration barrier into Bowman's capsule, while proteins and cells are retained. The proximal tubule reabsorbs about two thirds of filtered sodium, water, glucose, amino acids, and bicarbonate. The loop of Henle creates a medullary osmotic gradient that allows fine water reabsorption. The distal tubule and collecting duct fine-tune sodium, potassium, calcium, and water under control of aldosterone, ADH (vasopressin), and parathyroid hormone. About 1.5 liters per day exits as urine",
        "why": "kidneys maintain the constant internal environment that every other organ depends on. Failure (acute or chronic) requires dialysis or transplant. Hypertension, diabetes, and aging all damage kidneys, making chronic kidney disease (affecting roughly 10 percent of adults globally) a major public health problem. Drug dosing, fluid management, and acid-base balance all turn on renal function",
        "vs": "the kidneys differ from the liver, which detoxifies via metabolic transformation rather than filtration; from sweat glands, which excrete salts and water through skin; and from the lungs, which excrete CO2. Renal regulation differs from gut absorption in that filtration plus selective reabsorption gives finer control than the gut's selective uptake alone",
        "ex": "the artificial kidney (hemodialysis machine) replaces about 10 to 15 percent of normal renal function, performed three times a week for four hours. Patients survive for years on dialysis, but quality of life and life expectancy remain below those of transplant recipients, illustrating how much native kidney function does that machines only partially replicate",
        "mis": "people think 'detox' diets help kidneys. Healthy kidneys self-regulate; the most useful dietary interventions for renal health are blood pressure control, blood sugar management, and adequate hydration, not specialized cleanses. Another myth is that more water is always better; people with heart failure or advanced kidney disease can be harmed by excess fluid",
    }

    T["how greenhouse vegetables are grown commercially"] = {
        "_cat": "science",
        "what": "the controlled-environment cultivation of crops like tomatoes, cucumbers, peppers, and lettuce inside glass or polyethylene structures that regulate temperature, humidity, light, CO2, and nutrient delivery to maximize yield, year-round, with minimal pesticide use",
        "how": "modern greenhouses use computer-controlled climate systems: thermal screens, vents, heaters, evaporative cooling, supplemental LED lighting, and CO2 enrichment that boost photosynthesis. Hydroponic systems deliver dissolved nutrients to roots growing in inert substrates (rockwool, coco coir) or in water alone. Pollination relies on managed bumblebee colonies for tomatoes and peppers. Integrated pest management uses beneficial insects (Encarsia, Phytoseiulus) to control pests biologically. Yields per square meter run 5 to 10 times open-field equivalents",
        "why": "greenhouses extend growing seasons, reduce water use through closed-loop irrigation (1 liter per kg of tomatoes versus 50+ liters in open fields in arid climates), enable production near urban consumers, and reduce pesticide inputs. They are central to food security in cold and arid regions and to year-round access to fresh produce in northern markets. The Netherlands, the world leader, exports vegetables despite tiny land area",
        "vs": "greenhouse cultivation differs from open-field agriculture in capital intensity, water and pesticide efficiency, yield per area, and energy demand. It differs from indoor vertical farming in using natural sunlight (mostly) rather than full artificial lighting, which dramatically reduces energy per kg of produce. It differs from low-tech polytunnels in the level of climate control",
        "ex": "the Westland region of the Netherlands hosts about 4500 hectares of high-tech glass greenhouses, producing roughly 4 million tonnes of vegetables annually. Yields exceeding 70 kg of tomatoes per square meter per year are routine, with the surplus exported across Europe and beyond. Energy use is offset increasingly by combined heat and power and geothermal sources",
        "mis": "people think greenhouse vegetables are nutritionally inferior. Modern hydroponic systems deliver controlled nutrition that often matches or exceeds field equivalents; sensory differences track variety choice and ripeness at harvest more than growing method. Another myth is that hydroponics is unnatural in some hazardous sense; the chemistry is identical to soil chemistry, just delivered more directly",
    }

    T["how a smartphone touchscreen detects touch"] = {
        "_cat": "technology",
        "what": "the layered system of capacitive sensors and a controller IC that detects finger touches by measuring tiny changes in electrical capacitance across a grid of transparent conductors, then translates the change into x, y coordinates passed to the operating system",
        "how": "the screen has a matrix of indium tin oxide electrodes arranged in rows and columns under the cover glass. A controller drives one row at a time and senses capacitance on each column. A finger near the surface acts as a small grounded capacitor that diverts charge, lowering the measured capacitance at the intersection. The controller scans the full matrix many times per second, runs digital signal processing to identify peaks, and reports touch points. Multi-touch tracking, palm rejection, and gesture recognition are computed in firmware before events reach apps",
        "why": "capacitive multi-touch is what made the modern smartphone possible. Without reliable, fast, low-power touch input, the all-screen form factor and direct-manipulation interfaces of post-2007 phones would not work. The technology now extends to laptops, tablets, automotive consoles, kiosks, and household appliances",
        "vs": "capacitive touchscreens differ from resistive ones (older technology, registers any pressed object including styluses but supports only one touch and degrades over time). They differ from infrared and surface acoustic wave touchscreens used in larger displays, and from active stylus systems that combine capacitive sensing with electromagnetic resonance for pressure sensitivity",
        "ex": "the original 2007 iPhone introduced commercial multi-touch capacitive sensing at consumer scale, enabling pinch-to-zoom and direct manipulation that defined the smartphone era. Today's touchscreens detect 10 simultaneous touches, reject palms and water droplets, and integrate fingerprint and force sensing in some implementations",
        "mis": "people think gloves do not work because of insulation. They block capacitive coupling because most fabrics do not conduct; specialty conductive-thread gloves work fine. Another myth is that screen protectors degrade touch quality; quality protectors are thin enough that the capacitance change still propagates through; very thick or metallic ones can interfere",
    }

    T["how to read a paystub"] = {
        "_cat": "everyday_life",
        "what": "the document attached to a paycheck or available in an HR portal showing gross pay, mandatory and voluntary deductions, year-to-date totals, and net (take-home) pay, structured to satisfy labor law and let employees verify their compensation and tax withholding",
        "how": "start with gross pay (regular hours times rate plus overtime, bonuses, commissions). Pre-tax deductions (401(k) contributions, health insurance premiums, FSA/HSA, transit benefits) reduce taxable wages. Federal income tax withholding follows your W-4 elections, plus FICA (6.2 percent Social Security to a wage base, 1.45 percent Medicare). State and local taxes apply based on residency. After-tax deductions (Roth 401(k), garnishments, charitable giving) come out next. Net pay is what hits your bank. Year-to-date columns track running totals that should match a year-end W-2",
        "why": "checking a paystub catches errors (missed overtime, wrong tax setup, missing benefit deductions), confirms benefits enrollment, verifies year-to-date matches expectations, and prepares you to spot a tax surprise before April. Misreading a paystub leads to under-withholding and large April tax bills, or to overpaying for benefits without noticing",
        "vs": "paystubs differ from invoices (which contractors send for work), W-2s (annual wage and tax summary used to file taxes), and 1099s (independent contractor income reporting). They differ from bank statements in showing pay-period detail rather than account balances",
        "ex": "an employee earning 5000 dollars gross monthly might see 400 dollars 401(k), 200 health premium, 700 federal income tax, 310 Social Security, 73 Medicare, 200 state tax. Net pay around 3317 dollars, with year-to-date columns increasing each pay period. Spotting a sudden change in withholding or premium amount triggers questions to HR before the difference compounds",
        "mis": "people think gross pay equals what they earn. Taxes and pre-tax benefits can deduct 25 to 40 percent before take-home. Another myth is that bonuses are taxed at higher rates; they are withheld at supplemental rates that often look high but reconcile to your actual marginal rate at year-end filing",
    }

    T["how to spot a phishing email"] = {
        "_cat": "everyday_life",
        "what": "the practical skill of recognizing fraudulent messages designed to trick recipients into revealing credentials, transferring money, or installing malware, by checking sender details, link destinations, urgency cues, and tone against legitimate communication patterns",
        "how": "hover over links to see the actual URL before clicking; legitimate domains rarely match obscure-looking redirectors. Inspect the sender address (not just the display name) for misspellings or unfamiliar domains. Watch for urgency, threats of account closure, payment demands, or requests to act outside normal channels. Treat unexpected attachments with caution. When unsure, navigate to the service through a known bookmark or app rather than clicking the email's link. Confirm verbal requests for money transfers by phoning a known number, never the one in the email",
        "why": "phishing remains the dominant entry point for ransomware, account takeover, and business email compromise, costing billions annually. Personal exposure includes drained bank accounts, identity theft, and compromised email accounts that fan out to contacts. Pattern recognition is the cheapest and most effective defense available",
        "vs": "phishing differs from spam in being deliberately deceptive and targeted; from spear phishing in that the latter is personalized using gathered information about the target; and from vishing (voice) and smishing (SMS), which use the same playbook in different channels. It differs from malware delivered through compromised legitimate sites in always relying on social engineering",
        "ex": "a classic phishing email impersonates a bank and warns 'Your account has been suspended; click here to verify.' The link points to a typosquatted domain that captures credentials. Within seconds the attacker logs in and drains funds. The same template recurs constantly across providers; recognizing it once defends against thousands of variants",
        "mis": "people think enterprise security tools handle phishing. Modern attacks bypass spam filters routinely; user judgment remains the last line. Another myth is that only careless people fall for phishing; well-crafted, contextually relevant attacks deceive trained security professionals, especially under time pressure or emotional distraction",
    }

    T["how to compose a professional email"] = {
        "_cat": "everyday_life",
        "what": "the conventional structure of effective workplace correspondence: a clear subject line, a concise greeting, a focused opening that states purpose, well-organized body paragraphs or bulleted requests, an explicit call to action or clear close, and a signature with relevant contact information",
        "how": "lead the subject line with the action or topic ('Q3 budget review needed by Friday'). Open with the recipient's name and a single-sentence purpose. Give context only if needed; busy readers scan first. Put requests or questions in bullet points or numbered lists when there are more than two. Set a deadline or specify when no response is needed. Close with thanks or a brief next-step. Avoid passive aggression, overly casual emoji, all caps, and walls of unbroken text",
        "why": "professional email is the dominant medium for asynchronous workplace communication. Clear emails reduce back-and-forth, lower meeting load, document decisions, and save reader time. Poor emails compound interruptions, miscommunication, and bad decisions across teams",
        "vs": "professional email differs from chat in being more structured, more durable, and less synchronous; from formal letters in being shorter and more action-oriented; and from text messages in tone, structure, and reach. Internal email is typically more direct than external client email",
        "ex": "a good request email might read: subject 'Approval needed: Q3 marketing budget by Friday'. Body: 'Hi Jamie, attached is the proposed Q3 marketing budget (1.2M, up 8 percent). Could you approve or send revisions by EOD Friday so we can finalize agency commitments? Happy to walk through it Wednesday if helpful.' Signature follows. The reader knows the ask, the deadline, and the option to escalate to a meeting",
        "mis": "people think length signals importance. Long emails are more often skimmed or ignored; concise, well-structured ones get faster responses. Another myth is that bcc is a stealth tool; bcc is appropriate for one-time announcements but using it to hide recipients in a thread routinely backfires when someone replies-all",
    }

    T["how to budget on a variable income"] = {
        "_cat": "everyday_life",
        "what": "a practical method for managing personal finances when monthly income fluctuates (freelancers, commission work, seasonal employment, gig workers), based on prioritizing essentials, smoothing income through reserves, and tracking percentage allocations rather than fixed dollar amounts",
        "how": "list essential monthly expenses (rent, utilities, food, insurance, debt minimums) and aim to keep them below your worst-case income month. Build a buffer fund equal to one to three months of essentials before treating any month's income as discretionary. Pay yourself a flat monthly 'salary' from a holding account; surplus months top up the buffer, lean months draw from it. Set aside taxes immediately on each payment (often 25 to 35 percent for self-employed). Allocate remaining surplus by percentage: investments, savings goals, discretionary",
        "why": "variable income is increasingly common but household budgeting tools assume regular paychecks. Without a smoothing system, lean months trigger debt accumulation and high months get spent rather than saved, locking workers into precarity. A buffer-and-salary approach turns volatile cash flow into predictable household economics",
        "vs": "variable-income budgeting differs from fixed-income approaches like 50/30/20 in not assuming a constant base. It differs from envelope budgeting in needing temporal smoothing rather than category-by-category cash. It differs from business cash management in commingling personal goals with income recognition",
        "ex": "a freelancer averaging 6000 dollars monthly across a year but ranging from 2500 to 9500 might pay themselves 4500 monthly out of a holding account, contribute 1000 to a tax savings account on each payment, and use surplus months to top up a three-month buffer of 13500. After the buffer is full, surplus flows to retirement and discretionary",
        "mis": "people think variable income makes budgeting impossible. The buffer-and-salary approach makes it more disciplined than a regular paycheck, since it forces explicit reserves rather than depending on payday timing. Another myth is that you cannot save in lean months; even small consistent contributions during high months prevent the spiral of catching up later",
    }

    T["how home solar panels generate electricity"] = {
        "_cat": "everyday_life",
        "what": "rooftop photovoltaic systems that convert sunlight to direct current via silicon semiconductor cells, then convert it to alternating current through an inverter for use in the home and export to the grid, often paired with batteries for backup or self-consumption",
        "how": "photons absorbed in silicon cells excite electrons across the band gap, generating a DC voltage at the cell terminals. Cells are wired in series and parallel into modules and arrays sized for the load. A string inverter or microinverters convert DC to grid-synchronized AC, manage maximum power point tracking as sun and shading vary, and disconnect during grid outages (anti-islanding) unless a battery and transfer switch enable backup operation. Net metering or feed-in tariffs credit exported energy",
        "why": "rooftop solar gives households a hedge against electricity price increases, reduces grid emissions, and (with batteries) provides resilience during outages. Costs have fallen by roughly 90 percent since 2010, payback periods are typically 6 to 12 years in sunny markets, and panels last 25 to 30 years with modest degradation",
        "vs": "rooftop solar differs from utility-scale solar in scale, balance-of-system costs, and customer ownership. It differs from solar thermal (water heating) in producing electricity rather than hot water, and from off-grid systems in being grid-tied and benefiting from grid backup. With a battery it differs again from a backup generator, which uses fuel and emits exhaust",
        "ex": "a typical 8 kW residential system in California with about 25 panels generates roughly 12 to 14 MWh per year, often covering more than full annual household electricity use. Combined with a battery for time-of-use arbitrage and outage backup, the system shifts the household's grid relationship from pure consumer to prosumer",
        "mis": "people think solar does not work in cloudy or cold climates. Germany has more installed solar per capita than most sunnier countries; cells actually run more efficiently at lower temperatures, with cloud reducing output but not eliminating it. Another myth is that batteries are essential; most grid-tied systems still use the grid as a virtual battery via net metering, with home batteries being optional for backup or arbitrage",
    }
