#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank: science topics (fresh for batch G)."""


def register(T):
    T["plate tectonics and mantle convection"] = {
        "_cat": "science",
        "what": "the theory that Earth's lithosphere is broken into roughly a dozen large rigid plates that float on the ductile asthenosphere and move centimeters per year, driven primarily by slow convection in the mantle and slab pull at subduction zones",
        "how": "hot rock rises beneath mid-ocean ridges, cools, and spreads outward as new oceanic crust. As the crust ages it grows denser and eventually sinks back into the mantle at subduction zones, pulling the rest of the plate with it. Continental plates ride along, colliding to form mountain ranges, sliding past each other along transform faults, or rifting apart over upwelling plumes",
        "why": "plate tectonics explains earthquakes, volcanoes, mountain building, ocean basin formation, the distribution of fossils across continents, and the long-term carbon cycle that keeps Earth habitable. Hazard maps for seismic and volcanic risk all rely on it",
        "vs": "plate tectonics differs from continental drift (Wegener's earlier idea, which lacked a mechanism), from expanding-Earth hypotheses (now disproven), and from the static-Earth view that dominated geology before the 1960s. Mantle convection is the engine; tectonics is the surface expression",
        "ex": "the Pacific Ring of Fire is a chain of subduction zones surrounding the Pacific plate. The 2011 Tohoku earthquake and tsunami in Japan released energy stored as the Pacific plate slid beneath the North American plate, sliding the seafloor about 50 meters in seconds",
        "mis": "people think continents float on liquid magma. The mantle is solid rock that flows plastically over millions of years; only narrow zones near volcanoes contain actual melt. Another myth is that plate motion is too slow to matter on human timescales; it accumulates as elastic strain that releases catastrophically in earthquakes",
    }

    T["the immune system's innate vs adaptive arms"] = {
        "_cat": "science",
        "what": "the two coordinated branches of vertebrate immunity, where the innate arm provides immediate, broad pattern-recognition defense and the adaptive arm mounts a slower but highly specific response that produces long-term memory",
        "how": "the innate system uses pattern-recognition receptors on macrophages, neutrophils, and dendritic cells to detect conserved microbial features and triggers inflammation, complement activation, and phagocytosis within hours. Dendritic cells then carry pathogen fragments to lymph nodes, where T cells and B cells with matching receptors are activated. B cells produce antibodies; T cells kill infected cells or coordinate other responses. Memory cells persist for years",
        "why": "this two-tier architecture provides immediate cover while a tailored response is mounted, and it underlies vaccination, allergic disease, autoimmunity, transplant rejection, and cancer immunotherapy. Almost all therapeutic immunology hinges on which arm is being engaged",
        "vs": "innate immunity differs from adaptive in being fast, non-specific, and identical between individuals; adaptive is slow on first exposure, exquisitely specific, and shaped by an individual's history. Plant immunity has innate-like elements but lacks the adaptive memory of vertebrates",
        "ex": "a flu vaccine trains the adaptive arm: B cells generate antibodies against hemagglutinin, and memory cells persist so a real infection is met within days rather than weeks. Innate sensors at the injection site provide the inflammation signals that get adaptive activation off the ground",
        "mis": "people think immunity equals antibodies. T cells are equally critical, especially for viral and intracellular infections. Another myth is that a strong immune response is always good; cytokine storms, autoimmunity, and allergies are all immunity behaving too aggressively or against the wrong target",
    }

    T["dark matter evidence"] = {
        "_cat": "science",
        "what": "the body of astrophysical observations indicating that roughly 27 percent of the universe's mass-energy is made of an unseen, gravitationally interacting substance that does not emit or absorb light at any wavelength",
        "how": "evidence stacks from multiple independent directions. Galaxy rotation curves stay flat at large radii instead of falling off, implying invisible mass. Gravitational lensing maps mass directly and reveals far more than visible matter. The cosmic microwave background's acoustic peaks fit cosmologies with about five times more dark matter than ordinary matter. Galaxy cluster collisions like the Bullet Cluster show mass and hot gas separating, ruling out simple modified-gravity explanations",
        "why": "dark matter's gravity is what holds galaxies together, seeded structure formation in the early universe, and shapes the cosmic web. Without it, galaxies would not have formed by today. Its identity is one of the largest open questions in physics, with active searches at the LHC, in deep underground detectors, and through astronomical surveys",
        "vs": "dark matter differs from dark energy, which drives accelerating cosmic expansion and behaves like a smooth pressure rather than clumping mass. It differs from ordinary matter that is simply faint, like brown dwarfs and rogue planets, which have been ruled out by microlensing surveys",
        "ex": "the Bullet Cluster, a collision of two galaxy clusters, shows X-ray-emitting hot gas slowed by friction near the collision center while gravitational lensing reveals the bulk of the mass continuing on past it. The mass and the gas are spatially offset, exactly what is expected if most mass is collisionless dark matter",
        "mis": "people think dark matter is a single confirmed particle. It is a placeholder for several candidates (WIMPs, axions, sterile neutrinos, primordial black holes); none has been directly detected. Another myth is that we 'just have not found the missing matter'; we have ruled out most ordinary-matter explanations",
    }

    T["protein folding"] = {
        "_cat": "science",
        "what": "the process by which a linear chain of amino acids assembles into a specific three-dimensional structure that determines its biological function, governed by physical interactions between residues and their solvent environment",
        "how": "as the polypeptide emerges from the ribosome, hydrophobic residues collapse inward to avoid water while hydrogen bonds organize alpha helices and beta sheets. Side-chain interactions, disulfide bridges, and chaperone proteins guide the chain through intermediate states toward its native fold, typically the lowest accessible free-energy configuration. Folding completes in microseconds to seconds for most proteins",
        "why": "function follows form: misfolded proteins underlie diseases including Alzheimer's, Parkinson's, cystic fibrosis, and prion conditions. Understanding folding enables drug design, enzyme engineering, and the recent revolution in computational structure prediction with AlphaFold, which has reshaped biology",
        "vs": "protein folding differs from intrinsic disorder, where some proteins remain flexible by design, and from aggregation, where folding goes off the rails into amyloid fibrils. It differs from RNA folding, which uses similar principles but a much smaller alphabet of bases",
        "ex": "AlphaFold 2, released in 2021, predicted accurate structures for nearly all 200 million known proteins from sequence alone, an achievement that the protein structure community had pursued for fifty years. The predictions accelerated drug discovery and structural biology immediately",
        "mis": "people think proteins fold by trying every shape (Levinthal's paradox). They actually follow guided pathways shaped by free-energy landscapes funneled toward the native state. Another myth is that the native fold is unique; many proteins have multiple stable conformations, and some shift between them as part of their function",
    }

    T["greenhouse effect physics"] = {
        "_cat": "science",
        "what": "the warming of a planet's surface caused by atmospheric gases that are transparent to incoming visible sunlight but absorb and re-emit outgoing infrared radiation, raising the equilibrium surface temperature above what bare-rock physics predicts",
        "how": "sunlight reaches the surface and warms it. The warm surface emits infrared radiation upward. Greenhouse gases (water vapor, CO2, methane, nitrous oxide, ozone) absorb this infrared at specific wavelengths and re-emit it in random directions, with about half going back down. The atmosphere thus acts as a partial blanket, raising the surface temperature until incoming and outgoing energy balance again, roughly 33 Celsius warmer than otherwise on Earth",
        "why": "the natural greenhouse effect is what makes Earth habitable. Adding CO2 from fossil fuels strengthens it, driving global warming. Quantifying the effect lets climate models project temperature, sea level, and extreme-weather changes under different emissions scenarios",
        "vs": "the greenhouse effect differs from solar variability (a much smaller, fluctuating driver), from urban heat islands (local, not global), and from the runaway greenhouse on Venus where surface temperatures exceed 460 Celsius. It is a passive radiative process, not 'trapping heat' in the literal sense of closed convection",
        "ex": "doubling atmospheric CO2 from preindustrial 280 ppm to 560 ppm produces about 3.7 W/m^2 of additional radiative forcing, which translates through feedbacks to roughly 3 Celsius of equilibrium surface warming according to the latest IPCC consensus",
        "mis": "people think CO2 is the only greenhouse gas. Water vapor is actually the largest contributor, but it is a fast feedback rather than a driver; CO2 sets the long-term temperature anchor. Another myth is that the effect saturates; while CO2's absorption bands are saturated near the surface, additional CO2 still warms by raising the effective emission altitude",
    }

    T["the central limit theorem"] = {
        "_cat": "science",
        "what": "a foundational result in probability stating that the sum or average of many independent, identically distributed random variables with finite variance approaches a normal distribution as the sample size grows, regardless of the original distribution's shape",
        "how": "individual variables can have any distribution (skewed, discrete, heavy-shouldered) as long as variance is finite. When you average n of them, the variance of the average shrinks as 1/n while the shape converges to a Gaussian centered at the true mean with standard deviation sigma over root n. Convergence is fast for symmetric distributions, slower for skewed ones, and characterized formally by the Berry-Esseen theorem",
        "why": "the theorem justifies why so many real-world quantities are roughly normal (heights, measurement errors, polling results), underlies confidence intervals and hypothesis tests, anchors finance models for portfolio returns, and explains why averaging is such a powerful noise-reduction tool",
        "vs": "the central limit theorem differs from the law of large numbers, which says averages converge to the mean (a statement about location); CLT is about the shape of fluctuations. It differs from the stable distribution theorems, which generalize to infinite-variance cases producing Levy stable distributions instead of Gaussians",
        "ex": "polling 1000 randomly chosen voters about a binary issue gives a sample proportion whose distribution is approximately normal with standard error about 1.6 percent, even though each individual response is just 0 or 1. That is why polls report margins of error around plus or minus 3 percent",
        "mis": "people think CLT means individual measurements become normal. It is the average or sum that approaches normality, not the underlying distribution. Another myth is that CLT applies always; heavy-tailed distributions like Cauchy violate the finite-variance assumption and never converge to normal",
    }

    T["how antibiotics target bacteria"] = {
        "_cat": "science",
        "what": "drugs that kill bacteria or stop their growth by interfering with structures or processes that bacteria need but human cells either lack or use differently, exploiting evolutionary distance to achieve selective toxicity",
        "how": "different classes attack different targets. Beta-lactams (penicillin, cephalosporins) block cell wall synthesis by inhibiting transpeptidase. Aminoglycosides and tetracyclines bind bacterial ribosomes (which differ from eukaryotic ones) and block protein synthesis. Fluoroquinolones inhibit DNA gyrase. Sulfonamides block folate synthesis, a pathway humans bypass via dietary intake. Resistance arises through enzyme inactivation, target mutation, efflux pumps, or reduced uptake",
        "why": "antibiotics roughly doubled life expectancy in the twentieth century by making infections treatable and surgery, chemotherapy, and transplants safe. Resistance now threatens to roll those gains back; the WHO calls antimicrobial resistance one of the top global health threats",
        "vs": "antibiotics differ from antivirals, which target features of viruses (and which work against far fewer pathogens), from antifungals (which face harder selectivity problems because fungi are eukaryotes), and from antiseptics, which kill broadly on surfaces but are too toxic for systemic use",
        "ex": "ceftriaxone, a third-generation cephalosporin, is first-line for bacterial meningitis. It penetrates the blood-brain barrier and disrupts cell-wall synthesis in pathogens like Streptococcus pneumoniae, often turning a once-fatal disease into a recoverable infection within days",
        "mis": "people think antibiotics work against viruses. They do not, which is why they are useless against colds and flu. Another myth is that finishing the prescription always reduces resistance; recent studies suggest stopping when symptoms resolve can be appropriate for some indications, and the universal 'finish every dose' rule oversimplifies",
    }

    T["sleep stages and the role of REM"] = {
        "_cat": "science",
        "what": "the structured cycle of brain states the human body passes through each night, alternating roughly every 90 minutes between non-REM stages 1 to 3 (light to deep slow-wave sleep) and REM (rapid eye movement) sleep, when most vivid dreaming and memory consolidation occur",
        "how": "as you fall asleep, brain waves slow from alert beta and alpha through theta into delta during deep slow-wave sleep, when growth hormone is released and slow-wave activity supports synaptic homeostasis. After about 70 to 90 minutes the brain transitions to REM, where the cortex reactivates near waking levels, eyes flicker, the body is paralyzed by brainstem inhibition, and dreams become narrative. Cycles repeat through the night, with REM episodes lengthening toward morning",
        "why": "sleep stages support distinct functions: deep sleep clears metabolic waste through the glymphatic system and consolidates declarative memory, while REM appears critical for emotional processing, procedural memory, and creative recombination. Disruption of either stage is linked to cognitive deficits, mood disorders, and metabolic disease",
        "vs": "REM differs from non-REM in cortical activation, presence of vivid dreaming, muscle atonia, and irregular autonomic patterns. It differs from waking in that sensory input is largely gated out and the prefrontal cortex is relatively quiet, yielding the looser logic of dreams",
        "ex": "people deprived of REM specifically (by waking at every REM onset) recover by spending an unusually large fraction of subsequent nights in REM, the so-called REM rebound. This is one of the strongest pieces of evidence that REM serves a regulated function rather than being incidental",
        "mis": "people think dreams happen only in REM. They occur in non-REM too, though they tend to be more thought-like and less narrative. Another myth is that you can train yourself to need less sleep; the brain accumulates sleep debt that catches up regardless of conscious effort",
    }

    T["how genome-wide association studies work"] = {
        "_cat": "science",
        "what": "a study design that scans hundreds of thousands to millions of common genetic variants across the genomes of large populations to find statistical associations between specific variants and a trait or disease",
        "how": "researchers genotype each participant at a dense set of single-nucleotide polymorphisms (SNPs), code each variant as 0, 1, or 2 copies, and run a regression of the trait on each SNP, controlling for ancestry. Variants that pass a stringent significance threshold (typically 5 x 10^-8) after correcting for multiple testing are reported. Effect sizes for common variants are usually small, so cohorts of tens of thousands to millions are needed",
        "why": "GWAS has identified thousands of loci for diseases like type 2 diabetes, schizophrenia, and coronary artery disease, illuminating biology and enabling polygenic risk scores. They expose causal pathways (via Mendelian randomization), inform drug-target prioritization, and have driven the era of biobanks like UK Biobank",
        "vs": "GWAS differs from candidate-gene studies, which test prespecified genes (and historically had high false-positive rates), and from whole-genome sequencing studies, which capture rare variants too. They differ from family linkage analysis, which finds large-effect loci in pedigrees rather than population-wide associations",
        "ex": "GWAS for height has found over 12000 independent variants explaining roughly 40 percent of heritability. No single variant has a large effect, but together they show how a complex polygenic trait is built from many small contributions",
        "mis": "people think a GWAS hit is a 'gene for' the trait. Hits are usually intergenic regulatory variants whose target genes must be identified by follow-up work. Another myth is that GWAS effects are deterministic; even strong polygenic scores predict only a fraction of individual outcomes",
    }

    T["how mRNA vaccines work"] = {
        "_cat": "science",
        "what": "vaccines that deliver a fragment of messenger RNA encoding a pathogen antigen, usually wrapped in lipid nanoparticles, so a recipient's own cells transiently produce the antigen and prime an immune response without ever encountering the live pathogen",
        "how": "the mRNA, modified with pseudouridine to avoid innate immune over-activation, is encapsulated in lipid nanoparticles that fuse with cell membranes. Inside the cytoplasm, ribosomes translate the mRNA into the encoded protein (such as the SARS-CoV-2 spike). The cell displays fragments on MHC molecules and secretes the protein, which dendritic cells process and present to T cells. B cells generate antibodies and memory cells. The mRNA itself degrades within days; it never enters the nucleus",
        "why": "mRNA platforms allowed COVID-19 vaccines to go from genome sequence to clinical trial in weeks, an unprecedented speed. The same platform is being applied to influenza, RSV, cytomegalovirus, and personalized cancer vaccines, where rapid manufacturing and easy reformulation are decisive",
        "vs": "mRNA vaccines differ from inactivated vaccines (whole killed pathogen), live attenuated vaccines (weakened pathogen), and subunit vaccines (purified protein), which are slower and more rigid to manufacture. They differ from DNA vaccines in not needing to reach the nucleus, which simplifies safety",
        "ex": "the BNT162b2 (Pfizer-BioNTech) and mRNA-1273 (Moderna) COVID-19 vaccines deployed at scale in late 2020 prevented an estimated 14 to 20 million deaths in their first year. Each delivered 30 to 100 micrograms of spike-encoding mRNA per dose",
        "mis": "people think mRNA vaccines alter your DNA. They cannot; mRNA never enters the nucleus and there is no reverse transcriptase to integrate it. Another myth is that they are entirely new; mRNA vaccine research dates back to the 1990s, with two decades of preclinical work preceding 2020",
    }

    T["the second law of thermodynamics"] = {
        "_cat": "science",
        "what": "the principle that the total entropy of an isolated system never decreases over time, equivalently that heat flows spontaneously from hot to cold and that no cyclic process can convert heat entirely into work",
        "how": "statistically, isolated systems evolve toward macrostates that correspond to the largest number of microstates, because random microscopic dynamics make those configurations overwhelmingly more probable. Macroscopically, this manifests as gases mixing, hot objects cooling, and energy spreading out. Reversible processes hold entropy constant; real processes always generate entropy through friction, heat conduction, or unrestrained expansion",
        "why": "the second law sets the maximum efficiency of heat engines (the Carnot limit), explains why perpetual motion machines of the second kind are impossible, underlies refrigeration and chemical equilibrium, and gives time its arrow even though microscopic laws are time-symmetric",
        "vs": "the second law differs from the first (energy conservation), the third (entropy approaches a constant near absolute zero), and the zeroth (transitivity of thermal equilibrium). It differs from information-theoretic entropy in motivation but they are unified by Boltzmann's S = k log W",
        "ex": "a steam turbine running between 600 Celsius source and 30 Celsius sink has a maximum possible efficiency of 1 - 303/873, about 65 percent. Real turbines achieve 40 to 50 percent because of irreversibilities; no engineering can exceed the Carnot bound",
        "mis": "people think entropy means disorder in any colloquial sense. It is the count of microstates consistent with a macrostate, which often correlates with disorder but is not the same thing. Another myth is that life violates the second law; living systems decrease their internal entropy by exporting more entropy to the environment",
    }

    T["the human microbiome"] = {
        "_cat": "science",
        "what": "the trillions of bacteria, archaea, fungi, and viruses inhabiting human bodies (especially the gut, skin, mouth, and reproductive tract) that influence digestion, immune development, metabolism, mood, and susceptibility to disease",
        "how": "microbes colonize during and after birth and stabilize into individualized communities by age three. The gut microbiome ferments dietary fiber into short-chain fatty acids that nourish colon cells, modulates bile acid metabolism, trains immune tolerance, produces neurotransmitters (about 90 percent of body serotonin), and competes with pathogens. Composition responds to diet, antibiotics, illness, and medications, and is sampled most often via 16S rRNA sequencing or shotgun metagenomics",
        "why": "microbiome research has linked community composition to obesity, type 2 diabetes, inflammatory bowel disease, allergies, autism, depression, and cancer immunotherapy response. Fecal microbiota transplant cures recurrent C. difficile infection at over 90 percent rates. Personalized nutrition, probiotic therapeutics, and microbiome biomarkers are major active research and commercial areas",
        "vs": "the microbiome differs from infectious agents in that most resident microbes are commensals or mutualists rather than pathogens, and from cells of the host in being separate organisms with distinct genomes. It differs from the older notion of 'gut flora' in including all microbial domains and in being studied as a complex ecosystem rather than a list of species",
        "ex": "fecal microbiota transplantation (FMT) for recurrent Clostridioides difficile infection delivers stool from a healthy donor (or processed equivalent) into a patient's colon. Cure rates of 85 to 95 percent in randomized trials transformed treatment of a previously refractory condition and validated the principle that ecosystem-level intervention can outperform single-organism therapeutics",
        "mis": "people think probiotics universally improve health. Evidence is strong only for specific indications (antibiotic-associated diarrhea, certain pediatric conditions); over-the-counter probiotics show inconsistent effects in healthy adults. Another myth is that more diverse microbiome is always better; diversity correlates with health in many contexts but specific functional capacities may matter more than raw counts",
    }

    T["evolutionary natural selection"] = {
        "_cat": "science",
        "what": "the process by which heritable variations affecting reproductive success differentially propagate across generations, gradually shaping populations to fit their environments, originally articulated by Darwin and Wallace in 1858 and now grounded in modern genetics",
        "how": "individuals vary in heritable traits, and some variants leave more descendants than others under prevailing conditions. Over generations, allele frequencies shift toward variants that improve survival and reproduction. Mutation supplies new variation; recombination shuffles existing variation; drift, gene flow, and selection are the four main forces of population change. Selection can be directional, stabilizing, disruptive, or frequency-dependent, and operates on phenotypes that emerge from genotype-by-environment interaction",
        "why": "natural selection explains the apparent design of organisms without a designer, unifies biology under a single explanatory framework, underlies antibiotic and pesticide resistance evolution, informs conservation, and grounds evolutionary medicine. It also reshapes how we think about behavior, cognition, and culture, with extensions and debates continuing to expand the framework",
        "vs": "natural selection differs from artificial selection in lacking a directed selector but operating on the same underlying mechanism. It differs from genetic drift, which changes allele frequencies through random sampling rather than fitness differences, and from Lamarckian inheritance of acquired characteristics, which lacked a mechanism and was largely refuted by genetics. It differs from intelligent design as an explanatory framework for biological structure",
        "ex": "antibiotic resistance evolves rapidly when antibiotics are used: variants of bacteria with mutations that reduce drug binding survive and reproduce while susceptible strains die. The process is observable in clinical settings within months, demonstrating selection in real time. The same logic explains pesticide resistance, herbicide resistance in weeds, and treatment escape in HIV and cancer",
        "mis": "people think evolution is purposive or progressive, with humans as the goal. Selection is opportunistic and produces local fits rather than progress; many evolutionary changes are losses of complexity (cave fish losing eyes) or compromises. Another myth is that 'survival of the fittest' means the strongest physically; fitness is reproductive success in context, which can favor cooperation, deception, or being unobtrusive",
    }

    T["how CRISPR gene editing works"] = {
        "_cat": "science",
        "what": "a class of molecular tools derived from bacterial immune systems that uses a guide RNA to direct a programmable nuclease (most commonly Cas9) to a specific DNA sequence, where it cuts both strands and triggers cellular repair that can disable, edit, or insert genes",
        "how": "researchers design a 20-nucleotide guide RNA matching their target site adjacent to a protospacer adjacent motif (PAM). Cas9 binds the guide, scans the genome, and cleaves both strands at the matched site. Cells repair the cut by non-homologous end joining (which often introduces small insertions or deletions that knock out a gene) or, given a donor template, by homology-directed repair that installs precise edits. Variants like base editors and prime editors avoid double-strand breaks for cleaner edits",
        "why": "CRISPR has accelerated functional genomics, enabled gene therapies for sickle cell disease (Casgevy, approved 2023) and transthyretin amyloidosis, made disease models cheap and rapid, and is reshaping agriculture and biotechnology. The 2020 Nobel Prize in Chemistry recognized its discovery",
        "vs": "CRISPR differs from earlier programmable nucleases (zinc-finger nucleases, TALENs) in being far simpler to retarget by changing a guide RNA rather than redesigning a protein. It differs from RNA interference (RNAi), which knocks down mRNA without altering DNA, and from gene therapy with viral vectors that simply add a transgene without editing in place",
        "ex": "Casgevy, the first approved CRISPR therapy, uses ex vivo editing of a patient's hematopoietic stem cells to disrupt a regulator of fetal hemoglobin. Reactivating fetal hemoglobin substitutes for the defective adult hemoglobin in sickle cell disease, ending vaso-occlusive crises in most treated patients",
        "mis": "people think CRISPR creates designer babies easily. Editing germline embryos is technically possible but largely banned, and even there off-target effects and mosaicism limit reliability. Another myth is that CRISPR always cuts perfectly; off-target cuts at similar sequences and chromosomal rearrangements are real risks that drive the development of more precise variants",
    }
