#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Data tables for gen_tc_09_3_A.py.

Domain: weather, geolocation, maps, calendar, scheduling.

Each TOOL_SPECS entry is:
  (tool_name, [(user_template, args_dict_template, tool_result_template), ...])

Templates use {placeholders} filled from PARAM_POOLS.
"""

# Pools of realistic values to interpolate into templates.
CITIES = [
    "Boston", "Seattle", "Tokyo", "Berlin", "Lagos", "Mumbai", "Sao Paulo",
    "Cairo", "Sydney", "Reykjavik", "Buenos Aires", "Helsinki", "Marrakech",
    "Vancouver", "Dublin", "Singapore", "Cape Town", "Lima", "Oslo", "Manila",
    "Seoul", "Athens", "Vienna", "Prague", "Lisbon", "Auckland", "Quito",
    "Tashkent", "Nairobi", "Hanoi", "Bogota", "Kyoto", "Ankara", "Riyadh",
    "Stockholm", "Edinburgh", "Warsaw", "Budapest", "Zurich", "Casablanca",
]

ADDRESSES = [
    "1600 Amphitheatre Pkwy, Mountain View, CA",
    "350 5th Ave, New York, NY",
    "10 Downing St, London",
    "1 Apple Park Way, Cupertino, CA",
    "221B Baker St, London",
    "1500 Pennsylvania Ave NW, Washington DC",
    "Champs-Elysees 75, Paris",
    "Friedrichstrasse 200, Berlin",
    "Shibuya Crossing, Tokyo",
    "Bondi Beach, Sydney",
    "Plaza Mayor 1, Madrid",
    "Red Square 3, Moscow",
    "Avenida Paulista 1578, Sao Paulo",
    "Connaught Place, New Delhi",
    "Orchard Rd 200, Singapore",
    "King's Cross Station, London",
    "Union Station, Toronto",
    "Penn Station, New York",
    "Gare du Nord, Paris",
    "Marina Bay Sands, Singapore",
]

TIMEZONES = [
    "America/New_York", "America/Los_Angeles", "America/Chicago",
    "Europe/London", "Europe/Berlin", "Europe/Paris", "Europe/Madrid",
    "Asia/Tokyo", "Asia/Singapore", "Asia/Kolkata", "Asia/Dubai",
    "Australia/Sydney", "Pacific/Auckland", "Africa/Johannesburg",
    "America/Sao_Paulo", "America/Mexico_City", "Asia/Shanghai",
    "Europe/Moscow", "Europe/Istanbul", "America/Toronto",
]

COUNTRIES = ["US", "CA", "GB", "DE", "FR", "JP", "AU", "BR", "IN", "ZA",
             "MX", "ES", "IT", "NL", "SE", "NO", "FI", "PL", "PT", "GR"]

# (lat, lon) pairs roughly matching real cities
COORDS = [
    (40.7128, -74.0060), (34.0522, -118.2437), (51.5074, -0.1278),
    (48.8566, 2.3522), (35.6762, 139.6503), (-33.8688, 151.2093),
    (-23.5505, -46.6333), (19.0760, 72.8777), (1.3521, 103.8198),
    (52.5200, 13.4050), (55.7558, 37.6173), (-22.9068, -43.1729),
    (37.7749, -122.4194), (41.8781, -87.6298), (47.6062, -122.3321),
    (43.6532, -79.3832), (49.2827, -123.1207), (53.3498, -6.2603),
    (59.9139, 10.7522), (60.1699, 24.9384),
]

DATETIMES = [
    "2026-05-12T09:00:00", "2026-05-13T14:30:00", "2026-05-15T08:00:00",
    "2026-05-20T17:45:00", "2026-06-01T10:00:00", "2026-06-03T13:15:00",
    "2026-06-10T19:00:00", "2026-06-15T07:30:00", "2026-07-04T12:00:00",
    "2026-07-22T15:00:00", "2026-08-09T11:30:00", "2026-08-30T16:00:00",
    "2026-09-05T09:45:00", "2026-09-18T20:00:00", "2026-10-31T18:00:00",
    "2026-11-11T10:30:00", "2026-12-24T17:00:00", "2027-01-07T08:15:00",
    "2027-02-14T19:30:00", "2027-03-21T12:00:00",
]

EVENT_IDS = [f"cal_evt_{n:05d}" for n in
             [62150, 11420, 99812, 30457, 88123, 47291, 55039, 70022,
              13384, 24617, 36849, 48052, 59285, 60418, 71640, 82873,
              94005, 15238, 26461, 37694, 48927, 50150, 61383, 72516,
              83749, 94972, 16205, 27438, 38661, 49894]]

USER_IDS = [f"user_{n}" for n in
            ["lakshman", "alex42", "priya_s", "kenji.t", "maria_g",
             "ahmed_k", "sven_l", "ines_b", "yuki_n", "carlos_r",
             "fatima_z", "ola_w", "mei_l", "raj_p", "nina_h"]]

CALENDAR_IDS = [f"cal_{n}" for n in
                ["primary", "work", "personal", "family", "team_alpha",
                 "ops_oncall", "marketing", "sales_q3", "engineering",
                 "exec_offsite"]]


# ----------------------------------------------------------------------------
# Tool catalog. Each spec: tool_name -> (user_msgs, args_builders, results)
#
# The generator picks samples in round-robin so each tool gets ~12-13 samples.
# We need >=40 distinct tools and <=25 occurrences per tool. With 41 tools and
# 500 samples that's ~12 per tool, well under the 25 cap.
# ----------------------------------------------------------------------------

# We'll define per-tool (user_text, args_dict, tool_result_json_str) tuples.
# The generator will pick which become single-turn vs multi-turn.

import json as _json


def _r(d):
    """Helper: serialize dict as compact JSON string for tool result."""
    return _json.dumps(d, separators=(",", ":"))


# Each tool has 13 sample variants (we cycle deterministically).
TOOL_SAMPLES = {

    "get_weather": [
        ("What's the weather in {city} right now?",
         {"city": "{city}"}, _r({"temp_f": 54, "conditions": "clear", "humidity": 62})),
        ("weather in {city}?",
         {"city": "{city}"}, _r({"temp_f": 71, "conditions": "partly cloudy"})),
        ("Could you check current conditions for {city} please?",
         {"city": "{city}", "units": "metric"}, _r({"temp_c": 18, "conditions": "overcast"})),
        ("How's the weather over in {city} this morning?",
         {"city": "{city}"}, _r({"temp_f": 49, "conditions": "rain", "wind_mph": 12})),
        ("Pull weather for {city}.",
         {"city": "{city}"}, _r({"temp_f": 88, "conditions": "sunny", "humidity": 35})),
        ("What does it feel like outside in {city}?",
         {"city": "{city}", "units": "imperial"}, _r({"feels_like_f": 31, "actual_f": 38})),
        ("Quick weather check for {city}, thanks.",
         {"city": "{city}"}, _r({"temp_f": 64, "conditions": "fog"})),
        ("Show me the weather in {city}.",
         {"city": "{city}"}, _r({"temp_f": 77, "conditions": "scattered showers"})),
        ("Mind grabbing the current temp and sky in {city}?",
         {"city": "{city}"}, _r({"temp_f": 22, "conditions": "snow", "wind_mph": 18})),
        ("weather {city}",
         {"city": "{city}"}, _r({"temp_f": 95, "conditions": "hot, hazy"})),
        ("Need the weather for {city} for a planning email.",
         {"city": "{city}"}, _r({"temp_f": 60, "conditions": "clear", "humidity": 55})),
        ("Hey can you check {city} weather real quick?",
         {"city": "{city}"}, _r({"temp_f": 41, "conditions": "drizzle"})),
        ("Conditions in {city} at the moment?",
         {"city": "{city}", "units": "metric"}, _r({"temp_c": 27, "conditions": "thunderstorms"})),
    ],

    "get_forecast": [
        ("Give me a 5-day forecast for {city}.",
         {"city": "{city}", "days": 5}, _r({"days": [{"d": 1, "hi": 72, "lo": 55}, {"d": 2, "hi": 68, "lo": 52}]})),
        ("What's the 3-day outlook for {city}?",
         {"city": "{city}", "days": 3}, _r({"days": [{"d": 1, "hi": 80, "lo": 64}]})),
        ("7-day forecast for {city}, please.",
         {"city": "{city}", "days": 7}, _r({"summary": "mild week, rain on day 4-5"})),
        ("Will it rain in {city} this week?",
         {"city": "{city}", "days": 7}, _r({"rain_days": [3, 4]})),
        ("Forecast {city} 10 days out.",
         {"city": "{city}", "days": 10}, _r({"summary": "warming trend, dry"})),
        ("Show me the upcoming weather for {city}.",
         {"city": "{city}", "days": 5}, _r({"avg_hi": 65, "avg_lo": 48})),
        ("How's the weekend looking in {city}?",
         {"city": "{city}", "days": 3}, _r({"sat": "sunny 75", "sun": "cloudy 70"})),
        ("Two-day forecast {city}?",
         {"city": "{city}", "days": 2}, _r({"d1": "rain", "d2": "clearing"})),
        ("Forecast for {city} through next Tuesday.",
         {"city": "{city}", "days": 6}, _r({"trend": "cooling"})),
        ("Will I need an umbrella in {city} tomorrow?",
         {"city": "{city}", "days": 1}, _r({"precip_chance": 80})),
        ("Need the {city} forecast for a trip.",
         {"city": "{city}", "days": 5}, _r({"summary": "stable, mild"})),
        ("Pull a 4-day weather outlook for {city}.",
         {"city": "{city}", "days": 4}, _r({"hi_range": "65-72"})),
        ("How will weather evolve in {city} over the next week?",
         {"city": "{city}", "days": 7}, _r({"summary": "front moving through midweek"})),
    ],

    "geocode_address": [
        ("Geocode this address: {addr}",
         {"address": "{addr}"}, _r({"lat": 37.4220, "lon": -122.0841})),
        ("What are the coordinates for {addr}?",
         {"address": "{addr}"}, _r({"lat": 51.5034, "lon": -0.1276})),
        ("Convert {addr} to lat/lon please.",
         {"address": "{addr}"}, _r({"lat": 40.7484, "lon": -73.9857})),
        ("Find lat/long of {addr}.",
         {"address": "{addr}"}, _r({"lat": 35.6595, "lon": 139.7005})),
        ("Lookup coordinates: {addr}",
         {"address": "{addr}"}, _r({"lat": 48.8584, "lon": 2.2945})),
        ("Geocode {addr}",
         {"address": "{addr}"}, _r({"lat": -33.8915, "lon": 151.2767})),
        ("Where is {addr} on a map?",
         {"address": "{addr}"}, _r({"lat": 52.5163, "lon": 13.3777})),
        ("Need coordinates for {addr}, can you fetch them?",
         {"address": "{addr}"}, _r({"lat": 1.2834, "lon": 103.8607})),
        ("Resolve {addr} to a point.",
         {"address": "{addr}"}, _r({"lat": 19.4326, "lon": -99.1332})),
        ("turn this address into coords: {addr}",
         {"address": "{addr}"}, _r({"lat": 55.7520, "lon": 37.6175})),
        ("Hit the geocoder for {addr}.",
         {"address": "{addr}"}, _r({"lat": 41.8902, "lon": 12.4922})),
        ("Get me precise lat/lon for {addr} for the map pin.",
         {"address": "{addr}"}, _r({"lat": 59.3293, "lon": 18.0686})),
        ("Translate {addr} into geographic coordinates, please.",
         {"address": "{addr}"}, _r({"lat": 25.2048, "lon": 55.2708})),
    ],

    "reverse_geocode": [
        ("What's at lat {lat}, lon {lon}?",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"address": "Empire State Building, NYC"})),
        ("Reverse-geocode {lat},{lon}",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"address": "Pioneer Square, Seattle, WA"})),
        ("What address corresponds to {lat}, {lon}?",
         {"latitude": "{lat}", "longitude": "{lon}"}, _r({"address": "Eiffel Tower, Paris"})),
        ("Looking up the place at {lat}, {lon}.",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"address": "Shinjuku, Tokyo"})),
        ("Which neighborhood is {lat}/{lon} in?",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"neighborhood": "Mission District", "city": "San Francisco"})),
        ("Convert these coords to a street address: {lat}, {lon}",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"address": "12 Rue de Rivoli, Paris"})),
        ("Reverse geocode {lat}, {lon} please.",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"address": "Bondi Beach, Sydney NSW"})),
        ("Where on earth is {lat}, {lon}?",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"city": "Helsinki", "country": "FI"})),
        ("Address at {lat}/{lon}?",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"address": "Marina Bay, Singapore"})),
        ("Tell me what's near {lat}, {lon}.",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"poi": "Central Park"})),
        ("Find a postal address for {lat}, {lon}.",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"address": "221B Baker St, London"})),
        ("Drop a pin at {lat}, {lon} and tell me the area.",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"area": "Capitol Hill, Seattle"})),
        ("What location does {lat}, {lon} resolve to?",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"address": "Plaza de Mayo, Buenos Aires"})),
    ],

    "compute_route": [
        ("Get driving directions from {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "driving"},
         _r({"distance_km": 14.2, "duration_min": 22})),
        ("How do I drive from {addr} to {addr2}?",
         {"from": "{addr}", "to": "{addr2}"},
         _r({"distance_mi": 8.5, "duration_min": 18})),
        ("Plan a walking route between {addr} and {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "walking"},
         _r({"distance_km": 1.4, "duration_min": 19})),
        ("Cycling directions: {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "bicycling"},
         _r({"distance_km": 6.8, "duration_min": 25})),
        ("What's the route from {addr} to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"},
         _r({"distance_km": 22.0, "duration_min": 35, "tolls": True})),
        ("Route me from {addr} to {addr2}, avoiding highways.",
         {"origin": "{addr}", "destination": "{addr2}", "avoid": ["highways"]},
         _r({"distance_km": 19.5, "duration_min": 41})),
        ("Compute fastest route {addr} -> {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "optimize": "time"},
         _r({"duration_min": 27})),
        ("Shortest path from {addr} to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}", "optimize": "distance"},
         _r({"distance_km": 11.1})),
        ("Build a multi-stop route, start {addr}, end {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}"},
         _r({"steps": 7, "duration_min": 33})),
        ("How long to drive from {addr} to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "driving"},
         _r({"duration_min": 52})),
        ("Find a route from {addr} to {addr2} please.",
         {"origin": "{addr}", "destination": "{addr2}"},
         _r({"distance_km": 5.9, "duration_min": 12})),
        ("Walking directions, {addr} to {addr2}, no stairs.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "walking", "avoid": ["stairs"]},
         _r({"duration_min": 23})),
        ("Drive from {addr} to {addr2} avoiding tolls.",
         {"origin": "{addr}", "destination": "{addr2}", "avoid": ["tolls"]},
         _r({"distance_km": 30.4, "duration_min": 45})),
    ],

    "get_timezone": [
        ("What timezone is {city} in?",
         {"location": "{city}"}, _r({"tz": "America/New_York", "utc_offset": -4})),
        ("Tell me the timezone for {city}.",
         {"city": "{city}"}, _r({"tz": "Asia/Tokyo", "utc_offset": 9})),
        ("Which time zone does {city} fall under?",
         {"city": "{city}"}, _r({"tz": "Europe/Berlin"})),
        ("tz for {city}?",
         {"location": "{city}"}, _r({"tz": "Australia/Sydney", "utc_offset": 11})),
        ("Look up {city}'s timezone.",
         {"city": "{city}"}, _r({"tz": "America/Los_Angeles"})),
        ("What's the UTC offset for {city}?",
         {"city": "{city}"}, _r({"tz": "Asia/Singapore", "utc_offset": 8})),
        ("Need timezone of {city} for a meeting invite.",
         {"city": "{city}"}, _r({"tz": "Europe/London", "dst": True})),
        ("Timezone {city}",
         {"location": "{city}"}, _r({"tz": "America/Sao_Paulo"})),
        ("Which TZ database name covers {city}?",
         {"city": "{city}"}, _r({"tz": "Africa/Cairo"})),
        ("get tz {city}",
         {"city": "{city}"}, _r({"tz": "Asia/Kolkata", "utc_offset": 5.5})),
        ("Hey, what timezone is used in {city}?",
         {"city": "{city}"}, _r({"tz": "Pacific/Auckland"})),
        ("I need the timezone identifier for {city}.",
         {"city": "{city}"}, _r({"tz": "Europe/Paris"})),
        ("Locate {city} in the tz database.",
         {"city": "{city}"}, _r({"tz": "America/Mexico_City"})),
    ],

    "convert_timezone": [
        ("Convert {dt} from {tz1} to {tz2}.",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-12T15:00:00", "tz": "Europe/London"})),
        ("What's {dt} {tz1} time in {tz2}?",
         {"datetime": "{dt}", "src_tz": "{tz1}", "dst_tz": "{tz2}"},
         _r({"converted": "2026-05-12T22:00:00"})),
        ("Translate {dt} to {tz2} (originally {tz1}).",
         {"when": "{dt}", "from": "{tz1}", "to": "{tz2}"},
         _r({"local_time": "2026-05-13T01:00:00"})),
        ("Show me {dt} {tz1} in {tz2} terms.",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-12T08:00:00"})),
        ("Convert this timestamp: {dt}, source={tz1}, target={tz2}.",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-13T03:30:00"})),
        ("If it's {dt} in {tz1}, what time is it in {tz2}?",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-12T19:45:00"})),
        ("tz convert: {dt} {tz1} -> {tz2}",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-12T11:15:00"})),
        ("Need {dt} ({tz1}) expressed in {tz2}.",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-12T20:00:00"})),
        ("Move {dt} from {tz1} into {tz2}.",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-13T05:00:00"})),
        ("Time conversion please: {dt} {tz1} into {tz2}.",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-12T14:00:00"})),
        ("Render {dt} from {tz1} as a time in {tz2}.",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-12T17:30:00"})),
        ("Express {dt} {tz1} in {tz2}.",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-12T23:00:00"})),
        ("Map {dt} ({tz1}) onto {tz2}.",
         {"datetime": "{dt}", "from_tz": "{tz1}", "to_tz": "{tz2}"},
         _r({"converted": "2026-05-13T02:30:00"})),
    ],

    "create_calendar_event": [
        ("Create a calendar event titled '{title}' on {dt}.",
         {"title": "{title}", "start": "{dt}", "calendar_id": "{cal}"},
         _r({"event_id": "cal_evt_88123", "status": "created"})),
        ("Schedule '{title}' for {dt}.",
         {"title": "{title}", "start": "{dt}"}, _r({"event_id": "cal_evt_99812"})),
        ("Add an event '{title}' to my {cal} calendar at {dt}.",
         {"title": "{title}", "start": "{dt}", "calendar_id": "{cal}"},
         _r({"event_id": "cal_evt_30457", "status": "ok"})),
        ("Book '{title}' for {dt}, 1 hour.",
         {"title": "{title}", "start": "{dt}", "duration_min": 60},
         _r({"event_id": "cal_evt_47291"})),
        ("Put '{title}' on the calendar at {dt}.",
         {"title": "{title}", "when": "{dt}"}, _r({"event_id": "cal_evt_55039"})),
        ("New event: '{title}', start {dt}.",
         {"title": "{title}", "start": "{dt}"}, _r({"event_id": "cal_evt_70022"})),
        ("Create '{title}' on {dt} on my {cal} calendar.",
         {"title": "{title}", "start": "{dt}", "calendar_id": "{cal}"},
         _r({"event_id": "cal_evt_13384"})),
        ("Schedule a 30-minute '{title}' at {dt}.",
         {"title": "{title}", "start": "{dt}", "duration_min": 30},
         _r({"event_id": "cal_evt_24617"})),
        ("Add '{title}' to my schedule at {dt}.",
         {"title": "{title}", "start": "{dt}"}, _r({"event_id": "cal_evt_36849"})),
        ("Drop a calendar event called '{title}' at {dt}.",
         {"title": "{title}", "start": "{dt}"}, _r({"event_id": "cal_evt_48052"})),
        ("Block {dt} for '{title}' on calendar {cal}.",
         {"title": "{title}", "start": "{dt}", "calendar_id": "{cal}"},
         _r({"event_id": "cal_evt_59285"})),
        ("Make a new event '{title}' starting {dt}.",
         {"title": "{title}", "start": "{dt}"}, _r({"event_id": "cal_evt_60418"})),
        ("Add '{title}' to {cal} calendar for {dt}.",
         {"title": "{title}", "start": "{dt}", "calendar_id": "{cal}"},
         _r({"event_id": "cal_evt_71640"})),
    ],

    "update_event": [
        ("Move {evt} to {dt}.",
         {"event_id": "{evt}", "new_start": "{dt}"}, _r({"status": "updated"})),
        ("Reschedule {evt} for {dt}.",
         {"event_id": "{evt}", "start": "{dt}"}, _r({"status": "rescheduled"})),
        ("Change the title of {evt} to '{title}'.",
         {"event_id": "{evt}", "title": "{title}"}, _r({"status": "ok"})),
        ("Update {evt}: new start {dt}.",
         {"event_id": "{evt}", "start": "{dt}"}, _r({"status": "updated"})),
        ("Push {evt} back by 30 minutes (start now {dt}).",
         {"event_id": "{evt}", "start": "{dt}"}, _r({"status": "moved"})),
        ("Edit {evt} so it begins at {dt}.",
         {"event_id": "{evt}", "start": "{dt}"}, _r({"status": "saved"})),
        ("Patch event {evt}, set title '{title}'.",
         {"event_id": "{evt}", "title": "{title}"}, _r({"status": "patched"})),
        ("Modify {evt} to last 90 minutes.",
         {"event_id": "{evt}", "duration_min": 90}, _r({"status": "ok"})),
        ("Adjust {evt} start to {dt}.",
         {"event_id": "{evt}", "start": "{dt}"}, _r({"status": "updated"})),
        ("Bump {evt} to {dt}.",
         {"event_id": "{evt}", "start": "{dt}"}, _r({"status": "ok"})),
        ("Rename {evt} to '{title}'.",
         {"event_id": "{evt}", "title": "{title}"}, _r({"status": "renamed"})),
        ("Shift {evt} an hour later, new start {dt}.",
         {"event_id": "{evt}", "start": "{dt}"}, _r({"status": "shifted"})),
        ("Update event {evt} with new title '{title}' and start {dt}.",
         {"event_id": "{evt}", "title": "{title}", "start": "{dt}"}, _r({"status": "updated"})),
    ],

    "delete_event": [
        ("Delete event {evt}.",
         {"event_id": "{evt}"}, _r({"status": "deleted"})),
        ("Cancel {evt} please.",
         {"event_id": "{evt}"}, _r({"status": "cancelled"})),
        ("Remove {evt} from my calendar.",
         {"event_id": "{evt}"}, _r({"status": "removed"})),
        ("Drop event {evt}.",
         {"event_id": "{evt}"}, _r({"status": "deleted"})),
        ("Get rid of {evt}.",
         {"event_id": "{evt}"}, _r({"status": "ok"})),
        ("Cancel calendar event {evt}.",
         {"event_id": "{evt}", "notify_attendees": True}, _r({"status": "cancelled"})),
        ("Erase {evt} from the calendar.",
         {"event_id": "{evt}"}, _r({"status": "deleted"})),
        ("Pls delete {evt}.",
         {"event_id": "{evt}"}, _r({"status": "ok"})),
        ("Wipe event {evt}.",
         {"event_id": "{evt}"}, _r({"status": "deleted"})),
        ("Kill {evt}, no longer needed.",
         {"event_id": "{evt}"}, _r({"status": "deleted"})),
        ("Take down event {evt}, send cancellations.",
         {"event_id": "{evt}", "notify_attendees": True}, _r({"status": "cancelled"})),
        ("Pull {evt} off my schedule.",
         {"event_id": "{evt}"}, _r({"status": "removed"})),
        ("Cancel {evt} and notify attendees.",
         {"event_id": "{evt}", "notify_attendees": True}, _r({"status": "cancelled"})),
    ],

    "list_events": [
        ("List my events for today on {cal}.",
         {"calendar_id": "{cal}", "date": "2026-05-08"},
         _r({"events": [{"id": "cal_evt_82873", "title": "Standup"}]})),
        ("Show events between {dt} and the end of that day.",
         {"start": "{dt}", "end": "{dt}"}, _r({"count": 4})),
        ("What's on my {cal} calendar tomorrow?",
         {"calendar_id": "{cal}", "date": "2026-05-09"}, _r({"count": 2})),
        ("List all events for {cal} this week.",
         {"calendar_id": "{cal}", "range": "week"}, _r({"count": 11})),
        ("Pull events from {dt} for me.",
         {"start": "{dt}"}, _r({"events": []})),
        ("Show me my schedule on {cal} for {dt}.",
         {"calendar_id": "{cal}", "date": "{dt}"}, _r({"count": 3})),
        ("What meetings do I have on {cal}?",
         {"calendar_id": "{cal}"}, _r({"count": 7})),
        ("List events for user {user} today.",
         {"user_id": "{user}"}, _r({"count": 5})),
        ("Get my upcoming events on {cal}.",
         {"calendar_id": "{cal}", "limit": 10}, _r({"count": 6})),
        ("Show today's calendar events.",
         {"calendar_id": "primary", "date": "2026-05-08"}, _r({"count": 4})),
        ("List my agenda for {cal} on {dt}.",
         {"calendar_id": "{cal}", "date": "{dt}"}, _r({"count": 2})),
        ("Fetch events from {cal} between now and Friday.",
         {"calendar_id": "{cal}", "range": "until_friday"}, _r({"count": 9})),
        ("Show all of {user}'s events.",
         {"user_id": "{user}"}, _r({"count": 12})),
    ],

    "set_event_reminder": [
        ("Set a 5-minute sms reminder on {evt}.",
         {"event_id": "{evt}", "minutes_before": 5, "method": "sms"}, None),
        ("Add a 15-min email reminder for {evt}.",
         {"event_id": "{evt}", "minutes_before": 15, "method": "email"}, _r({"status": "ok"})),
        ("Remind me 30 minutes before {evt} via push.",
         {"event_id": "{evt}", "minutes_before": 30, "method": "push"}, _r({"status": "set"})),
        ("Add 1 hour reminder to {evt}.",
         {"event_id": "{evt}", "minutes_before": 60}, None),
        ("Remind me about {evt} 10 minutes prior.",
         {"event_id": "{evt}", "minutes_before": 10}, _r({"status": "ok"})),
        ("Set 24-hour email reminder on {evt}.",
         {"event_id": "{evt}", "minutes_before": 1440, "method": "email"}, _r({"status": "set"})),
        ("Push notification 5 min before {evt}.",
         {"event_id": "{evt}", "minutes_before": 5, "method": "push"}, None),
        ("Set a reminder 2 hours before {evt}.",
         {"event_id": "{evt}", "minutes_before": 120}, _r({"status": "ok"})),
        ("Remind me 45 minutes ahead of {evt}, sms.",
         {"event_id": "{evt}", "minutes_before": 45, "method": "sms"}, _r({"status": "set"})),
        ("Add reminder to {evt}: 20 min, push.",
         {"event_id": "{evt}", "minutes_before": 20, "method": "push"}, None),
        ("Quick: 5 minute heads-up before {evt}.",
         {"event_id": "{evt}", "minutes_before": 5}, _r({"status": "ok"})),
        ("Email me 10 mins before {evt}.",
         {"event_id": "{evt}", "minutes_before": 10, "method": "email"}, _r({"status": "set"})),
        ("Set reminder on {evt} for 15 minutes prior.",
         {"event_id": "{evt}", "minutes_before": 15}, None),
    ],

    "find_meeting_slot": [
        ("Find a 30-minute meeting slot for {user} and {user2} this week.",
         {"attendees": ["{user}", "{user2}"], "duration_min": 30},
         _r({"slot": "2026-05-09T14:00:00"})),
        ("When are {user}, {user2}, and {user3} all free for an hour?",
         {"attendees": ["{user}", "{user2}", "{user3}"], "duration_min": 60},
         _r({"slot": "2026-05-10T10:00:00"})),
        ("Suggest a 45-min slot for {user} and {user2} tomorrow.",
         {"attendees": ["{user}", "{user2}"], "duration_min": 45, "date": "2026-05-09"},
         _r({"slot": "2026-05-09T11:30:00"})),
        ("Find common free time for {user} and {user2} on Friday.",
         {"attendees": ["{user}", "{user2}"], "date": "2026-05-09"},
         _r({"slots": ["09:00", "13:30", "16:00"]})),
        ("Schedule a 1-hour sync between {user} and {user2}, soonest.",
         {"attendees": ["{user}", "{user2}"], "duration_min": 60, "earliest": "asap"},
         _r({"slot": "2026-05-09T15:00:00"})),
        ("Find any 30 min window for {user},{user2} next week.",
         {"attendees": ["{user}", "{user2}"], "duration_min": 30, "range": "next_week"},
         _r({"slot": "2026-05-13T09:30:00"})),
        ("When can {user}, {user2}, {user3} meet for 90 minutes?",
         {"attendees": ["{user}", "{user2}", "{user3}"], "duration_min": 90},
         _r({"slot": "2026-05-14T13:00:00"})),
        ("Free slot for {user}+{user2}, 25 min, today.",
         {"attendees": ["{user}", "{user2}"], "duration_min": 25, "date": "2026-05-08"},
         _r({"slot": "2026-05-08T17:00:00"})),
        ("Find a 1-hour overlap between {user} and {user2}.",
         {"attendees": ["{user}", "{user2}"], "duration_min": 60},
         _r({"slot": "2026-05-09T10:00:00"})),
        ("Pick the next free 20 min for {user} and {user2}.",
         {"attendees": ["{user}", "{user2}"], "duration_min": 20},
         _r({"slot": "2026-05-08T16:30:00"})),
        ("Find meeting time, attendees: {user}, {user2}; min 45 minutes.",
         {"attendees": ["{user}", "{user2}"], "duration_min": 45},
         _r({"slot": "2026-05-12T14:00:00"})),
        ("When do {user} and {user2} both have a free hour next week?",
         {"attendees": ["{user}", "{user2}"], "duration_min": 60, "range": "next_week"},
         _r({"slot": "2026-05-13T11:00:00"})),
        ("Suggest meeting times for {user},{user2},{user3}, 30 min, this week.",
         {"attendees": ["{user}", "{user2}", "{user3}"], "duration_min": 30},
         _r({"slot": "2026-05-09T16:00:00"})),
    ],

    "get_holiday_calendar": [
        ("List public holidays in {country} for 2026.",
         {"country": "{country}", "year": 2026},
         _r({"holidays": [{"name": "New Year", "date": "2026-01-01"}]})),
        ("What are the official holidays in {country} this year?",
         {"country": "{country}", "year": 2026}, _r({"count": 11})),
        ("Pull {country}'s 2027 holiday list.",
         {"country": "{country}", "year": 2027}, _r({"count": 13})),
        ("Holidays {country}.",
         {"country_code": "{country}", "year": 2026}, _r({"count": 9})),
        ("Show federal holidays in {country}.",
         {"country": "{country}", "type": "federal", "year": 2026}, _r({"count": 11})),
        ("Bank holidays for {country} 2026?",
         {"country": "{country}", "year": 2026, "type": "bank"}, _r({"count": 8})),
        ("Get me {country}'s observed holidays this year.",
         {"country": "{country}", "year": 2026, "observed": True}, _r({"count": 11})),
        ("Holiday list for {country}.",
         {"country": "{country}"}, _r({"count": 10})),
        ("Public holidays in {country} between Jan and Jun 2026.",
         {"country": "{country}", "start": "2026-01-01", "end": "2026-06-30"}, _r({"count": 5})),
        ("List national holidays for {country}.",
         {"country": "{country}", "scope": "national"}, _r({"count": 12})),
        ("Need the holiday calendar of {country} for planning.",
         {"country": "{country}", "year": 2026}, _r({"count": 11})),
        ("Show statutory holidays in {country}.",
         {"country": "{country}", "type": "statutory", "year": 2026}, _r({"count": 10})),
        ("{country} holidays 2026, please.",
         {"country": "{country}", "year": 2026}, _r({"count": 11})),
    ],

    "get_sunrise_sunset": [
        ("When does the sun rise and set in {city} today?",
         {"city": "{city}", "date": "2026-05-08"},
         _r({"sunrise": "05:42", "sunset": "20:01"})),
        ("Sunrise/sunset times for {city}?",
         {"city": "{city}"}, _r({"sunrise": "06:14", "sunset": "19:33"})),
        ("Sunset in {city} on {dt}?",
         {"city": "{city}", "date": "{dt}"}, _r({"sunset": "21:05"})),
        ("Get sunrise time for {city}.",
         {"location": "{city}"}, _r({"sunrise": "05:30"})),
        ("When's golden hour in {city}?",
         {"city": "{city}", "date": "2026-05-08"},
         _r({"golden_hour_start": "19:18", "golden_hour_end": "20:02"})),
        ("How long is daylight in {city} today?",
         {"city": "{city}", "date": "2026-05-08"}, _r({"daylight_hours": 14.6})),
        ("Need sunrise & sunset for {city}, both.",
         {"city": "{city}"}, _r({"sunrise": "06:00", "sunset": "20:15"})),
        ("Dawn and dusk times in {city}?",
         {"city": "{city}"}, _r({"dawn": "05:12", "dusk": "20:31"})),
        ("Show me sun times for {city}.",
         {"city": "{city}"}, _r({"sunrise": "07:01", "sunset": "17:48"})),
        ("Sunrise tomorrow in {city}.",
         {"city": "{city}", "date": "2026-05-09"}, _r({"sunrise": "05:41"})),
        ("Daylight info for {city} on {dt}.",
         {"city": "{city}", "date": "{dt}"}, _r({"daylight_hours": 12.3})),
        ("When does it get dark in {city} tonight?",
         {"city": "{city}", "date": "2026-05-08"}, _r({"sunset": "20:04", "dusk": "20:34"})),
        ("Sun position info for {city}, please.",
         {"city": "{city}"}, _r({"sunrise": "06:22", "sunset": "19:55"})),
    ],

    "get_moon_phase": [
        ("What's the moon phase tonight in {city}?",
         {"city": "{city}", "date": "2026-05-08"},
         _r({"phase": "waxing gibbous", "illumination": 0.78})),
        ("Moon phase on {dt}?",
         {"date": "{dt}"}, _r({"phase": "full moon"})),
        ("Is the moon full tonight?",
         {"date": "2026-05-08"}, _r({"phase": "waxing gibbous", "illumination": 0.78})),
        ("Get current moon phase.",
         {"date": "2026-05-08"}, _r({"phase": "waxing gibbous"})),
        ("What phase is the moon in over {city}?",
         {"city": "{city}"}, _r({"phase": "first quarter"})),
        ("Moon illumination percent today?",
         {"date": "2026-05-08"}, _r({"illumination": 0.62})),
        ("When's the next full moon?",
         {"after": "2026-05-08"}, _r({"next_full_moon": "2026-05-21"})),
        ("Moon phase on {dt} in {city}.",
         {"city": "{city}", "date": "{dt}"}, _r({"phase": "new moon"})),
        ("How illuminated is the moon tonight?",
         {"date": "2026-05-08"}, _r({"illumination": 0.78})),
        ("Lunar phase for {dt}.",
         {"date": "{dt}"}, _r({"phase": "waning crescent"})),
        ("Moon status now.",
         {"date": "2026-05-08"}, _r({"phase": "waxing gibbous"})),
        ("Phase of moon next Saturday?",
         {"date": "2026-05-16"}, _r({"phase": "full moon"})),
        ("What does the moon look like tonight?",
         {"date": "2026-05-08"}, _r({"phase": "waxing gibbous", "illumination": 0.78})),
    ],

    "get_air_quality": [
        ("Air quality in {city}?",
         {"city": "{city}"}, _r({"aqi": 42, "category": "Good"})),
        ("AQI for {city} please.",
         {"city": "{city}"}, _r({"aqi": 156, "category": "Unhealthy"})),
        ("Is the air clean in {city} today?",
         {"city": "{city}"}, _r({"aqi": 35, "category": "Good"})),
        ("Pollution level in {city}.",
         {"city": "{city}"}, _r({"pm25": 18.4, "aqi": 64})),
        ("Get pm2.5 for {city}.",
         {"city": "{city}", "pollutant": "pm25"}, _r({"pm25": 22.1})),
        ("Air quality reading {city}.",
         {"city": "{city}"}, _r({"aqi": 78, "category": "Moderate"})),
        ("Smog status in {city}?",
         {"city": "{city}"}, _r({"aqi": 105, "category": "Unhealthy for Sensitive Groups"})),
        ("AQI {city}",
         {"location": "{city}"}, _r({"aqi": 51})),
        ("How bad is the air in {city} right now?",
         {"city": "{city}"}, _r({"aqi": 142, "category": "Unhealthy"})),
        ("Air quality index {city}, today.",
         {"city": "{city}", "date": "2026-05-08"}, _r({"aqi": 38})),
        ("Particulate level for {city}.",
         {"city": "{city}"}, _r({"pm25": 9.2, "pm10": 21})),
        ("What's the AQI in {city} this morning?",
         {"city": "{city}"}, _r({"aqi": 62, "category": "Moderate"})),
        ("PM2.5 reading for {city}.",
         {"city": "{city}", "pollutant": "pm25"}, _r({"pm25": 14.3})),
    ],

    "get_uv_index": [
        ("UV index in {city} today?",
         {"city": "{city}"}, _r({"uv_index": 7, "category": "High"})),
        ("How strong is the sun in {city} right now?",
         {"city": "{city}"}, _r({"uv_index": 5})),
        ("Need UV info for {city}.",
         {"city": "{city}"}, _r({"uv_index": 9, "category": "Very High"})),
        ("Will I burn in {city} this afternoon?",
         {"city": "{city}", "time": "afternoon"}, _r({"uv_index": 8, "burn_minutes": 25})),
        ("UV reading {city}",
         {"city": "{city}"}, _r({"uv_index": 3, "category": "Moderate"})),
        ("Get UV index for {city} on {dt}.",
         {"city": "{city}", "date": "{dt}"}, _r({"uv_index": 6})),
        ("How dangerous is the UV today in {city}?",
         {"city": "{city}"}, _r({"uv_index": 11, "category": "Extreme"})),
        ("Solar UV in {city}?",
         {"city": "{city}"}, _r({"uv_index": 4})),
        ("Today's UV peak in {city}.",
         {"city": "{city}"}, _r({"peak_uv": 8, "peak_time": "13:30"})),
        ("Should I wear sunscreen in {city} now?",
         {"city": "{city}"}, _r({"uv_index": 7, "recommend_sunscreen": True})),
        ("UV forecast {city}.",
         {"city": "{city}"}, _r({"uv_index": 6})),
        ("UV strength for {city} please.",
         {"city": "{city}"}, _r({"uv_index": 5, "category": "Moderate"})),
        ("Get me the UV index in {city} at noon.",
         {"city": "{city}", "time": "12:00"}, _r({"uv_index": 9})),
    ],

    "get_traffic": [
        ("How's traffic on the route from {addr} to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"},
         _r({"delay_min": 14, "severity": "moderate"})),
        ("Current traffic between {addr} and {addr2}?",
         {"from": "{addr}", "to": "{addr2}"}, _r({"delay_min": 3})),
        ("Is traffic bad between {addr} and {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"},
         _r({"severity": "heavy", "delay_min": 28})),
        ("Traffic check on {addr} -> {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"severity": "light"})),
        ("Tell me about congestion {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"delay_min": 8})),
        ("Live traffic from {addr} to {addr2}, please.",
         {"origin": "{addr}", "destination": "{addr2}"},
         _r({"current_speed_mph": 22, "free_flow_mph": 55})),
        ("How long with traffic, {addr} to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"duration_min": 41})),
        ("Are there delays on {addr} to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"delay_min": 0})),
        ("Traffic from {addr} -> {addr2} now.",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"severity": "moderate"})),
        ("Pull traffic info {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"delay_min": 19})),
        ("Any accidents between {addr} and {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"incidents": 1, "type": "stalled vehicle"})),
        ("Roadway status, {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"severity": "light"})),
        ("Driving congestion {addr}->{addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"delay_min": 6})),
    ],

    "get_transit_route": [
        ("Find a transit route from {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "transit"},
         _r({"duration_min": 38, "transfers": 1})),
        ("Bus/train directions {addr} -> {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "transit"},
         _r({"steps": ["walk 5min", "bus M14", "subway 6"], "total_min": 45})),
        ("Public transport from {addr} to {addr2}, please.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "transit"},
         _r({"duration_min": 52})),
        ("Subway from {addr} to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "subway"},
         _r({"line": "blue", "duration_min": 22})),
        ("Take transit, {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "transit"},
         _r({"duration_min": 33, "transfers": 0})),
        ("Best transit option {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "transit"},
         _r({"option": "express bus 7", "duration_min": 28})),
        ("How long by bus, {addr} to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "bus"},
         _r({"duration_min": 41})),
        ("Train ride duration {addr} -> {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "train"},
         _r({"duration_min": 19})),
        ("Plan a transit trip from {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "transit"},
         _r({"duration_min": 56, "transfers": 2})),
        ("Need bus directions {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "bus"},
         _r({"line": "44", "duration_min": 35})),
        ("Transit route between {addr} and {addr2}, fewest transfers.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "transit", "optimize": "fewer_transfers"},
         _r({"transfers": 0, "duration_min": 47})),
        ("Public transit, {addr} to {addr2}, leaving now.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "transit", "depart": "now"},
         _r({"duration_min": 39})),
        ("How do I get from {addr} to {addr2} on transit?",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "transit"},
         _r({"steps": 4, "duration_min": 44})),
    ],

    "address_autocomplete": [
        ("Autocomplete this address: '1600 Amph'",
         {"query": "1600 Amph"},
         _r({"suggestions": ["1600 Amphitheatre Pkwy, Mountain View, CA"]})),
        ("Suggest completions for '350 5th'.",
         {"query": "350 5th"}, _r({"suggestions": ["350 5th Ave, New York"]})),
        ("Address autocomplete for '10 Down'.",
         {"query": "10 Down"}, _r({"suggestions": ["10 Downing St, London"]})),
        ("Help me complete: 'Friedrich' (street).",
         {"query": "Friedrich", "type": "street"},
         _r({"suggestions": ["Friedrichstrasse, Berlin"]})),
        ("Find addresses starting with 'Bondi'.",
         {"query": "Bondi"}, _r({"suggestions": ["Bondi Beach, Sydney NSW"]})),
        ("Autocomplete '1 Apple'.",
         {"query": "1 Apple"}, _r({"suggestions": ["1 Apple Park Way, Cupertino, CA"]})),
        ("What addresses match 'Champs'?",
         {"query": "Champs"}, _r({"suggestions": ["Champs-Elysees, Paris"]})),
        ("Suggest address for query 'Plaza Mayor'.",
         {"query": "Plaza Mayor"}, _r({"suggestions": ["Plaza Mayor, Madrid"]})),
        ("Autocomplete: 'Penn Stat'.",
         {"query": "Penn Stat"}, _r({"suggestions": ["Penn Station, New York"]})),
        ("Try address autocomplete for 'Marina B'.",
         {"query": "Marina B"}, _r({"suggestions": ["Marina Bay, Singapore"]})),
        ("Address suggestions starting with 'Gare'.",
         {"query": "Gare"}, _r({"suggestions": ["Gare du Nord, Paris", "Gare de Lyon, Paris"]})),
        ("Looking for address completions for 'Avenida Paul'.",
         {"query": "Avenida Paul"}, _r({"suggestions": ["Avenida Paulista, Sao Paulo"]})),
        ("Autocomplete '221B Bak'.",
         {"query": "221B Bak"}, _r({"suggestions": ["221B Baker St, London"]})),
    ],

    "place_search": [
        ("Find coffee shops near {addr}.",
         {"query": "coffee", "near": "{addr}", "radius_m": 1000},
         _r({"results": [{"name": "Bluestone Lane", "dist_m": 240}]})),
        ("Search for pizza places near {addr}.",
         {"query": "pizza", "near": "{addr}"}, _r({"count": 7})),
        ("Pharmacies within 500m of {addr}?",
         {"query": "pharmacy", "near": "{addr}", "radius_m": 500},
         _r({"count": 3})),
        ("Find ATMs near {addr}.",
         {"query": "ATM", "near": "{addr}"}, _r({"count": 5})),
        ("Search 'gym' close to {addr}.",
         {"query": "gym", "near": "{addr}", "radius_m": 1500}, _r({"count": 4})),
        ("Where can I get sushi near {addr}?",
         {"query": "sushi", "near": "{addr}"}, _r({"count": 6})),
        ("Bookstores near {addr}, please.",
         {"query": "bookstore", "near": "{addr}"}, _r({"count": 2})),
        ("Find me a hardware store close to {addr}.",
         {"query": "hardware store", "near": "{addr}"}, _r({"count": 3})),
        ("Search restaurants near {addr}, vegan.",
         {"query": "vegan restaurant", "near": "{addr}"}, _r({"count": 5})),
        ("Look for parks near {addr}.",
         {"query": "park", "near": "{addr}"}, _r({"count": 4})),
        ("Hotels close to {addr}, ranked by rating.",
         {"query": "hotel", "near": "{addr}", "sort": "rating"}, _r({"count": 8})),
        ("Search for laundromats around {addr}.",
         {"query": "laundromat", "near": "{addr}"}, _r({"count": 2})),
        ("Find museums near {addr}.",
         {"query": "museum", "near": "{addr}"}, _r({"count": 6})),
    ],

    "distance_matrix": [
        ("Compute distance matrix between {addr}, {addr2}, and {addr3}.",
         {"points": ["{addr}", "{addr2}", "{addr3}"]},
         _r({"matrix": [[0, 4.2, 8.7], [4.2, 0, 5.1], [8.7, 5.1, 0]]})),
        ("Pairwise distances for {addr}, {addr2}, {addr3}.",
         {"locations": ["{addr}", "{addr2}", "{addr3}"]},
         _r({"matrix_km": [[0, 12, 25], [12, 0, 14], [25, 14, 0]]})),
        ("Distance matrix km, {addr} and {addr2} and {addr3}.",
         {"points": ["{addr}", "{addr2}", "{addr3}"], "units": "km"},
         _r({"shape": [3, 3]})),
        ("Build distances among {addr}, {addr2}, {addr3} by car.",
         {"points": ["{addr}", "{addr2}", "{addr3}"], "mode": "driving"},
         _r({"all_pairs": True})),
        ("All-pairs travel time {addr},{addr2},{addr3}.",
         {"points": ["{addr}", "{addr2}", "{addr3}"], "metric": "duration"},
         _r({"shape": [3, 3]})),
        ("How far apart are {addr}, {addr2}, {addr3}?",
         {"points": ["{addr}", "{addr2}", "{addr3}"]},
         _r({"summary": "computed"})),
        ("Distance matrix for these three: {addr}, {addr2}, {addr3}, walking.",
         {"points": ["{addr}", "{addr2}", "{addr3}"], "mode": "walking"},
         _r({"shape": [3, 3]})),
        ("Compute matrix transit-mode {addr},{addr2},{addr3}.",
         {"points": ["{addr}", "{addr2}", "{addr3}"], "mode": "transit"},
         _r({"shape": [3, 3]})),
        ("Distance grid {addr}, {addr2}, {addr3}, miles.",
         {"points": ["{addr}", "{addr2}", "{addr3}"], "units": "mi"},
         _r({"shape": [3, 3]})),
        ("Pairwise driving distances {addr}, {addr2}, {addr3}.",
         {"locations": ["{addr}", "{addr2}", "{addr3}"], "mode": "driving"},
         _r({"shape": [3, 3]})),
        ("Get me a 3x3 distance matrix for {addr},{addr2},{addr3}.",
         {"points": ["{addr}", "{addr2}", "{addr3}"]}, _r({"shape": [3, 3]})),
        ("Distances between three points: {addr}, {addr2}, {addr3}.",
         {"points": ["{addr}", "{addr2}", "{addr3}"]}, _r({"shape": [3, 3]})),
        ("Build a travel-time matrix {addr},{addr2},{addr3}.",
         {"points": ["{addr}", "{addr2}", "{addr3}"], "metric": "duration"}, _r({"shape": [3, 3]})),
    ],

    "eta_lookup": [
        ("ETA from {addr} to {addr2} right now?",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"eta_min": 24})),
        ("How long until I arrive at {addr2} from {addr}?",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"eta_min": 18})),
        ("Get ETA: {addr} -> {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"eta_min": 11})),
        ("Estimated arrival from {addr} to {addr2}, leaving in 10 min.",
         {"origin": "{addr}", "destination": "{addr2}", "depart_in_min": 10},
         _r({"arrive_at": "2026-05-08T16:42:00"})),
        ("Time to drive from {addr} to {addr2} now?",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "driving"}, _r({"eta_min": 33})),
        ("If I leave now from {addr}, when will I get to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}", "depart": "now"},
         _r({"arrive_at": "2026-05-08T17:05:00"})),
        ("ETA driving {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "mode": "driving"}, _r({"eta_min": 19})),
        ("How quickly can I get from {addr} to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"eta_min": 14})),
        ("Compute ETA for the trip {addr} -> {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"eta_min": 28})),
        ("ETA please, {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"eta_min": 22})),
        ("Driving ETA, leaving 8am, {addr} to {addr2}.",
         {"origin": "{addr}", "destination": "{addr2}", "depart": "08:00"}, _r({"eta_min": 35})),
        ("Predict arrival, {addr}->{addr2}, current traffic.",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"eta_min": 40})),
        ("ETA from {addr} to {addr2} for a 5pm meeting.",
         {"origin": "{addr}", "destination": "{addr2}", "arrive_by": "17:00"},
         _r({"depart_at": "2026-05-08T16:30:00"})),
    ],

    "geofence_alert": [
        ("Set a geofence alert when {user} enters {city}.",
         {"user_id": "{user}", "region": "{city}", "trigger": "enter"},
         _r({"fence_id": "gf_4421", "status": "armed"})),
        ("Notify me when {user} leaves {city}.",
         {"user_id": "{user}", "region": "{city}", "trigger": "exit"},
         _r({"fence_id": "gf_4422"})),
        ("Geofence: alert if {user} crosses into {city}.",
         {"user_id": "{user}", "region": "{city}", "trigger": "enter"},
         _r({"fence_id": "gf_4423", "status": "ok"})),
        ("Add geofence around {addr} radius 500m for {user}.",
         {"user_id": "{user}", "center": "{addr}", "radius_m": 500},
         _r({"fence_id": "gf_4424"})),
        ("Watch for {user} entering {city}, alert me.",
         {"user_id": "{user}", "region": "{city}", "trigger": "enter"},
         _r({"fence_id": "gf_4425"})),
        ("Set up geofence trigger when {user} arrives at {addr}.",
         {"user_id": "{user}", "center": "{addr}", "radius_m": 200, "trigger": "enter"},
         _r({"fence_id": "gf_4426"})),
        ("Geofence alert {user}, region {city}, both enter+exit.",
         {"user_id": "{user}", "region": "{city}", "trigger": "both"},
         _r({"fence_id": "gf_4427"})),
        ("If {user} leaves a 1km zone around {addr}, ping me.",
         {"user_id": "{user}", "center": "{addr}", "radius_m": 1000, "trigger": "exit"},
         _r({"fence_id": "gf_4428"})),
        ("Add geofence: {user} entering {city}.",
         {"user_id": "{user}", "region": "{city}", "trigger": "enter"},
         _r({"fence_id": "gf_4429"})),
        ("Geofence trigger: notify when {user} is near {addr}.",
         {"user_id": "{user}", "center": "{addr}", "radius_m": 250},
         _r({"fence_id": "gf_4430"})),
        ("Set geofence for {user} around {city}.",
         {"user_id": "{user}", "region": "{city}"}, _r({"fence_id": "gf_4431"})),
        ("Alert me on {user} entering region {city}.",
         {"user_id": "{user}", "region": "{city}", "trigger": "enter"},
         _r({"fence_id": "gf_4432"})),
        ("Create geofence: 300m around {addr}, watch {user}.",
         {"user_id": "{user}", "center": "{addr}", "radius_m": 300}, _r({"fence_id": "gf_4433"})),
    ],

    "search_flights": [
        ("Search flights from {city} to {city2} on {dt}.",
         {"origin": "{city}", "destination": "{city2}", "depart": "{dt}"},
         _r({"results": 18, "cheapest_usd": 312})),
        ("Find cheapest flights {city} -> {city2}, {dt}.",
         {"origin": "{city}", "destination": "{city2}", "date": "{dt}", "sort": "price"},
         _r({"cheapest_usd": 198})),
        ("One-way {city} to {city2} on {dt}, please.",
         {"from": "{city}", "to": "{city2}", "depart": "{dt}", "trip_type": "oneway"},
         _r({"results": 12})),
        ("Round trip {city} <-> {city2}, depart {dt}.",
         {"origin": "{city}", "destination": "{city2}", "depart": "{dt}", "trip_type": "round"},
         _r({"results": 22})),
        ("Show flights from {city} to {city2} that day.",
         {"origin": "{city}", "destination": "{city2}", "date": "{dt}"}, _r({"results": 9})),
        ("Look up airfare {city} -> {city2}, {dt}.",
         {"origin": "{city}", "destination": "{city2}", "depart": "{dt}"}, _r({"min_usd": 240})),
        ("Search direct flights only, {city} to {city2}, {dt}.",
         {"origin": "{city}", "destination": "{city2}", "depart": "{dt}", "non_stop": True},
         _r({"results": 4})),
        ("Find flights {city} -> {city2}, leaving {dt}, 2 passengers.",
         {"origin": "{city}", "destination": "{city2}", "depart": "{dt}", "passengers": 2},
         _r({"results": 16})),
        ("Pull flight options {city} to {city2} {dt}.",
         {"origin": "{city}", "destination": "{city2}", "depart": "{dt}"}, _r({"results": 21})),
        ("Cheapest fares {city} -> {city2} {dt}, business class.",
         {"origin": "{city}", "destination": "{city2}", "depart": "{dt}", "cabin": "business"},
         _r({"min_usd": 1840})),
        ("Flight search {city} to {city2} {dt} morning.",
         {"origin": "{city}", "destination": "{city2}", "depart": "{dt}", "time_window": "morning"},
         _r({"results": 7})),
        ("Find me a flight from {city} to {city2} on {dt}.",
         {"origin": "{city}", "destination": "{city2}", "depart": "{dt}"}, _r({"results": 14})),
        ("Search airline tickets {city}->{city2} for {dt}.",
         {"origin": "{city}", "destination": "{city2}", "depart": "{dt}"}, _r({"results": 11})),
    ],

    "get_flight_status": [
        ("What's the status of flight {flight}?",
         {"flight_number": "{flight}"}, _r({"status": "on time", "gate": "B14"})),
        ("Is {flight} delayed?",
         {"flight_number": "{flight}"}, _r({"status": "delayed", "delay_min": 35})),
        ("Lookup flight {flight}.",
         {"flight": "{flight}"}, _r({"status": "departed", "actual_dep": "08:42"})),
        ("Flight {flight} status?",
         {"flight": "{flight}"}, _r({"status": "boarding", "gate": "C22"})),
        ("Where is flight {flight}?",
         {"flight": "{flight}"}, _r({"position": "in-flight", "altitude_ft": 36000})),
        ("Has flight {flight} arrived?",
         {"flight": "{flight}"}, _r({"status": "landed", "actual_arr": "13:02"})),
        ("Check {flight}.",
         {"flight_number": "{flight}"}, _r({"status": "scheduled"})),
        ("Live status of {flight}?",
         {"flight": "{flight}"}, _r({"status": "on time"})),
        ("Pull current info on {flight}.",
         {"flight": "{flight}"}, _r({"status": "delayed", "new_dep": "11:05"})),
        ("Did {flight} leave on time?",
         {"flight": "{flight}"}, _r({"on_time_dep": True, "actual_dep": "07:58"})),
        ("Get flight {flight} latest status.",
         {"flight_number": "{flight}"}, _r({"status": "diverted", "to": "ORD"})),
        ("ETA of flight {flight}?",
         {"flight": "{flight}"}, _r({"eta": "14:25", "status": "on time"})),
        ("Tell me about flight {flight}'s situation.",
         {"flight": "{flight}"}, _r({"status": "cancelled", "reason": "weather"})),
    ],

    "get_pollen_count": [
        ("Pollen count in {city} today?",
         {"city": "{city}"}, _r({"index": 7.4, "category": "High"})),
        ("Allergy levels {city}.",
         {"city": "{city}"}, _r({"tree": 8, "grass": 4, "weed": 2})),
        ("How bad is pollen in {city}?",
         {"city": "{city}"}, _r({"index": 9, "category": "Very High"})),
        ("Get tree pollen for {city}.",
         {"city": "{city}", "type": "tree"}, _r({"value": 6.1})),
        ("Pollen forecast {city}, 3 days.",
         {"city": "{city}", "days": 3}, _r({"trend": "rising"})),
        ("Allergen index in {city}.",
         {"city": "{city}"}, _r({"index": 5.2})),
        ("Will allergies be bad in {city} tomorrow?",
         {"city": "{city}", "date": "2026-05-09"}, _r({"index": 8})),
        ("Grass pollen level {city}.",
         {"city": "{city}", "type": "grass"}, _r({"value": 7.5})),
        ("Need pollen info {city} for asthma planning.",
         {"city": "{city}"}, _r({"index": 6})),
        ("Pollen reading in {city}, please.",
         {"city": "{city}"}, _r({"index": 4.8, "category": "Moderate"})),
        ("Today's allergens for {city}.",
         {"city": "{city}"}, _r({"top_allergen": "oak"})),
        ("Allergy index {city} this morning.",
         {"city": "{city}"}, _r({"index": 7.0})),
        ("Pollen count near {city}.",
         {"city": "{city}", "radius_km": 50}, _r({"index": 5.5})),
    ],

    "get_radar_image": [
        ("Get the weather radar image for {city}.",
         {"city": "{city}"}, _r({"url": "https://radar.example.com/img/abc.png"})),
        ("Show me radar over {city}, last hour.",
         {"city": "{city}", "window_min": 60}, _r({"frames": 12})),
        ("Pull a precipitation radar for {city}.",
         {"city": "{city}", "layer": "precipitation"}, _r({"url": "https://r.example/p.png"})),
        ("Animated radar loop for {city}, please.",
         {"city": "{city}", "animated": True}, _r({"url": "https://r.example/loop.gif"})),
        ("Storm radar near {city}?",
         {"city": "{city}", "layer": "storm"}, _r({"storms_detected": 2})),
        ("Need radar imagery centered on {city}.",
         {"city": "{city}"}, _r({"url": "https://r.example/r.png"})),
        ("Doppler radar map for {city}.",
         {"city": "{city}", "type": "doppler"}, _r({"url": "https://r.example/d.png"})),
        ("Recent radar for {city}.",
         {"city": "{city}"}, _r({"url": "https://r.example/recent.png"})),
        ("Lightning radar around {city}?",
         {"city": "{city}", "layer": "lightning"}, _r({"strikes_30min": 14})),
        ("Get static radar PNG for {city}.",
         {"city": "{city}", "format": "png"}, _r({"url": "https://r.example/p2.png"})),
        ("Radar coverage {city}, 2-hour loop.",
         {"city": "{city}", "window_min": 120, "animated": True}, _r({"frames": 24})),
        ("Show me snowfall radar for {city}.",
         {"city": "{city}", "layer": "snow"}, _r({"url": "https://r.example/s.png"})),
        ("Pull radar image, {city}, latest frame.",
         {"city": "{city}"}, _r({"url": "https://r.example/latest.png"})),
    ],

    "get_marine_forecast": [
        ("Marine forecast off {city} coast?",
         {"city": "{city}"}, _r({"wave_height_m": 1.4, "wind_kn": 15})),
        ("Sea conditions near {city}.",
         {"city": "{city}"}, _r({"swell_m": 1.0, "period_s": 9})),
        ("Boating forecast for {city}.",
         {"city": "{city}", "type": "small_craft"}, _r({"advisory": False})),
        ("How are the waves at {city} beach?",
         {"city": "{city}"}, _r({"wave_height_m": 0.8})),
        ("Marine outlook {city}, 24h.",
         {"city": "{city}", "hours": 24}, _r({"summary": "calm to moderate"})),
        ("Wind/wave near {city} for sailing.",
         {"city": "{city}"}, _r({"wind_kn": 12, "wave_m": 1.2})),
        ("Tide and surf {city}.",
         {"city": "{city}"}, _r({"tide_m": 0.6, "surf_ft": 3})),
        ("Get marine forecast for the waters near {city}.",
         {"city": "{city}"}, _r({"sea_state": "moderate"})),
        ("Wave heights {city}, 12h.",
         {"city": "{city}", "hours": 12}, _r({"max_m": 1.6})),
        ("Coastal weather around {city}, please.",
         {"city": "{city}"}, _r({"summary": "fog dispersing midday"})),
        ("Surf report {city}.",
         {"city": "{city}"}, _r({"surf_ft": 5, "period_s": 11})),
        ("Marine wind forecast near {city}.",
         {"city": "{city}", "type": "wind"}, _r({"wind_kn": 18, "gusts_kn": 25})),
        ("Get sea state for {city} waters.",
         {"city": "{city}"}, _r({"sea_state": "rough"})),
    ],

    "find_nearby_charging": [
        ("Find EV charging stations near {addr}.",
         {"near": "{addr}", "radius_m": 5000}, _r({"count": 8})),
        ("EV chargers around {addr}, please.",
         {"near": "{addr}"}, _r({"count": 5})),
        ("Looking for a Tesla supercharger close to {addr}.",
         {"near": "{addr}", "network": "tesla"}, _r({"count": 2})),
        ("Where can I charge my EV near {addr}?",
         {"near": "{addr}"}, _r({"closest_km": 0.8})),
        ("Find DC fast chargers within 10km of {addr}.",
         {"near": "{addr}", "radius_m": 10000, "type": "dc_fast"}, _r({"count": 3})),
        ("Closest CCS charger to {addr}?",
         {"near": "{addr}", "connector": "ccs"}, _r({"closest_km": 1.4})),
        ("EV station search around {addr}.",
         {"near": "{addr}"}, _r({"count": 6})),
        ("Need 50kW+ chargers near {addr}.",
         {"near": "{addr}", "min_kw": 50}, _r({"count": 4})),
        ("Where's the nearest charging point to {addr}?",
         {"near": "{addr}", "limit": 1}, _r({"name": "EVgo Mall #14"})),
        ("Find chargers near {addr}, available now.",
         {"near": "{addr}", "available_now": True}, _r({"count": 2})),
        ("Hunt for J1772 chargers near {addr}.",
         {"near": "{addr}", "connector": "j1772"}, _r({"count": 3})),
        ("EV charging points within 2 miles of {addr}.",
         {"near": "{addr}", "radius_mi": 2}, _r({"count": 5})),
        ("List chargers around {addr}.",
         {"near": "{addr}"}, _r({"count": 7})),
    ],

    "get_parking_availability": [
        ("Find available parking near {addr}.",
         {"near": "{addr}", "radius_m": 800}, _r({"available": 32, "lots": 3})),
        ("Parking spots open at {addr}?",
         {"location": "{addr}"}, _r({"available": 0, "full": True})),
        ("Garages near {addr} with space?",
         {"near": "{addr}", "type": "garage"}, _r({"count": 2})),
        ("Real-time parking availability around {addr}.",
         {"near": "{addr}"}, _r({"summary": "moderate availability"})),
        ("On-street parking near {addr}, free?",
         {"near": "{addr}", "free_only": True}, _r({"count": 5})),
        ("How many parking spots free at {addr}?",
         {"location": "{addr}"}, _r({"available": 18})),
        ("Parking lot status {addr}.",
         {"location": "{addr}"}, _r({"available": 7, "capacity": 200})),
        ("Find paid parking near {addr}.",
         {"near": "{addr}", "type": "paid"}, _r({"count": 4})),
        ("Show parking with EV chargers near {addr}.",
         {"near": "{addr}", "ev_charger": True}, _r({"count": 1})),
        ("Where can I park near {addr} right now?",
         {"near": "{addr}", "available_now": True}, _r({"count": 3})),
        ("Parking near {addr} under $10.",
         {"near": "{addr}", "max_price_usd": 10}, _r({"count": 2})),
        ("Free street parking close to {addr}?",
         {"near": "{addr}", "free_only": True, "type": "street"}, _r({"count": 6})),
        ("Hourly parking availability near {addr}.",
         {"near": "{addr}", "billing": "hourly"}, _r({"count": 3})),
    ],

    "subscribe_weather_alerts": [
        ("Subscribe me to severe weather alerts for {city}.",
         {"city": "{city}", "severity": "severe"}, _r({"sub_id": "wa_881", "status": "active"})),
        ("Sign me up for storm alerts in {city}.",
         {"city": "{city}", "type": "storm"}, _r({"sub_id": "wa_882"})),
        ("Watch for tornado warnings around {city}.",
         {"city": "{city}", "type": "tornado"}, _r({"sub_id": "wa_883"})),
        ("Add weather alert subscription, {city}, push.",
         {"city": "{city}", "channel": "push"}, _r({"sub_id": "wa_884"})),
        ("Notify me of any NWS warning in {city}.",
         {"city": "{city}", "agency": "NWS"}, _r({"sub_id": "wa_885"})),
        ("Subscribe to flood alerts for {city}.",
         {"city": "{city}", "type": "flood"}, _r({"sub_id": "wa_886"})),
        ("Set up heat-wave notifications in {city}.",
         {"city": "{city}", "type": "heat"}, _r({"sub_id": "wa_887"})),
        ("Email me about weather emergencies in {city}.",
         {"city": "{city}", "channel": "email"}, _r({"sub_id": "wa_888"})),
        ("Subscribe weather alerts {city}, all severities.",
         {"city": "{city}", "severity": "all"}, _r({"sub_id": "wa_889"})),
        ("Push severe weather pings for {city}, please.",
         {"city": "{city}", "channel": "push", "severity": "severe"}, _r({"sub_id": "wa_890"})),
        ("Hurricane alerts for {city}.",
         {"city": "{city}", "type": "hurricane"}, _r({"sub_id": "wa_891"})),
        ("Sign up: snow advisories in {city}.",
         {"city": "{city}", "type": "snow"}, _r({"sub_id": "wa_892"})),
        ("Add me to {city}'s severe weather alerting system.",
         {"city": "{city}"}, _r({"sub_id": "wa_893"})),
    ],

    "compute_isochrone": [
        ("Build a 30-minute drive isochrone from {addr}.",
         {"origin": "{addr}", "minutes": 30, "mode": "driving"},
         _r({"polygon_points": 47})),
        ("Walking isochrone, 15 min from {addr}.",
         {"origin": "{addr}", "minutes": 15, "mode": "walking"},
         _r({"area_km2": 1.2})),
        ("How far can I get in 20 min by transit from {addr}?",
         {"origin": "{addr}", "minutes": 20, "mode": "transit"}, _r({"area_km2": 8.5})),
        ("Compute drive-time polygon, 45 min, from {addr}.",
         {"origin": "{addr}", "minutes": 45, "mode": "driving"}, _r({"area_km2": 312})),
        ("Cycling reachable area, 25 min, from {addr}.",
         {"origin": "{addr}", "minutes": 25, "mode": "bicycling"}, _r({"area_km2": 14})),
        ("Make an isochrone, 10 min walk from {addr}.",
         {"origin": "{addr}", "minutes": 10, "mode": "walking"}, _r({"area_km2": 0.6})),
        ("60-min driving isochrone from {addr}.",
         {"origin": "{addr}", "minutes": 60, "mode": "driving"}, _r({"area_km2": 720})),
        ("Where can I reach in 5 min walk from {addr}?",
         {"origin": "{addr}", "minutes": 5, "mode": "walking"}, _r({"area_km2": 0.18})),
        ("Compute isochrones for 10/20/30 min, walking, from {addr}.",
         {"origin": "{addr}", "minutes": [10, 20, 30], "mode": "walking"}, _r({"bands": 3})),
        ("Drive-time map, 90 min, {addr}.",
         {"origin": "{addr}", "minutes": 90, "mode": "driving"}, _r({"area_km2": 1850})),
        ("Reach polygon, 15 min by car, from {addr}.",
         {"origin": "{addr}", "minutes": 15, "mode": "driving"}, _r({"area_km2": 38})),
        ("Build a transit reachability map from {addr} for 40 min.",
         {"origin": "{addr}", "minutes": 40, "mode": "transit"}, _r({"area_km2": 27})),
        ("How big is the 30 min cycling area from {addr}?",
         {"origin": "{addr}", "minutes": 30, "mode": "bicycling"}, _r({"area_km2": 22})),
    ],

    "get_elevation": [
        ("Elevation at lat {lat}, lon {lon}?",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"elevation_m": 412})),
        ("Get elevation for {addr}.",
         {"address": "{addr}"}, _r({"elevation_m": 27})),
        ("How high is {city} above sea level?",
         {"city": "{city}"}, _r({"elevation_m": 1520})),
        ("Elevation at coordinates {lat},{lon}.",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"elevation_m": 88})),
        ("Lookup terrain height at {lat}/{lon}.",
         {"latitude": "{lat}", "longitude": "{lon}"}, _r({"elevation_m": 2104})),
        ("What's the altitude at {addr}?",
         {"address": "{addr}"}, _r({"elevation_m": 4})),
        ("Elevation profile point: {lat}, {lon}.",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"elevation_m": 612})),
        ("Get height above mean sea level, {city}.",
         {"city": "{city}"}, _r({"elevation_m": 320})),
        ("Altitude at {lat}/{lon}, meters.",
         {"lat": "{lat}", "lon": "{lon}", "units": "m"}, _r({"elevation_m": 1402})),
        ("Tell me elevation at {addr}.",
         {"address": "{addr}"}, _r({"elevation_m": 92})),
        ("How tall is the terrain at {lat},{lon}?",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"elevation_m": 75})),
        ("Elevation reading {addr}.",
         {"address": "{addr}"}, _r({"elevation_m": 245})),
        ("MSL height at {lat}, {lon}.",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"elevation_m": 1180})),
    ],

    "calc_solar_noon": [
        ("When is solar noon in {city} today?",
         {"city": "{city}", "date": "2026-05-08"}, _r({"solar_noon": "12:53"})),
        ("Solar noon for {city} on {dt}?",
         {"city": "{city}", "date": "{dt}"}, _r({"solar_noon": "12:11"})),
        ("Compute solar noon at {city}.",
         {"city": "{city}"}, _r({"solar_noon": "13:02"})),
        ("Local apparent noon in {city}?",
         {"city": "{city}"}, _r({"solar_noon": "12:48"})),
        ("Solar zenith time {city}.",
         {"city": "{city}"}, _r({"solar_noon": "12:59"})),
        ("Sun-highest time for {city} today.",
         {"city": "{city}", "date": "2026-05-08"}, _r({"solar_noon": "12:46"})),
        ("Solar noon, {city}, next Saturday.",
         {"city": "{city}", "date": "2026-05-16"}, _r({"solar_noon": "12:51"})),
        ("Get solar noon at lat {lat}, lon {lon}.",
         {"lat": "{lat}", "lon": "{lon}"}, _r({"solar_noon": "12:33"})),
        ("Solar noon (local time) for {city}.",
         {"city": "{city}"}, _r({"solar_noon": "12:55"})),
        ("Find the moment the sun is highest over {city}.",
         {"city": "{city}"}, _r({"solar_noon": "12:42"})),
        ("Solar transit time {city}.",
         {"city": "{city}"}, _r({"solar_noon": "12:50"})),
        ("Compute when sun crosses meridian at {city}.",
         {"city": "{city}"}, _r({"solar_noon": "13:08"})),
        ("Local solar noon for {city} on {dt}.",
         {"city": "{city}", "date": "{dt}"}, _r({"solar_noon": "12:37"})),
    ],

    "find_optimal_route": [
        ("Optimize route through {addr}, {addr2}, {addr3}.",
         {"waypoints": ["{addr}", "{addr2}", "{addr3}"]},
         _r({"order": [0, 2, 1], "total_min": 47})),
        ("Best order to visit these stops: {addr}, {addr2}, {addr3}?",
         {"stops": ["{addr}", "{addr2}", "{addr3}"]},
         _r({"order": [0, 1, 2], "total_km": 22.4})),
        ("TSP-style route, start={addr}, visit {addr2}, {addr3}.",
         {"start": "{addr}", "stops": ["{addr2}", "{addr3}"]},
         _r({"order": [0, 1], "total_min": 35})),
        ("Optimize for shortest total distance: {addr},{addr2},{addr3}.",
         {"waypoints": ["{addr}", "{addr2}", "{addr3}"], "optimize": "distance"},
         _r({"total_km": 18.2})),
        ("Plan an efficient delivery loop: {addr}, {addr2}, {addr3}.",
         {"waypoints": ["{addr}", "{addr2}", "{addr3}"], "loop": True},
         _r({"total_min": 52})),
        ("Optimal sequence visiting {addr}, {addr2}, {addr3}.",
         {"waypoints": ["{addr}", "{addr2}", "{addr3}"]}, _r({"order": [2, 0, 1]})),
        ("Find best route for stops {addr}+{addr2}+{addr3}.",
         {"stops": ["{addr}", "{addr2}", "{addr3}"]}, _r({"total_min": 41})),
        ("Reorder stops to minimize time: {addr}, {addr2}, {addr3}.",
         {"stops": ["{addr}", "{addr2}", "{addr3}"], "optimize": "time"}, _r({"total_min": 38})),
        ("Solve TSP small for {addr},{addr2},{addr3}.",
         {"waypoints": ["{addr}", "{addr2}", "{addr3}"]}, _r({"order": [1, 2, 0]})),
        ("Optimize multi-stop trip {addr},{addr2},{addr3}.",
         {"waypoints": ["{addr}", "{addr2}", "{addr3}"]}, _r({"total_km": 31.7})),
        ("Best ordering: {addr}, {addr2}, {addr3}, returning to start.",
         {"waypoints": ["{addr}", "{addr2}", "{addr3}"], "loop": True}, _r({"total_km": 24.5})),
        ("Sequence these by drive time: {addr}, {addr2}, {addr3}.",
         {"stops": ["{addr}", "{addr2}", "{addr3}"], "optimize": "time"}, _r({"order": [0, 2, 1]})),
        ("Pick optimal visit order, points {addr}, {addr2}, {addr3}.",
         {"waypoints": ["{addr}", "{addr2}", "{addr3}"]}, _r({"order": [0, 1, 2]})),
    ],

    "set_recurring_event": [
        ("Schedule a weekly standup '{title}' on Mondays at {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=WEEKLY;BYDAY=MO"},
         _r({"event_id": "cal_evt_15238"})),
        ("Add recurring '{title}', daily at {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=DAILY"},
         _r({"event_id": "cal_evt_26461"})),
        ("Make '{title}' a weekly recurring event starting {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=WEEKLY"},
         _r({"event_id": "cal_evt_37694"})),
        ("Recurring event {title}, every other Friday from {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=WEEKLY;INTERVAL=2;BYDAY=FR"},
         _r({"event_id": "cal_evt_48927"})),
        ("Monthly '{title}' on first Monday, starting {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=MONTHLY;BYDAY=1MO"},
         _r({"event_id": "cal_evt_50150"})),
        ("Add daily standup '{title}' at {dt} weekdays only.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR"},
         _r({"event_id": "cal_evt_61383"})),
        ("Repeat '{title}' weekly, indefinite, starting {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=WEEKLY"},
         _r({"event_id": "cal_evt_72516"})),
        ("Set up annual '{title}' from {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=YEARLY"},
         _r({"event_id": "cal_evt_83749"})),
        ("Recurring '{title}', biweekly Tuesdays, start {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=WEEKLY;INTERVAL=2;BYDAY=TU"},
         _r({"event_id": "cal_evt_94972"})),
        ("Schedule '{title}' every Wednesday at {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=WEEKLY;BYDAY=WE"},
         _r({"event_id": "cal_evt_16205"})),
        ("Set repeating '{title}' for next 10 weeks, starting {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=WEEKLY;COUNT=10"},
         _r({"event_id": "cal_evt_27438"})),
        ("Recurring '{title}', quarterly, from {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=MONTHLY;INTERVAL=3"},
         _r({"event_id": "cal_evt_38661"})),
        ("Make '{title}' repeat every weekday at {dt}.",
         {"title": "{title}", "start": "{dt}", "recur": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR"},
         _r({"event_id": "cal_evt_49894"})),
    ],

    "list_calendars": [
        ("List all my calendars.",
         {}, _r({"calendars": [{"id": "primary"}, {"id": "work"}, {"id": "family"}]})),
        ("Show calendars for user {user}.",
         {"user_id": "{user}"}, _r({"count": 5})),
        ("What calendars do I have access to?",
         {}, _r({"count": 7})),
        ("Get a list of {user}'s calendars.",
         {"user_id": "{user}"}, _r({"count": 4})),
        ("Pull calendar list.",
         {}, _r({"calendars": [{"id": "primary"}, {"id": "team_alpha"}]})),
        ("Enumerate calendars I own.",
         {"role": "owner"}, _r({"count": 3})),
        ("List shared calendars for {user}.",
         {"user_id": "{user}", "shared": True}, _r({"count": 6})),
        ("Show me every calendar attached to my account.",
         {}, _r({"count": 8})),
        ("Calendars list please.",
         {}, _r({"count": 5})),
        ("Display all calendars for user {user}, including subscribed.",
         {"user_id": "{user}", "include_subscribed": True}, _r({"count": 9})),
        ("Get calendars where I'm the writer.",
         {"role": "writer"}, _r({"count": 4})),
        ("List my calendar resources.",
         {}, _r({"count": 6})),
        ("What calendars exist for {user}?",
         {"user_id": "{user}"}, _r({"count": 5})),
    ],

    "share_calendar": [
        ("Share calendar {cal} with {user}.",
         {"calendar_id": "{cal}", "user_id": "{user}", "role": "reader"},
         _r({"status": "shared"})),
        ("Give {user} write access to {cal}.",
         {"calendar_id": "{cal}", "user_id": "{user}", "role": "writer"},
         _r({"status": "ok"})),
        ("Share {cal} with {user} as owner.",
         {"calendar_id": "{cal}", "user_id": "{user}", "role": "owner"},
         _r({"status": "shared"})),
        ("Add {user} to calendar {cal}, viewer role.",
         {"calendar_id": "{cal}", "user_id": "{user}", "role": "viewer"},
         _r({"status": "added"})),
        ("Send {user} access to my {cal} calendar.",
         {"calendar_id": "{cal}", "user_id": "{user}"},
         _r({"status": "sent"})),
        ("Grant {user} reader on {cal}.",
         {"calendar_id": "{cal}", "user_id": "{user}", "role": "reader"},
         _r({"status": "ok"})),
        ("Share {cal} with team@example.com (user_id={user}).",
         {"calendar_id": "{cal}", "user_id": "{user}", "role": "writer"},
         _r({"status": "shared"})),
        ("Allow {user} to edit calendar {cal}.",
         {"calendar_id": "{cal}", "user_id": "{user}", "role": "writer"},
         _r({"status": "ok"})),
        ("Invite {user} to calendar {cal}.",
         {"calendar_id": "{cal}", "user_id": "{user}"}, _r({"status": "invited"})),
        ("Make {user} a co-owner of {cal}.",
         {"calendar_id": "{cal}", "user_id": "{user}", "role": "owner"},
         _r({"status": "ok"})),
        ("Share read-only {cal} with {user}.",
         {"calendar_id": "{cal}", "user_id": "{user}", "role": "reader"},
         _r({"status": "shared"})),
        ("Add {user} to calendar {cal} with full access.",
         {"calendar_id": "{cal}", "user_id": "{user}", "role": "owner"},
         _r({"status": "ok"})),
        ("Share my {cal} calendar with {user}.",
         {"calendar_id": "{cal}", "user_id": "{user}"}, _r({"status": "shared"})),
    ],

    "rsvp_to_event": [
        ("RSVP yes to {evt}.",
         {"event_id": "{evt}", "response": "accepted"}, _r({"status": "ok"})),
        ("Decline {evt}.",
         {"event_id": "{evt}", "response": "declined"}, _r({"status": "ok"})),
        ("Mark {evt} as tentative.",
         {"event_id": "{evt}", "response": "tentative"}, _r({"status": "ok"})),
        ("Accept the invite for {evt}.",
         {"event_id": "{evt}", "response": "accepted"}, _r({"status": "accepted"})),
        ("Send a 'no' RSVP for {evt}.",
         {"event_id": "{evt}", "response": "declined"}, _r({"status": "declined"})),
        ("Respond 'maybe' on {evt}.",
         {"event_id": "{evt}", "response": "tentative"}, _r({"status": "tentative"})),
        ("RSVP {evt} as accepted with note 'see you there'.",
         {"event_id": "{evt}", "response": "accepted", "note": "see you there"},
         _r({"status": "ok"})),
        ("Confirm attendance for {evt}.",
         {"event_id": "{evt}", "response": "accepted"}, _r({"status": "ok"})),
        ("Decline {evt}, scheduling conflict.",
         {"event_id": "{evt}", "response": "declined", "note": "schedule conflict"},
         _r({"status": "declined"})),
        ("Tentatively accept {evt}.",
         {"event_id": "{evt}", "response": "tentative"}, _r({"status": "tentative"})),
        ("Yes RSVP for event {evt}.",
         {"event_id": "{evt}", "response": "accepted"}, _r({"status": "ok"})),
        ("No, I can't make {evt}.",
         {"event_id": "{evt}", "response": "declined"}, _r({"status": "declined"})),
        ("Mark me as going to {evt}.",
         {"event_id": "{evt}", "response": "accepted"}, _r({"status": "ok"})),
    ],

    "block_focus_time": [
        ("Block 2 hours of focus time on {dt}.",
         {"start": "{dt}", "duration_min": 120, "title": "Focus"},
         _r({"event_id": "cal_evt_70022"})),
        ("Add a 'deep work' block at {dt} for 90 min.",
         {"start": "{dt}", "duration_min": 90, "title": "Deep Work"},
         _r({"event_id": "cal_evt_82873"})),
        ("Block focus time daily 9-11am next week.",
         {"recur": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR", "start": "2026-05-12T09:00:00", "duration_min": 120},
         _r({"created": 5})),
        ("Reserve {dt} for deep work, 3 hours.",
         {"start": "{dt}", "duration_min": 180, "title": "Deep Work"},
         _r({"event_id": "cal_evt_94005"})),
        ("Block 30-min focus on {dt}.",
         {"start": "{dt}", "duration_min": 30, "title": "Focus"},
         _r({"event_id": "cal_evt_15238"})),
        ("Set focus block at {dt}, 60 minutes, no notifications.",
         {"start": "{dt}", "duration_min": 60, "do_not_disturb": True},
         _r({"event_id": "cal_evt_26461"})),
        ("Block my calendar for focus on {dt}.",
         {"start": "{dt}", "duration_min": 90}, _r({"event_id": "cal_evt_37694"})),
        ("Reserve {dt} as focus, 45 min.",
         {"start": "{dt}", "duration_min": 45}, _r({"event_id": "cal_evt_48927"})),
        ("Mark {dt} private, 2hr focus.",
         {"start": "{dt}", "duration_min": 120, "visibility": "private"},
         _r({"event_id": "cal_evt_50150"})),
        ("Block 8-10am every weekday for focus.",
         {"recur": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR", "start": "2026-05-12T08:00:00", "duration_min": 120},
         _r({"created": 5})),
        ("Insert focus time on {dt}, 75 min.",
         {"start": "{dt}", "duration_min": 75}, _r({"event_id": "cal_evt_61383"})),
        ("Block focus session at {dt} for an hour.",
         {"start": "{dt}", "duration_min": 60}, _r({"event_id": "cal_evt_72516"})),
        ("Add a 4-hour deep work block on {dt}.",
         {"start": "{dt}", "duration_min": 240}, _r({"event_id": "cal_evt_83749"})),
    ],

    "convert_dst": [
        ("Does {tz1} observe DST?",
         {"timezone": "{tz1}"}, _r({"observes_dst": True, "transitions": ["2026-03-08", "2026-11-01"]})),
        ("When does DST start in {tz1}?",
         {"timezone": "{tz1}", "year": 2026}, _r({"start": "2026-03-29"})),
        ("Is DST active right now in {tz1}?",
         {"timezone": "{tz1}", "date": "2026-05-08"}, _r({"in_dst": True})),
        ("DST end date for {tz1} 2026?",
         {"timezone": "{tz1}", "year": 2026}, _r({"end": "2026-10-25"})),
        ("Compare DST between {tz1} and {tz2}.",
         {"tz_a": "{tz1}", "tz_b": "{tz2}"}, _r({"both_observe": True})),
        ("Will {tz1} change clocks this fall?",
         {"timezone": "{tz1}", "year": 2026}, _r({"transitions_remaining": 1})),
        ("Get DST schedule for {tz1}.",
         {"timezone": "{tz1}"}, _r({"transitions": ["2026-03-29", "2026-10-25"]})),
        ("Is {tz1} on summer time on {dt}?",
         {"timezone": "{tz1}", "date": "{dt}"}, _r({"in_dst": True})),
        ("DST status: {tz1} now.",
         {"timezone": "{tz1}", "date": "2026-05-08"}, _r({"in_dst": True})),
        ("When does {tz1} fall back?",
         {"timezone": "{tz1}", "year": 2026}, _r({"fall_back": "2026-11-01"})),
        ("Spring-forward date {tz1}?",
         {"timezone": "{tz1}", "year": 2026}, _r({"spring_forward": "2026-03-08"})),
        ("Daylight saving info {tz1}.",
         {"timezone": "{tz1}"}, _r({"observes_dst": True})),
        ("Tell me DST behavior of {tz1}.",
         {"timezone": "{tz1}"}, _r({"observes_dst": False})),
    ],

    "get_world_clock": [
        ("What's the current time in {city}?",
         {"city": "{city}"}, _r({"now": "2026-05-08T14:23:00", "tz": "Asia/Tokyo"})),
        ("Time in {city} right now?",
         {"city": "{city}"}, _r({"now": "2026-05-08T07:23:00"})),
        ("Show world clock for {city}.",
         {"city": "{city}"}, _r({"now": "2026-05-08T19:23:00"})),
        ("Quick: time in {city}?",
         {"city": "{city}"}, _r({"now": "2026-05-08T11:23:00"})),
        ("Local time {city}.",
         {"location": "{city}"}, _r({"now": "2026-05-08T22:23:00"})),
        ("Get current local time at {city}.",
         {"city": "{city}"}, _r({"now": "2026-05-08T03:23:00"})),
        ("What hour is it in {city}?",
         {"city": "{city}"}, _r({"hour": 18, "tz": "Europe/Paris"})),
        ("Display current time over in {city}.",
         {"city": "{city}"}, _r({"now": "2026-05-08T14:23:00"})),
        ("Now-time at {city}.",
         {"city": "{city}"}, _r({"now": "2026-05-08T09:23:00"})),
        ("World clock check for {city}.",
         {"city": "{city}"}, _r({"now": "2026-05-08T16:23:00"})),
        ("What time is it currently in {city}?",
         {"city": "{city}"}, _r({"now": "2026-05-08T08:23:00"})),
        ("Pull live time for {city}.",
         {"city": "{city}"}, _r({"now": "2026-05-08T20:53:00"})),
        ("Current time at {city} please.",
         {"city": "{city}"}, _r({"now": "2026-05-08T13:23:00"})),
    ],

    "weather_alert_history": [
        ("Show past severe weather alerts for {city} this year.",
         {"city": "{city}", "year": 2026}, _r({"count": 4})),
        ("Get weather alert history {city}, last 30 days.",
         {"city": "{city}", "days": 30}, _r({"count": 1})),
        ("Past tornado warnings near {city}.",
         {"city": "{city}", "type": "tornado"}, _r({"count": 0})),
        ("List historical alerts in {city} for 2025.",
         {"city": "{city}", "year": 2025}, _r({"count": 7})),
        ("Storm history {city}, 90 days.",
         {"city": "{city}", "days": 90, "type": "storm"}, _r({"count": 3})),
        ("Recent flood advisories around {city}.",
         {"city": "{city}", "type": "flood", "days": 365}, _r({"count": 2})),
        ("How many heat advisories did {city} get last year?",
         {"city": "{city}", "year": 2025, "type": "heat"}, _r({"count": 6})),
        ("Pull alert log for {city}.",
         {"city": "{city}"}, _r({"count": 12})),
        ("Past 6 months of weather warnings, {city}.",
         {"city": "{city}", "days": 180}, _r({"count": 5})),
        ("Severe weather record {city} 2024.",
         {"city": "{city}", "year": 2024}, _r({"count": 9})),
        ("History of NWS alerts for {city}.",
         {"city": "{city}", "agency": "NWS"}, _r({"count": 23})),
        ("Hurricane history near {city}.",
         {"city": "{city}", "type": "hurricane"}, _r({"count": 1})),
        ("Get all winter storm alerts {city} since Dec 2025.",
         {"city": "{city}", "type": "winter_storm", "since": "2025-12-01"}, _r({"count": 4})),
    ],

    "get_road_closures": [
        ("Any road closures near {addr}?",
         {"near": "{addr}"}, _r({"closures": [{"id": "rc_211", "reason": "construction"}]})),
        ("List active road closures around {city}.",
         {"city": "{city}"}, _r({"count": 3})),
        ("Are there closures between {addr} and {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"closures": []})),
        ("Show road closures in {city} today.",
         {"city": "{city}", "date": "2026-05-08"}, _r({"count": 2})),
        ("Get current closures for highways near {city}.",
         {"city": "{city}", "road_type": "highway"}, _r({"count": 1})),
        ("Are roads closed because of weather in {city}?",
         {"city": "{city}", "cause": "weather"}, _r({"count": 0})),
        ("Closures near route from {addr} to {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"count": 1})),
        ("Road closure list for {city} this week.",
         {"city": "{city}", "range": "week"}, _r({"count": 5})),
        ("Find construction closures near {addr}.",
         {"near": "{addr}", "cause": "construction"}, _r({"count": 2})),
        ("Closure status on roads in {city}.",
         {"city": "{city}"}, _r({"count": 4})),
        ("Get blocked streets in {city} now.",
         {"city": "{city}"}, _r({"count": 2})),
        ("Detour info around {addr}?",
         {"near": "{addr}"}, _r({"detours": 1})),
        ("Anything closed on the way between {addr} and {addr2}?",
         {"origin": "{addr}", "destination": "{addr2}"}, _r({"count": 0})),
    ],

    "create_meeting_invite": [
        ("Send a meeting invite for '{title}' at {dt} to {user} and {user2}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}", "{user2}"]},
         _r({"event_id": "cal_evt_94972", "invites_sent": 2})),
        ("Invite {user}, {user2}, {user3} to '{title}' on {dt}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}", "{user2}", "{user3}"]},
         _r({"invites_sent": 3})),
        ("Set up '{title}' meeting at {dt}, attendees {user}+{user2}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}", "{user2}"]},
         _r({"event_id": "cal_evt_16205"})),
        ("Schedule '{title}' on {dt}, invite {user}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}"]},
         _r({"event_id": "cal_evt_27438"})),
        ("Make a 30-min meeting invite to {user} for {dt}, '{title}'.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}"], "duration_min": 30},
         _r({"event_id": "cal_evt_38661"})),
        ("Send invite '{title}', {dt}, recipients {user},{user2}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}", "{user2}"]},
         _r({"invites_sent": 2})),
        ("Calendar invite for '{title}' to {user} starting {dt}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}"]},
         _r({"event_id": "cal_evt_49894"})),
        ("Create meeting '{title}' on {dt}, video link, invite {user}+{user2}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}", "{user2}"], "video": True},
         _r({"event_id": "cal_evt_50150", "video_url": "https://meet.example/x"})),
        ("Send '{title}' invite for {dt}, attendees: {user}, {user2}, {user3}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}", "{user2}", "{user3}"]},
         _r({"invites_sent": 3})),
        ("Email invite '{title}' at {dt} to {user}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}"]},
         _r({"event_id": "cal_evt_61383"})),
        ("Loop {user} and {user2} into '{title}' on {dt}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}", "{user2}"]},
         _r({"invites_sent": 2})),
        ("Quick invite, '{title}', {dt}, ping {user}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}"]},
         _r({"event_id": "cal_evt_72516"})),
        ("Build invite for '{title}' at {dt}, send to {user},{user2}.",
         {"title": "{title}", "start": "{dt}", "attendees": ["{user}", "{user2}"]},
         _r({"invites_sent": 2})),
    ],
}


# Sanity: verify each tool has 13 variants.
def _check():
    for name, samples in TOOL_SAMPLES.items():
        assert len(samples) == 13, f"{name} has {len(samples)} (need 13)"


_check()


# Titles used for create_calendar_event / update_event / etc.
EVENT_TITLES = [
    "Team standup", "1:1 with manager", "Product review", "Design sync",
    "Sprint planning", "Retro", "Customer demo", "Architecture review",
    "Hiring debrief", "Budget meeting", "All-hands", "Coffee chat",
    "Code walkthrough", "Roadmap discussion", "Vendor call",
    "Onboarding session", "Security review", "Performance check-in",
    "QBR", "OKR planning", "Office hours", "Pair programming",
    "Postmortem", "Marketing sync", "Sales kickoff", "Eng townhall",
    "Doc review", "Brainstorm", "Bug bash", "Release prep",
]

FLIGHTS = [
    "AA1234", "UA567", "DL2109", "BA0117", "LH401", "AF023", "SQ22",
    "EK215", "JL061", "QF1", "NH107", "VS3", "KE085", "TK001",
    "CX846", "AC852", "AS123", "JB456", "WN1500", "F92345",
]
