"""Part 6: math entries continued."""


def register_part_6(r):
    # ---- the fundamental theorem of calculus ----
    r("the fundamental theorem of calculus", "definition",
      "The fundamental theorem of calculus is the bridge between differentiation and integration, the two principal operations of calculus, showing that they are inverse processes. It comes in two parts. The first part states that if f is continuous on [a, b] and F(x) is defined as the integral of f from a to x, then F is differentiable and F'(x) = f(x); in other words, differentiating an accumulated integral recovers the original integrand. The second part states that if F is any antiderivative of f on [a, b], then the definite integral of f from a to b equals F(b) - F(a); in other words, definite integrals can be computed by finding any antiderivative and evaluating at the endpoints. Together these results convert the conceptually difficult problem of summing infinitely many infinitesimal pieces (integration) into the often easier problem of finding antiderivatives (differentiation in reverse), and they tie the local notion of rate of change to the global notion of accumulation.")
    r("the fundamental theorem of calculus", "significance",
      "The fundamental theorem matters because it makes definite integrals computable in closed form whenever an antiderivative is known, transforming integration from an awkward limit of Riemann sums into algebraic manipulation. Without the theorem, computing the area under a parabola would require explicitly summing infinitely many thin rectangles; with the theorem, one finds the antiderivative (x^3/3 for f(x) = x^2) and evaluates at the endpoints. The theorem also unifies two historically distinct mathematical traditions: the geometric problem of areas and volumes (going back to Archimedes and pursued through method of exhaustion) and the differential calculus (rates of change, tangent lines). Newton and Leibniz independently recognized this unification in the 17th century, and it is the cornerstone of analysis as a subject. Modern applications spanning physics, probability, statistics, signal processing, and engineering all rely on the theorem to convert integral problems into antiderivative computations.")

    # ---- integration techniques ----
    r("integration techniques", "definition",
      "Integration techniques are systematic methods for finding antiderivatives of functions, since unlike differentiation (which is mechanical for elementary functions), integration is partly an art. The basic techniques include direct application of standard antiderivative formulas (polynomials, exponentials, sines, cosines, basic rational functions), integration by substitution (the chain rule in reverse, useful when the integrand contains a function and its derivative), integration by parts (the product rule in reverse, useful when the integrand is a product), trigonometric substitution (handling integrals involving square roots of quadratic expressions), partial fractions (decomposing rational functions into simpler pieces), and reduction formulas (recursively reducing the complexity of integrands like x^n e^x or sin^n x). For integrals that have no closed-form antiderivative in elementary functions (like exp(-x^2) or sin(x)/x), numerical methods (Simpson's rule, Gaussian quadrature, Monte Carlo) provide approximations. Computer algebra systems like Mathematica and SymPy automate much of this work today.")
    r("integration techniques", "significance",
      "Integration techniques matter because integrals are ubiquitous in science and engineering, and being able to evaluate them in closed form gives understanding that numerical answers alone cannot provide. Many physical quantities are integrals: total work done by a force over a distance, total charge from a current over time, area under a probability density to compute event probabilities, expected values of random variables, total mass from density, electric and gravitational potentials from charge or mass distributions. Closed-form integrals reveal scaling behaviors, asymptotic limits, and symmetries that numerical evaluation obscures. Even when an integral cannot be evaluated symbolically, recognizing whether it converges, what its leading behavior is for large or small parameters, and how it depends on inputs requires the same toolkit. Numerical integration handles the rest, and understanding when each technique applies is part of the practical engineer's and scientist's repertoire.")
    r("integration techniques", "misconception",
      "A common misconception is that every elementary function has an elementary antiderivative; in fact, many simple-looking functions like exp(-x^2), sin(x)/x, and 1/ln(x) are provably non-integrable in elementary terms (Liouville's theorem and the Risch algorithm formalize this). The error function and many other special functions are defined precisely because such integrals appear in important contexts. Another misconception is that finding an antiderivative is the same as solving a differential equation; antiderivatives solve the simplest first-order ODE dy/dx = f(x), but most differential equations require richer techniques. People also sometimes assume that more advanced techniques are always needed for harder integrals; in practice, choosing the right technique often matters more than knowing many. Finally, the assumption that numerical integration always works is misleading; functions with singularities or rapid oscillations can defeat naive numerical methods, and specialized algorithms exist for difficult integrals.")

    # ---- multivariable calculus ----
    r("multivariable calculus", "example",
      "An example of multivariable calculus in action is finding and classifying critical points of a function of two variables. Consider f(x, y) = x^2 + xy + y^2 - 6x - 9y + 1. The gradient is (df/dx, df/dy) = (2x + y - 6, x + 2y - 9). Setting both components to zero: 2x + y = 6 and x + 2y = 9. Solving: from the first, y = 6 - 2x; substituting into the second, x + 2(6 - 2x) = 9, so x + 12 - 4x = 9, giving -3x = -3, x = 1, then y = 4. The unique critical point is (1, 4). To classify it, compute the Hessian matrix [[2, 1], [1, 2]], with determinant 3 (positive) and trace 4 (positive), indicating a local minimum. Evaluating f(1, 4) gives 1 + 4 + 16 - 6 - 36 + 1 = -20, so the function has a global minimum value of -20 at (1, 4). The example shows how partial derivatives, gradient zero conditions, and the Hessian generalize the single-variable optimization story to multiple dimensions.")

    # ---- partial derivatives ----
    r("partial derivatives", "mechanism",
      "Partial derivatives work by treating a multivariable function as a single-variable function with respect to one variable at a time, holding the others constant. For a function f(x, y, z), the partial derivative with respect to x at a point is computed by treating y and z as constants and differentiating with respect to x using ordinary single-variable rules. Geometrically, this measures the rate of change of f along the x-direction at the chosen point. The notation is df/dx (with curly d's, often written as a backwards 6 in print) to distinguish from ordinary derivatives. The mechanism extends to all the standard rules: linearity, product rule, quotient rule, chain rule (with appropriate care for paths through multiple variables), and so on. Higher-order partial derivatives apply the same idea iteratively, and mixed partials (df/dx then df/dy) generally agree with mixed partials in the other order under continuity (Clairaut's theorem). The full first-derivative information is collected into the gradient vector, and second-derivative information into the Hessian matrix.")

    # ---- Taylor series ----
    r("Taylor series", "definition",
      "A Taylor series is an infinite sum representing a function as a power series centered at a chosen point, built from the function's derivatives at that point. For an infinitely differentiable function f(x) and center a, the Taylor series is f(a) + f'(a)(x - a) + f''(a)(x - a)^2/2! + f'''(a)(x - a)^3/3! + ... The series is constructed so that all derivatives at x = a match those of f, providing successively better polynomial approximations to f near a. When the series converges to f(x) on some interval around a, the function is called analytic at a. Many familiar functions (exp, sin, cos, log near 1, 1/(1-x) on the unit disk) have convergent Taylor series everywhere or in characteristic intervals. Maclaurin series are Taylor series with center a = 0. Truncating at degree n gives a polynomial approximation with error controlled by the size of the (n+1)-th derivative on the interval, formalized by Taylor's theorem with remainder.")
    r("Taylor series", "mechanism",
      "Taylor series work by encoding all the derivatives of a function at a single point into an infinite polynomial. The mechanism is most clearly seen by the explicit construction: at the center, the constant term f(a) matches the function's value, the linear term f'(a)(x-a) matches the first derivative, the quadratic term f''(a)(x-a)^2/2 matches the second derivative, and so on. Every derivative at the center is matched by exactly one term in the series. Convergence of the resulting series and equality with the original function require additional analysis: some functions have Taylor series that converge but to a different function (the famous example exp(-1/x^2) extended to be 0 at x = 0 is smooth but has identically zero Taylor series at 0). The radius of convergence depends on singularities of the function (in the complex plane for analytic continuation). Within the radius, the series can be added, multiplied, differentiated, and integrated term by term, providing a powerful computational tool.")
    r("Taylor series", "comparison",
      "Taylor series differ from Fourier series in basis: Taylor uses powers of (x - a), Fourier uses sines and cosines (or complex exponentials). Taylor approximations are most accurate near the center and degrade away from it; Fourier approximations spread the approximation error across an interval. Taylor series suit functions that are smooth at a particular point and whose values nearby need to be computed; Fourier series suit periodic functions and oscillatory phenomena. Compared with polynomial interpolation through given data points, Taylor series use derivative information at one point rather than function values at many. Compared with Pade approximants, which are rational function approximations matching Taylor coefficients but often with better convergence properties for functions with singularities, Taylor series are simpler but can converge slowly or diverge near singularities. Compared with asymptotic series, which need not converge but provide useful approximations for large or small arguments, Taylor series are convergent power series and so are local approximations.")
    r("Taylor series", "example",
      "The Taylor series of e^x centered at 0 is 1 + x + x^2/2! + x^3/3! + x^4/4! + ..., which converges for all real and complex x. The first few terms approximate e well: the degree-3 polynomial 1 + x + x^2/2 + x^3/6 evaluated at x = 1 gives 1 + 1 + 0.5 + 0.1667 = 2.6667, compared with the true value e is approximately 2.71828, an error of about 0.05. Adding more terms shrinks the error: degree 5 gives 2.71667, error about 0.0016; degree 10 gives e to 7 decimal places. For sine, the Taylor series at 0 is x - x^3/3! + x^5/5! - x^7/7! + ..., and for cosine, 1 - x^2/2! + x^4/4! - x^6/6! + ..., both converging everywhere. These series let computers and calculators evaluate transcendental functions to arbitrary precision through truncated polynomial computation, which is faster than alternative algorithms in most cases.")
    r("Taylor series", "significance",
      "Taylor series matter because they approximate complicated functions by polynomials, which are easy to compute, integrate, and differentiate. Numerical algorithms for transcendental functions inside calculators, computer libraries, and scientific software rely on truncated Taylor series (often combined with range reduction and other techniques). Physics uses Taylor expansions to linearize nonlinear systems near equilibrium points, study small perturbations, and derive approximations for special regimes (small angles, weak fields, slow speeds). Numerical methods for differential equations like Runge-Kutta and Euler methods are derived from Taylor expansions. Asymptotic expansions, related to Taylor series in spirit, give insight into the behavior of complicated integrals and special functions in limiting regimes. The intellectual lesson is that local information at a point (function value and all derivatives) can determine the function entirely on its domain of analyticity, a striking consequence of analyticity that has no counterpart for merely continuous or smooth functions.")

    # ---- Fourier series ----
    r("Fourier series", "definition",
      "A Fourier series is the expansion of a periodic function as an infinite sum of sines and cosines (or equivalently complex exponentials) at integer multiples of the function's fundamental frequency. For a function f(x) of period 2 pi, the Fourier series is a0/2 + sum from n = 1 to infinity of (a_n cos(n x) + b_n sin(n x)), with the Fourier coefficients given by integrals over one period: a_n is the integral of f(x) cos(n x) divided by pi, and b_n is similar with sin. Convergence to the original function depends on its smoothness; for piecewise smooth functions, the series converges to the average of left and right limits at jump discontinuities (Dirichlet's theorem). Fourier series provide a frequency-domain representation of periodic phenomena, decomposing the signal into its sinusoidal components. The technique generalizes to Fourier transforms for non-periodic functions and to Fourier series on other intervals or in higher dimensions.")
    r("Fourier series", "mechanism",
      "Fourier series work by exploiting the orthogonality of sines and cosines on the period: the integral of cos(m x) cos(n x) over a period vanishes for m not equal to n and equals pi for m = n, and similarly for sines, while integrals of cos times sin or different m and n combinations vanish. This orthogonality makes the Fourier coefficients computable as inner products: a_n is essentially the projection of f onto cos(n x). The mechanism is identical in spirit to expressing a vector in an orthonormal basis: each component is the dot product of the vector with the corresponding basis vector. The series builds up the original function by combining its frequency components, with low-frequency terms capturing slow variations and high-frequency terms capturing fine detail. Convergence is uniform for smooth functions and pointwise (with possible Gibbs overshoot near jumps) for piecewise smooth ones. The same machinery extends to the Fourier transform for aperiodic functions, replacing the discrete sum by an integral over a continuous frequency variable.")
    r("Fourier series", "comparison",
      "Fourier series differ from Taylor series in basis (sines and cosines vs. powers), in domain (typically periodic functions on intervals, vs. functions analytic at a point), and in approximation behavior (uniform error spread across the interval vs. best near the center). Compared with the Fourier transform for aperiodic functions, Fourier series have discrete frequency content (only integer multiples of the fundamental) while the transform has a continuous spectrum. Compared with wavelet expansions, which use localized basis functions of different scales, Fourier series use globally supported basis functions and so cannot localize transient features in time as well. Compared with orthogonal polynomial expansions (Legendre, Chebyshev, Hermite), Fourier series are tailored to periodic structure, while polynomial expansions suit non-periodic intervals or weight-function-defined inner products. The choice of basis depends on the problem's geometry and the kind of structure to capture.")
    r("Fourier series", "significance",
      "Fourier series matter because frequency-domain analysis of signals and systems is central to virtually every quantitative discipline. Audio signals (musical notes, speech) are decomposed into harmonics by the human ear (and by spectrum analyzers); image compression in JPEG and similar formats relies on the closely related discrete cosine transform; differential equations (especially heat and wave equations on bounded intervals) are most easily solved by Fourier series, with each frequency component evolving independently. Quantum mechanics uses Fourier transforms to relate position and momentum representations. Communications systems modulate carrier waves whose frequency spectrum determines bandwidth and channel capacity. Earthquake seismograms, electroencephalograms, and economic time series are analyzed for spectral content to identify periodicities. The development of the fast Fourier transform in 1965 made these analyses computationally feasible at scale, ranking among the most important algorithmic developments of the 20th century.")

    # ---- the Laplace transform ----
    r("the Laplace transform", "mechanism",
      "The Laplace transform converts a function of time, f(t), defined for t at least 0, into a function of complex frequency F(s) by the integral F(s) = integral from 0 to infinity of e^(-s t) f(t) dt. The integral converges in a right half-plane of the complex s-plane for typical exponentially-bounded functions. The transform's power comes from how it converts differentiation in time into multiplication by s in the transform domain (with adjustments for initial conditions): if f(t) transforms to F(s), then f'(t) transforms to s F(s) - f(0). It also converts convolution in time into ordinary multiplication in the transform domain. These properties turn linear differential equations with constant coefficients into algebraic equations in s, which can be solved by ordinary algebra and inverted back to the time domain via tables of transform pairs or by contour integration. The mechanism extends to systems of equations, integro-differential equations, and partial differential equations along one variable.")
    r("the Laplace transform", "example",
      "Solve the differential equation y'' + 4y = 0 with initial conditions y(0) = 1, y'(0) = 0 using the Laplace transform. Let Y(s) be the transform of y(t). The transform of y''(t) is s^2 Y(s) - s y(0) - y'(0) = s^2 Y(s) - s. Substituting into the differential equation: s^2 Y(s) - s + 4 Y(s) = 0, so Y(s)(s^2 + 4) = s, giving Y(s) = s / (s^2 + 4). Looking up the inverse transform: s / (s^2 + 4) is the transform of cos(2 t). Therefore y(t) = cos(2 t). Verifying: y'(t) = -2 sin(2 t), y''(t) = -4 cos(2 t) = -4 y(t), and y(0) = 1, y'(0) = 0, all consistent. The example shows how Laplace transforms reduce a differential equation problem to algebra and table lookup, especially valuable for engineering applications where systems often involve constant-coefficient differential equations driven by complicated forcing functions.")

    # ---- differential equations - skipped, no entry needed ----

    # ---- vector calculus ----
    r("vector calculus", "comparison",
      "Vector calculus extends single-variable calculus to functions of and outputting vectors in higher-dimensional spaces, generalizing derivatives to gradients, divergences, and curls and integrals to line, surface, and volume integrals. Compared with single-variable calculus, the central new objects are vector fields (functions assigning vectors to points in space) and the operators that probe their structure: gradient (the multivariable analog of derivative for scalar functions), divergence (which measures the local source or sink behavior of a vector field), and curl (which measures local rotation). Compared with multivariable calculus more broadly, vector calculus emphasizes the geometric and physical interpretations of these operators in three-dimensional space, with the classical theorems (Green's, Stokes', divergence) generalizing the fundamental theorem of calculus to higher dimensions. Compared with differential geometry, vector calculus is essentially the special case for flat three-dimensional space; the more general formulations use differential forms, pullback, and the exterior derivative.")
    r("vector calculus", "misconception",
      "A common misconception is that the names 'gradient,' 'divergence,' and 'curl' are merely formal labels rather than reflecting clear geometric meanings. The gradient of a scalar field points in the direction of fastest increase and has magnitude equal to the rate of increase; the divergence of a vector field measures whether the field is locally a source (positive divergence), sink (negative), or neutral (zero); the curl measures the local axis and strength of rotation of the vector field. Another misconception is that the divergence and curl are difficult to compute; they are explicit partial derivative expressions that follow from algebraic rules. People also sometimes assume that line integrals always depend on the path; for conservative vector fields (those that are gradients of scalar potentials), line integrals depend only on the endpoints, a key result connecting integrability to the structure of the field. Finally, the assumption that vector calculus works only in three dimensions misses that the same ideas, suitably generalized through differential forms, work in any dimension and on curved manifolds.")

    # ---- modular arithmetic ----
    r("modular arithmetic", "definition",
      "Modular arithmetic is a system of arithmetic for integers in which numbers wrap around upon reaching a fixed value called the modulus. Two integers a and b are said to be congruent modulo n, written a equivalent b mod n, if a - b is divisible by n, equivalently if a and b have the same remainder when divided by n. The integers modulo n form a finite set Z/nZ with n elements (typically represented by 0 through n - 1), with addition and multiplication defined to produce results within this set by reducing intermediate values modulo n. Familiar everyday examples include clock arithmetic (mod 12 or mod 24 for hours), days of the week (mod 7), and angle measurements (mod 360 or mod 2 pi). Modular arithmetic underlies number theory, cryptography (RSA, Diffie-Hellman, elliptic-curve methods), error-correcting codes, hashing, random number generation, and many computer science algorithms.")
    r("modular arithmetic", "mechanism",
      "Modular arithmetic works by performing standard integer operations and then reducing the result by taking the remainder upon division by the modulus. For example, in mod 7 arithmetic: 5 + 4 = 9, but 9 mod 7 = 2, so 5 + 4 equivalent 2 mod 7; 5 times 4 = 20, but 20 mod 7 = 6, so 5 times 4 equivalent 6 mod 7. Subtraction works similarly, with care for negative results: 3 - 5 = -2, and -2 mod 7 = 5, so 3 - 5 equivalent 5 mod 7. Division is more subtle: division by a in mod n requires a to have a multiplicative inverse, which exists if and only if gcd(a, n) = 1. When n is prime, every nonzero element has an inverse, and Z/pZ is a field. The extended Euclidean algorithm computes inverses efficiently. Fast exponentiation by repeated squaring computes large powers modulo n efficiently, the basis of much modern cryptography.")
    r("modular arithmetic", "example",
      "A clean example is computing 7^100 mod 13. Direct computation of 7^100 yields a number with about 85 decimal digits, infeasible to handle naively, but modular arithmetic makes this trivial. Use Fermat's little theorem: for prime p and a not divisible by p, a^(p-1) equivalent 1 mod p. Here 7^12 equivalent 1 mod 13. Since 100 = 8 times 12 + 4, we have 7^100 = (7^12)^8 times 7^4 equivalent 1^8 times 7^4 mod 13 = 7^4 mod 13. Now 7^2 = 49 = 3 times 13 + 10, so 7^2 equivalent 10 mod 13. Then 7^4 equivalent 10^2 = 100 = 7 times 13 + 9, so 7^4 equivalent 9 mod 13. Therefore 7^100 equivalent 9 mod 13. The example shows how modular arithmetic, combined with results like Fermat's little theorem, lets us compute with otherwise unmanageable large numbers.")

    # ---- prime number distribution ----
    r("prime number distribution", "mechanism",
      "Prime numbers are integers greater than 1 with no positive divisors other than 1 and themselves. Their distribution among the integers is irregular but follows a smooth statistical pattern captured by the prime number theorem: the count of primes up to x, written pi(x), is asymptotic to x / ln(x) as x grows, meaning the density of primes near a large integer N is approximately 1 / ln(N). This means primes thin out logarithmically: about half of integers up to 6 are prime, but only about 4 percent of integers up to 100, and about 0.1 percent near 10^9. The mechanism behind this thinning is that as numbers grow, they have more potential divisors that could disqualify them from being prime; specifically, the probability that a random integer near N is not divisible by 2 is 1/2, by 3 is 2/3, by 5 is 4/5, and so on, and Mertens' theorems show that the product of these (1 - 1/p) terms over primes up to log N gives the leading 1 / ln(N) behavior of prime density.")
    r("prime number distribution", "misconception",
      "A common misconception is that prime numbers eventually run out or become very rare; in fact, Euclid proved more than 2000 years ago that there are infinitely many primes, and even though they thin out, the prime counting function pi(x) goes to infinity as x grows. Another misconception is that primes are randomly distributed in any meaningful statistical sense; while the prime gaps look chaotic, primes follow specific distributional laws and exhibit subtle non-random patterns (twin primes, prime constellations, congruence biases like 'Chebyshev's bias' that primes are slightly more likely to be 3 mod 4 than 1 mod 4). People also sometimes think that there is a formula generating only primes; while many polynomials and other expressions hit primes often, no simple formula generates exclusively primes for all inputs. Finally, the Riemann hypothesis is sometimes thought to be merely about the location of zeta function zeros; in fact, it has profound consequences for the precision of the prime number theorem's error term and for the distribution of primes in arithmetic progressions.")

    # ---- the Riemann hypothesis ----
    r("the Riemann hypothesis", "definition",
      "The Riemann hypothesis is a conjecture in mathematics, formulated by Bernhard Riemann in 1859, that all nontrivial zeros of the Riemann zeta function lie on the critical line where the real part equals 1/2. The Riemann zeta function zeta(s) is defined initially as the sum from n = 1 to infinity of 1/n^s for complex s with real part greater than 1, and analytically continued to the rest of the complex plane (except for a simple pole at s = 1). Its zeros are of two types: the trivial zeros at the negative even integers (-2, -4, -6, ...), and the nontrivial zeros that lie in the critical strip 0 < Re(s) < 1. The hypothesis asserts that all of these nontrivial zeros have real part exactly 1/2. The conjecture is one of the seven Millennium Prize Problems with a million-dollar prize for a proof, and it has been verified numerically for the first several trillion zeros, all of which lie on the critical line.")
    r("the Riemann hypothesis", "mechanism",
      "The connection between the zeros of the zeta function and the distribution of primes runs through the explicit formula derived from the Hadamard product of zeta. Specifically, the prime counting function pi(x) (or related functions like the Chebyshev psi function) can be expressed as a leading term plus a sum of contributions from zeros of zeta, with each zero giving an oscillatory term whose frequency is the imaginary part and whose amplitude depends on the real part. Zeros on the critical line (Re(s) = 1/2) produce the smallest possible oscillations and yield the optimal error estimate for the prime number theorem: pi(x) = Li(x) + O(sqrt(x) log x) under the Riemann hypothesis. Zeros off the critical line would correspond to larger irregularities in the distribution of primes. The mechanism reveals the deep duality between additive structure (counting primes among integers) and multiplicative structure (zeros of an analytic function), one of the most surprising connections in mathematics.")
    r("the Riemann hypothesis", "significance",
      "The Riemann hypothesis matters because it would settle hundreds of conditional theorems in number theory whose proofs currently rest on assuming the conjecture. It would give the sharpest known estimate for the error term in the prime number theorem and for the distribution of primes in arithmetic progressions. Many results about prime gaps, Goldbach-type partitions, and the Mertens function would follow. Beyond pure number theory, the conjectured behavior of zeta zeros has been linked to the spectra of certain quantum mechanical systems through the Hilbert-Polya conjecture and to random matrix theory through the Montgomery-Odlyzko law, suggesting a deep connection to physics that remains incompletely understood. Cryptography, while not directly using the conjecture, depends on the same kind of analytic number theory that surrounds it. The hypothesis has been called the most important open problem in mathematics; resolving it would not just answer one question but would also strongly suggest new techniques applicable across the discipline.")

    # ---- Fermat's last theorem ----
    r("Fermat's last theorem", "definition",
      "Fermat's last theorem states that no three positive integers a, b, c can satisfy the equation a^n + b^n = c^n for any integer exponent n greater than 2. The case n = 2 has infinitely many solutions, the Pythagorean triples like (3, 4, 5) and (5, 12, 13). Pierre de Fermat famously wrote in the margin of his copy of Diophantus' Arithmetica around 1637 that he had a 'truly marvelous proof' for the theorem but the margin was too narrow to contain it, leaving mathematicians to attempt proofs for over 350 years. The theorem was finally proved by Andrew Wiles in 1994 (with completion by Wiles and Richard Taylor in 1995), through a deep route involving modular forms, elliptic curves, and Galois representations, in particular by proving the Taniyama-Shimura-Weil conjecture for semistable elliptic curves, which had been shown by Frey, Serre, and Ribet to imply Fermat's last theorem.")
    r("Fermat's last theorem", "comparison",
      "Fermat's last theorem differs from many famous open problems by being about a simple-to-state diophantine equation accessible to anyone with elementary algebra, while its solution required some of the deepest abstract mathematics ever developed. Compared with Goldbach's conjecture (every even integer greater than 2 is the sum of two primes), Fermat's last theorem is now proved while Goldbach's remains open despite massive numerical confirmation. Compared with the Riemann hypothesis, Fermat's last theorem was about a specific algebraic equation while Riemann is about analytic structure. Compared with the abc conjecture and other deep number-theoretic conjectures, Fermat's last theorem is now a special case of much broader frameworks (modularity of elliptic curves), which is why its eventual proof was a triumph but no longer a foundational mystery once the broader framework was in place. The contrast between the simplicity of statement and the depth of proof is what makes the theorem famously emblematic of how superficially elementary problems in number theory can resist solution for centuries.")

    # ---- Goldbach's conjecture ----
    r("Goldbach's conjecture", "definition",
      "Goldbach's conjecture, posed by Christian Goldbach in 1742 in a letter to Leonhard Euler, asserts that every even integer greater than 2 can be expressed as the sum of two prime numbers. For example: 4 = 2 + 2, 6 = 3 + 3, 8 = 3 + 5, 10 = 3 + 7 = 5 + 5, 12 = 5 + 7, 100 = 3 + 97 = 11 + 89 = 17 + 83 = 29 + 71 = 41 + 59 = 47 + 53. The conjecture has been verified by computer for all even integers up to 4 times 10^18 without finding any exceptions, and it has strong heuristic support from probabilistic arguments about the density of primes. Despite this, no proof exists. The weak Goldbach conjecture (every odd integer greater than 5 is the sum of three primes) was proved by Harald Helfgott in 2013, but the strong (binary) version remains one of the oldest unsolved problems in mathematics. Resolving it would be a major achievement, though it would have less profound consequences for the rest of mathematics than the Riemann hypothesis would.")

    # ---- combinatorics basics ----
    r("combinatorics basics", "mechanism",
      "Combinatorics works by carefully counting arrangements, selections, and structures, using a small set of fundamental principles applied recursively to complex problems. The multiplication principle says that if a process has k stages with n_i choices at stage i, the total number of outcomes is n_1 times n_2 times ... times n_k. The addition principle handles disjoint cases by summing them. Permutations count ordered arrangements: P(n, k) = n! / (n-k)! gives the number of ways to arrange k items chosen from n. Combinations count unordered selections: C(n, k) = n! / (k! (n-k)!) gives the number of ways to choose k items from n without regard to order. Inclusion-exclusion handles overcounting when sets overlap. Generating functions encode counting sequences as coefficients of formal power series, allowing algebraic manipulation. Bijections between combinatorial sets establish equal counts. These tools combine to solve a wide range of counting problems in mathematics, computer science, statistics, and physics.")
    r("combinatorics basics", "example",
      "How many ways can we form a poker hand of 5 cards from a standard 52-card deck? The number of unordered selections is C(52, 5) = 52! / (5! times 47!) = 2,598,960. To find the probability of being dealt a flush (all five cards of the same suit, but not in sequence), count the favorable outcomes: choose one of 4 suits in C(4, 1) = 4 ways, then choose 5 cards from the 13 of that suit in C(13, 5) = 1287 ways, giving 4 times 1287 = 5148 hands. Subtract the 36 straight flushes (4 suits times 9 starting positions) and 4 royal flushes to get 5108 ordinary flushes. The probability is 5108 / 2,598,960, about 0.00197 or 1 in 508. Similar combinatorial reasoning produces all standard poker probabilities and, more importantly, the same techniques apply to counting passwords, scheduling problems, network configurations, and biological sequences.")
    r("combinatorics basics", "misconception",
      "A common misconception is that combinatorial formulas can be applied without checking whether outcomes are equally likely or which structural features matter. For example, asking 'how many ways can two dice land' could give 36 (ordered outcomes), 21 (unordered outcomes), or 11 (distinct sums), depending on what 'way' means; using the wrong count gives wrong probabilities. Another misconception is that 'choose' formulas are interchangeable with 'permutation' formulas; selections without order use C(n, k) while ordered arrangements use P(n, k), and confusing them gives counts that differ by a factor of k!. People also sometimes try to apply formulas designed for distinguishable items to indistinguishable ones; counting arrangements of letters in MISSISSIPPI requires dividing 11! by the redundancies (4! for the I's, 4! for the S's, 2! for the P's), giving 34650, not the naive 11!. Finally, naive multiplication can overcount when the same outcome can be reached by different choice sequences; inclusion-exclusion or careful case analysis is often needed.")
    r("combinatorics basics", "significance",
      "Combinatorics matters because counting problems pervade mathematics, computer science, statistics, and many natural and social sciences. Algorithms are analyzed for complexity by counting operations as functions of input size; data structures are designed using combinatorial reasoning about how items relate; cryptographic key spaces are sized through combinatorial counts; statistical models often involve combinatorial coefficients (binomial, multinomial); evolutionary biology tracks lineage branching through combinatorial models. Probability theory is built on counting in finite sample spaces. Network science uses combinatorial graph theory to characterize structure of social, biological, and technical networks. Even genomics relies on combinatorics to count alignments, sequence motifs, and recombination patterns. The seemingly simple acts of careful counting connect to deep mathematical structures (generating functions, partitions, Young tableaux, group representations, lattice theory) that resonate across the discipline.")

    # ---- the binomial theorem ----
    r("the binomial theorem", "definition",
      "The binomial theorem states that for any nonnegative integer n and any numbers a and b, (a + b)^n equals the sum from k = 0 to n of C(n, k) a^(n-k) b^k, where C(n, k) is the binomial coefficient n! / (k! (n-k)!). The coefficients form Pascal's triangle, with each row giving the coefficients in the expansion for the corresponding power. For example, (a + b)^4 = a^4 + 4 a^3 b + 6 a^2 b^2 + 4 a b^3 + b^4, with coefficients 1, 4, 6, 4, 1 from row 4 of Pascal's triangle. The theorem generalizes to negative and fractional exponents through the binomial series (1 + x)^alpha = sum from k = 0 to infinity of C(alpha, k) x^k, valid for |x| < 1 and any complex alpha, with C(alpha, k) = alpha(alpha - 1) ... (alpha - k + 1) / k! generalizing the binomial coefficient. The theorem is foundational to combinatorics, probability (binomial distributions), and analysis (Taylor expansions of (1 + x)^alpha).")
    r("the binomial theorem", "comparison",
      "The binomial theorem extends to the multinomial theorem, which expands (x_1 + x_2 + ... + x_m)^n in terms of multinomial coefficients C(n; k_1, k_2, ..., k_m) = n! / (k_1! k_2! ... k_m!) where the k_i are nonnegative integers summing to n. Compared with the binomial theorem (the m = 2 case), the multinomial covers expansions with more than two terms but uses the same combinatorial reasoning. Compared with Taylor series, the binomial series for (1 + x)^alpha is a special case in which the coefficients have a clean closed form, whereas general Taylor series may have arbitrary coefficients. Compared with generating functions in combinatorics, the binomial theorem provides one of the simplest examples: the generating function for binomial coefficients is (1 + x)^n. The theorem also connects to Pascal's triangle, which encodes combinatorial identities (Pascal's rule, hockey stick identity) and recursion in elegant geometric form.")
    r("the binomial theorem", "significance",
      "The binomial theorem matters because it provides a complete expansion of powers of binomial expressions, essential to algebra, combinatorics, probability, and calculus. In probability, the binomial distribution gives the probability of k successes in n independent trials with success probability p as C(n, k) p^k (1 - p)^(n-k); this distribution underlies hypothesis testing, quality control, and many other applications. In calculus, the binomial series expands (1 + x)^alpha for fractional exponents, used in approximations and series solutions. In combinatorics, binomial coefficients count subsets and arrangements, with identities like sum of C(n, k) over k equals 2^n encoding the total number of subsets of an n-set. In algebra and analysis, the theorem appears in derivations from Newton's law of cooling to perturbation expansions in physics. Pascal's triangle and the symmetry of the coefficients also have geometric and combinatorial interpretations that connect to many areas of mathematics.")
    r("the binomial theorem", "misconception",
      "A common misconception is that the binomial theorem only works for positive integer exponents; it works for any nonnegative integer in the finite-sum form, and the binomial series extends to any complex exponent for |x| < 1. Another misconception is that the binomial coefficients are only useful for expansions; they have rich combinatorial meaning (counting subsets, paths in a grid, balanced parentheses, and many other structures), and identities among them are the heart of combinatorial reasoning. People also sometimes assume that Pascal's triangle is just a curiosity; in fact, it encodes the recurrence C(n, k) = C(n-1, k-1) + C(n-1, k) that connects to combinatorial recursions throughout the field. Finally, students sometimes try to apply binomial expansion to (a - b)^n by simply changing signs naively; the correct expansion alternates signs as (-1)^k weights each term, producing for example (a - b)^4 = a^4 - 4 a^3 b + 6 a^2 b^2 - 4 a b^3 + b^4.")

    # ---- mathematical induction ----
    r("mathematical induction", "mechanism",
      "Mathematical induction works by establishing a chain of implications that proves a statement P(n) for all positive integers n in two steps. The base case verifies P(1) (or some other starting integer) directly. The inductive step assumes P(k) for an arbitrary k and uses that assumption to prove P(k + 1). Together these steps establish a domino chain: P(1) is true, so P(2) follows from the inductive step, then P(3) follows from P(2), and so on indefinitely. Strong induction (or complete induction) is a variant where the inductive step assumes P(j) for all j up to k and uses these to prove P(k + 1); strong induction has the same logical strength as ordinary induction but is often more convenient. Structural induction generalizes the technique to recursively defined data structures (trees, lists, formulas), with the base case covering the simplest structures and the inductive step covering structures built from smaller ones. Induction is the standard tool for proving statements involving natural numbers or recursively defined objects.")
    r("mathematical induction", "significance",
      "Mathematical induction matters because it is the fundamental tool for proving statements about infinite collections of natural numbers, recursive structures, and many algorithmic correctness properties. Without induction, statements like 'for all n, the sum of the first n positive integers is n(n+1)/2' cannot be proved with finitely many cases. Induction underpins essentially all of number theory, much of combinatorics, the analysis of recursive algorithms, formal verification of programs, and the construction of recursive data types in computer science. The technique formalizes the intuition that if a property is true for a starting value and propagates from each integer to the next, it must be true for all integers reachable from the start. Variants of induction (transfinite induction, well-founded induction, structural induction) extend the same logical pattern to richer settings, making induction one of the most broadly applicable proof techniques in mathematics.")
    r("mathematical induction", "comparison",
      "Mathematical induction differs from direct proof by handling infinite collections through a finite two-step argument rather than by proving each case individually. It differs from proof by contradiction in being constructive in the sense that it produces a chain of implications without invoking impossibility. Compared with strong induction, ordinary induction uses only the immediately preceding case, while strong induction uses all preceding cases; the two are logically equivalent but strong induction is sometimes more natural. Compared with structural induction on recursive data types, mathematical induction on natural numbers is a special case where the structure is the chain 0, S(0), S(S(0)), .... Compared with proofs by exhaustion (checking finitely many cases), induction is required when the statement covers infinitely many cases. Compared with proofs using infinite descent (a variant where one assumes a counterexample and constructs an ever-smaller one), induction proceeds upward from a base case rather than seeking a contradiction.")
    r("mathematical induction", "misconception",
      "A common misconception is that the inductive hypothesis is something to be proved independently; it is assumed within the inductive step, and the entire proof shows that the assumption suffices to prove P(k+1), not that the assumption is true on its own. Another misconception is that induction proves the statement only for some particular n (perhaps a large one); the chain of implications, once both steps are established, proves the statement for all positive integers from the base case onward, no matter how large. People also sometimes confuse a proof by induction with a proof by example or by analogy; verifying P(1), P(2), P(3) and concluding P(n) for all n is not induction unless the inductive step is also proved. Finally, the assumption that all statements about natural numbers can be proved by induction is wrong; Godel's incompleteness theorems show that some statements expressible in the language of arithmetic cannot be proved within standard axiom systems, including Peano arithmetic with induction.")
