"""Part 3: science entries continued."""


def register_part_3(r):
    # ---- the greenhouse effect ----
    r("the greenhouse effect", "mechanism",
      "The greenhouse effect works because Earth's atmosphere is largely transparent to the visible and near-infrared radiation arriving from the Sun but partially opaque to the longer-wavelength infrared radiation that the warmed Earth emits back to space. Sunlight passes through the atmosphere and warms the surface. The surface, at roughly 288 K, radiates thermal infrared in the 4-100 micrometer range. Greenhouse gases like water vapor, carbon dioxide, methane, and nitrous oxide have molecular vibrational and rotational modes whose frequencies happen to match parts of this infrared spectrum, so they absorb outgoing infrared photons and re-emit them in random directions, with about half going back toward the surface. The downward re-emission warms the surface beyond what direct sunlight alone would produce, raising Earth's mean surface temperature by roughly 33 K above the bare radiative-equilibrium value of about 255 K. Adding more greenhouse gases thickens this insulating blanket and raises the equilibrium surface temperature.")
    r("the greenhouse effect", "example",
      "A direct example is comparing Earth, Venus, and the Moon. The Moon, at essentially the same distance from the Sun as Earth, has no atmosphere and a mean surface temperature near 250 K with extreme day-night swings. Earth, with its modest greenhouse atmosphere, sits about 33 K warmer at 288 K and has comparatively gentle diurnal swings. Venus, with an atmosphere 90 times denser than Earth's and composed mostly of CO2, has a surface temperature of about 740 K, hot enough to melt lead, despite reflecting more sunlight than Earth thanks to its bright cloud deck. The Venusian extreme is a runaway greenhouse, in which a hot surface evaporates more water that adds to the greenhouse effect that further heats the surface, eventually losing all its surface water to space. The comparison shows that a planet's mean surface temperature depends on the composition and thickness of its atmosphere as much as on its distance from its star.")

    # ---- the carbon cycle ----
    r("the carbon cycle", "definition",
      "The carbon cycle is the global biogeochemical movement of carbon atoms among Earth's atmosphere, oceans, biosphere, soils, and rocks. Carbon transfers among these reservoirs through processes including photosynthesis (atmosphere into plants and algae), respiration (organisms back to atmosphere), decomposition (dead organisms into soil and atmosphere), ocean-atmosphere gas exchange (dissolution of CO2 in seawater and outgassing), and over geological timescales, weathering of silicate rocks, burial of organic matter, and volcanic outgassing. The fast components of the cycle exchange carbon on timescales of years to centuries, while geological components operate over thousands to millions of years. Total atmospheric CO2 has grown from about 280 ppm in the pre-industrial era to over 420 ppm today, primarily from fossil fuel combustion that liberates carbon stored in geological reservoirs over hundreds of millions of years.")
    r("the carbon cycle", "mechanism",
      "Carbon flows through the cycle along multiple coupled pathways. In the fast biological cycle, plants and phytoplankton fix atmospheric CO2 into organic compounds via photosynthesis; respiration by plants, animals, and microbes returns CO2 to the atmosphere on timescales of days to centuries. In the ocean, CO2 dissolves into surface waters where it equilibrates with bicarbonate and carbonate ions; thermohaline circulation transports dissolved carbon into the deep ocean on timescales of about 1000 years. The slow geological cycle involves silicate weathering: CO2 dissolved in rainwater reacts with silicate rocks, eventually delivering carbonates to the ocean where they precipitate and form sedimentary rocks. Volcanic and tectonic activity returns this stored carbon to the atmosphere over millions of years. Anthropogenic emissions from burning fossil fuels and land-use change add about 11 GtC per year, perturbing the cycle's steady state and accumulating in the atmosphere, ocean, and biosphere.")
    r("the carbon cycle", "example",
      "A clear illustration is the seasonal CO2 oscillation visible in the Mauna Loa atmospheric record. Each year, atmospheric CO2 drops by about 6-7 ppm during Northern Hemisphere spring and summer as land plants photosynthesize and accumulate biomass, then rises by about the same amount during fall and winter as decomposition releases CO2. The Northern Hemisphere dominates because it has more land and forest than the Southern. Superimposed on this annual breathing is a steady upward trend driven by fossil fuel emissions. The same record shows the asymmetry growing as Northern forests absorb a slightly larger fraction of summer emissions and decomposition releases a slightly larger pulse each fall, with shifts attributed to warming. The Keeling curve, named after Charles David Keeling who began the measurements in 1958, is one of the cleanest examples of a coupled biogeochemical cycle interacting with human activity at the global scale.")
    r("the carbon cycle", "significance",
      "The carbon cycle matters because changes in its operation directly determine atmospheric CO2 and hence climate. Over Earth's history, slow shifts in the balance between weathering and volcanic outgassing have driven both icehouse and hothouse climates, with CO2 levels ranging from below 200 ppm during ice ages to thousands of ppm during much of the deep past. Today's anthropogenic perturbation is delivering CO2 to the atmosphere far faster than natural processes can absorb it, leading to rising CO2 and global warming. About a quarter of emissions are absorbed by the ocean (causing acidification), about a quarter by land vegetation, and the remaining half stays in the atmosphere. Understanding the carbon cycle is essential for projecting future climate, evaluating proposed mitigation strategies (forest restoration, soil carbon sequestration, ocean alkalinity enhancement, direct air capture), and managing the risks associated with feedbacks like permafrost thaw and forest dieback that could amplify the human-caused perturbation.")

    # ---- the water cycle ----
    r("the water cycle", "definition",
      "The water cycle is the continuous global movement of water among the oceans, atmosphere, land surface, and subsurface, driven by solar energy and gravity. Water evaporates from ocean and land surfaces, condenses in the atmosphere to form clouds, falls back as precipitation (rain, snow, sleet, hail), runs off across land into rivers and back to the ocean, infiltrates soil and rock to become groundwater, and is taken up and transpired by plants. Total water on Earth is essentially constant; the cycle redistributes it among reservoirs at vastly different rates. Mean atmospheric residence time is about 9 days, soil moisture about a few weeks, rivers about 16 days, lakes about 100 years, and deep groundwater and ice sheets thousands to hundreds of thousands of years. The cycle delivers about 500,000 cubic kilometers of water from ocean evaporation per year, of which most falls back into the ocean and the rest precipitates over land.")
    r("the water cycle", "comparison",
      "The water cycle differs from the carbon cycle in that water is overwhelmingly stored on Earth's surface (oceans, ice, lakes, groundwater) rather than in the deep crust, with only a tiny fraction in the atmosphere at any moment. It differs from the nitrogen cycle in that water moves predominantly through phase changes rather than chemical transformations, and from the rock cycle in operating on timescales of days to thousands of years rather than millions. Compared with energy budgets, the water cycle moves enormous amounts of latent heat: evaporation from tropical oceans absorbs solar energy and releases it at higher latitudes when condensation occurs, transporting heat poleward and powering atmospheric circulation. The cycle also differs from purely physical fluid flow in coupling tightly with the biosphere: vegetation transpires substantial amounts of water, with the Amazon, for example, generating much of its own rainfall through transpiration recycling.")
    r("the water cycle", "example",
      "A useful concrete example is the journey of a water molecule starting in the tropical Atlantic Ocean. Solar energy evaporates the molecule, and trade winds carry it west toward South America. Over the Amazon basin, the molecule may participate in cloud formation and fall as rain, where it is taken up by tree roots and eventually transpired through leaves back into the atmosphere. After several cycles of precipitation and transpiration over the basin (this internal recycling makes the Amazon a partial moisture engine), the molecule may eventually flow into the Amazon River as runoff, traveling thousands of kilometers to the Atlantic. From the river mouth, the molecule joins the ocean and may be carried by currents to higher latitudes before evaporating again somewhere new. The full circuit illustrates the global, continental, and local scales over which water moves and the way each segment of the cycle is coupled to climate, ecosystems, and human water resources.")
    r("the water cycle", "significance",
      "The water cycle matters because it determines freshwater availability for ecosystems, agriculture, and human use; redistributes heat across the planet; carves landscapes through erosion; and is being perturbed by climate change with serious consequences. Warmer atmospheres hold more water vapor (about 7 percent more per Kelvin of warming), intensifying both droughts and heavy rainfall events, while shifting precipitation patterns reorganize where water is available. Glacier and snowpack reservoirs are critical to seasonal water supply for many populations and are shrinking as warming proceeds. Groundwater is being pumped faster than recharge in many agricultural regions, depleting an effectively non-renewable resource at human timescales. The cycle is also central to ecosystems: river flow regimes, soil moisture, and atmospheric humidity shape where forests, grasslands, and wetlands can exist. Understanding and managing the water cycle is foundational to water security, food production, and climate adaptation in the coming decades.")
    r("the water cycle", "misconception",
      "A common misconception is that 'new' water can be created or that pollution permanently removes water from the cycle; in fact, water molecules are essentially conserved and the cycle continually purifies them through evaporation, leaving contaminants behind. Another misconception is that all rainwater eventually returns to the ocean; substantial amounts re-evaporate from soil, lakes, and vegetation back to the atmosphere without ever reaching the sea. People often imagine groundwater as underground rivers; most groundwater is actually held in tiny pore spaces between grains of sand, gravel, or rock and moves quite slowly (centimeters to meters per day in productive aquifers, much less in tight clays). The popular image of clouds as containers of liquid water also misleads: clouds are mostly water vapor with suspended droplets or ice crystals, and the precipitation that falls is only a small fraction of the water in the air at any moment. Finally, the assumption that the cycle is in steady state at all timescales is wrong; long-term shifts driven by climate, land use, and water extraction are reshaping the cycle in measurable ways.")

    # ---- ocean currents and thermohaline circulation ----
    r("ocean currents and thermohaline circulation", "significance",
      "Thermohaline circulation matters because it transports enormous amounts of heat and dissolved gases around the planet, regulating regional climate, marine ecosystems, and the ocean's role in the carbon cycle. The Atlantic Meridional Overturning Circulation (AMOC), of which the Gulf Stream is the warm surface arm, carries about 1.3 petawatts of heat northward, keeping Northwest Europe several degrees warmer than equivalent latitudes elsewhere. As surface waters cool and become denser in the North Atlantic, they sink to depths of 2-3 kilometers and flow southward as North Atlantic Deep Water, eventually upwelling in the Southern Ocean and Indian/Pacific oceans on timescales of about 1000 years. The circulation distributes nutrients that fuel marine productivity and oxygenates the deep ocean. Climate models suggest the AMOC has weakened modestly over recent decades and could weaken further as freshwater from melting Greenland ice dilutes surface salinity, reducing density-driven sinking. A substantial slowdown would have major consequences for European climate, sea level on the eastern North American coast, tropical rain belts, and ocean carbon uptake.")

    # ---- El Nino and La Nina ----
    r("El Nino and La Nina", "significance",
      "El Nino and La Nina matter because the cyclic warming and cooling of the equatorial Pacific drives global weather anomalies that affect agriculture, water resources, and disaster risk on every continent. During El Nino, weakened easterly trade winds let warm water pool in the eastern Pacific, suppressing the usual cold upwelling off Peru, shifting the rising branch of the Walker circulation eastward, and producing predictable patterns: drought in Australia, Indonesia, and southern Africa; heavy rainfall in Peru, Ecuador, and parts of the southern United States; warmer winters in northern Asia and parts of North America; and a global temperature boost. La Nina enforces the opposite phase: stronger trade winds, colder eastern Pacific, drought in the southern United States, heavy rainfall in Indonesia and northern Australia, and a slight global temperature drag. The Pacific fishery off South America collapses during strong El Ninos, costing billions. Forecasting the cycle several months in advance is now possible, allowing governments and farmers to adapt planting and water-allocation decisions.")
    r("El Nino and La Nina", "comparison",
      "El Nino and La Nina are opposite phases of the El Nino-Southern Oscillation (ENSO), differing in the temperature anomaly pattern of the equatorial Pacific and the corresponding atmospheric circulation. Compared to the neutral state, El Nino features warmer-than-average eastern equatorial Pacific waters and weaker trade winds, while La Nina features cooler-than-average eastern Pacific waters and strengthened trade winds. Compared with other ocean-atmosphere oscillations like the North Atlantic Oscillation, the Pacific Decadal Oscillation, or the Atlantic Multidecadal Oscillation, ENSO operates on shorter timescales (typically 2-7 years between events) and produces stronger global weather impacts because of the Pacific's vast size and the way its atmospheric responses propagate via tropical-extratropical teleconnections. Compared with each other, El Nino events tend to be slightly stronger and more variable, while La Nina events are typically more symmetric and somewhat more persistent, though strong individual events of either type can occur and the dynamics are not perfectly mirror-symmetric.")
    r("El Nino and La Nina", "example",
      "The 1997-1998 El Nino is one of the strongest on record and offers a vivid example of the global reach of the phenomenon. Sea surface temperatures in the eastern equatorial Pacific climbed more than 4 degrees Celsius above normal. Severe drought struck Indonesia and the Amazon, with major wildfires releasing huge amounts of CO2 and smoke. Heavy rainfall and flooding hit Peru, Ecuador, California, and the southeastern United States. The Asian summer monsoon was suppressed. Coral reefs across the Pacific bleached as warm water persisted, killing about 16 percent of the world's reef-building corals globally. The Peruvian anchoveta fishery collapsed. Total global damages exceeded 35 billion dollars and the event contributed to 1998 becoming the warmest year then on record. The 2015-2016 El Nino was comparable in magnitude and produced similar patterns of impact, including widespread coral bleaching, drought-driven food crises in southern Africa, and another global temperature peak.")

    # ---- planetary atmospheres ----
    r("planetary atmospheres", "definition",
      "A planetary atmosphere is the layer of gases gravitationally bound to a planet (or moon) that surrounds its solid or liquid surface. Composition, density, and structure vary enormously: Mercury has only a tenuous exosphere, Venus has a CO2-dominated atmosphere about 90 times denser than Earth's, Earth's nitrogen-oxygen atmosphere supports liquid water and life, Mars has a thin CO2 atmosphere about 1 percent of Earth's pressure, the gas giants (Jupiter, Saturn) are mostly hydrogen and helium with no defined surface, and Titan has a thick nitrogen-methane atmosphere. Atmospheric properties depend on the planet's mass and gravity (which determine retention), surface temperature (which sets atmospheric scale height and which gases can escape thermally), magnetic field (which protects against solar wind stripping), and history of volcanic outgassing and biological processing. Atmospheres mediate climate, weather, surface chemistry, and habitability.")
    r("planetary atmospheres", "example",
      "Titan, Saturn's largest moon, is a striking example of an exotic planetary atmosphere. It is the only moon in the solar system with a substantial atmosphere, composed of about 95 percent nitrogen and 5 percent methane, with a surface pressure 50 percent higher than Earth's. The thick atmosphere is opaque to visible light because of an organic haze produced by photochemistry of methane and nitrogen high in the atmosphere, raining down as Titan tholins. Surface temperatures around 94 K (-179 C) are cold enough that methane and ethane exist as liquids on the surface, forming lakes, rivers, and seas with shorelines, deltas, and probably waves, all imaged by the Cassini-Huygens mission. The hydrological cycle on Titan involves methane evaporation, cloud formation, and methane rain, an alien analog of Earth's water cycle running with hydrocarbons instead. Titan demonstrates that planetary atmospheres can support complex weather and surface processes very different from those on Earth.")
    r("planetary atmospheres", "misconception",
      "A common misconception is that atmospheric composition simply reflects the composition of the planet's surface or interior. Earth's free oxygen, for example, is nearly all biological in origin, accumulated by photosynthesis over billions of years; without life, Earth's atmosphere would be much closer to that of Venus or Mars in being CO2-dominated. Another misconception is that the absence of a thick atmosphere means a planet is small; the Moon is small, but Mars has only a thin atmosphere despite being much larger, primarily because its weak magnetic field allowed solar wind stripping over billions of years. People also sometimes conflate atmospheric pressure with atmospheric mass per area; on Mars, both are very low, but on Venus, the dense atmosphere produces enormous surface pressure even at the same gravitational acceleration. Finally, atmospheres are not static; they constantly leak hydrogen and other light gases to space, and over geological time their composition evolves through outgassing, escape, weathering, and (on Earth) biological activity.")
    r("planetary atmospheres", "significance",
      "Planetary atmospheres matter because they regulate surface temperature through the greenhouse effect, govern surface weather and climate, mediate the planet's interaction with stellar radiation, and are central to questions of habitability. The presence and composition of an atmosphere determines whether liquid water can exist on a surface, whether ultraviolet radiation reaches the surface in lethal amounts, and whether erosion and chemistry shape the landscape. Comparative planetology has used Earth, Venus, and Mars as a natural experiment in how atmospheric composition and history influence outcome: similar starting conditions can lead to a runaway greenhouse hellscape, a frozen desert, or a habitable biosphere depending on water content, biological processing, and history. Studying exoplanet atmospheres is now possible by transit spectroscopy with telescopes like JWST, and is one of the principal paths to identifying potentially habitable or even inhabited worlds beyond our solar system, with biosignatures sought in oxygen, methane, water vapor, and other gases out of expected geochemical equilibrium.")

    # ---- the life cycle of stars ----
    r("the life cycle of stars", "definition",
      "A star's life cycle is the sequence of evolutionary stages from formation in a molecular cloud through its main fuel-burning life and ending in a final remnant whose nature depends primarily on the star's initial mass. Stars form when dense regions of giant molecular clouds collapse under gravity, igniting hydrogen fusion in their cores when the central temperature reaches about 10 million K. Most of a star's life is spent on the main sequence fusing hydrogen into helium. When core hydrogen is exhausted, the star expands and cools to become a red giant or supergiant, then begins fusing heavier elements. The endpoint depends on mass: stars below about 8 solar masses shed their outer layers as a planetary nebula, leaving a white dwarf; stars between roughly 8 and 25 solar masses end in a core-collapse supernova leaving a neutron star; the most massive stars collapse directly into stellar-mass black holes. Lifetimes range from millions of years for the most massive stars to trillions of years for the smallest red dwarfs.")
    r("the life cycle of stars", "comparison",
      "Different stellar masses follow markedly different evolutionary paths and timescales. A star like the Sun (1 solar mass) lives about 10 billion years on the main sequence, swells into a red giant, sheds its envelope as a planetary nebula, and ends as a white dwarf cooling for trillions of years. A red dwarf (0.1-0.5 solar masses) burns hydrogen so slowly that it lives 100 billion to 10 trillion years and never expands much before fading. A massive O or B star (10-50 solar masses) burns through its hydrogen in just millions of years, evolves through helium, carbon, oxygen, neon, silicon, and iron core fusion in successively shorter stages, and ends in a core-collapse supernova that leaves a neutron star or black hole. Compared with binary stars where mass transfer can radically alter evolution (producing classical novae, type Ia supernovae, X-ray binaries, and many exotic objects), single-star evolution is the simpler baseline. Compared with brown dwarfs (failed stars below 0.075 solar masses), proper stars sustain prolonged hydrogen fusion.")
    r("the life cycle of stars", "significance",
      "Stellar life cycles matter because stars produce essentially all the chemical elements heavier than helium, distribute them through stellar winds and supernovae, and provide the energy that powers planetary climates and life. The carbon in your DNA, the oxygen you breathe, the iron in your blood, and the calcium in your bones were all forged in the cores of stars or in the explosions that ended their lives, then returned to interstellar space and eventually incorporated into the gas cloud that formed the solar system. Massive stars enrich galaxies in heavy elements over cosmic time, enabling each new generation of stars and planets to form with more raw material for rocky worlds and biochemistry. Supernovae also drive shocks that compress nearby gas clouds, triggering further star formation, and produce neutron stars whose mergers are the principal source of the heaviest elements like gold and platinum. Understanding stellar evolution underpins cosmology, galactic archaeology, exoplanet astrobiology, and the broader history of cosmic chemical enrichment.")

    # ---- star formation and stellar nucleosynthesis ----
    r("star formation and stellar nucleosynthesis", "definition",
      "Star formation is the process by which dense regions of interstellar gas (mostly hydrogen and helium with traces of dust and heavier elements) collapse under gravity to form new stars. Stellar nucleosynthesis is the set of nuclear reactions inside those stars that fuse light nuclei into heavier ones, releasing energy that supports the star against further gravitational collapse and over cosmic time enriches the universe with elements beyond hydrogen and helium. Star formation typically occurs in giant molecular clouds where dense cores fragment and contract over hundreds of thousands to millions of years, eventually reaching central temperatures hot enough to ignite hydrogen burning. Nucleosynthesis proceeds through a sequence of fusion stages (hydrogen to helium, then helium to carbon and oxygen, then in massive stars carbon and oxygen to neon, magnesium, silicon, and finally up to iron), with the heaviest elements forged in supernovae and neutron-star mergers via rapid neutron-capture processes.")
    r("star formation and stellar nucleosynthesis", "comparison",
      "Different processes synthesize different elements. Hydrogen and helium were almost entirely produced in Big Bang nucleosynthesis in the first few minutes after the Big Bang. Lithium, beryllium, and boron come mostly from cosmic-ray spallation. Carbon through iron are produced by fusion in stellar cores: carbon and oxygen from helium burning, neon and magnesium from carbon burning, and so on through silicon to iron in successive shells of massive stars. Beyond iron, fusion no longer releases energy, so heavier elements are made by neutron capture: the slow s-process in asymptotic giant branch stars produces elements up to bismuth, while the rapid r-process in neutron-star mergers (and possibly some supernovae) makes elements up to uranium and beyond. Compared with these stellar sources, type Ia supernovae are the dominant producers of iron-peak elements like nickel and iron in galaxies, while core-collapse supernovae contribute oxygen and other intermediate-mass elements.")
    r("star formation and stellar nucleosynthesis", "example",
      "The fusion chain in the Sun is a clear example of stellar nucleosynthesis. The Sun's core, at about 15 million K, runs the proton-proton chain. Two protons collide and one converts to a neutron via the weak interaction, producing a deuteron, a positron, and a neutrino; this slow rate-limiting step gives the Sun its long lifetime. The deuteron quickly captures another proton to form helium-3 with the release of a gamma ray. Two helium-3 nuclei then combine to form helium-4 plus two protons. The net reaction converts four protons into a helium-4 nucleus, two positrons, two neutrinos, and energy of about 26.7 MeV per cycle, with the mass deficit appearing as photon and particle energy. Heavier stars run the catalytic CNO cycle that uses carbon, nitrogen, and oxygen as catalysts to fuse four protons into helium more rapidly. The Sun fuses about 600 million tons of hydrogen per second, releasing the energy that powers all life on Earth.")
    r("star formation and stellar nucleosynthesis", "significance",
      "Stellar nucleosynthesis matters because almost every element heavier than helium was created in stars and distributed through stellar winds and supernova ejecta into interstellar space, where it became the raw material for new stars and planets. The composition of Earth, the molecules of life, and the elements in your body are products of generations of stellar processing over the 13.8-billion-year history of the universe. The slow enrichment of galaxies with heavy elements (metallicity in astronomical jargon) over cosmic time has made later generations of stars and planets chemically richer than the first, with implications for planet formation (rocky planets need silicon, iron, and other heavy elements), atmospheric chemistry, and the prerequisites for life. Reconstructing the history of nucleosynthesis through stellar abundances and isotope ratios is the basis of galactic archaeology, which traces the assembly of galaxies and the origin of elements over cosmic time.")

    # ---- the Kuiper belt vs Oort cloud ----
    r("the Kuiper belt vs Oort cloud", "definition",
      "The Kuiper belt and Oort cloud are two reservoirs of icy small bodies in the outer solar system, distinguished by location, structure, and origin. The Kuiper belt is a doughnut-shaped region beyond Neptune's orbit, extending from about 30 to 50 astronomical units, populated by tens of thousands of cataloged objects (and many more uncataloged) including Pluto, Eris, Makemake, and Haumea. Its members orbit roughly in the plane of the planets and likely formed near their current locations from the protoplanetary disk's outer reaches. The Oort cloud, by contrast, is a hypothesized roughly spherical shell of icy bodies extending from perhaps 2,000 to 100,000 astronomical units, far beyond the Kuiper belt and approaching interstellar distances. Its members are presumed to have formed in the giant-planet region and been gravitationally scattered outward, ending up loosely bound to the Sun. Long-period comets are believed to originate in the Oort cloud; short-period comets like Halley likely come from the Kuiper belt or the related scattered disk.")
    r("the Kuiper belt vs Oort cloud", "comparison",
      "The Kuiper belt and Oort cloud differ in distance, shape, and dynamical properties. The Kuiper belt is about 30-50 AU from the Sun, flat (concentrated near the ecliptic plane), and its objects have orbital periods of roughly 200-1000 years. The Oort cloud spans roughly 2,000-100,000 AU, is approximately spherical, and its objects have orbital periods of millions of years. Kuiper belt objects experience moderate gravitational influence from the giant planets, especially Neptune, with many in resonant orbits (Pluto, the prototypical plutino, is in 3:2 resonance with Neptune). Oort cloud objects are so distant that their orbits are perturbed by passing stars and galactic tides, occasionally sending one inward as a long-period comet. The total mass of the Kuiper belt is estimated at a few percent of Earth's mass; the Oort cloud is thought to contain trillions of comets totaling perhaps several Earth masses, though the population is poorly constrained because individual objects are not directly observable at those distances.")
    r("the Kuiper belt vs Oort cloud", "example",
      "Pluto is the most famous Kuiper belt object. Discovered in 1930 and reclassified from planet to dwarf planet in 2006 after the recognition that it is one of many similar bodies, Pluto orbits the Sun every 248 years on a moderately eccentric and inclined orbit that brings it inside Neptune's orbit briefly each cycle. The 2015 New Horizons flyby revealed a complex world with nitrogen-ice plains, water-ice mountains, possible cryovolcanism, and a thin atmosphere. For the Oort cloud, the canonical example is the long-period comet C/1995 O1 Hale-Bopp, with an orbital period of about 2500 years on a highly eccentric path that took it from past Pluto's orbit at aphelion to inside Earth's orbit at perihelion. Its bright apparition in 1996-1997 made it one of the most observed comets in history. Hale-Bopp's long period and high inclination are characteristic of objects originating in the Oort cloud.")
    r("the Kuiper belt vs Oort cloud", "mechanism",
      "These reservoirs work as long-term sources of comets and as fossils of the early solar system. Kuiper belt objects can be perturbed by encounters with Neptune or by orbital resonances into more eccentric orbits that eventually become short-period comets in the inner solar system, with typical orbital periods under 200 years. The scattered disk, a related but more dynamically excited population beyond Neptune, is thought to be the principal source of these comets. Oort cloud objects, far from the Sun, are weakly bound and gravitationally perturbed by passing stars and the tidal field of the Milky Way, occasionally being nudged into elongated orbits that bring them into the inner solar system as long-period comets. Once a comet enters the inner solar system, solar heating sublimates ices, producing the characteristic coma and tail. Many comets are captured into shorter periods, eject material to space, or break apart on close approaches.")
    r("the Kuiper belt vs Oort cloud", "significance",
      "These distant reservoirs matter because they preserve material from the formation of the solar system in a relatively unaltered state, providing direct samples of early conditions. Comets carry primitive ices (water, methane, ammonia, CO, CO2) and organic compounds that have not been substantially heated or chemically altered, offering a window into the chemistry of the protoplanetary disk and the origin of volatiles delivered to the inner planets. Some early Earth water and prebiotic chemistry may have come from cometary impacts, though this remains debated. The Oort cloud also serves as a source of impactors that occasionally devastate inner planets; the Chicxulub impact 66 million years ago that contributed to the extinction of non-avian dinosaurs may have originated in either the asteroid belt or the outer reservoirs. Cataloging Kuiper belt objects has revealed a complex population dynamics tied to the migration history of the giant planets, and proposed missions to the Oort cloud aim to sample this most remote of solar system frontiers.")

    # ---- the Milankovitch cycles ----
    r("the Milankovitch cycles", "definition",
      "The Milankovitch cycles are quasi-periodic variations in Earth's orbital and rotational parameters that drive long-term changes in the distribution of solar radiation across the planet's surface and influence ice ages over tens to hundreds of thousands of years. Three orbital changes are most important: eccentricity (the shape of Earth's orbit, varying from nearly circular to slightly elliptical with periods around 100,000 and 400,000 years), obliquity (the tilt of Earth's rotation axis, varying between about 22.1 and 24.5 degrees over 41,000 years), and precession (the slow wobble of Earth's rotation axis on a 26,000-year cycle, combined with the precession of the orbital ellipse to give a climate-relevant period of about 19,000-23,000 years). These do not change the total annual sunlight much but redistribute it between seasons and latitudes, with the high northern latitudes' summer insolation being especially important for triggering ice sheet growth or retreat.")
    r("the Milankovitch cycles", "mechanism",
      "The mechanism by which Milankovitch cycles drive climate involves their effect on summer insolation at high northern latitudes, where most of the world's continental land area suitable for hosting large ice sheets is located. Cool summers allow winter snow to persist year-round, accumulating into ice sheets; warm summers melt back the previous winter's snow and inhibit ice growth. When Earth's axis is tilted less and orbital eccentricity is high in a phase that puts northern summer near aphelion, summer insolation is minimized at high northern latitudes, favoring ice sheet growth; the opposite phase favors retreat. The orbital forcing is small in absolute terms (a few percent change in summer insolation) but is amplified by feedbacks: growing ice sheets increase albedo (reflectivity), reducing absorbed sunlight; sea ice expansion does the same; lower temperatures reduce atmospheric water vapor and CO2, weakening the greenhouse effect; and dust and aerosol changes alter atmospheric heating. The combined feedbacks turn modest orbital nudges into the dramatic climate swings of the Pleistocene ice ages.")

    # ---- exoplanet detection methods ----
    r("exoplanet detection methods", "comparison",
      "Different exoplanet detection methods have complementary strengths and biases. The transit method (used by Kepler and TESS) detects planets by the slight dip in a star's brightness as a planet passes in front of it; the method requires the orbit to be nearly edge-on from our viewpoint, biases toward larger and shorter-period planets, but yields planet radii and orbital periods. The radial velocity method measures Doppler shifts in the star's spectrum as it wobbles around the system's center of mass; it works for any orbital orientation, biases toward massive close-in planets, and yields a minimum mass (sin i ambiguity unless transit is also seen). Direct imaging captures actual photons from the planet, mostly working for young, hot, widely separated giants where the contrast with the star is least extreme. Microlensing detects the brief brightening of a background star caused by gravitational lensing from an intervening star and its planet; sensitive to widely separated planets and even free-floating planets but each event is unrepeatable. Astrometry measures the star's tiny positional wobble against background stars; the Gaia mission is now starting to deliver such detections.")
    r("exoplanet detection methods", "significance",
      "Exoplanet detection matters because it has transformed our understanding of planetary systems and put astrobiology on an empirical footing. Before the first confirmed exoplanet around a Sun-like star (51 Pegasi b in 1995), planetary systems were known only from one example. Today over 5,000 exoplanets are confirmed, with statistics suggesting most stars host at least one planet and small rocky planets are common. The diversity of discovered planets (hot Jupiters, super-Earths, mini-Neptunes, ultra-short-period planets, circumbinary planets) has overturned models of planet formation that were tuned to our solar system. The transit method allows follow-up spectroscopy of planetary atmospheres, with JWST now characterizing atmospheres of warm Neptunes, super-Earths, and even some smaller worlds. The pursuit of potentially habitable worlds in the temperate zones of nearby stars is now a central goal of astronomy, and the first detection of an unambiguous biosignature in an exoplanet atmosphere would transform our understanding of life in the universe.")
    r("exoplanet detection methods", "misconception",
      "A common misconception is that we directly photograph most discovered exoplanets; the vast majority are detected indirectly through their effects on their stars (transit dimming, Doppler wobble) and only a few dozen, mostly young hot giants far from their stars, have been directly imaged. Another misconception is that 'Earth-like' as commonly used in exoplanet news means similar to Earth in any deep sense; usually it means roughly Earth-sized in some habitable zone, with no information yet about atmosphere, surface conditions, or composition beyond rough density estimates from combined transit-radial velocity measurements. People also sometimes imagine that the detection of a planet in the habitable zone implies surface liquid water; the habitable zone is a rough boundary based on stellar flux and assumed atmospheric properties, with actual habitability depending on many factors not yet measurable for most planets. Finally, the term 'goldilocks zone' suggests a knife-edge boundary, but in reality habitability depends on a complex combination of factors and many real planets in the zone may not be habitable at all.")

    # ---- earthquake mechanics ----
    r("earthquake mechanics", "definition",
      "An earthquake is the sudden release of stored elastic strain in Earth's crust along a fracture in the rock, called a fault, producing seismic waves that radiate outward and shake the ground. The vast majority of earthquakes occur at the boundaries of tectonic plates, where the plates' continuous motion (typically a few centimeters per year) loads stress into the locked sections of fault until the rock can no longer hold and slips. The point underground where slip begins is called the hypocenter or focus; the point on the surface directly above is the epicenter. Earthquake magnitude (commonly the moment magnitude scale Mw) is a logarithmic measure of the seismic energy released, so each unit higher represents about 32 times more energy. Most earthquakes are too small to feel; about a million per year worldwide are detectable by instruments, but only a handful per decade reach magnitude 8 or above with the potential to devastate large regions.")
    r("earthquake mechanics", "mechanism",
      "Mechanically, earthquakes follow elastic rebound: tectonic plate motion gradually deforms rocks adjacent to a locked fault, accumulating strain energy elastically; when the stress exceeds the friction holding the fault, the fault slips suddenly, the rocks snap back toward an unstressed state, and the released elastic energy radiates as seismic waves. The rupture begins at the hypocenter and propagates outward along the fault plane at speeds of about 2-3 km/s, with slip durations of seconds for small events and minutes for the largest. Several wave types radiate: P-waves (primary, compressional, fastest), S-waves (secondary, shear, slower), and surface waves (Love and Rayleigh, slower still and most damaging because they have larger amplitudes at the surface). Aftershocks follow as the surrounding crust adjusts to the new stress configuration, with a characteristic Omori law decay in rate over time. Foreshocks may precede a main event but are not reliably distinguishable from independent activity in advance.")
    r("earthquake mechanics", "comparison",
      "Different fault types produce different earthquake characteristics. Strike-slip faults (like the San Andreas) accommodate horizontal motion as plates slide past each other; their earthquakes can be very large but typically do not produce tsunamis since the seafloor displaces little vertically. Normal faults accommodate extension where plates pull apart, with the hanging wall dropping relative to the footwall; earthquakes tend to be moderate in size. Reverse and thrust faults accommodate compression as plates collide, with the hanging wall pushed up over the footwall; subduction zone megathrust earthquakes here are the largest known (the 1960 Chilean Mw 9.5, the 2011 Tohoku Mw 9.1) and frequently produce tsunamis from vertical seafloor displacement. Compared with intraplate earthquakes occurring within plates rather than at boundaries, plate-boundary earthquakes are far more common but intraplate events can still be devastating because regional building codes are often lax. Volcanic earthquakes have a different mechanism, involving magma movement and rock fracturing around magma bodies.")

    # ---- volcanic eruption types ----
    r("volcanic eruption types", "definition",
      "Volcanic eruption types are categories of volcanic activity distinguished by the explosivity, eruption style, and material erupted. The Volcanic Explosivity Index (VEI) ranks eruptions on a logarithmic scale from 0 (gentle effusive activity) to 8 (cataclysmic super-eruptions). Major styles include Hawaiian (low-viscosity basaltic lava flows with little explosivity), Strombolian (mild explosive bursts ejecting incandescent fragments), Vulcanian (more violent ash-bearing explosions), Plinian (sustained eruption columns reaching the stratosphere with widespread tephra fall), Pelean (collapsing eruption columns producing pyroclastic flows), and surtseyan (interaction of magma with water producing steam-driven explosions). Eruption type depends on magma composition (silica content controlling viscosity), gas content, and the geometry of the volcanic conduit. The most explosive eruptions arise from viscous silicic magmas with high gas content and narrow conduits that allow pressure to build before catastrophic release.")
    r("volcanic eruption types", "comparison",
      "Effusive and explosive eruptions differ fundamentally in style and hazard. Effusive eruptions like those of Hawaiian volcanoes (Kilauea, Mauna Loa) produce slow-moving lava flows that destroy property in their path but rarely kill anyone if evacuation is possible. Explosive eruptions like Plinian events (Vesuvius 79 CE, Mount St. Helens 1980, Pinatubo 1991) produce violently expanding eruption columns with ash fall, pyroclastic flows that race down slopes at hundreds of kilometers per hour with temperatures of hundreds of degrees, lahars (volcanic mudflows), and stratospheric aerosols that can affect global climate. Compared with each other, effusive eruptions are characteristic of basaltic volcanism associated with hotspots and divergent boundaries; explosive eruptions are characteristic of silicic volcanism at convergent boundaries where subducting plates produce water-rich, viscous magmas. Compared with phreatic and phreatomagmatic eruptions where water-magma interaction drives the explosivity, magmatic eruptions derive their energy from magmatic gas exsolution alone.")
    r("volcanic eruption types", "example",
      "The 1980 eruption of Mount St. Helens in Washington State illustrates a Plinian-style explosive eruption in vivid detail. Months of swelling on the volcano's north flank, driven by rising dacitic magma, culminated when a magnitude 5.1 earthquake triggered the largest landslide in recorded history. The collapse instantly depressurized the underlying magma, producing a lateral blast that flattened forest over 600 square kilometers. A vertical eruption column rose to 24 kilometers within minutes, and pyroclastic flows scoured the volcano's slopes. Lahars from melting ice and snow poured down river valleys, and ashfall coated states downwind. Fifty-seven people were killed despite extensive evacuation efforts. The eruption removed about 400 meters from the volcano's summit and reshaped the landscape. The same volcano had previously erupted effusively as well, illustrating that a single volcano can produce different eruption styles depending on the magma supplied to the system.")
    r("volcanic eruption types", "significance",
      "Eruption type matters because it determines hazard severity, recovery time, and global climate impact. Effusive eruptions threaten property and infrastructure but are usually slow enough for evacuation; explosive eruptions can kill thousands within minutes (Mount Pelee 1902 killed 28,000 in two minutes by pyroclastic flow) and produce regional and even global effects. Large Plinian eruptions inject sulfur dioxide into the stratosphere where it forms reflective sulfate aerosols, cooling Earth for months to years; the 1991 Pinatubo eruption lowered global mean temperatures by about 0.5 K for two years. Super-eruptions like Toba 74,000 years ago may have triggered abrupt climate disruptions and influenced human evolution. Volcanic ash poses serious risks to aviation, as illustrated by the 2010 Eyjafjallajokull eruption that grounded most European air traffic for days. Understanding eruption type from monitoring data and geological history is essential to risk communication, evacuation planning, and infrastructure protection in volcanic regions.")

    # ---- mineral formation ----
    r("mineral formation", "definition",
      "Mineral formation is the geological process by which solid, naturally occurring, inorganic crystalline substances with characteristic chemical compositions and crystal structures come into being. Minerals form from various source environments: cooling magma (igneous minerals like olivine, pyroxene, feldspar, quartz forming as melt crystallizes), precipitation from solutions (evaporite minerals like halite and gypsum forming as water evaporates from saline lakes or seas), metamorphism (existing rocks recrystallizing under heat and pressure to form new minerals like garnet or kyanite), hydrothermal activity (hot fluids depositing minerals like pyrite, gold, copper sulfides in veins), and biogenic processes (organisms building shells and skeletons from calcite, aragonite, silica, or apatite). Each formation environment leaves distinctive textures, mineral assemblages, and trace element patterns that geologists can read backwards to reconstruct the conditions of formation. Earth currently has about 6,000 known mineral species, with new ones being discovered each year.")
    r("mineral formation", "mechanism",
      "Mechanisms of mineral formation involve nucleation and growth of crystals from a parent phase: melt, solution, or solid. From cooling magma, nucleation of mineral crystals occurs when temperature drops below each mineral's crystallization point, with ions in the melt arranging into the regular lattice characteristic of the species. Growth proceeds as additional ions diffuse to the crystal face and attach. Slow cooling produces large interlocking crystals (granite); rapid cooling produces fine grains or volcanic glass (obsidian). From aqueous solution, supersaturation drives nucleation and growth, with precipitation kinetics depending on temperature, ion concentrations, pH, and the presence of nucleation surfaces. Metamorphic minerals form by solid-state diffusion as elements rearrange to thermodynamically favored phases under new pressure and temperature conditions; reactions are slow but achieve equilibrium given enough time. Biogenic mineralization involves organisms providing organic templates and ion concentrations that direct precipitation into specific shapes, often producing structures (mollusk shells, bone) far stronger than abiotic equivalents.")
    r("mineral formation", "comparison",
      "Igneous, sedimentary, and metamorphic minerals differ in formation environment and texture. Igneous minerals crystallize from molten rock, typically interlocking with each other and lacking porosity. Sedimentary minerals form by precipitation, mineral-fluid reactions, or accumulation of biological materials, often retaining porosity and occurring as cements binding pre-existing grains. Metamorphic minerals develop in solid rock under elevated temperature and pressure, with crystal shapes often elongated or aligned by directional stress (foliation in schists and gneisses). Compared with synthetic crystals grown industrially under controlled conditions, natural minerals contain more impurities and structural defects but reveal the geological context of their formation through compositional zoning, fluid inclusions, and isotope ratios. Compared with organic crystals like sugar or DNA, mineral crystals are dominated by ionic and covalent bonding, with much higher melting points and hardness, allowing them to persist in geological materials for billions of years.")
    r("mineral formation", "misconception",
      "A common misconception is that gemstones are inherently rare; many gemstones are simply varieties of common minerals (ruby and sapphire are both corundum, emerald is a beryl, amethyst is quartz) that owe their value to specific color centers from trace impurities and to the rarity of large, clear, well-formed crystals rather than to compositional rarity per se. Another misconception is that all minerals form slowly; some, like the carbonates precipitating in cave dripstones or the sulfides forming at undersea hydrothermal vents, can grow centimeters per year, while some metamorphic and igneous crystals take millions of years. People sometimes also assume that minerals are static once formed; in reality, minerals can be altered by weathering, hydrothermal fluids, and metamorphism, recrystallizing into different species in response to changing conditions. Finally, the idea that crystal shape is determined solely by external conditions misses that the underlying ionic geometry sets a basic symmetry, while growth conditions modulate which faces dominate the final habit.")
    r("mineral formation", "significance",
      "Mineral formation matters because minerals are the building blocks of rocks, the source of essentially all economically extracted elements (metals, energy minerals, fertilizers), and recorders of Earth's history. The mineralogy of a rock encodes the temperature, pressure, fluid composition, and kinetic conditions under which it formed, allowing reconstruction of past tectonic, climatic, and biological events from samples millions to billions of years old. Economic geology depends on understanding which environments concentrate which elements: copper porphyry deposits form in arc magmas; banded iron formations record the first oxygenation of the oceans; rare-earth element deposits form in carbonatites and weathering profiles; lithium concentrates in evaporites and pegmatites. Critical minerals for modern technology, from rare earths in magnets to lithium and cobalt in batteries, depend on geological processes that took millions of years to operate. Understanding mineral formation also bears on ocean acidification (which dissolves carbonate minerals organisms need), planetary science, and the search for life beyond Earth.")
