#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank part 4 of 4: arts_and_humanities, everyday_life,
current_events (fresh for batch F)."""


def register(T):
    # ===== ARTS AND HUMANITIES =====

    T["counterpoint in classical music"] = {
        "_cat": "arts_and_humanities",
        "what": "the compositional technique of combining two or more independent melodic lines that sound coherent when played together, governed by rules about consonance, dissonance treatment, and voice independence developed primarily in 16th-18th century Western music",
        "how": "species counterpoint, formalized by Fux in 1725, teaches the discipline in stages: against a slow cantus firmus, the student adds a second voice first in note-against-note style, then two notes against one, and so on, with rules about parallel fifths, dissonance preparation, and melodic contour. Mature counterpoint, as in Bach's fugues, blends multiple voices into structures where each line is musically interesting on its own and combines into rich harmony",
        "why": "counterpoint is the deep grammar of Western art music from Palestrina through Bach and Beethoven into Brahms and beyond. Mastery of it underlies craftsmanship in symphonic writing, choral music, and even modern film scoring and progressive jazz. Music conservatories still require species counterpoint as a foundational skill",
        "vs": "counterpoint differs from homophony (one melody supported by chords, the texture of most pop and folk music) and from monophony (single line). It contrasts with heterophony (variations of a single melody played simultaneously, common in many non-Western traditions) and with mere polyphony (any multi-voice texture, only some of which follows counterpoint conventions)",
        "ex": "Bach's Art of the Fugue is the supreme example: a single subject is developed through 14 fugues and 4 canons, including invertible counterpoint, augmentation, diminution, and stretto. Each piece can stand alone, yet they form a unified study of contrapuntal possibility built on one theme",
        "mis": "people think counterpoint is dry and academic. The strict rules exist to discipline the ear; in skilled hands, they produce some of the most expressive music ever written. Another myth is that counterpoint is obsolete; film and game composers from John Williams to Joe Hisaishi rely on contrapuntal textures for emotional weight",
    }

    T["Dutch Golden Age painting"] = {
        "_cat": "arts_and_humanities",
        "what": "the flowering of painting in the Dutch Republic during the 17th century, characterized by realistic depictions of everyday life, landscapes, still lifes, group portraits, and seascapes, produced for a broad middle-class market rather than aristocratic or church patrons",
        "how": "Protestant iconoclasm and the absence of a powerful court reshaped the art market: painters worked speculatively for an open middle-class market, specializing in marketable genres like merry company scenes, vanitas still lifes, civic guard portraits, and detailed landscapes. Studios produced paintings at scale; an estimated 1.4 million paintings were created in the Republic between 1640 and 1660 alone, sold through dealers and fairs",
        "why": "the period produced Rembrandt, Vermeer, Frans Hals, Jacob van Ruisdael, and Pieter de Hooch, whose work redefined Western painting's relationship to ordinary life and light. It is also a key episode in art history's transition from elite to mass-market production, anticipating modern art markets centuries later",
        "vs": "Dutch Golden Age painting contrasts with contemporary Italian Baroque (large religious and mythological commissions for church and court) and Flemish painting under Catholic Habsburg rule (Rubens, Van Dyck, more aristocratic and mythological). Within Dutch art, it differs from later 18th-century academic painting in its preference for genre subjects and unidealized realism",
        "ex": "Vermeer's View of Delft (about 1660-1661) shows the painter's home city across the harbor at midmorning, with cloud shadows on rooftops and a meticulously observed light. Marcel Proust called it 'the most beautiful painting in the world' and modeled the death scene of his fictional novelist Bergotte around standing before it",
        "mis": "people think Dutch Golden Age paintings are quiet realism without symbolic content. Many genre scenes are loaded with moralizing emblems, vanitas reminders, and witty allegory readable to contemporaries. Another myth is that Vermeer used the camera obscura mechanically; while he likely studied through one, the paintings are not traced and show interpretive choices unique to him",
    }

    T["the haiku tradition"] = {
        "_cat": "arts_and_humanities",
        "what": "a Japanese poetic form consisting of three phrases of roughly 5, 7, and 5 sound units (on, not strictly syllables), traditionally including a season word (kigo) and a cutting word (kireji) that creates juxtaposition between two images",
        "how": "the form crystallized from the opening verse (hokku) of longer collaborative renku poetry, made independent by Matsuo Basho (1644-1694). A successful haiku presents a sharp sensory image rooted in a specific season, leaves narrative implicit, and uses the kireji to pivot between two perceptions. English-language haiku usually relax the 5-7-5 count, since English syllables carry more weight than Japanese on",
        "why": "haiku has become the most widely practiced and translated poetic form in the world. It influenced Imagism (Pound, H.D.), modern American poetry, environmental writing, and contemplative practice across cultures. Its compression makes it both an entry-level form for beginners and a lifelong study for masters",
        "vs": "haiku differs from tanka (31 sound units in 5-7-5-7-7, more emotionally explicit), from senryu (same form but humorous and human-centered, no kigo required), and from Western lyric (typically narrative or argumentative). It differs from prose poems in its strict brevity and from epigrams in resisting overt punchlines",
        "ex": "Basho's frog haiku reads roughly: 'old pond / a frog jumps in / the sound of water'. The kireji (cutting) lies between the still pond and the sudden splash, juxtaposing eternity and event. Translators have rendered the same 17 sounds dozens of ways, each emphasizing different facets",
        "mis": "people think haiku must be exactly 5-7-5 syllables in English. Mature English-language haiku usually run shorter and prioritize the seasonal-image principle over syllable count. Another myth is that haiku is always serene nature poetry; classical haiku frequently address loss, illness, war, and city life",
    }

    T["the Bauhaus design movement"] = {
        "_cat": "arts_and_humanities",
        "what": "the German art and design school founded by Walter Gropius in Weimar in 1919, which sought to unite fine art and craft with industrial design, profoundly shaping 20th-century architecture, furniture, typography, and product design before the Nazis closed it in 1933",
        "how": "the Bauhaus combined preliminary courses in materials and form (taught by Itten, Albers, Moholy-Nagy, Klee, Kandinsky) with workshops in metal, weaving, ceramics, theater, and architecture. Form-follows-function principles, geometric abstraction, and machine-age aesthetics were paired with rigorous craft training. The school moved to Dessau (purpose-built campus by Gropius), then Berlin, before closure",
        "why": "Bauhaus aesthetics dominate contemporary product, graphic, and architectural design through the present. Tubular-steel chairs, sans-serif typefaces, white-walled modernist apartments, and grid-based graphic design all trace back to Bauhaus principles. Its diaspora after 1933 (Gropius and Breuer to Harvard, Mies van der Rohe to Chicago, Albers to Black Mountain and Yale) carried the ideas worldwide",
        "vs": "Bauhaus differs from Arts and Crafts (which rejected industry) by embracing mass production, from Art Deco (decorative, luxury-oriented) by stripping ornament, and from De Stijl (purer geometric abstraction, smaller scope) by tying ideology to integrated craft training. It differs from later postmodernism, which deliberately reintroduced ornament and historical reference",
        "ex": "Marcel Breuer's Wassily Chair (1925-26), made of tubular steel and leather straps, was inspired by his bicycle frame and is still in production a century later. It encapsulates the Bauhaus ideal: industrial materials, geometric form, comfort through engineering rather than upholstery",
        "mis": "people think Bauhaus was uniformly austere. Different masters held quite different views; Klee and Kandinsky brought spiritual and expressive concerns, Itten verged on the mystical, and the Bauhaus parties were legendary. Another myth is that Bauhaus invented modernist design; it synthesized ideas circulating in Vienna, Russian Constructivism, and Dutch De Stijl into a teaching program",
    }

    T["epic poetry traditions"] = {
        "_cat": "arts_and_humanities",
        "what": "long narrative poems in elevated style telling the deeds of heroes, the founding of nations, or cosmic events, found across many cultures including Greek (Iliad, Odyssey), Mesopotamian (Gilgamesh), Sanskrit (Mahabharata, Ramayana), Old English (Beowulf), and Mali (Sundiata)",
        "how": "epic typically opens with an invocation, employs a heightened diction, uses formulaic phrases (Homer's wine-dark sea, Homer's swift-footed Achilles), in medias res openings, extended similes, divine machinery, catalogs of warriors, and culminating heroic combat. Many trace back to oral performance, with formulaic patterns serving as memory aids; literate epics like Virgil's Aeneid and Milton's Paradise Lost adapt the conventions for written composition",
        "why": "epic transmits cultural memory, founding myths, ethical norms, and linguistic heritage. The Iliad shaped Greek and then Roman and Western literary education for over two millennia; the Mahabharata provides ethical and theological scaffolding for Hindu thought; Beowulf preserves Old English vocabulary and worldview otherwise largely lost. Modern fantasy literature inherits epic structures",
        "vs": "epic differs from lyric (short, personal, present-focused) and drama (enacted dialogue) in being narrative and panoramic. It differs from history (epic accepts mythic and divine elements) and from novels (verse rather than prose, formulaic rather than realist style), although novels have absorbed many epic strategies",
        "ex": "the Mahabharata, with about 200,000 verses (roughly 10 times the combined length of the Iliad and Odyssey), recounts the dynastic struggle between the Pandavas and Kauravas culminating in the great Kurukshetra War. Embedded within it is the Bhagavad Gita, a 700-verse philosophical dialogue between Arjuna and Krishna that became one of Hinduism's central scriptures",
        "mis": "people think epics were composed by single authors. Many, including the Homeric poems, were probably oral compositions stabilized over generations, with the names Homer or Vyasa serving as cultural attributions rather than identifying single historical poets. Another myth is that epic is dead; modern long narrative cinema (the Lord of the Rings films, Star Wars saga) consciously revives epic conventions",
    }

    T["the philosophy of language"] = {
        "_cat": "arts_and_humanities",
        "what": "the branch of philosophy that studies the nature of language, meaning, reference, truth, and the relations between language, thought, and reality, central to 20th-century analytic philosophy through Frege, Russell, Wittgenstein, Quine, Kripke, and others",
        "how": "the field analyzes how words refer (theories of reference), how sentences mean (truth-conditional semantics, use theories), how speakers do things with words (speech-act theory from Austin and Searle), how meanings depend on context (indexicals, demonstratives), and how language relates to thought (the Sapir-Whorf debate, Fodor's language of thought). Logic, linguistics, and cognitive science feed into and out of the analyses",
        "why": "philosophy of language underlies analytic philosophy's conviction that solving traditional problems (free will, knowledge, mind) requires first clarifying the language used to state them. It also undergirds work on natural-language semantics in linguistics, formal verification in computer science, and the design of programming languages and AI systems",
        "vs": "philosophy of language differs from linguistics (which focuses on empirical description of languages) by addressing normative and conceptual questions about meaning. It differs from rhetoric (which studies persuasion) and from philology (which studies historical texts). Within philosophy, it overlaps with philosophy of mind but emphasizes public symbols rather than mental states",
        "ex": "Saul Kripke's Naming and Necessity (1980) argued that proper names function as rigid designators picking out the same object in every possible world, against the dominant Russell-Frege view that names are abbreviated descriptions. The argument reshaped semantics, modal metaphysics, and the philosophy of natural kinds across decades",
        "mis": "people think philosophy of language asks 'what is the meaning of life'. It asks more technical questions like how 'water' refers to H2O, or how 'I' picks out a different person on each lip. Another myth is that the field is purely abstract; debates about reference and truth shape practical issues from courtroom interpretation to AI alignment",
    }

    # ===== EVERYDAY_LIFE =====

    T["how a heat pump heats and cools a home"] = {
        "_cat": "everyday_life",
        "what": "an electric appliance that moves heat between indoor and outdoor air using the refrigeration cycle, providing both heating in winter and cooling in summer with two to four times the heat delivered per unit of electricity, far more than a resistive heater",
        "how": "a refrigerant circulates between an indoor coil and an outdoor coil. A compressor raises the refrigerant's pressure and temperature; the hot gas releases heat in one coil and condenses to liquid; an expansion valve drops its pressure; the cold liquid evaporates in the other coil, absorbing heat. A reversing valve flips which coil is hot, switching the system between heating and cooling",
        "why": "heat pumps are the most efficient electric heating technology and a cornerstone of building decarbonization. Replacing a gas furnace and air conditioner with a heat pump can cut household carbon emissions sharply once the grid is even moderately clean, and operating costs are competitive in most US climates",
        "vs": "heat pumps differ from gas furnaces (which burn fuel for heat at 80-95 percent efficiency) by moving heat rather than generating it, achieving effective efficiencies of 200-400 percent. They differ from resistive electric heaters (100 percent efficient) by being multiple times more efficient. Air-source heat pumps differ from ground-source (geothermal) versions, which are more efficient but much more expensive to install",
        "ex": "a modern cold-climate heat pump can maintain effective heating output down to about minus 20 Celsius, with backup electric resistance available for the coldest hours. In Maine, where winters are long, heat-pump installations have grown rapidly because operating costs beat oil and propane on a yearly basis",
        "mis": "people think heat pumps cannot work in cold winters. Cold-climate models retain useful heating output well below zero Celsius. Another myth is that heat pumps create heat from nothing; they move heat from outside to inside, which is why their effective efficiency exceeds 100 percent of electrical input without violating energy conservation",
    }

    T["reading a food label's added sugars line"] = {
        "_cat": "everyday_life",
        "what": "the entry on US Nutrition Facts panels (required since 2020) that reports grams of sugars added during processing or preparation, distinct from sugars naturally present in fruit, dairy, or vegetables",
        "how": "manufacturers compute added sugars based on ingredients: cane sugar, high-fructose corn syrup, honey, agave, fruit juice concentrates, and similar all count. The label lists the gram amount and a percent Daily Value based on a 50-gram daily ceiling for a 2000-calorie diet. Total sugars sit on a separate line, including both added and naturally occurring",
        "why": "the line lets consumers distinguish, for example, plain yogurt (low or zero added sugars) from sweetened yogurt (often 10-20 grams added), or fresh fruit from fruit drinks. Excess added sugar is linked to obesity, type 2 diabetes, dental caries, and cardiovascular risk; the WHO recommends limiting added sugars to under 10 percent of total calories",
        "vs": "added sugars differ from total sugars in excluding naturally present sugars (fructose in apples, lactose in milk). They differ from total carbohydrates, which include starches and fibers as well. They differ from sugar alcohols and artificial sweeteners, which are tracked under different label entries",
        "ex": "an 8-ounce serving of sweetened breakfast cereal often contains 12 grams of added sugars, about 24 percent of the daily limit, sometimes more than a glazed donut by mass. The added-sugars line makes this comparison transparent, whereas the older 'sugars' line lumped natural and added together",
        "mis": "people think 'no added sugar' means low total sugars. A 'no added sugar' fruit juice can still contain 25 grams of fructose per 8-ounce serving from the fruit itself. Another myth is that natural sugars are nutritionally identical to added; in whole foods they come bundled with fiber, vitamins, and slower absorption, while added sugars deliver fast spikes",
    }

    T["how home Wi-Fi channels and bands work"] = {
        "_cat": "everyday_life",
        "what": "the radio frequency layout that home wireless networks use, with the 2.4 GHz band offering longer range and worse congestion, the 5 GHz band offering shorter range and more bandwidth, and the new 6 GHz band on Wi-Fi 6E and Wi-Fi 7 offering even more capacity with the least congestion",
        "how": "Wi-Fi divides each band into channels of 20, 40, 80, or 160 MHz width. In 2.4 GHz only three channels (1, 6, 11) avoid overlap, so neighboring routers usually fight for them. 5 GHz offers about two dozen non-overlapping 20 MHz channels, often grouped into wider channels. 6 GHz adds another large block of spectrum exclusive to recent devices. Routers select channels automatically and adjust to interference",
        "why": "channel and band choice often determines whether a home network feels fast or sluggish, especially in apartment buildings. Understanding the bands helps users place routers, pick devices, and diagnose slowdowns. Modern dual-band and tri-band routers steer devices to the optimal band, but manual settings can still help in dense environments",
        "vs": "Wi-Fi bands differ from cellular bands (licensed, much wider area, regulated by carriers) and from Bluetooth (short range, low data rate, on the same 2.4 GHz band, can interfere with Wi-Fi). Wi-Fi differs from wired Ethernet, which is faster, lower latency, and immune to RF interference but requires cabling",
        "ex": "in a crowded apartment, switching a smart-TV streaming session from 2.4 GHz to 5 GHz often eliminates buffering even though the 5 GHz signal is weaker; the trade is bandwidth and isolation from neighbors against range. Wi-Fi 6E adds 6 GHz, currently the cleanest band because few devices yet use it",
        "mis": "people think more bars means faster Wi-Fi. Bars indicate signal strength, which affects but does not determine throughput; congestion on the channel matters more in many cases. Another myth is that 5 GHz is universally better; for thick walls or distant rooms, 2.4 GHz often delivers more usable bandwidth despite the lower headline speed",
    }

    T["the difference between LED, CFL, and incandescent bulbs"] = {
        "_cat": "everyday_life",
        "what": "the three main lighting technologies in modern homes: incandescent bulbs heat a tungsten filament, compact fluorescent lamps (CFLs) excite mercury vapor and phosphor, and light-emitting diodes (LEDs) emit light from semiconductor junctions, with LEDs now dominating new sales for their efficiency and lifespan",
        "how": "incandescent bulbs pass current through a filament until it glows white-hot, wasting most energy as heat (only about 5 percent reaches visible light). CFLs ionize mercury vapor to emit UV that excites a phosphor coating to glow white, at roughly 20-25 percent efficiency. LEDs use a semiconductor diode to emit photons directly, often combined with a phosphor for white light, at 30-50 percent or higher efficiency",
        "why": "LEDs use about 10-15 percent the electricity of incandescents for the same brightness and last 10-25 times longer, slashing both bills and lighting waste. The shift to LEDs is one of the cleanest energy-efficiency wins of the past two decades, with global lighting electricity demand falling even as device counts rise",
        "vs": "incandescents are warm, dimmable, and cheap upfront but very inefficient. CFLs are more efficient but contain mercury, take time to warm up, and have largely been displaced. LEDs are most efficient and longest-lived but more expensive upfront, although prices have fallen sharply and most major retailers now stock LEDs as the default",
        "ex": "replacing a 60-watt incandescent with an 8-watt LED of equivalent brightness saves about 52 watts continuously. Burning 1000 hours per year, that is 52 kWh saved, around 7 to 15 dollars depending on local electricity rates, recouping the LED's purchase price in well under a year",
        "mis": "people think LED light is harshly blue. Modern LEDs come in warm-white (2700-3000 K), neutral (3500-4000 K), and cool (5000+ K) options, indistinguishable in color from incandescents in the warm range. Another myth is that LEDs do not need replacement; they slowly dim and eventually fail, just over much longer time scales than older bulbs",
    }

    T["how household credit scores are calculated"] = {
        "_cat": "everyday_life",
        "what": "a numeric summary (commonly 300-850 on FICO, 300-850 on VantageScore) that lenders use to estimate the probability a consumer will repay debt, computed from credit-bureau data covering payment history, balances, and account characteristics",
        "how": "FICO weights payment history about 35 percent, amounts owed (especially utilization, balance vs limit) about 30 percent, length of credit history about 15 percent, credit mix about 10 percent, and new credit (recent applications) about 10 percent. Late payments, collections, and bankruptcies depress scores; consistent on-time payment and low utilization across multiple accounts raise them",
        "why": "credit scores influence whether someone gets approved for mortgages, auto loans, credit cards, and apartment rentals, and determine the interest rates offered. Small score differences can mean tens of thousands of dollars over a 30-year mortgage. Employers and insurers in some jurisdictions also pull credit, although laws limit such uses",
        "vs": "FICO and VantageScore use overlapping but different formulas; the same person can have noticeably different scores on each. Both differ from the underlying credit reports (the raw account histories) which themselves can vary across the three major bureaus (Equifax, Experian, TransUnion). Credit scores differ from debt-to-income ratios and other underwriting metrics that lenders apply alongside the score",
        "ex": "a person with one 30-day late payment on a single account two years ago, $4000 of balances against $20,000 of limits, and a four-year credit history might score in the high 600s. Paying balances down to under 10 percent of limits typically raises the score by 30-50 points within one or two billing cycles",
        "mis": "people think checking your own score lowers it. Soft inquiries (your own checks, prequalifications) do not affect scores; only hard inquiries from new credit applications do. Another myth is that closing old credit cards always helps; closing your oldest account can shorten credit history and raise utilization, often hurting the score",
    }

    T["how dishwashers actually clean dishes"] = {
        "_cat": "everyday_life",
        "what": "an appliance that washes dishes by spraying hot, detergent-laden water onto them at high pressure, dissolving food residues with surfactants, alkali, and enzymes, then rinsing and drying with hot air, residual heat, or condensation",
        "how": "the cycle fills the bottom basin with several gallons of water, which is heated to 120-160 Fahrenheit. A pump drives water through rotating spray arms whose nozzles produce high-pressure jets reaching all dishes. Detergent dispensers release alkaline cleaners and enzymes part way through the cycle. Soiled water is filtered and pumped to the drain. A final rinse adds rinse aid, then dishes dry by heat or condensation on the tub walls",
        "why": "a modern Energy Star dishwasher uses about 3 gallons per load and significantly less water and energy than careful hand washing of an equivalent load, while sanitizing with hotter water than human hands tolerate. Understanding the mechanism explains why scraping is enough but pre-rinsing wastes water and why proper loading matters",
        "vs": "dishwashers differ from hand washing in pressure, heat, and detergent chemistry, and in producing more consistent sanitation. They differ from commercial under-counter machines, which finish in 90 seconds at 180 Fahrenheit, and from industrial conveyor washers used in restaurants. They differ from sterilizers (used for medical instruments) which use higher temperatures or chemical agents",
        "ex": "loading a plate facing the spray arms, with no large items blocking spray paths, will yield clean dishes even with stuck-on cheese, while crowding bowls so they nest will leave undersides dirty no matter how good the detergent. Most dishwasher complaints trace to loading and detergent issues rather than the appliance itself",
        "mis": "people pre-rinse dishes thoroughly, which wastes water and can confuse modern enzyme-based detergents that need food residue to activate properly. Another myth is that hotter water always cleans better; above about 160 Fahrenheit, baked-on starches actually polymerize harder, and modern detergents are tuned for moderate temperatures",
    }

    # ===== CURRENT_EVENTS =====

    T["the global push for AI regulation"] = {
        "_cat": "current_events",
        "what": "the wave of policy efforts since 2022 in the EU, US, UK, and elsewhere to govern advanced AI systems through risk-based rules, transparency requirements, and oversight bodies, responding to concerns about safety, bias, copyright, and economic disruption",
        "how": "the EU AI Act, agreed in 2024, classifies AI systems into prohibited, high-risk, limited-risk, and minimal-risk categories with corresponding obligations. The US has used executive orders and agency guidance (NIST AI Risk Management Framework, FTC enforcement) and the AI Safety Institute. The UK established its own AI Safety Institute. Voluntary commitments from major labs cover red-team testing and watermarking",
        "why": "AI's rapid capability gains have outpaced existing privacy, anti-discrimination, and consumer-protection law. Regulators are trying to set norms before harms entrench. The choices made over the next few years will shape who can build frontier AI, what data they can use, and what disclosures are required, affecting the trajectory of one of the most powerful general-purpose technologies",
        "vs": "AI regulation differs from earlier internet regulation (which was largely permissive, especially in the US) by attempting to set rules before deployment in many cases. It differs across jurisdictions: the EU prefers rights-based ex ante rules, the US has favored sector-specific and ex post enforcement, and China combines industrial promotion with content restrictions",
        "ex": "the EU AI Act bans certain practices outright (social scoring by governments, untargeted scraping for facial recognition databases) and requires general-purpose AI providers above thresholds to disclose training data summaries, perform model evaluations, and report serious incidents. Penalties reach 7 percent of global annual revenue for prohibited uses",
        "mis": "people think AI regulation is uniformly hostile to innovation. Most frameworks are tiered, leaving low-risk uses largely unregulated. Another myth is that regulation stops AI development; large labs continue to release models in regulated jurisdictions, adapting disclosures and evaluations to comply",
    }

    T["the post-pandemic shift in commercial real estate"] = {
        "_cat": "current_events",
        "what": "the structural change in office, retail, and urban commercial property markets since 2020, driven by hybrid work, e-commerce growth, and rising interest rates, with vacancy rates in many central business districts reaching multi-decade highs",
        "how": "remote and hybrid work cut typical office occupancy to roughly half its pre-pandemic level, eroding tenant demand at lease renewal. Tenants downsized, sublet space, or moved to higher-quality buildings ('flight to quality'), leaving older Class B and C buildings with structural vacancies. Rising interest rates from 2022 onward depressed valuations across the sector, triggering refinancing problems and forced sales",
        "why": "commercial real estate is a multi-trillion-dollar asset class held by pension funds, banks, and insurers; price declines ripple through balance sheets. Empty downtowns lose foot traffic that supported restaurants and retail, hurting city tax bases. Conversion of offices to housing has been proposed as a fix but is technically expensive due to floorplate depths, plumbing, and zoning",
        "vs": "the current shift differs from past office downturns (which were cyclical and recovered with the economy) by reflecting a permanent change in work patterns. It differs from the 2008 housing crash in that residential markets remain tight; the strain is concentrated in offices and certain retail categories. Industrial and logistics real estate has boomed, benefiting from e-commerce",
        "ex": "in San Francisco, central-city office vacancy crossed 35 percent in 2024, up from under 5 percent in 2019. Several towers that traded for hundreds of millions of dollars before 2020 sold for fractions of those prices, and the city has launched a program to subsidize office-to-housing conversions",
        "mis": "people think every office market is collapsing. Top-tier (Class A trophy) buildings in dense markets are leasing at near-pre-pandemic rates; the pain is concentrated in older properties and commodity space. Another myth is that work-from-home is a fad that will reverse; survey and badge-swipe data show hybrid patterns have stabilized rather than reverted",
    }

    T["the energy transition and critical mineral supply"] = {
        "_cat": "current_events",
        "what": "the global push to decarbonize electricity, transport, and heating that has surged demand for lithium, cobalt, nickel, copper, rare earths, and graphite needed for batteries, motors, and grid infrastructure, exposing concentrated supply chains as a geopolitical pressure point",
        "how": "EV batteries demand lithium and either nickel or LFP chemistry; wind turbines use neodymium and dysprosium magnets; high-voltage transmission expansion drives copper demand. Mining is concentrated (Australia and Chile for lithium, DRC for cobalt, Indonesia for nickel) but processing is even more so, with China handling about 60-90 percent of refining for several key minerals. Diversification through new mines, recycling, and substitute chemistries is being attempted but takes years",
        "why": "the speed of the energy transition will be limited by mineral availability, processing capacity, and the willingness to accept mining's environmental and social impacts. Concentration creates strategic risk: an export restriction or accident in a key country can ripple through global manufacturing. Recycling of EV batteries is expected to become a major secondary supply within 10-15 years",
        "vs": "the current critical minerals concern differs from 20th-century oil geopolitics in being about processing rather than reserves, since most minerals are widely distributed in the Earth's crust. It differs from semiconductor supply chains in physical scale and from earlier commodity cycles in being driven by policy-mandated demand growth rather than just price signals",
        "ex": "China restricted gallium and germanium exports in 2023, citing national security, briefly spiking prices for chips and solar manufacturing inputs. The EU and US responded with critical-raw-materials laws prioritizing diversified sourcing, recycling, and strategic reserves",
        "mis": "people think there is not enough lithium globally. Reserves are abundant; the bottleneck is the time and capital to open mines and refineries, plus the environmental review and community consent processes that can take a decade. Another myth is that EVs cannot be made sustainable due to mineral mining; lifecycle analyses show EVs produce far lower lifetime emissions than internal-combustion vehicles, and recycling can recover most battery metals",
    }

    T["the rise of weight-loss GLP-1 drugs"] = {
        "_cat": "current_events",
        "what": "the rapid clinical and commercial expansion of glucagon-like peptide 1 receptor agonists (semaglutide, tirzepatide) for weight loss in people with obesity, after originally being approved for type 2 diabetes, with profound effects on patients, healthcare costs, and adjacent industries",
        "how": "GLP-1 is a hormone released by the gut after eating that stimulates insulin, suppresses glucagon, slows gastric emptying, and reduces appetite via central nervous system signaling. The synthetic agonists, given as weekly injections, mimic these effects more durably. Tirzepatide additionally activates GIP receptors. Trials show 15-22 percent body weight loss over 68-72 weeks in patients with obesity, well above prior pharmacotherapy",
        "why": "obesity affects over 40 percent of US adults and is a major driver of cardiovascular disease, diabetes, and cancer. Drugs that produce surgical-level weight loss change long-term health outlooks for millions, with secondary impacts on food, beverage, and snack industries (early data show measurable reduction in overall food spending), and on Medicare/Medicaid budgets given the drugs' high cost (approximately 1000 USD per month before discounts)",
        "vs": "GLP-1 agonists differ from older weight-loss drugs (modest 5-10 percent weight loss, often with side effects), bariatric surgery (more weight loss but invasive), and lifestyle interventions alone (typically 3-5 percent sustained loss). Among GLP-1 drugs, tirzepatide leads efficacy trials but semaglutide has more cardiovascular outcome data; oral formulations are emerging",
        "ex": "Novo Nordisk's market value briefly exceeded that of every other European company on semaglutide demand, while supply shortages forced rationing in 2023-2024. By 2024, an estimated 6-8 percent of US adults had used a GLP-1 drug, with prescription volume growing fastest among insured non-diabetic adults",
        "mis": "people think discontinuing GLP-1 maintains the weight loss. Most patients regain a substantial fraction within a year of stopping, suggesting these drugs treat rather than cure obesity. Another myth is that they are cosmetic; outcomes data show meaningful reductions in major adverse cardiovascular events independent of weight effects",
    }

    T["the surge in undersea cable cuts and infrastructure threats"] = {
        "_cat": "current_events",
        "what": "the increase in observed and suspected damage to undersea fiber-optic and energy cables in the Baltic, Red Sea, and elsewhere since 2022, raising concerns about both accidental hazards from fishing and shipping and deliberate sabotage as part of geopolitical conflict",
        "how": "undersea cables, often laid on continental shelves at depths reachable by anchors, are routinely damaged a few hundred times per year worldwide by trawlers and dragged anchors. A new pattern since 2022 includes incidents involving specific ships in tense geopolitical contexts, with NATO and Baltic states investigating possible state-sponsored sabotage. Repairs require specialized cable-laying ships, which are scarce and concentrated in a few operators",
        "why": "undersea cables carry over 95 percent of intercontinental data traffic and are critical to financial markets, internet services, and military communications. Damage in conflict zones can disrupt commerce and intelligence. The combination of fragility, concentration of repair capacity, and ambiguity of attribution makes cables an attractive gray-zone target",
        "vs": "undersea cable risk differs from satellite communications in being higher-bandwidth and lower-latency but more physically exposed. It differs from terrestrial fiber, which is easier to monitor but easier to dig up. Energy cables (HVDC interconnectors) face similar physical risks but with different consequences, including grid instability rather than data loss",
        "ex": "the Nord Stream gas pipeline explosions in September 2022 and the Balticconnector pipeline and adjacent telecommunications cables incidents in October 2023 brought the issue into mainstream attention. Multiple Red Sea cable cuts in early 2024, attributed by some analysts to anchor drag from a Houthi-attacked freighter, briefly degraded internet capacity between Europe and Asia",
        "mis": "people assume cable cuts always knock services offline. Major routes are heavily redundant, with traffic rerouted around damage within minutes; users rarely notice any single cut. Another myth is that the cables are easily replaced; specialized repair ships are limited, and a coordinated campaign of cuts could outpace global repair capacity for weeks",
    }
