#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Kernel bank: technology topics (fresh for batch G)."""


def register(T):
    T["how SSL/TLS handshakes work"] = {
        "_cat": "technology",
        "what": "a cryptographic handshake protocol that establishes an authenticated, encrypted channel between a client and server, negotiating cipher suites, exchanging certificates, and deriving shared session keys before any application data flows",
        "how": "in TLS 1.3, the client sends a ClientHello with supported cipher suites and an ephemeral key share. The server responds with ServerHello, its certificate, and its own key share, then derives the shared secret via Diffie-Hellman over an elliptic curve. Both sides derive symmetric session keys using HKDF and confirm with a Finished message authenticated by an HMAC over the handshake transcript. Subsequent application data is encrypted with AEAD ciphers like AES-GCM or ChaCha20-Poly1305",
        "why": "TLS underlies HTTPS, secure email, VPNs, and almost every encrypted internet connection. It protects against eavesdropping, tampering, and impersonation. Without it, online banking, shopping, and login flows would be wide open to network attackers",
        "vs": "TLS 1.3 differs from TLS 1.2 in cutting handshake round trips from two to one and removing legacy cipher suites with known weaknesses. It differs from SSH (which authenticates differently and is designed for interactive sessions) and from IPsec (which operates at the network layer rather than transport)",
        "ex": "loading https://example.com triggers a TLS handshake during which the browser verifies the server's certificate against trusted root CAs, confirms the certificate matches the hostname, and derives keys to encrypt the GET request. All this typically completes in tens of milliseconds before the page begins to load",
        "mis": "people think the TLS lock icon means a site is safe. It only confirms the connection is encrypted and the certificate is valid; the site itself can still be a phishing page with a legitimate certificate. Another myth is that TLS encrypts the destination domain; SNI leaks the hostname unless Encrypted Client Hello is in use",
    }

    T["how a CPU pipeline executes instructions"] = {
        "_cat": "technology",
        "what": "the technique of overlapping the execution of multiple instructions by breaking each into stages (fetch, decode, execute, memory access, writeback) so different stages of consecutive instructions run simultaneously in different parts of the chip",
        "how": "the pipeline advances by one stage per clock cycle. While instruction N is in execute, N+1 is in decode and N+2 in fetch. Hazards (data dependencies, branches, memory stalls) interrupt the flow and are mitigated by forwarding (bypassing register writes), branch prediction, out-of-order execution, and speculative execution. Modern CPUs have pipelines 14 to 20 stages deep with multiple parallel execution units",
        "why": "pipelining is what makes CPUs run at gigahertz clocks while still completing useful work each cycle. Without it, instructions per second would be one to two orders of magnitude lower. Microarchitectural details directly determine how fast real programs run, and shape every compiler optimization decision",
        "vs": "pipelining differs from multi-issue (superscalar) execution, which runs multiple instructions per cycle in parallel pipelines, and from multi-threading, which interleaves instructions from different threads. It differs from GPU execution, which runs many threads in lockstep over wide SIMD units",
        "ex": "a tight loop with no branches and no memory stalls can sustain near one instruction per cycle even on simple in-order pipelines. A high-end x86 core may sustain four to six instructions per cycle through aggressive out-of-order issue, but only when branch prediction, caches, and dependencies all cooperate",
        "mis": "people think clock speed is what determines CPU performance. Instructions per cycle, cache hierarchy, and memory bandwidth matter at least as much; a 3 GHz modern core easily outperforms a 4 GHz older one. Another myth is that pipeline depth always helps; deeper pipelines suffer worse branch-mispredict penalties, which is why modern designs settled around 14 to 20 stages rather than 30",
    }

    T["how garbage collection works in managed runtimes"] = {
        "_cat": "technology",
        "what": "an automatic memory management technique in languages like Java, Go, JavaScript, and Python where the runtime identifies objects no longer reachable from program roots and reclaims their memory, freeing developers from explicit malloc/free pairs",
        "how": "tracing collectors start from roots (stack, globals, registers) and mark every reachable object, then sweep unreachable objects. Generational collectors exploit the observation that most objects die young by separating a young generation collected often from an older generation collected rarely. Concurrent and incremental collectors do most work without stopping the program. Reference counting (used in CPython) increments and decrements counts on assignment and frees objects when counts hit zero, but cannot reclaim cycles without a separate cycle collector",
        "why": "GC eliminates whole classes of bugs: dangling pointers, double-frees, and most memory leaks. It enables higher-level language design, faster development, and safer concurrent code. The cost is pause times, throughput overhead, and unpredictability that real-time systems cannot tolerate",
        "vs": "GC differs from manual memory management (C, C++) where the programmer pairs allocations with frees, and from RAII and smart pointers (Rust, modern C++) where ownership is tracked at compile time. Tracing collectors differ from reference-counting ones in handling cycles automatically but at the cost of pauses",
        "ex": "the Go runtime uses a concurrent tri-color mark-sweep collector with sub-millisecond stop-the-world pauses, achieved by doing most marking concurrently with the program. The JVM's G1 and ZGC collectors push pauses below 10 ms even on multi-gigabyte heaps",
        "mis": "people think GC eliminates all memory leaks. Holding references to unused objects (caches, listeners, closures over large state) still leaks memory because the GC sees them as reachable. Another myth is that GC is always slower than manual management; with generational collection and bump-pointer allocation, allocation-heavy workloads can actually be faster in managed runtimes",
    }

    T["how a load balancer distributes traffic"] = {
        "_cat": "technology",
        "what": "a network device or software that sits between clients and a pool of backend servers, distributing incoming requests across the pool to spread load, improve availability, and decouple clients from individual server identities",
        "how": "load balancers operate at layer 4 (TCP/UDP) by forwarding connections based on IP and port, or at layer 7 (HTTP) by inspecting requests and routing on path, host, headers, or cookies. Algorithms include round robin, least connections, weighted variants, and consistent hashing for sticky sessions. Health checks probe backends and remove failing instances. Modern load balancers also terminate TLS, do rate limiting, and integrate with service discovery in Kubernetes",
        "why": "load balancers turn individual servers into a fault-tolerant fleet, support horizontal scaling, enable rolling deploys with zero downtime, and provide a stable hostname clients can rely on regardless of which backend is up. They are the entry point of essentially every production web service",
        "vs": "load balancers differ from reverse proxies (which can do similar work but emphasize caching and SSL termination) and from service meshes (which load balance internally between microservices using sidecar proxies). Layer 4 load balancers differ from layer 7 in not understanding the application protocol; they are faster but less flexible",
        "ex": "AWS Application Load Balancer distributes HTTP traffic across EC2 targets using path-based and host-based routing, terminates TLS, and integrates health checks. A typical setup has the ALB in front of an auto-scaling group, so unhealthy instances are removed and new ones added based on CPU load, all transparent to clients",
        "mis": "people think a single load balancer is a single point of failure. Production systems run multiple load balancers behind DNS round robin or anycast routing for high availability. Another myth is that round robin is always fair; without weighting, it sends equal traffic to slow and fast backends alike, often making the slow ones a bottleneck",
    }

    T["how zero-knowledge proofs work"] = {
        "_cat": "technology",
        "what": "cryptographic protocols that let one party (the prover) convince another (the verifier) that a statement is true without revealing any information beyond the truth of the statement itself, often instantiated as zk-SNARKs or zk-STARKs",
        "how": "the prover encodes the statement as an arithmetic circuit and constructs a polynomial commitment that holds only if the statement is true. The verifier issues random challenges; the prover responds with values consistent with the commitments. The protocol's soundness ensures cheating provers fail with overwhelming probability, while its zero-knowledge property ensures the transcript reveals nothing about the secret witness. zk-SNARKs require a trusted setup; zk-STARKs avoid it but produce larger proofs",
        "why": "zero-knowledge proofs enable private blockchain transactions (Zcash), scalable rollups for Ethereum, anonymous credentials, and private auctions. They allow proving properties about sensitive data (income above a threshold, age above 18) without revealing the data itself, with applications across finance, identity, and compliance",
        "vs": "zero-knowledge proofs differ from traditional digital signatures, which prove who signed but reveal what was signed, and from secure multiparty computation, which jointly computes functions on secret inputs. They differ from homomorphic encryption, which lets you compute on encrypted data without seeing it",
        "ex": "Zcash uses zk-SNARKs to let users prove they own funds and authorize a transfer without revealing addresses or amounts. The proof is a few hundred bytes regardless of transaction complexity, and verifying it takes milliseconds, even though the underlying claim is about substantial off-chain computation",
        "mis": "people think zero-knowledge means no information leaks at all. The proof reveals exactly that the statement is true; nothing more, but the truth itself is information. Another myth is that ZK proofs are quantum-safe; SNARKs based on elliptic curves are not, while STARKs based on hash functions remain quantum-resistant",
    }

    T["how a relational database handles transactions"] = {
        "_cat": "technology",
        "what": "the mechanism by which a relational database guarantees that a sequence of operations either fully succeeds (commits) or fully fails (rolls back), preserving the ACID properties of atomicity, consistency, isolation, and durability",
        "how": "the database writes intended changes first to a write-ahead log on durable storage so commits can be replayed after a crash. Locks or multi-version concurrency control (MVCC) provide isolation between concurrent transactions. On commit, the log entry is flushed (giving durability), and changes become visible to other transactions. On abort or crash, the log is used to undo partial changes. Isolation levels (read uncommitted through serializable) trade consistency for throughput",
        "why": "transactions are what let banks transfer money, e-commerce sites maintain inventory, and reservation systems prevent double bookings. Without ACID guarantees, distributed concurrent updates would routinely produce inconsistent state and silent data loss",
        "vs": "ACID transactions differ from BASE semantics (basically available, soft state, eventual consistency) used in many NoSQL systems, which give up strict isolation for availability and scalability. They differ from optimistic concurrency, which lets transactions run without locks and aborts conflicting ones at commit",
        "ex": "transferring 100 dollars from account A to account B requires both subtracting from A and adding to B atomically. Inside a transaction, if either step fails, both are rolled back. If concurrent transactions touch the same accounts, isolation prevents intermediate states from being visible elsewhere",
        "mis": "people think transactions are free. They cost log writes and lock contention; high-throughput systems carefully tune isolation levels and batch sizes. Another myth is that 'serializable' means transactions run sequentially; serializable means the result is equivalent to some serial order, which permits significant concurrency in practice",
    }

    T["the difference between symmetric and asymmetric encryption"] = {
        "_cat": "technology",
        "what": "two complementary classes of encryption: symmetric uses the same secret key to encrypt and decrypt, while asymmetric (public-key) uses a mathematically linked key pair where one key encrypts and only its partner can decrypt",
        "how": "symmetric algorithms (AES, ChaCha20) operate on blocks or streams using a shared secret; they are fast, often hundreds of megabytes per second on modern hardware. Asymmetric algorithms (RSA, ECC, Diffie-Hellman) use number-theoretic problems where one direction is easy and the inverse hard. Public keys can be published; only the matching private key can decrypt or sign. Hybrid systems use asymmetric crypto to exchange a fresh symmetric key, then symmetric crypto for the bulk traffic",
        "why": "symmetric crypto provides bulk speed; asymmetric crypto solves the key distribution problem and enables digital signatures, certificate-based identity, and secure session establishment between parties who never met. Almost every modern secure protocol (TLS, SSH, Signal) combines both",
        "vs": "symmetric encryption is fast and short-keyed (128 to 256 bits give strong security) but requires a pre-shared secret. Asymmetric encryption removes the shared-secret requirement but is orders of magnitude slower and uses much longer keys (RSA 3072+ or 256-bit ECC for equivalent strength) for the same security level",
        "ex": "TLS uses ECDHE for asymmetric key exchange (deriving a shared secret without revealing private keys to a network attacker), then switches to AES-GCM symmetric encryption for the actual page contents. The handshake costs a few public-key operations once per connection; bulk data flows at symmetric speeds",
        "mis": "people think public keys are inherently more secure. Asymmetric crypto is necessary in different scenarios but slower and broken by quantum computers (Shor's algorithm). Symmetric ciphers like AES-256 remain quantum-resistant in practice when key sizes are doubled, while RSA and ECC are not",
    }

    T["how DNS resolves a domain name"] = {
        "_cat": "technology",
        "what": "the distributed system that translates human-readable domain names like example.com into IP addresses by querying a hierarchy of authoritative name servers, cached aggressively at every layer to keep latency low",
        "how": "a stub resolver on a client sends the query to a recursive resolver (often run by ISP or public providers like 1.1.1.1 or 8.8.8.8). The resolver, if not cached, asks a root server which TLD nameservers handle .com, then asks one of those for example.com's authoritative nameservers, then asks those for the A record. Each step's answer is cached for the TTL specified by the authoritative server. Modern flows use DNSSEC for authentication and DoT/DoH for encryption",
        "why": "DNS is the address book of the internet; without it, users would have to memorize IPs. It also enables flexible operations like rotating server fleets behind a stable name, multi-region failover, and content delivery network routing based on client geography",
        "vs": "DNS differs from DHCP, which assigns IPs to clients on a local network rather than translating names. It differs from hosts files, which are local static name-to-IP maps that predate DNS but still take precedence on most systems. Recursive resolvers differ from authoritative servers; the former cache answers from the latter",
        "ex": "loading google.com triggers a DNS query that typically resolves in 5 to 50 ms when the resolver has the answer cached, or 50 to 200 ms uncached as the recursive resolver walks the hierarchy. Modern browsers prefetch and pin DNS to overlap resolution with TLS handshake to cut total connection time",
        "mis": "people think DNS lookups go to a central server. The system is intentionally distributed; thirteen logical root server clusters are operated by different organizations on every continent. Another myth is that DNS is encrypted; classic DNS is plaintext UDP, which is why DNS over HTTPS and DNS over TLS were standardized",
    }

    T["how a B-tree index works"] = {
        "_cat": "technology",
        "what": "a self-balancing tree data structure used by relational databases and file systems to index data, where each node holds a sorted block of keys and pointers, optimized for storage where reads happen in pages from disk or SSD",
        "how": "lookups walk from the root, choosing the child whose key range contains the target. Each node holds many keys (often hundreds or thousands), keeping the tree shallow even for billions of rows; depth is typically three to five. Insertions split full nodes upward; deletions merge or rebalance underflowing ones. B+-trees, the variant used most often, store all data in leaves and link leaves for fast range scans",
        "why": "B-trees turn O(N) table scans into O(log N) lookups while remaining I/O-efficient because each node fits in a page. Without indexes, queries on large tables would be too slow for production use. Range queries, equality lookups, and sort-order scans all leverage the same structure",
        "vs": "B-trees differ from binary search trees in fan-out; a binary tree with billions of keys is 30+ levels deep, while a B-tree of the same size is 4 levels. They differ from hash indexes in supporting range queries (hash gives O(1) point lookups but no ordering). Log-structured merge trees (LSM trees, used by RocksDB and Cassandra) trade write speed for read complexity, while B-trees favor balanced read/write performance",
        "ex": "PostgreSQL's default index is a B+-tree. Querying WHERE id = 12345 on a table with 100 million rows takes a handful of page reads instead of scanning gigabytes. Range queries like WHERE created_at BETWEEN '2024-01-01' AND '2024-02-01' walk the leaf chain in order, visiting only matching pages",
        "mis": "people think indexes always help. Each index slows inserts and updates and consumes storage; over-indexing a heavily written table can cripple it. Another myth is that B-trees are obsolete on SSDs; they remain efficient because cache and OS page sizes still align with their structure",
    }

    T["how a Linux file system organizes data"] = {
        "_cat": "technology",
        "what": "the hierarchical layout by which Linux file systems (ext4, XFS, Btrfs, ZFS) store files and metadata on block devices, organizing inodes, directory entries, and free space so that paths resolve to data blocks efficiently and durably",
        "how": "each file is described by an inode containing metadata (size, owner, permissions, timestamps, pointers to data blocks). Directories are special files mapping names to inode numbers. The file system divides the device into block groups, each with its own bitmap of free blocks and inodes, to keep related data near one another. ext4 uses extents (contiguous run descriptions) instead of block-by-block pointers, dramatically improving large-file performance. Journals (ext4) or copy-on-write (Btrfs, ZFS) provide crash consistency",
        "why": "the file system is what gives software a stable abstraction of persistent data; choices about layout, journaling, and consistency models directly affect performance, durability, and recovery from crashes. Modern systems demand high throughput and integrity guarantees, especially for databases, container storage, and cloud workloads, all of which rest on these foundations",
        "vs": "Linux file systems differ from each other in features. ext4 is mature, fast, and conservative. XFS scales better for large parallel I/O. Btrfs and ZFS add snapshots, checksums, and built-in volume management at the cost of complexity. They differ from network file systems (NFS, SMB) in operating on local block devices, and from object storage (S3) in providing POSIX semantics and nested directory hierarchies",
        "ex": "a `git clone` of a large repository unpacks tens of thousands of small files. ext4 with extents and the orlov allocator places these efficiently within a few block groups, keeping subsequent reads close together on disk. The same operation on a fragmented or naively allocated file system can take many times longer due to seek overhead",
        "mis": "people think file systems are interchangeable. Workload characteristics (lots of small writes, large sequential reads, frequent metadata operations) matter substantially; choosing wrong can halve performance. Another myth is that journaling guarantees no data loss; journals protect metadata consistency by default, with data integrity requiring additional options or copy-on-write file systems",
    }

    T["how a JIT compiler optimizes running code"] = {
        "_cat": "technology",
        "what": "a runtime system, used by JavaScript engines (V8, SpiderMonkey), the JVM, and the .NET CLR, that compiles bytecode or source to machine code on the fly while observing actual execution patterns, generating tighter code than static compilation could produce",
        "how": "JITs typically run in tiers. First execution interprets or quickly compiles to baseline code. Profilers count call counts, branch outcomes, and observed types. Hot functions are recompiled with optimizations: inlining, type specialization, escape analysis, and dead code elimination based on the observed profile. If assumptions become false (a callee changes type), code is deoptimized and recompiled. Tiered compilation balances startup time against peak throughput",
        "why": "JITs make dynamically typed languages reach within a small factor of statically compiled performance, enable optimizations that depend on actual runtime patterns rather than worst-case assumptions, and let virtual machines target multiple CPU architectures by generating code on the fly. They are essential to the performance of modern web browsers, server-side JavaScript, and JVM ecosystems",
        "vs": "JIT differs from ahead-of-time compilation in compiling at runtime rather than build time, trading startup latency and memory for runtime adaptivity. It differs from interpretation in producing native machine code rather than dispatching through a VM loop. WebAssembly is closer to AOT than JIT: validated and compiled but largely without speculative profile-based optimization",
        "ex": "V8's TurboFan compiler observes that a hot JavaScript function is consistently called with two integer arguments, generates specialized machine code that assumes those types, and inlines call targets. If a later call passes a string, V8 deoptimizes back to the unspecialized version. This dance is what lets modern JavaScript run within 2x of equivalent C++ on numeric workloads",
        "mis": "people think JIT compiled languages are inherently slower than statically compiled ones. With sufficient profile data and warm caches, JITs can match or exceed AOT compilers because they specialize on actual rather than possible behavior. Another myth is that JIT is only for dynamic languages; even Java's JVM uses JIT compilation, and statically typed languages benefit from runtime profile information",
    }

    T["how a CDN accelerates content delivery"] = {
        "_cat": "technology",
        "what": "a globally distributed network of edge servers that caches and serves static and dynamic content from locations physically close to end users, reducing latency, offloading origin servers, and absorbing traffic spikes and DDoS attacks",
        "how": "when a user requests an asset, DNS or anycast routing directs the request to a nearby edge node. If the asset is cached and fresh, the edge serves it in tens of milliseconds. If not, it fetches from the origin (or a parent cache) and stores a copy. Cache rules use HTTP headers (Cache-Control, ETag), purge APIs let origins invalidate. Modern CDNs add edge compute (Cloudflare Workers, Fastly Compute@Edge), TLS termination, image optimization, and security features like WAF and bot management",
        "why": "CDNs reduce page load times by an order of magnitude for global audiences, turn what would be expensive bandwidth into pooled capacity, protect origins from traffic spikes and attacks, and form the delivery backbone of nearly every large web service. Without them, video streaming, large-scale e-commerce, and global SaaS would be considerably slower and more expensive",
        "vs": "CDNs differ from origin servers in geographic distribution and caching focus, from HTTP proxies in scale and management, and from peer-to-peer distribution in being centrally controlled. They differ from edge computing platforms in primarily caching content, though most major CDNs now offer compute at the edge as well",
        "ex": "Netflix's Open Connect appliances are CDN nodes deployed inside ISP networks across the globe. By placing the content one network hop from subscribers, Netflix delivers tens of terabits per second during peak streaming hours without overwhelming backbone links. The same general principle applies to Cloudflare, Akamai, and Amazon CloudFront",
        "mis": "people think CDNs only serve static images and CSS. Modern CDNs accelerate dynamic content via origin shielding, request collapsing, edge logic, and HTTP/3 transport, and they serve a substantial share of web pages' total payload. Another myth is that CDNs are only for big sites; cheap or free tiers from Cloudflare and Bunny make them practical for almost any project",
    }

    T["how WebSockets enable real-time communication"] = {
        "_cat": "technology",
        "what": "a network protocol providing full-duplex communication channels over a single long-lived TCP connection, established via an HTTP upgrade handshake, designed for low-latency bidirectional data flow between browsers and servers",
        "how": "the client sends an HTTP GET with Upgrade: websocket and a random key. The server replies with HTTP 101 Switching Protocols and a hashed key proving it understood the request. After that, both sides exchange WebSocket frames over the same TCP connection without HTTP overhead. Frames carry text or binary payloads, can be fragmented, and include ping/pong for heartbeats. Messages flow either direction at any time without waiting for requests",
        "why": "WebSockets enable real-time chat, collaborative editing, live notifications, multiplayer games, and streaming dashboards without the overhead and latency of repeated HTTP polling. They reduced the cost of pushing server-side events to browsers from 'open a new connection per message' to 'reuse one connection forever'",
        "vs": "WebSockets differ from HTTP long polling, which simulates push by holding requests open until data arrives, and from server-sent events, which support only server-to-client push. They differ from WebRTC, which goes peer-to-peer for media. WebSockets ride on TCP and inherit head-of-line blocking; WebTransport over QUIC addresses that for browsers that support it",
        "ex": "Slack, Discord, and Google Docs all use WebSockets to deliver new messages and collaborative edits within tens of milliseconds. A user sees a peer's edit almost instantly because the server pushes the change down the open connection rather than waiting for the next poll",
        "mis": "people think WebSockets are HTTP. They start as HTTP for compatibility with proxies, but after the upgrade handshake the framing is its own protocol. Another myth is that WebSockets scale infinitely; each connection consumes server memory and ephemeral ports, so production systems require connection-pooling proxies and careful capacity planning",
    }
