"""Part 7: math entries continued."""


def register_part_7(r):
    # ---- proof by contradiction ----
    r("proof by contradiction", "mechanism",
      "Proof by contradiction works by assuming that the statement to be proved is false and deriving a logical contradiction from that assumption, thereby establishing that the original statement must be true. The structure is: assume not P; through valid logical steps derive a statement Q and also its negation not Q, which is a contradiction; conclude that the assumption not P must be false, hence P is true. The technique relies on the law of excluded middle (every proposition is either true or false) and the principle that contradictions are impossible. Proof by contradiction is often the cleanest way to prove existence of objects whose construction is difficult, the impossibility of certain configurations, or the irrationality of specific numbers. Constructive mathematicians, who reject the law of excluded middle for infinite sets, are skeptical of contradiction-based existence proofs but accept those that derive a direct contradiction from concrete assumptions.")
    r("proof by contradiction", "example",
      "The classic example is Euclid's proof that the square root of 2 is irrational. Suppose for contradiction that sqrt(2) = a/b for some integers a, b with no common factor (a fraction in lowest terms). Then 2 = a^2/b^2, so a^2 = 2 b^2. This means a^2 is even, which forces a to be even (since the square of an odd number is odd). Write a = 2c for some integer c. Then 2 b^2 = (2c)^2 = 4 c^2, so b^2 = 2 c^2, meaning b^2 is even and b is even. But then a and b share the common factor 2, contradicting the assumption that a/b was in lowest terms. The contradiction shows that no such a, b exist; sqrt(2) cannot be written as a ratio of integers and is therefore irrational. The proof generalizes to show that the square root of any non-square positive integer is irrational and is among the most elegant in mathematics.")
    r("proof by contradiction", "comparison",
      "Proof by contradiction differs from direct proof, which proceeds from premises to conclusion through valid logical steps without any negation. It differs from proof by contraposition, which proves 'if P then Q' by directly proving 'if not Q then not P' without seeking a contradiction. Compared with proof by counterexample (which disproves a universal statement by exhibiting one case where it fails), proof by contradiction proves rather than disproves. Compared with constructive proofs (which exhibit objects explicitly), proof by contradiction can establish existence without producing the object itself, a feature constructive mathematicians find unsatisfying for some applications. Compared with computer-assisted proofs that check exhaustively, proof by contradiction is purely deductive. Within mathematics, the choice among these techniques depends on which yields the clearest argument; some statements admit elegant contradiction proofs, others direct constructions, and the most striking proofs sometimes combine multiple approaches.")
    r("proof by contradiction", "significance",
      "Proof by contradiction matters because it lets mathematicians establish results that would be difficult or impossible to prove directly. Many fundamental results in mathematics are most cleanly proved by contradiction: the irrationality of sqrt(2), the infinitude of primes (Euclid: assume finitely many, multiply them all and add 1, derive a contradiction), the impossibility of squaring the circle with compass and straightedge, the impossibility of solving the general quintic by radicals, and many results in topology and analysis. The technique formalizes a powerful intuition: to show something exists or is true, eliminate the possibility that it does not. Beyond mathematics, the same logical pattern appears in scientific reasoning (rejecting hypotheses that lead to predictions contradicting observation) and in everyday argumentation (reductio ad absurdum). The technique reminds us that the set of true statements has a tight logical structure such that admitting any falsehood somewhere leads to contradictions everywhere.")

    # ---- set theory basics ----
    r("set theory basics", "definition",
      "Set theory studies the abstract notion of a set: an unordered collection of distinct objects (the set's elements). Sets can contain anything (numbers, points, functions, other sets) and are defined either by listing elements (1, 2, 3) or by specifying a property that elements must satisfy (the set of even integers). Two sets are equal if and only if they have the same elements. Standard operations include union (elements in either set), intersection (elements in both), difference (elements in one but not the other), and complement (everything not in a given set, relative to a chosen universe). Subsets, power sets (the set of all subsets), Cartesian products, and ordered tuples build more complex structures. Modern axiomatic set theory (most commonly Zermelo-Fraenkel set theory with the axiom of choice, ZFC) provides a rigorous foundation for nearly all of mathematics: numbers, functions, relations, and geometric objects can all be constructed as sets.")
    r("set theory basics", "comparison",
      "Naive set theory (the casual treatment summarized above) differs from axiomatic set theory in being intuitive but vulnerable to paradoxes like Russell's: the set of all sets that do not contain themselves both contains itself (by the definition) and does not (also by the definition). Axiomatic set theories like ZFC restrict set formation through carefully chosen axioms (extensionality, pairing, union, power set, infinity, replacement, regularity, choice) that prevent paradoxes while supporting nearly all of mathematics. Compared with type theory, which classifies objects into hierarchical types and avoids paradoxes by structural restrictions, set theory uses untyped sets but disciplined axioms. Compared with category theory, which emphasizes morphisms over objects and is sometimes proposed as an alternative foundation, set theory remains the conventional foundation for most of mathematics. Compared with finite combinatorics, set theory addresses both finite and infinite collections, with infinite set theory leading to deep results about cardinality, well-orderings, and consistency.")
    r("set theory basics", "mechanism",
      "Set theory works by building structures from sets and operations using axioms that define what sets exist. From the empty set (which exists by axiom), we can construct natural numbers (von Neumann's encoding: 0 is the empty set, 1 is {0}, 2 is {0, 1}, ...), then integers (as equivalence classes of pairs of naturals), rationals (as equivalence classes of pairs of integers), reals (as Dedekind cuts or Cauchy sequence equivalence classes), and complex numbers (as ordered pairs of reals). Functions are sets of ordered pairs, ordered pairs are themselves sets ((a, b) = {{a}, {a, b}}), relations are sets of ordered pairs, and so on. Cardinality compares set sizes through bijections: two sets have the same cardinality if there exists a bijection between them. Cantor's theorem shows the power set of any set has strictly greater cardinality than the set, leading to the infinite hierarchy of cardinals.")
    r("set theory basics", "misconception",
      "A common misconception is that all sets that we can describe must exist. Russell's paradox shows that the 'set of all sets that do not contain themselves' cannot exist as a set in standard set theory; the comprehension axiom must be restricted to bounded comprehension over existing sets. Another misconception is that all infinities have the same size; Cantor's theorem shows that the cardinality of the power set is strictly greater than the cardinality of the set, producing an infinite hierarchy of larger and larger infinities. People also sometimes assume that the rational and real numbers have the same cardinality because both seem 'continuous'; in fact, the rationals are countable (same size as integers) while the reals are uncountable, a result of Cantor's diagonal argument. Finally, the axiom of choice is sometimes thought to be obviously true and trivially derivable from other axioms; it is independent of the other ZF axioms and has nontrivial consequences (Banach-Tarski paradox, well-ordering theorem) that some find counterintuitive.")

    # ---- Cantor's diagonal argument ----
    r("Cantor's diagonal argument", "comparison",
      "Cantor's diagonal argument is one of several techniques for proving uncountability or hierarchy results in set theory and computability. Compared with direct cardinality arguments via bijections, the diagonal argument is more robust: it shows that no list of real numbers can be complete by constructing a real not on the list, regardless of how the list was generated. Compared with measure-theoretic arguments showing that the rationals have measure zero in the reals (which also implies the reals are 'larger' in a measure-theoretic sense), the diagonal argument is purely combinatorial and prior to measure theory. The same diagonal idea appears in the proof of Godel's incompleteness theorems (constructing a self-referential statement that asserts its own unprovability), the halting problem's undecidability (constructing a program that halts if and only if it does not), and Russell's paradox (constructing a set that contains itself if and only if it does not). All of these are diagonal arguments adapted to different settings.")
    r("Cantor's diagonal argument", "misconception",
      "A common misconception is that the diagonal argument requires the assumed list of reals to be in some particular order or to follow a specific pattern; the argument works for any purported list, however constructed. Another misconception is that Cantor's argument creates a 'paradox' showing set theory is broken; on the contrary, the argument cleanly proves that the reals are uncountable, a positive theorem rather than an inconsistency. People also sometimes think the constructed missing real depends on which digit transformations are used; while different transformations give different missing reals, every valid transformation produces some real not on the list, so the conclusion holds regardless of the specific procedure. Finally, the assumption that uncountability requires the reals' continuity (no gaps) misses that countability or uncountability is purely about cardinality of the set considered as a collection of distinct elements; the orderly arrangement of reals on a number line is irrelevant to the diagonal argument.")
    r("Cantor's diagonal argument", "significance",
      "Cantor's diagonal argument matters because it established that infinity comes in different sizes, overturning the previously dominant view that all infinite collections were equally vast. The proof shows there can be no bijection between the integers and the reals, so the reals are 'more numerous' in a precise mathematical sense. Beyond this immediate result, the diagonal technique generalizes to prove Cantor's theorem (the power set has strictly larger cardinality than the original set) and is the kernel of Godel's incompleteness theorems and Turing's proof of the undecidability of the halting problem. The argument also frames the continuum hypothesis (whether there is a cardinality strictly between that of the integers and the reals), which Godel and Cohen showed to be independent of standard set theory axioms. The diagonal argument's combination of simplicity and depth has made it a paradigm for self-referential and limitative proofs across mathematics and theoretical computer science.")

    # ---- the axiom of choice ----
    r("the axiom of choice", "definition",
      "The axiom of choice (AC) is a principle in set theory asserting that for any collection of nonempty sets, there exists a function (a 'choice function') that assigns to each set in the collection an element of that set. For finite collections this is provable from other axioms, but for infinite collections (especially uncountable ones) it requires a separate axiom because no general construction is available. AC is independent of the other Zermelo-Fraenkel axioms (ZF): both ZF + AC (called ZFC) and ZF + not AC are consistent if ZF is. AC has many equivalent formulations, including Zorn's lemma (every nonempty partially ordered set in which every chain has an upper bound contains a maximal element) and the well-ordering theorem (every set can be well-ordered). It is foundational to many areas of mathematics that involve infinite operations, including general topology, functional analysis, abstract algebra, and measure theory.")
    r("the axiom of choice", "example",
      "An informal example of the axiom of choice is selecting one shoe from each of infinitely many pairs of shoes versus selecting one sock from each of infinitely many pairs of socks. With shoes you can specify a choice function constructively ('always pick the left shoe'), so no axiom of choice is needed. With socks, the two members of each pair are indistinguishable, so no constructive rule selects a particular member, and the assertion that a choice function nonetheless exists is exactly the axiom of choice. A more substantive mathematical example is showing that every vector space has a basis, which requires AC for infinite-dimensional cases (no constructive procedure builds the basis explicitly). Tychonoff's theorem (the product of any collection of compact spaces is compact) is also equivalent to AC. The Banach-Tarski paradox (a solid ball can be decomposed into finitely many pieces and reassembled into two balls of the same size) follows from AC and shows that AC has counterintuitive consequences in geometry.")
    r("the axiom of choice", "mechanism",
      "The axiom of choice operates by guaranteeing the existence of a choice function without specifying its construction. This is its essential feature: AC is a non-constructive existence axiom, fundamentally different from the explicit constructions used elsewhere in mathematics. The mechanism by which AC supports proofs is to allow simultaneous selection across infinite (often uncountable) collections without writing down the selection rule. Many useful theorems in algebra and analysis depend on selections that cannot be described concretely: extending a partial function to a total function defined on a larger domain, choosing representatives from equivalence classes, picking elements from cosets in groups, or selecting points from each member of an open cover in topology. Equivalents like Zorn's lemma reformulate AC into a more usable form for constructions involving partial orders, allowing proofs that maximal objects exist (maximal ideals in rings, maximal subspaces, maximal antichains) without specifying the maximal object explicitly.")
    r("the axiom of choice", "comparison",
      "The axiom of choice differs from other set-theoretic axioms (extensionality, pairing, union, power set) in being non-constructive: it asserts existence without giving a construction. Compared with constructive logic and intuitionistic mathematics, which reject non-constructive existence proofs, classical mathematics with AC is more powerful but less algorithmic. Compared with the axiom of dependent choice (DC), a weaker variant sufficient for most analysis, AC is stronger and applies to arbitrary index sets while DC works for sequential constructions. Compared with the continuum hypothesis (CH), another set-theoretic statement independent of ZF, AC has fewer paradoxical consequences in practice and is more commonly assumed without comment. Compared with Zorn's lemma and the well-ordering theorem, AC is logically equivalent: any one implies the others within ZF. Mathematicians today generally use AC freely because the alternative restricts so much familiar mathematics, though the debate over its philosophical status persists.")
    r("the axiom of choice", "misconception",
      "A common misconception is that the axiom of choice is obviously true; while it seems intuitive for finite or even countable collections, the assertion for arbitrary infinite collections is independent of the other axioms and has consequences (like the Banach-Tarski paradox) that strain intuition. Another misconception is that AC is constructive in any sense; the choice function is asserted to exist but typically cannot be exhibited explicitly, which is why some mathematicians prefer to avoid AC where possible. People also sometimes assume that all uses of AC produce paradoxes; in fact, most applications of AC support entirely intuitive results (every vector space has a basis), and the paradoxes appear only in specific geometric contexts that probe the boundary of what 'volume' can mean. Finally, the assertion that AC must either be true or false in some absolute sense misses the point of axiomatic mathematics: AC is a choice of axiom whose consequences differ from those of its negation, with both choices producing internally consistent mathematics.")

    # ---- Godel's incompleteness theorems ----
    r("Godel's incompleteness theorems", "definition",
      "Godel's incompleteness theorems are two related results in mathematical logic, proved by Kurt Godel in 1931, that establish fundamental limitations of formal axiom systems strong enough to express arithmetic. The first incompleteness theorem states that any consistent formal system that includes basic arithmetic is incomplete: there exist true statements about the natural numbers that the system cannot prove. The second incompleteness theorem strengthens this by showing that no consistent system of the relevant strength can prove its own consistency. Both results apply to standard formalizations of arithmetic (Peano arithmetic) and to set theories like Zermelo-Fraenkel that contain arithmetic. The theorems shattered the early-20th-century hope (most associated with David Hilbert) that mathematics could be reduced to a single complete and self-justifying formal system, and they reshaped the philosophy of mathematics, the foundations of computer science, and our understanding of what formal reasoning can achieve.")
    r("Godel's incompleteness theorems", "example",
      "The classic example of an undecidable statement is the Godel sentence G, which informally asserts 'this statement is not provable in this formal system.' Godel constructed G using a clever encoding of statements as numbers (Godel numbering), which allowed self-reference within a formal system that talks only about numbers. If G were provable, it would assert its own unprovability, contradicting consistency; therefore in a consistent system, G is not provable. But that is exactly what G asserts, so G is true in the standard interpretation. The system can talk about G, can recognize G as a meaningful statement, but cannot prove it. A more concrete example is Goodstein's theorem about a particular sequence of natural numbers, which is true but unprovable in Peano arithmetic (provable only in stronger systems). The continuum hypothesis is undecidable in ZFC, illustrating that incompleteness affects strong set theories as well, not only weak ones.")

    # ---- p-values and their misinterpretation ----
    r("p-values and their misinterpretation", "definition",
      "A p-value is the probability of observing data at least as extreme as the actually observed data, assuming the null hypothesis is true. In a standard hypothesis test, one specifies a null hypothesis (typically asserting no effect or no difference), computes a test statistic from the observed data, and computes the p-value as the probability under the null model of obtaining a test statistic at least as extreme as the one observed. Smaller p-values indicate that the observed data are less compatible with the null hypothesis, and a conventional threshold of 0.05 (or sometimes 0.01) is used to decide whether to reject the null in favor of an alternative. The p-value is conditional on the null hypothesis being true and on the chosen test statistic; it is not the probability that the null hypothesis is true given the data, despite frequent misinterpretation in introductory courses and the popular press.")
    r("p-values and their misinterpretation", "example",
      "A typical example is testing whether a coin is fair. Flip the coin 100 times and observe 60 heads. Under the null hypothesis of a fair coin, the number of heads has a binomial(100, 0.5) distribution. The two-sided p-value is the probability of observing 60 or more heads, or 40 or fewer heads, under this null. Computing: P(X >= 60) is approximately 0.0284 and P(X <= 40) is approximately 0.0284, so the two-sided p-value is approximately 0.057. At the conventional 0.05 threshold, this is not statistically significant: we do not reject the hypothesis of a fair coin. The example illustrates several subtleties: the p-value depends on whether we test one-sided or two-sided, on the choice of test statistic, and on the precise framing of the null hypothesis. A study with 1000 flips and 600 heads would yield a p-value of about 1 in 10^9, dramatically more compelling, illustrating the role of sample size.")
    r("p-values and their misinterpretation", "misconception",
      "Many misconceptions surround p-values. The p-value is not the probability that the null hypothesis is true given the data; that quantity requires Bayesian analysis with prior probabilities. The p-value is not the probability of having made an error in rejecting the null; the long-run error rate from a procedure is the alpha threshold, not the p-value of any single test. A non-significant result does not prove the null hypothesis; it only shows the data are compatible with the null but does not rule out genuine effects too small to detect with the given sample. Statistical significance does not imply practical significance; with very large samples, trivial effects can be statistically significant. Conversely, an underpowered study can fail to detect important effects. Multiple testing inflates the false positive rate; running many tests and reporting only significant ones (data dredging) is a leading source of irreproducible results. The American Statistical Association issued a 2016 statement warning against the misuse of p-values and encouraging researchers to consider effect sizes, confidence intervals, and prior knowledge.")

    # ---- the law of large numbers ----
    r("the law of large numbers", "mechanism",
      "The law of large numbers (LLN) states that the sample average of many independent identically distributed random variables converges to the true mean of the distribution as the sample size grows. There are two formal versions. The weak law states that the sample mean converges in probability to the population mean: for any positive epsilon, the probability that the sample mean differs from the true mean by more than epsilon tends to zero as the sample size increases. The strong law states that the sample mean converges almost surely to the true mean, meaning the set of outcome sequences for which convergence fails has probability zero. The mechanism behind both results is that random fluctuations in individual observations average out as more observations are aggregated, with the standard deviation of the sample mean shrinking as 1 / sqrt(n) where n is the sample size. The LLN underpins the foundations of statistical estimation, sampling theory, and the long-run behavior of randomized algorithms.")
    r("the law of large numbers", "example",
      "A simple example: flip a fair coin many times and track the proportion of heads. By the law of large numbers, this proportion converges to 0.5 as the number of flips grows. After 100 flips you might see proportions ranging from about 0.4 to 0.6 (one standard deviation is about 0.05). After 10,000 flips, you'd expect proportions within about 0.005 of 0.5 with high probability. After 1,000,000 flips, within about 0.0005. The example illustrates both the LLN and the rate of convergence implied by sqrt(n) shrinkage of the standard error: each tenfold increase in the sample size shrinks the typical deviation by a factor of about 3. Casinos rely on the LLN: while individual gamblers may win or lose substantially, the casino's per-game expected value times millions of plays gives essentially deterministic profit. Insurance companies rely on the same principle to price policies despite individual outcomes being uncertain.")

    # ---- the central limit theorem ----
    r("the central limit theorem", "definition",
      "The central limit theorem (CLT) states that the sample mean of many independent identically distributed random variables, suitably normalized, converges in distribution to a standard normal distribution, regardless of the original distribution's shape (provided it has finite variance). Specifically, if X_1, X_2, ... are i.i.d. with mean mu and variance sigma^2, then sqrt(n)(X-bar - mu) / sigma converges in distribution to N(0, 1) as n grows. The theorem is remarkable because the limiting distribution does not depend on the distribution of the individual X_i (subject to finite variance); whether the X_i are uniform, exponential, binomial, or arbitrarily exotic, their averages tend to be normally distributed for large n. The CLT generalizes to sums (rather than averages), to non-identically distributed variables under regularity conditions (Lyapunov, Lindeberg conditions), and to multivariate settings. It is one of the most important results in probability theory.")
    r("the central limit theorem", "comparison",
      "The CLT differs from the law of large numbers in describing the distribution of the sample mean rather than just its convergence to the population mean. The LLN says the sample mean approaches the true mean; the CLT says the deviations from the true mean are approximately normally distributed with predictable variance. Compared with the weak law of large numbers, the CLT is a more refined and precise statement: it gives the rate (1 / sqrt(n)) and the shape (normal) of the convergence. Compared with the binomial-to-normal approximation (a special case for sums of Bernoulli variables), the CLT generalizes to any underlying distribution with finite variance. Compared with the Berry-Esseen theorem, which gives quantitative bounds on the rate of convergence in the CLT, the CLT itself is asymptotic and does not directly tell us how large n must be for the normal approximation to be accurate; rules of thumb (n at least 30, or larger for skewed distributions) come from such refinements.")
    r("the central limit theorem", "example",
      "A clean example: roll a fair die many times and average the results. Each roll has mean 3.5 and variance 35/12 (about 2.917). For n = 100 rolls, the sample mean has mean 3.5 and standard error sqrt(35/12)/10, about 0.171, and is approximately normally distributed. The probability of a sample mean above 4 is roughly P(Z > (4 - 3.5)/0.171) = P(Z > 2.92), about 0.0018, less than 0.2 percent. The original die distribution is far from normal (uniform on 1 through 6), but the average of 100 rolls is essentially normal. This is why polling, quality control, and many statistical methods work even when the underlying populations are not normal: averages are normal, and statistical inference about means proceeds via normal approximations.")
    r("the central limit theorem", "mechanism",
      "The CLT works because of the way variances and characteristic functions combine when independent random variables are summed. The variance of a sum of independent random variables is the sum of the variances, so the standard deviation of the sum grows as sqrt(n) while the mean grows as n; rescaling by sqrt(n) keeps the variance bounded and the mean centered. Characteristic functions (Fourier transforms of probability densities) factor when independent variables are summed, and the rescaled limiting characteristic function turns out to match that of the standard normal distribution by Taylor expansion of log of the characteristic function. The deeper reason is that the normal distribution is uniquely the maximum-entropy distribution given a fixed mean and variance, and aggregating many independent contributions tends to maximize entropy subject to the constraints. Variants of the CLT for non-i.i.d., dependent, or heavy-tailed variables exist and depend on how strongly the assumptions of the standard CLT are relaxed.")
    r("the central limit theorem", "significance",
      "The CLT matters because it explains why so many real-world distributions are approximately normal and underpins statistical inference. Heights, measurement errors, exam scores, and many natural phenomena are normally distributed because they result from the combined effect of many small independent factors, each contributing a small amount to the total. Statistical methods like t-tests, confidence intervals for means, regression analysis, and analysis of variance rely on the assumption that sample means are normally distributed, which the CLT justifies for sufficiently large samples regardless of the underlying distribution. In quality control, process monitoring uses the CLT to set control limits. In finance, the assumption of normally distributed returns (often misapplied to heavy-tailed asset returns) traces back to the CLT. The CLT also underlies many bootstrap and resampling methods that empirically construct sampling distributions through the same kind of averaging the CLT describes analytically.")

    # ---- Bayes' theorem ----
    r("Bayes' theorem", "definition",
      "Bayes' theorem is a rule for updating beliefs in light of evidence, expressed as P(A | B) = P(B | A) P(A) / P(B), where P(A | B) is the probability of A given B, P(B | A) is the likelihood of observing B given A, P(A) is the prior probability of A, and P(B) is the marginal probability of B (which can be computed via the law of total probability as P(B | A) P(A) + P(B | not A) P(not A)). The theorem captures how prior beliefs (P(A)) should be updated to posterior beliefs (P(A | B)) after observing evidence B, with the update determined by the likelihood (how likely the evidence is under each hypothesis). Bayes' theorem follows from the definition of conditional probability and is mathematically uncontroversial; the philosophical disputes around 'Bayesian' methods concern whether and how to assign prior probabilities, not the validity of the theorem itself. The theorem is foundational to Bayesian statistics, machine learning, medical diagnosis, and scientific inference.")
    r("Bayes' theorem", "mechanism",
      "Bayes' theorem works by combining a prior probability with evidence to produce a posterior probability through multiplication and normalization. The numerator P(B | A) P(A) is the joint probability of A and B; dividing by P(B) renormalizes to give the conditional probability of A given B. The mechanism becomes intuitive through the natural-frequency formulation: imagine a population of 1000 patients, 10 of whom have a rare disease (prior 1 percent). Of those 10 with the disease, 9 test positive (sensitivity 90 percent). Of the 990 without the disease, 99 test positive (false positive rate 10 percent). A randomly selected patient who tests positive falls in a group of 9 + 99 = 108 positive testers, of whom only 9 actually have the disease, giving posterior probability 9/108, about 8 percent. The seemingly low posterior despite the impressive test sensitivity highlights the importance of base rates and is the source of the prosecutor's fallacy and the base rate neglect bias.")
    r("Bayes' theorem", "comparison",
      "Bayesian and frequentist approaches to statistics differ in how they treat probabilities of hypotheses. The Bayesian view assigns probabilities to hypotheses representing degrees of belief and uses Bayes' theorem to update them with evidence. The frequentist view treats hypotheses as fixed (true or false but unknown) and computes probabilities of data given hypotheses (p-values, confidence intervals) without assigning probabilities to hypotheses themselves. Compared with each other, Bayesian methods naturally incorporate prior knowledge but require its explicit specification (which can be controversial when the choice of prior is influential), while frequentist methods avoid prior specification but produce results (like confidence intervals and p-values) that are sometimes misinterpreted as Bayesian quantities. In machine learning, Bayesian methods are used for parameter estimation, model selection, and Bayesian neural networks, while frequentist methods underlie much of statistical learning theory. In practice, the two approaches often give similar answers for large samples but can differ noticeably for small samples or extreme priors.")
    r("Bayes' theorem", "example",
      "A medical example: a screening test for a disease has 99 percent sensitivity (true positive rate) and 95 percent specificity (true negative rate). The disease has 1 percent prevalence in the screened population. What is the probability that a person who tests positive actually has the disease? Using Bayes' theorem: P(disease | positive) = P(positive | disease) P(disease) / P(positive) = 0.99 times 0.01 / [0.99 times 0.01 + 0.05 times 0.99] = 0.0099 / 0.0594, about 16.7 percent. Despite a 99 percent sensitive test, a positive result implies only about a 1-in-6 chance of actually having the disease, because most positive tests come from false positives among the much larger uninfected population. This is why screening tests for low-prevalence conditions usually require confirmatory follow-up testing, and why physicians and patients often misinterpret positive results without explicit Bayesian reasoning.")
    r("Bayes' theorem", "misconception",
      "A common misconception is that Bayes' theorem requires assuming the prior is correct in some absolute sense; the theorem is a mathematical identity, and any prior choice gives a self-consistent inference, with the choice of prior being a separate epistemological question. Another misconception is that the prosecutor's fallacy (treating the probability of evidence given innocence as the probability of innocence given evidence) is an obscure error; in fact, it appears repeatedly in courtroom misinterpretation of DNA evidence, in medical diagnosis, and in everyday risk assessment. People also sometimes assume that Bayes' theorem requires sophisticated math; the natural-frequency formulation is highly accessible and easy to teach. Finally, the assumption that Bayesian updating always converges quickly to the truth is false in some pathological cases (when priors place zero weight on the truth, when models are misspecified, when data are dependent in unmodeled ways), highlighting that Bayesian inference is a rigorous tool but not a magic bullet.")

    # ---- Markov chains ----
    r("Markov chains", "comparison",
      "Markov chains differ from general stochastic processes in obeying the Markov property: the future depends only on the current state, not on the path that led there. This memoryless property simplifies analysis and computation enormously. Compared with deterministic dynamical systems, Markov chains incorporate randomness in transitions but otherwise have similar concepts of trajectories, fixed points (now stationary distributions), and cycles. Compared with continuous-time stochastic processes like Brownian motion, discrete-time Markov chains have at most countable state spaces and integer time steps, making them more tractable for many applications. Compared with hidden Markov models, where the underlying chain is not directly observable but produces observable emissions, ordinary Markov chains have observable states. Compared with higher-order Markov processes, where the next state depends on multiple past states, ordinary first-order chains are a special case but can usually represent higher-order processes by enlarging the state space.")
    r("Markov chains", "mechanism",
      "A Markov chain works through a transition matrix P whose entry P_ij is the probability of moving from state i to state j in one time step. Starting from an initial distribution over states, the distribution at time t is given by left-multiplication by the t-th power of P. The Markov property means future evolution is fully determined by the current distribution and P, with no need to remember the history. For finite irreducible aperiodic Markov chains, there exists a unique stationary distribution pi satisfying pi P = pi; the chain converges to pi from any starting distribution, with the rate determined by the spectral gap of P. The mechanism extends to infinite state spaces (where convergence is more subtle), to continuous time (continuous-time Markov chains characterized by transition rates), and to Markov decision processes (which add actions and rewards to model decision making under uncertainty).")
    r("Markov chains", "misconception",
      "A common misconception is that Markov chains lack memory in the sense that they are 'forgetful'; in fact, all the information about the past relevant for predicting the future is encoded in the current state, so designing the state space appropriately can capture arbitrarily complex dependencies. Another misconception is that Markov chains always converge to a unique stationary distribution; reducible chains (with isolated state subsets) and periodic chains (that cycle through state subsets in fixed patterns) do not converge, and chains on infinite state spaces may have transient or null recurrent behavior with no proper stationary distribution. People also sometimes assume that the Markov property is uncommon in real data; in fact, many physical, biological, and computational systems are well-approximated as Markov, and even non-Markovian systems can often be embedded in larger Markov processes. Finally, the assumption that Markov chains are simple and linear misses the rich theory connecting them to spectral analysis, mixing times, electrical networks, and sophisticated tools across mathematics.")

    # ---- the Monty Hall problem ----
    r("the Monty Hall problem", "mechanism",
      "The Monty Hall problem asks: a contestant on a game show chooses one of three doors, one of which conceals a prize and the other two conceal goats. The host, who knows what is behind each door, opens one of the unchosen doors to reveal a goat, then offers the contestant the option to switch to the other unopened door. Should the contestant switch? Marilyn vos Savant's famous answer (yes, switching wins the prize 2/3 of the time) drew widespread disbelief but is correct. The mechanism: the contestant's initial choice has a 1/3 probability of being the prize door. The remaining 2/3 probability is distributed between the two other doors. After the host opens one of those two and reveals a goat, the entire 2/3 probability is concentrated on the single remaining unopened door, because the host's action is informative: the host always chooses to open a goat door, so the host's choice depends on the prize location and updates the probability distribution.")
    r("the Monty Hall problem", "comparison",
      "The Monty Hall problem differs from the related but distinct three-prisoners problem and several superficially similar puzzles. In all such problems, the key is the conditional structure of how information is revealed: does the revealing party have inside knowledge they use to constrain the reveal, or is the reveal random? In Monty Hall, the host's deliberate avoidance of the prize door makes the reveal informative and tilts the posterior. Compared with naive symmetry arguments that suggest the two unopened doors should be 50/50 after one is opened, the Monty Hall problem shows that conditional probability requires careful tracking of what generates the observed evidence, not just what the evidence is. Compared with Bayesian reasoning more generally, Monty Hall is a clean teaching example of how the likelihood (the host's behavior given the prize location) shapes the posterior. The puzzle generalizes: with n doors and the host opening n - 2 goats, switching wins (n - 1)/n of the time.")
    r("the Monty Hall problem", "significance",
      "The Monty Hall problem matters as a teaching example because it cleanly illustrates how naive intuitions about probability fail when conditional information is involved, and how careful Bayesian reasoning produces the correct answer. The puzzle is a regular feature of probability and statistics courses, because students who understand it tend to develop more reliable intuitions about conditional probability in general. The same kind of reasoning error (failing to condition properly on the way evidence is generated) appears in real-world contexts: medical test interpretation, expert witness testimony, evaluation of forensic evidence, and many cases of statistical reasoning in journalism. The vehemence with which many people initially rejected the correct answer (including holders of mathematics PhDs writing letters to dispute Marilyn vos Savant) is an instructive lesson in how strong our incorrect intuitions about probability can be, and in the value of explicit calculation over reflexive intuition for these kinds of problems.")

    # ---- Simpson's paradox ----
    r("Simpson's paradox", "definition",
      "Simpson's paradox is a phenomenon in which a trend appearing in several groups of data reverses or disappears when the groups are combined. For example, two treatments may each appear better on a per-group basis but the combined data shows the opposite. The paradox arises when a confounding variable (the group label) is correlated with both the treatment assignment and the outcome, so aggregating across groups mixes effects that should be separated. A famous real example is the 1973 University of California, Berkeley graduate admissions data: aggregated, men were admitted at higher rates than women, suggesting bias against women, but examination by department showed that women applied disproportionately to more selective departments and within each department were admitted at slightly higher rates than men. The aggregated number combined the selectivity confounder with the actual admission rates, producing a misleading summary. Simpson's paradox is a classic warning about the dangers of analyzing aggregated data without considering the structure underlying the aggregation.")

    # ---- regression analysis ----
    r("regression analysis", "definition",
      "Regression analysis is a set of statistical methods for estimating the relationships between a dependent (outcome) variable and one or more independent (predictor) variables. Linear regression, the simplest and most common form, fits a linear function y = beta_0 + beta_1 x_1 + ... + beta_p x_p + epsilon to data, where the betas are coefficients to be estimated and epsilon is an error term capturing variation not explained by the predictors. Coefficients are typically estimated by ordinary least squares (minimizing the sum of squared residuals), which has closed-form solutions and well-developed inferential theory. Regression generalizes to logistic regression (for binary outcomes), Poisson regression (for count data), Cox regression (for survival times), and many other forms. Modern variants include regularized regression (ridge, lasso) for high-dimensional data, nonparametric regression (splines, kernel methods, neural networks) for nonlinear relationships, and Bayesian regression for incorporating prior knowledge.")
    r("regression analysis", "significance",
      "Regression analysis matters because it provides one of the most widely used tools for prediction, inference, and causal analysis in science, business, and policy. In observational studies, regression adjusts for measured confounders to estimate associations more cleanly than raw comparisons. In experimental settings, regression with random assignment can isolate causal effects of treatments. In prediction, regression and its modern extensions form the backbone of recommendation systems, credit scoring, demand forecasting, and many other applications. Regression coefficients have the convenient interpretation as the change in the outcome per unit change in the predictor (holding others constant), making results communicable. The technique scales to thousands of predictors with regularization and to nonlinear relationships with appropriate basis expansions, making it remarkably flexible. At the same time, regression has well-known pitfalls (collinearity, omitted variable bias, model misspecification, extrapolation outside data range) that require careful attention; understanding these is part of statistical literacy.")

    # ---- hypothesis testing ----
    r("hypothesis testing", "comparison",
      "Hypothesis testing differs from estimation in framing the question as a binary decision (reject or fail to reject a null hypothesis) rather than a quantitative summary of plausible parameter values. Compared with confidence intervals, hypothesis tests provide a yes/no answer about a specific value, while confidence intervals provide a range of values consistent with the data. The two are closely related: a 95 percent confidence interval excluding a value corresponds to rejecting that value at the 0.05 level in a two-sided test. Compared with Bayesian model selection (using Bayes factors or posterior probabilities), hypothesis testing is more procedural and avoids prior specification but also lacks the direct interpretation of how much evidence the data provide. Compared with cross-validation in machine learning (which evaluates predictive performance on held-out data), hypothesis testing focuses on parameter inference within a specified model rather than on out-of-sample prediction. Different methods suit different goals: hypothesis testing for confirmatory analysis, estimation for descriptive summaries, prediction for engineering applications.")
    r("hypothesis testing", "misconception",
      "A common misconception is that statistical significance equals practical importance; with large samples, tiny effects can be statistically significant but practically meaningless. Another misconception is that failing to reject the null proves the null; absence of evidence is not evidence of absence, and underpowered studies routinely fail to detect real effects. People also commonly misinterpret p-values as the probability the null is true (it is the probability of the data given the null), and misinterpret 0.05 thresholds as a meaningful boundary rather than an arbitrary convention. The 'file drawer problem,' where significant results are published while null results stay unpublished, biases the literature toward significant findings. Pre-registration of hypotheses and analyses combats this by committing to specific tests in advance. The replication crisis in psychology, biomedicine, and other fields has highlighted how easily classical hypothesis testing produces unreliable results when applied carelessly, leading to ongoing reform of statistical practice.")
    r("hypothesis testing", "significance",
      "Hypothesis testing matters because it provides a standardized framework for evaluating specific claims against data, with quantifiable error rates. Despite its limitations, hypothesis testing remains central to drug approval (regulatory frameworks specify p-value thresholds for efficacy), quality control (acceptance sampling and process monitoring rely on hypothesis tests), scientific publication (peer review often expects significance tests), and many other contexts where binary decisions must be made under uncertainty. The framework's discipline (specifying hypotheses and analysis plans before seeing data, controlling error rates) is valuable when followed properly. Modern reform of statistical practice includes emphasizing effect sizes alongside p-values, reporting confidence intervals, pre-registering hypotheses, and using multiple analytical approaches to triangulate findings. The deeper lesson is that statistical inference is hard, that any single tool has limitations, and that meaningful conclusions require careful study design, transparent reporting, and substantive scientific judgment beyond mechanical application of statistical procedures.")

    # ---- confidence intervals ----
    r("confidence intervals", "mechanism",
      "A confidence interval is computed from sample data using a procedure with a specified long-run coverage rate. For a 95 percent confidence interval for a mean, the procedure is: compute the sample mean and standard error, then take the sample mean plus and minus 1.96 times the standard error (using the standard normal critical value, or t-distribution critical value for small samples). The mechanism by which this works is that the sample mean (or appropriate test statistic) has a known sampling distribution under repeated sampling, and the procedure is designed so that 95 percent of intervals constructed this way will contain the true parameter value across the long run of repeated samples. The mechanism extends to confidence intervals for proportions, regression coefficients, variance ratios, and many other quantities, with the appropriate sampling distribution determining the critical value. Bootstrap methods estimate the sampling distribution by resampling from the data, providing confidence intervals when analytical formulas are intractable.")
    r("confidence intervals", "misconception",
      "A common misconception is that a 95 percent confidence interval has a 95 percent probability of containing the true parameter; the correct frequentist interpretation is that 95 percent of intervals constructed by the procedure contain the true parameter across repeated sampling, but for any specific interval the probability is either 0 or 1 (the interval either contains the true value or does not). Bayesian credible intervals, which do have the 95 percent probability interpretation given a prior, are conceptually different despite often coinciding numerically with frequentist intervals. Another misconception is that the width of a confidence interval reflects how confident we are in our estimate; in fact, the width reflects the precision of the estimate (smaller width with more data), while the confidence level (95 percent vs. 99 percent) is set by the analyst. People also sometimes assume that any value outside the confidence interval is 'rejected'; the duality with hypothesis tests means values outside the interval would be rejected at the corresponding significance level, but the interval itself does not reject anything.")
    r("confidence intervals", "significance",
      "Confidence intervals matter because they communicate uncertainty in estimates more informatively than point estimates alone or binary hypothesis tests. A point estimate without a confidence interval gives no sense of precision; an interval immediately reveals whether the estimate is sharp or vague. Many scientific reporting standards now recommend or require confidence intervals alongside p-values, in part because intervals make practical significance more visible: an effect with a wide confidence interval extending across zero is not clearly different from an effect close to zero, even if the p-value happens to fall below 0.05. Intervals also support meta-analysis, where results across studies must be combined, by allowing weighting by precision. In policy contexts, intervals communicate the range of plausible outcomes to inform decisions under uncertainty. Despite the technical distinctions from probability statements about parameters, intervals serve as a practical and accessible tool for quantifying statistical uncertainty.")
    r("confidence intervals", "example",
      "An example: a survey of 1000 voters finds 52 percent supporting a candidate. Using the standard formula, the standard error is sqrt(0.52 times 0.48 / 1000) = 0.0158, and the 95 percent confidence interval is 0.52 plus or minus 1.96 times 0.0158 = (0.489, 0.551), or about 49 percent to 55 percent. This illustrates that a 52 percent point estimate does not allow us to confidently declare a majority preference; the interval crosses 50 percent, so a 'tied race' is consistent with the data. Doubling the sample size to 2000 would shrink the standard error by sqrt(2) and the interval to about (0.498, 0.542); even with this larger sample, the interval is just barely above 50 percent. The example shows the practical use of confidence intervals to communicate not just what the data suggest but the range of plausible truths consistent with the data, with the width controlled by sample size.")

    # ---- sampling bias ----
    r("sampling bias", "definition",
      "Sampling bias occurs when the way a sample is drawn from a population systematically over- or under-represents some part of that population, producing estimates that do not generalize to the population as a whole. Common forms include selection bias (some population members are more likely to be sampled than others), nonresponse bias (those who decline to participate differ systematically from those who do), survivorship bias (only entities that survive some process are observed, omitting those that did not), self-selection bias (participants choose whether to be included based on factors related to the outcome), and convenience sampling (the sample consists of those easiest to reach, who differ systematically from the broader population). Sampling bias affects all types of data collection, from polls and surveys to medical research, social science studies, and machine learning datasets, and is a leading reason that empirical studies fail to replicate or generalize.")
    r("sampling bias", "comparison",
      "Sampling bias differs from random sampling error, which is the inherent variability in estimates from finite samples even when sampling is unbiased. Sampling error shrinks with larger samples; sampling bias does not, because increasing the sample size of a biased procedure just produces a more precise but still biased estimate. Compared with measurement error (errors in recording or quantifying observations), sampling bias is about who is included rather than how observations are measured. Compared with confounding (which involves the relationships among variables within a sample), sampling bias is about the relationship between the sample and the population. Compared with publication bias (where results are selectively published based on outcomes), sampling bias arises at data collection rather than at dissemination. All these biases distort inference and require different mitigation: random sampling for selection bias, calibrated instruments for measurement error, randomized assignment for confounding, registered reports for publication bias.")

    # ---- probability distributions (normal, Poisson, binomial) - skipped no entries needed ----

    # ---- the prisoner's dilemma ----
    r("the prisoner's dilemma", "example",
      "The classical prisoner's dilemma scenario: two suspects are arrested for a joint crime and held in separate cells with no communication. Each is offered a deal: testify against the other (defect) or stay silent (cooperate). If both cooperate, both serve 1 year. If both defect, both serve 5 years. If one defects while the other cooperates, the defector goes free and the cooperator serves 10 years. Each prisoner reasoning individually concludes: if my partner cooperates, I get 0 by defecting versus 1 by cooperating, so defect; if my partner defects, I get 5 by defecting versus 10 by cooperating, so defect. Defection dominates regardless of what the partner does, so both defect and serve 5 years each, despite both serving only 1 year if they had cooperated. This is the dilemma: individually rational play produces a collectively worse outcome. Real-world analogs include arms races (where mutual disarmament beats mutual armament but each side gains by arming if the other disarms), pollution (each polluter benefits but everyone is worse off when all pollute), price wars, and overfishing.")

    # ---- game theory and Nash equilibrium ----
    r("game theory and Nash equilibrium", "mechanism",
      "Game theory analyzes situations of strategic interaction in which the outcome for each participant depends on the choices of all participants. A game is specified by a set of players, the strategies available to each, and the payoffs each receives for every combination of strategies. A Nash equilibrium is a profile of strategies, one per player, in which each player's strategy is a best response to the others': no player can improve their payoff by unilaterally changing strategy. The equilibrium concept captures a stable outcome in the sense that, given everyone else's choices, no individual has incentive to deviate. Nash equilibria can be in pure strategies (each player chooses one specific action) or in mixed strategies (each player chooses a probability distribution over actions). In finite games, mixed-strategy Nash equilibria always exist (Nash's theorem). The framework extends to games with incomplete information, sequential moves, and many players, with refinements like subgame-perfect equilibrium, Bayesian Nash equilibrium, and evolutionary stability.")
    r("game theory and Nash equilibrium", "example",
      "A simple example is the rock-paper-scissors game between two players. Each player chooses rock, paper, or scissors simultaneously, with rock beating scissors, scissors beating paper, and paper beating rock; the loser pays the winner one dollar, with ties paying nothing. If a player always chose rock, the opponent would always choose paper and win every time. The unique Nash equilibrium is for both players to randomize uniformly: choose each option with probability 1/3. At this mixed equilibrium, the expected payoff is zero for both players, and each player is indifferent among the three actions because the opponent's randomization makes each action equally good. Any deviation from the uniform mix invites exploitation by the opponent. The example illustrates how Nash equilibrium can require randomization in zero-sum games, and how the equilibrium concept captures stability under self-interested play. Real-world games (auctions, business strategy, traffic patterns, evolutionary biology) use the same concepts in more complex settings.")

    # ---- convex optimization ----
    r("convex optimization", "definition",
      "Convex optimization is the branch of mathematical optimization concerned with minimizing convex functions over convex sets. A function is convex if the line segment between any two points on its graph lies on or above the graph; equivalently, its second derivative (or Hessian, in higher dimensions) is non-negative everywhere. A set is convex if it contains the line segment between any two of its points. Convex problems have the crucial property that any local minimum is automatically a global minimum, eliminating the difficulty in nonconvex problems where multiple local optima can trap optimization algorithms. Common convex problems include linear programming (linear objective and linear constraints), quadratic programming (quadratic objective with linear constraints), and second-order cone programming. Powerful algorithms (interior-point methods, gradient descent, ADMM) solve convex problems efficiently even at large scale, with convergence guarantees and theoretical analysis far stronger than for nonconvex problems.")
    r("convex optimization", "mechanism",
      "Convex optimization works through algorithms that exploit convexity to find global optima with provable convergence rates. Gradient descent iteratively moves in the direction of steepest descent, with step sizes chosen by line search or scheduled decay; for convex problems, gradient descent converges to a global minimum with rate depending on smoothness and strong convexity. Newton's method uses second-order information (Hessian) to take more efficient steps, with quadratic convergence near the optimum at the cost of computing and inverting the Hessian. Interior-point methods handle inequality constraints by adding barrier functions that diverge at constraint boundaries, then solving a sequence of unconstrained or equality-constrained subproblems with the barrier strength gradually reduced. Stochastic methods (SGD and variants) use noisy gradient estimates from random data subsets, making them suitable for huge datasets. The structure of convex problems guarantees that these algorithms find the global solution rather than getting stuck in local minima.")
    r("convex optimization", "comparison",
      "Convex optimization differs from nonconvex optimization in the strength of guarantees: convex problems have a single global optimum reachable by efficient algorithms with convergence rates, while nonconvex problems can have many local optima, saddle points, and flat regions that trap optimization algorithms. Compared with linear programming (a special case), general convex optimization handles nonlinear objectives and constraints. Compared with combinatorial optimization (where variables are discrete and feasible sets are not convex), convex optimization works with continuous variables and benefits from convex analysis tools. Compared with global optimization techniques for nonconvex problems (genetic algorithms, simulated annealing, branch-and-bound), convex methods are dramatically faster and more reliable but apply only to a restricted (though wide) class of problems. Many nonconvex problems can be approximated by convex relaxations, providing bounds and starting points for further analysis even when an exact solution is intractable.")
    r("convex optimization", "example",
      "Linear regression with regularization is a clean convex optimization example. Given data (x_i, y_i), find coefficients beta minimizing the sum of (y_i - x_i^T beta)^2 plus a regularization term lambda times norm(beta)^2 (ridge regression) or lambda times sum of |beta_j| (lasso). The objective is convex in beta: the squared loss is convex, and both ridge and lasso penalties are convex. Ridge has a closed-form solution beta = (X^T X + lambda I)^(-1) X^T y. Lasso has no closed form but is solved by efficient algorithms (coordinate descent, FISTA) that exploit convexity to find the global optimum. The same convex framework supports logistic regression (convex log-loss), support vector machines (convex hinge loss with L2 regularization), and many other machine learning models. The convex structure ensures that the same algorithm finds the same solution from any starting point, and that the optimization problem is well-posed and tractable even at scale.")
